### PR TITLE
Prevent random dispatcher deadlocks

### PR DESCRIPTION
**Pull request by ltetak**
## What does the pull request do?
It happens from time to time that the rendering stops (tested on macOS but probably can happen on any platform). The culprit seems to be the Dispatcher does not keep properly the info if the impl has been signaled or not.

## What is the current behavior?
_signaled property is true but the native implementation does nothing which breaks the loop

## What is the updated/expected behavior with this PR?
don't break the loop

## How was the solution implemented (if it's not obvious)?
I could not reproduce it 100% reliably but this seemed like the only place and it also makes no sense (to me) to reset the flag here since it was not signaled to the native impl.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/avalonia-docs with user documentation

### CODE REVIEW

**Comment by kekekeks** [comment]
1) the problem is most certainly elsewhere
2) this change will cause perf issues

Please, provide a repro app, since it might be app-specific.

**Comment by ltetak** [comment]
@kekekeks 100% repro steps. On any platform (tested on windows + mac)
1. Open Avalonia solution + ControlCatalog project
2. Open Dispatcher.Queue.cs
3. Make sure CanQueryPendingInput is false (override on windows, mac is false already - that makes it platform specific)
4. put breakpoint on line 195 + run
https://github.com/ltetak/Avalonia/blob/9f5a1027fd109d59b5519b5146c834e7b5c50668/src/Avalonia.Base/Threading/Dispatcher.Queue.cs#L195
This will make the condition true (because of the delay). And set the _signaled to true.
5. continue debugging - the Dispatcher is dead now

**Comment by kekekeks** [comment]
Hmmm, it seems that it's a leftover code from the time when foreground and background processing shared the same state flag. So now requesting background processing in that particular scenario effectively disables the foreground one.

**Review by kekekeks — APPROVED** [review]

**Comment by cfnfy** [comment]
@ltetak - Thank you so much for finding and fixing this issue!

**Pull request merged**
