### PR TITLE
Avalonia single project support

### PR DESCRIPTION
**Pull request by maxkatz6**
## What does the pull request do?

Makes it easier to create a single project for windows, macos, ios and android platforms.
With "NET8.0" it's possible to include "net8.0-browser" as well now.
But it still has problems with linux target - .NET doesn't support yet nor alias it.

What's working:
- Platform specific folders, including bootstrap projects.
- Rider integration (at least EAP), including project build, debug and run.

What does not work:
- Referencing of correct platform specific nuget packages. **Developers need to reference** `Avalonia.iOS/Browser/Android/Desktop` **manually**.
- ~Proper integration with VS (everything seems to work except VS doesn't understand how to run mobile projects).~ Fixed
- Linux targets. But it's possible to create a "Desktop" target (i.e. "net8.0" TFM)
- Windows MSIX support (out of scope).
- Special resource types that can be converted to the platform specific ones. For instance, icons defined once and converted to each platform automatically. Instead, developers need to convert them manually and put to the platform specific folder.

Disclaimer: Avalonia team still recommends multiple projects approach, which is available in our templates. It is more verbose, but way more flexible in a long term. Also doesn't have stoppers with linux projects.

## What is the updated/expected behavior with this PR?

MAUI, Tizen and MSBuild.SDK.Extras source codes were used as a reference.

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0026996-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-nightly/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0027018-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-nightly/nuget/v3/index.json) [PRBUILDID]

**Comment by maxkatz6** [comment]
Potentially can be useful on mobile only. But blocked by inconsistency in the .NET SDK itself.
Possibly can be reopened in the future.

**Comment by maxkatz6** [comment]
Resurrecting this PR. I want to have this feature at least for the internal use.

**Review by kekekeks — APPROVED** [review]
The entire single project concept is cursed, but PR looks good.

**Pull request merged**
