### PR TITLE
Port of WPF StackPanel and fixes to layout constraints

### LINKED ISSUE #2746: Grid layout issues with elements bigger than constraint size
After updating to newer Avalonia that has WPF `Grid` integrated some controls in my app started shifting content in a weird way. In the beginning I thought this may be how WPF `Grid` works, but same XAML works just fine in WPF (also this XAML can just be pasted into WPF or Avalonia, as it works in both).

```xaml
<Grid Width="120" Height="120">

        <Border BorderBrush="#292e34" BorderThickness="1" Background="#494B4D" Margin="2">

            <Grid >
                <Grid.RowDefinitions>
                    <RowDefinition Height="*"/>
                    <RowDefinition Height="Auto"/>
                    <RowDefinition Height="Auto"/>
                </Grid.RowDefinitions>

                <DockPanel Grid.Row="0">

                    <Border>
                        <Border.Background>
                            <SolidColorBrush Color="Red" />
                        </Border.Background>
                        <Rectangle Width="16" Height="16" Fill="Blue" />
                    </Border>
                </DockPanel>

                <Rectangle Grid.Row="1" Height="1" Fill="#292e34" />

                <Border Grid.Row="2" Background="#494B4D" Padding="2">
                    <TextBlock HorizontalAlignment="Center" Text="Very very very very very very very long text" />
                </Border>

            </Grid>

        </Border>

    </Grid>
```

Avalonia:
image

WPF:
image

Any idea what might be going on there? Also if I add `MaxWidth="112"` to `TextBlock` it looks the same as WPF.

cc: @jmacato as you ported `Grid` from WPF

### PR DESCRIPTION
**Pull request by wieslawsoltes**
## What does the pull request do?

Ports the StackPanel control from dotnet/wpf repository.

## What is the updated/expected behavior with this PR?

StackPanel's behavior should now be inline with WPF's.

## Checklist

- [x] Added unit tests (if possible)?
- [x] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

## Breaking changes

None in the API.

## Fixes

Fixes #2746

### CODE REVIEW

**Comment by wieslawsoltes** [comment]
For future reference: https://github.com/AvaloniaUI/Avalonia/pull/2644#issuecomment-505194785

**Comment by grokys** [comment]
Also related: https://github.com/AvaloniaUI/Avalonia/issues/2746#issuecomment-515618630

**Comment by grokys** [comment]
@wieslawsoltes I've updated this branch with fixes to make tests pass (based on results from wieslawsoltes/WpfUnitTests#1) and also added a test for #2746 which is now fixed in this branch.

**Comment by wieslawsoltes** [comment]
> @wieslawsoltes I've updated this branch with fixes to make tests pass (based on results from [wieslawsoltes/WpfUnitTests#1](https://github.com/wieslawsoltes/WpfUnitTests/pull/1)) and also added a test for #2746 which is now fixed in this branch.

This is great!

**Pull request merged**
