### PR TITLE
Remove Line Dash from Border

### LINKED ISSUE #9942: Border BorderDashArray is disabled when BorderThickness is a non uniform value.
**Describe the bug**
When setting `BorderThickness` to a non uniform value, the border stops being a dashed border.

**To Reproduce**

1. Create the following View:

`BorderIssueShowcaseView.axaml`:

```xaml
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d" d:DesignWidth="400" d:DesignHeight="400">
	
	<Border Width="200" Height="100" BorderBrush="black"
	        BorderThickness="5 4"
	        BorderDashArray="5,1">
		
		<TextBlock Text="Hello, World!" Margin="10" />
	</Border>
</UserControl>
```

2. Open IDE previwer or Run the application

**Expected behavior**

Each segment of the border would appear dashed.

**Screenshots**

Uniform Thickness:

HDMI-0-20230110-010914

Non Uniform Thickness:

HDMI-0-20230110-010921

**Desktop (please complete the following information):**

- OS: Linux (Arch)
- Avalonia Version: 0.10.18

**Additional context**

I noticed this issue when I wanted to display grid lines in Grid and have every other row have dashed bottom border giving the grid alternating border shapes similar to the Samsung Calendar app looks. I honestly think a better api should be provided for native grid lines instead of directly creating the borders myself.

f75d589d-9c1a-4783-85b6-ea0db2a6b198

### LINKED ISSUE #11424: Remove Dashed Line Properties from Border
**Is your feature request related to a problem? Please describe.**

In preparation for BackgroundSizing, dashed line properties need to be removed from Border. This was first discussed here: 
https://github.com/AvaloniaUI/Avalonia/issues/9946#issuecomment-1376650980.

**Additional context**

I think this must be done before 11.0 to avoid breaking changes in the 11.0 series.

@avaloniaui-team Thoughts?

### PR DESCRIPTION
**Pull request by robloo**
## What does the pull request do?

Per #11424, Removes line dash support (and deletes related properties) from `Border`. This is necessary in preparation for `BackgroundSizing` https://github.com/AvaloniaUI/Avalonia/issues/9946#issuecomment-1376650980.

Any apps needed line dashes will need to fall back to using Shapes directly (as done in WPF/WinUI).

## What is the current behavior?

Border supports dashed lines for its BorderBrush. This is NOT supported in WPF/WinUI where it is only possible to do this on shapes.

## How was the solution implemented (if it's not obvious)?

Related properties are now removed and no longer passed to the border render helper. Border render helper is not modified as it will require deeper changes in the future so make sense to do it later.

## Checklist

- ~[ ] Added unit tests (if possible)?~
- ~[ ] Added XML documentation to any related classes?~
- ~[ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation~

## Breaking changes

Yes, border line dash properties are now removed. This will break compilation of any apps currently using this feature.
 * `BorderDashArrayProperty`
 * `BorderDashOffsetProperty`
 * `BorderLineCapProperty`
 * `BorderLineJoinProperty`
 * `BorderDashArray`
 * `BorderDashOffset`
 * `BorderLineCap`
 * `BorderLineJoin`

## Obsoletions / Deprecations

None (with revised PR all properties are deleted)

## Related/Fixed issues

 * Undoes https://github.com/AvaloniaUI/Avalonia/pull/6836
 * Closes #11424 
 * Closes #9942 (won't fix)

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0035519-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by Gillibald** [comment]
Dashed properties where never part of an stable release so I think we can just just remove them without marking them being obsolete.

**Comment by robloo** [comment]
@Gillibald Yea, I saw that mentioned in the issue. However, I thought this was safer and would cause less friction. Since you brought it up again though, I'll remove them completely.

**Comment by maxkatz6** [comment]
Yes, better to remove it now. Especially right before the RC.

**Review by maxkatz6 — APPROVED** [review]

**Comment by robloo** [comment]
@Gillibald @maxkatz6 Removed and PR updated

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0035522-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Pull request merged**
