### PR TITLE
Vortice.Windows migration.

### PR DESCRIPTION
**Pull request by amerkoleci**
## What does the pull request do?
Migrates from SharpDX to Vortice.Windows

## What is the current behavior?
Uses SharpDX for D2D1, WIC and DirectWrite

## What is the updated/expected behavior with this PR?
Everything should work as before, when using SharpDX

## Checklist

- [x] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Breaking changes
This changes whole windows rendering part.

### CODE REVIEW

**Comment by amerkoleci** [comment]
All tests works now!

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019804-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by amerkoleci** [comment]
Ok, we should be fine now, you can merge if you want.

Thanks

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019823-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by danielmayost** [comment]
why?

**Comment by amerkoleci** [comment]
> @amerkoleci why?

This was mine 3rd PR for Vortice migration and received 0 feedback, so I won't bother migrating anymore :D

**Comment by Gillibald** [comment]
We had some internal discussion about this just before you closed this. Just keep in mind that we might be busy and it takes some time to give feedback.

**Comment by amerkoleci** [comment]
> We had some internal discussion about this just before you closed this. Just keep in mind that we might be busy and it takes some time to give feedback.

I can immagine but PR #5831 broked entire integration, this PR is in pending state as well: https://github.com/AvaloniaUI/Avalonia/pull/7753

And I can immagine being busy, don't worry, but without feedback is difficult for me to keep PR updated with master branch.

**Comment by grokys** [comment]
You did only give us 3 days from "this is ready" to "closing due to lack of feedback" - sorry but it can sometimes take us a long time to give feedback on PRs, especially ones that change our core infrastructure like this.

> PR https://github.com/AvaloniaUI/Avalonia/pull/5831 broked entire integration

https://github.com/AvaloniaUI/Avalonia/pull/5831#issuecomment-1099146051

**Comment by amerkoleci** [comment]
> You did only give us 3 days from "this is ready" to "closing due to lack of feedback" - sorry but it can sometimes take us a long time to give feedback on PRs, especially ones that change our core infrastructure like this.
> 
> > PR #5831 broked entire integration
> 
> [#5831 (comment)](https://github.com/AvaloniaUI/Avalonia/pull/5831#issuecomment-1099146051)

Yeah sorry, Avalonia is huge project and its difficult to keep track of all issues/PR, I can immagine being difficult for you as well, sorry for closing very quickly :) I would gladly submit new PR is it can give benefit to the project.

**Pull request closed without merging**
