### PR TITLE
Grammatical corrections to product names

### PR DESCRIPTION
**Pull request by mikeirvingweb**
Grammatical corrections to product names: XCode -> Xcode, .Net -> .NET, Javascript -> JavaScript, MacOS -> macOS, MacOs -> macOS

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019139-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019139-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by jmacato — APPROVED** [review]
LGTM, Thanks! :)

**Comment by grokys** [comment]
Removed `backport-candidate` as this PR doesn't apply cleanly to stable branch and fixes are internal only.

**Pull request merged**
