### PR TITLE
Release mouse capture when toplevel closed

### LINKED ISSUE #3182: Popup doesn't release capture when closed
ComboBox popup (or may be any toplevel window) doesn't release capture when closed, thus making next mouse click invalid and not recognized by the system.
For example in Control catalog try switch between dark and light themes with the dropdown.
Once theme selected, next click on dropdown will not open the dropdown popup, but need a second click.

### PR DESCRIPTION
**Pull request by donandren**
## What does the pull request do?

Release mouse capture when toplevel closed

## What is the current behavior?

mouse capture is not released when toplevel is closed

## What is the updated/expected behavior with this PR?

fix the issue

## Checklist

- [x] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

## Fixed issues

Fixes #3182

### CODE REVIEW

**Comment by danwalmsley** [comment]
@donandren would like to get merched soon, can a unit test be added?

**Comment by donandren** [comment]
@danwalmsley  sure i'll try add unit test in the next days

**Comment by kekekeks** [comment]
See https://github.com/AvaloniaUI/Avalonia/pull/3158

**Comment by donandren** [comment]
> See #3158

#3158 partially resolves the issue, but still `PointerCaptureLost `is not raised

**Comment by kekekeks** [comment]
Mouse/touch devices now are getting disposed in platform toplevel implementations: https://github.com/AvaloniaUI/Avalonia/blob/master/src/Windows/Avalonia.Win32/WindowImpl.cs#L487

Disposing a device releases any captures on its pointers

**Comment by grokys** [comment]
@donandren do you agree that #3158 solves this? Can we close this PR?

**Comment by donandren** [comment]
yea this pr is no longer needed

**Pull request closed without merging**
