### PR TITLE
Window Icons. Fixes #548

### LINKED ISSUE #548: Icon for application
Add new property `Icon` to `Window` tag:

`<Window Icon="youricon.ico"></Window>`

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Fixes #548.

### CODE REVIEW

**Comment by grokys** [comment]
Thanks Jeremy - mostly looks good but I'm not sure about having a separate type for icons - they're bitmaps after all, and it seems that WPF just uses an `ImageSource` for the [`Window.Icon` property](https://msdn.microsoft.com/en-us/library/system.windows.window.icon.aspx) and indeed assigning a .png file to WPF's `Window.Icon` works fine.

Would it be possible to do something similar here?

**Comment by jkoritzinsky** [comment]
Because of our split of our windowing and render systems it becomes more difficult. I have an idea that can try out to use the same types. I'll see if I can get that to work.

**Comment by jkoritzinsky** [comment]
@grokys I think I figured out a way to do it. Take a look.

**Comment by grokys** [comment]
Sorry for the delay, will take a look soon!

**Comment by grokys** [comment]
So from this we only support "normal" image files (.png, .jpg, .bmp) etc for icons rather than .ico files? That's fine for now (and indeed probably the only way to do it x-plat), just wanted to check.

**Comment by jkoritzinsky** [comment]
I think we have support for .ico on windows (since DirectX WIC has a decoder for ICO), but I haven't tested it.

**Comment by grokys** [comment]
Ah! I didn't know that. Ok if that's the case even better. I'll guess we need some sort of way to extract the different icon sizes from the .ico in future, but that can wait.

**Comment by grokys** [comment]
@jkoritzinsky this seems to have broken ControlCatalog somehow - only the first two pages show. Did you want to try and work out what caused it, or do you want me to? I want to finish item virtualization first so it might be a little while...

**Comment by jkoritzinsky** [comment]
I'm going to close this for now and send a new PR later.

**Pull request closed without merging**
