### PR TITLE
Win32 - Fix Window Frame Size and Position issues.

### LINKED ISSUE #11411: ExtendClientAreaToDecorationsHint=True, ClientArea gets shifted to the left.
**Describe the bug**
When the `ExtendClientAreaToDecorationsHint` is set to `True`, it seems the Client Area gets shifted over to the left by a tiny bit. This is shown in the screenshots (I made a border white so you can see it clearer).

**To Reproduce**
Set `ExtendClientAreaToDecorationsHint` to `True`

**Expected behavior**
The client area not to get shifted to the left (probably by the amount it saved by extending?)

**Screenshots**
Extend to Decorations True:
image

Extend to Decorations False:
image

**Desktop (please complete the following information):**
- OS: Windows 11

### LINKED ISSUE #14604: In WindowBase.PositionChanged event handler Point value is wrong
## Describe the bug
The value of `PixelPointEvenArgs.Point` inside event handler is wrong.

## To Reproduce

1. Create new Avalonia C# project.
2. In `MainWindow.axaml.cs` add line in constructor to output argument value and actual value:

```c#
    public MainWindow()
    {
        InitializeComponent();
        PositionChanged += (s, e) => Debug.WriteLine($"Position={e.Point}, actual={Position}");
        //Position = new(666, 666); // optional
    }
```

3. Run and observe debugger "Output" window.
4. My outputs are

```
Position=190, 213, actual=188, 182
or
Position=668, 697, actual=666, 666
```

## Expected behavior
I expect `e.Point` value to be equal to actual window `Position`.

## Environment 

- OS: Windows 11
- Avalonia-Version: 11.0.9

## Additional context
I tried to use `PositionChanged` event to store position of window in normal state, see #14517 ,but unfortunately discovered a new frustrating bug in Avalonia.

### LINKED ISSUE #16454: 11.1.0 - Window position is incorrect when the SystemDecorations property is set to BorderOnly
### Describe the bug

When you set the SystemDecorations property to BorderOnly, the window doesn't appear at the specified position, but with an offset

image

The window is shown correctly in version 11.0.11

### To Reproduce

Clone [the sample repository](https://github.com/pavelovcharov/avalonia-v11.1.0-window-incorrect-position), build the solution and run it.

### Expected behavior

Window should appear at the specified position

### Avalonia version

11.1.0

### OS

Windows

### Additional context

In version 11.0.11, the actual position of the window also depends on the order in which the Position and SystemDecorations properties are set

### LINKED ISSUE #16503: Caption Buttons disappearing
### Describe the bug

If you use this markup, the caption buttons are not visible.

`WindowState="Maximized"
SystemDecorations="Full"
ExtendClientAreaToDecorationsHint="True"`

image

### To Reproduce

Add this code in window markup

`WindowState="Maximized"
SystemDecorations="Full"
ExtendClientAreaToDecorationsHint="True"`

### Expected behavior

The caption buttons will be visible and the window will be expanded to maximized.

image

### Avalonia version

11.1.1

### OS

Windows

### Additional context

_No response_

### LINKED ISSUE #16529: First time window without borders has incorrect position
### Describe the bug

This window is still shifted as if it has the borders and the title bar. For example here is a pink window without borders and title bar 

        SystemDecorations = SystemDecorations.None
       CanResize = false

I attempt to start this window at position (0,0).

image

It is still shifted horizontally and vertically as if it has title bar and border. 

Then if I hide the window and show it again, it is displayed at a correct position. 

### To Reproduce

Please, see above

### Expected behavior

The window should be displayed at a correct position specified by its Position property. 

### Avalonia version

11.1.1

### OS

Windows

### Additional context

Not sure if it started happening with 11.1.1 or was there before. I noticed it only now.

### PR DESCRIPTION
**Pull request by emmauss**
## What does the pull request do?
Our Window properties that rely on the window border/frame have inconsistent behavior on windows, esp. when compared to WPF. This pr ensures that the FrameSize and window Position doesn't change when decorations are changed, and client area is affected. Window Position and FrameSize now considers the whole window border, including the transparent border Windows apply to resizable windows. The following rules are enforced;
1. Updates to Position should not cause Frame Size to change
2. Updates to Width/Height should not cause Position to change
3. Updates to WindowState should ensure Frame properties of other states do not change
4. Updates to Decorations should not cause Frame properties of the current window state to change
    https://github.com/AvaloniaUI/Avalonia/issues/16529
    https://github.com/AvaloniaUI/Avalonia/issues/16454
5. PositionChanged event should report the Frame position
6. ExtendClient margins are calculated on updates to Window State
   https://github.com/AvaloniaUI/Avalonia/issues/16503

## What is the current behavior?
Window Position doesn't consider the transparent part of the border, only the visible part, which is usually just 1 pixel wide. This causes the window Position to change when client is extended to window frame, even though the window hasn't moved. This behavior also affects reported FrameSize, even though the window hasn't been resized. 
For normal windows with system decorations, setting system decorations to BorderOnly or None forces Frame to shrink to client area, instead of growing the client area like it is in WPF.

## What is the updated/expected behavior with this PR?
Window FrameSize and Position are only updated when there's a change in WindowState, when user updates Window.Position or when use resizes the window. They are kept unchanged when there's an update to ExtendedClient properties and SystemDecorations. FrameSize and Position will consider all parts of the window that the OS considers as part of the window decorations.

## Checklist

- [x] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/avalonia-docs with user documentation

## Fixed issues
Fixes https://github.com/AvaloniaUI/Avalonia/issues/16529
Fixes https://github.com/AvaloniaUI/Avalonia/issues/16454
Fixes https://github.com/AvaloniaUI/Avalonia/issues/16503
Fixes https://github.com/AvaloniaUI/Avalonia/issues/14604
Fixes https://github.com/AvaloniaUI/Avalonia/issues/11411

### CODE REVIEW

**Comment by maxkatz6** [comment]
@emmauss does it also close https://github.com/AvaloniaUI/Avalonia/issues/14604 and https://github.com/AvaloniaUI/Avalonia/issues/11411

**Comment by maxkatz6** [comment]
Also, do we need [this another PR](https://github.com/AvaloniaUI/Avalonia/pull/16593) from @TomEdwardsEnscape ?

**Comment by emmauss** [comment]
> @emmauss does it also close #14604 and #11411

Yes. I'll add them to the fix list

**Comment by emmauss** [comment]
> Also, do we need [this another PR](https://github.com/AvaloniaUI/Avalonia/pull/16593) from @TomEdwardsEnscape ?

It seems their pr only extends client when a show operation is done, and not when window state is changed. Just to be certain extendclient is always checked, we can have both changes in.

**Review by maxkatz6 — APPROVED** [review]

**Comment by josephmoresena** [comment]
Would this solve AvaloniaUI/Avalonia#11333?

**Comment by maxkatz6** [comment]
@josephmoresena it should. You can check that by using nighly build from https://github.com/AvaloniaUI/Avalonia/pull/16608#issuecomment-2293582298

**Comment by adirh3** [comment]
FYI this change introduced multiple issues with my `FullScreen` window, mostly the window shrinking when moving it between monitors with different resolutions/DPIs.
Will try to investigate and update/create PR for fix

**Pull request merged**
