### PR TITLE
fix font fallback back to normal

### LINKED ISSUE #3308: Font fallback funtionality is lost
in current master Font fallbacks are lost and default system font is used in case first font is not found:

try 
`<Window FontFamilty="Non existent Font, Times New Roman" ... > ...`

all child content will be rendered with default system font (Segoe UI on windows) instead `Times New Roman`  even if `Times New Roman` is present on the system.

expected:
 Font to fallback to system only after no matching font is found in `FontFamily` names list.

Font fallbacks was working until recently, look like #3195 has incidently removed the support for the fallbacks.
for reference this lines was making fallbacks work (For Skia):
https://github.com/Gillibald/Avalonia/blob/69c24dc99df33a7eb8ee544ccba0a465acd9a632/src/Skia/Avalonia.Skia/FormattedTextImpl.cs#L40-L50

### PR DESCRIPTION
**Pull request by donandren**
## What does the pull request do?

Fixes font fallback to find first matching font in FonFamily and only if not exist fallbacks to system default font

## What is the current behavior?

Font fallbacks to system default font after first attempt to try find matching font in FontFamily.FontNames

## What is the updated/expected behavior with this PR?

fixes the problem
## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

## Fixed issues

fixes #3308 

@Gillibald

### CODE REVIEW

**Comment by Gillibald** [comment]
Can you pls test #3234 this should fix the issue you were facing

**Comment by donandren** [comment]
@Gillibald #3234 fixes the issue for Skia, but not for Direct2D, feel free to cherry pick the direct2d commit from this pr

**Comment by Gillibald** [comment]
@donandren #3234 should now work for Direct2D1. I have added the same unit tests for the platform implementation and everything passes.

**Comment by donandren** [comment]
superseded by #3234, will close it when #3234 is merged

**Pull request closed without merging**
