### PR TITLE
Fix property registrations

### PR DESCRIPTION
**Pull request by wieslawsoltes**
## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

### CODE REVIEW

**Comment by wieslawsoltes** [comment]
Not sure about that name https://github.com/AvaloniaUI/Avalonia/pull/8114/commits/2d6bd60f691434e667cbbbdff933dfda9d4c0f69

**Comment by maxkatz6** [comment]
> Not sure about that name https://github.com/AvaloniaUI/Avalonia/commit/2d6bd60f691434e667cbbbdff933dfda9d4c0f69

Does this property even work with style setters? Before this PR

**Comment by wieslawsoltes** [comment]
> > Not sure about that name [2d6bd60](https://github.com/AvaloniaUI/Avalonia/commit/2d6bd60f691434e667cbbbdff933dfda9d4c0f69)
> 
> Does this property even work with style setters? Before this PR

I have no idea what that property is for and naming is confusing.

**Comment by MarchingCube** [comment]
@maxkatz6 @wieslawsoltes https://github.com/AvaloniaUI/Avalonia/pull/4051#issuecomment-636748247 :)

**Comment by wieslawsoltes** [comment]
This PR is ready for review

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0020342-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by robloo** [comment]
Yikes, surprised at some of these. Glad issues like this are getting fixed.

**Review by maxkatz6 — APPROVED** [review]

**Comment by danwalmsley** [comment]
note: backport had the property rename removed... its a breaking change.

**Pull request merged**
