### PR TITLE
Feature : Add DryIoc and Microsoft.Extensions.DependencyInjection

### PR DESCRIPTION
**Pull request by ChrisPulman**
## What does the pull request do?

Adds support for Splat DI - DryIoc and Microsoft.Extensions.DependencyInjection

## What is the current behavior?

Feature

## What is the updated/expected behavior with this PR?

Adds ability to easily add a different DI container to Avalonia.ReativeUI

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Breaking changes

New feature

### CODE REVIEW

**Comment by kekekeks** [comment]
Sorry, but the main repo is not the place for keeping support for every single DI framework ReactvieUI can work with. Consider creating a separate library or contributing a documentation page.

**Comment by ChrisPulman** [comment]
@kekekeks  Thank you for your consideration, we will discuss the best way forward for the continuation of support for people wanting to use Avalonia ReactiveUI with different DI containers.
Likewise we can't support every situation where ReactiveUI is possibly used.
I have for now published a nuget package which solves the immediate issue.

**Comment by kekekeks** [comment]
We should probably move RxUI support to a separate repo or even finally move it to RxUI main repo, Avalonia API surface should now be stable enough.

**Comment by ChrisPulman** [comment]
I am going to be creating the support packages for Splat with Avalonia and the various DI's I can move the functionality of Avalonia.ReactiveUI into the ReactiveUI repositories too if your happy with this.

**Pull request closed without merging**
