### PR TITLE
Disable property change notifications when setting properties. Fixes 487

### PR DESCRIPTION
**Pull request by jkoritzinsky**

### CODE REVIEW

**Comment by grokys** [comment]
Hmm, I'm not sure this is the correct way to go about it: don't you usually *want* to be notified of changes when setting a value? e.g. if you set a bound value to 100 and it has some coercion logic in the model that limits it to 10 - you'd usually want the `TextBox` to notice that and set itself to 10.

I think the sensible route here is to take a look at what WPF does in this situation. Have you had a chance to check the behavior there?

**Comment by jkoritzinsky** [comment]
I'll go check the WPF behavior again. I think you might be right.

I had an issue when I was working in Xamarin.Forms with their binding system that the feedback as you described would randomly cause an infinite loop though, so that's why I decided to go this direction.

One way of resolving this would be to only not notify if the value doesn't change after being set (as in your situation).

**Comment by grokys** [comment]
Yeah, I think a good idea might be to start with unit tests that describe WPF's behavior and change Perspex to match that. I think there are a couple of situations to test:

1. What value is passed to the underlying model when invalid text is entered in a `TextBox` - both with and without a `FallbackValue`
2. What does a `TextBox` display after setting a value which the model coerces

In the meantime I'm going to make a few changes to the binding system which I think will make fixing this problem easier.

**Comment by jkoritzinsky** [comment]
Just checked WPF. It doesn't set the backing field and shows a validation error (red outline around the text box).

**Comment by jkoritzinsky** [comment]
Also, an important thing for WPF vs Perspex with binding that I've noticed. TextBox elements in Perspex send values back as they are typed. In WPF you need to tab (or click) out of the TextBox for changes to propagate.

**Comment by grokys** [comment]
Yeah, in WPF you can make WPF behave like Perspex by setting `UpdateSourceTrigger=PropertyChanged` which in my experience is usually the best behavior. However, we do need a way in Perspex to update the binding when focus is lost.

**Comment by grokys** [comment]
Actually, looking further into this, in WPF if you have a `TextBox` bound to a `double`, you can't enter decimals with `UpdateSourceTrigger=PropertyChanged`. This doesn't sound like behavior we want to copy to me.

UWP handles this more like your PR in that it doesn't seem to reflect changes to the underlying field while the user is entering text. Need to investigate more, but I'm thinking that the UWP behavior is actually less surprising.

**Comment by grokys** [comment]
Closing this because I think recent changes make it work. Thanks for the PR though!

**Pull request closed without merging**
