### PR TITLE
Fixing Canvas positioning for AdornerLayer

### PR DESCRIPTION
**Pull request by pr8x**
Despite `AdornerLayer` inheriting `Canvas`, positioning adorners with `Canvas.SetLeft`/`Canvas.SetTop` never worked. In order to just arrange a single child I needed to add a `ArrangeChild` method to `Canvas`. 

This could technically be a breaking change. Existing adorner code might rely on the old arrange system.

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0020207-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by grokys** [comment]
@danwalmsley you changed `AdornerLayer` to inherit from `Canvas` in [this commit](https://github.com/AvaloniaUI/Avalonia/commit/93a320522f1b93ccbb96a2ab1eeb2a3d9c21d287) and from the commit message I assumed that you wanted the canvas positioning properties to work on `AdornerLayer`?

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0020255-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]
I remember noticing this issue, when I wanted to add a custom adorner, not attached to any other control.
These changes make sense to me.

**Pull request merged**
