### PR TITLE
[PR] The proj files have been updated to enable SourceLink

### PR DESCRIPTION
**Pull request by JTOne123**
CSProj files have been updated to enable SourceLink in your nuget
---

*[This pull request was created with an automated workflow]*

I noticed that your repository and Nuget package are important for our .NET community, but you still haven't enabled SourceLink.

**We have to take 2 steps:**
1) Please approve this pull request and make .NET a better place for .NET developers and their debugging.
2) **Then just upload the .snupkg file** to https://www.nuget.org/ (now you can find the snupkg file along with the .nuget file)

You can find more information about SourceLine at the following links  
https://github.com/dotnet/sourcelink
https://www.hanselman.com/blog/ExploringNETCoresSourceLinkSteppingIntoTheSourceCodeOfNuGetPackagesYouDontOwn.aspx

If you are interesting about this automated workflow and how it works  
https://github.com/JTOne123/GitHubMassUpdater

*If you notice any flaws, please comment and I will try to make fixes manually*

### CODE REVIEW

**Comment by kekekeks** [comment]
@jkoritzinsky

**Comment by kekekeks** [comment]
I think it was already handled by https://github.com/AvaloniaUI/Avalonia/blob/dd6bfb77b24c272608fb11f1665bd36bd52d2619/build/SourceLink.props

**Comment by jkoritzinsky** [comment]
Now that the package from .NET is stable, we should update our SourceLink targets to use the official package.

But yes, we already have sourcelink support.

**Comment by JTOne123** [comment]
sorry guys for mismatch

**Pull request closed without merging**
