### PR TITLE
Fixed various invalidation and hit-testing issues

### LINKED ISSUE #8527: Composition Renderer does not handle dirty rects correctly
**Describe the bug**
Somehow after #8105 not all dirty rects are handled correctly, i.e. there are visuals left that should not be there. 

**To Reproduce**
There are several ways to do. 

Way 1: Open the control catalog on DataGrid page and select more than one row with [Ctrl] pressed. Notice that the current cell adorner gets not cleared. It will be cleared once you move your mouse over the row. See screenshot 1

Way 2: Open Dev tools and move your mouse fast over the rows. See that the hover brush does not always disappear. See screenshot 2

**Expected behavior**
Visuals should be updated correctly

**Screenshots**
Animation

Animation2

**Desktop (please complete the following information):**

- OS: Windows
- Version: latest master

**Additional context**
@robloo  saw similar issues and reported them on telegram channel. 

Unfortunately I have no idea where to look. So I think I'm not able to fix it on my own. 

One more hint: I only saw the issues related to the DataGrid, but it may be also an issue for other controls. 

/cc @kekekeks

### PR DESCRIPTION
**Pull request by kekekeks**
Fixes #8527

Also now passes hit-testing tests ported from DeferredRenderer

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0022195-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by timunie** [comment]
The issues I've mentioned seems to be gone now. I'm really impressed about how fast this was solved out 👍

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0022208-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by wieslawsoltes** [comment]
This PR fixes issues with invalidation we have also encountered.

**Review by wieslawsoltes — APPROVED** [review]

**Pull request merged**
