### PR TITLE
feat: Enable Rule CS0649

### LINKED ISSUE #9887: _controlActive is never used
`XimInputMethod._controlActive` and `DBusTextInputMethodBase._controlActive` are never used. so the checks that use them eg `var active = _windowActive && _controlActive;` will always have the same value. i have no idea where `_controlActive` should be set

### PR DESCRIPTION
**Pull request by workgroupengineering**
## What does the pull request do?

Enable Rule [CS0649](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0649): Field 'field' is never assigned to, and will always have its default value 'value'

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Fixed issues

Part of #8944
Fixes #9887

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0028703-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by workgroupengineering** [comment]
> Pinging @kekekeks for review as it looks to me like this changes behavior.

see https://github.com/AvaloniaUI/Avalonia/discussions/9990#discussioncomment-4701870

**Comment by grokys** [comment]
Ah ok, thanks. If you could link to such discussions in the description in future it would be helpful.

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0029139-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0029154-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Pull request merged**
