### PR TITLE
fix(AvaloniaPropertyAnalyzer): Avoid AVP1031 when Avalonia Field Acce…

### PR DESCRIPTION
**Pull request by workgroupengineering**
…ssibily in not Public

Considering following case

```bash
Warning AVP1031 Missing accessor: Avalonia.Controls.DefinitionBase.PrivateSharedSizeScopeProperty is writeable, but this CLR property lacks a set accessor Avalonia.Controls (net6.0) C:\GitHub\Avalonia\src\Avalonia.Controls\DefinitionBase.cs 418 Active
```

https://github.com/AvaloniaUI/Avalonia/blob/bc74d041989920a008016ec00c87a676b2304948/src/Avalonia.Controls/DefinitionBase.cs#L750-L754

https://github.com/AvaloniaUI/Avalonia/blob/bc74d041989920a008016ec00c87a676b2304948/src/Avalonia.Controls/DefinitionBase.cs#L415-L421

There is no need to report the rule violation because the PrivateSharedSizeScopeProperty field is declared private and cannot be accessed from other assemblies.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

### CODE REVIEW

**Comment by workgroupengineering** [comment]
Please @tomenscape Can you review?

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0030831-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]
This change makes sense as for me.
CC  @tomenscape

**Comment by tomenscape** [comment]
There is still an open change request. @workgroupengineering, what do you want to do?

**Comment by workgroupengineering** [comment]
> There is still an open change request. @workgroupengineering, what do you want to do?

I don't want to report AVP1031 when Avalonia Property has no public accessibility.

**Comment by tomenscape** [comment]
I meant what do you want to do about my review comment above.

**Comment by workgroupengineering** [comment]
> I meant what do you want to do about my review comment above.

Since you implemented the analyzer, I don't want the change to break something else that I don't know about your implementation or that I missed.

**Comment by workgroupengineering** [comment]
> ```cs
> = Accessibility.Private
> ```

Thank you

I don't understand why you suggest this

```csharp
if (avaloniaPropertyStorage.DeclaredAccessibility != Accessibility.Private)
```

Why can't i declare internal or protected AvaloniaProperty scope without clr property?

**Comment by tomenscape** [comment]
A protected symbol is still exposed to assembly consumers, so should be analysed. Internal symbols are less important.

What you have now seems fine to me.

**Review by TomEdwardsEnscape — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0031038-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Pull request merged**
