### PR TITLE
Make Delete on macOS delete correctly.

### PR DESCRIPTION
**Pull request by rhencke**
On a Mac keyboard, the Delete key functions as the Backspace key
does on a PC keyboard.  Map VK_Delete to Key.Back (VK_ForwardDelete
correctly maps to Key.Delete)

I'm not sure where appropriate test would be for this, but I'd be happy to add one if desired.

### CODE REVIEW

**Comment by grokys** [comment]
@AvaloniaUI/core anyone running on Mac who can test this?

**Review by danwalmsley — APPROVED** [review]

**Comment by danwalmsley** [comment]
Actually i tested on a vm with a pc keyboard, so not sure if thats a good enough test

**Comment by rhencke** [comment]
@danwalmsley Is this a Mac running in a VM?  If so, you can bring up the software keyboard to check the behavior and verify the mapping is the same.  System Preferences -> Keyboard -> Show keyboard and emoji viewers in menu bar.  Then, from the menu menu in the upper right, select Show Keyboard Viewer.  That'll give you an on-screen keyboard you can just click the buttons on, without worry of how anything else is mapped.

**Comment by danwalmsley** [comment]
Ok woll try this soon. Btw have you seen any wierd issue on mac like when you click things the window loses focus or disapears?

**Comment by danwalmsley** [comment]
That last comment is not related to this PR, your just one of the few mac users I have contact with.

**Comment by rhencke** [comment]
@danwalmsley Yes - there were quite a few little issues like that I encountered, but I also understand Avalonia is still very much a work in progress, so I didn't think much of it. :)

If this is something I can help on, I would be happy to.

**Pull request merged**
