### PR TITLE
Fixes intermittent test failures on AppVeyor when running Leak Tests.

### PR DESCRIPTION
**Pull request by jkoritzinsky**

### CODE REVIEW

**Comment by grokys** [comment]
@jkoritzinsky any idea why these tests were previously intermittently failing? AFAICS  `FailIfRunWithoutSupport` should have no effect as these tests should always be run with dotMemoryUnit.

**Comment by jkoritzinsky** [comment]
It was the constructor setting up the output that was causing the errors intermittently.

**Comment by grokys** [comment]
Hmm, ok, so how was that causing errors and how did this fix it? I am going to merge anyway, but I'm interested in learning exactly what the problem was.

**Comment by jkoritzinsky** [comment]
DotMemory errors out if there isn't an output method set when a test using it runs. It looks like it would fail when the test in this class would run first when the leak tests were run with dot memory (which was nondererministic)

**Comment by grokys** [comment]
Ahhh, got ya. Thanks!

**Pull request merged**
