### PR TITLE
[OSX] Handle default dialog actions to prevent beeping sounds

### PR DESCRIPTION
**Pull request by ltetak**
## What does the pull request do?
Handling the event so it does not produce superfluous warning sounds.

## What is the current behavior?
On macOS, when you have a dialog and you click Enter (or Escape) to close the dialog with default action (IsDefault or IsCancel flags) the action is successful but you will hear the warning notification sound.
1. on macOS open the sample application -> Dialogs page -> Dialog
2. click Enter
3. dialog is closed but you will hear the notification sound

image

## What is the updated/expected behavior with this PR?
No sound should be played if the action was successful. macOS plays sounds if the action was not handled which is not true in this case.

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018520-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019152-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019152-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by jmacato** [comment]
Closing due to inactivity. Please ping me if you're gonna work on this again.

**Comment by jmacato** [comment]
@ltetak is this ready to review?

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019329-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by ltetak** [comment]
@jmacato yes, if you need any clarification just ping me.

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019448-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
