### PR TITLE
Remove HeaderContentPresenter of several controls.

### LINKED ISSUE #9136: Remove HeaderContentPresenter from All Controls
**Describe the bug**

Some controls ported from UWP still have the header content presenter. That convention was largely decided against for Avalonia and has been removed from other controls such as ComboBox recently.

We should go through all controls and remove it completely:
 * DatePicker
 * TimePicker
 * etc...

I'm making this a bug because the API is very inconsistent here.

**Expected behavior**

Avalonia controls should not have header content. 

**Additional context**

There should be a separate HeaderContentPresenter control in any apps that need this functionality. The goal in Avalonia is not to flatten the visual tree and cause control-bloat like this.

### PR DESCRIPTION
**Pull request by rabbitism**
## What does the pull request do?

Remove `HeaderContentPresenter` from `DatePicker`, `TimePicker` and `Slider`

## What is the current behavior?

Mentioned three controls have HeaderContentPresenter which is from WinUI but not consistent with rest of Avalonia controls.

## What is the updated/expected behavior with this PR?

Remove them from template, and remove Header/HeaderTemplate property from DatePicker/TimePicker

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Breaking changes

Header/HeaderTemplate properties are removed. 

## Fixed issues

Fixes #9136

### CODE REVIEW

**Comment by robloo** [comment]
Thanks!

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0024606-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by rabbitism** [comment]
> Thanks!

My pleasure, but I never thought Header is actually used in Date/Time picker. is it okay to remove them as it's quite breaking?

**Comment by robloo** [comment]
11.0 is full of breaking changes. This is simple to fix and just requires a textblock above or just use the control you were putting in the header directly instead.

I'm sure some will not like it. But Control and API design needs to be consistent and now is the time to change. We are following WPF here not WinUI.

Do you have any specific examples of your concern though?

**Comment by rabbitism** [comment]
> Do you have any specific examples of your concern though?

No, this PR is ready for review.

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0024772-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
