### PR TITLE
fixes macOS build on C.I. SDK 11 according https://github.com/actions…

### PR DESCRIPTION
**Pull request by workgroupengineering**
…/virtual-environments/blob/macOS-10.15/20201212.1/images/macos/macos-10.15-Readme.md

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

### CODE REVIEW

**Comment by danwalmsley** [comment]
I dont understand what this fixes? We used 12, because that gives us 12.2, which I have verified and this is required for apple sillicon. If we use default... then the value this represents can randomly change in the future.

**Comment by maxkatz6** [comment]
> I dont understand what this fixes?

Right now CI fails with "xcodebuild: error: SDK "macosx11.0" cannot be located.".

**Comment by workgroupengineering** [comment]
> 
> 
> I dont understand what this fixes? We used 12, because that gives us 12.2, which I have verified and this is required for apple sillicon. If we use default... then the value this represents can randomly change in the future.

- The issue is the one reported by @maxkatz6 
- From [this](https://github.com/actions/virtual-environments/blob/macOS-10.15/20201212.1/images/macos/macos-10.15-Readme.md#installed-sdks) you can see thatn minimum requirement for SDK 11 is XCode 12.2

Possible solutions are to downgrade the SDK or update to XCode 12.2. I prefered the second.

**Comment by kekekeks** [comment]
>Possible solutions are to downgrade the SDK or update to XCode 12.2. I prefered the second.

Setting `default` is not an upgrade to XCode 12.2, it's an upgrade to a completely random version that can and will break our build in the future.

**Comment by workgroupengineering** [comment]
> 
> 
> > Possible solutions are to downgrade the SDK or update to XCode 12.2. I prefered the second.
> 
> Setting `default` is not an upgrade to XCode 12.2, it's an upgrade to a completely random version that can and will break our build in the future.

As I understand from Microsoft's specifications, "default" uses the latest released version compatible with the chosen operating system.
With this consideration, I would also remove the SDK version, in order to use the latest sdk compatible with the agent.
When you need new features, just change the os agent.

Merry Christmas for those who celebrate it.

**Comment by kekekeks** [comment]
>As I understand from Microsoft's specifications, "default" uses the latest released version compatible with the chosen operating system.

Which means a random undefined version in any moment of time after now.

**Comment by workgroupengineering** [comment]
I don't know Apple's policies, but I don't think it creates breking changes between different versions of the SDK dedicated to the same OS version but only bug fixes.

Do you have information about Apple SDK release policies?

**Pull request closed without merging**
