### PR TITLE
Implement Matrix.CreateRotation with center point.

### LINKED ISSUE #17307: Add Matrix.Rotate(angle, x, y) overload
### Is your feature request related to a problem? Please describe.

This is not a standard css transformation, but a frequently used in svg. 

### Describe the solution you'd like

as described. 

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rabbitism**
## What does the pull request do?

Add new overload for Matrix.CreateRotation(double radians, Point center).
This is a valid and commonly used transformation in SVG see: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform#rotate
Also part of Systme.Numeric api. 

Notice: whether to use `Point` or `Vector` is not finalized yet, pending on team descision. 

## Checklist

- [x] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/avalonia-docs with user documentation

## Fixed issues
Closes #17307

### CODE REVIEW

**Review by kekekeks — APPROVED** [review]

**Comment by robloo** [comment]
Please double check Radians vs. Degrees for API uniformity. Higher levels usually use degrees. It is very important we keep APIs consistent in terms of units.

**Comment by rabbitism** [comment]
I think the other rotation api uses radians.

**Comment by robloo** [comment]
@rabbitism All our shape API uses degrees. API in WPF almost always uses degrees. 

https://learn.microsoft.com/en-us/dotnet/api/system.windows.media.rotatetransform.-ctor?view=windowsdesktop-9.0#system-windows-media-rotatetransform-ctor(system-double-system-double-system-double)

I don't know the Matrix API off the top of my head but we need to 1) Use degrees or 2) Use radians if that is what WPF does in this case.

This is something that has to be very carefully reviewed in API because both degree and radian are double. So it's a very dangerous silently breaking changing if ever it needs to be fixed.

**Comment by rabbitism** [comment]
> @rabbitism All our shape API uses degrees. API in WPF almost always uses degrees.
> 
> https://learn.microsoft.com/en-us/dotnet/api/system.windows.media.rotatetransform.-ctor?view=windowsdesktop-9.0#system-windows-media-rotatetransform-ctor(system-double-system-double-system-double)
> 
> I don't know the Matrix API off the top of my head but we need to 1) Use degrees or 2) Use radians if that is what WPF does in this case.
> 
> This is something that has to be very carefully reviewed in API because both degree and radian are double. So it's a very dangerous silently breaking changing if ever it needs to be fixed.

I don't see any reason this API should use a different unit with the other. 
https://github.com/AvaloniaUI/Avalonia/blob/f4633e210c23ff7fbaec3cf402d03deac5315a68/src/Avalonia.Base/Matrix.cs#L210-L215

**Comment by robloo** [comment]
Well, seems we are already different from WPF...

https://learn.microsoft.com/en-us/dotnet/api/system.windows.media.matrix.rotateat?view=windowsdesktop-9.0#system-windows-media-matrix-rotateat(system-double-system-double-system-double)

I wonder if this was intentional or an oversight. I guess the one benefit is radians makes the math easier. Still, we really shouldn't have both degrees and radians in the APIs. The convention has always been degrees as well. If we wanted to switch to radians it should have been done everywhere.

But it is worse to have different units in the same class. So now we are stuck.

API review is extremely important.

There should NOT be a public degrees to radians conversion method on this class either.

**Comment by maxkatz6** [comment]
Matrix APIs in .NET BCL and SkiaSharp use radians
https://learn.microsoft.com/en-us/dotnet/api/system.numerics.matrix4x4.createrotationx?view=net-9.0#system-numerics-matrix4x4-createrotationx(system-single)

**Comment by maxkatz6** [comment]
> There should NOT be a public degrees to radians conversion method on this class either.

This method is 10 years old... Shouldn't be there indeed.

**Comment by robloo** [comment]
@maxkatz6 OK, if they already use radians in the BCL I won't argue. My point was WPF seems to be different using degrees. Perhaps Microsoft changed their thinking for .NET after WPF was initially released.

I guess the distinction is:

Low-level functionality uses Radians for mathematical reasons.

High-level API (XAML/Shapes) uses degrees for compatibility and simplicity (degrees are easier for people to visualize).

**Pull request merged**
