### PR TITLE
Build AOT demo project on CI

### PR DESCRIPTION
**Pull request by maxkatz6**
## What does the pull request do?

Not sure yet if it's the best way for us to test AOT builds on the CI.
Ideally, we should compile our unit tests with AOT and run them on CI instead.
But for now, building single project with all AOT/trimming errors enabled should be enough.
Continues https://github.com/AvaloniaUI/Avalonia/pull/15815 (as well as this PR should prevent similar regressions).

## What is the current behavior?

If any commit regresses AOT support, including AOT related warnings, nobody might notice until too late.

## What is the updated/expected behavior with this PR?

If any commit regresses AOT support, including AOT related warnings, build should fail.

## How was the solution implemented (if it's not obvious)?

Re-purposing BindingDemo project as a decent functionality test.

### CODE REVIEW

**Comment by maxkatz6** [comment]
Might not be necessary after https://github.com/AvaloniaUI/Avalonia/pull/16543

**Comment by kekekeks** [comment]
Can we run some subset of integration tests with AOT too? e. g. ones that would cover bindings and stuff.

**Comment by maxkatz6** [comment]
@kekekeks once [GeneratedComInterface] is merged, I was considering to run full set of integrational tests with AOT. We don't rely on reflection there, it should work well.

**Comment by maxkatz6** [comment]
Closing, as we want to focus on integrational tests in AOT mode instead.

**Pull request closed without merging**
