### PR TITLE
Portablexaml

### PR DESCRIPTION
**Pull request by kekekeks**
Based on #916

### CODE REVIEW

**Comment by grokys** [comment]
Just taking a look at this now. I see PortableXaml is included as a submodule - what's preventing us from using the NuGet package at the moment?

**Comment by jkoritzinsky** [comment]
We had to make a few changes to PortableXaml to fix some bugs and add some extensibility points for us (specifically `ISupportInitialize`)

**Comment by cwensley** [comment]
@jkoritzinsky if you submit the bug reports to the Portable.Xaml repo I can take a look.  Better yet, if you've already fixed them a PR would work and I can push it to nuget. (;

**Comment by kekekeks** [comment]
@cwensley
The main issue with NuGet package is that you are using pcl259 build for net461... Which is *not* binary compatible with netstandard one, since you are defining your own types in PCL version. That's causing runtime errors when trying to run our code compiled for netstandard on desktop .NET.
I'm not sure if it's even possible to fix that issue without dropping PCL support completely.

There are also a couple of changes to add missing support for reading attached properties (https://github.com/AvaloniaUI/Portable.Xaml/commit/dc333ff66eb1fdd8565e9b831718791675ec569b https://github.com/AvaloniaUI/Portable.Xaml/commit/926e82551c10591f2fa3afb25121ac2d16b272c6) and to fix a bug in XamlTypeInvoker.

I was planning to submit PRs for those once everything gets stabilized a bit.

@jkoritzinsky 
We haven't touched `ISupportInitialize` *yet* (still using that hack by @donandren ), but I think that we'll have to later. Or switch to netstandard2.0 and use built-in one.

**Comment by jkoritzinsky** [comment]
Would type forwarders possibly work if the name spaces are changed?

**Comment by kekekeks** [comment]
That might work, but it will break exiting code that's uses Portable.Xaml.

**Pull request merged**
