### PR TITLE
Allow progressbar width and height less than default

### LINKED ISSUE #1416: ProgressBar MinWidth and MinHeight hard coded
Values set from xaml are overwritten by code so it is hard to have a progress indicator <200x14

### PR DESCRIPTION
**Pull request by ahopper**
This fixes #1416

### CODE REVIEW

**Comment by grokys** [comment]
Actually, I think rather than having the `MinWidth` and `MinHeight` set in code, we should be setting these properties from the theme.

**Comment by ahopper** [comment]
@grokys I agree. This was a cautious fix on my behalf.

**Comment by ahopper** [comment]
I guess a better way to do it is the way slider handles Orientation, I'll have a go

**Comment by ahopper** [comment]
I have left the MinHeight and MinWidth in the template as they are effectively used as the default size in the control catalog

**Comment by jp2masa** [comment]
@grokys It was supposed to be a default value, but I implemented it wrongly, sorry... The selectors approach is much better, good job @ahopper!

**Review by jkoritzinsky — APPROVED** [review]
LGTM!

**Pull request merged**
