### PR TITLE
Fix Menu navigation

### PR DESCRIPTION
**Pull request by grokys**
Menu navigation was previously broken, and was hard to fix because the `DirectionalNavigation` framework we had in place was not too inflexible to implement navigation properly, but in fact _prevented_ it by intercepting navigation keypresses before they reach the control. In addition, menu interaction had no unit tests.

This PR is quite large but there are essentially two parts to it:

## Remove DirectionalNavigation

This PR removes the `DirectionalNavigation` framework. Controls which previously relied on this now implement their own handling. This isn't a big deal because it's not so hard to implement.

Although the directional navigation framework is present in WPF, it was removed from UWP for what I assume was the same reason.

## Abstract menu navigation to use interfaces

As mentioned previously, there were no unit tests for `Menu` navigation - this was mainly because it's really hard to test as it touches so many parts of Avalonia (focus manager, popups, `ItemsControl`). After trying for a while and coming up with convoluted and fragile unit tests, I decided to abstract menu interaction into an interface (`IMenuInteractionHandler`) which interacts with `IMenu` and `IMenuItem` interfaces.

In this way, the implementation details can be mocked out making unit tests much easier.

A side effect of this is that this will also allow menu interaction to be customized for different platforms if necessary.

Depends on #1811

### CODE REVIEW

**Comment by danwalmsley** [comment]
I have seen an issue, but will get time for a repro shortly.

**Comment by danwalmsley** [comment]
I see that this line wasn't changed in this pr but perhaps this bug can now be hit because of it... 

image

**Comment by danwalmsley** [comment]
pushed a commit to fix that.

**Comment by danwalmsley** [comment]
in avalonstudio and avalonstudio shell apps, menu navigation isn't working because items are not getting selected.

A bit of investigations and this has to be the weirdest bug iv come across. Same code in control catalog works.

image

See the immediate window, its an Avalonia.Controls.MenuItem but it wont cast to iControl or TControl (menuitem)

**Comment by grokys** [comment]
> pushed a commit to fix that. (this was happening when binding menu items)

Ah, thanks for that. I think the actual fix is slightly different, but thanks for finding the bug! ;)

> menu navigation isn't working because we bind to an IEnumerable

Oh, ok - that's a bad idea in general. Quite a bit of stuff can break if you do that. I'm just not sure how to handle it, see https://github.com/AvaloniaUI/Avalonia/issues/54 - it's a really old issue :/

**Comment by danwalmsley** [comment]
I fixed in my code by converting the enumerable to a List before using it. Which was fine in this case :)

**Comment by danwalmsley** [comment]
Yes. I thought you were going to pish the correct fox for that bug?

**Review by danwalmsley — APPROVED** [review]

**Pull request merged**
