### PR TITLE
Rewrite SelectionModel

### LINKED ISSUE #4496: Selection Model Issues
- Always selected mode - Add 3 items, select the last item... remove the middle item... this leaves no item selected.
- Crash when removing all items, and then inserting at position 0.
image

-- more to come.

### PR DESCRIPTION
**Pull request by grokys**
## What does the pull request do?

`SelectionModel` as ported from WinUI has a number of problems:

- Didn't handle binding `SelectedIndex` (#4496)
- Combining flat and nested selection led to unergonomic API (`IndexPath` for flat selection)
- Nested selection didn't work very well anyway due to the way `TreeView` works (don't know what the child items are until the `TreeViewItem` is materialized, so can't select non-expanded nodes)
- API was complex with lots of convenience methods so extracted interface was large
- Was not generic so lots of casts needed in ViewModel layer
- Did not preserve `SelectedIndex`/`SelectedItem`; instead returned first selection
- AnchorIndex didn't behave like in normal controls
- Didn't allow setting `SelectedItem`
- SelectRange/SelectAll selected multiple items even when `SingleSelect = true`
- Didn't work well when making selections before Source assigned, so `BeginInit`/`EndInit` logic had to be hacked into control (needs to be possible to set `SelectedIndex`/`SelectedItem` before `Items` is assigned in XAML)

This PR first reverts the changes introduced by the previous `SelectionModel` attempt and then rewrites `SelectionModel` to:

- Only handle list (flat) selections, so indexes are plain `int`s
- Slims down the interface
- Makes `SelectionModel` generic so that it can be used in ViewModels without casts everywhere
- Preserves `SelectedIndex`
- Makes `AnchorIndex` work as expected
- Allows setting `SelectedItem`
- Disable range selection when `SingleSelect = true`
- Makes setting selection before `Source` is assigned work better, so `BeginInit` can simply delay the `Source` assigment until initialization is finished

Note that after this change, `TreeView` no longer has a selection model: it will remain reverted to its pre-`SelectionModel` v1 state.

It's still a WIP, left to do:

- [x] Use the list of selected objects in `SelectedItems` to repopulate selection after `Reset` (needs to be a way to turn it off for large collections)
- [x] Correctly select newly added items with `IsSelected` set
- [x] Re-apply use of `Selection` to samples (were changed back to `SelectedItems` when I reverted the previous `SelectionModel`)
- Various other little bugs

## Breaking changes

Yep, it's a breaking change :) Not so much from 0.9.x but the `SelectionModel` API has changed from the previous version shipped in the 0.10 previews.

## Fixed issues

Fixes #4496

### CODE REVIEW

**Comment by grokys** [comment]
> Removing IndexPath; however, cripples the usefulness of SelectionModel and as you stated, doesn't allow it to work in a hierarchy (TreeView)

The idea will be to add a `TreeSelectionModel` at a later date: I'm working on it over at https://github.com/grokys/AvaloniaSelectionModel but it's a bit more involved so might take a while.

> IndexPath with a single int index isn't that complicated.

Heh, it's a lot more complicated than it first seems!

**Review by jmacato — APPROVED** [review]
code style :+1: tested controlcatalog and found nothing wrong :+1: would need a deeper dive testing @danwalmsley

**Comment by Kermalis** [comment]
Does this fix #4472 or #4048? More unlikely to fix #4461

**Comment by grokys** [comment]
@Kermalis I wasn't targeting those issues specifically, as this PR was holding up a release, however it's possible it may have fixed some things. I plan to look into those issues again when I have a moment.

**Pull request merged**
