### PR TITLE
Compositor-aware resources

### PR DESCRIPTION
**Pull request by kekekeks**
Brush, pen and transform (only when used in brush for now) now have mutable render thread counterparts and are syncing automatically (i. e. no-need for OnRender call on brush invalidation).

Breaking changes:
- IBitmap is now hidden
- ImageBrush now accepts a special interface instead of IBitmap (that will allow us to use IImage later)
- PlatformImpl for resources is no longer available, for drawing glyph runs a special API is introduced
- IAffectsRender is hidden and will be completely removed later

TODO (later):
- remove the remnants of IAffectsRender usages (effects can be left as is for now)
- - add  a separate way for IImage to trigger invalidation when it relies on building render lists on the UI thread (should probably have a base class that handles said render list)
- remove the rest of IRef usage

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0034734-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by danipen** [comment]
@kekekeks do you think this PR fixes #11036? Sorry, I'm out and I cannot verify now myself.

**Comment by kekekeks** [comment]
It only affects the way changes from the brush propagate to the visual. If brush itself doesn't get updated, this PR won't fix it.

**Review by maxkatz6 — APPROVED** [review]

**Comment by jp2masa** [comment]
#11438 #11469

**Comment by llfab** [comment]
Please see details here: https://github.com/AvaloniaUI/Avalonia/discussions/11491#discussioncomment-5993054

**Pull request merged**
