### PR TITLE
Enable $visualparent syntax.

### PR DESCRIPTION
**Pull request by rabbitism**
## What does the pull request do?

Since `$parent` only works on logical tree, so `$visualparent` is needed to find relative resource on visual tree. Most related code is available in code base, so I just add them back in parsing logic.  

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/avalonia-docs with user documentation

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0040456-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by rabbitism** [comment]
I marked this as WIP because I was trying to find a way to add unit test for it. But it's difficult.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0040489-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by rabbitism** [comment]
It is not working for AvaloniaRuntimeXamlLoader ...

**Comment by maxkatz6** [comment]
We are not interested in this feature at this moment, sorry. Closing this PR.

**Pull request closed without merging**
