### PR TITLE
Implement xdg-desktop-portal accent-color spec

### PR DESCRIPTION
**Pull request by affederaffe**
## What does the pull request do?
Use the standardized xdg-desktop-portal setting to get the accent color
https://github.com/flatpak/xdg-desktop-portal/pull/815/

Currently, no DE actually implements it as it just got merged, hence WIP

## What is the current behavior?
Accent colors only work on KDE

## What is the updated/expected behavior with this PR?
Accent colors should work on every DE that provides them via the settings portal

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0038807-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by orowith2os** [comment]
It's fine if you remove the WIP tag, if the only reason is DEs implementing the key; the only actual requirement should be a stable xdg-desktop-portal release with the key.

**Comment by maxkatz6** [comment]
@jmacato @kekekeks should we merge this PR now? Before actual distros support this feature. Since it's considered as a part of the standard now.

**Comment by jmacato** [comment]
PR/Concept looks good to me, although i'll wait what @kekekeks has to say

**Comment by kekekeks** [comment]
The support for the spec seems to be merged into KDE yesterday, so I'd like to wait for the next KDE Neon build to test.

Not strictly required though.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0039153-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by affederaffe** [comment]
Testing it on KDE Neon, it doesn't work.
Though I think actually KDE isn't following the spec here: When changing the accent color, the `SettingChanged` signal is invoked with the value
```
   string "org.freedesktop.appearance"
   string "accent-color"
   variant       array [
         variant             double 0.0313726
         variant             double 0.611765
         variant             double 0.541176
      ]
```
but as per spec:

> In the case that an accent color is requested, the underlying value would be a struct containing three doubles, each being an RGB value in the range of [0,1].

**Comment by jmacato** [comment]
@affederaffe could we handle that without straying out of spec? perhaps a special case for KDE? (although ik that would suck...)

**Comment by orowith2os** [comment]
@jmacato KDE should fix their portal if it's not following the spec, you shouldn't be working around their bug.

**Comment by affederaffe** [comment]
@jmacato I've asked in the KDE Plasma Matrix room to see if this is actually a spec violation or just me not reading said spec correctly. For now, I'd just wait since no DE has officially released any version that supports it anyway.

**Comment by easyteacher** [comment]
@affederaffe You can test the new spec on Plasma 5.27.8, which will be released tomorrow and has corrected the value type. Thanks for the timely bugreport!

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0039404-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0039525-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by jmacato** [comment]
@affederaffe which KDE version is the spec implemented? could i use Debian Sid for testing?

**Comment by easyteacher** [comment]
On 2023/9/16 13:14, Jumar Macato wrote:
>
> @affederaffe <https://github.com/affederaffe> which KDE version is the 
> spec implemented? could i use Debian Sid for testing?Message ID: 
> ***@***.***>
>
Plasma 5.27.8

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0039592-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0039865-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by affederaffe** [comment]
Confirmed to work on Plasma 5.27.8 and 6, GNOME still hasn't merged the relevant PRs...
Additionally, the current solution breaks on Plasma 6, probably due to a bug on their side as far as I can tell.

**Comment by easyteacher** [comment]
> Confirmed to work on Plasma 5.27.8 and 6, GNOME still hasn't merged the relevant PRs... Additionally, the current solution breaks on Plasma 6, probably due to a bug on their side as far as I can tell.

https://invent.kde.org/plasma/xdg-desktop-portal-kde/-/merge_requests/244

**Review by maxkatz6 — APPROVED** [review]

**Pull request merged**
