### PR TITLE
Add resource Key to ResourcesChangedEventArgs

### PR DESCRIPTION
**Pull request by rabbitism**
## What does the pull request do?

1. Add an optional resource key to ResourcesChangedEventArgs, to help subscriber understand what key is changed if possible. 
2. Add several more IResourceNode extension methods to allow user subscribing to updates only for a particular key. 

## Checklist

- [x] Added unit tests (if possible)?
- [x] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/avalonia-docs with user documentation

### CODE REVIEW

**Comment by rabbitism** [comment]
@grokys @maxkatz6 Please help to review.

**Comment by maxkatz6** [comment]
What's your use-case for this API?
It adds unnecessary allocations for most developers, while not adding any improvements for them.

**Comment by rabbitism** [comment]
> What's your use-case for this API? It adds unnecessary allocations for most developers, while not adding any improvements for them.

Trigger a resource update when another resource is updated.

**Comment by rabbitism** [comment]
I'm going to close this PR as we are going to deliver a self-maintained resource dictionary for this feature.

**Pull request closed without merging**
