### PR TITLE
Handle multiple content presenters within a content control

### PR DESCRIPTION
**Pull request by WojciechKrysiak**
- What does the pull request do?
Adds the ability to use ContentControlMixin multiple times on the same ContentControl (for different content presenters)
- What is the current behavior?
ConditionalWeakTable throws an ArgumentException, as the control callbacks have already been registered, and the key is present in the table.
- What is the updated/expected behavior with this PR?
Previous registrations are being combined into CompositeDisposable, allowing unlimited chaining.

### CODE REVIEW

**Comment by grokys** [comment]
Hey, thanks for the PR! Could you give an example of what this this is needed for?

**Comment by WojciechKrysiak** [comment]
It's done mostly to secure the Mixin for control creators that wouldn't be aware of the limitation.

My use case is:

```
class Foo: HeaderedSelectingItemsControl
{
   static Foo()
   {
      ContentControlMixin.Attach<Foo>(HeaderIconProperty, x => x.LogicalChildren, "PART_IconPresenter");
   }
}
```

Currently this would crash when the `TemplatedControl.TemplateAppliedEvent` fires for the second time (first being for `PART_HeaderPresenter` in `HeaderedSelectingItemsControl`).

**Comment by grokys** [comment]
Ok, I think that makes sense. There's already currently `HeaderedContentControl`, but that doesn't expose the header as a logical child - I guess it should.

I think we could do with some unit tests for this to make sure that it works correctly when applied multiple times to a control, as that wasn't a use-case when the class was written. We need to be sure that the logical children are correctly added and removed etc.

**Comment by WojciechKrysiak** [comment]
Ok, I'll write the tests tomorrow.

**Review by grokys — APPROVED** [review]

**Pull request merged**
