### PR TITLE
Correct RtlGetVersion usage

### PR DESCRIPTION
**Pull request by MichalPetryka**
## What does the pull request do?
When I've looked at the `RtlGetVersion` usage, I've noticed that it:
1. uses `out` where `ref` was probably intended, I've tested it and it seems to return the correct values, but I'm pretty sure this behaviour is not defined, which could mean that some runtimes would give a pointer to some uninitialized memory with incorrect `dwOSVersionInfoSize`
2. it passes `dwPlatformId` to the `Version` constructor, which isn't a part of the version itself so I think this might also be an unwanted behaviour

## What is the current behavior?
The code relies on an probably undefined behaviour and stores data that isn't the version inside it.

## What is the updated/expected behavior with this PR?
The code uses `ref` which is guaranteed to provide the intended behaviour and doesn't pass dwPlatformId to the version anymore.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=5377) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=5377) before we can accept your contribution.<br/><br/>:x: MichalPetryka [sign now](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=5377)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/AvaloniaUI/Avalonia?pullRequest=5377) it.</sub>

**Comment by Gillibald** [comment]
`ref` Vs. `out´ should make no difference

**Comment by MichalPetryka** [comment]
> `ref` vs. `out` should make no difference

Is that behaviour defined somewhere? Afaik out isn't required to point to initialized memory, since in C# you can never access it before assigning anyway?

**Comment by Gillibald** [comment]
In the P/Invoke scenario `out` just means the value only flows in one direction. The actual compiled instructions have the same result. This is mainly for the managed side.

The native code will just write to the memory region you are passing when the method is called and will never read the actual value.

**Comment by MichalPetryka** [comment]
Still, in this case the value goes in both directions due to the size member, so `ref` is still better even because it indicates that.

**Comment by Gillibald** [comment]
https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-rtlgetversion

The caller has to make sure the pointer passed is writable

**Comment by MichalPetryka** [comment]
`ref` does guarantee that as far as i know.

**Comment by Gillibald** [comment]
The intended flow is in the `out` direction from the managed side. The `in` direction is only implicit. We construct an `RTL_OSVERSIONINFOEXW` struct and pass that to the native side.

**Comment by kekekeks** [comment]
@Gillibald in this case it's actually `ref` since one of the struct members acts as a function parameter.

**Review by grokys — APPROVED** [review]

**Pull request merged**
