### PR TITLE
Fix ClearType rendering

### PR DESCRIPTION
**Pull request by Gillibald**
## What does the pull request do?

There was some change in Skia that caused SKSurface to be created with a SKPixelGeometry.Unknown by default. This prevented ClearType usage. This sets the SKPixelGeometry to `RgbHorizontal` and allows ClearType rending that way.

Question: Can we assume all physical displays have this pixel orientation or do we need to make this customizable?
@kekekeks 

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

### CODE REVIEW

**Comment by Gillibald** [comment]
@danipen

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0026617-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by danipen** [comment]
It's awesome to get this fixed! Thanks 🙏

**Comment by danipen** [comment]
I can confirm it's working as expected in Windows:

- Top image is this PR.
- Bottom image is the baseline (11.0.0-preview4)

image

Thanks again for fixing this!

**Review by danwalmsley — APPROVED** [review]

**Pull request merged**
