### PR TITLE
Support creating OpenGL context with EGL on Linux

### PR DESCRIPTION
**Pull request by emmauss**
## What does the pull request do?
Support creating OpenGL context with EGL on Linux and other unix platforms. Linux supports core OpenGL with both GLX and EGL, but only OpenGL ES context is available in avalonia. This pr allows creating a OpenGL context with EGL, using GlProfiles set during AppBuilder initialization.

An OpenGL 4.0 context can be requested with
```csharp
  => AppBuilder.Configure<App>()
                  .UsePlatformDetect()
                  .With(new X11PlatformOptions
                  {
                      EnableMultiTouch = true,
                      UseDBusMenu = true,
                      EnableIme = true,
                      UseEGL = true,
                      GlProfiles = new List<GlVersion>()
                      {
                          new GlVersion(GlProfileType.OpenGL, 4, 0)
                      }
                  })
```

## What is the current behavior?
Only opengl es context is supported. Setting OpenGL in the angle options will cause shaders to fail

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018280-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by kekekeks** [comment]
>AngleOptions

It's for ANGLE compatibility layer, we should be only using that with Windows. X11 should use `GlProfiles` from `X11PlatformOptions`

BTW, why exactly do you need EGL on Linux? We mainly use it for Windows, with Linux it's here mostly for testing purposes and has issues with window resize and transparency (transparency one is due to a bug in MESA that hasn't been fixed for 8 years)

**Comment by emmauss** [comment]
> > AngleOptions
> 
> It's for ANGLE compatibility layer, we should be only using that with Windows. X11 should use `GlProfiles` from `X11PlatformOptions`
> 
> BTW, why exactly do you need EGL on Linux? We mainly use it for Windows, with Linux it's here mostly for testing purposes and has issues with window resize and transparency (transparency one is due to a bug in MESA that hasn't been fixed for 8 years)

A lot of the users of a project I work on have had issues with GLX on Linux, mostly with performance and a compatibility issue with nvidia prime. That project is making changes to use EGL on it's current gtk based ui. I'm designing an avalonia based ui for it, and will have issues when those changes are done.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018287-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by kekekeks** [comment]
I'll take a look next week or so to refactor EGL configuration properly, not sure if we can merge the PR as-is.

>mostly with performance and a compatibility issue with nvidia prime. 

Note that we've only encountered issues with `optirun` utility and found them not fixable on our side. Avalonia should work fine with `primusrun`, `prime-select` and [PRIME offloading](https://download.nvidia.com/XFree86/Linux-x86_64/435.17/README/primerenderoffload.html).
If you are encountering issues with those, please, file a separate issue.

**Comment by emmauss** [comment]
> I'll take a look next week or so to refactor EGL configuration properly, not sure if we can merge the PR as-is.
> 
> > mostly with performance and a compatibility issue with nvidia prime.
> 
> Note that we've only encountered issues with `optirun` utility and found them not fixable on our side. Avalonia should work fine with `primusrun`, `prime-select` and [PRIME offloading](https://download.nvidia.com/XFree86/Linux-x86_64/435.17/README/primerenderoffload.html). If you are encountering issues with those, please, file a separate issue.

Those issues are on our gtk based ui, so it's not related to avalonia. That will be fixed with egl support on our context wrapper, though that will take a while. I'm in charge of porting the ui to avalonia. I do not get the glx issues on avalonia, but users won't be happy if we switch back to glx on our app. 
if there is going to be a proper refactor of egl, then I'm OK with closing this. The issue isn't critical.

**Pull request closed without merging**
