### PR TITLE
Fix "original.dll" file permission errors during build

### LINKED ISSUE #5294: Random VS/Mac compile failures for sharing violation
MacOS Big Sur 11.1
Visual Studio for Mac 8.8.5 (build 18)
Avalonia 0.9.12

About a quarter of the time after correcting a syntax error that caused a build failure, the next build attempt fails with the following message:

/Users/t/.nuget/packages/avalonia/0.9.12/build/AvaloniaBuildTasks.targets(5,5): Error MSB4018: The "CompileAvaloniaXamlTask" task failed unexpectedly.
System.IO.IOException: Sharing violation on path /Users/t/Projects/PhotoViewer/obj/Debug/netcoreapp5.0/osx-x64/Avalonia/original.pdb
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x00259] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/corlib/System.IO/FileStream.cs:274 
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.IO.FileOptions options) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/mcs/class/corlib/System.IO/FileStream.cs:106 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,System.IO.FileOptions)
  at System.IO.FileSystem.CopyFile (System.String sourceFullPath, System.String destFullPath, System.Boolean overwrite) [0x00035] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.FileSystem/src/System/IO/FileSystem.Unix.cs:55 
  at System.IO.File.Copy (System.String sourceFileName, System.String destFileName, System.Boolean overwrite) [0x00056] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-02/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.FileSystem/src/System/IO/File.cs:74 
  at Avalonia.Build.Tasks.CompileAvaloniaXamlTask.Execute () [0x00074] in D:\a\1\s\src\Avalonia.Build.Tasks\CompileAvaloniaXamlTask.cs:29 
  at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute () [0x00023] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr/external/bockbuild/builds/msbuild-15/src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs:577 
  at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask (Microsoft.Build.BackEnd.ITaskExecutionHost taskExecutionHost, Microsoft.Build.BackEnd.Logging.TaskLoggingContext taskLoggingContext, Microsoft.Build.BackEnd.TaskHost taskHost, Microsoft.Build.BackEnd.ItemBucket bucket, Microsoft.Build.BackEnd.TaskExecutionMode howToExecuteTask) [0x002b9] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr/external/bockbuild/builds/msbuild-15/src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs:809  (MSB4018) (PhotoViewer)

The only workaround I know of is to close and reopen the project, after which it compiles successfully (if there are no other errors),

### PR DESCRIPTION
**Pull request by TomEdwardsEnscape**
I'm serious. This fixes it, and I know exactly why.

## What does the pull request do?
The changes in this PR prevent the Avalonia Xaml Compiler from recompiling the project's output every time its `build` target is executed.

The .Net SDK executes this target not just on the project being built, but also on all of its dependencies. This is done within the `ResolveProjectReferences` target to ensure that the dependencies are all up to date.[^1] 

[^1]: Visual Studio is a bit different: it identifies and builds each dependency individually. It's probably less affected by the issue that this PR solves.

Not only does this constant rebuilding waste CPU time, it also means that each build involves opening a write handle onto the intermediate build output of each and every dependency containing Avalonia XAML. The more often a project containing Avalonia XAML files is referenced the more likely a file write permission error is to occur.

### Before, the compiler executes:

image

### With these changes, the task is skipped because the output is up to date:

image

## How was the solution implemented

`CompileAvaloniaXaml` now declares its `Inputs` and `Outputs`. MSBuild inspects these files and if it finds that any input is newer than any output, the target is executed. Otherwise, it is skipped.

The inputs are all Avalonia XAML files in the project, plus the assembly and ref assembly generated by the .Net SDK in its `CoreCompile` target. The outputs are a new assembly and ref assembly compiled by Avalonia.

Because MSBuild now knows what the output of the task is supposed to be, we don't need the previous behaviour of moving the build output from its original location. Instead we leave it alone and just write our own build output to a location that we control. This is a lot safer. No more "original.dll".

`CompileAvaloniaXaml` is now preceded and followed by two other tasks which always execute. 

- `PrepareToCompileAvaloniaXaml` sets up the various properties and item groups which will be used (including the inputs and outputs mentioned above).
- `InjectAvaloniaXamlOutput` redefines `IntermediateAssembly` and `IntermediateRefAssembly` as being the files that `CompileAvaloniaXaml` generated.

### C#
There are C# changes to `CompileAvaloniaXamlTask`. Its file-swapping behaviour has been removed and we now use `ITaskItem` properties to transfer items with all of their metadata into the task. I found some apparently unused code which allowed the task assembly to be run as an executable; instead of upgrading this I just deleted it.

### FileWrites
Lastly, the behaviour of `FileWrites` items has been corrected. The items in this group are supposed to be deterministic for a given build configuration, and NOT be a list of the files which were actually written during the current build. This means that if a target is skipped due to its outputs being up to date, we still need to add those outputs to `FileWrites`.

It is therefore no use for `CompileAvaloniaXamlTask` to tell us what files it wrote. We need to know this information before it runs.

## Breaking changes
The changes to intermediate build output give rise to the possibility that a third party MSBuild target could end up working with the "raw" CSC output, instead of the version containing Avalonia's compiled XAML.

This would happen if the target used the `IntermediateAssembly` or `IntermediateRefAssembly` items without hitting any of Avalonia's targets. If no Avalonia targets execute, we cannot redirect these items to the Avalonia build output.

However, this is unlikely to happen for these reasons:

1. Avalonia targets will always run during a build.
1. If your target doesn't build the project, you almost always want the final build output (by default written to the `bin` folder), not the intermediate output. The final output file has always been processed by `CompileAvaloniaXaml`.
2. The various SDK targets which do actually return intermediate build output will all trigger Avalonia's targets.

### Mitigation
If this does prove to be a problem, we can mitigate it by copying the Avalonia build output back onto the original CSC build output. But this is not how the build system is supposed to work, so I'd rather not do it unless necessary.

## Obsoletions / Deprecations
None

## Fixed issues
Fixes #5294

### CODE REVIEW

**Comment by maxkatz6** [comment]
> I found some apparently unused code which allowed the task assembly to be run as an executable

It was commonly used to test compiled as a console app. But I would say it's easier to attach debugger.

**Comment by timunie** [comment]
> I'm serious. This fixes it, and I know exactly why.

that hit me hard 😆 

Great explanations btw! ❤️

**Comment by kekekeks** [comment]
Ah, that's what the reason why the file gets locked. We probably need a special fake output file instead, will investigate after I'm back from vacation.

> I found some apparently unused code which allowed the task assembly to be run as an executable

It's not unused, that's how we are debugging the compiler by switching the TFM.

**Comment by TomEdwardsEnscape** [comment]
Seems that it's still possible for a failure to occur, [see this comment](https://github.com/AvaloniaUI/Avalonia/issues/5294#issuecomment-1842931443). This is occurring when the task tries to copy the ref assembly to its intended output location, in the unusual case of the compiler completing successfully without producing any output. Perhaps it holds onto a file handle in this case?

**Comment by lsoft** [comment]
@kekekeks could you share any timeline for reviewing this? no pressing here, but it would be super cool for many of us to enable back a parallel builds for Avalonia-based apps, if this fix will be included into the next release of Avalonia.

**Comment by lsoft** [comment]
Hello guys! Looks like we lost the opportunity to include this in 11.0.7, but is there any chances to include this to the next release?

**Comment by timunie** [comment]
@lsoft as you may see we added the priority label just before you asked for it. So likely to be reviewed soonish. Still not sure it can be backported to 11.0.x, if not it will be available in nightly and 11.1 latest.

**Review by maxkatz6 — APPROVED** [review]

**Comment by botcher** [comment]
Really want to this fix!

**Comment by cmoaciopm** [comment]
@timunie Do you know when will the 11.1 be released? We have been suffered from this issue for quite a long time. Can't wait to get the new release. Thanks.

**Comment by timunie** [comment]
I don't have a due date to share. But I think the first beta will be soonish. Anyways if you want to have that fix now, use nightly builds. These are on 11.1 preview.

**Pull request merged**
