### PR TITLE
.NET6-Android target

### PR DESCRIPTION
**Pull request by maxkatz6**
image

### CODE REVIEW

**Comment by rstm-sf** [comment]
> Update iOS projects

Also, it would be a good change in this direction https://github.com/AvaloniaUI/Avalonia/pull/4661 :)

**Comment by maxkatz6** [comment]
Depends on https://github.com/AvaloniaUI/Avalonia/pull/7347

**Comment by maxkatz6** [comment]
Fixes #7052

**Comment by emmauss** [comment]
Any plans to rebase this?

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018440-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by maxkatz6** [comment]
@emmauss thanks, I rebased it.
Also, I removed iOS project changes for now (so this PR can be merged faster) and enabled nuget packages for android project, but it seems to fail. Even with android workload installed. Will try to fix it tomorrow.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018644-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by maxkatz6** [comment]
Android backend is finally back on the nuget. Available for net6 and old xamarin SDKs.
Version is nuget feed available in the comment above.

Simple test projects can be found here https://github.com/maxkatz6/AvaloniaAndroidTestProject
Or it's also possible to build ControlCatalog.Android project in this PR for more complete sample.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018647-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by danwalmsley — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018707-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
