### PR TITLE
Hide caret of TextBox when IsReadOnly = True

### PR DESCRIPTION
**Pull request by RayyanTahir**
This template is not intended to be prescriptive, but to help us review pull requests it would be useful if you included as much of the following information as possible:

- What does the pull request do?
This PR hides the caret of TextBox on gaining focus if IsReadOnly is True.
- What is the current behavior?
Currently a readonly textbox still shows a blinking caret when focused.
- What is the updated/expected behavior with this PR?
When TextBox's IsReadOnly property is set to True and it gains focus, the caret will not show.

### CODE REVIEW

**Review by jkoritzinsky — CHANGES_REQUESTED** [review]
Hey can you add the `IsReadOnly` check in the `TextBox.OnTemplateApplied` method as well? And possibly extract out the check to a helper method?

**Comment by Sorien** [comment]
its a bit weird in WPF couse even if textbox is readonly you should be able to select and copy (part of) text

in WPF it was fixed by IsReadOnlyCaretVisible as i remember

**Comment by RayyanTahir** [comment]
@jkoritzinsky I have made the changes you've requested, let me know if they seem okay.

@Sorien As far as I have checked in WPF, changing the value of IsReadOnlyCaretVisible has no effect on a readonly textbox, but I do see your point and have made changes so that a readonly textbox's text can be selected and copied from. Therefore IMHO adding IsReadOnlyCaretVisible will not be necessary, unless I'm missing something.

**Review by danwalmsley — APPROVED** [review]
LGTM

**Review by jkoritzinsky — APPROVED** [review]

**Pull request merged**
