### PR TITLE
Add info required by .NET foundation

### PR DESCRIPTION
**Pull request by grokys**
## What does the pull request do?

- Added CONTRIBUTING.md
- Added NOTICE.md with 3rd party licences
- Added build instructions from website
- Modified readme:
  - Move links to stuff added above
  - Add link to licence
  - Add link to CoC
  - Add link to .NET foundation

### CODE REVIEW

**Comment by MarchingCube** [comment]
We also have some code from https://github.com/jtmueller/Collections.Pooled

**Comment by grokys** [comment]
Thanks @MarchingCube - added.

**Comment by kekekeks** [comment]
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Shared/RenderHelpers/ArcToHelper.cs was ported from some Java code

**Comment by kekekeks** [comment]
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Remote.Protocol/MetsysBson.cs was imported from https://github.com/elaberge/Metsys.Bson

**Comment by grokys** [comment]
@kekekeks thanks, added that.

**Comment by maxkatz6** [comment]
There are some controls ported from microsoft-ui-xaml repo like ItemsRepeater. Should it be also included in NOTICE.md?

**Comment by grokys** [comment]
@maxkatz6 yes you're right!

**Comment by MarchingCube** [comment]
@kekekeks That `ArcToHelper.cs` looks like to be dead code - we might want to just remove it instead.

**Review by MarchingCube — APPROVED** [review]
LGTM. We can address dead code later.

**Pull request merged**
