### PR TITLE
Suppress static SKFont finalizer to prevent crashes on app exit

### LINKED ISSUE #7579: Avalonia app crashes on exit (.net framework only)
**Describe the bug**
**.net framework Avalonia app crashes on exit.** The crash is not visible unless debugging but it is present also in Event Viewer -> Application logs.
**This does not repro for .net core apps.**

**To Reproduce**
Start any Avalonia app. e.g. the sample **ControlCatalog.Desktop** (not the ControlCatalog.NetCore). On exit, the application crashes in SkiaSharp deinitialization. 

**Desktop (please complete the following information):**

- OS: Windows 10 21H1
- Version 0.10.12

**Additional context**
Message: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
```
   at SkiaSharp.Internals.PlatformLock.NonAlertableWin32Lock.EnterCriticalSection(IntPtr lpCriticalSection)
   at SkiaSharp.Internals.PlatformLock.NonAlertableWin32Lock.Enter()
   at SkiaSharp.Internals.PlatformLock.NonAlertableWin32Lock.EnterWriteLock()
   at SkiaSharp.HandleDictionary.DeregisterHandle(IntPtr handle, SKObject instance)
   at SkiaSharp.SKObject.DeregisterHandle(IntPtr handle, SKObject instance)
   at SkiaSharp.SKObject.set_Handle(IntPtr value)
   at SkiaSharp.SKNativeObject.Dispose(Boolean disposing)
   at SkiaSharp.SKObject.Dispose(Boolean disposing)
   at SkiaSharp.SKNativeObject.Finalize()
```
SKObject instance is either SKFont or GRContext

### PR DESCRIPTION
**Pull request by ltetak**
## What does the pull request do?
It fixes the crash on any .net framework avalonia application on exit.

## What is the current behavior?
Application crashes leaving log in the Event Viewer (on windows). It does not repro with .net core and might be depending on some other factors but it is easily reproducible. The impact is medium since it is on the exit but still can cause issues with the proper app shutdown.

## What is the updated/expected behavior with this PR?
Application should not crash on exit.

## How was the solution implemented (if it's not obvious)?
The problem is partially in the skiasharp pattern of disposing everything in the finalizer. Finalizer does not have well defined priority of invocations and thus the SKFont instance is finalized after a lock on which it is depending. A proper solution would be to dispose the SKFont instance but that would require a bigger architectural change. So I used a workaround (a proper solution is welcome of course).

## Breaking changes
This class is a singleton so it shouldn't create any memory leaks.

## Fixed issues
Fixes https://github.com/AvaloniaUI/Avalonia/issues/7579

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019517-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by Gillibald** [comment]
Have you tried making `s_font` a non static field? We should change that anyways if we keep that object alive. There can be multiple instances.

**Comment by ltetak** [comment]
@Gillibald that was my first instinct. The problem is who will dispose the parent object then? `PlatformRenderInterface : IPlatformRenderInterface` is not `IDisposable` so we would just shift the problem one layer up and it gets more complicated there (with multiple implementations of `IPlatformRenderInterface` and no real IoC container that would handle this for us).
If the question is just about the GC priority then it does not help. It gets finalized after the `NonAlertableWin32Lock` anyway.

**Review by Gillibald — APPROVED** [review]

**Comment by teocomi** [comment]
Hello, seems like this was not included in the [0.10.14](https://github.com/AvaloniaUI/Avalonia/compare/0.10.13...0.10.14) release, wondering if it'll make its way in the next one or if there are any blockers?

Thanks!

**Pull request merged**
