### PR TITLE
Refactor Binding Support classes and Styling

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Currently, our binding support libraries that allow us to create bindings that understand `INotifyPropertyChanged` and the like depend on our controls library. Additionally, our most user-friendly binding clases, i.e. `Binding`, are part of our XAML markup library, which they really don't need to be since they have no XAML specific features. So, I refactored these libraries to all have less dependencies on elements higher up our layered architecture:

* Avalonia.Markup -> Avalonia.Data.Core
* Data converters from Avalonia.Markup -> Avalonia.Data.Converters
* Avalonia.Markup.Xaml.Parsers -> Avalonia.Markup.Parsers
* Avalonia.Markup.Xaml.Data -> Avalonia.Markup.Data
* ControlLocator split into ControlLocator (now in Avalonia.Styling) and VisualLocator (now in Avalonia.Visuals)
* Styling, namescope, logical tree, and DataContext implementation in `Control` moved to new `Avalonia.StyledElement` class in `Avalonia.Styling`. This `StyledElement` class now inherits from `Animatable` and is inherited by `Visual`.
* `Avalonia.Styling` moved to in-between Avalonia.Animation and Avalonia.Visuals in our dependency chain (it can now go anywhere in the chain).
* Moved tests between test assemblies to now match where their tested component now lives.

New features in this PR:

* Animations can now use `Setter` for setting values.

New features this refactoring enables (just off the top of my head):

* Pseudoclasses based on complex conditions (can now use ExpressionObserver)
* Easier decoupling of XAML if we were to ever make XAML an optional (but default included) component.

### CODE REVIEW

**Comment by grokys** [comment]
Good call, this definitely needs doing. Got a few questions:

- Why `Avalonia.Data.Core`? What makes something "Core Data" as opposed to just "Data"? To me it would make more sense to just put these in `Avalonia.Data`, and indeed the WPF equivalents of these classes are in `System.Windows.Data`
- What was the reason for moving `StyledElement` so low in the hierarchy? As you say, it can be anywhere really, but previously it was near the top and now is near the bottom. What was the reasoning for this?
- Should `Binding` be moved out of the markup library? It can be useful to use it from code.

**Comment by jkoritzinsky** [comment]
The main reason I added `Avalonia.Data.Core` was that I didn't want to move it to the same place that the `IBinding` interface and related classes were since I really liked that setup. Maybe we could swap what's currently in `Avalonia.Data.Core` and `Avalonia.Data`? I think that would look the cleanest. Especially since all classes in `Avalonia.Base` only depend on the current `Avalonia.Data` namespace.


I moved styling up the hierarchy based a little on a conversation @kekekeks and I had about a year or so ago. We were talking about making the Avalonia property and binding system available more globally (outside of the UI framework). By moving the styling features below anything rendering based, we can ensure that we could do a Base + Animation + Styling release that includes all of the Property API features we have without having to touch any rendering/layout features.


We could move `Binding` out of the markup library. We could also add a dependency on `Avalonia.Markup` from `Avalonia.Controls` if we really wanted to since that dependency is no longer circular.

**Comment by grokys** [comment]
> I moved styling up the hierarchy based a little on a conversation @kekekeks and I had about a year or so ago. [...]

Yep, this makes sense I think.

> We could move Binding out of the markup library.

I think it would make sense to put `Binding` alongside `IBinding`, as the default implementation no?

> We could also add a dependency on Avalonia.Markup from Avalonia.Controls if we really wanted to since that dependency is no longer circular.

Not sure I see a reason for this yet (though it's good to have the option!)

> The main reason I added Avalonia.Data.Core was that I didn't want to move it to the same place that the IBinding interface and related classes were since I really liked that setup

Hmm yeah thinking more about it, the only public classes of note in `Avalonia.Data.Core` are `ExpressionObserver` and `BindingExpression`, right? And yeah these are implementation details to some extent of `Binding` so maybe what you have here now is a good solution.

**Comment by jkoritzinsky** [comment]
> I think it would make sense to put Binding alongside IBinding, as the default implementation no?

We can't do that since the `RelativeSource` and `ElementName` features of `Binding` require the ability to traverse the logical and visual trees, which aren't available in `Avalonia.Base`. One option would be to move `DataContext` support up to `Avalonia.Base` and include a bare-bones `BindingBase` class that supports bindings that don't require traversing any trees except the property inheritance tree.


> Not sure I see a reason for this yet (though it's good to have the option!)

The only reason I've seen so far is that the DataGrid PR requested support for reading from Bindings. But since we're spinning that off into its own repo it doesn't really matter. The main goal was to have that option available.

> Hmm yeah thinking more about it, the only public classes of note in Avalonia.Data.Core are ExpressionObserver and BindingExpression, right? And yeah these are implementation details to some extent of Binding so maybe what you have here now is a good solution.

Sounds good to me!

**Comment by grokys** [comment]
That makes sense. However `Binding` should probably be in the Avalonia.Data namespace?

Maybe we should make the Avalonia.Markup project's default namespace Avalonia, move the other stuff in there into a Markup directory and move Binding out into a top-level Data directory - just to keep the directory structure and the namespace structure the same?

**Comment by jkoritzinsky** [comment]
@grokys Can you take another look and let me know if there's anything else you want me to do?

**Review by grokys — APPROVED** [review]
Looks good! Lets get this merged and see how we go.

**Pull request merged**
