### PR TITLE
Update ProgressBar.cs float comparison fix

### PR DESCRIPTION
**Pull request by j123123**
float comparison fix. Maybe Math.Abs doesn't need here because Maximum should be always greater than Minimum

### CODE REVIEW

**Comment by grokys** [comment]
Thanks for the PR! I think you're right that `Math.Abs` shouldn't be needed.

**Comment by j123123** [comment]
ok

**Comment by ForNeVeR** [comment]
I cannot get why are you using `Single.Epsilon` here. Both Minimum and Maximum are `double`. And you better get rid of this `using System` - it does not seem to fit the code style very well.

**Comment by j123123** [comment]
ok, fixed

**Comment by ForNeVeR** [comment]
:+1:

**Comment by ForNeVeR** [comment]
Wait. According to [that](http://stackoverflow.com/questions/20222314/is-math-absx-double-epsilon-equivalent-to-math-absx-0d), the comparison with `double.Epsilon` is complete equivalent of direct comparison with zero. Maybe we should use some calculated epsilon value based on our `Maximum` / `Minimum` value range? Any thoughts on this?

**Comment by j123123** [comment]
>Comparison with double.Epsilon is complete equivalent of direct comparison with zero.

no. On ARM, `double.Epsilon` is `0d`, and in this case, `somevar < 0d` always false
https://msdn.microsoft.com/en-us/library/system.double.epsilon%28v=vs.110%29.aspx?cs-save-lang=1&cs-lang=csharp
>On ARM systems, the value of the Epsilon constant is too small to be detected, so it equates to zero. You can define an alternative epsilon value that equals 2.2250738585072014E-308 instead. 

looks like we need machine epsilon https://stackoverflow.com/questions/9392869/where-do-i-find-the-machine-epsilon-in-c

**Comment by grokys** [comment]
What is the current status of this PR?

**Comment by ForNeVeR** [comment]
Well, we're still not sure how to determine a proper IEEE machine epsilon value in a cross-platform way.

**Comment by ForNeVeR** [comment]
@grokys, I'll try to take a look at the current situation in the nearest days. Please do not merge or close it right now.

**Comment by grokys** [comment]
Superseded by #331

**Pull request closed without merging**
