### PR TITLE
Fix IsChecked property differing from :checked pseudoclass

### PR DESCRIPTION
**Pull request by ThereGoesMySanity**
## What does the pull request do?
Fixes a bug where `IsChecked` could be true on a button without the `:checked` pseudoclass, so it would appear unchecked on the UI.

## What is the current behavior?
`SetAndRaise` does not always change the property value, but `UpdatePseudoClasses` would always be called with the new value, regardless of whether or not it was actually applied.

## What is the updated/expected behavior with this PR?
`IsChecked` should now always remain in sync with the `:checked` and `:unchecked` pseudoclasses.

## How was the solution implemented (if it's not obvious)?
Call `UpdatePseudoClasses` with the actual value of `IsChecked`, not the (possibly incorrect) new value.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=4840) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=4840) before we can accept your contribution.<br/><br/>:x: ThereGoesMySanity [sign now](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=4840)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/AvaloniaUI/Avalonia?pullRequest=4840) it.</sub>

**Comment by maxkatz6** [comment]
Thanks!
Shouldn't it be updated from OnIsCheckedChanged method? Method should be also fine with DirectProperty though.

**Comment by ThereGoesMySanity** [comment]
I don't know the code well enough to say - the UpdatePseudoClasses call was already in the setter, so I left it there.

**Comment by maxkatz6** [comment]
@ThereGoesMySanity do you have steps to reproduce this issue or some minimal example?

**Comment by ThereGoesMySanity** [comment]
It happens when one of the subscribers of the IsChecked property changes IsChecked. After the nested call completes, the `value` parameter from the first call is passed to UpdatePseudoClasses after it has become stale.

Minimal example (using avalonia.app template):
```
        public RadioButton radio;
        public MainWindow()
        {
            InitializeComponent();
            this.AttachDevTools();
            this.FindControl<Button>("Button").Click += OnClicked;
            radio = this.FindControl<RadioButton>("Radio");
            radio.GetObservable(RadioButton.IsCheckedProperty).Subscribe(OnCheckedUpdated);
        }

        private void OnClicked(object sender, RoutedEventArgs args)
        {
            radio.IsChecked = false;
        }

        private void OnCheckedUpdated(bool? newValue)
        {
            if (newValue == false)
            {
                radio.IsChecked = true;
            }
        }
```
```
    <Window.Styles>
        <Style Selector="RadioButton:unchecked[IsChecked=true]">
            <Setter Property="Background" Value="red"/>
        </Style>
    </Window.Styles>
    <Grid RowDefinitions="*,*">
        <RadioButton Name="Radio" IsChecked="True">Test</RadioButton>
        <Button Name="Button" Content="UpdateValueTest" Grid.Row="1"/>
    </Grid>
```

**Comment by danwalmsley** [comment]
@maxkatz6 I can see why that fixes it... hmmm maybe if psuedoclasses was updated in OnPropertyChanged this would never have happened.

**Review by danwalmsley — APPROVED** [review]
LGTM

**Pull request merged**
