### PR TITLE
[Win32] Use WS_EX_LAYERED style for native control holders with winui composition

### LINKED ISSUE #7106: NativeControlHost doesn't work properly with most native control when UseWindowsUIComposition enabled
**Describe the bug**
Native control is embed but not rendered on the window. It still possible to interact with mouse, but visual any visual response.

**To Reproduce**

1. Clone latest master
2. Change NativeEmbedSample config to include lines
```csharp
.With(new Win32PlatformOptions
{
    UseWindowsUIComposition = true
})
```
3. Run this sample on windows

**Expected behavior**
Control is rendered.

**Screenshots**
image

**Desktop (please complete the following information):**

- OS: Windows
- Version 0.10.x

**Additional information**

This issue is not reproducible with newer native controls such as WebView2

### PR DESCRIPTION
**Pull request by kekekeks**
Fixes #7106

### CODE REVIEW

**Review by maxkatz6 — APPROVED** [review]

**Comment by adirh3** [comment]
@kekekeks after this change the `DumbWindow` is never created (when using composition), causing previous native controls to not work anymore.
I checked it a bit and it seems like to create a layered *child* window you need to use specific manifest file - https://docs.microsoft.com/en-us/windows/win32/winmsg/using-windows
Works after doing so, but might want to somehow make it work from Avalonia or at least throw an exception

**Comment by maxkatz6** [comment]
Can we possibly detect if manifest is missing or not?
Otherwise, we can throw an exception if Handle is empty with information that manifest is required. It might be less useful, because window handle can be empty for many other reasons too.

I am not sure if it's the best idea if we force users to use manifest. I don't think other frameworks do that. Although we definitely can include it with templates.

**Comment by adirh3** [comment]
> Can we possibly detect if manifest is missing or not? Otherwise, we can throw an exception if Handle is empty with information that manifest is required. It might be less useful, because window handle can be empty for many other reasons too.
> 
> I am not sure if it's the best idea if we force users to use manifest. I don't think other frameworks do that. Although we definitely can include it with templates.

If it's missing, then `CreateWindowEx` will fail which I think should be identifiable using `GetLastError`.
One thing we can do is fallback to non-layered window if layered one fails and have a warning log.

**Comment by kekekeks** [comment]
IMO we should just retry creating the window without WS_EX_LAYERED.

**Pull request merged**
