### PR TITLE
Zero reflection unicode data

### PR DESCRIPTION
**Pull request by Gillibald**
## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0021260-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by Gillibald** [comment]
Trie generation isn't trivial and should not happen every build. Embedding the data as source files is totally fine. This is internal and all trie generation is part of the project.

**Comment by kant2002** [comment]
I miss code generation part because it was in `tests` folder. Shouldn't codegen be located closer to `src` folder, I definitely would not look into `tests` folder for the coden.

**Comment by Sergio0694** [comment]
You can use a `ReadOnlySpan<byte>` to skip allocating the array entirely, as well as to skip the startup initialization. You can then pass that data to the constructor by pinning the span and creating an unmanaged memory stream over it 🙂

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0021262-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0021272-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0021353-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
