### PR TITLE
Popup focus fixes

### LINKED ISSUE #3639: Textbox doesn't focus when placed in popup
When textbox is placed in popup, no focus is given when clicked on it. It behaves similarly to if IsReadOnly = true, as text can still be highlighted but not edited and it still recognizes when the cursor is over the textbox. 
A textbox will work normally if its set as the header to a MenuItem in a Menu or ContextMenu, however. The only special thing I can find within MenuBase is the InteractionHandler, but I don't know if that adds extra logic that allows it to work when a textbox is within a Menu.
I'm trying to create something along the lines of the WinUI Flyout so the popup control is not part of a control template and is generated in code. All other controls (Button, ComboBox, CheckBox, etc) still work as intended.

### PR DESCRIPTION
**Pull request by amwx**
## What does the pull request do?
After some digging around a little, I finally (hopefully) figured out why Textboxes don't play nice with focus when placed in a popup. 
In `FocusManager`
````
public void Focus(
            IInputElement control, 
            NavigationMethod method = NavigationMethod.Unspecified,
            KeyModifiers keyModifiers = KeyModifiers.None)
        {
            if (control != null)
            {
                var scope = GetFocusScopeAncestors(control)
                    .FirstOrDefault();

                if (scope != null)
                {
                    Scope = scope;
                    SetFocusedElement(scope, control, method, keyModifiers);
                }
            }
...
````
`scope` is null because `PopupRoot` doesn't implement `IFocusScope` so attempting to set focus on any control within a popup through `Control.Focus()` or `FocusManager.Instance.Focus()` failed. This also meant that Tab navigation would have to be handled on the host control/PlacementTarget of the popup to work properly.
I checked with WPF's source and if no FocusScope is found, they still allow focus to be placed on the control and just make it an implicit FocusScope: (line 414)
https://referencesource.microsoft.com/#PresentationCore/Core/CSharp/System/Windows/Input/FocusManager.cs,970b54bfb95832d9,references

This PR just marks `PopupRoot` as `IFocusScope` which seems to work as expect compared with WPF, and AFAIK doesn't disrupt behavior of existing popup navigation logic (i.e. context menus, menus), so it shouldn't break anything. 
TextBox can now be focused, and using the Tab key will keep focus contained within the popup instead of directing it back to the main window. I didn't want to mess with FocusManager and the implicit focus scope idea of WPF to not break anything

## Checklist

- [x] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

## Fixed issues
Fixes #3639

### CODE REVIEW

**Review by grokys — APPROVED** [review]

**Comment by amwx** [comment]
@danwalmsley Unless I wrote something in the test that doesn't play nice with the CI, I don't know why its failing. It's another of the "it works locally, but fails here." I can skip the test as I know the fix does work.

image

**Comment by danwalmsley** [comment]
@grokys any ideas about this test that works locally but fails on CI?

**Review by danwalmsley — DISMISSED** [review]
hopefully we can either agree to skip the test, or find a fix for it.... adding this to prevent merge until we have a consensus on this.

**Comment by grokys** [comment]
It doesn't seem to be that test that's failing - seems to be something in `LeakTests`, most likely unrelated. Lets see if it passes now.

**Comment by amwx** [comment]
@grokys @danwalmsley 
I finally got the test to fail on my end, not sure why it wasn't before? Anyway, digging into this a little more, it seems the test is using an `OverlayPopupHost` instead of a `PopupRoot` which also makes the test pointless since it's not using `PopupRoot`, however, it did make me think maybe the implementing of `IFocusScope` shouldn't just be on `PopupRoot` but maybe on `IPopupHost` that way it applies to both overlay and regular popups (so the behavior is the same). But I found another issue that I think is behind the test failing...
It seems `OverlayPopupHost` doesn't set its visual children, as none of the controls placed in the popup have their `VisualRoot` set (it's null) and a `GetVisualDescendents()` call on the popup host returns no visual children. This prevents the focus manager from working properly cause it uses the `VisualRoot` of the control requesting focus to find the focus scope and the test fails.

image

image

**Comment by amwx** [comment]
@grokys  @danwalmsley 
I think I've managed to figure this out. I moved implementing `IFocusScope` to `IPopupHost` so it works for both `PopupRoot` and `OverlayPopupHost`. I think the issue was I didn't realize the test ran twice, once using a popuproot and again using the overlayhost and when I got it to pass locally I think I was running only the popuproot version. Also didn't know you have to call `Measure` and `Arrange` on an `OverlayPopupHost` to get the visual tree to realize (my last comment).
Anyway, everything seems to work now and hopefully this can be merged now

**Comment by grokys** [comment]
Thanks @amwx - glad you figured it out. Seems like the failing test actually pointed you in the right direction in the end :)

**Pull request merged**
