### PR TITLE
Added Osx-Command keys to Key-enum

### LINKED ISSUE #10889: Improve Keys-Enum
These keys seems to be also used for the MacOS command key (`⌘`)
https://github.com/AvaloniaUI/Avalonia/blob/e4ed304234ee69dab7cd300afafe659869e11172/src/Avalonia.Base/Input/Key.cs#L397-L405. 

IMO we should either: 
- Rename the key (which is a breaking change)
- (or) improve the XML-comment to reflect this. 

**Related**: 
https://github.com/AvaloniaUI/Avalonia/discussions/10690#discussioncomment-5494917 

Anyone owning a Mac, can you confirm this?

### PR DESCRIPTION
**Pull request by timunie**
## What does the pull request do?
Adds `OsxLeftCommand` and `OsxRightCommand` alias keys to Key-enum. 

## What is the current behavior?
A developer who is developing an App for Mac-OS has to know that `LWin` and `RWin` is the commands key on Mac-OS. However, this is not very intuitive.

## What is the updated/expected behavior with this PR?
We have an alias for these keys in order to reduce confusion

## Checklist

- [ ] Added unit tests (if possible)?
- [x] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Fixed issues
Fixes #10889

### CODE REVIEW

**Comment by timunie** [comment]
@Mikolaytis instead of reacting with 👎 , can you please share your thoughts with me? Is the name misleading? Is the key the wrong key? 

Note: I don't own a Mac, so I cannot test is on my own.

**Comment by timunie** [comment]
@maxkatz6 I looked up an image of the Mac-keyboard and saw they have a left and right command-key. Are they mapped to the same key internally? 

image

**Comment by maxkatz6** [comment]
@timunie yes, the same key, as far as I can tell.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0032744-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by Mbucari** [comment]
@maxkatz6 I've tested this on a genuine mac, and I can confirm that the left and right keys do in fact have different key codes. the left command maps to LWin, and the right command maps to RWin.

**Comment by timunie** [comment]
Marked as WIP because due to @Mbucari feedback I'd rather like to revert the last commit.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0032848-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by Mikolaytis** [comment]
> @Mikolaytis instead of reacting with 👎 , can you please share your thoughts with me? Is the name misleading? Is the key the wrong key?
> 
> Note: I don't own a Mac, so I cannot test is on my own.

I just don't like it. I don't like when we have multiple enum names for a same value. This way we can add tones more names for OEM keys and other things and I think that this is not a good idea.
Also I don't think that my dislike is something I want to defend or discuss, thats why I didn't post anything. But thanks for asking.

**Comment by Mbucari** [comment]
> This way we can add tones more names for OEM keys and other things

Sounds great! Where do I sign?

Joking aside, your "explanation" amounts to little more than "because I don't want it". That's no reason to deny a feature to someone else. A feature, I might add, that in no way impacts your use of the library. You're used to using Windows names? Great! Keep using them.

**Comment by jmacato** [comment]
Any updates on this @timunie?

**Comment by maxkatz6** [comment]
I am going to close this PR, as we didn't have any agreement on this API.
And in overall, current implementation is not correct, since these keys actually have different values.

**Comment by timunie** [comment]
all right, understood.

**Pull request closed without merging**
