### PR TITLE
Defer `bring into view` for newly created TreeViewItem

### LINKED ISSUE #9173: TreeView doesn't autoscroll for a newly added and selected item.
**Describe the bug**
TreeView `AutoScrollToSelectedItem` property doesn't work when `SelectedItems` is setting immediately after it has been added in nodes collection.

**To Reproduce**

ViewModel's Code:
``` c#
// *** //
public ObsevableCollection<Node> Nodes {get;} = new();

public Node SelectedNode
{
    get => _selectedNode;
    set => this.RaiseAndSetIfChanged(ref _selectedNode, value);
}

public void AddNode()
{
    var node  = new Node();
    Nodes.Add(node);
    SelectedNode = node;
}

// *** //
```

View's Code:
``` xml
     <!-- *** -->
     <Button Command="{Binding AddNode}"/>
     <TreeView Items="{Binding Nodes}" 
               SelectedItem="{Binding SelectedNode}"
               AutoScrollToSelectedItem="True" />
                      
    <!-- *** -->
```

When button clicked, new node had added in `Nodes` collection, but `TreeView` hadn't scrolled to corresponding `TreeViewItem`. 

**Expected behavior**
TreeView scrolls to newly created and immediately selected item.

**Desktop (please complete the following information):**

- OS: Windows
- Version: 0.10.17

**Additional context**
Looks like the problem is _TreeViewItem.cs_:
```cs
protected virtual void OnRequestBringIntoView(RequestBringIntoViewEventArgs e)
{
    if (e.TargetObject == this && _header != null) // <-- when the `TreeView` calls to BringIntoView, 
                                                   //     the `TreeViewItem` (for new Node) has not applied 
                                                   //     template yet, and _header is null.
    {
        //***// 
    }
}
```

### PR DESCRIPTION
**Pull request by dif-sam**
## What does the pull request do?
Trying to deffere request for BringIntoView, when TreeViewItem not ready yet. 

## Fixed issues
Fixes #9173

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0024661-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0024703-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by grokys — APPROVED** [review]
👍 makes sense I think.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0025386-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
