### PR TITLE
Added SlicedImage

### PR DESCRIPTION
**Pull request by JurjenBiewenga**
Adds a 9 sliced control

Issues:
If the width or the height is smaller than the borders then it renders on top of each other.
DPI scaling?

### CODE REVIEW

**Comment by JurjenBiewenga** [comment]
I don't think there is a proper way to fix the issue as you would have to scale the corners which will still look weird and out of place.

**Comment by grokys** [comment]
I can see this being useful, but I'm not sure it should be in core Avalonia. Do you want to try to convince us that it should be there?

**Comment by JurjenBiewenga** [comment]
In my opinion it largely depends on what you want Avalonia to be, if you'd eventually would like to compete in the cross platform app development scene or the web development scene then 9 sliced images are a must as to support the multitude of different resolutions and aspect ratios. Even if you would not like to support those platforms then 9 slicing is still very valuable to have perhaps not in the core repository but still as an official extension.

**Comment by grokys** [comment]
I would have thought that 9 sliced images react worse to different resolutions than vector graphics and they'd be used in situations where speed was required over resolution-independence, is that not correct?

**Comment by JurjenBiewenga** [comment]
From my limited understanding of SVG usage, they're generally used to keep the same image nice and clean at different resolutions, 9 patch/sliced images allows you to scale an image in the width and height while maintaining a good quality image.

**Comment by JurjenBiewenga** [comment]
What would be the correct way to handle different dpi settings as the user currently sets how many pixels he wants to remain the same which is not scaled by the dpi settings.

**Comment by grokys** [comment]
I'm going to close this as I don't think it's suited for the main avalonia repository. I think it should be developed in a separate repository and if there's enough demand for it, we can talk about moving it here.

**Pull request closed without merging**
