### PR TITLE
Don't cast android scaling from double to int

### PR DESCRIPTION
**Pull request by maxkatz6**
While checking https://github.com/AvaloniaUI/Avalonia/issues/8150 issue I noticed that we round trim scaling (i.e. from 2.5d to 2) down casting it to int.
Not sure if it is intended or I am missing something.

### CODE REVIEW

**Comment by maxkatz6** [comment]
@emmauss @jp2masa @kekekeks

**Comment by maxkatz6** [comment]
Before:
image
After
image

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0020589-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by jp2masa — APPROVED** [review]
Looks good!

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0020615-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by jmacato — APPROVED** [review]

**Pull request merged**
