### PR TITLE
Don't run layout on hidden TopLevels

### LINKED ISSUE #4161: macos crash on tooltip closing
On 0.9.999-cibuild0008603-beta my app crashes on High Sierra 10.13.6 when the mouse is moved once a tooltip is shown (i.e. when the tool tip closes) with
```
System.NullReferenceException: Object reference not set to an instance of an object.
at Avalonia.Native.ScreenImpl.get_AllScreens()
at Avalonia.Native.WindowBaseImpl.get_MaxAutoSizeHint()
at Avalonia.Controls.Primitives.PopupRoot.MeasureOverride(Size availableSize)
at Avalonia.Controls.WindowBase.MeasureCore(Size availableSize)
at Avalonia.Layout.Layoutable.Measure(Size availableSize)
at Avalonia.Layout.LayoutManager.Measure(ILayoutable control)
at Avalonia.Layout.LayoutManager.Measure(ILayoutable control)
at Avalonia.Layout.LayoutManager.Measure(ILayoutable control)
at Avalonia.Layout.LayoutManager.Measure(ILayoutable control)
at Avalonia.Layout.LayoutManager.ExecuteMeasurePass()
at Avalonia.Layout.LayoutManager.ExecuteLayoutPass()
at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
at Avalonia.Native.PlatformThreadingInterface.SignaledCallback.Signaled(Int32 priority, Boolean priorityContainsMeaningfulValue)
at Avalonia.Native.Interop.IAvnSignaledCallbackShadow.IAvnSignaledCallbackVtbl.Signaled(IntPtr thisObject, Int32 param0, Byte param1)
--- End of stack trace from previous location where exception was thrown ---
at Avalonia.Native.PlatformThreadingInterface.RunLoop(CancellationToken cancellationToken)
at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetimeT
at SparkSDR.Program.Main(String[] args)
```

### PR DESCRIPTION
**Pull request by grokys**
## What does the pull request do?

Make `ILayoutManager` implement `IDisposable` and make the `TopLevel` dispose it when closing. This allows layout passes to be run before a window/popup is shown but prevents them being run after close. It also clears the layout queues on dispose, fixing a problem @MarchingCube was seeing (see thread below).

## Fixed issues

Fixes #4161

### CODE REVIEW

**Comment by grokys** [comment]
@danwalmsley I do think however that `Avalonia.Native.ScreenImpl.get_AllScreens` shouldn't throw a NRE when called for a closed toplevel.

**Comment by grokys** [comment]
Looks like this might not be optimal: for embedding scenarios it can be useful to run a layout before a window is shown. We should probably only prevent layout after closing, perhaps by disposing the `LayoutManager`.

**Comment by MarchingCube** [comment]
Disposing and clearing `LayoutManager` can be useful to make sure that nothing is leaked as well. I guess some of memory leaks I had were caused by layout queues containing items after close, we also don’t clear jobs when shutting down (and layout requests are enqueued as jobs) which can lead to controls being kept alive by random delegates.

**Comment by grokys** [comment]
Made that change. @MarchingCube this should fix layout queues holding onto items after the window is closed.

**Review by MarchingCube — APPROVED** [review]
LGTM.

**Pull request merged**
