### PR TITLE
Publish test results and make task names more readable.

### LINKED ISSUE #2035: Publish test results
Publish the test results from builds in Azure DevOps so test failures show up in GitHub PR checks.

### LINKED ISSUE #2036: Add display names for build phases
The current build steps are not very descriptive. We should add display names so we can more easily figure out where a build fails at a glance.

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Publish our test results so failed tests will show up on GitHub PR Checks. Also add display names for each task so we can more easily understand which build step is currently running.

Fixes #2035
Fixes #2036

### CODE REVIEW

**Comment by jkoritzinsky** [comment]
@grokys @danwalmsley can you take a look at this?

**Comment by grokys** [comment]
Any chance we could see what a failing test looks like now?

**Comment by jkoritzinsky** [comment]
Here’s an example from another project of mine: https://github.com/jkoritzinsky/AggregatePackage.NuGet.Sdk/pull/1/checks

**Comment by jkoritzinsky** [comment]
Screenshot for the curious:
c0becc2e-9099-417c-b724-b1aa7582dd4c

**Review by danwalmsley — APPROVED** [review]
LGTM

**Pull request merged**
