### PR TITLE
Fix for window animations for undecorated Win32 window

### PR DESCRIPTION
**Pull request by mstr2**
## What does the pull request do?
https://github.com/AvaloniaUI/Avalonia/pull/3221 describes the original problem and solution.

Back when Windows did not have multi-screen support, maximized windows were supported by simply placing the window at negative x/y screen coordinates and extending the size of the window slightly, so that the window border would be off-screen and invisible to the user.

To maintain compatibility, Windows still uses this positioning behavior for maximized windows, even though DWM will exclude the "off-screen" parts of the window from rendering.

Notably, this only applies to a maximized window. If a window is instead docked to the sides of the screen, Windows will not place it at negative screen coordinates.

This PR fixes this issue by adjusting the client area of a maximized window such that it matches the visible screen area by subtracting the "off-screen" border.

## Known issues
When a maximized window is resized manually via `IWindowImpl.BeginResizeDrag`, it doesn't seem to lose the maximized state. This results in receiving `WM_SIZE` with the `SIZE_MAXIMIZED` flag still set. In this case, `GetWindowPlacement` will also continue to report `SW_SHOWMAXIMIZED`.

As a result, the client area will not be updated to the correct size (remember, this PR adjusted the client area specifially for the maximized state). The client area will remain offset from the window until the maximized state is removed from the window.

It seems to me that the issue here is that it's possible to resize a maximized window. I think window sizing should be left to the operating system.

For Windows, this means that rather than invoking window sizing manually, the `WM_NCHITTEST` message should be handled by enabling a user-configurable callback to classify which coordinates correspond to each of the window parts (title bar, four corners, four edges).

Correctly implementing `WM_NCHITTEST` also enables missing window interactions like double-clicking the titlebar to maximize or restore the window.

### CODE REVIEW

**Comment by kekekeks** [comment]
We could simply disable BeginResizeDrag when window is in maximized state, since that operation is invalid anyway.

**Comment by mstr2** [comment]
I removed `Window.BeginMoveDrag` and `Window.BeginResizeDrag` in favor of
```C#
Func<Point, WindowRegion> IWindowImpl.ClassifyWindowRegion { get; set; }
```

This function should be provided for an undecorated window that wants to show custom move/size decorators. If the function is provided, the windowing platforms will use it to trigger platform-specific move/resize behavior. A simple implementation might look like this:
```C#
PlatformImpl.ClassifyWindowRegion = point =>
{
    if (this.InputHitTest(point) == this.FindControl<Control>("TitleBar"))
    {
        return WindowRegion.TitleBar;
    }
    return WindowRegion.ClientArea;
};
```

This will allow a window to be moved, but not resized. Correctly classifying all window regions will enable moving and resizing behavior.

For Win32, `WM_NCHITTEST` is now fully implemented, which also enables the system-provided default window interactions (e.g. double-click to maximize or restore a window).

The weird Win32 corner case where an undecorated window is resized with using custom resize grips while it is still maximized is now handled by restoring the window to normal state.

I did test the changes on OSX and Linux, and as far as I can tell, the behavior is unchanged.

**Comment by mstr2** [comment]
Double-click to maximize/restore is now also working for the macOS platform.
Tested on macOS Catalina.

**Comment by Splitwirez** [comment]
> We could simply disable BeginResizeDrag when window is in maximized state, since that operation is invalid anyway.

I know this is an ancient issue, but...just for future reference, I'd like to point out that no, that operation is not invalid. As of Windows 7, a maximized window can be dragged around by its titlebar, and initiating this drag also un-maximizes the window.

**Comment by jmacato** [comment]
Closing this PR for inactivity. Ping me if this is updated accordingly.

**Pull request closed without merging**
