### PR TITLE
Make Bitmap Implement IDisposable

### LINKED ISSUE #135: Bitmap should implement IDisposable

### LINKED ISSUE #904: Bitmap disposal
Since bitmaps typically consume tons of memory, it's worth to have an option to explicitly dispose them. However, if bitmap is already used somewhere, application will just crash, and that's not what we want.

So the proposal is to have a static instance of transparent 1x1 bitmap, which will be used as a substitute for `BitmapImpl` in `Bitmap` class. It should be provided by rendering subsystem and never get disposed. That way we won't need complex checks in our rendering code to determine if we can use bitmap or not.

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Fix #904. Fix #135.

@kekekeks can you take a look? I'm not sure if I put dispose implementations in all of the correct places within `DeferredRenderer.

### CODE REVIEW

**Comment by kekekeks** [comment]
I don't quite like the design of having COM-like AddRef/Release because it breaks `Dispose` semantics (multiple calls to dispose should not break things). I have a some refcounting code and add it to your PR tomorrow, so, please, refrain from merging it for now.

**Comment by jkoritzinsky** [comment]
Multiple calls to dispose won't break things with this refcounting infrastructure. And this refcounting is thread safe.

**Comment by kekekeks** [comment]
The thing is that `Dispose` doesn't have the same semantics as `Release` in COM. You can call `Dispose` multiple times, like:

```cs
using(var stream = File.Open(...);
{
     stream.Dispose();
     stream.Dispose();
     stream.Dispose();
}
```

And that's completely fine. You can't do that for refcounting, because the reference count will be incorrect after multiple calls to Release that weren't matched by AddRef calls previously.

**Comment by jkoritzinsky** [comment]
One thing to note is SharpDX uses the same model I'm proposing here for ref-counting (Dispose lowers the refcount).

**Comment by grokys** [comment]
Yeah, I'm not sure either about putting ref-counting into `Dispose`, it's true that SharpDX _kinda_ does use `Dispose` for ref counting but that feels more acceptable to me because it's COM underneath. Having said that though, this is all in `Impl` classes so it's not like we're exposing a refcount `Dispose` in our public API.

I don't know if you've sope about this, but I remember a while back having a conversation with @kekekeks about maybe actually disposing the underlying bitmap on the UI thread, and if there is a race with the render thread then either nothing or a blank image would be drawn.

**Pull request closed without merging**
