### PR TITLE
Feature/data grid custom sorting

### PR DESCRIPTION
**Pull request by maxkatz6**
## What does the pull request do?
1. Adds Sorting event that allows to change SortDescriptions before sorting or replace Items source with sorted by custom algorithm and set Handled to "true". Event API is same as in WPF and WCT (WindowsCommunityToolkit), sorting implementation is a bit different though.
2. Adds ICompare argument to DataGridSortDescription.FromPath method, so it is easier to define sorting without creating custom DataGridSortDescription.
3. Changed DataGridSortDescription.Descending (bool) to DataGridSortDescription.Direction (ListSortDirection) to be in-line with WPF. In WCT they have custom enum with same values.

## What is the current behavior?
It is impossible to define custom sorting algorithm.

## What is the updated/expected behavior with this PR?
It is possible to define custom sorting algorithm.

## Checklist

- [ ] Added unit tests (if possible)?
- [x] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

## Breaking changes
DataGridSortDescription.Descending is now obsolete - "Use Direction property to read or override sorting direction."
DataGridSortDescription.FromPath(string, bool, CultureInfo) is now obsolete - "Use overload taking a ListSortDirection."

### CODE REVIEW

**Comment by maxkatz6** [comment]
@grokys test is failing "Avalonia.LeakTests.ControlTests.Attached_ContextMenu_Is_Freed [FAIL]".
It doesn't seem to be related to this PR.

**Comment by MarchingCube** [comment]
Should we make `DataGridSortDescription.SwitchSortDirection` public as well?

**Comment by maxkatz6** [comment]
@MarchingCube done.

**Review by MarchingCube — APPROVED** [review]
LGTM.

**Comment by stepangovorko** [comment]
@maxkatz6 Thanks for this feature. But I tried to use it and found that it lacks one thing:
If you want to fully override sorting you have to handle multi-column sorting cases. To do this PointEventArgs is needed to understand Ctrl/Shift modifier keys are pressed. There is no such issue in WPF, because we have static Keyboard.IsKeyDown(), but in Avalonia we don`t have it. 
Do you have an idea how about good solution here?

**Comment by maxkatz6** [comment]
@stepangovorko it's not always possible to get current keyboard state in crossplatform environment, but you can handle keydown events and save previous state, that you cab handle. You probably will need to register handler in Tunnel mode instead of Bubble (alternative to PreciewKeyDown).

**Pull request merged**
