### PR TITLE
fix LayoutTransformControl and add comment.

### PR DESCRIPTION
**Pull request by lindexi**
fix equality comparison of the double number

### CODE REVIEW

**Review by grokys — APPROVED** [review]
LGTM I think. Could you go in to a little detail as to what problem you were seeing that this fixes?

**Comment by lindexi** [comment]
@grokys I only downloads the code and add some comment.

When I found LayoutTransformControl that use `==` to check two double that I dont think its a good way. I try to change the equality comparison of the double number to Math.Abs.

**Comment by grokys** [comment]
Hmm, in that case I'm not sure these changes are needed, as they're essentially just short-circuits as far as I can tell, and the code comes from the [silverlight toolkit](https://github.com/MicrosoftArchive/SilverlightToolkit/blob/master/Release/Silverlight4/Infrastructure/TestFramework/Client/LayoutTransformer.cs#L421) which comes from Microsoft themselves.

I'd be convinced if you could come up with a case where the current logic fails.

@donandren you ported this, what do you think?

**Comment by lindexi** [comment]
@grokys  Equality comparison of the double number is easily put the unexpected result when the double passed the calculation.  In my opinion,  Equality comparison of the double number is only used to compare two double that have only define and never do any calculation.

            double a = 0.4d + 0.3d + 0.2d + 0.1d;
            double b = 1;
            System.Console.WriteLine(a==b);//false a=1 b=1

**Comment by donandren** [comment]
@grokys code comes from microsoft silverlight toolkit  (it's been tested and worked there many many years).
also not sure this change what performance impact will have this new changes.
all the changes are related to comparison with 0 which looks pretty safe to me in the original code

**Comment by grokys** [comment]
I'm going to close this because I don't think it's correct and in fact I think it will cause jumps in animations that are magnified a lot. Let me know if you think I'm wrong ;)

**Comment by grokys** [comment]
Also, if you'd like to submit another PR with your documentation comments, I'd accept that!

**Comment by lindexi** [comment]
@grokys Ok

**Pull request closed without merging**
