### PR TITLE
Added unit-tests for the Select All option of the TreeView.

### PR DESCRIPTION
**Pull request by Michron**
## What does the pull request do?

This PR adds unit-tests for the Select All option in the `TreeView` to showcase a bug in the Select All feature if items are already selected in a top to bottom order.
I've only tested this for the `TreeView` class, but it could be that the `SelectingItemsControl` is also affected by this bug.

## What is the current behavior?

Currently if a user selects a range of items in a multi-select `TreeView` from the top to bottom, and then presses `Ctrl+A` (or any other hotkey for Select All) it will deselect some of the last selected items. This is caused by `SelectingItemsControl.SynchronizeItems` which doesn't work properly if the lists are not in the same order.

## What is the updated/expected behavior with this PR?

The expected behaviour would be to always select all items in the list when Select All is pressed.

## How was the solution implemented (if it's not obvious)?

This PR does not include a fix for the problem yet, it only shows the bug by adding unit-tests. Possible ways to fix this:
* Clear the list of currently selected items before synchronizing the list.
* Reversing the currently selected items based on how they are sorted (can be very tricky if the list is in a random order).
* Adding a check in `SynchronizeItems` to detect if an item from `desired` is already in the `items` list.

## Checklist

- [X] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

### CODE REVIEW

**Comment by grokys** [comment]
pinging @MarchingCube

**Comment by MarchingCube** [comment]
@grokys I didn't implement the select all functionality - it was @MonkAlex. But I think the root of the problem here is `SelectingItemsControl.SynchronizeItems` which both of us didn't touch. I wonder why we can't just clear the list and add new items. Is this some compatibility issue, or there is another reason?

**Comment by grokys** [comment]
Ah ok, thanks for pointing that out ;)

I think the reason was that when an additional item is selected, you don't want to send a deselected and then a selected message for any existing selected item.

**Comment by Michron** [comment]
I've changed `SynchronizeItems` so it now removes items that are already in the list before inserting them in the proper location. This does mean it will cause an add and remove event to be invoked, instead of the move event if it's on an `AvaloniaList`. I was thinking of casting the list to an `AvaloniaList` so I can use the `Move` method, but that was getting pretty tricky and ugly.

**Comment by grokys** [comment]
Thanks for this @Michron! And sorry for taking so long to get around to it - I thought from the description that it was only a unit test, I didn't realise it also contained a fix! If I'd have known that I'd have gotten around to it sooner.

I think your fix looks good, though I'm going to have a go at using `Move` when it's available.

**Review by grokys — APPROVED** [review]
Looks good to me, thanks!

**Pull request merged**
