### PR TITLE
add support for RGBAF16 pixel format.

### PR DESCRIPTION
**Pull request by danwalmsley**

### CODE REVIEW

**Comment by danwalmsley** [comment]
Tested both bitmap and writeable bitmap:

```
var bmp = new WriteableBitmap(new PixelSize(100, 100), new Vector(96, 96), PixelFormat.RgbaF16);

                using var framebuffer = bmp.Lock();

                var span = new Span<FPixel>(framebuffer.Address.ToPointer(), 100 * 100);
                
                for (int i = 0; i < (100 * 100); i++)
                {
                    span[i].R = (Half)1.0f;
                    span[i].A = (Half)1.0f;
                }

                image.Source = bmp;
```

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0028328-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by grokys** [comment]
We probably want to add a full range of pixels formats rather than just adding them one-by-one? I notice that currently our pixel format enum is in the `Avalonia.Platform` namespace which means its kind of an implementation detail anyway.

We could add a [`PixelFormat`](https://learn.microsoft.com/en-us/dotnet/api/system.windows.media.pixelformat?source=recommendations&view=windowsdesktop-7.0) struct like in WPF or use the [WUFFS encoding](https://github.com/google/wuffs/blob/main/doc/note/pixel-formats.md) that skia uses

**Comment by jmacato** [comment]
Closing this PR temporarily due to inactivity. Please ping me if this needs to be reopened.

**Pull request closed without merging**
