### PR TITLE
Fix StackPanel OutOfRangeException

### PR DESCRIPTION
**Pull request by adirh3**
## What does the pull request do?
Fixes `OutOfRangeException` in `StackPanel`

## What is the current behavior?
image
I see consistent crashes for my app for `OutOfRangeException` in `StackPanel` line 194, this would mean that the StackPanel childs are changing as the `ArrangeOverride` loop, not sure how that's possible.
This happens in a `ItemsPresenter` inside `ItemsPresenter` as the nested one gets populated.

Note - I am using Avalonia 0.10.7 branch, and I changed it to compile to .NET 6, which might be the root cause, although I don't really understand why.

## What is the updated/expected behavior with this PR?
Program will not crash, confirmed with users already

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018521-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by jmacato** [comment]
Closing due to inactivity, please ping me if this is going to be worked on again.

**Comment by adirh3** [comment]
> Closing due to inactivity, please ping me if this is going to be worked on again.

Why inactivity? This PR is ready for review

**Comment by maxkatz6** [comment]
Previous code was ported from https://github.com/dotnet/wpf/blob/89d172db0b7a192de720c6cfba5e28a1e7d46123/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Stack.cs#L589

It's not clear for me why initial code was like that neither why it had this out of range exception error.
It might be possible if any child was removed from the panel inside of Measure call.

**Comment by adirh3** [comment]
> Previous code was ported from https://github.com/dotnet/wpf/blob/89d172db0b7a192de720c6cfba5e28a1e7d46123/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Stack.cs#L589
> 
> It's not clear for me why initial code was like that neither why it had this out of range exception error. It might be possible if any child was removed from the panel inside of Measure call.

This started to happen once changed to .NET 6, I believe something changed in IL as well.
@jmacato can you reopen this please?

**Pull request closed without merging**
