### PR TITLE
Standardize Default Members

### LINKED ISSUE #7762: IsEmpty/IsDefault and Related Field Changes
**Describe the solution you'd like**

As discussed heavily in the `HsvColor` PR: https://github.com/AvaloniaUI/Avalonia/pull/7724#discussion_r817626579

`HsvColor` and `Color` structs should (IMO) have an `IsEmpty` property and an `Empty` field value (as named in System.Drawing.Color). This could also be named `IsDefault` and `Default` like in Xamarin.Forms.

These properties align these structures with older APIs that support this and indicate whether or not a Color struct is considered null or whether the system should interpret it with a transparent/default color instead. It doesn't need to be marked nullable with the added overhead that entails -- null can be communicated with the struct itself.

This idea is contested and I'm in the minority based on the linked discussion. Therefore, I've removed code that implements this from the `HsvColor` PR and created this discussion to make a final determination with a wider discussion.

---

This is still current in .NET. I didn't check other frameworks.

https://github.com/dotnet/runtime/blob/main/src/libraries/System.Drawing.Primitives/src/System/Drawing/Color.cs

Note that `IsEmpty` is tracked with a separate "state" field. That would mitigate any concern about it being equal to #00000000 which is technically a valid color.

Here are some .NET examples of `IsEmpty`:

 * [Color.Empty Field](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.color.empty?view=net-6.0)
 * [Syncfusion IColor.IsEmpty](https://help.syncfusion.com/cr/file-formats/Syncfusion.Presentation.IColor.html#Syncfusion_Presentation_IColor_IsEmpty)
 * [GrapeCity Empty Field (Color)](https://www.grapecity.com/activereportsnet/docs/v14/online/GrapeCity.ActiveReports.Viewer.Wpf~GrapeCity.Viewer.Common.Color~Empty.html)

It was even done for other types:

 * [Point.IsEmpty Property](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.point.isempty?view=net-6.0)
 * [Rectangle.Empty Field](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.rectangle.empty?view=net-6.0)

And here is a .NET example of `IsDefault` with Xamarin.Forms:

 * [Color.IsDefault Property](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.color.isdefault?view=xamarin-forms)

However, see the related discussion for why this was removed with MAUI: https://github.com/dotnet/Microsoft.Maui.Graphics/issues/57

**Describe alternatives you've considered**

The alternative is to add no Property/Field and just use a `nullable<Color>` when needed.

**Additional context**

### PR DESCRIPTION
**Pull request by robloo**
## What does the pull request do?

`IsEmpty` and `IsDefault` is used interchangeably across various types without standardiation. This PR standardizes related members to use the "default" term.

See: https://github.com/AvaloniaUI/Avalonia/issues/7762

"Default" is chosen because:

 * It is the modern term used in this case for most new API's
 * `IsDefault` matches well with the existing `default` keyword in C#
 * "Empty" implies the type can have something in it. This makes sense for a string or a collection but it doesn't make sense in most other cases. In common language, what does "empty thickness" mean? It can't hold anything. "default thickness" is much better.

## What is the current behavior?

Mixed/non-standardized usage of `IsEmpty`/`Empty` and `IsDefault`/`Default`:

## What is the updated/expected behavior with this PR?

As described above.

## How was the solution implemented (if it's not obvious)?

 * Most common base types (`CornerRadius`, `Thickness`, `Point`, `Rect`, etc. now standardize to `IsDefault`/`Default`)
 * Collections *MAY* be an exception to this rule where it makes sense
   * `DataGridCollectionView` keeps `IsEmpty` to maintain the old API and because, as a collection, empty makes sense
   * `DirtyRects` keeps `IsEmpty` is an internal API and is also a collection so it makes sense

## Checklist

- ~[ ] Added unit tests (if possible)?~
- [x] Added XML documentation to any related classes?
- ~[ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation~

## Breaking changes

None, old members were obsoleted instead per: https://github.com/AvaloniaUI/Avalonia/issues/7762#issuecomment-1296537217.

## Obsoletions / Deprecations

Yes:
 1. `IsEmpty` is deprecated in favor of `IsDefault`
 2. `Empty` is deprecated in favor of `Default`

## Fixed issues

Fixes #7762

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0026869-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-nightly/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0026978-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-nightly/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0027060-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-nightly/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0027457-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-nightly/nuget/v3/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0027503-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Pull request merged**
