### PR TITLE
Android Single Activity

### PR DESCRIPTION
**Pull request by emmauss**
## What does the pull request do?
This pr removes AvaloniaSplashActivity from the Android project. Initialization is now done in AvaloniaMainActivity.
This is to prevent a crash that occurs when the Android OS kills the app process, but as the last activity on the stack is the MainActivity, which can't be directly instantiated currently.
This also improves intent handling, in cases where we want to launch the app when an event occurs in the os, outside of being launched from the launcher.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Breaking changes
`AvaloniaSplashActivity` is removed.
`MainActivity` in apps now derives from `AvaloniaMainActivity<App>`.

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0036837-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Review by kekekeks — APPROVED** [review]

**Comment by kekekeks** [comment]
haven't tested, api-wise looks ok

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0036856-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by mysteryx93** [comment]
Does this change the Android project template?

**Comment by emmauss** [comment]
> Does this change the Android project template?

Yes, it does. A release will be made soon for the xplat template

**Pull request merged**
