### PR TITLE
WIP: Winit Backend (new backend to make Mac Usable)

### LINKED ISSUE #1828: TextBox makes BEEP sound when typing on Mac
TextBox makes sound like if it was an error each time some key is pressed.

### PR DESCRIPTION
**Pull request by danwalmsley**
This template is not intended to be prescriptive, but to help us review pull requests it would be useful if you included as much of the following information as possible:

Still todo:
- [ ] Drag and Drop (in progress) (@danwalmsley)
    - [ ] stuck on unrecognised selector issue, need @nc4rrillo to have a look.
- [ ] Borderless window resize issue (fix found needs implementing) (@nc4rrillo)
- [ ] When child menus open, parent menu no longer detect mouse over.
- [ ] black boxes when popups and child windows open. (@nc4rrillo)
- [ ] fix rendering corruption after popup has opened. (@nc4rrillo)
- [ ] inject events for managed drag?
- [ ] Dialog file type filters (@danwalmsley)
- [ ] Child Windows 
- [ ] PR for Avalonia.Gpu
- [ ] Window topmost
- [ ] Package for native artifacts (@lontivero)

- [x] Clipboard
- [x] Investigate threading issue with AvalonStudio
- [x] Ensure the context of the window is current
- [x] Fix Popup positioning
- [X] Corrupted text rendering in popups
- [X] Mouse Wheel LineDelta
- [x] BeginMoveDrag - managed dragging perhaps???
- [x] Unable to click on anything on AvalonStudio
      - mouse transparency not working.
- [x] Mouse click seems to register as multiple mouse clicks
- [x] System Dialogs
- [x] Open file dialog
- [x] save dialog
- [x] open folder dialog
- [x] callback to .net
- [x] return dialog results
- [x] multiple selection
- [x] initial dir / file 
- [x] Monitor / Screens
- [X] Unable to click on buttons and checkboxes
- [X] Revert changes made to ImmedatiateRenderer
- [X] OS window closing
- [x] Timers

- What does the pull request do?
It implements a new backend based on winit (https://github.com/tomaka/winit) a small compatibility layer written in rust.

This will give us a high performance backend for mac (mono mac is unusable and not really viable to repair or support going forward (IMHO)

Allows GPU rendering on mac (framerate currently <= 5-8 fps with this PR is 60+FPS)

We can also use this backend on windows and Linux if someone needed although mac is where this is definitely required.

- What is the current behavior?
Avalonia is completely unusable on mac :( 

- What is the updated/expected behavior with this PR?
Parity with win32 and Linux backends

- How was the solution implemented (if it's not obvious)?
P/Invoke simple wrapper layer built on rust. Easy to build and maintain.

Fixes #1828

### CODE REVIEW

**Comment by nc4rrillo** [comment]
Rust wrapper is here https://github.com/nc4rrillo/winit-wrapper

**Comment by danwalmsley** [comment]
BeginMoveDrag implementation started here: https://github.com/AvaloniaUI/Avalonia/tree/implement-decorated-window-dragging

almost working just some wierd jitter needs fixing.

**Comment by danwalmsley** [comment]
@nc4rrillo borderless window dragging (BeginMoveDrag) is implemented.

It works but the mouse cursor seems to get ahead of window moving if you move mouse quickly, are mouse events delayed? Perhaps you could have a look, I think it works acceptably well, but if you can suggest a way to improve this it might help.

**Comment by nc4rrillo** [comment]
@danwalmsley I think I may bite the bullet and just add a way to inject drag events into the event loop like the MonoMac backend currently has.

**Comment by danwalmsley** [comment]
@nc4rrillo ok sounds good :)

**Comment by danwalmsley** [comment]
Drag and Drop work is here:
https://github.com/AvaloniaUI/Avalonia/tree/windowing-prototype-drag-and-drop

and 

https://github.com/nc4rrillo/winit-wrapper/tree/feature/implement-drag-and-drop

**Comment by danwalmsley** [comment]
This PR is stale, a new technique: Avalonia.Native where native libraries expose a COM interface is coming.

**Pull request closed without merging**
