### PR TITLE
WIP: Property listeners

### LINKED ISSUE #3109: There is no way to get notified about non-Animated value changes
```xml
  <StackPanel Margin="10">
    <StackPanel.Styles>
      <Style Selector="Border">
        <Setter Property="Height" Value="100"/>
      </Style>
      <Style Selector="Border.animated">
         <Setter Property="Transitions">
            <Setter.Value>
               <Transitions>
                   <DoubleTransition Property="Height" Duration="0:0:4"/>
               </Transitions>
            </Setter.Value>
         </Setter>
        <Setter Property="Height" Value="200"/>
      </Style>
      <Style Selector="Border.animated:pointerover">
        <Setter Property="Height" Value="400"/>
      </Style>
    </StackPanel.Styles>
     <Border Classes="animated" Background="Red">

     </Border>
  </StackPanel>
```

https://files.gitter.im/AvaloniaUI/avalonia-core/rcxY/tran-avalonia.mp4

```html

<div class="animated " style='background: red'>

</div>
```

```css
div
{
  height: 100px;
}
div.animated
{
  transition: height 4s;
  height: 200px;
}
div.animated:hover
{
  height: 400px;
}
```

https://files.gitter.im/AvaloniaUI/avalonia-core/cJVA/tran-browser.mp4

This happens because our transition system has no way of knowing that `Style` or `StyleTrigger` value has changed. `AvaloniaObject` only notifies about the *effective* value changes. When transition is running, the effective value is always one of `Animation` priority

So we need a separate property change notification that notifies about a value that would be effective if there were no `Animated` one. Then we could cancel the current transition and start a new one towards the new target value.

### PR DESCRIPTION
**Pull request by grokys**
## What does the pull request do?

- Adds `IAvaloniaObject.Listen` to implement observables in a way that that doesn't go via `PropertyChanged`
- There are two variants of `Listen`:
  - Once which returns an `IObservable<AvaloniaPropertyChange<T>>`: this is used for listening to changes to a single property
  - One which takes an `IAvaloniaPropertyListener`: this is used for listening to all property changes in an object
- Both variants of `Listen` have an `includeAnimations` flag: setting to false only raises changes for non-animatable values. Fixes #3109
- Adds `AvaloniaPropertyChange<T>` struct as a typed no allocation version of `AvaloniaPropertyChangedEventArgs`

TODO: More details

## Open Questions

We now have quite a few ways of listening for property changes:

- `AvaloniaProperty.Changed`
- `AvaloniaObject.PropertyChanged`
- INPC on `AvaloniaObject`
- `Listen`
- `GetObservable` extension method
- `GetBindingObservable` extension method

This feels like too much. Is there any way we can simplify this?

## Checklist

- [x] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

## Breaking changes

TODO

## Fixed issues

Fixes #3109

### CODE REVIEW

**Comment by kekekeks** [comment]
>Listen has includeAnimations flag: setting to false only raises changes for non-animatable values. Fixes #3109

Unfortunately, transition handling code needs to subscribe to all of the properties and monitor their changes. Right now it overrides PropertyChanged method: https://github.com/AvaloniaUI/Avalonia/blob/adb587e39f3c435b8cf597750b22cdd326fe3e8d/src/Avalonia.Animation/Animatable.cs#L65

**Comment by grokys** [comment]
> Unfortunately, transition handling code needs to subscribe to all of the properties and monitor their changes. Right now it overrides PropertyChanged method:

Ah yeah, that was something else i wanted to mention: we'll probably need an overload of `Listen` without a property parameter which listens to all properties. If we add that, we can think about removing the `PropertyChanged` event too.

**Comment by grokys** [comment]
@kekekeks added a new variant of `Listen` which takes an `IAvaloniaPropertyListener`: this overload is used to listen to changes to all properties on an `IAvaloniaObject`.

**Comment by kekekeks** [comment]
Note that `Listen` will be called from `Animatable` constructor.

**Comment by grokys** [comment]
Ah. Yes that would make more sense if it's going to be enabled from the start. I thought for some reason that you wanted to only subscribe to the changes once a transition had been registered.

**Comment by kekekeks** [comment]
We could only call `Listen` when first transition is registered, but for no transitions scenario virtual method call with a check inside will be almost as much fast as the current check for `_allPropertyListeners`, but we'll be avoiding allocations and calls through observable infrastructure for objects that have transitions.

**Comment by kekekeks** [comment]
On the other hand it will be a *generic* virtual method call. Those have horrible performance.

@MarchingCube

**Comment by MarchingCube** [comment]
Since animations are closely tied to the framework having something dedicated would perform better for sure. Although I've never benchmarked differences between normal virtual calls and virtual stub dispatch so I am not sure how slow it could be.

**Comment by grokys** [comment]
Closing this as I decided to go for a simpler approach for now in https://github.com/AvaloniaUI/Avalonia/pull/3853

**Pull request closed without merging**
