### PR TITLE
Optimizing resource related code.

### PR DESCRIPTION
**Pull request by MarchingCube**
## What does the pull request do?

Avalonia has too many interfaces and casts are used too often which leads to degraded performance caused by this.
This PR is tweaking a few resource related interface usages to get rid of casts and speed up hot paths. 

## What is the current behavior?

|        Method |     Mean |   Error |  StdDev |   Gen 0 |   Gen 1 | Allocated |
|-------------- |---------:|--------:|--------:|--------:|--------:|----------:|
| CreateTextBox | 625.6 us | 2.25 us | 1.88 us | 90.8203 | 30.2734 |    230 KB |
| CreateCalendar | 13.67 ms | 0.121 ms | 0.113 ms | 1500.0000 | 531.2500 | 171.8750 |      4 MB |

## What is the updated/expected behavior with this PR?

|        Method |     Mean |   Error |  StdDev |   Gen 0 |   Gen 1 | Allocated |
|-------------- |---------:|--------:|--------:|--------:|--------:|----------:|
| CreateTextBox | 526.3 us | 2.40 us | 1.87 us | 93.7500 | 28.3203 |    222 KB |
| CreateCalendar | 12.46 ms | 0.088 ms | 0.082 ms | 1453.1250 | 515.6250 | 156.2500 |      4 MB |

## How was the solution implemented (if it's not obvious)?

Also since benchmark was using default theme I've changed data validation to use compiled bindings for attached properties since reflection path is really slow.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

### CODE REVIEW

**Comment by timunie** [comment]
Hi @MarchingCube 

I am not sure if this is related, but I have once learned that `foreach` may be noticeable slower that `for` in many cases. See: https://www.c-sharpcorner.com/article/c-sharp-performance-of-code-for-loop-vs-for-each-loop/ . 

I leave this link here as a suggestion to test / benchmark if you think it's useful. If not, just ignore. 

Happy coding
Tim

**Comment by MarchingCube** [comment]
@timunie I had a good chuckle reading that article, although then I got a bit sad since people look at such content and then "optimize" their applications causing perf regressions.

For people actually wondering about `for` and `foreach` performance:
- It heavily depends on collection type and local information. For example for `Span<T>` quite often code generation for `foreach` is really good due to runtime optimization. Such optimization also depends on what compiler sees so it can devirtualize or inline code.
- Use proper benchmarking suite like `BenchmarkDotNet`, measuring perf using stopwatch is generally pointless. In that article you can probably swap `for` and `foreach` tests locations and get the opposite result :) Code has to be compiled, caches warmed up and benchmarking suites do that for you.
- Modern runtimes quite often use struct based enumerators that do not require allocations (for example `List<T>.Enumerator`)
- Enumerators sometimes do more work, for example `List<T>.Enumerator` checks if collection was not modified.
- For arrays and spans you can do tricks to avoid generation of index validity checks since that is also expensive if you have a lot of data to go through

Better article that actually uses proper way of benchmarking perf: https://www.meziantou.net/fastest-way-to-enumerate-a-list-t.htm

And this is why I've already optimized a few `for` loops or simply implemented better enumerators in certain cases, but it all had to be backed by benchmarks since runtime is a complex beast.

**Comment by timunie** [comment]
Thank you for the detailed explanations and the other article. That is great 👍 :-)

**Review by grokys — APPROVED** [review]
LGTM! A simple change for a decent performance win.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0020193-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
