### PR TITLE
Fix expander header stretching

### LINKED ISSUE #5284: Expander header is not stretch
There is no way to made full width expander header, without control template modification.

1. Apply fluent style
2. Put expander
3. Add header content with right alignment
4. Header is always aligned to left

```
          <Expander>
            <Expander.Header>
              <Grid ColumnDefinitions="*, Auto">
                <TextBlock Text="{Binding ComponentType}" />
                <Button Grid.Column="1" Padding="0">
                  <Image  Source="{StaticResource AppMinus}" Height="30" />
                </Button>
              </Grid>
            </Expander.Header>
            <ContentControl Content="{Binding}" />
          </Expander>
```

**Expected behavior**
Content aligned to right

**Screenshots**

*Actual result*
image

*Expected result:*
image

**Additional context**
This is probably because of following Grid in Expander toggle button template. 
https://github.com/AvaloniaUI/Avalonia/blob/25fe106c235ebb5c6260af5a13d6a79b633c5b82/src/Avalonia.Themes.Fluent/Controls/Expander.xaml#L90

I think it should have `ColumnDefinitions="Auto,*"` . Should I make a pull request with this fix?

### PR DESCRIPTION
**Pull request by maxkatz6**
## What does the pull request do?
Fixes header stretching of the expander's header.

## Fixed issues
Fixes #5284

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018950-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018950-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by robloo** [comment]
From a discussion a long time ago: Perhaps the Fluent style and template should be synced with upstream WinUI. This PR reminded me but if you don't feel like it, there is no need.

**Review by danwalmsley — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018994-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018994-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
