### PR TITLE
Fix #3079 (Rect.Contains())

### LINKED ISSUE #3079: PointerPressed captures pointers 1 pixel outside of the control
I have a control that's size is 128 wide and 16 tall. When I subscribe to the PointerPressed event, I am getting events from both x=128 and y=16 (which are outside of the control). Any X and Y coords larger do not fire the event. The event also will not fire if there is a different control directly next to this control. For example, if I have another control to the right of this control, then events with x=128 will not be sent to this control.

### PR DESCRIPTION
**Pull request by Kermalis**
## What does the pull request do?
Fixes #3079

### CODE REVIEW

**Review by grokys — CHANGES_REQUESTED** [review]
The existing behavior here matches WPF: https://github.com/dotnet/wpf/blob/master/src/Microsoft.DotNet.Wpf/src/WindowsBase/System/Windows/Rect.cs#L784-L785

I'm not sure we want to make such a basic API behave differently?

**Comment by Kermalis** [comment]
For me it's unexpected to get events about something outside of my control and I have to have additional logic to check for that specific case, also in my own opinion I don't consider something at the edge of the width and height to be within the bounds (for example: if you have a screen that's 1920x1080 and a pixel at [1920,y] is considered in that screen, that is potentially dangerous because it is simply incorrect)

My specific case has to do with rendering as well, and I would get an access violation for drawing outside of the bounds of my image because of this, which is why I need a helper function which instead uses `<`

I can't really think of a good reason to keep <= even if it is how WPF does it. I'm open to hearing other opinions so I can learn other uses for it.

Also, I'm not sure why that test is failing as it seems unrelated to rectangles entirely

**Comment by grokys** [comment]
I agree that it seems rather strange to have `Rect.Contains` work like this, but I've checked on UWP and `Rect.Contains(Point)` works like this there too. And in fact, originally Avalonia's `Rect.Contains` was also exclusive but changed to inclusive here: 

https://github.com/AvaloniaUI/Avalonia/commit/ad9abd53c12142d585702a020e068d5731e0822e#diff-eeae6e342870a38bf94876352f66cd6cR233-R234

I can't remember exactly why I changed it (I wish I'd mentioned it in the commit message) but doing a search for this issue, I came across a discussion here which suggests that it needs to be like this in continuous coordinate spaces:

https://social.msdn.microsoft.com/Forums/vstudio/en-US/a4f6500c-561b-4bc7-9a4f-6829cc11329f/quotcontainsquot-method-in-rect-wpf-and-rectangle-winforms?forum=wpf

It also says:

> for hit testing, you need a different rule than for painting, I think... depends how you define it.

So I think that `Rect.Contains` needs to stay the same.

We do need to fix hit-testing though by the sounds of it.

**Comment by jinek** [comment]
> I can't remember exactly why I changed it (I wish I'd mentioned it in the commit message) 
> 

I think because of this https://github.com/AvaloniaUI/Avalonia/commit/ad9abd53c12142d585702a020e068d5731e0822e#diff-5da613710eeefd3a7ada8e5f7aaf3110ecf3b2bccb354885fdf18d0ddd549669R244
BottomRight is not supposed to be contained in own rectangle, similar to https://docs.microsoft.com/en-us/dotnet/api/system.drawing.rectangle.right?view=net-6.0

**Pull request closed without merging**
