### PR TITLE
Send one notifi per seq range in RemoveAll method of AvaloniaList (optimized)

### PR DESCRIPTION
**Pull request by usUyGBx**
## How was the solution implemented (if it's not obvious)?
- Fast low-level error prone solution for large lists
- Special case for huge lists

## Checklist

- [x] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

### CODE REVIEW

**Comment by grokys** [comment]
This seems over-complex and still not that performant - it generates multiple lists and dictionaries in the worst case.

I've not tried to implement this myself but wouldn't this be simpler?

- Add the indexes and items as tuples to a list as they're removed
- Sort the list after all items are removed
- Iterate the sorted list, raising an event each time a non-sequential index is encountered
  - Where the `IList` passed to the `NotifyCollectionChangedEvent` is just a wrapper over the above sorted list with a start index and count (i.e. a list span)

Am I missing something?

**Comment by usUyGBx** [comment]
> This seems over-complex

My bad :)

>     * Add the indexes and items as tuples to a list as they're removed
>     * Sort the list by index after all items are removed
>     * Iterate the sorted list, raising an event each time a non-sequential index is encountered
>      Where the `IList` passed to the `NotifyCollectionChangedEvent` is just a wrapper over the above sorted list with a start index and count (i.e. a list span)

In my understanding:
* Create a copy of inner list
* Detect next sequence
* Remove sequence from inner list insted of using AvaloniaList.RemoveRange
* Call notifications manually (with span wrapper over the copy of inner list as OldItems)

I see only one benefit from the span wrapper that is use only one memory allocation. But the whorst case (short single remove sequence) for it is the common case.

So i think simplified version is optimal. IndexOf version of course is faster on small collections, but extra case reduses the pithiness.

**Comment by usUyGBx** [comment]
Removing 200 elsements (with duplicates) from 10000-elements list (with duplicates)

|           Method |        Mean |    Error |   StdDev |    Gen 0 |   Gen 1 | Gen 2 | Allocated |
|----------------- |------------:|---------:|---------:|---------:|--------:|------:|----------:|
|    SimpleVersion |    62.90 us | 0.018 us | 0.014 us |   0.8545 |       - |     - |    4024 B |
| VmelnikovVersion | 1,086.91 us | 2.883 us | 2.696 us | 183.5938 | 78.1250 |     - | 1009064 B |

**Comment by vmelnikov** [comment]
> Removing 200 elements (with duplicates) from 10000-elements list (with duplicates)
> 
> Method	Mean	Error	StdDev	Gen 0	Gen 1	Gen 2	Allocated
> SimpleVersion	62.90 us	0.018 us	0.014 us	0.8545	-	-	4024 B
> VmelnikovVersion	1,086.91 us	2.883 us	2.696 us	183.5938	78.1250	-	1009064 B

I think your solution is simple and much better than my. So I can close my PR

**Comment by grokys** [comment]
Ah, yes this looks much simpler now! Need to give it a proper look but from first glance looks good!

**Comment by MarchingCube** [comment]
I did run a benchmark that compares this implementation vs the old one.

Comparison is done by adding `N` items to an `AvaloniaList<string>` and then removing all.
Collection has a subscriber to `CollectionChanged` so events are being sent as well.

|             Method |                items |        Mean |     Error |    StdDev | Ratio | RatioSD |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------------- |--------------------- |------------:|----------:|----------:|------:|--------:|-------:|------:|------:|----------:|
|          RemoveAll | 0 |    31.84 ns |  0.190 ns |  0.169 ns |  1.00 |    0.00 | 0.0095 |     - |     - |      40 B |
|          RemoveAll | 1 |   154.37 ns |  1.171 ns |  1.096 ns |  4.85 |    0.05 | 0.0515 |     - |     - |     216 B |
|          RemoveAll | 4 |   402.74 ns |  1.784 ns |  1.668 ns | 12.65 |    0.10 | 0.1259 |     - |     - |     528 B |
|          RemoveAll | 8 |   770.39 ns |  2.757 ns |  2.302 ns | 24.19 |    0.13 | 0.2251 |     - |     - |     944 B |
|          RemoveAll | 32 | 3,175.72 ns | 17.048 ns | 15.947 ns | 99.74 |    0.57 | 0.8202 |     - |     - |    3440 B |
| RemoveAllOptimized | 0 |    96.80 ns |  0.780 ns |  0.691 ns |  3.04 |    0.03 | 0.0516 |     - |     - |     216 B |
| RemoveAllOptimized | 1 |   316.47 ns |  1.119 ns |  0.992 ns |  9.94 |    0.07 | 0.1011 |     - |     - |     424 B |
| RemoveAllOptimized | 4 |   546.75 ns |  1.800 ns |  1.596 ns | 17.17 |    0.10 | 0.1259 |     - |     - |     528 B |
| RemoveAllOptimized | 8 |   849.45 ns |  2.442 ns |  2.165 ns | 26.68 |    0.18 | 0.1526 |     - |     - |     640 B |
| RemoveAllOptimized | 32 | 2,681.13 ns | 19.780 ns | 17.535 ns | 84.20 |    0.52 | 0.3204 |     - |     - |    1352 B |

**Comment by usUyGBx** [comment]
The point of reduсing notofication count is not to increase performance of 'RemoveAll' itself.
The goal is to reduce the number of calls to the UI View changed handler, which, perhaps, is not written in the most optimal way, can keep a log, as well as generate its own events that will propagate further. 
Special cases for 0, 1 and 2 (if equals) items is not introdused for obvious reasons.

**Review by grokys — APPROVED** [review]
Sorry it took so long to review this.

Looks good to me, as you say, the goal is to reduce UI updates so slightly worse performance on the list can translate to better performance in general.

I hope you don't mind, but my feeble mind was unable to understand your unit tests and so I simplified the single test into multiple simpler tests in order to be sure that things were working as expected - the tests were way more complicated than the code, which makes it hard to confirm that the tests are correct ;) I hope I caught each important edge case.

**Pull request merged**
