### PR TITLE
Change the default font to system's default.

### PR DESCRIPTION
**Pull request by jmacato**
- What does the pull request do?
Changes `Courier New` to the target's system default font so that Avalonia apps wont look out of place.

- What is the current behavior?
`Courier New` is currently the default font and it frankly doesn't look good across platforms.

### CODE REVIEW

**Comment by Gillibald** [comment]
Is that working with DirectWrite? 

We have fixed the skia backend to support an aliases with the help of FontConfig. It will give you a matching font when an alias is defined for it. We should just use a font that is configured as an alias by default.

I mean if "system-ui" always works on all backends and platforms this is fine.

**Comment by jmacato** [comment]
i originally added Segoe UI, sans-serif on it but i think those needs to be tested first

**Comment by danwalmsley** [comment]
@jmacato maybe its better to fine some nice font fallbacks that give a similar look and feel / metrics on the main platforms, and it fallaback to the system font as a last resort, the other thing we could do is find a decent ui font we can embed with avalonia that we use instead of system font when fallbacks fail. If UWP were cross platform font is so important i dont think they would leave it to every different linux distribution to decide how the final app would look

**Comment by Gillibald** [comment]
What about comparing the system default of major platforms? They should already be very similar. If you want the same look on all platforms you have to embed a font amd use that. Using the system's default feels more natural to me. You can always override the default with your own.

**Comment by danwalmsley** [comment]
Put it this way, we are a lookless framework, so we dont embed native buttons and that way we have a consistent look across platforms. But when it comes to fonts we are using a different approach. System font would Make sense on native frameworks like Xamarin Forms. The other thing is the default font is also part of how people recognise avalonia, its a major part of your first impression of the framework, if we use system font we are basically leaving this to chance.

**Comment by danwalmsley** [comment]
@grokys what is your take on this?

**Comment by grokys** [comment]
My feel is that the system font would be a good default, yeah.

**Comment by Gillibald** [comment]
The system's default will be able to handle all kinds or at least most font weights and styles etc. This is not so easy to achieve by embedding a font or finding a font family on each platform to support these.

**Comment by wieslawsoltes** [comment]
I have tested with Windows 10 x64 and it works.

system-ui

**Review by danwalmsley — APPROVED** [review]
LGTM

**Pull request merged**
