### PR TITLE
OSX handle CMD+key up combinations in Avalonia

### PR DESCRIPTION
**Pull request by ltetak**
## What does the pull request do?
On macOS, when you press CMD + some key you don't get key up event notification as we do on Windows.

## What is the current behavior?
The order of events is
* KeyDown CMD
* KeyDown A (modifiers CMD)
* KeyUp CMD

## What is the updated/expected behavior with this PR?
* KeyDown CMD
* KeyDown A (modifiers CMD)
* **KeyUp A (modifiers CMD)**
* KeyUp CMD

(this is aligned to Shift and Control behavior)

## How was the solution implemented (if it's not obvious)?

I am a newbie with objective C (please check the code or rework completely). I was inspired by this SO thread https://stackoverflow.com/questions/4001565/missing-keyup-events-on-meaningful-key-combinations-e-g-select-till-beginning?rq=1
I think it is common behavior on mac but is not in line with other frameworks.

## Breaking changes
We should get more events, not less. So it should be safe.

Note that there are other unrelated keyboard problems
1. Alt key does not forward key down/up keys.
2. Shift + key sends Shift + shift key on key down
3. Meta and LWin modifiers are kind of randomly used for the same CMD mac key. To align this would probably create some breaking changes though.

**I based it on the master branch but the master branch is not buildable ATM. Try it on the RC branch to test.**

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018519-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by jmacato** [comment]
Closing due to inactivity, please ping me if this is going to be worked on again.

**Comment by ltetak** [comment]
@jmacato I saw you closed both this and https://github.com/AvaloniaUI/Avalonia/pull/6991 OSX PRs. What is the process to have this accepted? We use this code in our code successfully (from a custom build). If some additional samples/tests are necessary I can provide these.

**Comment by jmacato** [comment]
@ltetak yeah i closed because i didnt see any activity over the last month. I'll reopen this and see if anyone in core can review it.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019328-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by robloo** [comment]
@jmacato I'm just going to comment this here since it's the last one I saw. I noticed this happens a lot though. You are closing PRs that are clearly waiting for review of the Avalonia maintainers. I don't think you should just close PRs. First, ask if there is anything that needs to be done or if it is ready for review. Only if there is no response and clearly pending issues close it. 

Closing good PRs just because the maintainers haven't reviewed it is a bad look for the project.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019914-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019959-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
