### PR TITLE
Support heterogeneous item containers V2

### PR DESCRIPTION
**Pull request by grokys**
## What does the pull request do?

#11068 proposed a potential API for heterogeneous item containers in `ItemsControl`s but we got [feedback](https://github.com/AvaloniaUI/Avalonia/pull/11068#issuecomment-1515658820) that it wasn't sufficient for certain scenarios. This PR attempts to address these scenarios while also maintaining support for recycling heterogeneous containers.

The main changes in this PR when compared to current `master` are:

- `bool IsItemItsOwnContainer(Control container)` becomes `bool NeedsContainer(object? item, int index, out object? recycleKey)`
- `Control CreateContainer()` becomes `Control CreateContainer(object? item, int index, object? recycleKey)`

The process for generating new containers now goes like this:

- `NeedsContainer(object, int, out object?)` should first be called to determine whether the item needs a container. This method will return true if the item should be wrapped in a container control, or false if the item itself can be used as a container. It will also return a recycle key - this will be discussed later but `null` can be returned as a recycle key in two cases:
  - The item doesn't need a container (i.e. it is it's own container and by definition cannot be recycled)
  - Recycling is not supported for the container
- If `NeedsContainer(object, int, out object?)` returns true then the `CreateContainer` method should be called to create a new container, passing the recycle key returned from `NeedsContainer(object, int, out object?)`.
- If the panel supports recycling and the recycle key is non-null then the recycle key should be recorded for the container (e.g. in an attached property or the realized container list).
- PrepareItemContainer, AddInternalChild and ItemContainerPrepared should be called as before

The recycle key is an `object` whose only requirement from the API standpoint is that it can be used as a dictionary key. However given that the recycle key returned from `NeedsContainer` is passed to `CreateContainer` it can be used to pass information between these two methods instead of using the [`_currentItem` hack used by WPF](https://github.com/dotnet/wpf/blob/main/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/MenuItem.cs#L2080).

The logic of `IsItemItsOwnContainer` has been inverted (e.g. it now returns `false` if an item is its own container). This is because it felt weird returning a `null` value in the `out` parameter when the method returned `true` and a non-null value when the method returned `false`.

`CreateContainer` now accepts the item and index. I don't really see any downsides to this additional information being passed and it allows more flexibility in where the container type is decided. Let me know if you can forsee a problem with this.

Here are the scenarios supported by this API:

### Basic Usage

The usage currently supported on `master`, e.g. `ListBox`:

- A single container type
- Items can be their own container
- Recycling is supported

```csharp
protected internal override bool NeedsContainerOverride(object? item, int index, out object? recycleKey)
{
	return NeedsContainer<ListBoxItem>(item, out recycleKey);
}

protected internal override Control CreateContainerForItemOverride(object? item, int index, object? recycleKey)
{
	return new ListBoxItem();
}
```

`NeedsContainer` calls the utility `ItemsControl.NeedsContainer(object?, out object?)` method which is implemented as follows:

```csharp
protected bool NeedsContainer<T>(object? item, out object? recycleKey) where T : Control
{
    if (item is T)
    {
        recycleKey = null;
        return false;
    }
    else
    {
        recycleKey = DefaultRecycleKey;
        return true;
    }
}
```

`DefaultRecycleKey` is a default key that can be used when an <see cref="ItemsControl"/> supports a single container type.

### "Menu" Scenario

@billhenn gave a good [writeup](https://github.com/AvaloniaUI/Avalonia/pull/11068#issuecomment-1515658820) of how `MenuItem` works in WPF. I'm going to call this the "Menu" scenario:

- Container type decided outside the `ItemsControl`
- Items can be their own container
- No recycling supported

Note that this PR doesn't introduce `ItemContainerTemplateSelector` for Avalonia (though it may well be introduced later).

```csharp
protected internal override bool NeedsContainerOverride(object? item, int index, out object? recycleKey)
{
    // Containers can never be recycled.
    recycleKey = null;
    return !(item is MenuItem or Separator);
}

protected internal override Control CreateContainerForItemOverride(object? item, int index, object? recycleKey)
{
    if (UsesItemContainerTemplate)
    {
        var itemContainerTemplate = ItemContainerTemplateSelector.SelectTemplate(item, this);

        if (itemContainerTemplate != null)
        {
            var itemContainer = itemContainerTemplate.Build(item);
            
            if (itemContainer is MenuItem || itemContainer is Separator)
            {
                return itemContainer as Control;
            }
            else
            {
                throw new InvalidOperationException("Invalid container.");
            }
        }
    }

    return new MenuItem();
}
```

Here, as in WPF, the container selection is deferred to the `CreateContainer` stage, but we don't need to store `_currentItem` because the item is passed into `CreateContainerForItemOverride`.

### Recycling "MenuItem" Scenario

An extension of the previous scenario, not supported by WPF (afaik) is:

- Container type decided outside the `ItemsControl`
- Items can be their own container
- Recycling is supported

```csharp
protected internal override bool NeedsContainerOverride(object? item, int index, out object? recycleKey)
{
    if (item is MenuItem or Separator)
    {
        recycleKey = null;
        return false;
    }

    if (UsesItemContainerTemplate &&
        ItemContainerTemplateSelector.SelectTemplate(item, this) is var itemContainerTemplate)
    {
        // Return the template as the recycle key.
        recycleKey = itemContainerTemplate;
        return true;
    }

    recycleKey = DefaultRecycleKey;
    return true;
}

protected internal override Control CreateContainerForItemOverride(object? item, int index, object? recycleKey)
{
    if (recycleKey is IDataTemplate itemContainerTemplate)
    {
        object itemContainer = itemContainerTemplate.Build(item);
        
        if (itemContainer is MenuItem || itemContainer is Separator)
        {
            return itemContainer as Control;
        }
        else
        {
            throw new InvalidOperationException("Invalid container.");
        }
    }

    return new MenuItem();
}
```

Here the container selection is implemented in `NeedsContainerOverride` and the container template is returned as the recycle key. This allows virtualizing panels to locate containers previously created using this container template in the recycle pool and reuse them. If no existing container is found in the recycle pool, then the container template is passed to `CreateContainer` and can be used there (instead of having to look it up again from the `ItemContainerTemplateSelector`).

As always, feedback welcome!

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0034171-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by billhenn** [comment]
@grokys It's great how `NeedsContainer` allows you to indicate that recycling might not be supported for a control.

For the "Menu" Scenario, I think that should handle what we do in our WPF Bars product other than the lack of `ItemContainerTemplateSelector`.

For the Recycling "MenuItem" Scenario, that's very clever using the `IDataTemplate` as the recycle key so it's a one-time lookup.  I like it!

Great work on all this, I think that will do the trick and is very flexible.  I'm happy to discuss `ItemContainerTemplateSelector` separately with you since it is a worthwhile addition if nothing similar is already in Avalonia, but is not pertinent to this PR.

**Comment by timunie** [comment]
@billhenn For `ItemContainerTemplateSelector` I think implementing `IDataTemplate` on your own could work. https://github.com/AvaloniaUI/Avalonia.Samples/tree/main/src/Avalonia.Samples/DataTemplates/IDataTemplateSample

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0034370-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Review by danwalmsley — APPROVED** [review]
Tested + LGTM

**Pull request merged**
