### PR TITLE
Add WS_CLIPCHILDREN window style.

### PR DESCRIPTION
**Pull request by grokys**
## What does the pull request do?

Adds `WS_CLIPCHILDREN` window style to window and popup. Needed for embedding chromium, see https://github.com/AvaloniaUI/Avalonia/issues/3281#issuecomment-557615525

### CODE REVIEW

**Review by danwalmsley — APPROVED** [review]
LGTM

**Comment by danwalmsley** [comment]
backport candidate?

**Comment by kekekeks** [comment]
Same change is a part of unmerged embedding PR.

**Comment by grokys** [comment]
@kekekeks ah I didn't realise that. Would you prefer to close this PR and wait for that to be merged?

**Comment by danwalmsley** [comment]
closing, seems the other pr was merged anyway.

**Pull request closed without merging**
