### PR TITLE
[Text] Fixes

### LINKED ISSUE #6767: Italic text is getting clipped
**Describe the bug**
Setting `FontStyle="Italic"` is clipping the end of the text. HorizontalAlignment needs to be left so that the textblock sizes to the text. Some fonts are worse than others like the new Windows 11 font Segoe UI Variable is particularly bad

image

````
<TextBlock Text="Arial"
	  FontStyle="Italic"
	  FontFamily="Arial"
	  HorizontalAlignment="Left"
	  VerticalAlignment="Top"
	  Background="#15000000" />

<TextBlock Text="Segoe UI"
	  FontStyle="Italic"
	  FontFamily="Segoe UI"
	  HorizontalAlignment="Left"
	  VerticalAlignment="Top"
	  Background="#15000000" />

<TextBlock Text="Segoe UI Variable Text"
	  FontStyle="Italic"
	  FontFamily="Segoe UI Variable Text"
	  HorizontalAlignment="Left"
	  VerticalAlignment="Top"
	  Background="#15000000" />
````

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: Win 11
- Version 0.10.8

**Additional context**

### LINKED ISSUE #11346: [Regression] TextBox selectAll selection not always rendering
**Describe the bug**
selectAll not always rendering it’s state 50% repro. every second textBox show with select all shows only caret, but works like select all

https://github.com/AvaloniaUI/Avalonia/assets/4997065/df454292-24ae-45a6-83e0-975488f87d48

**Desktop (please complete the following information):**

- macOS, Windows

### LINKED ISSUE #11350: [Regression] TextBox text selection is not set to End while SelectAll and click on white space after text
**Describe the bug**
TextBox text selection is not set to End while SelectAll and click on white space after text

https://github.com/AvaloniaUI/Avalonia/assets/4997065/10a557e4-f785-4d57-8a6d-644c248e2f57

On Any OS.

### LINKED ISSUE #11390: TextBox Text Selection is not reset on single click in the same caret position where double click selection was invoked
**Describe the bug**
Double click on any word in text box. Click Again in same spot. Selection is not reset to caret position.

**To Reproduce**
See Video

https://github.com/AvaloniaUI/Avalonia/assets/4997065/f1c6c888-fff6-4da4-a2c3-4986ce309b36

**Expected behavior**
On a single click in that place should be SelectionStart=SelectionEnd=CaretIndex = pos where clicked.

### PR DESCRIPTION
**Pull request by Gillibald**
- Fix TextLineImpl.GetCharacterHitFromDistance for lines that include a TextEndOfLine run
- Fix overhang handling to prevent clipped text for slanted glyphs
- Fix TextBox selection issues
 
## Checklist

- [x] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Fixed issues

Fixes #11390
Fixes #11346
Fixes #11350
Fixes #6767

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0034461-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0034563-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by robloo** [comment]
Without spending the time to test this, does this PR fix tooltip text measurements again? The below issue previously occurred several previews ago and then was fixed. Now it's back:

Too much margin/padding:
image

Cutting off last character:
image

**Comment by robloo** [comment]
> How can I verify this?

Its the ColorPicker in ControlCatalog. If you click and hover over any color in the Palette tab it should appear. 

You have to be using an English locale though as it just shows a processed version of the knowncolors enum. No localization infrastructure exists yet.

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0034887-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Pull request merged**
