### PR TITLE
Fix issue with 0,0 position when pointerover was cleaned up + blinking issue

### LINKED ISSUE #8795: MouseOver Blinking Behavior
**Describe the bug**

Clicking within the color spectrum of the ColorView and holding while dragging over menu items causes them to blink rapidly in ControlCatalog. There should never be any blinking.

**To Reproduce**

1. Go to the ColorPicker page in the ControlCatalog
2. Press/Hold/Drag to change the selected color in the spectrum
3. While continuing to hold, move the pointer outside the ColorPicker and on top of the side-pane menu
4. Notice that the background of the item sin the menu blinks rapidly (pointer held the entire time)

**Expected behavior**

Even if the item background is supposed to change, it certainly shouldn't be blinking.

**Screenshots**

Note the blinking of the pointer moved / over is actually much faster than shown in the video.

https://user-images.githubusercontent.com/17993847/185774180-54683373-2bad-444a-9cb5-42fa30acdb09.mp4

**Desktop (please complete the following information):**

- OS: Windows 10 Pro
- Version [e.g. 0.10.0-rc1 or 0.9.12]

**Additional context**

### LINKED ISSUE #8796: Pointer Position Jumps to 0,0 on Fast Movement
**Describe the bug**

This was first noticed with the ColorPicker but I expect is applies to every control.. Pressing and holding on the spectrum then dragging outside the window bounds will cause the pointer position to report 0,0 (relative) before it is usually fixed. This shouldn't happen and causes jumps in the selected color.

**To Reproduce**

1. Go to the ColorPicker page of the ControlCatalog
2. On the far-right color spectrum Press/Hold/Drag to change color
3. While continuing to hold the left mouse button, drag the pointer outside the app window
4. Notice that the reported pointer position to the control is sometimes (0,0) instead of the last position before the pointer exited the app.

**Expected behavior**

Pointer position should never be reported as 0,0. Instead, either the last pointer position should be used -- or more accurately -- the pointer position clipped to the bounds of the focused control.

**Screenshots**

https://user-images.githubusercontent.com/17993847/185774278-b5d84be0-772a-4aba-a919-216167c8e82c.mp4

**Desktop (please complete the following information):**

- OS: Windows 10 Pro
- Version [e.g. 0.10.0-rc1 or 0.9.12]

**Additional context**

### LINKED ISSUE #8832: Drag operation is lost in Avalonia 11
**Describe the bug**
The mouse control is lost when dragging and the pointer goes out of the control bounds. 

* Mouse down.
* Start moving the mouse.
* Go out of the control bounds.
* The "drag" operation is lost. It seems that previously the `PointerExited` event was not fired, and now it's fired.

**Expected behavior**
The "drag" operation is still active.

**Screenshots**
See the following recording comparing `0.10.18` (left), and `11.0-preview-1`:
drag-operation

**Desktop (please complete the following information):**

- OS: Windows
- Version 11.0-preview-1

### PR DESCRIPTION
**Pull request by maxkatz6**
## Checklist

- [x] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Fixed issues

Fixes #8795
Maybe fixes #8832 (@danipen hi, can you confirm this?)

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0023704-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by danipen** [comment]
I can confirm that it fixes #8832 and #8830.

**Comment by robloo** [comment]
I guess these were all related. Thanks for finding and fixing this!

**Comment by tomenscape** [comment]
This PR fixes the flickering reported in #8926. However, after opening or closing the drop-down, the `pointerover` style isn't applied or removed until the user moves their mouse or clicks. It looks like an update is missing when a window opening or closing causes the element under the pointer to change.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0023732-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0023797-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0023809-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by maxkatz6** [comment]
Doesn't fix #8796 anymore in favor of https://github.com/AvaloniaUI/Avalonia/pull/8957

**Review by grokys — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0023832-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
