### PR TITLE
Bump DBus stack take 2

### PR DESCRIPTION
**Pull request by affederaffe**
## What does the pull request do?
Bump Tmds.DBus.Protocol and Tmds.DBus.SourceGenerator.
This uses the "official" Variant system instead of the SourceGenerator provided one (which was removed).
Accept the explicit ignoration of the DBus spec and assume collapsed variants.

## How was the solution implemented (if it's not obvious)?
Tmds.DBus.SourceGenerator.PropertyChanges`1 was made internal by Tmds.DBus.SourceGenerator

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/avalonia-docs with user documentation

## Obsoletions / Deprecations
None

## Fixed issues
#15655

### CODE REVIEW

**Comment by maxkatz6** [comment]
@affederaffe since this PR has breaking changes, you need to run `nuke ValidateApiDiff` command locally (nuke tool needs to be installed, alternatively, you can run `_build` project with the same command directly).
As it looks like, some autogenerated dbus files were made internal, as they should be.

**Comment by affederaffe** [comment]
Only the PropertyChanges<T> type was made internal as it should be, it was a mistake to make it public at first.
It is safe to make it internal as it is unusable by itself, all members that use this type  (i.e. proxies with WatchPropertyChangedAsync) are already internal, so there cannot be any users of this api anyway.

**Comment by jmacato** [comment]
@affederaffe we still need to run the API validation regardless as it's a hard requirement for making stable buiilds at the moment

**Comment by affederaffe** [comment]
Avalonia.FreeDesktop.nupkg.xml
```xml
<?xml version="1.0" encoding="utf-8"?>
<!-- https://learn.microsoft.com/en-us/dotnet/fundamentals/package-validation/diagnostic-ids -->
<Suppressions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Suppression>
    <DiagnosticId>CP0001</DiagnosticId>
    <Target>T:Tmds.DBus.SourceGenerator.PropertyChanges`1</Target>
    <Left>baseline/netstandard2.0/Avalonia.FreeDesktop.dll</Left>
    <Right>target/netstandard2.0/Avalonia.FreeDesktop.dll</Right>
  </Suppression>
</Suppressions>
```

**Comment by maxkatz6** [comment]
@affederaffe @jmacato just updated api baseline by running "nuke" tool in the solution root.

**Comment by kekekeks** [comment]
Sorry, missed the PR, will test tomorrow.

**Comment by kekekeks** [comment]
As of the public API, can we have source-generated classes to be private?

**Comment by affederaffe** [comment]
> As of the public API, can we have source-generated classes to be private?

How could they be private?
The private modifier only makes sense for nested classes, but for that we'd need an explicit entrypoint (e.g. marker attribute) on a class. Which is only possible for proxies, and even then, when using the proxy multiple times, each would have its own private class.

**Comment by maxkatz6** [comment]
@affederaffe private for external consumer. I.e. internal is fine.

**Comment by affederaffe** [comment]
That makes more sense.
In this case, every source-generated class is already internal and thus inaccessible for users.

**Comment by kekekeks** [comment]
Why do we need
```
    <DiagnosticId>CP0001</DiagnosticId>
    <Target>T:Tmds.DBus.SourceGenerator.PropertyChanges`1</Target>
    <Left>baseline/netstandard2.0/Avalonia.FreeDesktop.dll</Left>
    <Right>target/netstandard2.0/Avalonia.FreeDesktop.dll</Right>
  </Suppression>
```
then?

**Comment by maxkatz6** [comment]
@kekekeks it wasn't internal before this PR

**Comment by affederaffe** [comment]
> Sorry, missed the PR, will test tomorrow.

@kekekeks Any updates on this?

**Comment by kekekeks** [comment]
DBus menu works now with KDE without crashes, yes

**Review by kekekeks — APPROVED** [review]

**Comment by kekekeks** [comment]
I think at some point we might want to switch to using libdbus by adapting your generators. It wont be a 100% managed solution, but at least libdbus is pretty much guaranteed to follow the spec.

**Comment by tmds** [comment]
> I think at some point we might want to switch to using libdbus by adapting your generators. It wont be a 100% managed solution, but at least libdbus is pretty much guaranteed to follow the spec.

My 2 cents.

`VariantValue` isn't meant to be a match with wire-representation of a variant. It is a convenience type that is meant for reading variant values. When you are reading those values, the UX is nicer if the variants are unwrapped.

I think that `VariantValue` probably works very well for your use-cases, but that you got caught/surprised by the difference in behavior with what you had before.

If you prefer a different behavior, you can still use the lower-level APIs and build your own Variant representation as the SourceGenerator was doing before.

**Comment by kekekeks** [comment]
Some DBus protocols _**require**_ variants to be wrapped into variants. If it's not possible to represent such thing via the API, we'd need to switch the transport layer to a spec-conformant one for future-proofing.

**Comment by kekekeks** [comment]
The current problem was caused by misrepresentation of variants on receiver side, which is an inconvenience, but it's not possible to _send_ such messages, which would outright prevent us from being able to implement protocols.

**Comment by tmds** [comment]
> but it's not possible to send such messages, which would outright prevent us from being able to implement protocols.

For sending, `VariantValue` isn't used. There's a different type called `Variant`. Currently, it doesn't allow putting a Variant in a Variant. That's not intentional, it is an oversight.

And even then, the lower-level APIs enable you to take full control of serialization.

**Pull request merged**
