### PR TITLE
Ensure templated parent control theme is applied

### LINKED ISSUE #10226: Expander styles broken when using Simple Theme
**Describe the bug**

Expanding an expander breaks its styles. This bug only seems to occur when using the Simple Theme. I could only create a simple repro for pointer over styles not working, although the original bug is that the list box would measure 0 height after the expander is expanded at least once. I believe it's the same bug.

**To Reproduce**

1. Clone branch https://github.com/jp2masa/Avalonia/tree/styles-bug-repro
2. Run `Sandbox`
3. Expanding any item will break its styles. At least, the border color doesn't change anymore on pointer over

**Expected behavior**

Expander's border color should change according to pointer over, even after expanding it at least once.

**Screenshots**

https://user-images.githubusercontent.com/10765201/216821300-46f71d00-98de-48eb-9b88-4004de3082d8.mp4

**Desktop (please complete the following information):**

- OS: Windows 11
- Version: https://github.com/AvaloniaUI/Avalonia/commit/64155069c5ec97aa496fc0f3f437d475e2bf4b24

### PR DESCRIPTION
**Pull request by jp2masa**
## What does the pull request do?

Ensure templated parent control theme is applied.

## What is the current behavior?

When templated parent control theme changes, styles are not applied, this affects Expander on Simple Theme (#10226).

## What is the updated/expected behavior with this PR?

Styles are correctly applied.

## How was the solution implemented (if it's not obvious)?

Override `OnTemplatedParentControlThemeChanged` on Layoutable and call `InvalidateMeasure`, like it's already being done for `OnControlThemeChanged`. Add missing `!_templatedParentThemeApplied` to `ApplyStyling`.

## Checklist

- [x] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Fixed issues

Fixes #10226

### CODE REVIEW

**Comment by jp2masa** [comment]
While fixing this I also found a possible bug, related to the following overrides:

https://github.com/AvaloniaUI/Avalonia/blob/4a4d7139343703d4d457629e91ba813dc249a13c/src/Avalonia.Controls/Primitives/TemplatedControl.cs#L399-L429

It makes sense to override `OnControlThemeChanged` on `TemplatedControl` to call `OnTemplatedParentControlThemeChanged` on its visual children, i.e. the template.

However, for `OnTemplatedParentControlThemeChanged` what I understood is that it's propagating `OnTemplatedParentControlThemeChanged` to all children inside the template, but to be part of the template they don't have to be `TemplatedControl`s, right? The minimum requirement is for them to be `Visual`s. Am I missing something?

**Comment by maxkatz6** [comment]
@jp2masa is it possible to add some tests, so it won't be regressed?

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0029785-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Review by grokys — APPROVED** [review]
Sorry, this dropped off my radar - LGTM, thanks @jp2masa !

**Comment by grokys** [comment]
> However, for OnTemplatedParentControlThemeChanged what I understood is that it's propagating OnTemplatedParentControlThemeChanged to all children inside the template, but to be part of the template they don't have to be TemplatedControls, right? The minimum requirement is for them to be Visuals. Am I missing something?

Yes, that's correct I think. I also notice we have no test coverage covering the `for` loop in `OnTemplatedParentControlThemeChanged` so we should fix that.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0030363-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by jp2masa** [comment]
> > However, for OnTemplatedParentControlThemeChanged what I understood is that it's propagating OnTemplatedParentControlThemeChanged to all children inside the template, but to be part of the template they don't have to be TemplatedControls, right? The minimum requirement is for them to be Visuals. Am I missing something?
> 
> Yes, that's correct I think. I also notice we have no test coverage covering the `for` loop in `OnTemplatedParentControlThemeChanged` so we should fix that.

Opened #10471 with a test and fix.

**Pull request merged**
