### PR TITLE
Fix Menu when using overlay popups

### PR DESCRIPTION
**Pull request by grokys**
## What does the pull request do?

As discovered by adding integration tests with overlay popups in #10448, menus didn't work with overlay popups. This PR fixes that issue and thus fixes the integration test failures in #10448 - this PR depends on that one and should be merged instead. I kept them separate as they address two separate things.

PR contains one fix and one tidy up:

- Run a layout pass when popup is opened if we detect that the `MenuItem` presenter isn't attached to the visual tree. This is need when using overlay popups as they don't automatically do a layout pass on open like real popup windows
- Use `RoutedEentArgs` instead of `PointerEventArgs` for `MenuItem.PointerEnteredItem` and `MenuItem.PointerExitedItem`: we were using an obsolete API to create the event args for these events but we don't need a `PointerEventArgs` anyway

Depends on #10448 (merge this one to merge that one)

### CODE REVIEW

**Comment by timunie** [comment]
Will this probably also address #8859 ?

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0030561-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by grokys** [comment]
@timunie nope, I investigated that as part of this PR, but couldn't work out what was happening as I'm not familiar with the client-side decorations stuff, and didn't want to delay this fix as #10420 is a release blocker.

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0030577-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Pull request merged**
