### PR TITLE
Try fix issue #11438

### LINKED ISSUE #11438: NRE throw during the startup when using latest Nightly build
**Describe the bug**

A NRE exception throw during the startup when using latest Avalonia Nightly Build:

```

 	Avalonia.Base.dll!Avalonia.Threading.DispatcherOperation.InvokeCore()
 	Avalonia.Base.dll!Avalonia.Threading.DispatcherOperation.Execute()
 	Avalonia.Base.dll!Avalonia.Threading.Dispatcher.ExecuteJob(Avalonia.Threading.DispatcherOperation job)
 	Avalonia.Base.dll!Avalonia.Threading.Dispatcher.ExecuteJobsCore()
 	Avalonia.Base.dll!Avalonia.Threading.Dispatcher.Signaled()
 	Avalonia.Win32.dll!Avalonia.Win32.Win32DispatcherImpl.DispatchWorkItem()
 	Avalonia.Win32.dll!Avalonia.Win32.Win32Platform.WndProc(nint hWnd, uint msg, nint wParam, nint lParam)
 	[本机到托管的转换]	
 	[托管到本机的转换]	
 	Avalonia.Win32.dll!Avalonia.Win32.Win32DispatcherImpl.RunLoop(System.Threading.CancellationToken cancellationToken)
 	Avalonia.Base.dll!Avalonia.Threading.DispatcherFrame.Run(Avalonia.Threading.IControlledDispatcherImpl impl)
 	Avalonia.Base.dll!Avalonia.Threading.Dispatcher.PushFrame(Avalonia.Threading.DispatcherFrame frame)
 	Avalonia.Base.dll!Avalonia.Threading.Dispatcher.MainLoop(System.Threading.CancellationToken cancellationToken)
 	Avalonia.Controls.dll!Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(string[] args)
 	Avalonia.Controls.dll!Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(Avalonia.AppBuilder builder, string[] args, Avalonia.Controls.ShutdownMode shutdownMode)
>	LauncherX.Avalonia.dll!LauncherX.Avalonia.Program.Main(string[] args) Line 14	C#

```

**Expected behavior**

The main window should show.

**Screenshots**

image

**Desktop (please complete the following information):**

- OS: Windows 11 22H2
- Version: 11.0.999-cibuild0035015-beta

### PR DESCRIPTION
**Pull request by laolarou726**
## What does the pull request do?

Try to fix issue #11438.

## What is the current behavior?

Currently, the code can not ensure the list is not null when trying to iterate through it.

## What is the updated/expected behavior with this PR?

Added one more check to ensure the list is not null.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Fixed issues

Fixes #11438

### CODE REVIEW

**Comment by laolarou726** [comment]
> @dotnet-policy-service agree

@dotnet-policy-service agree

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0035175-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by kekekeks** [comment]
Please, provide a unit test that demonstrates the issue

**Comment by laolarou726** [comment]
> Please, provide a unit test that demonstrates the issue

You mean the repro for this bug? Actually I didn't figure out what caused this problem. I tried to find it out and make a repro for that but eventually I failed :(

**Comment by llfab** [comment]
Please find repro here: https://github.com/AvaloniaUI/Avalonia/discussions/11491#discussioncomment-5993054

**Comment by maxkatz6** [comment]
Fixed by https://github.com/AvaloniaUI/Avalonia/pull/11552
@laolarou726 thanks!

**Pull request closed without merging**
