### PR TITLE
Throw on attempt to invalidate a visual during a render pass

### PR DESCRIPTION
**Pull request by kekekeks**
It's invalid to call InvalidateVisual while renderer is already updating the scene graph. Previously DeferredRenderer was silently ignoring such calls while CompositingRenderer would crash while enumerating the collection. 

This PR explicitly throws an exception from InvalidateVisual instead.

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0023495-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by Gillibald — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0023502-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by danipen** [comment]
How this affects developers? In other words... what should we avoid in order to avoid getting that exception?

**Comment by Gillibald** [comment]
Don't invalidate the visual during Render

**Pull request merged**
