### PR TITLE
Enable ClearType on Windows

### PR DESCRIPTION
**Pull request by Gillibald**
## What does the pull request do?

This PR enables ClearType on Windows.

Current SkiaSharp `2.88.0-preview.179` has broken ClearType support and the last working version is `2.80.3` to be able to use ClearType one needs to downgrade SkiaSharp.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

### CODE REVIEW

**Comment by jangernert** [comment]
Is there a reason for downgrading SkiaSharp? I am already using the newly added SKRuntimeEffect of SkiaSharp 2.88 together with a ICustomDrawOperation in Avalonia 0.10.11. This would mean I am stuck on 0.10.11 until SkiaSharp gets upgraded again.

**Comment by Gillibald** [comment]
`2.88.0-preview.179` has broken `ClearType` support therefore the downgrade

**Comment by danwalmsley** [comment]
> Is there a reason for downgrading SkiaSharp? I am already using the newly added SKRuntimeEffect of SkiaSharp 2.88 together with a ICustomDrawOperation in Avalonia 0.10.11. This would mean I am stuck on 0.10.11 until SkiaSharp gets upgraded again.

Your still free to update the reference in your project.

**Comment by kekekeks** [comment]
As discussed separately:
1) We should keep updated SkiaSharp since its required for WASM and M1 macs
2) We should make sure that code works properly (even if without ClearType on 2.88) with both SkiaSharp 2.80 and 2.88 by doing assembly version check if necessary
3) Projects requiring ClearType on Windows will have to downgrade SkiaSharp manually

**Review by danwalmsley — APPROVED** [review]

**Comment by BitCrusader** [comment]
Wasn't ClearType specifically removed from modern XAML (system/UWP/WinUI) due to only working when snapped to the nearest pixel, which isn't an option with lots of animations?

**Comment by vitidev** [comment]
@kekekeks 

> Projects requiring ClearType on Windows will have to downgrade SkiaSharp manually

How to do it right? After the downgrade, it does not start with an error

    System.IO.FileNotFoundException: 'Could not load file or assembly
    'SkiaSharp, Version=2.88.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756'.

**Pull request merged**
