### PR TITLE
Remove ContentControlMixin

### PR DESCRIPTION
**Pull request by grokys**
## What does the pull request do?

One of the problems in #2821 is that `ContentPresenter` doesn't set the logical parent of its child control when the host `ContentControl` is removed from the logical tree and then re-added.

The problem was in `ContentControlMixin` which is really complex and even with its complexity had bugs (such as this one). This bug would have been difficult to fix in `ContentControlMixin` and I've been intending to remove this class for a while, so I took this opportunity to do so.

By moving the functionality to the content controls there is some repeated code but it's much more straightforward, and more importantly fixes the menu issue.

## Checklist

- [x] Added unit tests (if possible)?

## Breaking changes

`ContentControlMixin` has been removed. Although this was technically a public API, it's unlikely that 3rd party code was using it.

### CODE REVIEW

**Comment by MarchingCube** [comment]
I am using `ContentControlMixin` in my codebase (in one place only though), I guess now I have to manually manage `LogicalChildren` and `VisualChildren`?

**Comment by danwalmsley** [comment]
@grokys I tested this, and seems to work, but im still having trouble with menus, did you expect this to completely fix menus?

**Comment by grokys** [comment]
@MarchingCube you just need to implement the changes in `ContentControl`, that is:

- Implement `IContentPresenterHost`
- Add a [changed handler](https://github.com/AvaloniaUI/Avalonia/pull/2926/files#diff-727ede034dacfffdd8ba76a0c9ac1139R120) for the content property which adds/removes logical children

@danwalmsley yeah other than the [popup clipping issue](https://github.com/AvaloniaUI/Avalonia/issues/2821) menus should be fixed with this PR. What problems are you still seeing?

**Comment by MarchingCube** [comment]
It seems that opening context menu and clicking on a titlebar crashes the application. `DefaultMenuInteractionHandler` is trying to close null  `Menu` in `RawInput`.

**Comment by MarchingCube** [comment]
DevTools don't even open in this branch.

**Comment by grokys** [comment]
@MarchingCube well spotted. Fixed those issues.

**Review by danwalmsley — APPROVED** [review]
Confirmed that issues are resolved and tested, seems to fix menu issues

👍

**Pull request merged**
