### PR TITLE
Fix dwm opaque backdrop

### LINKED ISSUE #6465: Acrylic Blur does not work on Windows 11
**Describe the bug**
Win2d acrylic blur does not work on Windows 11 build 22000.160. This also breaks `TransparencyLevel.Blur` if WinUI compositor is enabled.

DWM transparency and blur works fine.

**To Reproduce**

1. Create new project from template
2. Set `TransparencyLevelHint.AcrylicBlur` on the main window.
3. Set background to `null`.
4. Run

This can also be observed in the SampleApp.

**Expected behavior**
The acrylic layer should not be opaque.

**Screenshots**
image

**Desktop (please complete the following information):**
- OS: Windows 11 22000.160
- Version 0.10.3; 0.10.7 (master)

**Additional context**
Side note: `ICompositor3.CreateHostBackdropBrush()` is _not_ broken in this build of windows. `ICompositor2.CreateBackdropBrush()` might be though.

### LINKED ISSUE #7403: ExtendClientAreaToDecorationsHint breaks winui composition effects
**Describe the bug**
`DwmExtendFrameIntoClientArea` breaks the winui backdrop effect. This causes Acrylic and Mica backgrounds to turn opaque.
https://github.com/AvaloniaUI/Avalonia/blob/38f726f997b9abfa14b9ea3cfd5c742da0c88fa9/src/Windows/Avalonia.Win32/WindowImpl.cs#L930-L934

**To Reproduce**

1. Create a new MVVM app.
1. Follow the [docs](https://docs.avaloniaui.net/tutorials/music-store-app/creating-a-modern-looking-window) and enable acyrlic on the main window.
1. Ensure`ExtendClientAreaToDecorationsHint="True"` is set on the window.
1. Build and run.
1. Observe an opaque background.
1. Disable ExtendClientAreaToDecorationsHint (e.g. with dev tools) and observe correct behavior.

**Expected behavior**
ExtendClientAreaToDecorationsHint should not break acyrlic.
- If no workarounds are planned, this behavior should be documented.
- The backdrop should fall back to DWM blur if acrylic blur is not available -- [also when composition is enabled](https://github.com/adirh3/Avalonia/blob/d1dea568510f0d00246a9a0a5cb01ef9427e6eca/src/Windows/Avalonia.Win32/WindowImpl.cs#L374).

**Screenshots**
image

**Desktop (please complete the following information):**

- OS: Windows 11, 22000.466
- Version: 0.10.11 (fe4197ecd2489a9c8eb7a4f5ee3e72a9d81d0832)

**Additional context**
Not sure if this issue was introduced with Windows 11. If so, perhaps the issue should be forwarded to Microsoft?

Invoking `DwmExtendFrameIntoClientArea` with an empty `MARGINS` resolves the issue.

Related to #6465

### PR DESCRIPTION
**Pull request by trympet**
## What does the pull request do?
Windows 11 introduced some breaking changes / bugs to DWM [1] [2]. As a result, the behavior of DWM changed from win10. This could cause the acrylic backdrop to become opaque. This PR resolves this issue by setting a new DWM attribute introduced in win11.

## What is the current behavior?

Neither `TransparencyLevelHint.Transparent` nor `TransparencyLevelHint.AcrylicBlur` works with extended margins. 

## What is the updated/expected behavior with this PR?

`TransparencyLevelHint.Transparent` and `TransparencyLevelHint.AcrylicBlur` now works with  `Window.ExtendClientAreaToDecorationsHint = true`

## How was the solution implemented (if it's not obvious)?

1. Use host backdrop from ICompositor3 instead of backdrop from ICompositor2 if win11.
1. Set  [DWMWA_USE_HOSTBACKDROPBRUSH](https://docs.microsoft.com/en-us/windows/win32/api/dwmapi/ne-dwmapi-dwmwindowattribute#constants) if the acrylic backdrop is enabled.

## Breaking changes

No breaking changes.

## Fixed issues
Fixes #7403
Fixes #6465

[1] https://github.com/dotnet/winforms/issues/6364
[2] https://www.youtube.com/watch?v=dH7-rVpssxQ

### CODE REVIEW

**Review by kekekeks — COMMENTED** [review]
Changes generally look ok.

@grokys @danwalmsley are we ok with merging so many formatting changes?

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019125-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019125-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by trympet** [comment]
> Changes generally look ok.
> 
> @grokys @danwalmsley are we ok with merging so many formatting changes?

Thanks! I can rebase and remove the formatting changes if you'd like.

**Review by jmacato — CHANGES_REQUESTED** [review]
@trympet please remove the formatting changes, otherwise LGTM :)

**Comment by danwalmsley** [comment]
@trympet this will still work on win10 right?

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019157-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019180-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by danwalmsley — APPROVED** [review]

**Pull request merged**
