### PR TITLE
Don't create virtualizer before panel.

### LINKED ISSUE #1707: ItemVirtualization for ListBox is Broken
image

Performance is really bad now. Will investigate further.

### PR DESCRIPTION
**Pull request by grokys**
In `Itemspresenter`:

- Don't create virtualizer before panel. Otherwise, an `ItemVirtualizerNone` is created which can materialize all items, even if `ItemVirtualizationMode.Simple` is set.
- Use weak subscriptions. This not only prevents memory leaks, but also accidental double-subscribes as we have an `IDisposable` to represent the subscription state.

@danwalmsley : hopefully fixes #1707.
@RayyanTahir: should also fix the problem you were seeing with two listboxes.

### CODE REVIEW

**Review by danwalmsley — APPROVED** [review]
LGTM, id like to see if @RayyanTahir agrees this has fixed issues.

**Comment by RayyanTahir** [comment]
I'm still getting an exception, `System.ArgumentException: 'An item with the same key has already been added. Key: 1'
`

**StackTrace:**
```
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Avalonia.Controls.Generators.ItemContainerGenerator.Materialize(Int32 index, Object item, IMemberSelector selector) in C:\Projects\Avalonia\src\Avalonia.Controls\Generators\ItemContainerGenerator.cs:line 65
   at Avalonia.Controls.Presenters.ItemVirtualizerSimple.CreateAndRemoveContainers() in C:\Projects\Avalonia\src\Avalonia.Controls\Presenters\ItemVirtualizerSimple.cs:line 324
   at Avalonia.Controls.Presenters.ItemVirtualizerSimple.ItemsChanged(IEnumerable items, NotifyCollectionChangedEventArgs e) in C:\Projects\Avalonia\src\Avalonia.Controls\Presenters\ItemVirtualizerSimple.cs:line 164
   at Avalonia.Controls.Presenters.ItemsPresenter.ItemsChanged(NotifyCollectionChangedEventArgs e) in C:\Projects\Avalonia\src\Avalonia.Controls\Presenters\ItemsPresenter.cs:line 160
   at Avalonia.Controls.Presenters.ItemsPresenterBase.ItemsCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e) in C:\Projects\Avalonia\src\Avalonia.Controls\Presenters\ItemsPresenterBase.cs:line 257
```

Please use the repro provided in: https://github.com/AvaloniaUI/Avalonia/issues/1709

The steps to repro are almost similar to https://github.com/AvaloniaUI/Avalonia/issues/1709 as well:

1. add up to 5 items to listbox.
2. select first item and remove till the listbox is empty.
3. add a couple of items
4. app crashes with the above exception.

**Comment by grokys** [comment]
@RayyanTahir i've pushed another fix that hopefully will fix what you were seeing!

**Comment by grokys** [comment]
@RayyanTahir this may also now fix #1723 - could you check?

**Comment by RayyanTahir** [comment]
@grokys Apologies for being late. I've checked, it works great now. Great work and thanks.

**Pull request merged**
