### PR TITLE
Replaced flag checking expressions by Enum.HasValue

### PR DESCRIPTION
**Pull request by YohDeadfall**
## What does the pull request do?

The PR replaces expression checking the value for a flag by invocation of `Enum.HasFlag` which isn't boxing since 2017 (dotnet/runtime#6080).

## What is the current behavior?

Currently there are a lot of hand written expressions checking for null which can be simplified.

## What is the updated/expected behavior with this PR?

No changes except more clean code.

### CODE REVIEW

**Comment by grokys** [comment]
We added `Enum.HasFlagCustom` because `Enum.HasFlag` didn't seem to work non-boxing in a lot of cases - see https://github.com/AvaloniaUI/Avalonia/pull/3066

I'm not sure if this is still the case? @MarchingCube @jkoritzinsky

**Comment by jkoritzinsky** [comment]
The non-boxing optimization I believe only happens on Tier 1 JIT or R2R, so we added HasFlagCustom to ensure that we don’t box with Tiered Compilation enabled.

**Comment by MarchingCube** [comment]
Also all debug builds are boxing, we technically also support Mono and .Net Framework and addition of tiered compilation that also boxes initially makes me always suspicious when I see `Enum.HasFlag`.

**Comment by YohDeadfall** [comment]
@AndyAyersMS @egorbo, could you confirm that tiered compilation affects this optimization and tier 0 may box an enum value?

@grokys, @MarchingCube, in case if it's true (I hope that this optimization works always) then it makes sense to fix your implementation which is slow, unsafe and buggy (having a non-`int` enum may cause at least an incorrect result or even crash the app).

**Comment by EgorBo** [comment]
> @AndyAyersMS @EgorBo, could you confirm that tiered compilation affects this optimization and tier 0 may box an enum value?
> 
> @grokys, @MarchingCube, in case if it's true (I hope that this optimization works always) then it makes sense to fix your implementation which is slow, unsafe and buggy (having a non-`int` enum may cause at least an incorrect result or even crash the app).

it's not optimized in tier0 currently (it's below [this check](https://github.com/dotnet/runtime/blob/master/src/coreclr/src/jit/importer.cpp#L3607-L3616))
I guess it's quite slow for tier0 and can affect throughput/startup time (see `gtOptimizeEnumHasFlag`).

**Comment by kekekeks** [comment]
>it makes sense to fix your implementation which is slow, unsafe and buggy (having a non-int enum may cause at least an incorrect result or even crash the app).

[SL](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKBuIGYACY8pZ0xgYUYG8bGBggQG0AygAtsUAA4AZbMAB0AJQCuAOwwBLfDEUApLRgDiMdTChawACgwBPaTAgAza6IyX1Ac1HSANkYA8tLaEOq4AJQRALr8QoLCLCoa2rqKnBD40lp+FqIWAG5WMLiKALIwGOIQACYAkll+1klqmjp6GVk5eYXFpRVVtQ3+waHhigCCXl6wuLhaBTB16gHqWt4xcfHMTCxsGrjYzjCMwBAQfowAEngAYn7YXpyquBiZADwAKgB8tuJauEYn0YBWwflUMDQQMYzgeXgijAA7uILCdgSBGBp8Nh1I8YDUoQBRdSqfBbeJ8ajbbagqCMdYYABqYIhjAAvIwAFTWBmciIAMlB4JgAG5ydSQVJ6Zp7o92VyeZo+fzYY8xbQqRLBMQAOyMRVMlknfnSjCy+HsjkM83qiUAXxodqAA==)
```cs
        [SharpLab.Runtime.JitGeneric(typeof(StringSplitOptions))]
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static unsafe bool HasFlagCustom<T>(this T value, T flag) where T : unmanaged, Enum
        {
            var intValue = *(int*)&value;
            var intFlag = *(int*)&flag;

            return (intValue & intFlag) == intFlag;
        }
```
x64
```asm
C.HasFlagCustom[[System.StringSplitOptions, System.Private.CoreLib]](System.StringSplitOptions, System.StringSplitOptions)
    L0000: and ecx, edx
    L0002: cmp ecx, edx
    L0004: sete al
    L0007: movzx eax, al
    L000a: ret
```

I don't see what exactly is slow for those instructions that only operate with registers. Legacy framework JIT generates pointer-based stack access, but that's still better than default HasFlag.

Regarding non-int enums: we simply do not use that function for non-int enums.

**Comment by YohDeadfall** [comment]
> Regarding non-int enums: we simply do not use that function for non-int enums.

At least it can be changed to be safe and contain a throw expression if non-`int` enums are not allowed.

**Comment by kekekeks** [comment]
>At least it can be changed to be safe and contain a throw expression if non-int enums are not allowed.

Unfortunately `if(Marshal.SizeOf<T>() == 4)` check doesn't get resolved at JIT-time and generates invocations at run-time. .NET type system also doesn't allow us to have enum size type constraint.

**Comment by YohDeadfall** [comment]
`Unsafe.SizeOf<T>` works at JIT time and is supported by any target framework ([see dependencies](https://www.nuget.org/packages/System.Runtime.CompilerServices.Unsafe/5.0.0-rc.2.20475.5)).

**Comment by YohDeadfall** [comment]
The following code is safe and produces the same instructions as existing.

```csharp
public static bool HasFlagCustom<T>(this T value, T flag) where T : unmanaged, Enum
{
    if (Unsafe.SizeOf<T>() != Unsafe.SizeOf<int>())
        throw new NotSupportedException();
            
    var valueUntyped = Unsafe.As<T, int>(ref value);
    var flagUntyped = Unsafe.As<T, int>(ref flag);
            
    return (valueUntyped & flagUntyped) == flagUntyped;
}
```

**Comment by kekekeks** [comment]
For some reason checking the size reduces the [generated code quality](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgCUBXAOwwEt8YLAMIR8AB14AbGFADKMgG68wMXAG4aMLh3wMAQlp0h9ATwwwA3jQC+NO9UO752/MdwALaBivVb1e44MAJKOxrw8Pn4BLgwAMqEMkhBcAOaR9sQAzEzkSEykDEIMPgylZaUA2rLu2FBisdjA7Nx8AiwAUrwYAOJaMsoAFBgmYjAQAGYDBi4AlDMAujTl5VU1dQ1NnDz8gp09fVCDw6MTA846c4vUZUvLldW19Y3N2217vVz9YEMjY5PxswWtzuq0eGxerV2XQ+Xx+J0mIUBVzulQAsjAMJ4ACZBcSSAbozEQHF4gDyYj4yVwLAAgikUrBcLheAoYEEuJJwuEUkDriisjk8txcNhxjAGMAIBBJAwABJ4ABikmwKQA6l13EJ3DAwABrAA8ABUAHxDdy8XAMQ0MBTYSQcGBoK0McbKnkMADu2tgzuM3Hw2C4KpgWKdAFEXMDliUUeVeJMAKpcEViliyXgALxgpPGRtNMwYAF5CwxyDMo7GLLHyhXq6VbVAJWYYAA1O0OosMABUA2Aza7MwAZLb7TANHy6+UG03zEqVZ2e33zAPB66VePJ8tiAB2Bi95tt0cMQczmBz93F0/njeTvybmCSXDi+MDJMpwTprM5vMDAuX0jlhO1ZVpOtZ1tOHheIeHYlj2kFQBgK4jg6N6bvWtQMPBGDnguAxYSua4pKhaE7nuWHQeKJ5Yeef4ltRbrEbGd6Tg+T4MC+b6ih+mbZrmJq/kWJYoIBm4gXWYHVtO4QYBRuHSUh7ZjhJsZSTwOGwQM8lDoRjGTqRmk8LJJ7STRgnsWpDHKWUzF1qxz7jHunGpp+vE/rRDAABwiZOMZoTaGFJKkskaYFKQKaOungQFyQpOp3YDKFBGWUBm76aFRmJDFpmXqF15WaUNnVnZ+XLJiUAQB6DCfJVAByEAYLIHBiGIXghmGCAqBSvDJAMABEEY6J6GqYTxDATAwvUMAA1AwTncV+fH5tNE0MLU4pcPVmFNS1CEhr1MyRQwhUSaC6zPFskIdNCBxHL8pyIhcvKxgKzBCsmXESlKMryrg55CBwuAYKIpKSFiP6YhazrIY6zqEQWXoyOK1p+lwAZBikIbhpGKVlL5aGqTJilyTw4UoSVU4YSZbrE4h2nJX5pT6dJGVUyq7ms0REl+NYQA==):
```asm

C.HasFlagWithCheck[[Ienum, _]](Ienum, Ienum)
    L0000: sub rsp, 0x18
    L0004: xor eax, eax
    L0006: mov [rsp+8], rax
    L000b: mov [rsp+0x10], rax
    L0010: mov [rsp+0x20], ecx
    L0014: mov [rsp+0x28], edx
    L0018: mov eax, [rsp+0x20]
    L001c: mov edx, [rsp+0x28]
    L0020: and eax, edx
    L0022: cmp eax, edx
    L0024: sete al
    L0027: movzx eax, al
    L002a: add rsp, 0x18
    L002e: ret

C.HasFlagCustomOld[[Ienum, _]](Ienum, Ienum)
    L0000: and ecx, edx
    L0002: cmp ecx, edx
    L0004: sete al
    L0007: movzx eax, al
    L000a: ret

```

**Comment by kekekeks** [comment]
Your proposed variant actually works better on the legacy framework than our current one though. I wonder if we should have separate method versions for different enum sizes to overcome that JIT limitation.

**Comment by kekekeks** [comment]
Mkay, replacing `Unsafe.SizeOf<T>()` with `sizeof(T)` [fixes](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgCUBXAOwwEt8YLAMIR8AB14AbGFADKMgG68wMXAG4aMLh3wMAQlp0h9ATwwwA3jQC+NO9UO752/MdwALaBivVb1e44MAJKOxrw8Pn4BLgwAMqEMkhBcAOaR9sQAzEzkSEykDEIMPgylZaUA2rLu2FBisdjA7Nx8AiwAUrwYAOJaMsoAFBgmYjAQAGYDBi4AlDMAujTl5VU1dQ1NnDz8gp09fVCDw6MTA846c4vUZUvLldW19Y3N2217vVz9YEMjY5PxswWtzuq0eGxerV2XQ+Xx+J0mIUBVzulQAsjAMJ4ACZBcSSAbozEQHF4gDyYj4yVwLAAgikUrBcLheAoYEEuJJwuEUkDriisjk8txcNhxjAGMAIBBJAwABJ4ABikmwKQA6l13EJ3DAwABrAA8ABUAHxDdy8XAMQ0MBTYSQcGBoK0McbKnkMADu2tgzuM3Hw2C4KpgWKdAFEXMDliUUeVeJNmQAvP4DQ0zBgAXgzDHIMyjsYssfK+aLpVtUAlZhgADU7Q7MwwAFQDYBVxszABktvtMA0fNL5XLlfMSpVDebrfM7Y7rpVfYHy2IAHYGC2q7WewwO8OYKP3Vmd3v5wO/AuYJJcOL4wMkym05ns6Q8/2i4WByXS0OPF4N/Xs83vygDBp27B1jwXMtagYQCMD3ccb08IDp1nFJwIg5dVxg39xW3GC93TA88LdNDY1PAdz0vBhr1vU57wPFBnwXN9Sw/Ish3CDBsPgjiQLrXtWNjdieDg/8Bh4zsUJIgcMLEnguO3Dj8IfKjhOIgSyjI0sKKvcZMN4ZNaII7MAA5GIHGMIJtKCklSLjRJslJeJ7KTP2s5IUhEpsBgc5C1JfBcZIc+TEncpSDwco91NKTSi20qLlkxKAIA9BhPhSgA5CAMFkDgxDELwQzDBAVApXhkgGAAiCMdE9DVoP08UJgYCqGAAagYABVLgRTFFhZAa0lxiNU103alranFLgsug3L8qAkMKpmFyGBi1jQXWZ4tkhDpoQOI5flORELl5WMBWYIVutFcVJWlOVFTdIQOFwDBRFJSQsWGs0LWdUDHWdFD0y9GRxWtP0uADIMUhDcNI38soLIgoTOL47ieCcsD4sHKDFLdVHgIkvzLNKGSOOCnGVSMlTYMJlE/GsIA) the code, but then changing it to use Unsafe.As [adds weirdness again](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgCUBXAOwwEt8YLAMIR8AB14AbGFADKMgG68wMXAG4aMLh3wMAQlp0h9ATwwwA3jQC+NO9UO752/MdwALaBivVb1e44MAJKOxrw8Pn4BLgwAMqEMkhBcAOaR9sQAzEzkSEykDEIMPgylZaUA2rLu2FBisdjA7Nx8AiwAUrwYAOJaMsoAFBgmYjAQAGYDBi4AlDMAujTl5VU1dQ1NnDz8gp09fVCDw6MTA846c4vUy2WrtfWNzdtte71c/WBDI2OT8bMLSxuDDu60eW1auy6bw+XxOkxC/yuQOBAFkYBhPAATILiSQDNEYiDY3EAeTEfGSuBYAEEUilYLhcLwFDAglxJOFwikAdcgVkcnluLhsOMYAxgBAIJIGAAJPAAMUk2BSAHUuu4hO4YGAANYAHgAKgA+IbuXi4BgGhgKbCSDgwNCWhjjJXchgAdy1sCdxm4+GwXGVMExjoAoi5ATcSsiyrxJkyAF4/BgDA0zBgAXgzDHIM0jMYsMbK+aLpRtUHFZhgADVbfbMwwAKpcYWimm4Q2O4BVk2wcbWuswGYaXmlsrlyvmRXKhvN1uCakdg1dnsDPvO13Dkul4gAdhT3fMtbtYoAZJOYNO3VmL1eR2O/GOYJJcGK4wM5yLBLJeEmSeNDRNdMb1IPNRwLbciwnDwvGPets0/NtF07BgYKgDBexgfsbRPLdwLHaDPHQq9ZxbL92xQtCMLXLCN2VPCx3KPcUyouCz1QoiMCvYDsyou9IOWR9S2fV8GHfRDv1/GB/0AgYeIYFAwLHaNGIHCtwgwNjSPnCjlzEnhMOwwcGNUtT9K411tPI5C9I0wy6O5e9TOYgYNK088NO4zNs0810nKLISixEt9+w/Mi2x/P8AONOTvIYAAOJTSxUxiJySVItIQ8KFyXR10pSeycPtEzVLS5IUhIrKdJsvLyvsl16P8xiXPy9zEnKryb3y/j8KBQKY2CgTkQxKAIHdBh3nGgA5CAMFkDgxDELxg1DBAVHJXhkgGAAicMdA9dVUKkhgJgYbaGAAaibbKWEi6ToqAy6zoYWoxS4WbUIWpb0ODbaSsE/MBJBB5NhaHYOihA4jm+U4EQuHlkX5ZhBWy8VJWlOVcCvIQOFwDBRBJSRMVkjFzSdIqHSdBq3U9GQxStX0uH9QMUmDMMI160oUoI2pzMyhgACpXJ4AWZlPCmmp59SeEqwXhYwUXT2pyWd33eW2t8+i4s1lIVdKPxrCAA).

**Comment by AndyAyersMS** [comment]
> For some reason checking the size ... reduces the generated code quality:

Can you open a bug for this over on dotnet/runtime? The jit may be getting confused by the parts of the IL that end up not getting imported.

**Comment by kekekeks** [comment]
This version seems to consistently produce optimized code with both .NET core and legacy framework JIT

```cs
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static unsafe bool HasFlagWithCheck<T>(this T value, T flag) where T : unmanaged, Enum
        {
            if(sizeof (T) == 1)
            {            
                var byteValue = Unsafe.As<T, byte>(ref value);
                var byteFlag = Unsafe.As<T, byte>(ref flag);
                return (byteValue & byteFlag) == byteFlag;
            }
            else if(sizeof (T) == 2)
            {
                var shortValue = Unsafe.As<T, short>(ref value);
                var shortFlag = Unsafe.As<T, short>(ref flag);
                return (shortValue & shortFlag) == shortFlag;
            }
            else if(sizeof (T) == 4)
            {
                var intValue = Unsafe.As<T, int>(ref value);
                var intFlag = Unsafe.As<T, int>(ref flag);
                return (intValue & intFlag) == intFlag;
            }
            else if (sizeof (T) == 8)
            {
                var longValue = Unsafe.As<T, long>(ref value);
                var longFlag = Unsafe.As<T, long>(ref flag);
                return (longValue & longFlag) == longFlag;
            }
            else
                throw new NotSupportedException("Enum with size of " + Unsafe.SizeOf<T>() + " are not supported");
        }
```

```asm
C.HasFlagWithCheck[[Lenum, _]](Lenum, Lenum)
    L0000: and rcx, rdx
    L0003: cmp rcx, rdx
    L0006: setz al
    L0009: movzx eax, al
    L000c: ret

C.HasFlagWithCheck[[Ienum, _]](Ienum, Ienum)
    L0000: and ecx, edx
    L0002: cmp ecx, edx
    L0004: setz al
    L0007: movzx eax, al
    L000a: ret
```

**Comment by kekekeks** [comment]
@AndyAyersMS 
https://github.com/dotnet/runtime/issues/43509

**Comment by grokys** [comment]
What is the status on this PR?

**Comment by YohDeadfall** [comment]
Since there's only `int` sized enums, I think I will just support them only for better code gen if you're okay with it. Perhaps, today will submit changes.

**Comment by YohDeadfall** [comment]
Accidentally dropped mine branch while cleaning up mine fork (`git branch -a` gave me endless list of branches). Going to open a new one soon.

**Pull request closed without merging**
