### PR TITLE
Fixed NativeControlHost to prevent calling ShowInBounds when bounds empty

### PR DESCRIPTION
**Pull request by joaompneves**
## What does the pull request do?
- Prevent showing native control when NativeControlHost bounds are empty

## What is the current behavior?
- Native control is shown with incorrect bounds during attachment phase

## What is the updated/expected behavior with this PR?
- Prevent showing native control when NativeControlHost bounds are empty

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=5413) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=5413) before we can accept your contribution.<br/><br/>:x: joaompneves [sign now](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=5413)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/AvaloniaUI/Avalonia?pullRequest=5413) it.</sub>

**Review by kekekeks — APPROVED** [review]
+1

**Review by kekekeks — DISMISSED** [review]
Actually, we should probably HIDE the control when bounds are invalid. That would require passing `null` to `HideWithSize`, or having a separate `Hide` call that doesn't update the size.

**Comment by joaompneves** [comment]
Can you pease make those changes as it requires changing native code? which I'm not confortable with

**Comment by kekekeks** [comment]
Sure, as soon as I get back to my macOS machine.

**Review by danwalmsley — APPROVED** [review]

**Pull request merged**
