### PR TITLE
WIP: Implement Metro Window Control

### PR DESCRIPTION
**Pull request by danwalmsley**
Implements control very similar to Mahapps Metro Window.

very basic at moment, so WIP for now.

### CODE REVIEW

**Comment by danwalmsley** [comment]
aiming for a design very close to this...
image

**Comment by punker76** [comment]
@danwalmsley haha, nice 👍

**Comment by grokys** [comment]
Hey @danwalmsley I'm going to close this out for now, please re-open a new PR if/when you complete this!

**Comment by nitanmarcel** [comment]
Do we have something like this already available?

**Comment by maxkatz6** [comment]
@nitanmarcel that style of window is not available out of box, but it isn't too hard to implement similar.
Check sample repository, which has fluent window with acrylic background:
https://github.com/AvaloniaUI/XamlControlsGallery

**Comment by nitanmarcel** [comment]
> @nitanmarcel that style of window is not available out of box, but it isn't too hard to implement similar.
> Check sample repository, which has fluent window with acrylic background:
> https://github.com/AvaloniaUI/XamlControlsGallery

Thanks. But 5 minutes ago I've found about [Avalonia.Shell](https://github.com/VitalElement/AvalonStudio.Shell/tree/ca0982b18c3b9b6f215cc8d76cd6199b8229e526) which does exactly what I'm looking for.

**Pull request closed without merging**
