### PR TITLE
Set CornerRadius via style

### PR DESCRIPTION
**Pull request by RolandUI**
## What does the pull request do?
This PR will remove from the control templates the local `CornerRadius` set and replace it via style set.

## What is the current behavior?
Currently, the `CornerRadius` is set locally in the template and later it is not possible to change it via style.

## What is the updated/expected behavior with this PR?
It will be possible to change the `CornerRadius` via style.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=4850) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=4850) before we can accept your contribution.<br/><br/>:x: soosr [sign now](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=4850)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/AvaloniaUI/Avalonia?pullRequest=4850) it.</sub>

**Review by jmacato — APPROVED** [review]
Glad to see you here @soosr  :) LGTM!

**Comment by soosr** [comment]
Thank you @jmacato!  I leave out a few controls which are not familiar to me but I am done with most.

**Review by danwalmsley — APPROVED** [review]
LGTM

**Pull request merged**
