### PR TITLE
Make sure PopupRoot.Parent is a Popup.

### LINKED ISSUE #2137: InvalidCastException on Popup.Open
Version: 0.7.0

Occurs when adding a `Popup` to the `LogicalChildren` of a `PopupRoot`.

```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidCastException: Unable to cast object of type 'RoslynPad.MainWindow' to type 'Avalonia.Controls.Primitives.Popup'.
   at Avalonia.Controls.Primitives.Popup.Open() in D:\a\1\s\src\Avalonia.Controls\Primitives\Popup.cs:line 255
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Subjects\Subject.cs:line 148
   at Avalonia.AvaloniaObject.RaisePropertyChanged(AvaloniaProperty property, Object oldValue, Object newValue, BindingPriority priority) in D:\a\1\s\src\Avalonia.Base\AvaloniaObject.cs:line 505
   at Avalonia.AvaloniaObject.<>c__DisplayClass46_0`1.<SetAndRaiseCore>b__0() in D:\a\1\s\src\Avalonia.Base\AvaloniaObject.cs:line 596
   at Avalonia.Utilities.DeferredSetter`1.<>c__DisplayClass12_0`1.<SetAndNotify>b__0(Action notification) in D:\a\1\s\src\Avalonia.Base\Utilities\DeferredSetter.cs:line 144
   at Avalonia.AvaloniaObject.SetAndRaiseCore[T](AvaloniaProperty property, T& field, T value, Action`1 notifyWrapper) in D:\a\1\s\src\Avalonia.Base\AvaloniaObject.cs:line 597
   at Avalonia.AvaloniaObject.<>c__DisplayClass45_0`1.<SetAndRaise>b__0(T val, T& backing, Action`1 notifyWrapper) in D:\a\1\s\src\Avalonia.Base\AvaloniaObject.cs:line 576
   at Avalonia.AvaloniaObject.<>c__DisplayClass44_0`1.<SetAndRaise>b__0(Object update, T& backing, Action`1 notify) in D:\a\1\s\src\Avalonia.Base\AvaloniaObject.cs:line 553
   at Avalonia.Utilities.DeferredSetter`1.SetAndNotify[TValue](AvaloniaProperty property, TValue& backing, SetterDelegate`1 setterCallback, TSetRecord value) in D:\a\1\s\src\Avalonia.Base\Utilities\DeferredSetter.cs:line 140
   at Avalonia.AvaloniaObject.SetAndRaise[T](AvaloniaProperty`1 property, T& field, SetAndRaiseCallback`1 setterCallback, T value) in D:\a\1\s\src\Avalonia.Base\AvaloniaObject.cs:line 547
   at Avalonia.AvaloniaObject.SetAndRaise[T](AvaloniaProperty`1 property, T& field, T value) in D:\a\1\s\src\Avalonia.Base\AvaloniaObject.cs:line 572
```

### PR DESCRIPTION
**Pull request by grokys**
## What does the pull request do?

Prevents an `InvalidCastException` in `Popup` is a `PopupRoot` is created that has a control other than `Popup` as its parent, as in [`AvaloniaEdit.CodeCompletion.CompletionWindowBase`](https://github.com/AvaloniaUI/AvaloniaEdit/blob/61db596a207ee00d2584300409eebb5892b5c68a/src/AvaloniaEdit/CodeCompletion/CompletionWindowBase.cs#L139).

## What is the current behavior?

AvaloniaEdit crashes with an `InvalidCastException`.

## How was the solution implemented (if it's not obvious)?

Make sure the parent is of the correct type before trying to use it.

## Fixed issues

Fixes #2137

### CODE REVIEW

**Review by ahopper — COMMENTED** [review]
I have a slight concern that if parent is neither Window or popup there should still be some event to trigger close on parent closing

**Comment by grokys** [comment]
What would you suggest in that case?

**Comment by grokys** [comment]
Thinking about it, if someone is parenting `PopupRoot` themselves, then saying "ok, you're responsible for closing the popup" sounds reasonable to me? Probably if they're doing that, there's a good reason for it, and one of those reasons may be that they _want_ to control the lifetime of the popup.

**Review by ahopper — APPROVED** [review]
That make sense to me.

**Pull request merged**
