### PR TITLE
Rework deferred renderer scene hit testing

### PR DESCRIPTION
**Pull request by MarchingCube**
## What does the pull request do?

Reworks current hit testing to use less memory. 

## What is the current behavior?

Recursive iterator blocks are causing far too many allocations. Results below are from moving a mouse over an empty area in `ControlCatalog` for like 15 seconds. It gets worse the more complex visual tree we have. This can allocate orders of magnitude more with more control nesting.

image

memory-before

## What is the updated/expected behavior with this PR?

Drops memory usage and traffic significantly. Only related allocation is in `PooledStack<Entry>` which could be eventually eliminated by either pooling stacks or implementing something like `ValuePooledStack`.

image

memory-after

To compare 1:1 you can take count of `PointerEventArgs` as a baseline, previous approach would allocate 100x more memory on top of it. New approach needs 0.5x more than base (compared to previous - 200x less).

## How was the solution implemented (if it's not obvious)?

Since we can't use regular recursion (we return an enumeration and current recursion allocates too much) I am using a stack based approach. Since this is invoked so frequently when using normal `Stack` we end up with stack related memory showing up as primary allocation. 

To combat this I figured we can used pooled variants from https://github.com/jtmueller/Collections.Pooled/tree/master/Collections.Pooled. To avoid nuget dependency hell we have to keep a copy since user code might be using different version. I still need to add proper license attribution to code that is not from corefx.

I think pooled collections can benefit our codebase greatly as in many areas we end up allocating a lot of temporary buffers that can be saved by pooling.

Open questions are:
- should these collections live in `Avalonia.Base`?
- `PooledList` and `PooledStack` are currently public since we are using that code outside of `Avalonia.Base`. But users are not supposed to use this (like `ViewModelBase` in `Avalonia.Diagnostics`) so we can either mark it internal and then we need tons of `InternalsVisibleTo` attributes. Or shipping reference assemblies, but I guess that is a long journey.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

### CODE REVIEW

**Comment by jmacato** [comment]
@MarchingCube i wonder if `ArrayPool<>` would do the same job as `Collections.Pooled`? or is there some significant differences between the two?

**Comment by MarchingCube** [comment]
@jmacato `Collections.Pooled` are basically collections variants that use `ArrayPool` to allocate.

**Comment by jmacato** [comment]
@MarchingCube makes sense, thanks alot for enlightening me  :)

**Comment by MarchingCube** [comment]
Also we have to be careful in the future - https://github.com/AvaloniaUI/Avalonia/pull/3033 caused extra half a megabyte of garbage to be allocated (not significant in old implementation, but almost doubling memory usage in new approach) by using `Enum.HasFlag`.

**Review by grokys — APPROVED** [review]
LGTM! Yeah I think putting the pooled collections there makes sense, true it's possible that people could take an unwanted dependency on them but that's a wider problem that we need to address before 1.0.

**Pull request merged**
