### PR TITLE
[Theme] [Default] Unify Avalonia.Themes.Default xaml resources embedding

### PR DESCRIPTION
**Pull request by wieslawsoltes**
## What does the pull request do?

Unifies Avalonia.Themes.Default xaml resources embeding

## What is the current behavior?

The resource are embedded twice by using EmbeddedResource and AvaloniaResource

## What is the updated/expected behavior with this PR?

Embed xaml resource using AvaloniaResource 

## How was the solution implemented (if it's not obvious)?

Removed EmbeddedResource and added .xaml files wildcard for AvaloniaResource

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

### CODE REVIEW

**Review by kekekeks — APPROVED** [review]
A bit later to do during the RC phase, but OK

**Comment by wieslawsoltes** [comment]
.xaml is not added by default as `.axaml` and `.paml`, should we make breaking change and change all .xaml files to .axaml, this would be on par with default targets

**Comment by maxkatz6** [comment]
@wieslawsoltes tests fails because in some places we are still using old style include syntax:
```
  Error Message:
   Avalonia.Markup.Xaml.XamlLoadException : No precompiled XAML found for resm:Avalonia.Themes.Default.Accents.BaseLight.xaml?assembly=Avalonia.Themes.Default (baseUri: ), make sure to specify x:Class and include your XAML file as AvaloniaResource
  Stack Trace:
     at Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Uri uri, Uri baseUri) in /home/vsts/work/1/s/src/Markup/Avalonia.Markup.Xaml/AvaloniaXamlLoader.cs:line 76
   at Avalonia.UnitTests.TestServices.CreateDefaultTheme() in /home/vsts/work/1/s/tests/Avalonia.UnitTests/TestServices.cs:line 170
   at Avalonia.UnitTests.TestServices.<>c.<.cctor>b__66_0() in /home/vsts/work/1/s/tests/Avalonia.UnitTests/TestServices.cs:line 28
   at Avalonia.UnitTests.UnitTestApplication.RegisterServices() in /home/vsts/work/1/s/tests/Avalonia.UnitTests/UnitTestApplication.cs:line 69
   at Avalonia.UnitTests.UnitTestApplication..ctor(TestServices services) in /home/vsts/work/1/s/tests/Avalonia.UnitTests/UnitTestApplication.cs:line 29
   at Avalonia.UnitTests.UnitTestApplication.Start(TestServices services) in /home/vsts/work/1/s/tests/Avalonia.UnitTests/UnitTestApplication.cs:line 38
   at Avalonia.Controls.UnitTests.TolTipTests.Open_Class_Should_Not_Initially_Be_Added() in /home/vsts/work/1/s/tests/Avalonia.Controls.UnitTests/ToolTipTests.cs:line 206

```

**Comment by grokys** [comment]
@wieslawsoltes - still seems to be failing on CI.

**Comment by wieslawsoltes** [comment]
> @wieslawsoltes - still seems to be failing on CI.

Probably this is still failing 
https://github.com/AvaloniaUI/Avalonia/pull/5204/files#diff-f483dada972cf974fd4df2a8757aaae40bb798fa4dbaaeee7a59f00facc145c2R171

**Comment by danwalmsley** [comment]
I thought we were leaving default theme as is.. to not break backwards compatibility?

**Comment by grokys** [comment]
Yeah I think this is a breaking change, so probably need to wait for 11.0.

**Comment by grokys** [comment]
@wieslawsoltes I think we can merge this now if you'd like to fix the conflicts.

**Comment by wieslawsoltes** [comment]
@grokys Pushed but seems some test fail because of usage of avares https://github.com/AvaloniaUI/Avalonia/pull/5204/files#diff-f483dada972cf974fd4df2a8757aaae40bb798fa4dbaaeee7a59f00facc145c2R171

**Comment by jmacato** [comment]
@wieslawsoltes is this backportable?

**Comment by wieslawsoltes** [comment]
> @wieslawsoltes is this backportable? coz it seems to be so

Not sure, @grokys added braking-change label.

**Comment by maxkatz6** [comment]
Continued in https://github.com/AvaloniaUI/Avalonia/pull/7353

**Pull request closed without merging**
