### PR TITLE
Set double tap of a TreeViewItem on ContentPresenter instead of whole header

### PR DESCRIPTION
**Pull request by yexcoffier**
## What does the pull request do?
Set the double tap behavior of a TreeViewItem on the Content Presenter instead of the whole header including the toggle button.

## What is the current behavior?
When double tapping on the toggle button of a TreeViewItem, the toggle button click event and the double tap are both used which gives an unexpected behavior.

## What is the updated/expected behavior with this PR?
To ignore double tap event on the toggle button but not on the content presenter part.

## How was the solution implemented (if it's not obvious)?
TreeViewItem.cs double tapped event takes the PART_HeaderPresenter control instead of PART_Header. The simpletheme and fluenttheme were also slightly changed so the ContentPresenter background is set to Transparent to capture the tap event..

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

### CODE REVIEW

**Comment by yexcoffier** [comment]
@dotnet-policy-service agree

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0033798-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Review by grokys — APPROVED** [review]
LGTM, thanks for contributing!

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0033816-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Pull request merged**
