### PR TITLE
Bump SDK, TFM for desktop sample to net5.0 and Nuke to 5.0.2

### PR DESCRIPTION
**Pull request by rstm-sf**
## What does the pull request do?
Bump SDK, TFM for desktop sample to net5.0 and Nuke to 5.0.2

## What is the current behavior?
Limit to .NET Core 3.1 and C#8

## What is the updated/expected behavior with this PR?
Limit to .NET 5.0 and C#9

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

### CODE REVIEW

**Comment by rstm-sf** [comment]
The following problems are currently observed:
1. Linux: https://dev.azure.com/AvaloniaUI/AvaloniaUI/_build/results?buildId=12742&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=5b4cc83a-7bb0-5664-5bb1-588f7e4dc05b&l=1104
<details>

```
##[error][1/2] ArgumentNullException: Value cannot be null. (Parameter 'genericType')
   at ICSharpCode.Decompiler.TypeSystem.ParameterizedType..ctor(IType genericType, IEnumerable`1 typeArguments)
   at Pharmacist.Core.Generation.ReflectionExtensions.GetRealType(IType type, ICompilation compilation) in D:\a\1\s\src\Pharmacist.Core\Generation\ReflectionExtensions.cs:line 147
   at Pharmacist.Core.Generation.ReflectionExtensions.GetEventType(IEvent eventDetails) in D:\a\1\s\src\Pharmacist.Core\Generation\ReflectionExtensions.cs:line 112
   at Pharmacist.Core.Generation.Resolvers.EventNamespaceResolverBase.IsValidParameters(IEvent eventDetails) in D:\a\1\s\src\Pharmacist.Core\Generation\Resolvers\EventNamespaceResolverBase.cs:line 32
   at Pharmacist.Core.Generation.Resolvers.PublicEventNamespaceResolver.IsValidEvent(IEvent x) in D:\a\1\s\src\Pharmacist.Core\Generation\Resolvers\PublicEventNamespaceResolver.cs:line 133
   at Pharmacist.Core.Generation.Resolvers.PublicEventNamespaceResolver.<>c__DisplayClass1_0.<GetValidEventDetails>b__1(ITypeDefinition typeDefinition) in D:\a\1\s\src\Pharmacist.Core\Generation\Resolvers\PublicEventNamespaceResolver.cs:line 62
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()

##[error][2/2] ArgumentNullException: Value cannot be null. (Parameter 'genericType')
   at ICSharpCode.Decompiler.TypeSystem.ParameterizedType..ctor(IType genericType, IEnumerable`1 typeArguments)
   at Pharmacist.Core.Generation.ReflectionExtensions.GetRealType(IType type, ICompilation compilation) in D:\a\1\s\src\Pharmacist.Core\Generation\ReflectionExtensions.cs:line 147
   at Pharmacist.Core.Generation.ReflectionExtensions.GetEventType(IEvent eventDetails) in D:\a\1\s\src\Pharmacist.Core\Generation\ReflectionExtensions.cs:line 112
   at Pharmacist.Core.Generation.Resolvers.EventNamespaceResolverBase.IsValidParameters(IEvent eventDetails) in D:\a\1\s\src\Pharmacist.Core\Generation\Resolvers\EventNamespaceResolverBase.cs:line 32
   at Pharmacist.Core.Generation.Resolvers.PublicEventNamespaceResolver.IsValidEvent(IEvent x) in D:\a\1\s\src\Pharmacist.Core\Generation\Resolvers\PublicEventNamespaceResolver.cs:line 133
   at Pharmacist.Core.Generation.Resolvers.PublicEventNamespaceResolver.<>c__DisplayClass1_0.<GetValidEventDetails>b__1(ITypeDefinition typeDefinition) in D:\a\1\s\src\Pharmacist.Core\Generation\Resolvers\PublicEventNamespaceResolver.cs:line 62
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
```

</details>

2. MacOS: https://dev.azure.com/AvaloniaUI/AvaloniaUI/_build/results?buildId=12742&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=bde16fc7-7659-5b1c-12aa-0110866d993c&l=1240
<details>

```
NotSupportedException: Specified method is not supported.
....
CreateNugetPackages                Failed
```

</details>

3. Windows: https://dev.azure.com/AvaloniaUI/AvaloniaUI/_build/results?buildId=12742&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=f33089cd-d3fe-578c-2c5e-4ee560e10a0d&l=578

<details>

```
##[error]ProcessException: Process 'MSBuild.exe' exited with code 1.
   > "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" D:\a\1\s\dirs.proj /p:JavaSdkDirectory="C:\Program Files\Java\jdk8u282-b08" /p:PackageVersion=0.10.999-cibuild0012742-beta /p:iOSRoslynPathHackRequired=True /p:Configuration=Release /target:Build /verbosity:Minimal /r
   @ D:\a\1\s

   at Nuke.Common.Tooling.ProcessExtensions.AssertZeroExitCode(IProcess process)
   at Nuke.Common.Tools.MSBuild.MSBuildTasks.MSBuild(MSBuildSettings toolSettings)
   at Nuke.Common.Tools.MSBuild.MSBuildTasks.MSBuild(Configure`1 configurator)
   at Build.MsBuildCommon(String projectFile, Configure`1 configurator) in D:\a\1\s\nukebuild\Build.cs:line 102
   at Build.<get_Compile>b__15_1() in D:\a\1\s\nukebuild\Build.cs:line 159
   at Nuke.Common.Execution.TargetDefinition.<>c__DisplayClass62_0.<Executes>b__0()
   at Nuke.Common.Execution.BuildExecutor.<>c.<Execute>b__4_0(Action x)
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode)

```

</details>

**Comment by jp2masa** [comment]
The problem is actually this I think: https://dev.azure.com/AvaloniaUI/AvaloniaUI/_build/results?buildId=12742&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=f33089cd-d3fe-578c-2c5e-4ee560e10a0d&l=351.

<details>
<summary>Details</summary>

```
D:\a\1\s\build\MicroCom.targets(18,5): error : It was not possible to find any compatible framework version [D:\a\1\s\src\Windows\Avalonia.Win32\Avalonia.Win32.csproj]
D:\a\1\s\build\MicroCom.targets(18,5): error : The framework 'Microsoft.NETCore.App', version '3.1.0' was not found. [D:\a\1\s\src\Windows\Avalonia.Win32\Avalonia.Win32.csproj]
D:\a\1\s\build\MicroCom.targets(18,5): error :   - The following frameworks were found: [D:\a\1\s\src\Windows\Avalonia.Win32\Avalonia.Win32.csproj]
D:\a\1\s\build\MicroCom.targets(18,5): error :       5.0.2 at [C:\hostedtoolcache\windows\dotnet\shared\Microsoft.NETCore.App] [D:\a\1\s\src\Windows\Avalonia.Win32\Avalonia.Win32.csproj]
D:\a\1\s\build\MicroCom.targets(18,5): error :  [D:\a\1\s\src\Windows\Avalonia.Win32\Avalonia.Win32.csproj]
D:\a\1\s\build\MicroCom.targets(18,5): error : You can resolve the problem by installing the specified framework and/or SDK. [D:\a\1\s\src\Windows\Avalonia.Win32\Avalonia.Win32.csproj]
D:\a\1\s\build\MicroCom.targets(18,5): error :  [D:\a\1\s\src\Windows\Avalonia.Win32\Avalonia.Win32.csproj]
D:\a\1\s\build\MicroCom.targets(18,5): error : The specified framework can be found at: [D:\a\1\s\src\Windows\Avalonia.Win32\Avalonia.Win32.csproj]
D:\a\1\s\build\MicroCom.targets(18,5): error :   - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.1.0&arch=x64&rid=win10-x64 [D:\a\1\s\src\Windows\Avalonia.Win32\Avalonia.Win32.csproj]
D:\a\1\s\build\MicroCom.targets(18,5): error MSB3073: The command "dotnet D:\a\1\s\build\../src/tools/MicroComGenerator/bin/Release/netcoreapp3.1/MicroComGenerator.dll -i WinRT\winrt.idl --cs WinRT\WinRT.Generated.cs" exited with code -2147450730. [D:\a\1\s\src\Windows\Avalonia.Win32\Avalonia.Win32.csproj]
D:\a\1\s\src\Skia\Avalonia.Skia\Gpu\OpenGl\GlSkiaGpu.cs(69,30): warning CS0168: The variable 'e' is declared but never used [D:\a\1\s\src\Skia\Avalonia.Skia\Avalonia.Skia.csproj]
D:\a\1\s\src\Skia\Avalonia.Skia\Gpu\ISkiaGpu.cs(24,77): warning CS1573: Parameter 'session' has no matching param tag in the XML comment for 'ISkiaGpu.TryCreateSurface(PixelSize, ISkiaGpuRenderSession)' (but other parameters do) [D:\a\1\s\src\Skia\Avalonia.Skia\Avalonia.Skia.csproj]
```

</details>

**Comment by jp2masa** [comment]
You also have to update the TFM to `net5.0` here:

- https://github.com/AvaloniaUI/Avalonia/blob/1a39210febf92e9e87b3ebacca9b56d99e660913/tests/Avalonia.DesignerSupport.Tests/DesignerSupportTests.cs#L38
- https://github.com/AvaloniaUI/Avalonia/blob/1a39210febf92e9e87b3ebacca9b56d99e660913/tests/Avalonia.DesignerSupport.Tests/DesignerSupportTests.cs#L50

**Comment by jp2masa** [comment]
I think the problem is this:

1. https://github.com/jbevain/cecil/blob/1b1b58a5da2a261d003f3f2647f7219b5344f20d/Mono.Cecil/ModuleDefinition.cs#L176
2. https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.CoreLib/src/System/Reflection/Assembly.cs#L87

**Comment by jp2masa** [comment]
For now I would recommend downgrading `_build` to `netcoreapp3.1`, unless it's needed for some reason?

**Comment by rstm-sf** [comment]
@jp2masa thank you very much for help!

> 
> 
> I think the problem is this:
> 
>     1. https://github.com/jbevain/cecil/blob/1b1b58a5da2a261d003f3f2647f7219b5344f20d/Mono.Cecil/ModuleDefinition.cs#L176
> 
>     2. https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.CoreLib/src/System/Reflection/Assembly.cs#L87

This should be fixed in the original https://github.com/jbevain/cecil/issues/669. I didn't think that in the end there would be a fork on the fork

**Comment by rstm-sf** [comment]
It seems to me, that it is better to begin with simple and easier to try to lift the version sdk https://github.com/AvaloniaUI/Avalonia/pull/5400

**Pull request closed without merging**
