### PR TITLE
Exclude snap directories in Managed Dialogs volume enumeration

### PR DESCRIPTION
**Pull request by jmacato**
Fixes the issue on some linux distros that uses snap app package/virtualization where the managed dialogs are showing the tiny volume mounts that snap allocates for each package.

### CODE REVIEW

**Comment by Gillibald** [comment]
Hmm. Wouldn't it be better to make this filter pluggable? Excluding locations might be needed more frequently.

**Comment by lontivero** [comment]
Tested. It works okay in my machine where previously it displayed many volumes for /snap

**Comment by kekekeks** [comment]
The thing is, we shouldn't be using /proc/mounts in the first place. Waaaaaay to many things can get mounted on a Linux system. UDisks is the preferred way of getting mount lists.

**Comment by jmacato** [comment]
@Gillibald I don't want to introduce new API's in 0.9. could be done in master branch after this though.
@kekekeks I think we talked about this before, because there are times where DBus is not available (fbdev/embedded) hence i wrote this code that compares /proc/partitions and /proc/mounts instead. I also was not able to properly communicate with UDisk2 on ubuntu.. but that could just be me lacking the know-how on that part of Freedesktop specs...

**Comment by kekekeks** [comment]
If you want to enumerate volumes without udisks, limit your enumeration to mounts `/media`.

**Comment by jmacato** [comment]
@kekekeks i think that was the previous behavior right? it isnt foolproof since it can either be in /media, /run or /mnt or worse, in user's home directory.

**Review by kekekeks — APPROVED** [review]
Since the whole thing has to be replaced by udisks anyway, I'm fine with adding more hacks.

**Comment by jmacato** [comment]
@kekekeks Thanks for the reconsideration, I'll be working on a UDisk-based replacement for this later afterwards!

**Pull request merged**
