### PR TITLE
Created a shared DataValidationErrors framework

### PR DESCRIPTION
**Pull request by sdoroff**
Moved Validation Error tracking to attached an attached property
Created an shared error indicator that can be simply added to control
templates and re-styled across all controls
This should reduce the need for code and markup duplication while
allowing for a consistent visual interface

### CODE REVIEW

**Comment by sdoroff** [comment]
I think the making it a direct property is valuable for consistency and simplicity, but it does hide functionality. Making the property settable has value in some use-cases and being able to bind the value of the property has simplified the control template of the DatePicker control I'm building (the TextBox can just display any data errors). I feel its important to include this in the first Beta, as it is a breaking change to the TextBox. 
Though, I had a few questions regarding my implementation:
1. Should the control be split out into a separate class from the attached properties?
2. Should there be another property for a DataTemplate for the ToolTip?
3. Is there a way to directly set the border and background of a ToolTip not through a style?
4. The complex binding logic in the ControlTemplate is un-ideal, is it worth making the ContentControl a named part and wiring up the Binding in the OnTemplateApplied method?

**Comment by grokys** [comment]
Thanks for the PR @sdoroff. I've not reviewed this properly yet, but I do have a question: what other controls do you see this applying to? You mention your `DatePicker` control, are there any other core controls that this would be applied to?

**Comment by sdoroff** [comment]
@grokys , my responses are below.

> What other controls do you see this applying to? You mention your `DatePicker` control, are there any other core controls that this would be applied to?

Currently I'm planning on using it for `DatePicker` and `AutoCompleteTextBox`. I think it will have a place in editable cells within a `DataGrid` and would probably like to add it to the `DropDown` for when a required selection isn't made.

> Is there anything similar to this in any other frameworks?

The attached properties are similar to the `Validation` class in WPF. For the actual user interface, WPF has an attached `ErrorTemplate` property that stores a `ControlTemplate` that is added to the adorner layer. This isn't possible in Avalonia as the adorner layer is not hit test visible which is required for tool tips.

**Comment by grokys** [comment]
@sdoroff I've taken a look at this and I like it! My only concern is that it adds an extra `ContentControl` and `ContentPresenter` to the depth of the visual tree for every `TextBox`, but I'm hoping that shouldn't be a problem.

Regarding your questions:

> Should the control be split out into a separate class from the attached properties?

No, I think it makes sense to have the properties defined there.

> Should there be another property for a DataTemplate for the ToolTip?

Not sure, at this point I'm thinking probably not. We can revisit that decision later if the need comes up.

> Is there a way to directly set the border and background of a ToolTip not through a style?

Not currently, it may be that there should be, though I don't think WPF allows this without re-templating `ToolTip`?

> The complex binding logic in the ControlTemplate is un-ideal, is it worth making the ContentControl a named part and wiring up the Binding in the OnTemplateApplied method?

I quite like the way the `DataValidationErrors` automatically picks up the contained control without you having to do anything. One thing I'm not sure about is how it does this by hooking into the `TemplatedParent` property - it might be nice if you could wrap a control in a `DataValidationErrors` control _outside_ a template. To do this you could listen to the `Content` property to get the child control?

I'm going to approve this. Let me know if you want to merge it now, or take a look into listening to the `Content` property. That can be done separately if you want to though I think.

**Review by grokys — APPROVED** [review]

**Comment by grokys** [comment]
Ok, I've merged this - we can think about improvements in another PR. Thanks @sdoroff!

**Pull request merged**
