### PR TITLE
Allow for showing child windows

### PR DESCRIPTION
**Pull request by MarchingCube**
## What does the pull request do?

Adds a concept and implementation of window ownership. 

## What is the current behavior?

`WindowBase.Owner` is simply ignored.

## What is the updated/expected behavior with this PR?

You can use `Window.Show(Window parent)` on desktop platforms to show child windows.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

### CODE REVIEW

**Comment by Sorien** [comment]
what happens when you try to show as a child with a parent that is is not visible?

**Comment by MarchingCube** [comment]
Good question, I've checked WPF and this PR - both just show child window normally. WPF has one quirk - you must show parent window at least once before assigning it as `Owner`.

**Comment by danwalmsley** [comment]
WPF Specification:
If an owner window is minimized, all its owned windows are minimized as well.

If an owned window is minimized, its owner is not minimized.

If an owner window is maximized, both the owner window and its owned windows are restored.

An owner window can never cover an owned window.

Owned windows that were not opened using ShowDialog are not modal. The user can still interact with the owner window.

If you close an owner window, its owned windows are also closed.

If an owned window was opened by its owner window using Show, and the owner window is closed, the owned window's Closing event is not raised.

**Comment by danwalmsley** [comment]
WPF Specification Win32:

- [x] If an owner window is minimized, all its owned windows are minimized as well.

- [ ] If an owned window is minimized, its owner is not minimized.

- [ ] If an owner window is maximized, both the owner window and its owned windows are restored.

- [x] An owner window can never cover an owned window.

- [ ] Owned windows that were not opened using ShowDialog are not modal. The user can still interact with the owner window.

- [ ] If you close an owner window, its owned windows are also closed.

- [ ] If an owned window was opened by its owner window using Show, and the owner window is closed, the owned window's Closing event is not raised.

**Comment by danwalmsley** [comment]
WPF Specification X11:

- [x] If an owner window is minimized, all its owned windows are minimized as well.

- [ ] If an owned window is minimized, its owner is not minimized.

- [ ] If an owner window is maximized, both the owner window and its owned windows are restored.

- [x] An owner window can never cover an owned window.

- [ ] Owned windows that were not opened using ShowDialog are not modal. The user can still interact with the owner window.

- [ ] If you close an owner window, its owned windows are also closed.

- [ ] If an owned window was opened by its owner window using Show, and the owner window is closed, the owned window's Closing event is not raised.

**Comment by MarchingCube** [comment]
This is actually more complicated to get right cross-plat than anticipated and our shutdown/window close might need more work to support everything. Might revisit in the future.

**Comment by Gillibald** [comment]
I suggested to move the window bookkeeping into the windowing platform in the past. Maybe that makes things easier.

What part of your work didn't work out well?

**Comment by MarchingCube** [comment]
Main issues were with closing parent windows and cancellation of such. WPF for instance won't invoke any `Closing` callbacks when you close parent window. For us we wanted to make sure that we invoke `Closing` handlers for dialogs. Which is causing issues since `Window.Close` will just dispose platform implementation which on X11 and Win32 will just destroy current window. On Win32 it will kill child windows but won't notify about closing. On X11 it will just leave child windows open.

I've tried to come up with a solution for this, but in the end I am not sure what is the correct behavior here across different platform.

**Comment by Gillibald** [comment]
Thanks for your summary

**Comment by danwalmsley** [comment]
bringing this back to life!

**Comment by MarchingCube** [comment]
@danwalmsley @kekekeks Reworked this on top of the new API.

**Comment by danwalmsley** [comment]
@MarchingCube wow much simpler now :) will test in the morning.

**Comment by danwalmsley** [comment]
Final Tests:
- [ ] Windows
- [ ] OSX
- [ ] Linux

**Review by danwalmsley — APPROVED** [review]
LGTM...

Tested osx and windows... all conditions met.

@MarchingCube has confirmed x11 also.

**Pull request merged**
