### PR TITLE
Set antialias to true when calling ClipRoundRect

### LINKED ISSUE #7358: Lack of anti-aliasing when encapsulating any control in a Border with a set CornerRadius
**Describe the bug**
Avalonia's renderer does not seem to de-alias rounded corners of a Border correctly when an image is in the corner. Could apply to other controls as well.

**To Reproduce**

1. Create a new Avalonia project.
2. Add an image to your Assets folder, preferably one that is not transparent around the corners so the effect is visible, and one that is is a contrasting color to the background.
3. In the main window, put a Border as the main child of the window, make sure it is the same size as your chosen image, set the CornerRadius of the border to something like 20 or 30 depending on your image size, place an Image tag inside your border with your chosen image URI, then set "ClipToBounds" to "true" on the border. See screenshots for example AXAML.

**Expected behavior**
Avalonia should apply proper anti aliasing to the corners, like the second example screenshot below (taken from chrome).

**Screenshots**
An example of the problem, taken from a new Avalonia project
Expected behavior, taken from Chrome
Example AXAML that should reproduce the problem in Avalonia 0.10.11 & 0.10.10

**Desktop:**

- OS: Windows 11, Windows 10, Ubuntu 20.04 via WSL2, and Manjaro Linux with NVIDIA proprietary drivers.
- Version: 0.10.11 & 0.10.10

### PR DESCRIPTION
**Pull request by JamDoggie**
## What does the pull request do?
Fixes issue #7358. Summary: sets anti alias to true when applying a rounded rectangle clip. This makes it so any controls rendered within, say, a border with a CornerRadius get properly anti-aliased around the corners when cut off.

## What is the current behavior?
antialias is not set to true, so controls clipped off by their parent's CornerRadius show very visible aliasing.

## What is the updated/expected behavior with this PR?
Controls with a CornerRadius now properly anti-alias on corners.

## Fixed issues
Fixes #7358

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=7368) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=7368) before we can accept your contribution.<br/><br/>:x: JamDoggie [sign now](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=7368)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/AvaloniaUI/Avalonia?pullRequest=7368) it.</sub>

**Comment by kekekeks** [comment]
IIRC that previously caused glitches on Apple hardware. 
@danwalmsley

**Comment by JamDoggie** [comment]
I mean, you guys set the anti alias argument elsewhere in the exact file. Unless it is an issue with the rounded rect specifically.

**Comment by robloo** [comment]
If there was an issue, that should have been documented in code when it was disabled.

**Comment by kekekeks** [comment]
Don't get me wrong, I'm not against merging, I've just asked @danwalmsley to check on his apple hardware.

**Comment by jmacato** [comment]
@kekekeks Lemme check on mine, if it doesnt have any artifacts let's merge it

**Review by jmacato — APPROVED** [review]
LGTM on Mac M1 

pending @danwalmsley's review

**Comment by danwalmsley** [comment]
@kekekeks looks good, im 100% sure it did cause an issue at some point, but could be due to stencil buffers.

Iv tested this with many scenarios and test apps and couldnt see anything obvious.

**Comment by danwalmsley** [comment]
> If there was an issue, that should have been documented in code when it was disabled.

it wasnt disabled, its disabled by default... the work was done to enable it in some scenarios.

**Comment by danwalmsley** [comment]
OK there was a good reason for this... Clipping doesnt work.. we shall have to revert this.

**Comment by robloo** [comment]
1. In what scenarios?
2. This should really be documented in code with a TODO to re-enable later

**Comment by JamDoggie** [comment]
> OK there was a good reason for this... Clipping doesnt work.. we shall have to revert this.

If we can find out a repro I'd be glad to attempt to find a fix and open another pull request.

**Comment by JamDoggie** [comment]
Hey, if this pull request caused an issue we should probably figure out what it is and make an issue to get it fixed.

**Pull request merged**
