### PR TITLE
Control data validation fix

### LINKED ISSUE #4559: Validation via DataAnnotation as well as binding exceptions produce bad UX
With a simple view model that uses `RequiredAttribute`, the result of the validation this:

image

Notice the exception type prefix.

There are two ways how to fix this. First is to use `DataValidationException` in https://github.com/AvaloniaUI/Avalonia/blob/release/0.10.0-preview3/src/Avalonia.Base/Data/Core/Plugins/DataAnnotationsValidationPlugin.cs#L66

Change to
```
                    return new DataValidationException(errors[0].ErrorMessage);
```

(and similar changes required for https://github.com/AvaloniaUI/Avalonia/blob/release/0.10.0-preview3/src/Avalonia.Base/Data/Core/Plugins/DataAnnotationsValidationPlugin.cs#L70 and maybe also https://github.com/AvaloniaUI/Avalonia/blob/release/0.10.0-preview3/src/Avalonia.Base/Data/Core/Plugins/ExceptionValidationPlugin.cs)

This will cause the result to be as expected:
image

Similarly, there are problems with binding exception, e.g. from invalid number to a number. This is an issue since there is no validation error displayed on NumericUpDown (#3591), but possibly there are more binding exceptions that even having working validation on NumericUpDown would not solve. It looks like this:

image

This could be worked around with using `int` field, but `string` property and check if the value on setter is a number of not, and if not, throwing `DataValidationException`. I thought changing `ExceptionValidationPlugin` might fix this, but it did not work for me.

image

The second way of fixing this, that might fix both problems (haven't checked), is actually changing the code of `GetExceptionData` (https://github.com/AvaloniaUI/Avalonia/blob/release/0.10.0-preview3/src/Avalonia.Controls/DataValidationErrors.cs#L133), change to:

```
        private static object GetExceptionData(Exception exception)
        {
            if (exception is DataValidationException dataValidationException)
                return dataValidationException.ErrorData;

            return exception.Message;
        }
```

or something similar (haven't tested this one)...

### PR DESCRIPTION
**Pull request by KieranDevvs**
## What does the pull request do?
Changes the validation exception type to `DataValidationException` so `DataValidationErrors` can cast the expected type and extract the user friendly validation message to be displayed.

```
        private static object GetExceptionData(Exception exception)
        {
            if (exception is DataValidationException dataValidationException)
                return dataValidationException.ErrorData;

            return exception;
        }
```

## What is the current behavior?
Control validation exceptions currently display the validation message with a prefix of the exception type.

## What is the updated/expected behavior with this PR?
`DataValidationErrors` is able to read the user friendly exception message rather than returning the whole exception object.

## How was the solution implemented (if it's not obvious)?
Its obvious.

## Checklist

- [X] Added unit tests (if possible)? (Unit test modified)
- [X] Added XML documentation to any related classes? None required.
- [X] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

## Fixed issues

Fixes #4559

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=4704) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=4704) before we can accept your contribution.<br/><br/>:x: KieranDevvs [sign now](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=4704)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/AvaloniaUI/Avalonia?pullRequest=4704) it.</sub>

**Review by grokys — CHANGES_REQUESTED** [review]
Hey! Sorry for the delay in reviewing this. I just tried it by running `BindingDemo` in the main Avalonia repository and going to the "Property Validation" tab then entering 10 in the "Less than 10" `TextBox` and I see:

image

Should this PR fix this case too? Feels like it probably should?

**Comment by KieranDevvs** [comment]
> Hey! Sorry for the delay in reviewing this. I just tried it by running `BindingDemo` in the main Avalonia repository and going to the "Property Validation" tab then entering 10 in the "Less than 10" `TextBox` and I see:
> 
> image
> 
> Should this PR fix this case too? Feels like it probably should?

Theoretically no...
The `BindingDemo` overrides the default implementation of validation.

```
<StackPanel Margin="18" Spacing="4" MinWidth="200" DataContext="{Binding ExceptionDataValidation}">
      <TextBlock FontSize="16" Text="Exception Validation"/>
      <TextBox Watermark="Less Than 10" UseFloatingWatermark="True" Text="{Binding Path=LessThan10}"/>
</StackPanel>
```

```
 public class ExceptionErrorViewModel : ReactiveObject
    {
        private int _lessThan10;

        public int LessThan10
        {
            get { return _lessThan10; }
            set
            {
                if (value < 10)
                {
                    this.RaiseAndSetIfChanged(ref _lessThan10, value);
                }
                else
                {
                    throw new ArgumentOutOfRangeException(nameof(value), "Value must be less than 10.");
                }
            }
        }
    }
```

Changing the exception type from `ArgumentOutOfRangeException` to `DataValidationException` i.e
```
{
    throw new DataValidationException($"{nameof(value)} must be less than 10.");
}
```
Results in:
image

IMO, everything is in working as expected. I think the question that needs to be asked is... Is it necessary for the binding demo to override the validation rather than just using the built in `[Range(min, max, message)]` validation attribute.

Changing the `DataContext` for the textbox from 'ExceptionErrorViewModel' to 'DataAnnotationsValidation' removes the getter validation override and thus results in the default message:
image

My opinion would be to remove `ExceptionErrorViewModel` and just rely on the default exception for validation attributes to be thrown...

**Comment by maxkatz6** [comment]
> Is it necessary for the binding demo to override the validation rather than just using the built in [Range(min, max, message)] validation attribute

There is another example with data validation attributes in the BindingDemo. So, exception sample just shows available option that is supported by Avalonia.

**Comment by KieranDevvs** [comment]
> > Is it necessary for the binding demo to override the validation rather than just using the built in [Range(min, max, message)] validation attribute
> 
> There is another example with data validation attributes in the BindingDemo. So, exception sample just shows available option that is supported by Avalonia.

Hmmm, if you want to use custom validation, then you also need to override the validation template so it knows how to display the exception correctly rather than `.ToString()`-ing the object (exception) and dumping it.

I don't know enough about Avalonia to make that change and there's nothing in the documentation. Can anyone point me in the right direction?

**Review by grokys — APPROVED** [review]
> Or I could just update the demo project validation to throw DataValidationException rather than ArgumentOutOfRangeException and that should achieve the same result while showing off the fact that you can implement custom validation rules?

No, I think what you're saying makes sense, or at least can be addressed in a separate PR. Lets get this merged and worry about the exception case later if need be.

**Pull request merged**
