### PR TITLE
Implement DataContext update notifications on the DataGrid

### LINKED ISSUE #5661: Combobox in Datagrid's index reset to -1 after changing tab
**Describe the bug**
It is possible to run into a situation where a Combobox in a datagrid can have its index reset to -1 when changing tab. I am linking here a very small project which allows to reproduce this issue.

**To Reproduce**

1. Open and compile the provided project
2. Go to the "Party" tab
3. Observe the items in the combobox being rendered correctly (see the code for details, it just adds 3 integers with the descriptions being hardcoded)
4. Go to the "Global" tab
5. Go BACK to the "Party" tab
6. Observe the comboox showing nothing. The selected index actually was set to -1 when step 4 occured.

**Expected behavior**
To have the combobox retain their values after switching tabs

**Screenshots**
Before switching tabs:
Screenshot 2021-03-14 003123

After switching tab:
Screenshot 2021-03-14 003137

**Desktop (please complete the following information):**

- OS: Windows 10
- Version 0.10.0

**Additional context**
Here is the zip that can reproduce this issue: 
[ComboboxIssueSample.zip](https://github.com/AvaloniaUI/Avalonia/files/6136157/ComboboxIssueSample.zip)

### PR DESCRIPTION
**Pull request by aldelaro5**
## What does the pull request do?
This fixes #5661 by allowing the `DataGrid` to notify its cells that their `DataContext` is about to be changed. This allows controls who needs to have these notifications (such as any `SelectingItemsControls`) to get notified before the `DataContext` changes. This is needed if the `DataContext` of the `DataGrid` changes to null which can occur when switching to another Tab from a `TabControl` ancestor as it prevents a clear of the items which would cause a binding target on the `SelectedIndex` to be set to -1.

## What is the current behavior?
If a `DataGrid` has a `ComboBox` in one of its cell and this `DataGrid` is inside a TabControl, it is possible to trigger an unwanted set to the `SelectedIndex` binding to -1 by switching to another tab. This happens because since this `ComboBox` never gets notified that its `DataContext` is about to change, it will not avoid clearing its items once the change actually happen since this `DataContext` becomes `null` in this context.

## What is the updated/expected behavior with this PR?
To have the `DataGrid` inform its cells that their `DataContext` is about to change and to also be informed when the change has completed.

## How was the solution implemented (if it's not obvious)?

I call the Notify event passing the cell's content for each cell. This is done because the cells aren't reachable from the `DataGrid`'s logical tree.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Fixed issues

Fixes #5661

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=8668) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=8668) before we can accept your contribution.<br/><br/>:x: aldelaro5 [sign now](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=8668)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/AvaloniaUI/Avalonia?pullRequest=8668) it.</sub>

**Comment by aldelaro5** [comment]
Not sure what the CI is doing: it was failing last time, I just rebased and it seems to work...somewhat?

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0022966-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by maxkatz6** [comment]
@aldelaro5 integration tests for mac are failing currently, because mac device is offline. That's fine for this PR, can be ignored.

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0023158-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
