### PR TITLE
Fixes TileBrush transform handling

### PR DESCRIPTION
**Pull request by Gillibald**
## Checklist

- [x] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/avalonia-docs with user documentation

### CODE REVIEW

**Comment by BAndysc** [comment]
I went to see if maybe this PR also fixes https://github.com/AvaloniaUI/Avalonia/issues/11959 (unfortunately doesn't look like)

But additionally, it renders incorrectly again: before the commit [More adjustments](https://github.com/AvaloniaUI/Avalonia/pull/15157/commits/6f70e7d9f40d7448519c51cde2ba658c95aa1ed8)

image

(might be related to my screen dpi?)

After the commit the grid is completely gone:

image

**Comment by Gillibald** [comment]
Looks like there is no test coverage here. Can you provide me the brush definition that isn't working?

**Comment by BAndysc** [comment]
```
<DrawingBrush TileMode="Tile"
              DestinationRect="0 0 15 15">
    <DrawingBrush.Drawing>
        <GeometryDrawing Geometry="M0,0 L0,1 0.03,1 0.03,0.03 1,0.03 1,0 Z"
                         Brush="Red" />
    </DrawingBrush.Drawing>
</DrawingBrush>
```

even with no transform attached. It is completely blank after the latest commit. But it might be due to my screen scaling (macbook retina x2 scaling).

**Comment by Gillibald** [comment]
The PR currently does not handle all Stretch modes that might cause this. Thanks for the sample.

**Review by maxkatz6 — APPROVED** [review]

**Pull request merged**
