### PR TITLE
Improve ToolTip show logic

### PR DESCRIPTION
**Pull request by jankrib**
## What does the pull request do?
With this PR the ToolTip will not show during a pointer press. If the ShowDelay is set to 500ms, but the user press the button after 400ms having the tooltip pop up during the press is not only a strange experience, but breaks the pointer capture at least on windows. A ShowDistanceLimit is also introduced to avoid the having the tooltip show up before the pointer comes to a rest. To have the tooltip show up while vigorously moving the mouse around doesn't feel right to me, atleast.

## What is the current behavior?
Simple timer based on ShowDelay.

## What is the updated/expected behavior with this PR?
Timer is stopped on pointer pressed and restarted on pointer released. Also the pointer position is captured on timer start and timer is reset if the pointer moves more than the new attached property ShowDistanceLimit.

## How was the solution implemented (if it's not obvious)?
Adjustments made to ToolTipService.

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0031848-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by jankrib** [comment]
I also changed it to ignore if the event is handled. Both the new and old logic did not play nice if an override handled events. For example if OnPointerExited had `e.Handled = true;`

**Comment by jmacato** [comment]
Closing this PR temporarily due to inactivity. Please ping me if this needs to be reopened.

**Comment by jankrib** [comment]
I still think it's a nice fix

**Pull request closed without merging**
