### PR TITLE
MacOS: Only bring windows to front if they're on the active space.

### PR DESCRIPTION
**Pull request by grokys**
## What does the pull request do?

As described in #9565, if one showed a child window then made the parent window fullscreen, clicking on the parent window caused a switch away from the fullscreen space to the main desktop.

Fix this by only bringing a child window to front if it's on the active desktop.

I'm not 100% happy with this solution, because I don't like the way that child window behavior is different when you show the child window in fullscreen vs transition to fullscreen afterwards. Ideally we'd be able to bring child windows to the fullscreen space when the parent window is made fullscreen, but that looks to me to be impossible in macOS without using private APIs. Still, this is much better now as it's now possible to at least interact with the fullscreen window.

## Fixed issues

Fixes #9565

### CODE REVIEW

**Comment by grokys** [comment]
Making this a draft for now as we need to await customer validation.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0026660-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0026734-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by grokys** [comment]
Customer gave this a 👍 so ready for review/merge.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0026797-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-nightly/nuget/v3/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0026896-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-nightly/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0026912-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-nightly/nuget/v3/index.json) [PRBUILDID]

**Comment by danwalmsley** [comment]
I beleive this has broken the integration test app, so integration tests are failing

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0027132-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-nightly/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0027146-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-nightly/nuget/v3/index.json) [PRBUILDID]

**Pull request merged**
