### PR TITLE
Fix SelectableTextBlock selection

### LINKED ISSUE #10817: Cannot Select Text in SelectableTextBlock
**Describe the bug**
I cannot select anything inside a `SelectableTextBlock` at all with latest nightly. It works fine if I only use normal strings, but not usable if I have `Run` or `LineBreak` inside it.

**To Reproduce**
```
	<SelectableTextBlock>
		<Run>Hello World!</Run>
		<LineBreak/>
		<Run>Hello World!</Run>
		<LineBreak/>
		<Run>Hello World!</Run>
		<LineBreak/>
		<Run>Hello World!</Run>
		<LineBreak/>
		<Run>Hello World!</Run>
		<LineBreak/>
		<Run>Hello World!</Run>
		<LineBreak/>
	</SelectableTextBlock>
```

**Expected behavior**
Can select the text inside `SelectableTextBlock`

**Desktop (please complete the following information):**

- OS: Windows
- Version 11

**Additional context**
[AvaloniaApplication.zip](https://github.com/AvaloniaUI/Avalonia/files/11086965/AvaloniaApplication.zip)

### PR DESCRIPTION
**Pull request by Gillibald**
## What does the pull request do?

DirectProperty to StyledProperty conversion broke the SelectableTextBlock selection. This PR makes sure it works again.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Fixed issues

Fixes: #10817

### CODE REVIEW

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0032420-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0032448-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0032558-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0032622-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Pull request merged**
