### PR TITLE
Fix DataContext not getting GC'd/Finalized. closes #12123

### LINKED ISSUE #12123: DataContext not getting GC'd/Finalized
### Discussed in https://github.com/AvaloniaUI/Avalonia/discussions/12109

<div type='discussions-op-text'>

<sup>Originally posted by **nic547** July  9, 2023</sup>
Using the Avalonia .NET Core template, updating to Avalonia11 and editing the mainWindow like following:
```
public partial class MainWindow : Window
{

    public MainWindow()
    {
        DataContext = new ViewModel();
        InitializeComponent();
    }

    private void Button_OnClick(object? sender, RoutedEventArgs e)
    {
        new MainWindow().Show();
    }

    private void Button_GC_Click(object? sender, RoutedEventArgs e)
    {
        GC.Collect();
    }
}

public class ViewModel
{
    ~ViewModel()
    {
        Debug.WriteLine("Finalized called");
    }

    private readonly byte[] someData = new byte[65536];

}
```

```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="AvaloniaApplication1.MainWindow"
        Title="AvaloniaApplication1">
    <StackPanel>
	    <Button Click="Button_OnClick">Open New Window</Button>
        <Button Click="Button_GC_Click">GC</Button>
	</StackPanel>  
</Window>

```

After opening and closing new windows, I cannot observe the "ViewModel" getting finalized. Additionally a Memory Snapshot (VS) will reveal as many Instances of the ViewModel as Windows were opened, despite only one being open.

Is there something I need to do to properly "clean up" a closed window?

(Full code: https://github.com/nic547/AvaloniaRepro)

Edit: Does work as expected in 11 preview 8, but not in 11 rc1.1 and 11
</div>

### PR DESCRIPTION
**Pull request by flexxxxer**
## What does the pull request do?
Now `Window.DataContext` getting GC'd/Finalized after window close and `GC.Collect` call.

## What is the current behavior?
`Window.DataContext` not getting GC'd/Finalized after window close and `GC.Collect` call.

## What is the updated/expected behavior with this PR?
`Window.DataContext` getting GC'd/Finalized after window close and `GC.Collect` call.

## How was the solution implemented (if it's not obvious)?
To `Avalonia.Controls.TopLevel.HandleClosed` method body was added `Avalonia.Controls.TopLevel.StopRendering` method call.

## Checklist

- [x] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Breaking changes
None.

## Obsoletions / Deprecations
None.

## Fixed issues
#12123

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0038306-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by timunie** [comment]
Can you check if it also fixes #8240?

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0038328-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by flexxxxer** [comment]
> Can you check if it also fixes #8240?

I will take a look

**Comment by flexxxxer** [comment]
> Can you check if it also fixes #8240?

No, when MS Windows Narrator is turn ON. I won't be making fix changes #8240 in this pull request

**Review by maxkatz6 — APPROVED** [review]
Thank you!

**Pull request merged**
