### PR TITLE
Fix IsRegisteredAsAnchorCandidate desync, mainly affecting recycled anchors

### PR DESCRIPTION
**Pull request by 0x0ade**
## What does the pull request do?

My understanding of Avalonia's under-the-hood workings is very basic. From what I understand, `ItemsRepeater` recycles cleared elements, and `ScrollContentPresenter` holds a list of anchor candidates for when changes occur. This PR attempts to fix some edge cases occurring between those two, where the list of candidates contains duplicate and even recycled elements.

## What is the current behavior?
In the .NET Core control catalog, go to the items repeater page. The second commit of this PR adds a few buttons required for the following steps, feel free to cherry-pick that onto master, or revert the first commit when testing.

- Press "Scroll to Random".
- Select a random element.
- Press "Scroll to Random" again.
- Press "Scroll to Select".
- Remove the selected item.
- Remove again, this time it will remove the item at the end of the list.
- Remove again.
- Remove again.
- ...

Under certain circumstances, the scroll offset can jump seemingly at random.

## What is the updated/expected behavior with this PR?
When following the same steps as above, the scroll offset should stay anchored. Removing items at the end of the list shouldn't scroll when the viewport is in the middle of the list.

## How was the solution implemented (if it's not obvious)?
It seems to me that `IsRegisteredAsAnchorCandidate` is already supposed to keep track of the registered state, but wasn't updated or checked in some places.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019543-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019608-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019746-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0020034-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0020053-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by 0x0ade** [comment]
Visual reference of the behavior - I forgot that uploading videos is now possible on GitHub 😅 

Before - note how the number at the top keeps changing:

https://user-images.githubusercontent.com/1200380/164204344-0c80102f-9da6-4d95-bc00-5b06f1b8f2ad.mp4

After - note how anchoring works properly and the number at the top stays consistent:

https://user-images.githubusercontent.com/1200380/164204350-fdb98e0f-140b-4129-b21e-dce064d34b51.mp4

**Review by grokys — APPROVED** [review]
I'm not really that familiar with how `ItemsRepeater` works either, given that it was ported from WinUI and is pretty complex, but these changes look totally reasonable 👍

**Pull request merged**
