### PR TITLE
DataGrid: Extracting error data from DataValidationException

### LINKED ISSUE #5221: DataGrid doesn't handle DataValidationException special way as other controls do
**Describe the bug**
The DataValidationException is raised from the property setter. TextBox displays error message from the exception, while DataGrid cell displays error message together with the full exception details (I think the exception.ToString() is diplayed).

**To Reproduce**
1. Clone repo https://github.com/antrv/samples/tree/master/Avalonia-Indexer-Validation-Issue and run the app
2. Delete all characters from the top text box and move focus outside of it. The red border and error icon are displayed. Move mouse cursor to the error icon. The error message will be displayed.
3. Do the same as in p.2 in the Name column of the data grid. The full exception details will be displayed.

**Expected behavior**
The behavior should be the same as of TextBox.

**Desktop (please complete the following information):**
 - OS: Windows 10 x64 20H2
 - Version 0.10.0-rc1

### PR DESCRIPTION
**Pull request by antrv**
## What does the pull request do?
This PR adding handling of DataValidationException in DataGrid the same way as DataValidationException is handled in other controls, i.e. TextBox.

## What is the current behavior?
DataGrid displays full exception details instead of error data from DataValidationException.

## How was the solution implemented (if it's not obvious)?
The ErrorData is extracted from DataValidationException.

## Breaking changes
None

## Fixed issues
Fixes #5221

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=5222) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=5222) before we can accept your contribution.<br/><br/>:x: antrv [sign now](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=5222)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/AvaloniaUI/Avalonia?pullRequest=5222) it.</sub>

**Review by maxkatz6 — APPROVED** [review]
Thank you.

**Comment by antrv** [comment]
Reimplemented without a public contract changes

**Comment by antrv** [comment]
Sorry for removed spaces. VS plugin does this automatically.

**Comment by Gillibald** [comment]
You need to revert those unintended changes to spaces etc. That can be easily done via a soft reset. Then revert all changes that are not needed. In the end force push the remaining changes.

**Pull request merged**
