### PR TITLE
InternalSelectionModel: Prevent unwanted source collection changes

### LINKED ISSUE #9438: ComboBox messes Items/SelectedItem values when DataContext Changes
**Describe the bug**
ComboBox binding seems to be a little bit buggy, or at least much different from what happens in WPF.

We have a case where a ComboBox **DataContext** is binded to a datagrid/listbox selected item.

When you bind the ComboBox **Items** and **SelectedItem** , when the **ComboBox** **DataContext** changes, Avalonia will set the **Items** and **SelectedItem** values to their defaults, and immediately sets those values back to their original ones.

This seems to be bug, and causes some weird side effects, on apps that have specific behavior on setters.

For ex, if when the property that is binded to the ComboBox.SelectedItem changes we have some cases where changing that property will also do some changes on other properties of the ViewModel, and this bug causes a lot of issues on those scenarios.

**To Reproduce**

1. Go to https://github.com/braca/avalonia-combobox-bug
2. Download the repro repository
3. The repro contains 2 projects, one in Avalonia another one in WPF
4. Run the Avalonia project
5. On the listbox/datagrid (the behavior is the same) select the item 2
6. In the debug console you will get
```
Changed Object (Id: 2) Property: SelectedEnumValue | OldValue: Value2 | NewValue:Value0
Changed Object (Id: 2) Property: SelectedEnumValue | OldValue: Value0 | NewValue:Value2
```
It's visible that Avalonia changed the value to the enum default value (Value0) and than later on restored the correct value (Value2)
7. Run the WPF Project
8. You will see that this behaviour does not occur in WPF

**Expected behavior**
Avalonia should not change the ComboBox SelectedItem/Items properties to their default value when DataContext changes

**Desktop (please complete the following information):**

- OS: Windows 11, macOS 13.0 (Ventura)
- Version 0.10.18

**Additional context**

### PR DESCRIPTION
**Pull request by aldelaro5**
## What does the pull request do?
I investigated #9438 thoroughly and I found that the underlying cause of the issue was that we were committing internal changes to the selection model such that they would be seen by the binding targets. This meant that simply setting the source collection of the selection model meant to push a change notification about the selected index. This happened multiple times on a BatchUpdate's Dispose because since these changes were seen as something the bindings would pay attention, they were pushed without regards to the fact they are supposed to be internal changes only.

In other words, the selection model was not yet ready to commit its changes to the bindings. This pr aims to address that.

## What is the current behavior?
If any `SelectingItemsControl`'s DataContext changes or that its selection source needs a reset for one reason or another, it will push its working changes to the target bindings which can be undesired.

## What is the updated/expected behavior with this PR?
To only push the change notifications that needs to be pushed. WPF behaves the same as demonstrated by the sample in the issue.

## How was the solution implemented (if it's not obvious)?
This pr through the use of `OnSourceCollectionChangeStarted` and `OnSourceCollectionChangeFinished` allows the internal updates to be deferred until they are completely done in the case the source changes. We still want to have the sync done if the selection itself changes, but this pr only applies if the source changes which can happen simply by changing the DataContext or other events like the repro mentioned in the issue.

To note, I am not that familiar with this area of the codebase because I had to dig this one pretty deep. I recommend @grokys to take a look as they have previously dealt with fixes similar to these. 

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Breaking changes
None.

## Obsoletions / Deprecations
None.

## Fixed issues
Fixes #9438 

I would like to mention: this does NOT seem to be the same issue than 10393 because after thoroughly investigating #9438, I couldn't come at the conclusion that the $parent notation had anything to do with it because this was about pushing updates when it shouldn't while the $parent thing seems to be about the specific bindings.

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0032616-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0032977-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by grokys** [comment]
@aldelaro5 sorry for the delay on this, I'm busy trying to get all breaking changes finished for 11.0 and this issue/PR is going to take some time to diagnose/review. I will get to it eventually ;)

**Review by grokys — APPROVED** [review]
Just taken a look and fixes the issue, what's more I've so far been unable to find anything else it breaks (which is quite something when it comes to selection! Every little change breaks something else simply due to the number of competing sources of selection).

I pushed a unit test for the issue in question to your branch.

Nice one! This part of the code is really hairy despite my best efforts.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0034776-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by trrahul** [comment]
Hi, I am on 11.0.0-rc1.1, and this issue is still there. I am binding a list of enum to a combo box and the selected item to another enum property. When the data context changes, the selected item value is set to the default value.

**Comment by trrahul** [comment]
Hi @timunie. I have opened a new issue here with a sample project. https://github.com/AvaloniaUI/Avalonia/issues/11784

**Pull request merged**
