### PR TITLE
Custom setters implement Equals/GetHashCode and have optimized code gen

### PR DESCRIPTION
**Pull request by MrJul**
## What does the pull request do?
This pull request updates the XamlX IL compiler to https://github.com/kekekeks/XamlX/pull/65 (please see that PR for full details).

It also implements `Equals`, `GetHashCode` and `IXamlILOptimizedEmitablePropertySetter` on custom property setters to take advantage of the XamlX changes and generate fewer IL instructions.

## What is the updated/expected behavior with this PR?
`Equals` and `GetHashCode` overrides allow the IL compiler to cache the generated dynamic setter methods when possible.
`IXamlILOptimizedEmitablePropertySetter` generates smaller IL code for static setters.
Everything should work the same as before, but with smaller assemblies emitted from XAML code.

Setters for `IBinding` and `UnsetValueType` now use `AllowRuntimeNull = false` to keep the same behavior as before (that setting wasn't respected before the XamlX PR: the generated code didn't allow null in practice).

## Tests
New unit tests have been added to XamlX.
Avalonia already has all the relevant tests needed, which should all pass.

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0022862-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by MrJul** [comment]
Rebased the PR onto master and implemented `IXamlILOptimizedEmitablePropertySetter` on the new `AdderSetter` class added by the lazy resources feature.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0022883-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by kekekeks — APPROVED** [review]

**Comment by danwalmsley** [comment]
@MrJul we are unable to merge this because for some reason your repo settings prevent us from updating your branch to master.

**Comment by MrJul** [comment]
@danwalmsley Sorry, "allow edit by maintainers" was unchecked, should be all good now!

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0023050-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
