### PR TITLE
Flyout sample label fix

### LINKED ISSUE #10543: ControlCatalog Flyout Sample mislabeling
The `Flyout Placements` section of `ControlCatalog` has the wrong `Content` for `RightEdgeAlignedTop` example. It repeats the `RightEdgeAlignedBottom`'s `Content` and just needs to say `Placement=RightEdgeAlignedTop` instead.

The file/line#:
https://github.com/AvaloniaUI/Avalonia/blob/105b999d5f46315e2d2a4960d3899c4d9845d4b8/samples/ControlCatalog/Pages/FlyoutsPage.axaml#L193

### PR DESCRIPTION
**Pull request by tkefauver**

### CODE REVIEW

**Comment by tkefauver** [comment]
@dotnet-policy-service agree

**Comment by tkefauver** [comment]
From https://github.com/AvaloniaUI/Avalonia/issues/10543#issue-1608684637

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0031417-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]

**Comment by maxkatz6** [comment]
Thanks!

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0031451-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by tkefauver** [comment]
@maxkatz6 No problem! Was really just guessing how to file the PR correctly, never done one before.... Everything was ok?

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0031512-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by maxkatz6** [comment]
@tkefauver changes are good. Only new CLA bot for some reason doesn't work well. Can you approve again maybe?

**Comment by tkefauver** [comment]
@dotnet-policy-service agree

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0031584-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Pull request merged**
