### PR TITLE
Utilizing TextLayout's LineHeight in TextBox and TextPresenter

### PR DESCRIPTION
**Pull request by macabrett**
## What does the pull request do?

This pull request gives users the ability to set the line height on text boxes, which was a feature already accounted for in TextLayout, but could not be passed in from a TextBox/TextPresenter.

Let me know if there was already a way to accomplish this, I just didn't see a path within the source.

## What is the current behavior?

LineHeight is always NaN.

## What is the updated/expected behavior with this PR?

Users can set LineHeight on a TextBox or TextPresenter, but it will default to double.NaN, which is the follow used previously.

## How was the solution implemented (if it's not obvious)?

Standard StyledProperty.

## Checklist

- [ ] Added unit tests (if possible)?
- [x] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Breaking changes

N/A

## Obsoletions / Deprecations

N/A

## Fixed issues

N/A

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=8139) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=8139) before we can accept your contribution.<br/><br/>:x: BrettStory [sign now](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=8139)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/AvaloniaUI/Avalonia?pullRequest=8139) it.</sub>

**Comment by BrettStory** [comment]
I'd be happy to write unit tests, but since I only altered view logic, I didn't find unit tests appropriate.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0020396-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0020398-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by Gillibald** [comment]
You can use AddOwner instead of redefining the property https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/TextBlock.cs#L79

**Comment by BrettStory** [comment]
> You can use AddOwner instead of redefining the property https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/TextBlock.cs#L79

Thanks for the suggestion! I've added a commit to the PR which uses AddOwner.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0020401-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by Gillibald** [comment]
TextBox should use TextBlock.LineHeightProperty.AddOwner

**Comment by BrettStory** [comment]
> TextBox should use TextBlock.LineHeightProperty.AddOwner

Changes applied! Thanks again. Somehow, I completely missed that TextBlock already had a LineHeight. Now all three should benefit from the same validation and default value.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0020412-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0020413-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by Gillibald — APPROVED** [review]

**Pull request merged**
