### PR TITLE
Implement GeometryBoundsHelper

### LINKED ISSUE #5381: Rotating an ArcSegment via Animation creates artefacts
**Describe the bug**
Rotating an ArcSegment via Animation creates artefacts.

**To Reproduce**
1. https://github.com/darinkes/AvaloniaUITests

**Expected behavior**
No artefacts

**Screenshots**
See https://www.youtube.com/watch?v=ijXDyM4Xlhg

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 0.10.0

**Additional context**
Only happens while executing the Application. Preview in Visual Studio looks fine.
Setting an Background to the hosting Control works around this problem.

### PR DESCRIPTION
**Pull request by timunie**
## What does the pull request do?
If a path geometry has LineCaps other than Flat defined, one may get render artifacts. In order to fix this we need to inflate the dirty rects to cover the LineCaps. 

## What is the current behavior?
You get articats, See #5381 

## What is the updated/expected behavior with this PR?
No artifacts 

## How was the solution implemented (if it's not obvious)?
Implemented a helper class which calculates the needed bound offset

## Checklist

- [ ] Added unit tests (if possible)? 
- [X] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation ► Not needed as this is an internal class

## Fixed issues
Fixes #5381

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019148-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019148-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by jmacato — APPROVED** [review]
changes are no-brainer, yolo merging this

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019223-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019227-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by timunie** [comment]
> changes are no-brainer, yolo merging this

For me this was hard to figure out: 😆

**Comment by jmacato** [comment]
@timunie sorry i meant it was really good hahaha, i just meant nobrainer == should be merged immediately 😆

**Pull request merged**
