### PR TITLE
Make RequestPlatformInhibition public.

### PR DESCRIPTION
**Pull request by Stannieman**
This was implemented previously, but having it protected is annoying. Public is more convenient.

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0030283-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]

**Comment by robloo** [comment]
I dont think we follow the rule of public members first really anywhere. So moving the method like this makes such a simple change larger than if needs to be in the commit history and for review. I would not move the method, just make the existing one public.

**Comment by maxkatz6** [comment]
Yes, we don't really follow ordering, especially in files like this which were modified hundreds of times. So, it wouldn't be a big deal.
But this file specifically happens to be actually ordered in case of public methods, except of InvalidateMirrorTransform one. Even though is mixed with explicit interface implementations.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0030323-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Pull request merged**
