### PR TITLE
Expander Updates

### LINKED ISSUE #9234: Align Expander Fluent ControlTheme with WinUI
**Is your feature request related to a problem? Please describe.**

Over a year ago I updated the WinUI expander default style to fix several issues. I think these should be back-ported to Avalonia before the 11.0 release.
 
* https://github.com/microsoft/microsoft-ui-xaml/pull/4394
* Source: https://github.com/microsoft/microsoft-ui-xaml/blob/main/dev/Expander/Expander.xaml and https://github.com/microsoft/microsoft-ui-xaml/blob/main/dev/Expander/Expander_themeresources.xaml

**Describe the solution you'd like**

Align the Fluent ControlTheme for Expander in Avalonia with WinUI.

**Additional context**

I'll take care of this one.

### PR DESCRIPTION
**Pull request by robloo**
## What does the pull request do?

 * Updates the Fluent theme Expander to more closely follow WinUI
 * This is primarily to:
    1. Switch the Expander properties like Padding to apply to the content area instead of the header area. This was heavily discussed in the WinUI repo and consensus was properties should apply to "Content".
    2. Pull in all the new (standardized) resource names. Terms like "Content" and "Dropdown" were previously mixed
 * Fully support disabled state
 * Change the dropdown/chevron background like Fluent v2 to indicate the expander can be pressed
 * Implement many more resources and pseudoclasses to control the header

## What is the current behavior?

The control is functional but has poor resource naming and unintuitive usage with main properties applying to the header instead of content area.

## What is the updated/expected behavior with this PR?

**Before**

Before

**After**

After

(WinUI Fluent v2 (Windows 11) Default Style for Reference)

WinUI2

## How was the solution implemented (if it's not obvious)?

 1. Imported the latest WinUI default styles
 2. Converted the resource to use Fluent v1 base resources instead of Fluent v2 (WinUI never had a Fluent v1 style of this control)
 4. Further fix resource names
 5. Adapt the control for Avalonia (template architecture changes and remove of visual state manager, etc.)

## Checklist

- ~[ ] Added unit tests (if possible)?~
- ~[ ] Added XML documentation to any related classes?~
- ~[ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation~

## Breaking changes

Yes to anyone who customizes this control and uses the Fluent theme. Properties are used differently (like Padding/Background, etc.) and the resource keys are changed.

## Obsoletions / Deprecations

None

## Fixed issues

Closes #9234

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0025269-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by timunie** [comment]
@robloo I opened a discussion here: https://github.com/AvaloniaUI/Avalonia/discussions/9273 

I think we should at least consider if new Properites for the header-part are worth the costs.

**Comment by maxkatz6** [comment]
> Switch the Expander properties like Padding to apply to the content area instead of the header area. This was heavily discussed in the WinUI repo and consensus was properties should apply to "Content".

I agree on this change. I wonder if something like `Expander.HeaderTheme` would be helpful. As a flexible alternative for the `Header***` properties.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0025407-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]

**Pull request merged**
