### PR TITLE
Modified slider style to look like other controls

### PR DESCRIPTION
**Pull request by wieslawsoltes**
Before:

before

After:

after

### CODE REVIEW

**Comment by grokys** [comment]
I know where you're coming from with this, but I liked the look before. I know it wasn't consistent with the rest of the default theme, but then a lot of our controls aren't currently consistent. @herasimchuk-aa what do you think?

**Comment by wieslawsoltes** [comment]
Well I would prefer to use the default theme, anyway no pressure, I have already copied template from default theme and modified for my use.

**Comment by herasimchuk-aa** [comment]
It is so important for me. I didn't find any style guides, so I just used a style from my another project because it looked a pretty fine.

**Comment by herasimchuk-aa** [comment]
I meant it is NOT so important. I have to recheck commetns before sending)

**Comment by grokys** [comment]
Ok, lets merge this.

**Pull request merged**
