### PR TITLE
Adds new HslColor struct and Support for CSS Color Formats

### LINKED ISSUE #7899: Enhanced Color Format Support in XAML/Styles based on CSS
**Is your feature request related to a problem? Please describe.**

The framework works in the RGB color model for good reasons. However, there are cases where other color models should be supported for designers and control authors. In additional HTML/CSS supports alternative formats.

**Describe the solution you'd like**

Add support for all [HTML/CSS color formats](https://www.w3schools.com/cssref/css_colors_legal.asp) and include a new one for HSV.

Examples:
 * `"Green"` (already supported)
 * `"#ff0000"` (already supported)
 * `"rgb(255, 0, 0)"` new for Avalonia based on CSS
 * `"rgba(0, 255, 0, 0.3)"` new for Avalonia based on CSS
 * `"hsl(120, 100%, 75%)"` new for Avalonia based on CSS
    * `"hsl(120, 1.0, 0.75)"` new for Avalonia (not in CSS)
 * `"hsla(120, 100%, 75%, 0.3)"` new for Avalonia based on CSS
    * `"hsla(120, 1.0, 0.75, 0.3)"` new for Avalonia (not in CSS)
 * `"hsv(300, 100%, 20%)"` new for Avalonia (not in CSS)
    * `"hsv(300, 1.0, 0.2)"` new for Avalonia (not in CSS)
 * `"hsva(300, 90%, 20%, 0.8)"` new for Avalonia (not in CSS)
    * `"hsva(300, 0.9, 0.2, 0.8)"` new for Avalonia (not in CSS)

Note that alpha can also be specified as a percentage by adding a percent sign. This is an extension of the format that CSS does not have.

Advantages:
 * Three color models could be supported HSV, HSL and RGB (existing)
 * Full compatibility with HTML/CSS color format strings
 * No need for designers or developers to convert always into hex ("#FFFFFF") or named ("White") formats.
 * Makes Avalonia the best XAML framework to use when working with colors!

This would be supported in the XAML parser by modifying the `Color.Parse()` methods to handle all formats including those for HSV/HSL. It's convenient that `Color` is named simply `Color` instead of `RgbColor` as this modification still makes sense in the API naming!

Other color models will be automatically converted to RGB after parsing. Code for parsing and conversion other color models to RGB would not be within the Color struct itself and would instead exist in `HsvColor` and potentially `HslColor`.

**Describe alternatives you've considered**

Alternative is to keep using simple RGB color formats.

**Additional context**

 * https://www.w3schools.com/cssref/css_colors_legal.asp
 * In the future the parser may be extended to forgo commas and allow only spaces between the components `"rgb(255 0 30)"`

### PR DESCRIPTION
**Pull request by robloo**
## What does the pull request do?

Adds a new `HslColor` struct alongside `HsvColor` and `Color` and supports all CSS color formats discussed in #7899 

## What is the current behavior?

 * Currently HslColor doesn't exist
 * Color formats in XAML only support named "Black" or hex "#ff0000" formats.

## What is the updated/expected behavior with this PR?

Add support for all [HTML/CSS color formats](https://www.w3schools.com/cssref/css_colors_legal.asp) and include a new one for HSV.

Examples:
 * `"Green"` (already supported)
 * `"#ff0000"` (already supported)
 * `"rgb(255, 0, 0)"` new for Avalonia based on CSS
 * `"rgba(0, 255, 0, 0.3)"` new for Avalonia based on CSS
 * `"hsl(120, 100%, 75%)"` new for Avalonia based on CSS
    * `"hsl(120, 1.0, 0.75)"` new for Avalonia (not in CSS)
 * `"hsla(120, 100%, 75%, 0.3)"` new for Avalonia based on CSS
    * `"hsla(120, 1.0, 0.75, 0.3)"` new for Avalonia (not in CSS)
 * `"hsv(300, 100%, 20%)"` new for Avalonia (not in CSS)
    * `"hsv(300, 1.0, 0.2)"` new for Avalonia (not in CSS)
 * `"hsva(300, 90%, 20%, 0.8)"` new for Avalonia (not in CSS)
    * `"hsva(300, 0.9, 0.2, 0.8)"` new for Avalonia (not in CSS)

Note that alpha can also be specified as a percentage by adding a percent sign. This is an extension of the format that CSS does not have.

## How was the solution implemented (if it's not obvious)?

 * Originally, HsvColor has FromRgb/ToRgb methods. However, this API design does not allow expanding to additional color models easily. Therefore, the convention is established that each color type ONLY has .ToModel() conversions. This means conversions are in only one direction per type. It makes the code easier to understand and extend in the future.
 * Rounding is used when going from HsvColor or HslColor to Color (RGB). HsvColor/HslColor have much higher precisions than Color. This also better aligns with other conversion libraries based on comparison testing.
   * Rounding is not needed going from Color -> HsvColor/HslColor.
   * It is only needed going HsvColor/HslColor -> Color due to the underlying precisions in the component types.
 * Unit tests were added for all format parsing
 * I decided to keep HslColor public. It turned out almost the same as HsvColor and has full functionality. So in the case some app actually needs this there is no reason to hide it. It is ready for public use.

## Checklist

- [x] Added unit tests (if possible)?
- [x] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Breaking changes

None

## Obsoletions / Deprecations

None

## Fixed issues

Closes #7899

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019761-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019776-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by robloo** [comment]
@jmacato This is finished and ready for review. It should support all the formats you wanted as discussed in other PR.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019778-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by robloo** [comment]
FYI, the build and checks are actually successful. I merged in master almost immediately after kicking off the build checks. It then cancelled the 2nd checks and show them as failure while the commit before completed and shows pass.

I think running checks should be cancelled when a new commit comes in and then restarted for the new commit. Seems a bit backwards right now.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019794-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by jmacato — APPROVED** [review]
This is cool.. also TIL about HSL/HSV and i believe they will be useful for fluent style stuff as well.

**Pull request merged**
