### PR TITLE
Added AppBuilder methods for logging.

### PR DESCRIPTION
**Pull request by grokys**
You can now set up serilog logging to `Debug` or `Trace` by calling e.g.:

```
AppBuilder.Configure<App()
    .LogToDebug()
    .UsePlatformDetect();
```

The methods accept an optional `level` parameter to control the minimum log level.

### CODE REVIEW

**Review by jkoritzinsky — CHANGES_REQUESTED** [review]
You need to update our build script so it knows our packages have dependencies on the serilog sink packages.

**Comment by grokys** [comment]
@jkoritzinsky is that right now?

**Comment by jkoritzinsky** [comment]
You need to create a version variable like the other packages and use that. Then the build script will version automatically with the project.

**Comment by grokys** [comment]
Ok, done that (I think) - hope it's right, I've not been much involved in the build scripts; I was wondering whether a version variable was required but not all packages seem to use it.

**Review by jkoritzinsky — APPROVED** [review]
LGTM

**Pull request merged**
