### PR TITLE
[WIP][** do not merge **] Playground/clipboard bitmap support

### PR DESCRIPTION
**Pull request by timunie**
## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Fixed issues

--------

**PLEASE NOTE**

This is just a playground to estimate how clipboard support for images work. 

A basic sample can be found in the Sandbox App

Once I found a valid solution this PR will be closed and a new one will be opened. 

If anyone knows how to do the stuff I would be happy about your input. 

Happy coding 
Tim

### CODE REVIEW

**Comment by kekekeks** [comment]
Note that bitmap clipboard support is mostly blocked by our inability to deal with more than 64K of clipboard data on X11 which needs to be fixed first

**Comment by timunie** [comment]
> Note that bitmap clipboard support is mostly blocked by our inability to deal with more than 64K of clipboard data on X11 which needs to be fixed first

Thank you @kekekeks for this info. At the moment I only need Windows Clipboard support, but I understand that this should not be implemented if X11 does not work. Can I keep this PR for testing purpose? 

Do you already have a branch for this? If yes, could you link it here? 

/cc @drwenzel @danwalmsley 

Happy coding 
Tim

**Comment by timunie** [comment]
Also related:

#6501 #3588

**Comment by Whiletru3** [comment]
Hello Any plan for this PR ? I need this on macos :)

thanks

**Comment by timunie** [comment]
> Hello Any plan for this PR ? I need this on macos :)
> 
> thanks

not from my side as said, we need to implement another feature first. I hope this can be done after 11.0 release but I can't promise.

**Comment by maxkatz6** [comment]
Closing for now, as it's blocked by the linux backend implementation.

**Pull request closed without merging**
