### PR TITLE
Add Avalonia AutoSuspendHelper

### PR DESCRIPTION
**Pull request by worldbeater**
## What does the pull request do?

Adds an implementation of `AutoSuspendHelper` for Avalonia. This class is required to fascilate the use of [ReactiveUI Suspension feature](https://reactiveui.net/docs/handbook/data-persistence/). For more illustrative examples see [ReactiveUI.Samples.Suspension project](https://github.com/worldbeater/ReactiveUI.Samples.Suspension).

## What is the current behavior?

There is no `AutoSuspendHelper` in `Avalonia.ReactiveUI` package.

## What is the updated/expected behavior with this PR?

There is `AutoSuspendHelper` in `Avalonia.ReactiveUI` package.

## How was the solution implemented (if it's not obvious)?

Heavily based on implementations for [Universal Windows](https://github.com/reactiveui/ReactiveUI/blob/196433808c46cf8404502350664d70ccd7e4ebec/src/ReactiveUI/Platforms/uap/AutoSuspendHelper.cs) and for [Windows Presentation Foundation](https://github.com/reactiveui/ReactiveUI/blob/eb53eee4bd1865b3a226ec468c0a344620349bee/src/ReactiveUI.Wpf/AutoSuspendHelper.cs). 

## Checklist

- [x] Added unit tests
- [x] Added XML documentation to any related classes
- [x] Updated to use the [new lifecycle events](https://github.com/AvaloniaUI/Avalonia/pull/2676)

### CODE REVIEW

**Comment by worldbeater** [comment]
Planning to port `AutoSuspendHelper` to use the new lifecycle events after https://github.com/AvaloniaUI/Avalonia/pull/2676 is shipped.

**Comment by grokys** [comment]
@worldbeater #2676 is now merged. Do you want to do the work to integrate that on this PR?

**Comment by worldbeater** [comment]
@grokys sure. Going to finish this one up in around 3-4 days due to the lack of free time these days 😰

**Comment by worldbeater** [comment]
Rewrote the `AutoSuspendHelper`, but stuck with adding tests for it. Don't know what to do in unit tests to prevent the `UnitTestApplication.ApplicationLifetime` property from being null. Probably should wait for an event for appear, but have no idea which one. The `ApplicationLifetime` feature [is not covered with any single test at the moment](https://github.com/AvaloniaUI/Avalonia/search?q=ApplicationLifetime&unscoped_q=ApplicationLifetime).

**Review by grokys — APPROVED** [review]

**Pull request merged**
