### PR TITLE
Add RadiusX,RadiusY and Center in EllipseGeometry

### PR DESCRIPTION
**Pull request by jmacato**
## What does the pull request do?

These Properties are missing in the current impl of EllipseGeometry, i added them for more WPF compat and easier way of defining circles.

cc @grokys @danwalmsley

### CODE REVIEW

**Comment by jmacato** [comment]
@donandren hope you can take a look this too

**Review by danwalmsley — COMMENTED** [review]
LGTM

**Review by donandren — APPROVED** [review]
LGTM

**Review by danwalmsley — APPROVED** [review]
LGTM

**Pull request merged**
