### PR TITLE
[Round 2] Improved: D3D11 Adapter Creation Speed by Manually Selecting Hardware Type

### PR DESCRIPTION
**Pull request by Sewer56**
This is a resubmission of
- https://github.com/AvaloniaUI/Avalonia/pull/16035

As per comment in 
- https://github.com/AvaloniaUI/Avalonia/pull/16035#issuecomment-2178108248

With additional feedback addressed.
For more details, see the original PR.

### CODE REVIEW

**Comment by Sewer56** [comment]
Reminder to ensure that

- https://github.com/AvaloniaUI/Avalonia/issues/16062

Can no longer be reproduced by @maxkatz6 after checking out this PR.

**Comment by Sewer56** [comment]
Is there anything else that I need to do for this PR?
It's been sitting stale for a month, and it's relatively simple, so I'm not really sure per-se.

**Comment by maxkatz6** [comment]
@Sewer56 thank you for reminding.
With this PR it doesn't crash on my machine anymore, and instead fallback works properly.

But still, `D3D11CreateDevice(D3D_DRIVER_TYPE_HARDWARE)` returns E_INVALIDARG for me. I am pretty sure my machine with nvidia gpu should be in covered ~99% of use cases.
Do you have any hints how can I debug that to get more information about error?

**Comment by maxkatz6** [comment]
@Sewer56 ok, enabled debug flag and used Visual Studio with native code debugging enabled (Rider didn't show any extra info for some reason).

Now I have this output in the logs:
```
DX ERROR: D3D11CreateDevice: When creating a device from an existing adapter (i.e. pAdapter is non-NULL), DriverType must be D3D_DRIVER_TYPE_UNKNOWN. [ INITIALIZATION ERROR #3146142: ]
```

**Comment by maxkatz6** [comment]
If it's a good idea to rely on default adapter, we can skip creating IDXGIFactory1 and IDXGIAdapter1, unless we have Arm64 (older Adreno GPU didn't work well with avalonia).

**Comment by maxkatz6** [comment]
FYI @kekekeks

**Comment by kekekeks** [comment]
I think the idea was to add adapter selection callback or options to Win32PlatformOptions. IIRC it was requested to make sure that chosen adapter matches pre-existing VkDevice for interop purposes.

**Comment by maxkatz6** [comment]
Closing due to inactivity

**Comment by Sewer56** [comment]
I'm not inactive with regards to the thread.
I just wasn't sure what the further plan of action should be myself.

**Comment by Sewer56** [comment]
For instance; is the request to amend the code to rely on the default adapter?
I'm sure if the steps needed to proceed are/were reliant on myself or @kekekeks from the context here.

**Pull request closed without merging**
