### PR TITLE
try fix #13891

### LINKED ISSUE #13891: `TextBlock.Inlines.Clear()` no work
## Describe the bug
Call `TextBlock.Inlines.Clear()` is can't remove all `Inlines` element, then the text still display.

## To Reproduce

```
TextBlock.Inlines.Add(new Run("123"));

//Render ..

TextBlock.Inlines.Clear()

```

## Expected behavior
Before `TextBlock.Inlines.Clear()`, text not display.

## Screenshots
image
This should not display, because it has already been deleted
image

Expected 
image

## Environment 

- OS: Windows
- Avalonia-Version: 11.0.6

## Additional context

[AvaloniaApplication1.zip](https://github.com/AvaloniaUI/Avalonia/files/13627232/AvaloniaApplication1.zip)

### PR DESCRIPTION
**Pull request by Coloryr**
## What does the pull request do?
fix #13891 

## What is the current behavior?
Make `_textRuns` empty if necessary 

## Checklist

- [x] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/avalonia-docs with user documentation

## Fixed issues
Fixes #13891

### CODE REVIEW

**Comment by Coloryr** [comment]
any info?

**Comment by timunie** [comment]
@Coloryr please give us some time to review.

**Comment by Coloryr** [comment]
ok

**Comment by WillisXue** [comment]
SelectableTextBlock has same issue

**Comment by Gillibald** [comment]
I hope you don't bind but I have created a new PR with a different fix

**Comment by Coloryr** [comment]
Fix it is ok!

**Pull request closed without merging**
