### PR TITLE
Patch MSBuild tasks assembly during packaging

### PR DESCRIPTION
**Pull request by kekekeks**
Should fix various build-related issues

### CODE REVIEW

**Comment by grokys** [comment]
Not sure what I'm looking at here. What does it do?

**Comment by kekekeks** [comment]
1) Removed ILRepack task from the project itself and moved it to the Nuke script (you were complaining that ILRepack is causing the whole solution to be rebuilt)
2) Added Avalonia.Build.Tasks.dll assembly name randomization so MSBuild won't complain about "assembly with the same name is already loaded".

Need to check that PR nuget outputs with some actual projects before merging

**Comment by jkoritzinsky** [comment]
You should be able to fix item 1 by adding `Inputs` and `Outputs` fields to the target instead of moving the ILRepack task invocation to Nuke.

**Comment by kekekeks** [comment]
1) ILRepack isn't really needed within solution and takes valuable build time
2) We still need to randomize the name

So I'd still like to patch stuff during the packaging.

**Pull request merged**
