### PR TITLE
Switch TreeViewItem.IsExpanded to a StyledProperty

### PR DESCRIPTION
**Pull request by robloo**
## What does the pull request do?

Switches the TreeViewItem.IsExpanded property to a StyledProperty. This follows the Expander control changes.

## What is the current behavior?

IsExpanded is a DirectProperty and cannot be styled (see discussion https://github.com/AvaloniaUI/Avalonia/discussions/9719) cc @cristinathoughtpennies 

## What is the updated/expected behavior with this PR?

IsExpanded is now a full StyledProperty and usable in the styling system.

## How was the solution implemented (if it's not obvious)?

See code.

## Checklist

- ~[ ] Added unit tests (if possible)?~
- ~[ ] Added XML documentation to any related classes?~
- ~[ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation~

## Breaking changes

Yes, StyledProperty instead of DirectProperty but functionality is largely only expanded for app developers.

## Obsoletions / Deprecations

None

## Fixed issues

Part of #9944

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0029297-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0029331-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0029355-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0029363-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Review by TomEdwardsEnscape — COMMENTED** [review]
Things are a bit broken here because the control calls `SetValue` (via `IsExpanded`) in several places. This sets a value with local priority, which overrides any value that was applied by a style/template/etc.

This cannot be fixed until #9985 is complete.

**Comment by robloo** [comment]
Good point, I'll update after that PR is merged.

**Pull request merged**
