### PR TITLE
fixes(DeferredRenderer):  Avoid NullReferenceException

### LINKED ISSUE #6103: [DeferredRenderer] NullReferenceException
**Describe the bug**
During using RedererDemo project throw NullReferenceException

**To Reproduce**

I don't know the exact sequence it took place in different contexts.

**Expected behavior**
do not throw NullReferenceException

**Screenshots**
Screenshot (78)

Screenshot (79)

**Desktop (please complete the following information):**

- OS:  Windows 10 20H2
- Version: 7304643fec3fb8f7173d3f20f3c79410c78d1ba1

**Additional context**

### PR DESCRIPTION
**Pull request by workgroupengineering**
## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Fixed issues

fixes #6103

### CODE REVIEW

**Comment by danwalmsley** [comment]
do you have a repro for this?

**Comment by MarchingCube** [comment]
We should probably check why this actually happens since it looks like we dispose a drawing operation too early. While it won't crash after your change it probably won't render something.

**Comment by workgroupengineering** [comment]
> 
> 
> do you have a repro for this?

The exception is throw during test the Render Demo in this repository. I have not made any changes to the code. I noticed that most of the time this happened to me when a menu was displayed and I resized the main window.

> We should probably check why this actually happens since it looks like we dispose a drawing operation too early. While it won't crash after your change it probably won't render something.

I don't see any render glitch, I think depend of contextmenu or menu is closing but render operation is not dequeue.

**Comment by Gillibald** [comment]
Y this is hiding something. The DrawingOperation should not be null.

**Pull request closed without merging**
