### PR TITLE
TextBox Ignore Changes While Editing 

### LINKED ISSUE #3603: Bindings to Text property in TextBox doesnt work
I don't know why binding to Text doesnt work in TextBox
https://github.com/pelmenstar1/test-projects/blob/master/AvaloniaBindingTest/ViewModels/MainWindowViewModel.cs

```
public class MainWindowViewModel : ViewModelBase
    {
        private string _str = "#0000";
        public string String
        {
            get => _str;
            set
            {
                if (value!= null && value.Length > 0 && value[0] == '#' && value.Length <= 5)
                {
                    _str = value;
                }

                this.RaisePropertyChanged(nameof(String));
            }
        }
    }

```

```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:vm="clr-namespace:AvaloniaBindingTest.ViewModels;assembly=AvaloniaBindingTest"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="AvaloniaBindingTest.Views.MainWindow"
        Icon="/Assets/avalonia-logo.ico"
        Title="AvaloniaBindingTest">

    <Design.DataContext>
        <vm:MainWindowViewModel/>
    </Design.DataContext>

    <TextBox Text="{Binding String, Mode=TwoWay}" HorizontalAlignment="Center" VerticalAlignment="Center"/>

</Window>
```

bandicam-2020-02-22-12-52-12-586

### LINKED ISSUE #8317: TextBox ignores any changes while the user is inputting text
**Describe the bug**
Avalonia TextBox contains a field callled `_ignoreTextChanges` which stops the Textbox from reacting to changes while the user inputs text, I understand that it might be beneficial in some case but in others it causes a lot of unexpected behavior (especially when migrating from WPF because WPF does not has this behavior by default), implementing a property on the text box that disable the `_ignoreTextChanges`  will be really useful

### PR DESCRIPTION
**Pull request by ahmedmohammedfawzy**
## What does the pull request do?
 Removed the `_ignoreTextChanges` from the Text Box

## What is the updated/expected behavior with this PR?
The text box will now react to any changes to Text property even when the user is inputting text

## Fixed issues
Fixes #8317 
Fixes #3603

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=8318) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=8318) before we can accept your contribution.<br/><br/>:x: ahmedmohammedfawzy [sign now](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=8318)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/AvaloniaUI/Avalonia?pullRequest=8318) it.</sub>

**Comment by robloo** [comment]
Not sure about this myself. However please make sure to document properties-- especially ones like this that don't exist in other frameworks!

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0021138-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0021140-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by ahmedmohammedfawzy** [comment]
> Not sure about this myself. However please make sure to document properties-- especially ones like this that don't exist in other frameworks!

How should I document it?

**Comment by danwalmsley** [comment]
Use comments, /// in visual studio, describe what the property does etc

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0021155-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by grokys** [comment]
To be honest, I don't remember why I added the `_ignoreTextChanges` field back in 2016, and looking at #3603 it sounds like WPF doesn't act like this anyway.

I'd probably be happier to just remove this behavior altogether at this point.

**Comment by ahmedmohammedfawzy** [comment]
> To be honest, I don't remember why I added the `_ignoreTextChanges` field back in 2016, and looking at #3603 it sounds like WPF doesn't act like this anyway.
> 
> I'd probably be happier to just remove this behavior altogether at this point.

So Shall I make a new pull request and remove the property

**Comment by ahmedmohammedfawzy** [comment]
> > To be honest, I don't remember why I added the `_ignoreTextChanges` field back in 2016, and looking at #3603 it sounds like WPF doesn't act like this anyway.
> > I'd probably be happier to just remove this behavior altogether at this point.
> 
> So Shall I make a new pull request and remove the field?

**Comment by robloo** [comment]
If it was me, I would just modify this PR. You can also change the title if that's required (Probably not). It's good to keep all the discussion and decision making together here.

**Comment by ahmedmohammedfawzy** [comment]
After removing the `_ignoreTextChanges` from the Text box these tests are failing: `Avalonia.Controls.UnitTests.TextBoxTests.Typing_Beginning_With_0_Should_Not_Modify_Text_When_Bound_To_Int ` 
`Avalonia.Controls.UnitTests.MaskedTextBoxTests.Typing_Beginning_With_0_Should_Not_Modify_Text_When_Bound_To_Int`
they seem to be checking for the text box ignoring the change while user is inputting text, the commit says :

>  If a TextBox is e.g. bound to an int and the user types "02" then the TextBox text should be "02" - not the value that comes back from the binding which will be "2"

So I am not sure about this should the text be removed or shall I return to my previous solution with the custom property?

**Comment by robloo** [comment]
It's good there were unit tests. That explains what this all is for. @grokys Will need to confirm but my guess is we go back to what you had originally.

**Comment by Gillibald** [comment]
The test itself is wrong. When the TexProperty is bound to an int this is expected. It is safe to remove that test.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0021172-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0021180-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0021186-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0021246-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by grokys — APPROVED** [review]
LGTM, thanks @ahmedmohammedfawzy !

**Comment by danwalmsley** [comment]
@ahmedmohammedfawzy if you need this in 0.10.x stable release please open another PR targeting `stable/0.10.x` there are conflicts there so wouldnt want to backport and break something.

**Pull request merged**
