### PR TITLE
Impl auto safe area padding

### LINKED ISSUE #12969: Safe area insets background colour is wrong (on iOS)
**Describe the bug**
Insets on iOS result in background colours not filling the screen. 

**To Reproduce**

1. Create an iOS application
2. Set the background colour to anything 
3. Run the app
4. Look at the insets being either black or white (depending on the current OS theme). 

**Expected behavior**
The background colour should fill the entire view. I've included a screenshot of a native iOS app in Xcode with the background colour set. You can see how it fills the entire view. 

**Screenshots**
CleanShot 2023-09-21 at 09 47 03@2x

CleanShot 2023-09-21 at 09 46 15@2x

### PR DESCRIPTION
**Pull request by maxkatz6**
## What does the pull request do?

Adds a new `TopLevel.AutoSafeAreaPadding` property settable on the top-level content (MainView) or top-level itself.
When enabled, it automatically adds safe area paddings. 

Normally, to see any effect, it also requires InsetsManager.DisplayEdgeToEdge to be enabled as well, so application content can be rendered behind the status bar. 
It is enabled automatically on iOS though, and we need to add safe paddings automatically. Making overall Avalonia iOS experience better out of the box.

It's a behavioral change on mobile, since TopLevel.AutoSafeAreaPadding is enabled by default now. If not needed, TopLevel.AutoSafeAreaPadding can be disabled on the main view.

Also, this PR changes iOS InsetsManager.SafeAreaPadding behavior to match Android behavior, when SafeAreaPadding returns empty paddings, when DisplayEdgeToEdge is disabled.

## Fixed issues

Fixes https://github.com/AvaloniaUI/Avalonia/issues/12969

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0040066-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Review by jmacato — APPROVED** [review]
LGTM

**Comment by kerams** [comment]
I don't see the property. Has this been removed in a recent version of Avalonia? On iPhone SE 2nd gen I get no automatic padding and my navbar is rendered across the system status bar:

Screenshot 2024-10-24 at 13 32 03

**Comment by emmauss** [comment]
> Has this been removed in a recent version of Avalonia? On iPhone SE 2nd gen I get no automatic padding and my navbar is rendered across the system status bar:
> 
> Screenshot 2024-10-24 at 13 32 03
> 
> Similarly in iPhone 15 Pro emulator:
> 
> Untitled

@maxkatz6

**Comment by maxkatz6** [comment]
@kerams can you open an issue with minimal repro? I can take a look over weekend

**Pull request merged**
