### PR TITLE
Fix issue 4427 - System.InvalidOperationException: Default font family name can't be null or empty

### LINKED ISSUE #4427: System.InvalidOperationException: Default font family name can't be null or empty
Version: 0.10-preview2

I upgraded project IPOCS.JMRI.CONTROL, located at https://github.com/GMJS/ipocs.jmri, to preview2 (not committed and pushed yet) and made a build for `linux-arm` using `dotnet publish IPOCS.JMRI.CONTROL -c Release -r linux-arm`. Upon trying to run this on a raspberry pi I'm getting the exception:

```
Unhandled exception. System.InvalidOperationException: Default font family name can't be null or empty.
   at Avalonia.Media.FontManager..ctor(IFontManagerImpl platformImpl)
   at Avalonia.Media.FontManager.get_Current()
   at Avalonia.Rendering.RendererBase..ctor(Boolean useManualFpsCounting)
   at Avalonia.Rendering.DeferredRenderer..ctor(IRenderRoot root, IRenderLoop renderLoop, ISceneBuilder sceneBuilder, IDispatcher dispatcher, IDeferredRendererLock rendererLock)
   at Avalonia.X11.X11Window.CreateRenderer(IRenderRoot root)
   at Avalonia.Controls.TopLevel..ctor(ITopLevelImpl impl, IAvaloniaDependencyResolver dependencyResolver)
   at Avalonia.Controls.WindowBase..ctor(IWindowBaseImpl impl, IAvaloniaDependencyResolver dependencyResolver)
   at Avalonia.Controls.WindowBase..ctor(IWindowBaseImpl impl)
   at Avalonia.Controls.Window..ctor(IWindowImpl impl)
   at Avalonia.Controls.Window..ctor()
   at IPOCS.JMRI.CONTROL.Views.MainWindow..ctor() in <path>\ipocs.jmri\IPOCS.JMRI.CONTROL\Views\MainWindow.axaml.cs:line 9
   at IPOCS.JMRI.CONTROL.App.OnFrameworkInitializationCompleted() in <path>t\ipocs.jmri\IPOCS.JMRI.CONTROL\App.axaml.cs:line 20
   at Avalonia.Controls.AppBuilderBase`1.Setup()
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at IPOCS.JMRI.CONTROL.Program.Main(String[] args) in <path>\ipocs.jmri\IPOCS.JMRI.CONTROL\Program.cs:line 13
```

### PR DESCRIPTION
**Pull request by mihnea-radulescu**
**Fix issue 4427 - System.InvalidOperationException: Default font family name can't be null or empty**

[Link to issue 4427](https://github.com/AvaloniaUI/Avalonia/issues/4427)

## What does the pull request do?
Fixes the exception _System.InvalidOperationException: Default font family name can't be null or empty_ occurring on some GNU / Linux operating systems, in particular Arch Linux and variants, through falling back to the first registered system font family, in the absence of a default font family name.

## What is the current behavior?
On some GNU / Linux operating systems, in particular Arch Linux and variants, the _FontManager_ constructor throws a _System.InvalidOperationException_ when a _defaultFontFamilyName_ is neither provided through the _FontManagerOptions_ instance, nor can it be resolved using _PlatformImpl.GetDefaultFontFamilyName()_.

## What is the updated/expected behavior with this PR?
The PR fixes the issue by falling back to the first registered system font family, in the absence of a provided or resolved default font family name.

## Checklist
- [x] Added new and updated existing unit tests

## Fixed issues
Fixes [#4427](https://github.com/AvaloniaUI/Avalonia/issues/4427)

### CODE REVIEW

**Comment by mihnea-radulescu** [comment]
@dotnet-policy-service agree

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0039277-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0039434-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0039497-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by Gillibald** [comment]
Can we avoid using Linq to select the first font and instead just use the indexer with a bounds check?

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0039540-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by mihnea-radulescu** [comment]
Thank you for the feedback, @Gillibald!

The PR has been updated accordingly.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0039544-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Review by Gillibald — APPROVED** [review]

**Comment by nopara73** [comment]
Congrats @mihnea-radulescu, you've earned [the 0.03 BTC bounty I created some years ago](https://github.com/AvaloniaUI/Avalonia/issues/4427#issuecomment-761541876) for resolving https://github.com/AvaloniaUI/Avalonia/issues/4427 🚀 

Please send me a Bitcoin address to adam.ficsor73@gmail.com. If you don't yet have a Bitcoin wallet, then a natural choice would be [Wasabi Wallet](https://wasabiwallet.io/), which is also written with Avalonia.

**Comment by kekekeks** [comment]
Not sure why it got merged, but it's incorrect behavior. The first found font could be some symbol font without any characters even for latin scripts.

We need to P/Invoke libfontconfig instead.

**Pull request merged**
