### PR TITLE
Devtools misc fixes

### PR DESCRIPTION
**Pull request by pr8x**
- Display Name of controls in the hierarchy
- Fix selection brush inside DataGrid
- Increase default panel width and fix annoying bug that prevents resizing the panel sometimes (not sure where this is coming from)

Maybe we should adjust the default theme for DataGrid to include this selection brush fix? Which color should we use in that case?

image

### CODE REVIEW

**Comment by maxkatz6** [comment]
I love every addition to the DevTools that improves productivity. But isn't there too much information in the tree view items? There is already type, classes and pseudoclasses.

**Comment by pr8x** [comment]
IDK, I often find myself looking for a specific part of a control and having the name immediately visible is certainly a big help. We could also consider adding the name to the tooltip maybe.

**Comment by danwalmsley** [comment]
name is really usefull!

**Review by danwalmsley — APPROVED** [review]
LGTM

**Comment by pr8x** [comment]
@danwalmsley  I guess I could increase the width of the left panel even more then?

**Comment by danwalmsley** [comment]
@pr8x do it... after ill merge!

**Comment by pr8x** [comment]
image

**Comment by pr8x** [comment]
image

**Pull request merged**
