### PR TITLE
Fallback from CenterOwner to CenterScreen when owner is null

### PR DESCRIPTION
**Pull request by sn4k3**
## What does the pull request do?
If a window with `WindowStartupLocation=CenterOwner` does not have an owner, it fall-back to CenterScreen.

## What is the current behavior?
If a window with `WindowStartupLocation=CenterOwner` is opened without a owner, it will be placed at a random location and depending on the OS.

## What is the updated/expected behavior with this PR?
Windows using `WindowStartupLocation=CenterOwner` without a owner will fall-back to CenterScreen and open at center of screen. 

## Checklist

- [ ] Added unit tests (if possible)?
- [x] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

### CODE REVIEW

**Review by maxkatz6 — APPROVED** [review]

**Comment by maxkatz6** [comment]
@sn4k3 it seems there is a possible NRE error. Can you check?

**Comment by sn4k3** [comment]
> @sn4k3 it seems there is a possible NRE error. Can you check? CI build it failing.

Done, however AvaloniaUI.IntegrationTests and AvaloniaUI.IntegrationTests (Mac) are still failling

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0024101-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0024234-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
