### PR TITLE
Text processing fixes

### LINKED ISSUE #8070: Text processing bugs
This issue helps track bugs related to recent text processing changes. Feel free to post your findings here.

Successor of #7502

### PR DESCRIPTION
**Pull request by Gillibald**
## Checklist

- [x] Added unit tests (if possible)?
- [x] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Fixed issues

Fixes #8070

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0022852-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0023281-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0023296-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by danipen** [comment]
I detected a selection issue using RTL text:

Using the following string:
```// RTL-arabic: اللغات مزدوجة البايت مدعومة الآن! continue here```

* Click to move the caret just at the starting of the word "continue".
* Then press Ctrl+Right to select the next word.
* **Expected**: The word "continue" is selected. **Actual**, the caret jumps to the beginning, and another part of the text is selected. Also, there is a rendering issue (the word "continue" disappears).
ctrlright-bug

**Comment by Gillibald** [comment]
Thanks for the repro. Having a look shortly.

**Comment by Gillibald** [comment]
> 

Seems to be fixed:

https://user-images.githubusercontent.com/5928797/192685537-6f949af5-8715-4fe6-b304-808dd16b6fbb.mp4

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0024194-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0024197-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0024226-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
