### PR TITLE
Removed unreferenced resources from TextBox

### PR DESCRIPTION
**Pull request by YohDeadfall**
## What does the pull request do?

Removes two resources which are not referenced anywhere in Avalonia.

## What is the current behavior?

Not to use them.

## What is the updated/expected behavior with this PR?

Not to use them, but also don't include them into Avalonia.

## How was the solution implemented (if it's not obvious)?

Running the editor of my choice first. Then switched to the selection mode, pressed `d` to remove selection, typed `:w` to save results. Repeated it for the second file, but with `:wq`.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0033152-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by maxkatz6** [comment]
These context menus were kept for backward compatibility with older applications which rely on context menu in the textbox styling and not context flyout.
But I believe it can be removed now, yes, as part of 11.0 breaking changes.

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0033154-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0033332-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Pull request merged**
