### PR TITLE
restore correct implementation of SetSystemDecorations on Win32.

### PR DESCRIPTION
**Pull request by danwalmsley**
This template is not intended to be prescriptive, but to help us review pull requests it would be useful if you included as much of the following information as possible:

- What does the pull request do?
This fixes SetSystemDecorations on Win32.

- What is the current behavior?
This doesn't work, it leaves an empty titlebar and leave a weird margin around the window when maximized.

Introduced by #1522.

- What is the updated/expected behavior with this PR?
This restores this function as it was before, leaving intact the PRs new functionality of implementing CanResize.

### CODE REVIEW

**Comment by grokys** [comment]
Pinging @CommonGuy for input.

**Comment by CommonGuy** [comment]
Won't this have a bug in these scenarios? I can't test these at the moment....

1. Set `CanResize` to true (default)
2. Set `HasSystemDecorations` to false
3. Now the window isn't resizable, even though `CanResize` is true.

or

1. Set `CanResize` to false
2. Set `HasSystemDecorations` to false, then to true again
3. Now the window is resizable, even though `CanResize` is false

That is why I made changes to the SetSystemDecorations method on Win32. Please correct me if I am wrong.

**Comment by danwalmsley** [comment]
When you have system decorations set to false the window is never resizable you have to implement your own resize grips.

**Comment by danwalmsley** [comment]
Let me post a screenshot of what they Windows look like without reverting this change

**Comment by danwalmsley** [comment]
https://files.gitter.im/AvaloniaUI/Avalonia/rCCu/image.png

This is a fully maximized window, there is a small white area at the top, this is titlebar that failed to be hidden and a margin all around the window (this is a bit of a mystery).

If I want to switch of Window Decorations im trying to get rid of all the features / chrome around the window including the grips that enable resize. The window here in the screenshot, has to implement its own resize grips.

If you know a way to completely get rid of the titlebar and know why the margin is happening then id be happy to move to look into it.

**Comment by CommonGuy** [comment]
@danwalmsley Thanks, that makes everything clearer. I fully agree with this change.

Maybe it makes sense to add a little bit of documentation to `CanResize` or `HasSystemDecorations` that they don't play well together? Or rather, if `HasSystemDecorations` is set to false, `CanResize` is ignored?

Oh, and I think there is a little bug: If you disable resizing, then disable system decorations and turn them back on, the window will have a resizable grip, even though `CanResize` is false. The Win32 implementation has a `_resizable` property, which should be respected when turning system decorations back on.

**Comment by danwalmsley** [comment]
@CommonGuy ok thanks for the feedback I will see if I can fix the bug and update documentation. I may also look for a way to just completely Hide the title bar, which would have worked better in my case, have you seen any information on completely hiding titlebar?

**Comment by danwalmsley** [comment]
@CommonGuy does the latest commit resolve the bug you mentioned?

**Review by CommonGuy — APPROVED** [review]

**Comment by kekekeks** [comment]
I don't quite like the way we are managing window styles. The current approach is error-prone because SetWindowLong is called from multiple places and modifies the current style instead of recomputing all of the parts of it that are controlled by Avalonia.

From my point of view style management should be done by a separate UpdateWindowStyles function that would recompute them according to the current flags (_canResize, _hasDecorations, etc). The functions that update said flags should get window rect before the change, update the flags, call `UpdateWindowStyles` and restore window size and position according to the new styles if needed.

**Comment by kekekeks** [comment]
Regarding custom resize implementations, we have a managed one that is used by MonoMac backend: https://github.com/AvaloniaUI/Avalonia/blob/master/src/Shared/WindowResizeDragHelper.cs

**Pull request merged**
