### PR TITLE
Fix #1484 nested popups

### LINKED ISSUE #1484: DropDown selection in Popup container closes Popup
Selecting an item from the dropdown below will close the flyout Popup and leave the DropDown's popup open

```
<ToggleButton IsChecked="{Binding #flyout.IsOpen, Mode=TwoWay}" ClickMode="Press" > settings </ToggleButton>
    <Popup Name="flyout" StaysOpen="False" Width="200" Height="200"  >
      <Border Background="LightGray" BorderBrush="Gray" BorderThickness="1" Padding="6" >
        <StackPanel>
          <DropDown>
            <DropDownItem>Item A</DropDownItem>
            <DropDownItem>Item B</DropDownItem>
          </DropDown>
        </StackPanel>
      </Border>
    </Popup>

### PR DESCRIPTION
**Pull request by ahopper**

### CODE REVIEW

**Comment by grokys** [comment]
@ahopper could you add a description of what the problem was and how you fixed it to the PR? It's hard to review without that context.

**Comment by ahopper** [comment]
Sorry for the  lack of detail. This was to fix https://github.com/AvaloniaUI/Avalonia/issues/1484 . The initial problem was that a dropdown in a popup would leave the dropdown popup open and close the containing popup if you selected an item. In fixing this another problem appeared, closing a popup that contained other open popups would leave the contained popup visible.

**Comment by ahopper** [comment]
more detail, this pr seems to fix both problems in my previous comment. I'm not sure I'm traversing the tree in the most efficient way to detect if a click is in a child popup. I tried detecting if a parent popup has closed in a number of ways and Popup.Closed was the only event that seemed to fire, I tried 
 popupRoot.Deactivated so that it worked like window but got no joy.

**Review by grokys — CHANGES_REQUESTED** [review]
Looks good, I think the changes make sense.

My only problem is that I can't really fathom the Popup page in ControlCatalog - I know it's meant to demonstrate the problem here, but to the casual user the Popup page won't make much sense!

Could you either try to create a Popup page that works as a general demonstration of the Popup control, or just remove the page? Also the pages in Control catalog should be in alphabetical order.

**Review by grokys — APPROVED** [review]

**Comment by grokys** [comment]
Thanks @ahopper - merged!

**Pull request merged**
