### PR TITLE
Fix #13474 by partially reverting #12883

### LINKED ISSUE #13474: [Regression] ListBoxItems and children no longer reliably generate Tapped events from Touch input.
## Describe the bug
ListBoxItems or their children (with the exception of Buttons at least) no longer generate Tapped events or trigger Tapped event handlers when the input comes from a touch device.  Mouse clicks still generate Tapped events as expected.  Both generate DoubleTapped events.

## To Reproduce

1. Clone https://github.com/IanRawley/ListBoxItemTappedInteractions.git and build as is.
2. Run on a touch enabled device, and see that tapping either the Buttons or Border/Textblocks increment the appropriate counter.
3. Update solution to Avalonia 11.0.5 and rebuild.
4. Tapping the Border/Textblocks no longer increments the appropriate counter.  Buttons are unaffected.  Using a mouse to click the Border/Textblocks will increment the counter though.

## Expected behavior
Both mouse input and touch input generate Tapped events.

## Environment 
- OS: Windows 11 / Android.
- Avalonia-Version: 11.0.4 - OK / 11.0.5 - Broken.

## Additional context
Looking through the list of commits from Avalonia 11.0.4 to 11.0.5 the only one that seems potentially relevant is  #12666,
although I don't know nearly enough about the whole GestureRecognizer system to comment with any certainty.

Using a Surface Go 4 to check has been a boon, as the use of DevTools has allowed me to confirm that nowhere within the bounds of a ListBoxItem is generating Tapped events from touch input, with the exception of the bounds of the Button.

### PR DESCRIPTION
**Pull request by IanRawley**
## What does the pull request do?
Fixes issue #13474, where Tapped events are not generated by ListBoxItems or their children from Touch based pointer events.

## What is the current behavior?
Currently when a ListBoxItem (or child control) is tapped with a touch device, the ListBoxItem re-raises the PointerReleased event on the owner ListBox, overwriting the event source with the ListBox.  The Tapped gesture recognizer is looking for PointerPressed and PointerReleased events with matching sources, so this change of source prevents Tapped events from being raised.

## What is the updated/expected behavior with this PR?
ListBoxItem no longer re-raises the event from Touch input, allowing it to bubble up to the ListBox (and Tapped gesture recogniser) normally.  This re-enables Tapped events from Touch input, and also prevents the probably unintended consequence of the same event arguments bubbling up twice.

## How was the solution implemented (if it's not obvious)?
Partially reverts #12883, removing the changes to ListBoxItem where it re-raises the PointerReleased event on the owner ListBox.  I couldn't figure out why the event needed to be raised rather than bubbling up, as nothing I could find to the AutoCompleteBox checked what the source of the event was or whether it was handled or not.  I couldn't reproduce #12848 after my changes, so I don't think I've re-broken the AutoCompleteBox focus issues.

In the course of setting up the failing unit test, I ran into an issue where different parts of the framework make different assumptions about Touch input.  Specifically the TouchTestHelper generates Touch events without assigning mouse buttons to them, but every other part of the framework seems to assume that Pointer events are by default LeftMouseButton events.  This means that using the TouchTestHelper to unit test the change didn't work, because Gestures is checking if the PointerReleasedEvent has InitialButtonPress == LeftMouseButton even for touch input, and thus wouldn't generate Tapped events.  I elected to manually generate the Pressed and Released events in the unit test rather than touch other parts of the framework to avoid unintended consequences.  I also wasn't sure where the unit test should go, but elected for with the ListBox unit tests rather than Gestures or TouchDevice as it's very specific to ListBoxItem.

## Checklist

- [X ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/avalonia-docs with user documentation

## Breaking changes
No breaking changes I'm aware of.

## Fixed issues
Fixes #13474

### CODE REVIEW

**Comment by IanRawley** [comment]
@dotnet-policy-service agree company="Silmetra Ltd"

**Comment by emmauss** [comment]
On non-desktop touch devices(android, ios), tapping an item in an autocomplete box doesn't close the list and focus on the box, with this PR. Could you confirm this works on android?

**Comment by IanRawley** [comment]
> On non-desktop touch devices(android, ios), tapping an item in an autocomplete box doesn't close the list and focus on the box, with this PR. Could you confirm this works on android?

You're right, it doesn't close the drop down on Android.  I'll spend some time today trying to figure out why, and how to fix it without breaking tapped events.

**Comment by IanRawley** [comment]
Putting the Event re-raise back and testing on Android more, I'm getting some strange results.

1. On the emulator, typing into the box and selecting something closes the popup and focuses the textbox as expected.
2. On a physical device with bluetooth keyboard, the same result.
3. On a physical device with no keyboard, the popup closes, but focus is usually lost.  But not always.

On another note, connecting a Bluetooth keyboard to the physical device while the soft keyboard is showing is causing the ControlCatalog to throw System.ArgumentException: 'Attempt to call InvalidateArrange on wrong LayoutManager.'
That's a different issue obviously.

**Comment by IanRawley** [comment]
OK, I've figured out the particular oversight that caused the problems on Android.  I neglected to consider that marking the event handled would (of course) prevent it bubbling up to the ListBox.  By changing the ListBoxItem change to only mark the event handled from a mouse it seems to have fixed the AutoCompleteBox, at least as far as I can tell, and Tapped events still occur.  I'm running the Unit Tests now to make sure I haven't broken anything else.

**Comment by IanRawley** [comment]
New version has the ListBoxItem not mark the PointerReleased event as handled if it came from a non-mouse device.  It seems to work, but I'm leery of handling mouse and touch differently, which is what started me working on this in the first place.  An alternative is simply to have the ListBoxItem not mark PointerReleased as handled full stop, but I don't know the wider implications of that.

**Comment by IanRawley** [comment]
Third version.  Always sets handled, but backs the source up before raising the event again, and restores the original source after.  Allows Tapped events to be generated, and seems to not break AutoCompleteBox.

**Comment by jmacato** [comment]
requesting review @emmauss

**Review by emmauss — APPROVED** [review]
LGTM. No issues on android

**Comment by IanRawley** [comment]
Any chance of this getting backported?  Or is it slated for an imminent release?

**Pull request merged**
