### PR TITLE
Additional SKIA Caching

### PR DESCRIPTION
**Pull request by DJGosnell**
## What does the pull request do?
Continuing my investigation into performance of the composer loop.  Currently, there are several places which `SKTextBlobBuilder`, `SKRoundRect` and `SKFont` objects are instanced and either fall out of scope or are disposed..  These objects are all backed by SKIA counterparts which must be disposed of.  This PR seeks to reduce how many of these items are instanced and discarded and instead reuse the instances for later.

Found out that SKTextBlobBuilder is designed to be re-used.  Once the [make](https://api.skia.org/classSkTextBlobBuilder.html#abf5e20208fd5656981191a3778ee5fef) method is called, it is reset for reuse.  Apparently SkaiSharp uses the [make method internally](https://github.com/mono/SkiaSharp/blob/a863ca3ed6b420a86f7e81afec8eba79dfda495d/binding/Binding/SKTextBlob.cs#L285).

I took the opportunity to also update the `SKPaintCache` introduced in #9441 to use the same new base caching system.

## What is the current behavior?
`SKTextBlobBuilder`, `SKRoundRect` and `SKFont`s are created and either explicitly disposed or GCed.  This leads to additional objects which are created and needlessly disposed.

## What is the updated/expected behavior with this PR?
There are new `SKTextBlobBuilderCache`, `SKRoundRectCache` and `SKFontCache` types which allow for caching and resetting of these base types for reuse.

This PR focuses on improving following methods:
#### `Avalonia.Skia.PlatformRenderInterface.CreateGlyphRun(IGlyphTypeface, Double, IReadOnlyList, Point)`
Now uses ` SKFontCache` for caching.
Now uses ` SKTextBlobBuilderCache` for caching,

#### `Avalonia.Skia.DrawingContextImpl.DrawRectangle(IBrush, IPen, RoundedRect, BoxShadows)`
Now uses ` SKRoundRectCache` for caching,

#### `Avalonia.Skia.TextShaperImpl.ShapeText(ReadOnlyMemory, TextShaperOptions)`
Now has an internal static cache on the `TextShaderImpl` class which caches currently used languages.
ShapeText

## How was the solution implemented (if it's not obvious)?
Added caching classes and utilized where possible.

## Benchmarks
| Type     | Method                                                                                             | N         | Time (ms) | Memory (MB) |
|----------|----------------------------------------------------------------------------------------------------|-----------|-----------|-------------|
| Baseline | Avalonia.Skia.PlatformRenderInterface.CreateGlyphRun(IGlyphTypeface, Double, IReadOnlyList, Point) |  250,000  | 426       | 91          |
| PR       | Avalonia.Skia.PlatformRenderInterface.CreateGlyphRun(IGlyphTypeface, Double, IReadOnlyList, Point) |  250,000  | 92        | 45          |
|          |                                                                                                    |           |           |             |
| Baseline | Avalonia.Skia.DrawingContextImpl.DrawRectangle(IBrush, IPen, RoundedRect, BoxShadows)              |  250,000  | 550       | 27          |
| PR       | Avalonia.Skia.DrawingContextImpl.DrawRectangle(IBrush, IPen, RoundedRect, BoxShadows)              |  250,000  | 90        | 0           |
|          |                                                                                                    |           |           |             |
| Baseline | Avalonia.Skia.TextShaperImpl.ShapeText(ReadOnlyMemory, TextShaperOptions)                          |  250,000  | 744       | 169         |
| PR       | Avalonia.Skia.TextShaperImpl.ShapeText(ReadOnlyMemory, TextShaperOptions)                          |  250,000  | 246       | 177**       |

All benchmarks are run with this [Benchmark](https://github.com/DJGosnell/Avalonia/tree/render-benchmark) which renders 500 Square Rectangles, 500 Round Rectangles and 500 simple texts every frame until 500 frames have passed.  When the test takes less time, it means that the rendering took less time to complete. the same 500 frames.

** Currently Reviewing why this usage is higher...

Baseline Benchmark Time **10,235ms**
BaselineOverall

PR Benchmark Time **7,419ms**
PROverall

<details><summary>DotTrace Details</summary>
<p>

CreateGlyphRun_Baseline
CreateGlyphRun_Baseline

CreateGlyphRun_PR
CreateGlyphRun_PR

DrawRectangle_Baseline
DrawRectangle_Baseline

DrawRectangle_PR
DrawRectangle_PR

Language_Baseline
Language_Baseline

Language_PR
Language_PR

ShapeText_Baseline
ShapeText_Baseline

ShapeText_PR
ShapeText_PR

</p>
</details>

## Checklist

- [x] Added unit tests (if possible)? [Benchmark](https://github.com/DJGosnell/Avalonia/tree/render-benchmark)
- [x] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Breaking changes
None.

## Obsoletions / Deprecations
N/A

## Fixed issues
N/A

## Notes
It may be worth a discuss about these locations the caches are used and if there is any possibility for cross thread usage.  If not, we can replace the ConcurrentBag<T> with a Queue<T> for additional savings.

### CODE REVIEW

**Comment by maxkatz6** [comment]
> if there is any possibility for cross thread usage. If not, we can replace the ConcurrentBag with a Queue for additional savings.

Currently we support only a single rendering thread. But I think there were discussion to support more than one in the future.

**Comment by kekekeks** [comment]
Graphics backend can be used from multiple threads already.
1) RenderTargetBitmap is available from the UI thread in immediate mode
2) It's possible to manually create a render target from something like a framebuffer

**Comment by Gillibald** [comment]
Are you sure that SKTextBlobBuilder can be shared by multiple threads? We should definitely verify that FormattedText can be created on any thread.

**Comment by DJGosnell** [comment]
> Are you sure that SKTextBlobBuilder can be shared by multiple threads? We should definitely verify that FormattedText can be created on any thread.

I'll run some tests to verify.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0029942-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by DJGosnell** [comment]
> Are you sure that SKTextBlobBuilder can be shared by multiple threads? We should definitely verify that FormattedText can be created on any thread.

@Gillibald Just want to make sure that I understand what is going and how my caching strategy works in this case. 
-  All the caches require you to manually add back the cached item.  This has two effects: 
    1. There is no overhead for any wrapper classes and handling disposal of wrappers.
    2. If for some reason the item does not get added back to the cache, it will get properly disposed like any normal CLR object. 
- Any time a cached item is not in the cache, a new one is created even if they are on the same thread.
- No time between requesting a cached item and returning it to the cache, should the cached object be used in multiple places across the codebase.  Meaning the same cached object will not be used on another thread nor another place on the same thread.  If one thread requests an object and another does simultaneously, they will both get separate objects whether they be from the cache or new instances created by the cache.

Now that I explained my cache implementation a bit better, is the following flow the concern?

  1. Cached item for SKTextBlobBuilder is requested, used and returned on one thread.
  2. Cached item for the same SKTextBlobBuilder is requested and used on another thread.

Through this implementation of the cache, no single SKTextBlobBuilder will be used simultaneously.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0029946-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by Gillibald** [comment]
As long as no SKTextBlobBuilder-related resources are bound to a dedicated thread this is fine.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0029983-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by DJGosnell** [comment]
Per the [documentation](https://api.skia.org/classSkTextBlobBuilder.html#abf5e20208fd5656981191a3778ee5fef), the `make` method _Resets [SkTextBlobBuilder](https://api.skia.org/classSkTextBlobBuilder.html) to its initial empty state, allowing it to be reused to build a new set of runs._

I've run extensive testing to ensure that SKTextBlobBuilder is can be used used across threads (not simultaneously) and one of the methods I used was to create a multi-threaded benchmark which has the baseline current method of using the SKTextBlobBuilder (instancing per usage) and PR caching usage.  See the benchmarks and traces below.

I never ran into any exceptions or unexpected behavior throughout testing.

https://github.com/DJGosnell/SKTextBlobBuilderBenchmarks

|   Method |     Mean |    Error |   StdDev | Ratio | RatioSD |     Gen0 |    Gen1 | Allocated | Alloc Ratio |
|--------- |---------:|---------:|---------:|------:|--------:|---------:|--------:|----------:|------------:|
| Baseline | 33.14 ms | 1.293 ms | 3.813 ms |  1.00 |    0.00 | 187.5000 |       - |   1.65 MB |        1.00 |
|       PR | 17.45 ms | 0.455 ms | 1.343 ms |  0.53 |    0.07 | 140.6250 | 15.6250 |   1.05 MB |        0.64 |

**Baseline**
Baseline

**PR**
PR

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0030075-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Review by Gillibald — APPROVED** [review]
Thanks a lot for your work and detailed analysis

**Pull request merged**
