### PR TITLE
Avoid IME to be disabled after popups, fix #8758

### LINKED ISSUE #8758: Windows - IME Context isn't reset for Popups
**Describe the bug**
ime will be disabled after clicking some controls like combobox

i use chinese ime (sogou) ，when i click textbox after clicking combobox , the ime will be disabled an i can't input chinese words ,i can only input english words.

**To Reproduce**

1. run the app
2. Click on textbox,the ime is ok,i can input chinese words
3. Click on combobox
4. Click on textbox,the ime will be disabled,i can't input chinese

**Expected behavior**
i hope that i can input chinese words

**Screenshots**

https://user-images.githubusercontent.com/6055564/184682349-b92b5dad-da83-41e9-b4a4-557a64e9bbf7.mp4

**Desktop (please complete the following information):**

- OS: Windows 19042
- Version 0.10.17

### PR DESCRIPTION
**Pull request by lnxon**
## What does the pull request do?
Fix the issue that IME is diabled if you open a popup (problem repoted in [#8758](https://github.com/AvaloniaUI/Avalonia/issues/8758)).

## What is the current behavior?

For example if you have TextBox and Combobox in a Window, you can not enter Japanese text in this TextBox once you open Combobox's dropdown.

## What is the updated/expected behavior with this PR?

TextBox have active IME regardless if you open any popup, dropdowns, etc...

## How was the solution implemented (if it's not obvious)?

Following author's comment at [on Aug 18, 2022](https://github.com/AvaloniaUI/Avalonia/issues/8758#issuecomment-1219344182)

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Fixed issues

Fixes #8758

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0032600-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by lnxon** [comment]
@dotnet-policy-service agree

**Comment by lnxon** [comment]
#8758

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0032692-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by ptpt666** [comment]
@Gillibald Is't the best way?

**Review by Gillibald — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0032903-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Pull request merged**
