### PR TITLE
Mark some classes/types needed for unit testing as [PrivateApi]

### PR DESCRIPTION
**Pull request by danipen**
## What does the pull request do?
It marks the needed classes/types as `PrivateApi` so other Avalonia projects using Unit Testing can set a compositor for the [IWindowImpl](https://github.com/AvaloniaUI/Avalonia/blob/fdf27e16a1cc35f3cf6e4b6be036e5091b2cafa8/tests/Avalonia.UnitTests/MockWindowingPlatform.cs#L31), in the same way [it's done in this repository](https://github.com/AvaloniaUI/Avalonia/blob/fdf27e16a1cc35f3cf6e4b6be036e5091b2cafa8/tests/Avalonia.UnitTests/RendererMocks.cs#L19).

## What is the current behavior?
Cannot use the internal constructors for the `Compositor` class.

## What is the updated/expected behavior with this PR?
When using the `<AvaloniaAccessUnstablePrivateApis>True</AvaloniaAccessUnstablePrivateApis>`, those types are now accessible.

## Breaking changes
No.

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0039048-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0039052-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0039065-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by danipen** [comment]
Discarded in favor of https://github.com/AvaloniaUI/Avalonia/pull/12750

**Pull request closed without merging**
