### PR TITLE
fix: DataContext Inheritance in ReactiveUserControl<TViewModel>

### LINKED ISSUE #4962: ReactiveUserControl DataContext/ViewModel synchronization broken for inherited values.
https://github.com/AvaloniaUI/Avalonia/pull/4917 appears to have broken `DataContext` inheritance in `ReactiveUserControl`. Here's a failing test:

```
        [Fact]
        public void Should_Inherit_DataContext()
        {
            var vm1 = new ExampleViewModel();
            var vm2 = new ExampleViewModel();
            var view = new ExampleView();
            var root = new TestRoot(view);
            Assert.Null(view.DataContext);
            Assert.Null(view.ViewModel);
            root.DataContext = vm1;
            Assert.Same(vm1, view.DataContext);
            Assert.Same(vm1, view.ViewModel);
            root.DataContext = null;
            Assert.Null(view.DataContext);
            Assert.Null(view.ViewModel);
            root.DataContext = vm2;
            Assert.Same(vm2, view.DataContext);
            Assert.Same(vm2, view.ViewModel);
        }
```

This happens because when `ViewModel` is set to `null`, it assigns `null` to `DataContext` instead of clearing the value.

cc: @worldbeater

### PR DESCRIPTION
**Pull request by worldbeater**
#### What does the pull request do?

Fixes https://github.com/AvaloniaUI/Avalonia/issues/4962 The regression was introduced in https://github.com/AvaloniaUI/Avalonia/pull/4917

#### What is the current behavior?

Currently, the `DataContext` is set to `null` when `ViewModel` changes, and this breaks `DataContext` inheritance.

#### What is the updated/expected behavior with this PR?

Now, we are using `ClearValue` extension method in order to indicate that the `DataContext` is null.

cc @grokys

### CODE REVIEW

**Comment by worldbeater** [comment]
Also adjusted `ReactiveWindow<TViewModel>` class to comply with the updated `ReactiveUserControl<TViewModel>` behavior.

**Comment by MarchingCube** [comment]
@grokys Please take a look so we can avoid stuff blowing up again :)

**Comment by worldbeater** [comment]
Yeah had a conversation with Steven in Slack regarding this topic, but this change totally needs a careful review in order to ensure the data context inheritance never breaks (e.g. I might be lacking the expertise and I might not see some edge-cases)

**Review by grokys — APPROVED** [review]
Thanks @worldbeater - hope you don't mind but I committed a small change to your branch to use the existing `OnDataContextChanged` method instead of creating a new one.

I also looked through the history of my version of this feature for WPF as for why in WPF I had to do it only `WhenActivated` and it was to prevent leaking `DependencyPropertyDecriptor`s and so shouldn't be necessary in Avalonia as we suspected.

**Pull request merged**
