### PR TITLE
Update SkiaSharp to V2

### PR DESCRIPTION
**Pull request by Gillibald**
## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

### CODE REVIEW

**Comment by jmacato** [comment]
tested and it works great :D though let's keep this open until the current RC goes into official

**Comment by Gillibald** [comment]
I wonder why tests are failing on Linux

**Comment by danwalmsley** [comment]
> tested and it works great :D though let's keep this open until the current RC goes into official

if they release, then prob we should include in 0.10

**Review by jmacato — APPROVED** [review]
LGTM! @danwalmsley please include this in preview2

**Pull request merged**
