### PR TITLE
Support StringFormat without Converter in MultiBinding

### LINKED ISSUE #2590: Allow MultiBindings with StringFormat and without Converter
In #2385, @OronDF343 added the StringFormat property to MultiBindings. Currently, it is necessary to provide a converter, even if StringFormat is set. In WPF, this is not necessary:

```
<MultiBinding StringFormat="{} Dimensions: {0}mm x {1}mm">
      <Binding Path="PhysicalLength"></Binding>
      <Binding Path="PhysicalHeight"></Binding>
</MultiBinding>
```

I therefore propose removing the exception thrown in the `Initiate` method of `MultiBinding` when no Converter is set.

### PR DESCRIPTION
**Pull request by OronDF343**
This PR adds support for using `StringFormat` in `MultiBinding` even when `Converter` isn't specified, instead of throwing an exception. This feature is present in WPF.

Implementation is now closer to how it was done in `Binding`.

Side-effect of this change: Specifying neither `StringFormat` nor `Converter` will result in an `object[]` value, instead of throwing an exception.

Fixes #2590 

- [x] Updated unit tests
- [x] Added XML documentation to any related classes

### CODE REVIEW

**Comment by grokys** [comment]
@jhofinger could you take a look and see if this is expected behavior now?

**Comment by jhofinger** [comment]
Thanks for the quick fix! In theory, yes, however, I can't get it to work for the AutoCompleteBox with MultiBinding in the ControlCatalog. When I specify the following:
```
var binding = new MultiBinding { StringFormat = "{0} ({1})" };
binding.Bindings.Add(new Binding("Name"));
binding.Bindings.Add(new Binding("Abbreviation"));
var multibindingBox = this.FindControl<AutoCompleteBox>("MultiBindingBox");
multibindingBox.ValueMemberBinding = binding;
```
I get a `System.FormatException` in the Convert method of `StringFormatMultiValueConverter`, and the `values` parameter shows two results of type `Avalonia.BindingNotification` with `Error` = `Null value in expression "."` You might want to add a handler for this.

Instead, I tried to set the multi binding from XAML (as in WPF). So I specified
```
<AutoCompleteBox.ValueMemberBinding>
      <MultiBinding StringFormat="\{0\} (\{1\})">
            <Binding Path="Name"></Binding>
            <Binding Path="Abbreviation"></Binding>
      </MultiBinding>
</AutoCompleteBox.ValueMemberBinding>
```
which of course conflicts with the correct format for format strings, but unescaped braces are interpreted as markup extension (see also #2592) so neither works for me.

**Comment by OronDF343** [comment]
@jhofinger I've fixed it now, sorry for the delay.

(The Converter was not "instanced", so since AutoCompleteBox causes `Initiate` to be called multiple times, the string format converter was being applied multiple times.)

**Comment by grokys** [comment]
@jhofinger does the recent change work for you?

**Comment by jhofinger** [comment]
@Grokys yes, it does - but only when setting it from code behind, and there I don't see a clear advantage over using `FuncMultiValueConverter`. The idea of StringFormat with MultiBinding would be to set it from XAML, which is still not possible, see my last answer. At least the user should be presented an error when trying to instantiate a MultiBinding with StringFormat in XAML.

**Comment by grokys** [comment]
Ok, I'll take a look at this.

**Comment by grokys** [comment]
Yep, confirmed that this is a problem with the XAML compiler: https://github.com/AvaloniaUI/Avalonia/issues/2592#issuecomment-505972730

**Review by grokys — APPROVED** [review]

**Comment by grokys** [comment]
Going to merge this and then we'll fix the XAML compiler.

**Pull request merged**
