### PR TITLE
DataGrid - Fix remaining theme colors

### PR DESCRIPTION
**Pull request by Symbai**
## What does the pull request do?
Replace remaining hardcoded brushes with theme brushes. I had to use similar theme brush values because the hardcoded brush values don't exist in theme resource dictionary.

#### Before Light
image
#### After Light
image
#### Before Dark
image
#### After Dark
image

### CODE REVIEW

**Comment by grokys** [comment]
@Symbai I've just noticed that #3530 causes a problem: the row highlight color is now the same as the `TextBox` highlight color, so when you double-click to edit a `DataGridTextColumn`, you can't see that the text is highlighted, for example:

yYwbO87HHQ

I think we need to choose a different color for the row highlight, could we do that in this PR? Here's the above operation using `ThemeAccentBrush` (which might be a good choice?) for example:

uyRJbTbAhL

Other than that, PR looks good!

**Comment by Symbai** [comment]
@grokys Nice catch. Using `ThemeAccentBrush` makes the selection really noticeably. But on dark theme it barely is then:

### Light
image

### Dark
image

How about `ThemeAccentBrush2`?

### Light:
image

### Dark:
image

**Comment by Gillibald** [comment]
Can't we change the background of the TextBox so it does not have the same color as the selected row?

**Comment by Symbai** [comment]
@Gillibald Generally we should consider adding background colors to many controls as currently many controls have a transparent background, causing the issue above (different behavior to WPF and causes issues when controls are placed on a custom background. I wanted to make a PR someday later about). 

In WPF the textbox in DataGrid has a background which is not transparent, matching with your suggestion.
image

If this is what we want to do, I would undo the change in this PR and make a new PR setting background colors to several controls.

**Comment by grokys** [comment]
Hmm yeah maybe that would be better, if that's what WPF does. If that's the case 👍 to reverting the change there.

**Comment by Symbai** [comment]
Done

**Review by grokys — APPROVED** [review]

**Pull request merged**
