### PR TITLE
Properly handle setting SelectedIndex from XAML

### PR DESCRIPTION
**Pull request by Gillibald**
## What does the pull request do?
It fixes an issue with SelectingItemsControl when someone tries to pre-select an item by setting SelectedIndex in XAML.

## What is the current behavior?
Setting SelectedIndex in XAML has no effect.

## What is the updated/expected behavior with this PR?
Setting SelectedIndex in XAML has the expected effect.

## How was the solution implemented (if it's not obvious)?
Currently, the selection is updated during initialization and that causes a reset of SelectedIndex every time an item is added. Now collection changes aren't handled during initialization and therefore the SelectedIndex is preserved. If no pre-selection is made the SelectedIndex is properly set to the first item.

## Checklist

- [ ] Added unit tests (if possible)?

## Fixed issues
#2987

### CODE REVIEW

**Comment by Gillibald** [comment]
Let me know if we need a unit test. Then I will try to write one that is covering the issue.

**Comment by grokys** [comment]
Thanks @Gillibald - a unit test would be good. If you could rebase so that the failing test is a single commit before the fix, that would make it easy to review.

**Comment by Gillibald** [comment]
Okay will do shortly 👍

**Comment by Gillibald** [comment]
Messed up rebasing this sry.
Moved to #3047

**Pull request closed without merging**
