### PR TITLE
Don't rebuild when running .NET Core tests.

### PR DESCRIPTION
**Pull request by grokys**
When running `dotnet test` we can pass the `NoBuild` and `NoRestore` flags to save a bit of time as we've already built everything. This looks like it cuts a few minutes off CI build time.

There is currently [an issue](https://help.appveyor.com/discussions/problems/10117-dotnet-test-with-xunit-fails-because-of-the-wrongly-resolved-path) with AppVeyor and `dotnet test` where the wrong platform is being sent to `dotnet test`, the solution is simply to not pass the platform for now.

### CODE REVIEW

**Comment by grokys** [comment]
Hmm, this is failing on travis...

**Comment by jkoritzinsky** [comment]
Travis by default builds ControlCatalog.NetCore instead of us maintaining a separate solution file for Linux. So, the tests currently have to build on Linux since nothing else is building the test assemblies right now.

**Comment by grokys** [comment]
Yeah I just saw that. So on travis we're building using .NET Core? In that case why are we passing `--platform "Mono"`?

**Comment by grokys** [comment]
What if I just change the "Mono" configuration to not build the projects we can't build on travis for now?

**Comment by jkoritzinsky** [comment]
That would probably work. It might just have been really annoying before to get that to work. Try it out!

**Comment by lindexi** [comment]
I also cant build it.

**Comment by grokys** [comment]
Managed to get this compiling, but to do so I made the unit tests run on `netcoreapp2.0` only (no `net47`). Is this acceptable? My reasoning was that 1. I've never seen a test fail on one platform but pass on another 2. it's more valuable to be running the tests on Travis.

Also: the .sln configuration used to run on Travis is still called `Mono` but it's not actually running on `Mono`. Should we rename this? What to? `NetCore`? `NetCoreOnly`?

**Review by jkoritzinsky — APPROVED** [review]
Let's rename the configuration to NetCoreOnly. Other than that this PR LGTM.

**Pull request merged**
