### PR TITLE
Virtualization improvements

### LINKED ISSUE #10367: ListBox with variable height items using Expander and virtualization shows items on top of each other
**Describe the bug**
A ListBox with variable height ItemTemplate by using an Expander shows items on top of each other while scrolling them into view.
(also some scroll 'skipping' while scrolling them out of view? see video)

(ps. after multiple scroll passes, there seem to appear 'ghost' items in view)

this is using `11.0.999-cibuild0030035-beta`.

**To Reproduce**
[ListBox_VariableHeightItems.zip](https://github.com/AvaloniaUI/Avalonia/files/10757213/ListBox_VariableHeightItems.zip)

ListBox looks like:
```xaml
    <ListBox Items="{Binding Items}">
        <ListBox.ItemTemplate>
            <DataTemplate DataType="vm:Item">
                <Expander HorizontalAlignment="Stretch" IsExpanded="{Binding IsExpanded, Mode=TwoWay}">
                    <Expander.Header>
                        <TextBlock Text="{Binding Index}" />
                    </Expander.Header>
                    <Panel Height="250" Background="Black" />
                    <!--  instead of panel I'd like to do an inner ListBox for a simple master-detail pattern  -->
                </Expander>
            </DataTemplate>
        </ListBox.ItemTemplate>
    </ListBox>
```

**Expected behavior**
Items adjacent to each other.

**Screenshots**

https://user-images.githubusercontent.com/27849065/219400418-5ba2c2ed-a295-42dc-8923-55304016cd8a.mp4

### LINKED ISSUE #10825: ListBox inside Scrollviewer cause crash
**Describe the bug**
When ListBox are scrolled in and out of Scrollviewer visible area, app crash with exception 
System.InvalidOperationException: 'The control already has a visual parent.'

**To Reproduce**

1. Clone https://github.com/rabbitism/ListBoxCrashDemo
2. Run App
3. Scroll up and down

**Expected behavior**
Nothing should happen

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 11
- Version 11.0-preview6

**Additional context**
I think this is ScrollViewer issue. I also encountered similar issue when change theme of a control with ScrollViewer in control template. I will prepare another sample if I can reproduce.

### PR DESCRIPTION
**Pull request by grokys**
## What does the pull request do?

Working on improving virtualization with variable-sized items:

- Housekeeping: [move the realized element list out of `VirtualizingStackPanel`](https://github.com/AvaloniaUI/Avalonia/pull/10892/commits/a08f4ac97726d51b3ba638f003b49c56099581ee) as it was getting big
- Housekeeping: [Modernize ItemsControl tests](https://github.com/AvaloniaUI/Avalonia/pull/10892/commits/670eea0977f005263e7586227532da2085fc00b0)
- [Register anchor candidate in `VirtualizingStackPanel`](https://github.com/AvaloniaUI/Avalonia/pull/10892/commits/345fb7e1d6b8aaadf01b3f7f2f722dbff433a261): We need to register controls as anchor candidates in the panel instead of in `ItemsControl` because the candidate needs to be registered after arrange. See commit message for more details
- [Make thumb drag delta relative to parent](https://github.com/AvaloniaUI/Avalonia/pull/10892/commits/54449850cc39d9c04c13412fc3fb9f27c35c03aa) instead of thumb itself: prevents the viewport jumping around when scrolling a virtualized list with differing sizes. Instead the thumb jumps around which is much less jarring
- [Modify VirtualizingStackPanel algorithm.](https://github.com/AvaloniaUI/Avalonia/pull/10892/commits/5919ca6acc3aa75af9771bc18fce99f1a2a90b26): Try to get an "anchor element" during measure, which is an existing element in the viewport that we know the position of. Start realizing elements from this anchor element.
- [Handle recycling control items inside containers.](https://github.com/AvaloniaUI/Avalonia/pull/10892/commits/39db10b345dc15a664c92ff79b1f22c3b6bc950e) to fix #10825 

Also rewrote `VirtualizationDemo` to try to give some more real-world examples for virtualizing lists, e.g. a ChatGPT-generated conversation:

https://user-images.githubusercontent.com/1775141/229478092-e2b9b7c8-1eb6-4658-86b6-3066642ff068.mp4

## Fixed issues

Fixes #10367
Fixes #10825

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0032802-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by grokys** [comment]
Ready for review/testing.

**Review by jmacato — APPROVED** [review]
Tested with a sample app: https://github.com/jmacato/Avater/tree/fake-chat-text-gen-latest-listbox


https://user-images.githubusercontent.com/16554748/230141404-aae5519b-aab2-4361-bda5-51d66c7bf7d7.mov

**Comment by wieslawsoltes** [comment]
The position of mouse pointer and scrollbar thumb get out of sync when moving scrollbar:

image


https://user-images.githubusercontent.com/2297442/230170522-015e737a-278c-4ec1-9078-89fa5cbe49ad.mp4

**Comment by wieslawsoltes** [comment]
This shows the issue more clearly (scrolling with mouse pointer and thumb):

https://user-images.githubusercontent.com/2297442/230171380-9b99f3bc-dee3-4258-b4f3-b86a14587aa8.mp4

**Comment by wieslawsoltes** [comment]
> This shows the issue more clearly (scrolling with mouse pointer and thumb):

This makes impossible to scroll entire list using scrollbar + mouse.

**Comment by grokys** [comment]
> This shows the issue more clearly (scrolling with mouse pointer and thumb):

Yes, this is intended. When the extent changes due to the estimated size of the unrealized items changing, either the viewport needs to jump (as before) or the scrollbar needs to jump. The scrollbar jumping is a lot less jarring! The same thing happens with chrome, e.g. http://googlechromelabs.github.io/ui-element-samples/infinite-scroller/

**Comment by grokys** [comment]
> This makes impossible to scroll entire list using scrollbar + mouse.

If the window is fullscreen, yes. One can still release the button and continue scrolling though.

**Comment by robloo** [comment]
>>This shows the issue more clearly (scrolling with mouse pointer and thumb):
>
>Yes, this is intended, and mentioned in the description. When the extent changes due to the estimated size of the unrealized items changing, either the viewport needs to jump (as before) or the scrollbar needs to jump. The scrollbar jumping is a lot less jarring! The same thing happens with chrome, e.g. http://googlechromelabs.github.io/ui-element-samples/infinite-scroller/

I see this other places as well. However, the thumb size does NOT reduce again while dragging.

As can be seen here: https://github.com/AvaloniaUI/Avalonia/pull/10892#issuecomment-1497934145 the thumb reduces its size when scrolling down as the content height estimates are increased. However, when scrolling back up the thumb reduces its size again. This behavior I don't usually see in other frameworks. Instead, as the scroll progresses (but the thumb is NOT released) the extent height estimates are continuously improved the more items are realized. The current implementation is forgetting the size of items it has already realized.

**Comment by grokys** [comment]
> as the scroll progresses (but the thumb is NOT released) the extent height estimates are continuously improved the more items are realized. The current implementation is forgetting the size of items it has already realized

Correct. This PR bases the extent size on the elements that are currently realized. It does not attempt to remember the sizes of unrealized elements: I've not even researched the best way to do this yet.

**Comment by robloo** [comment]
> This PR bases the extent size on the elements that are currently realized. It does not attempt to remember the sizes of unrealized elements: I've not even researched the best way to do this yet.

The general principles are these:
 1. Make a best-guess for extent size based on realized elements so far
 2. As more items are realized (more information is available) continuously improve that extent size estimate.

In this way the algorithm is stable and mathematically approaches the exact extent size. So thumb size won't be unstable either -- it will continuously get more accurate.

You already have part 1 done. To do part 2 you essentially need a cache of all realized item heights so far. This cache needs to be updated as items are 1) Realized 2) Removed from the control 3) Item height changes. Extent size is then calculated:

```
Estimated_Extent_Height = Total_Cached_Item_Height + (Average_Cached_Item_Height * (Total_Item_Count - Cached_Item_Count))
```

Doing a simple/arithmetic average of item height is necessary for later optimizations. Otherwise, I might try a geometric average.

If you implement the cache as a dictionary<item, height> it is easiest but will require the most memory. You also need to keep a cached total height and total item count around and recalculate that. This is likely too much overhead so it can probably be simplified with just keeping the sum and total components. That said, it may ultimately be required because you need to know exactly which item heights have already been taking into account.

 * Total_Cached_Item_Height : This is the height of ALL realized items so far. It is continuously updated.
 * Cached_Item_Count : This is just the count of all realized items so far. It is updated in sync with Total_Cached_Item_Height.

Updating these two variables and the dictionary cache must be done in the three cases described above. That is where things get difficult and you probably know better than me what is possible.

I would also not monitor for item size changes directly. I would simply check as an item is shown if the height now differs from what was last recorded and update the cache accordingly. That would require a dictionary-type approach. I think the other two cases are fairly straightforward.

Anyway, these are just ideas. They might help, they might not.

**Comment by robloo** [comment]
@jp2masa I agree a simple moving average is worth a try just to see what it looks like. It might be good enough.

With continuous removing items or very significant item height differences I'm a little skeptical as this moving average may take a long time to be accurate again. It is stable though and will approach "almost correct" extent height. I think the moving average would just need to be cleared on list/collection reset to fix most of those concerns.

In practice it might be fine.

**Comment by grokys** [comment]
> you essentially need a cache of all realized item heights so far

This is the obvious/naive way to do it, and something I've considered of course. I dismissed it however as it will lead to potentially unbounded allocations for infinite scrolling lists; even in cases where all of the items are of the same size.

> A cheap alternative is to consider some kind of moving average

I tried a moving average in a previous iteration of this feature and wasn't happy with the results, precisely because in cases with many items of similar heights with a few items with wildly different heights, I found that the moving average can actually make things worse. It would be worth trying it again though now that the changes in this PR are done as some of the other changes here might make the result more acceptable.

**Comment by jp2masa** [comment]
> Either way, IMO this PR improves things dramatically and extent estimation is orthogonal to the changes here.

Yes, this PR is awesome as it is.

> I tried a moving average in a previous iteration of this feature and wasn't happy with the results, precisely because in cases with many items of similar heights with a few items with wildly different heights, I found that the moving average can actually make things worse. It would be worth trying it again though now that the changes in this PR are done as some of the other changes here might make the result more acceptable.

If it doesn't work, maybe another cheap alternative is to use a Kalman filter. I have no idea if it would work well in this case, and the quality of the model is very important to achieve good results.

I would start with a simple model like:

$\mu_{n + 1} = \mu_n + w_n$
$y_n = \mu_n + v_n$

where $y_n$ is the arranged container height, and $n$ can advance on every arrange for example.

The algorithm, which for this simple model wouldn't even need matrices, is described for example on wikipedia: https://en.wikipedia.org/wiki/Kalman_filter#Details. The main advantage of this method is that it is computationally cheap, and the model can be adjusted as needed. The model isn't always easy to design though...

I have one question: there's no guarantee that when realizing container n all containers 0, ..., n - 1 were realized and arranged, right? Because that could simplify things a lot, but I guess it breaks performance.

**Comment by wieslawsoltes** [comment]
@grokys Seems there are invalidation issue, when switching between views the SelectingItemsControl with VirtualizingStackPanel does not update the view. Repro: https://github.com/wieslawsoltes/ChatGPT/blob/852de17d96d03a9929c5785eed0d8ef319035259/src/ChatGPT.UI/Views/Chat/ChatView.axaml#L35

https://user-images.githubusercontent.com/2297442/230587735-3be0dcc6-c38c-4f48-991b-18788107ae29.mp4

**Comment by wieslawsoltes** [comment]
> > I have one question: there's no guarantee that when realizing container n all containers 0, ..., n - 1 were realized and arranged, right?
> 
> Nope: imagine you're scrolled to the top and press the "End" button. The containers between the first page and the last page won't be realized.
> 
> > Seems there are invalidation issue, when switching between views the SelectingItemsControl with VirtualizingStackPanel
> 
> Ok, will take a look. Unfortunately GhatGPT is illegal in my country so will have to sign up for a VPN I guess! Unless you have a simple repro?

You don't need run ChatGPT using api, you can just add messages (click on left icon and add message).

**Comment by msneijders** [comment]
tested my real-world use case using this PR (which looks like https://github.com/AvaloniaUI/Avalonia/issues/10367 -- a listbox with a few dozen items of equal height, and user can 'expand' an item showing its details).

And the issues I noted are fixed -- good step forward!

About the scrollbar jumps because of size estimates: in my use case its a lot more erratic, as many of my items are small and a few can be large. Not something you can improve with a better estimation algorithm I think.
Would it make sense if I could somehow provide data about item sizes for a specific use case, so it would not have to make an estimate? Or should I than just create a custom virtualizingpanel?

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0033006-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Pull request merged**
