### PR TITLE
Removed outdated comment in PR template

### PR DESCRIPTION
**Pull request by jp2masa**

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0023036-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by maxkatz6** [comment]
Biggest breaking changes are still added there
https://github.com/AvaloniaUI/Avalonia/wiki/Breaking-Changes

**Comment by jp2masa** [comment]
Right, but only maintainers can edit it, so I think this comment is no longer relevant to the PR submitter.

**Comment by maxkatz6** [comment]
Hm, makes sense

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0023048-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0023054-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
