### PR TITLE
Add text box clipboard events

### PR DESCRIPTION
**Pull request by maxkatz6**
## What does the pull request do?
Adds:
```csharp
public class TextBox
{
   public event EventHandler<RoutedEventArgs> CopyingToClipboard;
   public event EventHandler<RoutedEventArgs> CuttingToClipboard;
   public event EventHandler<RoutedEventArgs> PastingFromClipboard;
}
```

## UWP API reference:
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.textbox.paste?view=winrt-20348
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.textbox.copyingtoclipboard?view=winrt-20348
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.textbox.cuttingtoclipboard?view=winrt-20348

## Discussion:

These events are ported from UWP, but there are couple of differences:
1. In UWP there are new event arg per event, in this PR I reused single one
2. In UWP instead of 'PastingFromClipboard' they have 'Paste' event. We can't use 'Paste' name, because we already have 'Paste' method. In the same time in UWP they have same 'Paste' method but named differently - 'PasteFromClipboard()'. **We can't have 1to1 API port without breaking changes**.

Also:
~1. In UWP these events are not routed. In our API I also did not make them routed, but simple clr events instead.~
2. At first I used CancelEventHandler, but probably "Cancel" is not right word here.

### CODE REVIEW

**Comment by Gillibald** [comment]
I suggest naming the events `Cutting``Pasting``Copying` the `Clipboard` suffix is a bit redundant in my opinion.

**Comment by maxkatz6** [comment]
@Gillibald personally I would go with 1to1 UWP names to keep it matching with other XAML frameworks as possible. But in this case we already have conflicting names with "Paste" member, so yeah. To match UWP API we would need to change existing method names as well. It shouldn't be a big breaking change though.

On other hand since we already have different names for methods, your proposal seems reasonable and fitting with current API.

Also, I am not sure, but "Pasting*" sounds a bit wrong and ambiguous.

**Review by grokys — APPROVED** [review]
I prefer the naming here to @Gillibald's suggestion and also to UWP's naming, but have no strong opinions. Approving to avoid bikeshedding anyway ;)

**Comment by Gillibald** [comment]
Let's keep it as is 👍

**Pull request merged**
