### PR TITLE
Cleanup runtime platform classes #2

### PR DESCRIPTION
**Pull request by maxkatz6**
## What does the pull request do?

There was an oversight with IRuntimePlatform being still public, when it shouldn't. This PR fixes it + removes some code from there.

Continuing https://github.com/AvaloniaUI/Avalonia/pull/8183

1. Replaces public IDynamicLibraryLoader NativeLibraryEx as it always had single registration.
2. Makes UnmanagedBlob independent internal class (in the future might be replaced with NativeMemory, but it doesn't use mmap IIRC)
3. Makes IRuntimePlatform a private API. Removes timer and blob members from it.
4. Unifies IRuntimePlatform registration across platforms (browser had some hacks before).
5. Seals AppBuilder and removes public ctor from it (AppBuilder.Configure<T> should be used)

## Breaking changes

1. IRuntimePlatform 
Minor breaking change, as IRuntimePlatform wasn't accessible without Locator anyway.
With this, it can be merged either now or for 11.1 without breaking any app.

2. Inheriting AppBuilder and creating it from ctor is not supported anymore.
This one can be an actual breaking change, but I don't see where any app would use it anyway.

### CODE REVIEW

**Comment by kekekeks** [comment]
>Replaces public IDynamicLibraryLoader NativeLibraryEx as it always had single registration.

Technically that might be a problem for out-of-tree backends for obscure environments.

**Comment by maxkatz6** [comment]
> Technically that might be a problem for out-of-tree backends for obscure environments.

In Avalonia specifically, it's used only for OpenGL code. Backends for these obscure environments will likely need their special rendering either way. So I don't think it's an issue for us to solve, at least not until we support these environments officially.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0037097-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Review by kekekeks — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0037239-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0037264-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Pull request merged**
