### PR TITLE
Reduced nesting levels in several places by changing old using statements to block-scoped usings

### PR DESCRIPTION
**Pull request by Lehonti**
## What does the pull request do?
It uses the new syntax for block-scoped `using`s (for `IDisposable`) in order to reduce nesting and make the code more readable

## What is the updated/expected behavior with this PR?
No significant behavior changes

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0037861-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by robloo** [comment]
It's not always an improvement in my opinion to do formatting changes like this. With using blocks specifically they help readability in some cases and scope is very clear. So this is developer preference I think and we probably shouldn't be changing other developer's preference unless we have formatting rules for the entire project in this area.

That said, other formatting-only changes are a clear improvement so that isn't a hard rule either.

**Comment by kekekeks** [comment]
Note that unlike `using` block the `using var` doesn't dispose the object until the control leaves the outer block. So it might be a behavior change in certain cases.

**Comment by kekekeks** [comment]
e. g.
```cs
        using (var x = Disposable.Create(() => Console.WriteLine("Disposed")))
        {
            Console.WriteLine("Step 1");
        }

        Console.WriteLine("Step 2");
```
Produces: Step 1, Disposed, Step 2

The shiny new
```cs
        using var x = Disposable.Create(() => Console.WriteLine("Disposed"));
        Console.WriteLine("Step 1");
        Console.WriteLine("Step 2");
        ```
        Produces: Step 1, Step 2, Disposed

**Comment by Lehonti** [comment]
> Note that unlike `using` block the `using var` doesn't dispose the object until the control leaves the outer block. So it might be a behavior change in certain cases.

I am aware of this. Not all `using` blocks were changed to the new syntax, but only some, and I made sure that their scope continued until the end of the block, or that if the scope was extended, the cost was negligible. Feel free to verify

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0037891-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Pull request closed without merging**
