### PR TITLE
Refatcor: move X11 and FreeDesktop on Linux sub folder

### PR DESCRIPTION
**Pull request by workgroupengineering**
## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

### CODE REVIEW

**Comment by kekekeks** [comment]
Note that those can be used with FreeBSD too.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0037889-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by workgroupengineering** [comment]
> Note that those can be used with FreeBSD too.

what do you suggest to do? leave as it is?

**Comment by robloo** [comment]
They are all "Unix-like" platforms. So Unix might be an alternative folder name.

**Comment by workgroupengineering** [comment]
what do you think of `nix` or `_nix`?

**Comment by kekekeks** [comment]
>They are all "Unix-like" platforms. So Unix might be an alternative folder name.

Note, that
- there is a native implementation of XOrg for Windows with libX11.dll and other stuff
- macOS is "unix-like" too

**Comment by grokys** [comment]
I'd rather we don't move stuff around for the sake of it, especially when there's contention on exactly what "X11" and "Freedesktop" are part of, unless there's some technical reason to do so?

**Comment by robloo** [comment]
I agree the root src directory is getting a bit messy now though. With Wayland and Tizen coming it will get worse.

I always though just a "Platforms" directory would make more sense here. Browser, Windows, Android, X11, FreeDesktop everything would stay as they are but just go in a new parent for now.

**Comment by workgroupengineering** [comment]
the proposal came from this:
immagine

I expected to find the same thing.

I like @robloo 's idea.

**Pull request closed without merging**
