### PR TITLE
Fix Issue3825

### LINKED ISSUE #3825: Changing TextBlock.Text to multiline String causes rendering issue
I've got a TextBlock with text like this: 
```xaml
<TextBlock Text="Original" VerticalAlignment="Center" x:Name="Thing" />
```

From code-behind, if I set the Text to a multi-line string like this:
```cs
Thing.Text = "This is a long line 1\nThis is a long line 2\nThis is a long line 3";
```

The TextBlock will only render the first line fully, while the second line will only visually contain the region that was previously occupied by the original text. Screenshot examples:
image
image

Opening DevTools and inspecting the TextBlock causes it to redraw properly, showing all three lines.

cibuild0006806

### PR DESCRIPTION
**Pull request by VisualMelon**
## What does the pull request do?
Addresses #3825 by fixing the code that determines the `Bounds` of a `GlyphRunNode` so that they take into account the position of the text, rather than assuming it is positioned at `0,-ascent`

## What is the current behavior?
`GlyphRunNodes` are mis-positioned, resulting in incorrect dirty rectangles when the text of a textbox changes to something with multiple lines but the same total height and width as previously, resulting in incorrect rendering of the result.

## What is the updated/expected behavior with this PR?
Text should always render correctly.

## How was the solution implemented (if it's not obvious)?
It should be fairly obvious, but the `_bounds` property is not assigned in `GlyphRun.Initialise` because it wasn't being used and was redundant with `CalculateBounds` as called by the `Bounds` property. The `Bounds` for a `GlyphRun` are now relative to the baseline origin 

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

## Fixed issues
Fixes #3825

I can add tests on request with some guidance.

### CODE REVIEW

**Comment by VisualMelon** [comment]
Err... I'm not sure how that other commit got in there... I'll try to work out what went wrong with that.

**Comment by Gillibald** [comment]
You can soft reset revert unintended changes and force push

**Comment by Gillibald** [comment]
**Before**


**After**

**Review by Gillibald — APPROVED** [review]
Fixes the issue. Still think I should rework how baseline origin works.

**Pull request merged**
