### PR TITLE
Don't allow bindings to private methods

### LINKED ISSUE #2417: Binding Command to method can execute private methods
The private method will be executed.
```C#
private async Task OnOpen()
```
```C#
public async void OnOpen(string path)
```
```XAML
            <MenuItem Header="_Recent" Items="{Binding RecentProjects}">
                <MenuItem.Styles>
                    <Style Selector="MenuItem">
                        <Setter Property="Header" Value="{Binding Name}"/>
                        <Setter Property="Command" Value="{Binding $parent[UserControl].DataContext.Platform.OnOpen}"/>
                        <Setter Property="CommandParameter" Value="{Binding Path}"/>
                    </Style>
                </MenuItem.Styles>
            </MenuItem>
```

### PR DESCRIPTION
**Pull request by Takoooooo**
## What does the pull request do?
Previously when you were binding to the private method using the "method binding" feature it was allowed. Now you will receive a binding error in a log.

Open question:
Should we disallow bindings to internal methods also?

## Fixed issues
Fixes #2417

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0020773-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by kekekeks** [comment]
I'm not sure if it can't be backported since it technically removes a feature and can break existing code.

**Comment by pr8x** [comment]
Binding to internal seems perfectly fine as long as the View and the ViewModel are in the same assembly.

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0020835-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
