### PR TITLE
[Text] [Refactoring] Extract SymbolTextRun from ShapedTextRun

### PR DESCRIPTION
**Pull request by mklts**
This PR is blocked by #9892 . Please look at this PR only after merging of #9892 because diff is bad.

## What does the pull request do?
This is a minor refactoring. Preliminary step to add shaping skipping to improve text build performance.
Currently all text runs is `ShapedTextRun`. That means that shaping is performed with harfbuzz even if it is not needed at all. @Gillibald said that he wants to add a shortcut for this cases that will leave `UnshapedTextRun` in `TextLineImpl`. To make this possible - we've decided to extract `SymbolTextRun` from `ShapedTextRun`, inherit `UnshapedTextRun` from `ShapedTextRun` and make all hit test and selection code to work with `SymbolTextRun`. So the codebase will work with shaped and unshaped text.

## What is the current behavior?
Code works as before. Just code architecture is affected.

## What is the updated/expected behavior with this PR?
I've added a base class as we discussed with @Gillibald. You can merge this PR as is and everything will work as before. Or you can not merge this PR and @Gillibald will add a shaping-shortcut code and fix all todos by editing this PR or making a new one.

## Comments to @Gillibald 
After analysis I've come to an idea that unshaped text can be RTL and bidi - that's why `SymbolTextRun` have so many abstract methods: `Reverse`, `Split`, `TryMeasureCharacters`, `TryMeasureCharactersBackwards`. I did not implement this methods inside `UnshapedTextRun` because this requires shortcut logic. 
I've added 9 "//todo gillibald" in all places where you need to make changes.
Screenshot 2023-01-05 at 21 20 47
Even if this PR will be cancelled - there is still a research done and now we can see that making shaping shortcuts takes a bit more work than we were expected

## Checklist

- [ x] Added unit tests (if possible)?
- [ x] Added XML documentation to any related classes?
- [ x] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Breaking changes / Obsoletions / Deprecations
I think there is none.

### CODE REVIEW

**Comment by Mikolaytis** [comment]
@Gillibald ok, I thought there can be corner cases. Then after dependant PR will be merged and we will see a nice diff we should specify a list of methods/properties that I should put back to `ShapedTextRun` from `SymbolTextRun`. 

Just in case: `BiDiLevel` property was in class before my changes...

**Comment by Gillibald** [comment]
I can see two potential optimizations.

> 1. Skip bidi analysis
> 2. Skip shaping

Bidi analysis can be skipped for text that only contains ASCII

Shaping can be skipped for non complex scripts and if no font features like `liga` are present. In general text that only contains digits is a good candidate for this.

Unshaped text defaults to the paragraph's bidi level

In general skipping shaping should be optional and the TextLineImpl should work with unshaped and shaped runs

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0028290-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by Mikolaytis** [comment]
After some perf profiling I see that there is a lot of perf bottlenecks that's 100x times significant than shaping. Shaping takes just 0.01-0.1% of CPU load, while text enumerations over GraphemeEnumerator and other enumerators are taking 90% of CPU load.

CoerceLength bottleneck:


Enumeration bottlenecks:
Screenshot 2023-01-06 at 22 54 16
Screenshot 2023-01-06 at 22 51 53
Screenshot 2023-01-06 at 22 51 37

harfbuzz pressure:
Screenshot 2023-01-06 at 23 33 11

After this I think I should close this PR and focus on defeating this perf issues. Maybe we will come to this idea a lot later.

**Comment by Mikolaytis** [comment]
Turnes out profiler do not show unmanaged performance. So 0.1% is a bad measurement. In reality there is about 20-40% unmanaged CPU load. Uncnown part of it is harfbuzz.

**Pull request closed without merging**
