### PR TITLE
Move ItemsRepeater to separate package.

### PR DESCRIPTION
**Pull request by grokys**
## What does the pull request do?

Moves `ItemsRepeater` and associated layout classes to a separate `Avalonia.Controls.ItemsRepeater` package:

- [x] Move `ItemsRepeater` to separate project
- [x] Setup creating packages for `Avalonia.Controls.ItemsRepeater`
- [x] Investigate why XAML compiler needs to special-case `ItemsControl` and `ItemsRepeater` in `AvaloniaXamlIlDataContextTypeTransformer` and come up with a generic solution - thanks @maxkatz6 for fixing this!

## Breaking changes

Users of `ItemsRepeater` will have to include a separate package.

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0029183-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by robloo** [comment]
It's still too bad the ItemsRepeater could never be fixed to handle differing height measurement in edge cases and other issues. It would have been great to build on top of it for everything. I get that it doesn't make sense to keep two different concepts like this side-by-side in Avalonia though so it probably is best to separate out.

Anyway, all the ItemsControl-related reworking recently is certainly a lot of great work!

**Comment by danielmayost** [comment]
I already asked this here: #9733, but maybe this is another opportunity to ask:
I'm leaning heavily on `ItemsRepeater` in my project along with my own `AttachedLayouts`, after the `ItemsControl` refactor is there anything that `ItemsRepeater` knows how to do better?

**Comment by timunie** [comment]
I'm using ItemsRepeater bucause I can have several stacked in one huge ScrollViewer with virtualization enabled. If that now also works with ItemsControl, I have no usecase for ItemsRepeater. Can anyone answer this already or should I just create a playground App to try it out?

**Comment by maxkatz6** [comment]
> Investigate why XAML compiler needs to special-case ItemsControl and ItemsRepeater in AvaloniaXamlIlDataContextTypeTransformer and come up with a generic solution

Previously we had discussed, that we need some way to set an attribute which will be able to pass children data type to the template. 
Same for DataGrid which doesn't support it yet. 

If you remove this special case from the compiler, users will need to set DataType explicitly in the template.

**Comment by grokys** [comment]
> after the ItemsControl refactor is there anything that ItemsRepeater knows how to do better

Nothing that comes to mind, other than the fact that currently we only have a virtualizing stack panel implemented for `ItemsControl`.

> I'm using ItemsRepeater bucause I can have several stacked in one huge ScrollViewer with virtualization enabled. If that now also works with ItemsControl, I have no usecase for ItemsRepeater. Can anyone answer this already or should I just create a playground App to try it out?

Yes, `ItemsControl` now uses the effective viewport like `ItemsRepeater` to determine which items to realize so should work when stacked in a `ScrollViewer`. However I admit I've not tested this yet, so your findings would be appreciated!

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0029395-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]

**Comment by timunie** [comment]
> Yes, ItemsControl now uses the effective viewport like ItemsRepeater to determine which items to realize so should work when stacked in a ScrollViewer. However I admit I've not tested this yet, so your findings would be appreciated!

I did a short testing today. Found out it works if you explicitly change `ItemsPanel` to `VirtualizingStackPanel`. I wonder if we want to update the styles to support it out of the box? https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Themes.Fluent/Controls/ItemsControl.xaml#L1

Off-topic: Interesting was that 3,000 items worked quite smooth even without virtualization. Great job!

**Pull request merged**
