### PR TITLE
Implement GroupName for RadioButton

### LINKED ISSUE #1782: Implement GroupName for RadioButton
It`s very usefull to work with different groups of RadioButtons in one parent containers

### PR DESCRIPTION
**Pull request by siegfriedpammer**
Fixes #1782 

It contains a unit test, if you want me to add more, please tell me. I made the new property behave the same as in WPF.

This is my first pull request, so please tell me if there is anything wrong with the way I do things. I will try to adapt my style to this project as much as possible! :)

### CODE REVIEW

**Comment by siegfriedpammer** [comment]
@jmacato Just to confirm: you did see that I changed the implementation? It's just that I "force pushed" the commit in order to remove the legally risky code from the pull request.

**Comment by Gillibald** [comment]
In general Register and Unregister methods went away and their implementation moved to SetGroupName. Still, the code stayed the same. I really don't know how far we can go. This is the reason why I don't have a look at the reference source anymore. It is highly likely that you copy code by accident. The approach with WeakReference is fine but with the general implementation, I am not so sure about the
licensing.

**Comment by siegfriedpammer** [comment]
I am in the process of implementing the feature using a different, although slightly more bloated approach. It will fix a small bug I have in the current implementation as well.

**Comment by siegfriedpammer** [comment]
I pushed a new implementation.

Explanation:

The problem is that this feature is very simple. So finding a completely different way of implementing it is very hard. Basically, what you need to implement this feature are two things:

1. A property to store the GroupName.
2. A centralized list so you can efficiently detect which radio buttons share the same group name.

In order to avoid the simplest implementation used by WPF, I created a RadioButtonGroupManager class that is attached to the IRenderRoot using WeakReferences. Whenever a RadioButton is added to a visual tree, it retrieves and updates the RadioButtonGroupManager of the current visual tree. Whenever a RadioButton is removed from the visual tree, it removes itself.

Note that RadioButtons not attached to a visual tree, but with the GroupName property set, get added to a global manager instance.

This also fixes a bug in my previous implementation where two radio buttons with the same group name, but in different windows would interfere with each other.

The main difference is that WPF uses a global list for all RadioButtons. I use a list for each visual tree.

If Avalonia provides a better mechanism to loosely attach an object to a visual root, I would like to use it instead of my custom and clunky implementation.

**Comment by siegfriedpammer** [comment]
Well, it seems that the pull request did not get updated, because it was closed. Please take a look at my local branch: https://github.com/siegfriedpammer/Avalonia/commit/18f36ab3bc34c0a47e93da5089697851e3bcc099

**Comment by jmacato** [comment]
@siegfriedpammer can you reopen a new PR?

**Pull request closed without merging**
