### PR TITLE
Make the animation display complete

### PR DESCRIPTION
**Pull request by Coloryr**
## What does the pull request do?
https://github.com/AvaloniaUI/Avalonia/discussions/12362

## What is the current behavior?
Correct animation frames

## What is the updated/expected behavior with this PR?
change `CrossFade`

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

### CODE REVIEW

**Comment by Coloryr** [comment]
> @microsoft-github-policy-service agree

**Comment by Coloryr** [comment]
@microsoft-github-policy-service agree

**Comment by Coloryr** [comment]
@microsoft-github-policy-service agree

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0038199-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by Coloryr** [comment]
@dotnet-policy-service agree

**Review by jmacato — APPROVED** [review]

**Pull request merged**
