### PR TITLE
Add a stream binding operator.

### LINKED ISSUE #711: Binding Error in binding to Avalonia.Controls.TextBlock Text Could not find CLR property
I have run into issue with data binding in Avalonia (0.4.1-build2016-alpha).

Log output:
```
ReactiveHistorySample.Avalonia.vshost.exe Error: 0 : Binding: Error in binding to "Avalonia.Controls.TextBlock"."Text": "Could not find CLR property 'Value' on 'line1'"
ReactiveHistorySample.Avalonia.vshost.exe Error: 0 : Binding: Error in binding to "Avalonia.Controls.TextBlock"."Text": "Could not find CLR property 'Value' on 'line2'"
```

Code to reproduce:
https://github.com/wieslawsoltes/ReactiveHistory/blob/4bf4316a7ab78bd32f4ac48a44686c11db98acf4/samples/ReactiveHistorySample.Avalonia/MainWindow.xaml#L49

The issue is present with other binding in linked `MainWindow.xaml` sample, especially for all `.Value` ones I get a lot of log errors `Could not find CLR property`:
```
ReactiveHistorySample.Avalonia.vshost.exe Error: 0 : Binding: Error in binding to "Avalonia.Controls.ContentControl"."Content": "Could not find CLR property 'Value' on 'ReactiveHistorySample.ViewModels.PointShapeViewModel'"
ReactiveHistorySample.Avalonia.vshost.exe Error: 0 : Binding: Error in binding to "Avalonia.Controls.TextBox"."Text": "Could not find CLR property 'Value' on 'start21'"
ReactiveHistorySample.Avalonia.vshost.exe Error: 0 : Binding: Error in binding to "Avalonia.Controls.ContentControl"."Content": "Could not find CLR property 'Value' on 'ReactiveHistorySample.ViewModels.PointShapeViewModel'"
```

I have also almost same version in WPF:
https://github.com/wieslawsoltes/ReactiveHistory/tree/4bf4316a7ab78bd32f4ac48a44686c11db98acf4/samples/ReactiveHistorySample.Wpf

The WPF version behaves correctly.

### PR DESCRIPTION
**Pull request by grokys**
Previously, when then binding system encountered an `IObservable<>` or a `Task` it automatically tried to subscribe to the observable or task and use the produced value as its value. However this caused problems such as #711.

This PR adds a '^' stream binding operator which informs the binding system that the value should be subscribed to.

This also incedentally renders the previous special case for `IReactiveCommand` unnecessary.

Fixes #711.

### CODE REVIEW

**Comment by grokys** [comment]
cc: @wieslawsoltes

**Comment by wieslawsoltes** [comment]
@grokys Tested with my sample app and it works for bindings with `.Value` from #711.

Not sure about the `^` operator, when I try to use it like this:

``` XAML
<TextBlock Text="{Binding Name^.Value}"/>
```

or this:

``` XAML
<TextBlock Text="{Binding Name^}"/>
```

I get the following exception:

```
OmniXaml.LoadException was unhandled
  HResult=-2146233088
  LineNumber=30
  LinePosition=22
  Message=Error loading XAML: Sprache.ParseException: Parsing failure: unexpected '^'; expected } (Line 1, Column 14); recently consumed: nding Name
   w Sprache.ParserExtensions.Parse[T](Parser`1 parser, String input) w z:\TeamCityAgent\work\52fca6ab21d30618\src\Sprache\ParserOfT.cs:wiersz 51
   w OmniXaml.Parsers.Parser.InstructionParser.ParseMarkupExtension(String valueOfMember)
   w OmniXaml.Parsers.Parser.InstructionParser.<ParseMembersOfObject>d__39.MoveNext()
   w OmniXaml.Parsers.Parser.InstructionParser.<ParseEmptyElement>d__26.MoveNext()
   w OmniXaml.Parsers.Parser.InstructionParser.<ParseElements>d__24.MoveNext()
   w OmniXaml.Parsers.Parser.InstructionParser.<ParseContentPropertyIfAny>d__32.MoveNext()
   w OmniXaml.Parsers.Parser.InstructionParser.<ParseNonEmptyElement>d__27.MoveNext()
   w OmniXaml.Parsers.Parser.InstructionParser.<ParseElements>d__24.MoveNext()
   w OmniXaml.Parsers.Parser.InstructionParser.<ParseCollectionInsideThisProperty>d__34.MoveNext()
   w OmniXaml.Parsers.Parser.InstructionParser.<ParseNestedProperties>d__31.MoveNext()
   w OmniXaml.Parsers.Parser.InstructionParser.<ParseNonEmptyElement>d__27.MoveNext()
   w OmniXaml.Parsers.Parser.InstructionParser.<ParseElements>d__24.MoveNext()
   w OmniXaml.Parsers.Parser.InstructionParser.<ParseCollectionInsideThisProperty>d__34.MoveNext()
   w OmniXaml.Parsers.Parser.InstructionParser.<ParseContentPropertyIfAny>d__32.MoveNext()
   w OmniXaml.Parsers.Parser.InstructionParser.<ParseNonEmptyElement>d__27.MoveNext()
   w OmniXaml.Parsers.Parser.InstructionParser.<ParseElements>d__24.MoveNext()
   w OmniXaml.Parsers.Parser.InstructionParser.<ParseContentPropertyIfAny>d__32.MoveNext()
   w OmniXaml.Parsers.Parser.InstructionParser.<ParseNestedProperties>d__31.MoveNext()
   w OmniXaml.Parsers.Parser.InstructionParser.<ParseNonEmptyElement>d__27.MoveNext()
   w OmniXaml.Parsers.Parser.InstructionParser.<ParseElements>d__24.MoveNext()
   w OmniXaml.Parsers.Parser.InstructionParser.<Parse>d__23.MoveNext()
   w OmniXaml.MemberDependencyNodeSorter.<Sort>d__11.MoveNext()
   w OmniXaml.XmlParser.Parse(IEnumerable`1 xamlNodes)
   w OmniXaml.XmlParser.Parse(IXmlReader stream)
   w OmniXaml.XmlLoader.Load(Stream stream, IParser parser)
  Source=Avalonia.Markup.Xaml
  StackTrace:
       w OmniXaml.XmlLoader.Load(Stream stream, IParser parser)
       w Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Stream stream, Object rootInstance, Uri uri)
       w Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Type type, Object rootInstance)
       w Avalonia.Markup.Xaml.AvaloniaXamlLoader.Load(Object obj)
       w ReactiveHistorySample.Avalonia.MainWindow.InitializeComponent() w C:\DOWNLOADS\GitHub\ReactiveHistory\samples\ReactiveHistorySample.Avalonia\MainWindow.xaml.cs:wiersz 18
       w ReactiveHistorySample.Avalonia.MainWindow..ctor() w C:\DOWNLOADS\GitHub\ReactiveHistory\samples\ReactiveHistorySample.Avalonia\MainWindow.xaml.cs:wiersz 12
       w ReactiveHistorySample.Avalonia.App.Start() w C:\DOWNLOADS\GitHub\ReactiveHistory\samples\ReactiveHistorySample.Avalonia\App.xaml.cs:wiersz 63
       w ReactiveHistorySample.Avalonia.App.Main(String[] args) w C:\DOWNLOADS\GitHub\ReactiveHistory\samples\ReactiveHistorySample.Avalonia\App.xaml.cs:wiersz 35
       w System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       w System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       w Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       w System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       w System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       w System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
       HResult=-2146233088
       Message=Parsing failure: unexpected '^'; expected } (Line 1, Column 14); recently consumed: nding Name
       Source=Sprache
       StackTrace:
            w Sprache.ParserExtensions.Parse[T](Parser`1 parser, String input) w z:\TeamCityAgent\work\52fca6ab21d30618\src\Sprache\ParserOfT.cs:wiersz 51
            w OmniXaml.Parsers.Parser.InstructionParser.ParseMarkupExtension(String valueOfMember)
            w OmniXaml.Parsers.Parser.InstructionParser.<ParseMembersOfObject>d__39.MoveNext()
            w OmniXaml.Parsers.Parser.InstructionParser.<ParseEmptyElement>d__26.MoveNext()
            w OmniXaml.Parsers.Parser.InstructionParser.<ParseElements>d__24.MoveNext()
            w OmniXaml.Parsers.Parser.InstructionParser.<ParseContentPropertyIfAny>d__32.MoveNext()
            w OmniXaml.Parsers.Parser.InstructionParser.<ParseNonEmptyElement>d__27.MoveNext()
            w OmniXaml.Parsers.Parser.InstructionParser.<ParseElements>d__24.MoveNext()
            w OmniXaml.Parsers.Parser.InstructionParser.<ParseCollectionInsideThisProperty>d__34.MoveNext()
            w OmniXaml.Parsers.Parser.InstructionParser.<ParseNestedProperties>d__31.MoveNext()
            w OmniXaml.Parsers.Parser.InstructionParser.<ParseNonEmptyElement>d__27.MoveNext()
            w OmniXaml.Parsers.Parser.InstructionParser.<ParseElements>d__24.MoveNext()
            w OmniXaml.Parsers.Parser.InstructionParser.<ParseCollectionInsideThisProperty>d__34.MoveNext()
            w OmniXaml.Parsers.Parser.InstructionParser.<ParseContentPropertyIfAny>d__32.MoveNext()
            w OmniXaml.Parsers.Parser.InstructionParser.<ParseNonEmptyElement>d__27.MoveNext()
            w OmniXaml.Parsers.Parser.InstructionParser.<ParseElements>d__24.MoveNext()
            w OmniXaml.Parsers.Parser.InstructionParser.<ParseContentPropertyIfAny>d__32.MoveNext()
            w OmniXaml.Parsers.Parser.InstructionParser.<ParseNestedProperties>d__31.MoveNext()
            w OmniXaml.Parsers.Parser.InstructionParser.<ParseNonEmptyElement>d__27.MoveNext()
            w OmniXaml.Parsers.Parser.InstructionParser.<ParseElements>d__24.MoveNext()
            w OmniXaml.Parsers.Parser.InstructionParser.<Parse>d__23.MoveNext()
            w OmniXaml.MemberDependencyNodeSorter.<Sort>d__11.MoveNext()
            w OmniXaml.XmlParser.Parse(IEnumerable`1 xamlNodes)
            w OmniXaml.XmlParser.Parse(IXmlReader stream)
            w OmniXaml.XmlLoader.Load(Stream stream, IParser parser)
       InnerException: 
```

**Comment by wieslawsoltes** [comment]
Here is screen recording:


Few issues I have found (not related to this PR):
- at the beginning of recording you can see that `ListBox` width is incorrect (scrollbar is displayed).
- at the end or recording you can see `FIXME!` string in `ListBox`, this is result of this binding `Text="{Binding Name.Value, FallbackValue=FIXME!}"`, probably related to issue with `SelectedItem` I have described also in #711, same happens when I tested with `Core2D` using this PR

**Comment by grokys** [comment]
Ah yeah the `OmniXaml.LoadException` is due to https://github.com/SuperJMN/OmniXAML/issues/111. I forgot about that. Will need to patch up our OmniXAML even further. I think at this point, it's been so long without bug fixes (there have been no bug fixes since April AFAICS) that we can consider OmniXAML unmaintained. Is that fair @SuperJMN? If so, we should seriously consider a move to PortableXAML.

For the other two bugs, would you have time to put together a minimal repro and file bugs? If not, I can take a look at your project as time permits.

**Comment by grokys** [comment]
Ok, the `^` character should now be accepted in markup extensions.

**Comment by wieslawsoltes** [comment]
This works now:

``` XAML
<TextBlock Text="{Binding Name^, FallbackValue=FIXME!}"/>
```

but this gives me only `FallbackValue`:

``` XAML
<TextBlock Text="{Binding Name^.Value, FallbackValue=FIXME!}"/>
```

**Comment by wieslawsoltes** [comment]
@grokys As for the bugs, no easy repro as it need to define VM. But both are easily reproducible in `Core2D` and in `ReactiveHistory` projects, also see my comments in #711 how to reproduce:
https://github.com/AvaloniaUI/Avalonia/issues/711#issuecomment-244473217
https://github.com/AvaloniaUI/Avalonia/issues/711#issuecomment-244477871

**Comment by grokys** [comment]
> `<TextBlock Text="{Binding Name^.Value, FallbackValue=FIXME!}"/>`

What type is `Name`? An observable? This should work (there's a unit test for it at least: https://github.com/AvaloniaUI/Avalonia/blob/b0e0596500daa237db46a95355657bb3d75c874e/tests/Avalonia.Markup.UnitTests/Data/ExpressionObserverTests_Observable.cs#L54)

Any idea what's different about your case from the unit test?

**Comment by wieslawsoltes** [comment]
Yes its observable:

``` C#
public ReactiveProperty<string> Name { get; set; }

public class ReactiveProperty<T> : IReactiveProperty<T>, IReactiveProperty, IHasErrors, IObservable<T>, IDisposable, INotifyPropertyChanged, INotifyDataErrorInfo, IReadOnlyReactiveProperty<T>, IReadOnlyReactiveProperty
```

and I get this error:

```
ReactiveHistorySample.Avalonia.vshost.exe Error: 0 : Binding: Error in binding to "Avalonia.Controls.TextBlock"."Text": "Could not find CLR property 'Value' on 'line1'"
```

here is full code:
https://github.com/wieslawsoltes/ReactiveHistory/blob/master/samples/ReactiveHistorySample.ViewModels/LineShapeViewModel.cs#L16

**Comment by grokys** [comment]
Hmmm, but `Name` is an `IObservable<string>` which means that `Name^` will bind to `string` and `string` doesn't have a `Value` property.

**Comment by wieslawsoltes** [comment]
@grokys I see. I do not have currently use case for this scenario (using the `^` operator). Anyway changes from this PR have fixed my issues with observables.

**Comment by grokys** [comment]
@wieslawsoltes ok, I'm going to merge this PR. #711 actually details a few different issues but I think this fixes the main one. I will look into the others shortly.

**Comment by wieslawsoltes** [comment]
@grokys ok.

**Pull request merged**
