### PR TITLE
Cleanup and small optimization to GeometryDrawing

### PR DESCRIPTION
**Pull request by MarchingCube**
## What does the pull request do?

First commit fixes one not needed allocation and second one adds doc comments to both `Drawing` and `GeometryDrawing`.

## What is the current behavior?

Each call to `GeometryDrawing.GetBounds` allocates a ton due to `Pen` being an `AvaloniaObject`.

## What is the updated/expected behavior with this PR?

No extra allocations when calling `GetBounds`.

## How was the solution implemented (if it's not obvious)?

Also changed API compat since `Geometry` functions required `Pen` and not `IPen` for some reason.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

### CODE REVIEW

**Comment by Gillibald** [comment]
I think we should get rid of IPen usage in public API in the near future and instead use StrokeBrush etc.

**Comment by MarchingCube** [comment]
How do you want to deal with passing info like stroke thickness, dashes, etc?

**Comment by MarchingCube** [comment]
Current problem is that constructing `Pen` is so expensive it turns into a bottleneck almost instantly. If we construct it internally perhaps we can also simplify it.

**Comment by MarchingCube** [comment]
@Gillibald Currently both Skia and D2D backends need a `Pen` to just compensate for thickness. I think before renderer rework we might not want to change too much in rendering APIs itself.

**Review by grokys — APPROVED** [review]

**Pull request merged**
