### PR TITLE
Generate more OpenGL functions and uncomment some consts

### PR DESCRIPTION
**Pull request by nesrak1**
## What does the pull request do?

The `GlInterface` class is missing a lot of GL functions, including basic ones like `glUniform3f` or `glUniform1i`. Additionally, many GL consts were commented out in #8580 due to size reasons, but there are many consts that are common that aren't available anymore.

## What is the current behavior?

The OpenGL support works as far as I can tell, it's just missing a lot of functions and consts.

## What is the updated/expected behavior with this PR?

I've added all of the GLES2 functions and uncommented all of the consts from this file: https://github.com/KhronosGroup/OpenGL-Registry/blob/main/api/GLES3/gl3.h. This should cover most basic usages for now. I am not using any from GLES3 and the existing functions from 3 have been kept the way they were.

The amount of new uncommented consts is pretty low. In total, there's about 300 that were in the header file compared to the ~5500 lines in `GlConsts.cs`, so the size shouldn't have increased that much.

Since I generated the C# code directly from the header file, some types that were originally `IntPtr` (I'm not sure how it was decided what was `IntPtr` and what was a normal pointer) are now all just normal pointers, except when the type was `GLintptr`. There's also exceptions for `Uniform2fv`-`Uniform4fv` and `UniformMatrix4fv` to use `Vector2`-`Vector4` and `Matrix4x4` respectively. I'm not sure if more of the functions need exceptions or any pointers need to turn back into `IntPtr`.

`GetIntegerv` and `GetStringNative` are commented out since they're defined in `GlBasicInfoInterface`. It feels a little weird keeping those two specifically in there.

I've also added some sliders to the OpenGL sample to show `Uniform3fv` working.

## How was the solution implemented (if it's not obvious)?

See above. Generated new functions from a Python script reading `gl3.h`.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Breaking changes

This breaks anything that was previously using `IntPtr` and now using a real pointer. All other wrapper functions have been left as is.

### CODE REVIEW

**Comment by nesrak1** [comment]
@dotnet-policy-service agree

**Comment by kekekeks** [comment]
Sorry, but the limited number of functions is there by design. The existing bindings are there for the internal needs of our OpenGL backend, not for user apps. We were even considering to remove some that are only required for the sample in our control catalog.

The reasoning is that we need to keep the OpenGL backend support reasonably small (<200KB dll size) and can't maintain a proper set for OpenGL(ES) bindings anyway.

Please, consider using Silk.NET instead.

**Comment by kekekeks** [comment]
You can convert GlInterface into Silk.NET  API wrapper via `GL.GetApi(avaloniaGl.GetProcAddress);`

**Comment by nesrak1** [comment]
That's a bit confusing since the control catalog sample makes it seem like it's showcasing off what you can do with the OpenGL control, but maybe I'm missing the purpose of the catalog.

**Comment by kekekeks** [comment]
Here is an example of using Silk.NET with `OpenGlControlBase` - https://github.com/kekekeks/Avalonia-Silk.NET-Example/blob/bfd0e0385f8125d3ce5d0e3a9f9c597863535879/AvaloniaSilkExample/Gl/SilkNetExample.cs#L35-L63

We've implemented the teapot without referencing Silk.NET to avoid bringing extra dependencies to the ControlCatalog.

**Comment by nesrak1** [comment]
> We've implemented the teapot without referencing Silk.NET to avoid bringing extra dependencies to the ControlCatalog.

Ah, that makes sense then. I'll check it out, thanks.

**Pull request closed without merging**
