### PR TITLE
List virtualization fixes

### PR DESCRIPTION
**Pull request by grokys**
## What does the pull request do?

Fixes some issues with the new virtualization system introduced in #9677:

- When items are removed and the list is scrolled, ensure that we cause the extent to change by adjusting the size returned from `VirtualizingStackPanel.MeasureOverride`. This was broken previously due to two problems:
  - We weren't setting `_startUUnstable` when items were removed before the realized range
  - We were clamping the stand and end indexes too late when calculating the viewport, meaning that `firstIndexU` was calculated with a non-clamped index, which caused the items to be realized in the wrong position
- There was a problem in `ScrollContentPresenter` whereby if the viewport or extent were changed the offset wasn't being coerced, leading to an offset beyond the extent of the scroll

### CODE REVIEW

**Comment by adirh3** [comment]
@grokys maybe it's a bit off topic for this PR, but my app crashes on index out of range due toto this method giving a negative index using ItemsControl - https://github.com/AvaloniaUI/Avalonia/blob/7da9bb9d434ecb70e5ef2fc7af768067c43709f1/src/Avalonia.Controls/VirtualizingStackPanel.cs#LL491C28-L491C28

**Comment by grokys** [comment]
@adirh3 i don't suppose you have a minimal repro do you? Hard to know what's going wrong from your description.

**Comment by adirh3** [comment]
> @adirh3 i don't suppose you have a minimal repro do you? Hard to know what's going wrong from just your description.

As usual I can't repro anything outside of my app :/
The issue is that `GenerateElements` calls `GetOrCreateElement` with a negative `index` which cause an `OutOfRangeException`.
I will try to make a repro but TBH I doubt it will happen in empty app 😅

**Review by maxkatz6 — APPROVED** [review]
Let's merge it, and see if somebody will find a repro for the master branch.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0030261-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by grokys** [comment]
In the absence of a repro, a stacktrace might help.

**Comment by timunie** [comment]
@grokys is this maybe related? https://github.com/AvaloniaUI/Avalonia/issues/10399#issuecomment-1436663282 

If so, the issue seems not to be solved yet.

**Comment by adirh3** [comment]
Will give stack trace later today.
FYI I reproduced this issue using the nightly build of thus PR, so it definitely did not solve it.

**Comment by adirh3** [comment]
@grokys @maxkatz6  Sorry took longer than expected - 
image
More debug info -
image

Not sure if it makes sense, but I will try to add `|| index < 0` to the if return condition and see if that helps without generating new bugs.

**Pull request merged**
