### PR TITLE
[WIP][Windows] Use InputScope API for ITextInputMethodImpl.SetOptions

### PR DESCRIPTION
**Pull request by Gillibald**
## What does the pull request do?

Use https://learn.microsoft.com/en-us/windows/win32/api/inputscope/nf-inputscope-setinputscope to notify Windows about requested input scope

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

### CODE REVIEW

**Comment by Gillibald** [comment]
#10136

**Comment by Gillibald** [comment]
Needs to be tested with an actual touch device

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0034322-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by maxkatz6** [comment]
@Gillibald api is executed, but it doesn't seem to work at all.
Animation

**Comment by Gillibald** [comment]
```
If you call this method on a window (hwnd parameter) that has not been associated with a Document Manager, then no text service notifications are sent to interested clients (such as the touch keyboard) that may want to respond to the scope change.
```

So supporting this is a more involved change

**Comment by Gillibald** [comment]
Closing this because the required text services implementation requires too many resources at the moment

**Pull request closed without merging**
