### PR TITLE
DataGrid - Avoid scrollbar overlapping border

### LINKED ISSUE #3511: DataGrid - Scrollbar is overlapping border
If the border of the DataGrid is used and the scrollbar becomes visible, it overlaps the border.

## XAML
```
<DataGrid .....
BorderBrush="{StaticResource ThemeBorderMidBrush}"
BorderThickness="1"/>
```
## Result
image

### PR DESCRIPTION
**Pull request by Symbai**
If border of the DataGrid is used the scrollbar currently overlaps the border. See screenshots below.

## What is the current behavior?
Before

## What is the updated/expected behavior with this PR?
After

## Fixed issues
Fixes #3511

### CODE REVIEW

**Review by grokys — APPROVED** [review]
Thanks so much for this @Symbai ! `DataGrid` is in much need of some love!

**Review by grokys — CHANGES_REQUESTED** [review]
Oh actually, I spoke too soon. A seeminly unrelated change to `ComboBox` seems to have crept in?

**Comment by grokys** [comment]
Hmm, that change seems to be part of #3513. Once that PR is merged, that change should disappear from this PR.

**Comment by grokys** [comment]
Um... actually now #3513 has been merged, this PR is empty. I could have sworn that I saw a change to the `DataGrid` style in here before, but looking at the commits I can't see it. Did I imagine it? Did you open a PR with the wrong branch?

Going to close this as it's empty anyway...

**Comment by Symbai** [comment]
Sorry @grokys I am not a Github expert and created the pull requests via Github clone and direct file editing through the browser after tested the changes locally.

I noticed some trouble when creating two different changes and creating two different pull requests. It could very likely be that I've done something wrong.

Is the change now merged or do I have to create a new pull request?

**Comment by Gillibald** [comment]
In general you should create a new branch per PR so things stay separate. The branch can be deleted after your work got merged.

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-and-deleting-branches-within-your-repository

**Comment by grokys** [comment]
@Symbai I merged the changes in #3513 but if you could submit a new PR with the `DataGrid` changes that would be appreciated. I'd personally recommend using GitHub desktop to create the PR: https://help.github.com/en/desktop

You'll want to do something like this:

- Fork the Avalonia repository (you seem to have already done this)
- [Clone your fork](https://help.github.com/en/desktop/contributing-to-projects/cloning-and-forking-repositories-from-github-desktop) to your machine
- [Create a branch for your changes](https://help.github.com/en/desktop/contributing-to-projects/creating-a-branch-for-your-work)
- Make the changes
- [Commit the changes to your branch](https://help.github.com/en/desktop/contributing-to-projects/committing-and-reviewing-changes-to-your-project)
- [Open a pull request for the branch](https://help.github.com/en/desktop/contributing-to-projects/creating-a-pull-request)

**Pull request closed without merging**
