### PR TITLE
Fix palette TryGetResource code

### PR DESCRIPTION
**Pull request by maxkatz6**
## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0036885-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0036903-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by timunie** [comment]
@maxkatz6 is this connected to https://github.com/AvaloniaUI/Avalonia/issues/11640? if so, maybe @amwx  wants to take a look at it / give it a try. I believe he had some issues with this in FluentAvalonia as well.

**Comment by maxkatz6** [comment]
No, it's our FluentTheme specific bug

**Review by emmauss — APPROVED** [review]

**Pull request merged**
