### PR TITLE
Fix Exception when window is closed via Close() Method

### PR DESCRIPTION
**Pull request by danwalmsley**
## What does the pull request do?

Fixes exception when window is closed programatically.

## What is the current behavior?

Close() causes Window to be detached twice.

## What is the updated/expected behavior with this PR?

Only detach once.

### CODE REVIEW

**Comment by Gillibald** [comment]
This "fix" is wrong. The platform implementation should raise closed and that calls: https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/TopLevel.cs#L109
Nothing else should call HandleClosed

**Comment by kekekeks** [comment]
If mocks aren't triggering Closed event properly, then mocks have to be fixed to match the actual backends. We shouldn't be adding workarounds for broken mocks in the framework code

**Comment by MarchingCube** [comment]
I agree as well that current solution is incorrect. Especially because `HandleClosed` is virtual so people implementing their own windows will still get two calls to it and similar bugs might surface again.

**Comment by danwalmsley** [comment]
For context, I reset back to the correct fix as confirmed by discussion, so the conversation refers to now missing commits.

**Review by grokys — APPROVED** [review]

**Pull request merged**
