### PR TITLE
feat(Style): Allow to using attached properties in attribute selector

### LINKED ISSUE #4183: [Bug] Unable to use attached properties in attribute selector
Test to reproduce the issue:
```csharp
[Fact]
public void Style_Can_Use_Attached_Property_In_Attribute_Selector()
{
    using (UnitTestApplication.Start(TestServices.StyledWindow))
    {
        var xaml = @"
            <Window xmlns='https://github.com/avaloniaui'
                            xmlns:x='http://schemas.microsoft.com/winfx/2006/xaml'>
                <Window.Styles>
                    <Style Selector='Button[(ToolTip.IsOpen)=True]'>
                        <Setter Property='Background' Value='Red'/>
                    </Style>
                </Window.Styles>
            </Window>";
        var loader = new AvaloniaXamlLoader();

        // Should not throw XamlIlParseException
        _ = loader.Load(xaml);
    }
}
```
```
  Message: 
    XamlIl.XamlIlParseException : Unable to parse selector: Expected '=', got '(' (line 5 position 30) Line 5, position 30.
  Stack Trace: 
    AvaloniaXamlIlSelectorTransformer.Transform(XamlIlAstTransformationContext context, IXamlIlAstNode node) line 122
    Visitor.Visit(IXamlIlAstNode node) line 100
    XamlIlAstNode.Visit(IXamlIlAstVisitor visitor) line 56
    XamlIlAstNode.VisitList[T](IList`1 list, IXamlIlAstVisitor visitor) line 74
    XamlIlAstXamlPropertyValueNode.VisitChildren(IXamlIlAstVisitor visitor) line 56
    XamlIlAstNode.Visit(IXamlIlAstVisitor visitor) line 60
    XamlIlAstNode.VisitList[T](IList`1 list, IXamlIlAstVisitor visitor) line 74
    XamlIlAstObjectNode.VisitChildren(IXamlIlAstVisitor visitor) line 78
    XamlIlAstNode.Visit(IXamlIlAstVisitor visitor) line 60
    XamlIlAstTransformationContext.Visit(IXamlIlAstNode root, IXamlIlAstTransformer transformer) line 117
    XamlIlCompiler.Transform(XamlIlDocument doc, Boolean strict) line 74
    AvaloniaXamlIlCompiler.ParseAndCompile(String xaml, String baseUri, IFileSource fileSource, IXamlIlTypeBuilder tb, IXamlIlType overrideRootType) line 117
    AvaloniaXamlIlRuntimeCompiler.LoadSreCore(String xaml, Assembly localAssembly, Object rootInstance, Uri uri, Boolean isDesignMode) line 130
    AvaloniaXamlIlRuntimeCompiler.LoadSre(String xaml, Assembly localAssembly, Object rootInstance, Uri uri, Boolean isDesignMode) line 100
    AvaloniaXamlIlRuntimeCompiler.Load(Stream stream, Assembly localAssembly, Object rootInstance, Uri uri, Boolean isDesignMode) line 191
    AvaloniaXamlLoader.Load(Stream stream, Assembly localAssembly, Object rootInstance, Uri uri) line 98
    AvaloniaXamlLoader.Load(String xaml, Assembly localAssembly, Object rootInstance) line 83
    StyleTests.Stylr_Can_Use_Attached_Property_In_Attribute_Selector() line 266
```

### LINKED ISSUE #6984: [XamlIl] Unable use custom attached property in Style Selector
**Describe the bug**
When use custom attached propery in Style Selector the XamlIL report:
```bash
Error	XAMLIL	Unable to parse selector: Expected '=', got '|' Line 14, position 6.	AA2	...\MainWindow.axaml	14	
```

**To Reproduce**

1. Create Avalonia MVVM project
2. Define class like this
    ```csharp
        namespace AA2
        {
            public class Auth
            {
                  public readonly static AttachedProperty<string> NameProperty =
                      AvaloniaProperty.RegisterAttached<Auth, AvaloniaObject, string>("Name");
          
                  public static string GetName(AvaloniaObject avaloniaObject) =>
                      avaloniaObject.GetValue(NameProperty);
          
                  public static void SetName(AvaloniaObject avaloniaObject, string value) =>
                      avaloniaObject.SetValue(NameProperty, value);
            }
        }
    ```
3. In MainWindow.axaml add following line
    ```xaml
    <Window xmlns="https://github.com/avaloniaui" ....
                    xmlns:l="using:AA2"
                    l:Auth.Name="{Binding SelectedAuth}">
        <Window.Styles>
          <Style Selector="Window[l|Auth.Name=Admin]">
            <Setter Property="Background" Value="Green"/>
            <Setter Property="Foreground" Value="White"/>
            ....
          </Style>
        </Window.Styles>
        ....
    </Window>
    ```
4. Build
5. See error in Errors List

**Expected behavior**
Selector Style Selector supports namespace

**Screenshots**

**Desktop (please complete the following information):**

- OS:  Windows
- Version 32fe95a2cc428e165b6ef89337a96e15fda65239

**Additional context**

### PR DESCRIPTION
**Pull request by workgroupengineering**
## What does the pull request do?

Allow to using attached properties in attribute selector

## What is the current behavior?

XamlIl  trhow exception: `Unable to parse selector: Expected '=', got '('  `  or `Unable to parse selector: Expected '=', got '|'` when using attached property

## Checklist

- [x] Added unit tests (if possible)?
- [x] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Fixed issues

Fixes #4183 
Fixes #6984

### CODE REVIEW

**Comment by Sorien** [comment]
is really needed to have those '(' ')' ? 

`Button[(ToolTip.IsOpen)=True]` -> `Button[ToolTip.IsOpen=True]`

**Comment by workgroupengineering** [comment]
> is really needed to have those '(' ')' ?
> 
> `Button[(ToolTip.IsOpen)=True]` -> `Button[ToolTip.IsOpen=True]`

it is only for consistency with the syntax of the BindingExpression

**Review by maxkatz6 — APPROVED** [review]
LGTM

**Comment by maxkatz6** [comment]
We might have another discussion if attached properties should be allowed in the selector without '(', ')', but as for now it's better to keep it compatible with bindings and maybe more complex property paths in this selector (if we need it)

**Pull request merged**
