### PR TITLE
Use ID2D1BitmapRenderTarget for D2D render layers (Option 2)

### PR DESCRIPTION
**Pull request by grokys**
We previously were using `RenderTargetBitmap`s for render layers and in the D2D backend. These are backed with WIC bitmaps, which need to be format converted on every frame so performance was bad.

This PR adds an `IDrawingContextImpl.CreateLayer` method which on the D2D backend uses `ID2D1RenderTarget::CreateCompatibleRenderTarget` to create layers that are backed by `ID2D1BitmapRenderTargets` so no format conversion is needed.

This PR is similar to #1140, except this adds the `CreateLayer` method to `IDrawingContextImpl` instead of `IRenderTarget` as @kekekeks suggested in that PR. Only one of them should be chosen.

### CODE REVIEW

**Comment by kekekeks** [comment]
We probably need `IDrawingContext::IsCompatible(IRenderTargetBitmapImpl impl)` to check if layer can be used with the current Direct2D render target, since it can be gone and recreated between different calls to `CreateDrawingContext`.

**Comment by grokys** [comment]
Yeah I was thinking about this:

- Firstly, is it even possible to get this information in D2D?
- Secondly - I think could do this a little differently. What I was thinking is that `CreateDrawingContext` shouldn't recreate the render target - that should be a separate step. If we did it this way then we wouldn't need to be able to check compatibility because the caller would _know_ that it needs to throw away its render targets.

Thoughts?

**Comment by kekekeks** [comment]
>Firstly, is it even possible to get this information in D2D

Just save the `RenderTarget` it was created with somewhere and check if it's the same. We are always recreating it manually, so it should work.

Not sure about that separate step idea.

**Comment by grokys** [comment]
Thing is, most of the time you _can_ re-use the layers, and in the cases we can't, we crash before we get chance to draw an invalid RTB anyway. I think we should leave the decision for now and address it when we come to fix the crash on render target recreation, does that sound like a plan?

**Review by kekekeks — APPROVED** [review]
LGTM

**Pull request merged**
