### PR TITLE
Fix iOS Dispatcher

### LINKED ISSUE #11696: iOS Animation
**Brief Description**

We are trying to draw a modal with animation for opacity and some properties.
The animation is work great on Windows and Android but not in iOS it animate like a 1 framerate

**To Reproduce**
```xaml
 <Panel x:Name="PART_Container">
 					<Rectangle x:Name="PART_Background" Fill="Black">
 						<Rectangle.Styles>
 							<Style Selector="Rectangle#PART_Background">
 								<Setter Property="Opacity" Value="0"/>
 							</Style>
 							<Style Selector="controls|ModalControl[IsOpen=True] /template/ Rectangle#PART_Background">
 								<Style.Animations>
 									<Animation Duration="{Binding RelativeSource={RelativeSource TemplatedParent}, Path=Speed}" FillMode="Both">
 										<KeyFrame Cue="0%">
 											<Setter Property="Opacity" Value="0.0"/>
 										</KeyFrame>
 										<KeyFrame Cue="100%">
 											<Setter Property="Opacity" Value=".6"/>
 										</KeyFrame>
 									</Animation>
 								</Style.Animations>
 							</Style>
 							<Style Selector="controls|ModalControl[IsOpen=False] /template/ Rectangle#PART_Background">
 								<Style.Animations>
 									<Animation Duration="{Binding RelativeSource={RelativeSource TemplatedParent}, Path=Speed}" FillMode="Both">
 										<KeyFrame Cue="0%">
 											<Setter Property="Opacity" Value="0.6"/>
 										</KeyFrame>
 										<KeyFrame Cue="100%">
 											<Setter Property="Opacity" Value="0"/>
 										</KeyFrame>
 									</Animation>
 								</Style.Animations>
 							</Style>
 						</Rectangle.Styles>
 					</Rectangle>
 
 					<ContentPresenter
 						Content="{TemplateBinding Content}"/>
 				</Panel>
```

```xaml
<Style Selector="controls|ModalControl[IsOpen=False]">
		<Style.Animations>
			<Animation Duration="0:0:0.3" >
				<KeyFrame Cue="0%">
					<Setter Property="IsVisible" Value="True"/>
				</KeyFrame>
				<KeyFrame Cue="100%">
					<Setter Property="IsVisible" Value="False"/>
				</KeyFrame>
			</Animation>
		</Style.Animations>
	</Style>
	<Style Selector="controls|ModalControl[IsOpen=True]">
		<Setter Property="IsVisible" Value="True"/>
	</Style>
```

**Expected behavior**
It should work like Windows and Android without any issue

- OS: iOS 16.4
- Version 11.0.0-rc1.1

**Additional context**

### LINKED ISSUE #13029: Problems with transitions on iOS
**Describe the bug**
It seem like transition is not animating or stops randomly.
If I comment transition, then style is applied correctly (but, of course, without an animation)

**To Reproduce**

Run XAML below on iOS. It works as expected on Android and macOS desktop.

```xaml
<StackPanel Classes.rotated="{Binding #Rotate.IsChecked}"
              HorizontalAlignment="Center" VerticalAlignment="Center">
      <StackPanel.Styles>
          <Style Selector="StackPanel">
              <Setter Property="RenderTransform" Value="rotate(0)" />
          </Style>
          <Style Selector="StackPanel.rotated">
              <Setter Property="RenderTransform" Value="rotate(45deg)" />
          </Style>
      </StackPanel.Styles>
      <StackPanel.Transitions>
          <Transitions>
              <TransformOperationsTransition Property="RenderTransform"
                                             Duration="0:0:1"
                                             Easing="ExponentialEaseIn" />
          </Transitions>
      </StackPanel.Transitions>
      <TextBlock Text="Transition not working on iOS" TextWrapping="Wrap" TextAlignment="Center"
                 FontSize="40" FontWeight="Bold"
                 HorizontalAlignment="Center" VerticalAlignment="Center">
      </TextBlock>
      <CheckBox x:Name="Rotate" HorizontalAlignment="Center">Rotate</CheckBox>
  </StackPanel>
```

**Expected behavior**
StackPanel should rotate with an animation.

**Desktop (please complete the following information):**

- Desktop (IDE) - macOS 13.6 M2
- OS: iOS latest emulator and iPad 15.7.9
- Avalonia: 11.0.2+ (including latest beta)

**Additional context**

### LINKED ISSUE #13110: TransitioningContentControl (and other Transitions?) not working properly on iOS after web authentication
## Describe the bug
When changing a bound Content property of a TransitioningContentControl on iOS after returning from a Web Authentication view (using MAUI.Essentials WebAuthenticator), it fails to navigate until I tap on some other control (say a button)

It works fine if it's just a regular ContentControl so presumably there is something funky going on with transitions

It also works fine if I do not launch the authentication flow

I think this is also happening on ReactiveUI's routing

## To Reproduce

1. Create a basic "sign in" kind of screen and launch a WebAuthenticator 
2. upon returning, attempt to set the Content property bound to the control, navigating to a view with a button (presumably some sort of router/view locator is in place, but don't think it matters). 
3. Observe nothing happens
4. Tap a button (probably the sign in button), note instantly switches to the intended view

## Expected behavior
Transition should occur

## Screenshots

N/A

## Environment 

- OS: iOS
- Avalonia-Version: 11.0.4

## Additional context
I don't know how specific using WebAuthenticator is to this, perhaps any deep link or any native modal style view will cause it? Not sure at this point

### LINKED ISSUE #13594: Aynchronous reactive commands on Avalonia.iOS never complete
## Describe the bug
I have a straightforward scenario - a reactive command in the view model that invokes an awaitable async task. For the demo purposes, it's just `Task.Delay(2000)`. The problem is that on iOS, when the command execution starts, it never completes. Please take a look at the demo project I've attached. 

The command works as expected when launching the desktop version of the sample. In the demo project, I also have a Maui.iOS app that re-uses the same view model with the same set of bindings, and the reactive command works as expected there.

## To Reproduce

1. Download the [sample project](https://github.com/kyurkchyan/AvaloniaReactiveUIAsyncCommand/tree/main)
2. Launch the `AvaloniaReactiveUIAsyncCommand.iOS` on iOS Simulator
3. Press the "Load" button
4. Observe that the `Load command is busy` stays to value of "true" and the "Load" button is never reactivated.

## Expected behavior
After the load command completes its execution, the load command should be reactivated and its `IsExecuting` property should be set back to `true`

## Environment 

- OS: Mac
- Avalonia-Version: 11.1.999-cibuild0041899-beta

### LINKED ISSUE #13941: CustomSkiaPage Example do not work on ios simulator?
## To Reproduce

1. Create new avalonia cross platform app.
2. try to run the example code for custom skia page.
https://github.com/AvaloniaUI/Avalonia/blob/master/samples/RenderDemo/Pages/CustomSkiaPage.cs
3. run it on iossimulator.
4. it only renders the page first time loaded, whenever you call invalidatevisual with dispatcher, render method is not  triggered

## Expected behavior
whenever you call invalidatevisual method render method call should be made? or is there any other call to trigger render method.

I am on a mac with m1 chip. I will try with a device also.

## Screenshots
Screenshot 2023-12-14 at 00 16 35

## Environment 

- OS: Mac M1 Chip
- Avalonia-Version: 11.0.5

### PR DESCRIPTION
**Pull request by maxkatz6**
## What does the pull request do?

Two major changes:
1. Replaces kCFRunLoopCommonModes with kCFRunLoopDefaultMode on loop observer and timer. Original code was copy-pasted from our macOS backend, where we used kCFRunLoopCommonModes. But apparently it's a no-op on iOS. This was an actual bug in our backend, as the timer wasn't ticking basically.
2. Replaces delegates with function pointers where in dispatcher code. And ensuring that we don't have any runtime marshaling with dll imports. Both should result in less overhead. 

## Fixed issues

I have not tested all of these issues, but only animations+timer related. Let me know if any of these issues is still reproducible.

Fixes #13594
Fixes #13110
Fixes #13029
Fixes #11696
Fixes #13941

### CODE REVIEW

**Review by kekekeks — APPROVED** [review]

**Comment by cangunaydin** [comment]
don't know if this is directly related but #13941 is still not fixed. 
InvalidateVisual is still triggering with very much latency, sometimes it is not even triggered. 
Can be related with dispatcher but not sure.
i have created a minimal repro with the problem if you want to check.
https://github.com/cangunaydin/avalonia-customskia-ios-bug

**Comment by maxkatz6** [comment]
@cangunaydin please use a newer invalidation APIs: `TopLevel.GetTopLevel(thisControll).RequestAnimationFrame(callback)`. You can use InvalidateVisual as a callback.

**Comment by cangunaydin** [comment]
Hello again,
I tried but it doesn't help. same behavior. check the image 6 or 7 ticks happening in 30secs.
Screenshot 2024-01-20 at 11 52 48

**Comment by maxkatz6** [comment]
Can you test on a real device? .NET runtime is rather slow in the simulator. 
If not, I can try on the next week.

**Comment by maxkatz6** [comment]
Either way, it doesn’t look related to the old issue. Previously dispatcher wouldn’t raise any timer ticks at all. In your case there is something ticking

**Comment by cangunaydin** [comment]
sure i will try it on the real device. Yes you are right it is not related with the old issue. But don't think the behavior will change on real device. The weird part is like 2 days ago it seems it was working with dispatcher, i was playing with it and it is broken now :) maybe it can be related with whatever i did. But same sample works fine on android emulator 
if it doesn't work with real device, should i open a new issue instead?

**Comment by cangunaydin** [comment]
I have tested it on iphone 12, it is much more better. But still it is around 28fps. It seems like sth else is slowing it down.
on android emulator it is around 60fps, on my old samsung galaxy tablet Galaxy Tab A (2016) it is only 2fps.

**Comment by maxkatz6** [comment]
@cangunaydin so, I have 60 fps on iPhone 15. Though there shouldn't be such difference, unless you have limited FPS or there some another problem with configuration.

1. How do you measure FPS? You should use `TopLevel.GetTopLevel(this).RendererDiagnostics.DebugOverlays |= RendererDebugOverlays.Fps;`.
2. Simulator apps are known to be much slower. They also run JIT interpreter. It's still surprising that iphone 12 has such bad fps.
3. You can try to enable Metal rendering in the latest master (was merged today):
```
            .With(new iOSPlatformOptions
            {
                RenderingMode = new [] { iOSRenderingMode.Metal }
            })
```

Screenshot 2024-01-21 at 1 36 52 AM

IMG_0517

**Comment by cangunaydin** [comment]
Hello @maxkatz6 ,
I have tried with 
```
 .With(new iOSPlatformOptions
            {
                RenderingMode = new [] { iOSRenderingMode.Metal }
            })
```
and it increased to 60fps. weird though why it has so much difference with opengl.
I was using my own calculation for fps. 
Screenshot 2024-01-22 at 02 27 26

But it has the same value with `opLevel.GetTopLevel(this).RendererDiagnostics.DebugOverlays |= RendererDebugOverlays.Fps;`
is there a way to set the fps overlay somewhere else than safe areas?

**Comment by maxkatz6** [comment]
Good to know that Metal helps. 

No, I don’t think it’s possible to move fps counter.

**Pull request merged**
