### PR TITLE
When a textbox gets focus via the tab key, select all text if the textbox is single line.

### PR DESCRIPTION
**Pull request by robbieknuth**

### CODE REVIEW

**Comment by robbieknuth** [comment]
Fix for #702

**Comment by grokys** [comment]
Hi @robbieknuth - orry, I've just got round to trying to merge this now but your PR is out of date with master :(

Could you merge again, or if you could give me [write access to the PR branch](https://github.com/blog/2247-improving-collaboration-with-forks) I could merge myself.

**Comment by robbieknuth** [comment]
I've updated the branch. The "Allow edits from maintainers" checkbox is indeed ticked... but this feature looks new, perhaps it is buggy.

**Comment by grokys** [comment]
Hi @robbieknuth - yes again the branch got out of date before I could merge it. I've confirmed that this is a GitHub UI bug now, so I manually merged master into your branch from the command line. Will merge when CI has finished!

**Comment by grokys** [comment]
MERGED! Finally, thanks for your patience!

**Pull request merged**
