### PR TITLE
fix(Windows): Clipboard is missing ConfigureAwait(false) on some methods

### LINKED ISSUE #13922: Clipboard.GetDataAsync(xxx).Result freeze, since 11.0.6?
Hi,
I start to get freezes with the following line, (I am not 100% sure but) I think since I upgraded to 11.0.6.

`Clipboard.GetDataAsync(xxx).Result `

The code is called on Windows, where the internal Clipboard API is not async I think?

### PR DESCRIPTION
**Pull request by workgroupengineering**
## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/avalonia-docs with user documentation

## Fixed issues

Fixes #13922

### CODE REVIEW

**Comment by MrJul** [comment]
OLE usually requires a STA thread to work properly.
By using `ConfigureAwait(false)`, the loop will continue run on the thread pool, where the apartment won't be correct and I expect issues to occur.

[A few minutes later...]

I did some tests, and while the apartment doesn't seem to prevent calls, all clipboard functions once the clipboard is open must run on the same thread. You can't use `OpenClipboard` on some thread and call `GetClipboardData` and `CloseClipboard` on another one. With the changes, the system clipboard is completely locked if any `Task.Delay` occur in `OpenClipboard`.

**Comment by maxkatz6** [comment]
Interesting. So, this code either way would have problems with .Result blocking calls.
DispatcherFrame hack making async code into a sync could help, but I guess it's for a user code to do.

```csharp
internal static T WaitOnDispatcherFrame<T>(
    this Task<T> task)
{
    if (!task.IsCompleted)
    {
        var frame = new DispatcherFrame();
        task.ContinueWith(static (_, s) => ((DispatcherFrame)s).Continue = false, frame);
        Dispatcher.PushFrame(frame);
    }
    
    return task.GetAwaiter().GetResult();
}

var frame = Clipboard.GetFormatsAsync().WaitOnDispatcherFrame();
```

**Comment by maxkatz6** [comment]
Or, I guess, we can switch all clipboard methods to the thread pool from the beginning?

**Comment by MrJul** [comment]
> DispatcherFrame hack making async code into a sync could help, but I guess it's for a user code to do.
I agree it's for the user to do so, as `DispatcherFrame` have other problems, such as unexpected reentrancy. We might provide the helper publicly though?

> Or, I guess, we can switch all clipboard methods to the thread pool from the beginning?

Open and Close could still be called on two different threads (from the thread pool) - breaking them. I don't think we should spawn a specific thread just for clipboard operations.

Plus, even if I couldn't get anything breaking with a simple test, OLE methods are documented to run only on STA threads, and the thread pool threads aren't.

My personal opinion is that we shouldn't do anything here. Task-returning methods don't guarantee running in another thread. Sync-over-async (`Result`, `Wait()` or `GetAwaiter().GetResult()`) are a natural recipe for deadlocks whatever we choose to do.

**Comment by workgroupengineering** [comment]
in my private vsix project, to avoid problems with STD model i threads using the following code

```c#
             string content = System.Text.Json.JsonSerializer.Serialize(/* ... */);
             Thread thread = new((state) => Clipboard.SetData(Vsix.MyFormat, state));
             thread.SetApartmentState(ApartmentState.STA); //Set the thread to STA
             thread.Start(content);
             thread.Join();
``` 
It has been working for two months without any problems.

**Comment by maxkatz6** [comment]
For the reference, WPF clipboard uses Thread.Sleep which obviously has its own problems
https://github.com/dotnet/wpf/blob/e6a8177202c8c584c4b8d532dd8bc95388d3a07b/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/clipboard.cs#L616

UWP/WinUI use IClipboardStatics ([Windows.ApplicationModel.DataTransfer](https://learn.microsoft.com/en-us/uwp/api/windows.applicationmodel.datatransfer?view=winrt-22621)) without any loops. But they fallback to OLE clipborad in RichEditBox if IClipboard factory method failed.

**Comment by kekekeks** [comment]
All clipboard operations have to happen on STA thread. `ConfigureAwait(false)` forces continuation on a pool thread. The change is simply invalid.

**Pull request closed without merging**
