### PR TITLE
Window blurbehind for Windows 7 and 8.x

### PR DESCRIPTION
**Pull request by Splitwirez**
Windows 8.1 without Aero Glass mod:
unknown

Windows 8.1 with Aero Glass mod:
image

Windows 7:
image

## What does the pull request do?
Currently, Avalonia's window blurbehind and transparency functionality supports Windows, but only Windows 10. This PR extends support for blurbehind to Windows 7, as well as Windows 8.x with the aeroglass mod. I'm also looking into pure window transparency for Windows 8.x, but haven't gotten that working as of just yet.

## What is the updated/expected behavior with this PR?
On Windows 7 or 8.1, ensure DWM is active (and that the aeroglass mod is up and running if on Windows 8.1), and then open the control catalog, and set the window transparency hint to Acrylic or Blur. Go to the Acrylic page, and you'll be able to see the effect through the Acrylic areas.

### CODE REVIEW

**Comment by Splitwirez** [comment]
I should probably note, I'm still awaiting test results on Windows 7 from a friend. Those should be in later today or tomorrow. Theoretically it should work...

**Comment by kekekeks** [comment]
I'm not quite sure if we should depend on custom windows mods.

**Comment by Splitwirez** [comment]
> I'm not quite sure if we should depend on custom windows mods.

It's hardly a *dependency* per se - the code just falls back to `None` if the mod isn't present, not unlike the current behavior. If you have a better idea, I'm all ears, but I see no reason to not take advantage of the functionality if and when it exists. It's the exact same API as on WIndows 7 (namely `DwmEnableBlurBehindWindow`), and said API does *exist* in Windows 8+ even without the mod, it just...doesn't produce any blurbehind unless the mod is installed anymore.

The benefit: Users who have the mod installed will enjoy blurred transparency, which is kind of the whole point of installing the mod in the first place.

The cost: I...honestly don't see any. If you see one, I'm all ears.

**Comment by jmacato** [comment]
@Splitwirez can you give us new screenshots with and without the aeromod on win7/8?

**Comment by Splitwirez** [comment]
> 
> 
> @Splitwirez can you give us new screenshots with and without the aeromod on win7/8?

Can do on Windows 8.1, but for Windows 7, we're still stuck on that shader compilation error I mentioned on Discord...and it's been reproduced on two machines now (one was a VM)...a separate VM running Windows 8.1 on the same host machine had no such problems, nor any of the OpenGL teapot glitchiness I showed you on Discord...

**Comment by Splitwirez** [comment]
@jmacato I've added the requested screenshot as seen on 'vanilla' Windows 8.1, but until we get Avalonia itself up and running on Windows 7, I can't really provide screenshots of that (nor confirmation that my code works on Windows 7...though theoretically it should). So on that note...now what?

**Comment by jmacato** [comment]
Ignore Windows 7 for now

**Comment by Splitwirez** [comment]
> 
> 
> Ignore Windows 7 for now

...okay :/

Is there anything else I need to do before this PR is reviewed/merged/whatever?

**Comment by Splitwirez** [comment]
Updated OP with Windows 7 screenshot - apparently it's not as simple as "Avalonia no workie on Windows 7"

**Review by jmacato — APPROVED** [review]
LGTM! awaiting @danwalmsley 's approval

**Review by danwalmsley — APPROVED** [review]
LGTM, did a bit of tidying.

**Pull request merged**
