### PR TITLE
[WIP] Draft: Port ListView and GridView from WPF to Avalonia

### PR DESCRIPTION
**Pull request by joneuhauser**
## What does the pull request do?
This is an early draft to port https://github.com/dotnet/wpf/blob/master/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/ from WPF to Avalonia. At this point it compiles, but doesn't really work, so please don't review it yet.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=4934) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=4934) before we can accept your contribution.<br/><br/>:x: jhofinger [sign now](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=4934)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/AvaloniaUI/Avalonia?pullRequest=4934) it.</sub>

**Comment by MarchingCube** [comment]
I'm wondering - what is the difference between `GridView` vs `DataGrid`? I never used it much so I'm quite curious what is the primary use case.

**Comment by Gillibald** [comment]
From a quick look to the source, it looks like ListView is a ListBox but with a customizable layout. So it might make sense to use ItemsRepeater as the building block for this and introduce a GridLayout instead.

**Comment by jhofinger** [comment]
So I guess there are multiple ways forward.

1) Don't do this at all, Datagrid is sufficient. The main difference is that GridView is a far lighter control, but doesn't have editing, which is sometimes desirable.

2) Try to fix this branch. As @Gillibald points out, a virtualizing ItemsRepeater would be better for this, but that doesn't seem to be how the WPF one is built. So starting over from scratch it is.

3) Continue from this experimental branch: https://github.com/AvaloniaUI/Avalonia/compare/xdatagrid-experiment which uses an ItemsRepeater (+1) and is not editable (+1)

**Comment by jmacato** [comment]
@jhofinger I authored that xdatagrid/datarepeater branch and would be great to have someone take over the cleanup/maintainance of that one :)

**Comment by danwalmsley** [comment]
@jhofinger I think actually with the advances that ItemsRepeater gives and with Avalonia being a more modern framework... its probably the way to go...

I think it might even be possible to make the api quite similar too.

**Pull request closed without merging**
