### PR TITLE
Increase TextFormatter compatibility with WPF's version

### LINKED ISSUE #4830: TextBlock wrapping causes text alignment Center to be off center
Repro:
`<TextBlock Text="STRIKE TAKEN" TextAlignment="Center" TextWrapping="Wrap" />`

Looks like in 0.10 wrapping causes width to be calculated based on "STRIKE_" instead on "STRIKE", which puts string a bit off center to the left with TextAlignment="Center" + TextWrapping="Wrap".

Picture displays output for same control in WPF, Avalonia 0.9 and 0.10.

Avalonia wrap issue

### PR DESCRIPTION
**Pull request by Gillibald**
## What does the pull request do?

Introduce multiple fixes to text hit testing
Better coverage of WPF's API to allow porting WPF's FormattedText

## Checklist

- [x] Added unit tests (if possible)?
- [x] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

## Fixed issues

Fixes: #4830

### CODE REVIEW

**Comment by grokys** [comment]
@Gillibald this seems to be a breaking change, so it'll have to wait for 11.0, is that correct?

**Comment by Gillibald** [comment]
Yes, we break some low-level API. It can be released alongside the FormattedText and TextBox rework.

**Comment by Gillibald** [comment]
@shartte I have added TextEndOfLine handling to the TextFormatter by introducing a new property on `TextLine.TextLineBreak`
This isn't breaking as much as your solution.

**Review by grokys — APPROVED** [review]

**Comment by grokys** [comment]
Is this ready for merge?

**Comment by Gillibald** [comment]
Y this is ready for merge. Just confirmed the fix of the referenced issue.

**Pull request merged**
