### PR TITLE
Prevent SelectingItemsControl's selection from being updated on focus when toggle is enabled

### LINKED ISSUE #8462: ListBox selection using keyboard with Ctrl and arrow keys
**Describe the bug**
Selecting items using Shift works perfectly. However with Ctrl, it's not working as expected.

**To Reproduce**
1. Focus the listbox.
2. Select a random item.
3. Hold Ctrl down and navigate using arrow keys to other items.
4. You will see that the selection state of the items are inverted as you navigate, instead of just getting focused.

**Expected behavior**
As you are holding down Ctrl, the items should be only focused, keeping the previous selected items untouched. Then when you hit Space, the focused item should be toggled. This is the exact behavior of standard ListBox controls in Windows, Ubuntu and maybe other OS as well.

**Desktop:**

- OS: Windows, Ubuntu
- Version: *any*

### PR DESCRIPTION
**Pull request by emmauss**
## What does the pull request do?
This prevents a list item's selection state from being updated when it gains focus with Toggle enabled, or the Control key pressed with Multiple Selection enabled.

## What is the current behavior?
When a list item gains focus, it's selection is updated. For range selection using the Multiple Selection Mode, or with Shift pressed, selection behaves as expected. With Toggle enabled, or Control pressed, the selection state is always toggled, even if the triggering event isn't confirming the selection, like in the case of navigating with arrow keys.

## What is the updated/expected behavior with this PR?
When Toggle is enabled, selection will only be toggled when Space or Enter is pressed, or the item is clicked. Using the arrow keys won't update selection in this case.

## Checklist

- [x] Added unit tests (if possible)?
- [x] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Fixed issues
Fixes #8462

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0024519-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0024857-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0025367-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0025401-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
