### PR TITLE
Port of WPF DockPanel

### LINKED ISSUE #2601: TabControl TabItem's overflow over the content panel.
Repro (add more tab items in Control Catalog TabControl page):

### PR DESCRIPTION
**Pull request by wieslawsoltes**
## What does the pull request do?

Ports the DockPanel control from dotnet/wpf repository.

Also fixed `WrapPanel` license header.

## What is the updated/expected behavior with this PR?

DockPanel's behavior should now be inline with WPF's.

## Checklist

- [x] Added unit tests (if possible)?
- [x] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

## Breaking changes

None in the API, old unit tests passed.

## Fixed issues

Fixes https://github.com/AvaloniaUI/Avalonia/issues/2601

### CODE REVIEW

**Comment by wieslawsoltes** [comment]
I have tested WPF version using Avalonia's unit test and the WPF tests pass without modification.

https://github.com/wieslawsoltes/WpfUnitTests/blob/7b524ef75d1e0f0700187a199d4dd243f6731e37/tests/WpfUnitTests/DockPanelTests.cs#L17-L102

**Comment by wieslawsoltes** [comment]
Seems like we have issue with StackPanel/Image:

**Comment by wieslawsoltes** [comment]
@jmacato Seems like there is issue with `DataGrid` `Bounds.Height`:

**Comment by wieslawsoltes** [comment]
Marking this as [WIP]. I will try to port WPF `StackPanel` to see if it fixes above issues.

**Comment by wieslawsoltes** [comment]
Ported tests to WPF (tests with spacing are not ported for obvious reasons): https://github.com/wieslawsoltes/WpfUnitTests/blob/fadd87bede5ac4ded6bc9ffe3fab819df7ad512e/tests/WpfUnitTests/StackPanelTests.cs#L19-L358

Interesting that rwo tests fail in WPF version of StackPanel:
https://github.com/wieslawsoltes/WpfUnitTests/blob/fadd87bede5ac4ded6bc9ffe3fab819df7ad512e/tests/WpfUnitTests/StackPanelTests.cs#L139
```
Message: Assert.Equal() Failure
Expected: 60;120
Actual:   100;120
```
https://github.com/wieslawsoltes/WpfUnitTests/blob/fadd87bede5ac4ded6bc9ffe3fab819df7ad512e/tests/WpfUnitTests/StackPanelTests.cs#L116
```
Message: Assert.Equal() Failure
Expected: 120;60
Actual:   120;100
```

**Comment by wieslawsoltes** [comment]
Looks like there are issues with `Control`'s alignment inside panels e.g.: https://github.com/AvaloniaUI/Avalonia/blob/fedbe118be3ef7b1c8cf59172c0ec84fbfe2a99a/tests/Avalonia.Controls.UnitTests/StackPanelTests.cs#L171 as this tests are failing (they pass in WPF).

**Comment by grokys** [comment]
@wieslawsoltes the `StackPanel` tests seem to be failing because WPF keeps hidden state relating to the value returned from `MeasureOverride` and uses that instead of `DesiredSize` to actually position the control.

If you look at the test in WPF, the `DesiredSize` for the failing control is `100, 10` but the `ActualWidth` is `150`.

image

I remember coming across this when originally writing the Avalonia layout code and being really confused what was happening here! So I'm not sure we want to copy WPF's behavior here, however we kinda _do_ want to end up with the same layout (which is what we had before), which leads me to think that it might not be worth copying WPF's `StackPanel` code... What do you think?

**Comment by wieslawsoltes** [comment]
@grokys

> WPF keeps hidden state relating to the value returned from MeasureOverride

I could not find where this hidden state comes from. I would like to try to port this behavior in this PR and see if this works, otherwise I will remove `StackPanel` from this PR.

**Comment by wieslawsoltes** [comment]
@grokys When looking at https://github.com/dotnet/wpf/blob/master/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Stack.cs I could not find how this hidden state is calculated. I suspected its related to control alignment and not some hidden state.

**Comment by grokys** [comment]
@wieslawsoltes the hidden state is in `FrameworkElement`: it's referred to as "ink size" in this part of the code: https://github.com/dotnet/wpf/blob/master/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/FrameworkElement.cs#L4727

**Comment by wieslawsoltes** [comment]
@grokys I have reverted `StackPanel` changes in this PR. I will submit separate PR for StackPanel so this PR is not blocked.

**Comment by wieslawsoltes** [comment]
This PR is ready for review.

**Review by grokys — APPROVED** [review]

**Pull request merged**
