### PR TITLE
Add a few missing Window APIs back in.

### PR DESCRIPTION
**Pull request by grokys**
## What does the pull request do?

#11062 made `WindowBase.PlatformImpl` internal, but a couple of APIs from there weren't exposed in our public API surface, so this PR adds alternatives back in:

- [Added WindowBase.TryGetPlatformHandle.](https://github.com/AvaloniaUI/Avalonia/commit/cf52ab43cde367fc12ecad06340ce21b3df31fa7) : `WindowBase.PlatformImpl` is now internal so we need to expose a different want to get the window handle
- [Added WindowBase.Resized event.](https://github.com/AvaloniaUI/Avalonia/commit/981dfd29d74ba2c64b9cca220d2f0e7ec830e201): exposes the resize reason and new client size. Required renaming `PlatformResizeReason` to `WindowResizeReason`. Made `TopLevel.HandleResized` method internal.

### CODE REVIEW

**Review by danwalmsley — APPROVED** [review]

**Review by kekekeks — APPROVED** [review]

**Comment by robloo** [comment]
SizeChanged events were added to other controls to follow WPF. Having a separately termed Resized event for conceptually the same thing, but with a few more details, may not be the best API. I'll point that out but expect you won't change it.

**Comment by MikeCodesDotNET** [comment]
Hi @robloo, we needed to add that to support an existing enterprise customer.

While looking to WPF for inspiration is helpful, we’re not looking to copy that API 1:1 and can make changes when necessary.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0033618-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by robloo** [comment]
As stated, I wasn't expecting you to change it but wanted to point it out for consideration. API review and consistency is useful for everyone. And unless there is a good reason to deviate from WPF/WinUI usually its best to follow established convention -- which is what this project has done so far. Microsoft is far more strict about such things though and we can find a middle road.

Being open source by nature solicits feedback and different viewpoints to consider. I'll just assume there were reasons I am unaware of for why you went with a different name. Nothing wrong with pointing that out though.

**Comment by grokys** [comment]
I see your point but to me these are two different events at two different levels: a `Resized` event on a window causes the control's size to change, raising `SizeChanged`.

We _could_ make `WindowResizedEventArgs` inherit from `SizeChangedEventArgs` and overload the `SizeChanged` CLR event in `WindowBase` with a `new EventHandler<WindowResizedEventArgs> SizeChanged` event, but then the we'd be introducing an inconsistency in that the handler delegate type would be different between `Control` and `Window`, unless you cast `Window` to `Control`. More confusing IMO.

**Comment by grokys** [comment]
Although... this did make me check the order that the events are raised, and it's wrong: `SizeChanged` is raised before `Resized` as we do an explicit layout pass when we get a resize message from the platform. This should be fixed.

**Comment by robloo** [comment]
> are two different events at two different levels: a Resized event on a window causes the control's layout size to change, raising SizeChanged after layout has run.

In my mind Resized would be an event coming from the OS and handled internally to Avalonia (not exposed for apps). Then once it is processed it raises the normal SizeChanged event for apps (which is already done).

The sequence of these events will be confusing to app developers and I almost guarantee they will just be using them interchangeably... except for the one company you are adding this for. I'm also not sure apps need to know `WindowResizeReason` which is the only property that necessitates new event args I think. Again, it seems like that would just be internal to Avalonia.

I also think the comments for the Resized event need to be a lot more clear about what it's doing in the context of this discussion.

**Pull request merged**
