### PR TITLE
Disable android application projects from build

### PR DESCRIPTION
**Pull request by wieslawsoltes**
Fixes appveyor build time-out

### CODE REVIEW

**Comment by grokys** [comment]
Closing this as it didn't seem to fix it, and I've merged @kekekeks' PR which moves us to the previous VS2017 build for now.

**Comment by wieslawsoltes** [comment]
@grokys It will probably fail too as appveyor updated its VS2017 image again to April 10th updates. Fix is scheduled for version 15.2 release.

**Comment by grokys** [comment]
Hmm, maybe we should disable appveyor until 15.2 is released then...

**Comment by wieslawsoltes** [comment]
Disabling appveyor would not give us much. Currently it will just fail and not publish nugets. Merging PR is still possible.

**Pull request closed without merging**
