### PR TITLE
Updated obsolete API usages in interfaces

### PR DESCRIPTION
**Pull request by jp2masa**
## Changes
- Updated obsolete API usages in interfaces (`InputModifiers` -> `KeyModifiers`).

**This is a breaking change.**

### CODE REVIEW

**Comment by grokys** [comment]
Apologies for the delay @jp2masa - would it be possible to keep the old methods but mark them `[Obsolete]`? We try to limit breaking changes where possible. Only place this may cause a problem is on interfaces. Might be worth adding the old method signatures as extension methods to the interface.

**Comment by jp2masa** [comment]
Except for `IKeyboardDevice`/`KeyboardDevice`, I don't think that's possible, because of the default parameter values. If the objective is binary compatibility, the changes in the interfaces won't allow that anyway I think, if it's "source code compatibility" (i.e. what used to compile still compiles) is not really easy, e.g.:

```cs
public void Focus(
    IInputElement control,
    NavigationMethod method = NavigationMethod.Unspecified,
    InputModifiers modifiers = InputModifiers.None)
```

If we remove the default value for `modifiers`, it also has to be removed for `method` (default value parameters have to be last ones). However, if it's called like `Focus(control, modifiers: modifiers)` it won't compile anymore.

**Comment by grokys** [comment]
@kekekeks what do you think? Worth taking the breaking change here? It's not a breaking change that's difficult to fix.

>  if it's "source code compatibility" (i.e. what used to compile still compiles) 

Yes at this point, it's source compatibility.

**Comment by kekekeks** [comment]
We are breaking binary compatibility between versions anyway, so it's better to change things before entering the 1.0 stage with stronger compatibility guarantees.

**Review by grokys — APPROVED** [review]

**Pull request merged**
