### PR TITLE
Fix drawing presenter clipping

### LINKED ISSUE #1877: DrawingPresenter Margin does not offset drawing
Setting a Margin on a DrawingPresenter makes the control larger but the drawing is left at the top left and clipped by the margin

```
<DrawingPresenter Margin="6">
        <DrawingPresenter.Drawing>

          <DrawingGroup>
            <DrawingGroup.Children>
              <GeometryDrawing Brush="#00FFFFFF" Geometry="F1M16,16L0,16 0,0 16,0z" />
              <GeometryDrawing Brush="#FFF6F6F6" Geometry="F1M16,10.5352L14.505,12.0302 16,13.5252 16,14.4742 14.475,16.0002 13.525,16.0002 12.03,14.5052 12,14.5352 12,16.0002 10.535,16.0002 9.586,16.0002 0.00999999999999979,16.0002C-0.0130000000000017,16.0202,0.00999999999999979,3.0002,0.00999999999999979,3.0002L2,3.0002 2,2.0002 3.01,2.0002C3.423,0.8362 4.717,0.000199999999999534 6.02,0.000199999999999534 7.324,0.000199999999999534 8.598,0.8362 9.01,2.0002L10.01,2.0002 10.01,3.0002 12,3.0002 12,9.5252 12.03,9.5562 14,7.5862 16,9.5862z" />
              <GeometryDrawing Brush="#FF424242" Geometry="F1M7.1631,9L8.6461,9 7.6461,10 4.2671,10 3.0001,10 3.0001,9 4.8371,9z M9.0001,7L9.0001,8 7.2461,8 4.7541,8 3.0001,8 3.0001,7 3.7521,7 8.2481,7z M8.5861,15L1.0001,15 1.0001,4 3.0001,4 3.0001,5 2.0001,5 2.0001,14 7.5861,14z M10.0001,5L9.0001,5 9.0001,4 11.0001,4 11.0001,8.525 10.0601,7.586 10.0001,7.646z M6.0191,4C5.4691,4 5.0101,3.553 5.0101,3 5.0101,2.447 5.4591,2 6.0101,2 6.5621,2 7.0101,2.447 7.0101,3 7.0101,3.553 6.5721,4 6.0191,4 M8.0101,3C8.0101,1.896 7.1151,1 6.0101,1 4.9061,1 4.0101,1.896 4.0101,3L3.0001,3 3.0001,4 3.0001,5 9.0001,5 9.0001,4 9.0001,3z" />
              <GeometryDrawing Brush="#FFEFEFF0" Geometry="F1M3,7L3.752,7 8.248,7 9,7 9,8 7.246,8 4.754,8 3,8z M9.556,12.03L7.586,10.061 7.646,10 4.267,10 3,10 3,9 4.837,9 7.163,9 8.646,9 10,7.646 10,5 2,5 2,14 7.586,14z" />
              <GeometryDrawing Brush="#FFA1260D" Geometry="F1M12.0303,10.9699L10.0603,8.9999 9.0003,10.0609 10.9703,12.0299 9.0003,13.9999 10.0603,15.0599 12.0303,13.0909 14.0003,15.0599 15.0603,13.9999 13.0903,12.0299 15.0603,10.0609 14.0003,8.9999z" />
            </DrawingGroup.Children>
          </DrawingGroup>

        </DrawingPresenter.Drawing>
      </DrawingPresenter>
```

### PR DESCRIPTION
**Pull request by ahopper**
This template is not intended to be prescriptive, but to help us review pull requests it would be useful if you included as much of the following information as possible:

- What does the pull request do?
fixes #1877 DrawingPresenters with a margin are clipped wrongly
- What is the current behavior?
the clipping rectangle moves by double the margin
- What is the updated/expected behavior with this PR?
clipping is correct

- How was the solution implemented (if it's not obvious)?

Checklist:

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

If the pull request fixes issue(s) list them like this:

Fixes #1877

Sorry, I don't know how the submodule stuff has appeared here and so far I've failed to remove them

### CODE REVIEW

**Comment by ahopper** [comment]
sorry, I'm having a bad git day and appear to have made a mess!

**Comment by aelij** [comment]
Hey @ahopper. Could you please explain the fix and maybe also add a comment in the code? It's not trivial IMO why `Translate(-Bounds.Position)` works. Thanks :)

**Comment by ahopper** [comment]
@aelij the Bounds effectively contains the margin offset in Bounds.Position but the context already has allowed for the margin so only the size of Bounds is wanted for clipping.  Instead it could be written (new Rect(Bounds.Size) )

**Comment by aelij** [comment]
I think that would be clearer.

**Review by aelij — APPROVED** [review]

**Comment by Sorien** [comment]
maybe i should be squashed 10commits for 1 line change :)

**Comment by jkoritzinsky** [comment]
Yeah I'm going to squash-rebase-merge this commit to keep our git history clean. Thanks @ahopper!

**Pull request merged**
