### PR TITLE
Move FlowFirection to Visual

### PR DESCRIPTION
**Pull request by danielmayost**
## What does the pull request do?
- Move the FlowDirection property to `Visual` which makes more sense to me.
- Remove `BypassFlowDirectionPolicies` override from `TopLevel`, previously I thought it was consumed by a bug I already fixed, it is no longer needed.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Breaking changes
None, Apparently.

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0027051-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-nightly/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0027056-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-nightly/nuget/v3/index.json) [PRBUILDID]

**Comment by grokys** [comment]
>Move the FlowDirection property to Visual which makes more sense to me.

Not sure - in WPF and UWP it's defined on `FrameworkElement` so the equivalent Avalonia class is `Control`. What are the reasons for moving it to `Visual`? I don't really mind either way but we tend to try to default to doing what WPF/UWP do unless there's a good reason not to.

@Gillibald may have an opinion on this.

**Comment by danielmayost** [comment]
I think in WPF the transform apply as LayoutTransform and it was not possible to apply a transformation before `FrameworkElement`, which is our equivalent to `Layout`.

Besides, we apply `HasMirrorTransform` according to the previous element in the visual tree, if `Control` is the owner of `FlowDirection` the visual parent will not always be `Control`, and the calculation has to rely on it being LTR, which is not always true, for example, if its parent is Control and it is RTL.

**Comment by Gillibald** [comment]
I am fine with this change. It makes sense to handle FlowDirection on the Visual level to support mirroring for Visuals that are added to the visual tree but are not of type control. This also makes it possible to share the FlowDirection with the renderer if needed.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0027219-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-nightly/nuget/v3/index.json) [PRBUILDID]

**Review by Gillibald — APPROVED** [review]

**Pull request merged**
