### PR TITLE
Add Sector shape

### PR DESCRIPTION
**Pull request by ErrorCraft**
## What does the pull request do?
This PR adds a Sector shape, similar to the Arc shape.
Sector Shape

It also adds three methods to the `MathUtilities` class which are used in the `Sector` class. (These can also be used in the `Arc` class, I will likely make a PR for this as well if it is accepted.)

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=8667) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=8667) before we can accept your contribution.<br/><br/>:x: ErrorCraft [sign now](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=8667)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/AvaloniaUI/Avalonia?pullRequest=8667) it.</sub>

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0022832-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by kekekeks** [comment]
The code looks OK, but I'm not quite sure about the naming, `Sector` seems to be too ambigious. Could we name it `CircularSector` or `CircleSector` instead?

**Comment by maxkatz6** [comment]
If there is a similar control/shape in other GUI frameworks, we can take naming from there.
There is none in WPF/UWP/Xamarin from what I know.

**Comment by robloo** [comment]
A sector is the proper mathematical name.

We were also discussing this here: https://github.com/AvaloniaUI/Avalonia/pull/6003#issuecomment-856046022

**Comment by Sorien** [comment]
there are other possible names https://en.wikipedia.org/wiki/Circular_sector

**Comment by ErrorCraft** [comment]
I mainly chose the name `Sector` because it's consistent with the name `Arc`. If the name is changed to `CircularSector` then `Arc` should likely be renamed to `CircularArc` as well. Also speaking of https://github.com/AvaloniaUI/Avalonia/pull/6003#issuecomment-856046022, I was thinking of adding an inner radius to the sector as well to allow for something like this.
Sector Shape Inner

**Comment by robloo** [comment]
In terms of properties I would follow what was decided for arc and have:

 - `StartAngle` (units: degrees)
 - `SweepAngle` (units: degrees)
(make sure to document these, especially degrees units)

Then I would add an
 - `InnerRadius` (units: DI pixels same as height/width)
I've seen many cases where this would be useful already.

There is no need for a `Radius` property since the height/width of the shape itself define that (as currently reflected in the code).

**Comment by kekekeks** [comment]
Would InnerRadius control inner oval height or width?

**Comment by robloo** [comment]
> Would InnerRadius control inner oval height or width?

Good point, I was thinking just for uniform/circular sectors.

Options:

 1. `InnerRadius` could be of type `Size` and have both width/height components together
 2. Break apart into two properties
     - InnerRadiusX
     - InnerRadiusY
 3. Break apart into two properties but follow the outer radius concepts/naming
    - InnerHeight
    - InnerWidth
 
Option 3 might make the most sense considering how the overall shape size is set.

**Comment by jp2masa** [comment]
Note that allowing different inner radius Width/Height would allow some weird shapes which may or not be wanted (e.g. circle cut by ellipse, ellipse cut by circle, or ellipse cut by other, not proportional, ellipse).

**Comment by robloo** [comment]
As written now, the Sector class supports non-uniform width and height. If that is supported for the outside geometry we should have the same for inside geometry. Since arc allows this, it seems sector should as well. While strange if misused, I think the logic for API purposes makes sense.

**Comment by robloo** [comment]
Although, I suppose their is a 4th option and the inner radius would be specified as a percentage. Then it would follow the same aspect ratio as the outside geometry. That would ensure both inside and outside are always matching: either ellipse or circle.

**Comment by maxkatz6** [comment]
RelativeSize type for the inner radius? So it can be specified as percentage OR absolute values.

**Comment by robloo** [comment]
I couldn't find a `RelativeSize` type, but the `RelativeRect` type should work for this. That would allow a single property and both relative/absolute size as mentioned. There are some downsides:

 - Having a property called `InnerRadius` taking a `Rect` doesn't make a lot of sense
 - It would still be possible to have an outside oval and inside circle which was a concern mentioned above (not so much a concern for me)
 - The percentage would have to be specified for both the height AND width. That defeats the simplicity of using a percentage which would also match inner aspect ratio with outer.

**Comment by robloo** [comment]
Well, it's probably best to just finish this up without the inner radius functionality. That can always be added back as a non-breaking change once the API is settled. There doesn't seem to standard anywhere and all the ideas here are quite different.

**Review by maxkatz6 — APPROVED** [review]

**Comment by robloo** [comment]
@maxkatz6 Are you ok with the properties for the arc in `Sector` being different than in `Arc`? That still doesn't seem right to me and I would standardize that at least before a merge.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0023180-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
