### PR TITLE
Implement measure pass in AdornerLayer.

### PR DESCRIPTION
**Pull request by grokys**
## What does the pull request do?

Previously the `AdornerLayer` was falling back to the base class implementation of `MeasureOverride`, in `Canvas`. This meant that at times, adorner controls were being measured with a larger constraint than the final size given to them. `Grid` doesn't like it when this happens which causes problems with various controls.

Add a measure pass to `AdornerLayer` which passes the adorned control's bounds as the constraint (which is the value that the arrange pass will use).

cc: @YohDeadfall

### CODE REVIEW

**Review by YohDeadfall — APPROVED** [review]
Looks good, thank you!

**Comment by jmacato** [comment]
Is there any issue tracker for this one?

**Comment by YohDeadfall** [comment]
No, it was discussed privately.

**Review by MarchingCube — APPROVED** [review]
LGTM.

**Pull request merged**
