### PR TITLE
do not focus scrollbar

### PR DESCRIPTION
**Pull request by Sorien**
- What does the pull request do?

marks all scrollbar's active buttons as non-focusable 

- What is the current behavior?

user can set focus to scrollbar

- What is the updated/expected behavior with this PR?

afaik scrollbars are not focusable in any os

### CODE REVIEW

**Comment by kekekeks** [comment]
Basically, separate scroll bar should have input focus, while one in ScrollViewer shouldn't. Also see: https://docs.microsoft.com/en-us/windows/desktop/controls/create-a-keyboard-interface-for-standard-scroll-bars

I think we need keyboard scrolling support (via PgUp/PgDown) for ScrollViewer

**Comment by Sorien** [comment]
you are right i forgot that scrollbar can be used as separated control (but i have never used it that way)

**Comment by grokys** [comment]
Thanks @Sorien but still not sure this is right: if I create a scrollbar in WPF and make it `Focusable`, then I can focus the `ScrollBar` itself but not the individual components of the scrollbar. Here, if I do the same I can individually select the different buttons in the scrollbar.

**Review by grokys — CHANGES_REQUESTED** [review]
Thanks @Sorien but still not sure this is right: if I create a scrollbar in WPF and make it Focusable, then I can focus the ScrollBar itself but not the individual components of the scrollbar. Here, if I do the same I can individually select the different buttons in the scrollbar.

**Comment by Sorien** [comment]
i made few changes, hope i get it right

**Review by grokys — APPROVED** [review]
Thanks @Sorien, looks good now!

**Pull request merged**
