### PR TITLE
bugfix: Avoid compositor issue of CalendarDatePicker

### LINKED ISSUE #8864: Calendar month names are not always visible
**Describe the bug**
It's possible to use `CalendarDatePicker` in such a way that the month names in the year view are not generated. The control displays blank tiles instead.

**To Reproduce**

1. Start the Control Gallery and navigate to the CalendarDatePicker tab
2. Open the calendar pop-up on any of the controls inside the tab
3. Click on the current year, at the top of the pop-up
4. Click outside the pop-up so that it closes
5. Re-open the pop-up
6. Click on the current year again

You will see this:

image

**Expected behavior**
Month names should always be visible in the year view, like this:

image

**Desktop (please complete the following information):**

- OS: Windows
- Version 11 preview 1

### PR DESCRIPTION
**Pull request by comesx4**
## What does the pull request do?
We met the same issue in #8864, but I found one way to avoid the compositor issue of CalendarDatePicker

## What is the current behavior?
As described in #8864.

## What is the updated/expected behavior with this PR?
Calendar month names shown as normal.
Tested on both Fluent and Simple Theme.
SimpleLight
FluentLight

## How was the solution implemented (if it's not obvious)?
Replace ContentControl to ContentPresenter

## Checklist

~~- [ ] Added unit tests (if possible)?~~
~~- [ ] Added XML documentation to any related classes?~~
~~- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation~~

## Fixed issues
Fixes #8864

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0026794-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-nightly/nuget/v3/index.json) [PRBUILDID]

**Comment by kekekeks** [comment]
I believe the issue should be fixed by this PR - https://github.com/AvaloniaUI/Avalonia/pull/9487

**Comment by robloo** [comment]
> I believe the issue should be fixed by this PR - https://github.com/AvaloniaUI/Avalonia/pull/9487

Regardless, I think ContentPresenter makes more sense and is what should have always been used here. So this PR should still get merged.

**Comment by maxkatz6** [comment]
Yes. ContentPresenter is a better choice for this control.

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0026859-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-nightly/nuget/v3/index.json) [PRBUILDID]

**Pull request merged**
