### PR TITLE
Set control adorner from xaml

### PR DESCRIPTION
**Pull request by wieslawsoltes**
## What does the pull request do?

Add Adorner property to AdornerLayer to enable setting control adorner from xaml directly.

https://user-images.githubusercontent.com/2297442/192141160-e25e0ced-d723-43d8-a3f8-01fcaa9d136f.mp4

## What is the current behavior?

Can not easily set control adorner from xaml directly.

## How was the solution implemented (if it's not obvious)?

Added Adorner attached property to AdornerLayer.

```xaml
<Button Content="Adorned Button" 
        HorizontalAlignment="Stretch" HorizontalContentAlignment="Center"
        VerticalContentAlignment="Center" VerticalAlignment="Stretch" 
        Width="200" Height="42">
  <AdornerLayer.Adorner>
    <Canvas x:Name="AdornerCanvas"
            HorizontalAlignment="Stretch"
            VerticalAlignment="Stretch"
            Background="Cyan"
            IsHitTestVisible="False"
            Opacity="0.3"
            IsVisible="True">
      <Line StartPoint="-10000,0" EndPoint="10000,0" Stroke="Cyan" StrokeThickness="1" />
      <Line StartPoint="-10000,42" EndPoint="10000,42" Stroke="Cyan" StrokeThickness="1" />
      <Line StartPoint="0,-10000" EndPoint="0,10000" Stroke="Cyan" StrokeThickness="1" />
      <Line StartPoint="200,-10000" EndPoint="200,10000" Stroke="Cyan" StrokeThickness="1" />
    </Canvas>
  </AdornerLayer.Adorner>
</Button>
```

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0024046-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0024060-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0024062-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0024238-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
