### PR TITLE
SkewTransform Implementation

### PR DESCRIPTION
**Pull request by jmacato**
Added SkewTransform and the relevant function in Matrix.cs.
P.S. I can't figure out how to do the bounds test for skewtransform correctly so i skipped them for now.

### CODE REVIEW

**Comment by grokys** [comment]
Thanbs for this @jmacato. Looks good except I think the X and Y angles are reversed. This is avalonia with a `<SkewTransform AngleX="20"/>`:

image

And this is WPF:

image

Regarding the bounds tests, I don't think they're strictly necessary, but if you want to do them, then  just create a `Rect` and then transform it with `TransformToAABB` to get the axis-aligned bounds of the skewed rectangle.

**Comment by jmacato** [comment]
Sorry 'bout that, uploading new fix right away

**Comment by jmacato** [comment]
Updated commit with fix, please re-check

**Comment by grokys** [comment]
LGTM! Thanks @jmacato !

**Review by grokys — APPROVED** [review]

**Pull request merged**
