### PR TITLE
[Features] [DevTools] Allowed to filter the control detail property list based on a favorite property list.

### PR DESCRIPTION
**Pull request by workgroupengineering**
## What does the pull request do?

Allowed to filter the control detail property list based on a favorite property list.
Favorites Properties

## How was the solution implemented (if it's not obvious)?

- Allowed to edit favorite property list.
- favorite property list is stored in FavoritesProperties.json
- FavouritesProperties.json is located in the directory of the executing assembly.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

### CODE REVIEW

**Comment by MarchingCube** [comment]
I am not so sure about outputting `FavouritesProperties.json` in the executing assembly location due to several reasons - write right is not guaranteed and this name has high chance of conflicting with user files.

**Comment by workgroupengineering** [comment]
Hi, @MarchingCube 
> write right is not guaranteed

normally it can be written because it coincides with the directory where the project is created, the example buid: bin / debug.

> this name has high chance of conflicting with user files.

this is true, we can add suffix like `FavouritesProperties.avalonia.json`

I thought about the executing assembly location because it is easily accessible and is cleaned up when you clean the project.

The fact that `FavouritesProperties.json` is deleted when you clean the project project can also be a disadvantage because if you have made any customizations they would be lost.

Do you have any suggestions?

**Comment by MarchingCube** [comment]
I would say - since this is a framework we should provide configuration options for users to provide path/filename. DevTools allow users to configure hotkeys and I see no reason why we couldn't configure dev tools paths and other features as well.

**Comment by maxkatz6** [comment]
> normally it can be written because it coincides with the directory where the project is created, the example buid: bin / debug.

Applications with MSIX packaging system don't have write-access to the app folder with executable. 
DevTools could be still useful in that case for testing builds.

**Comment by grokys** [comment]
What is the use-case for this? Why do you have "favourite" properties? Wouldn't the properties that are interesting to you be different depending on what you are doing?

It looks like the default settings for this are used to categorize the properties into "Layout", "Font and Color", "Input" etc. Wouldn't it be better to define this at compile-time as is done in WinForms/WPF using the [`CategoryAttribute`](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.categoryattribute?view=netcore-3.1)?

**Comment by workgroupengineering** [comment]
> What is the use-case for this? Why do you have "favourite" properties? Wouldn't the properties that are interesting to you be different depending on what you are doing?

This in the past in WPF helped me to debug unwanted behavior more quickly, highlighting only the properties that interested me.



> It looks like the default settings for this are used to categorize the properties into "Layout", "Font and Color", "Input" etc. Wouldn't it be better to define this at compile-time as is done in WinForms/WPF using the [`CategoryAttribute`](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.categoryattribute?view=netcore-3.1)?

The ones I've included are the ones I've used most often in my WPF experience. I have given the possibility to modify them because it could depend on the specific case. Using CategoryAttribute they would be fixed in the code and you would lose versatility.

**Comment by grokys** [comment]
> This in the past in WPF helped me to debug unwanted behavior more quickly, highlighting only the properties that interested me.

Oh, interesting, does WPF have this? Where?

**Comment by workgroupengineering** [comment]
> 
> 
> > This in the past in WPF helped me to debug unwanted behavior more quickly, highlighting only the properties that interested me.
> 
> Oh, interesting, does WPF have this? Where?

(Snoop wpf Tool)https://github.com/snoopwpf/snoopwpf

**Comment by grokys** [comment]
I've had some time to think about this, and though I appreciate that it could be useful I think the overhead of a UI etc in DevTools is a bit too heavy: DevTools doesn't get a whole lot of maintenence as it is and such features are likely to bitrot.

However I _do_ like the idea of `DevToolsOptions` as proposed in #5011. I'd like to suggest getting the `DevToolsOptions` feature merged first and then using that to implement such a filter.

Sound good? Going to close this PR now because our PR list is getting unmanageable. If you'd like to chat about it some more, ping me on gitter!

**Pull request closed without merging**
