### PR TITLE
Fixes InvalidOperationException error

### LINKED ISSUE #2089: InvalidOperationException when pressing TAB to change focus
## Summary
Avalonia throws an `InvalidOperationException` exception when navigating controls pressing TAB ke. 

## How to reproduce it

1. Run the ControlCatalog.NetCore project
2. Go to the TextBox panel
3. Do click on any textbox to focus it
4. Press Tab key until the exception is rised

## Original issue
https://github.com/zkSNACKs/WalletWasabi/issues/814

## Exception details

<details>
<summary>Stack trace (click to open)</summary>

```
Unhandled Exception: System.InvalidOperationException: Control is not attached to visual tree.
   at Avalonia.VisualExtensions.GetRootAndPosition(IVisual v) in /home/lontivero/GitHub/Avalonia/src/Avalonia.Visuals/VisualExtensions.cs:line 74
   at Avalonia.VisualExtensions.TranslatePoint(IVisual visual, Point point, IVisual relativeTo) in /home/lontivero/GitHub/Avalonia/src/Avalonia.Visuals/VisualExtensions.cs:line 50
   at Avalonia.Rendering.SceneGraph.Scene.<HitTest>d__27.MoveNext() in /home/lontivero/GitHub/Avalonia/src/Avalonia.Visuals/Rendering/SceneGraph/Scene.cs:line 175
   at Avalonia.Rendering.SceneGraph.Scene.<HitTest>d__27.MoveNext() in /home/lontivero/GitHub/Avalonia/src/Avalonia.Visuals/Rendering/SceneGraph/Scene.cs:line 183
   at Avalonia.Rendering.SceneGraph.Scene.<HitTest>d__27.MoveNext() in /home/lontivero/GitHub/Avalonia/src/Avalonia.Visuals/Rendering/SceneGraph/Scene.cs:line 183
   at Avalonia.Rendering.SceneGraph.Scene.<HitTest>d__27.MoveNext() in /home/lontivero/GitHub/Avalonia/src/Avalonia.Visuals/Rendering/SceneGraph/Scene.cs:line 183
   at Avalonia.Rendering.SceneGraph.Scene.<HitTest>d__27.MoveNext() in /home/lontivero/GitHub/Avalonia/src/Avalonia.Visuals/Rendering/SceneGraph/Scene.cs:line 183
   at System.Linq.Enumerable.<CastIterator>d__34`1.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Avalonia.Input.InputExtensions.InputHitTest(IInputElement element, Point p) in /home/lontivero/GitHub/Avalonia/src/Avalonia.Input/InputExtensions.cs:line 39
   at Avalonia.Input.MouseDevice.SetPointerOver(IPointerDevice device, IInputRoot root, Point p) in /home/lontivero/GitHub/Avalonia/src/Avalonia.Input/MouseDevice.cs:line 323
   at Avalonia.Input.MouseDevice.MouseMove(IMouseDevice device, IInputRoot root, Point p, InputModifiers inputModifiers) in /home/lontivero/GitHub/Avalonia/src/Avalonia.Input/MouseDevice.cs:line 208
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawMouseEventArgs e) in /home/lontivero/GitHub/Avalonia/src/Avalonia.Input/MouseDevice.cs:line 139
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawInputEventArgs e) in /home/lontivero/GitHub/Avalonia/src/Avalonia.Input/MouseDevice.cs:line 104
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e) in /home/lontivero/GitHub/Avalonia/src/Avalonia.Input/InputManager.cs:line 38
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e) in /home/lontivero/GitHub/Avalonia/src/Avalonia.Controls/TopLevel.cs:line 350
   at Avalonia.Gtk3.WindowBaseImpl.<>c__DisplayClass94_0.<OnInput>b__0() in /home/lontivero/GitHub/Avalonia/src/Gtk/Avalonia.Gtk3/WindowBaseImpl.cs:line 400
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run() in /home/lontivero/GitHub/Avalonia/src/Avalonia.Base/Threading/JobRunner.cs:line 169
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /home/lontivero/GitHub/Avalonia/src/Avalonia.Base/Threading/JobRunner.cs:line 40
   at Avalonia.Gtk3.Gtk3Platform.<>c__DisplayClass29_0.<Signal>b__0() in /home/lontivero/GitHub/Avalonia/src/Gtk/Avalonia.Gtk3/Gtk3Platform.cs:line 135
   at Avalonia.Gtk3.Interop.GlibTimeout.Handler(IntPtr data) in /home/lontivero/GitHub/Avalonia/src/Gtk/Avalonia.Gtk3/Interop/GlibTimeout.cs:line 12
   at Avalonia.Gtk3.Gtk3Platform.RunLoop(CancellationToken cancellationToken) in /home/lontivero/GitHub/Avalonia/src/Gtk/Avalonia.Gtk3/Gtk3Platform.cs:line 108
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /home/lontivero/GitHub/Avalonia/src/Avalonia.Base/Threading/Dispatcher.cs:line 64
   at Avalonia.Application.Run(Window mainWindow) in /home/lontivero/GitHub/Avalonia/src/Avalonia.Controls/Application.cs:line 259
   at Avalonia.Controls.AppBuilderBase`1.Start[TMainWindow](Func`1 dataContextProvider) in /home/lontivero/GitHub/Avalonia/src/Avalonia.Controls/AppBuilderBase.cs:line 128
   at ControlCatalog.NetCore.Program.Main(String[] args) in /home/lontivero/GitHub/Avalonia/samples/ControlCatalog.NetCore/Program.cs:line 33
```

</details>

### PR DESCRIPTION
**Pull request by lontivero**
Checks the element is attached to the visual tree as part of the Hit test

This template is not intended to be prescriptive, but to help us review pull requests it would be useful if you included as much of the following information as possible:

- What does the pull request do?

This request proposes a change to fix issue https://github.com/AvaloniaUI/Avalonia/issues/2089

- What is the current behavior?

Currently Avalonia throws an exception during controls navigation

- What is the updated/expected behavior with this PR?

Test the element processed is attached to the visual tree.

- How was the solution implemented (if it's not obvious)?

Checklist:

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

If the pull request fixes issue(s) list them like this:

Fixes #2089

### CODE REVIEW

**Comment by grokys** [comment]
@ahopper you were looking into this, weren't you? Does this look like the correct fix?

**Comment by ahopper** [comment]
it is an alternative fix to the one I put in #2067 I've no view as to which is better

**Comment by lontivero** [comment]
I based that on the latest commit (master branch) 2e05a7fc4fadb9504bde857026d67c4eb181a5bc.

**Comment by grokys** [comment]
To be honest, I think they're both the correct fix and they should both go in ;)

The fix in #2067 prevents this error for all calls to `HitTest` and this fix short-circuits the call to `HitTest`. I need to review #2067 properly, and I'll merge that and then this PR.

**Review by grokys — APPROVED** [review]

**Comment by grokys** [comment]
Thanks @lontivero - looks like #2067 is going to need a bit more discussion, so merged this first.

**Pull request merged**
