### PR TITLE
Fix bidi mirror handling

### LINKED ISSUE #8991: Parenthesis reversed in RTL
**Describe the bug**
Text rendering is weird in RTL mode, with parenthesis at the end of line. 

**To Reproduce**

1. Run ControlCatalog sample project
2. Switch to RTL in setting
3. Check `Menu` sample

**Expected behavior**

**Screenshots**
image

**Desktop (please complete the following information):**

- OS: [Windows]
- Version [11.0-preview1]

**Additional context**

### PR DESCRIPTION
**Pull request by Gillibald**
## What does the pull request do?

When FlowDirection was RightToLeft paired brackets were not appropriately mirrored. This PR fixes that.

## What is the current behavior?

Paired brackets are not mirrored and therefore are displayed in the wrong order.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Fixed issues

Fixes: #8991

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0023943-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0023971-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0024039-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0024090-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
