### PR TITLE
Implement AttachedProperties for RenderOptions

### LINKED ISSUE #12786: Pixelated image rendering regression in 11.0.2 and 11.04
**Describe the bug**
The following issue is happening again: https://github.com/AvaloniaUI/Avalonia/issues/11319 so I'm opening a new issue to point out the regression.

**To Reproduce**

1. Add an Image with a size much smaller than the native resolution of the image
2. Don't add the manual fix which should have been set as the default in Avalonia according to #11319  (`RenderOptions.BitmapInterpolationMode="HighQuality"`)
3. Run the program and see the image have a lot of jagged / pixelated edges

**Expected behavior**
According to that closed issue this should be fixed, but apparently the problem is back.

**Screenshots**
Here's how my example project looks without manually setting that option that shouldn't be necessary:

Kuvakaappaus - 2023-09-05 11-07-18

And here it is when I manually put in that workaround:

Kuvakaappaus - 2023-09-05 11-08-25

The difference is slight but I can't unsee it in my real Avalonia application where multiple buttons with icons on them now look bad in comparison to how they should look.

**Desktop (please complete the following information):**

- OS: Linux
- Version 11.0.2 and 11.04 both show this issue (11.0.2 is the current version used by the templates)

**Additional context**
This is a sample project showing the problem, I just used the new avalonia.mvvm template and did just the few changes needed to add the image file and code to display it:

[AvaloniaImageTest.zip](https://github.com/AvaloniaUI/Avalonia/files/12520765/AvaloniaImageTest.zip)

### PR DESCRIPTION
**Pull request by timunie**
## What does the pull request do?
RenderOptions are not able to be defined via Styles as they are no AvaloniaProperties. This leads to the needs that each individual control needs to set the RenderOptions

## What is the current behavior?
RenderOptions cannot be set "easily"

## What is the updated/expected behavior with this PR?
RenderOptions can be defined inside Styles

## How was the solution implemented (if it's not obvious)?
Introduced AttachedProperties for all RenderOptions

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/avalonia-docs with user documentation

## Fixed issues
Fixes #12786

### CODE REVIEW

**Comment by timunie** [comment]
@Gillibald if I don't inherit the properties, they only work if set BEVORE App start. But it would be great to be able to change it whenever one likes to. If you have any idea how to fix it, let me know.

**Comment by maxkatz6** [comment]
I will leave final review for @Gillibald, but from previous discussions this API doesn't seem to be a good tradeoff. RenderOptions are inherited by nature (without being an avalonia property). And making them an attached property adds an unwanted overhead.

**Comment by timunie** [comment]
@maxkatz6 I'm open to other API ideas here. But I still think being unable to set these globally either by style or by AppBuilder would be great for convenience. If the overhead is too big, sure that is a valid point though.

**Comment by Gillibald** [comment]
I intentionally avoided using attached properties for render options. Defined render options are automatically propagated and merged. So inheritance is already in place.

**Comment by timunie** [comment]
closing as per internal discussion

**Pull request closed without merging**
