### PR TITLE
Fixed gradient brush target rectangles.

### LINKED ISSUE #5947: Gradient start/end points are calculated incorrectly
**Describe the bug**

When drawing using a `LinearGradientBrush` in the `Visual.Render` method, the brush start and end points appear to be relative to the control being drawn on, not the primitive being drawn.

**To Reproduce**

```csharp
    class MyCanvas : Canvas
    {
        LinearGradientBrush brush;

        public MyCanvas()
        {
            brush = new LinearGradientBrush();
            brush.StartPoint = new RelativePoint(0, 0, RelativeUnit.Relative);
            brush.StartPoint = new RelativePoint(0, 0.5, RelativeUnit.Relative);
            brush.GradientStops = new GradientStops
            {
                new GradientStop(Colors.Red, 0),
                new GradientStop(Colors.Green, 1),
            };
        }

        public override void Render(DrawingContext context)
        {
            context.DrawRectangle(brush, null, new Rect(0, 0, 100, 100));
            context.DrawRectangle(brush, null, new Rect(300, 300, 100, 100));
        }
    }
```

**Expected behavior**

WPF outputs this:

image

Avalonia instead does this:

image

### PR DESCRIPTION
**Pull request by grokys**
## What does the pull request do?

As described in #5947, when drawn via the `DrawingContext` gradient brushes were not taking the origin of the target rect into account, only the size - meaning that primitives drawn away from the origin were incorrectly filled.

This PR changes the methods which currently accept a `Size` accept a `Rect` in order to create the brush rect.

## Fixed issues

Fixes #5947.

### CODE REVIEW

**Review by maxkatz6 — APPROVED** [review]

**Comment by yankun** [comment]
Hi, this merge request breaks a behaviour I relied on. I'm drawing a pie chart, built with multiple shapes laying in a canvas, which shared the same gradient background. On 10.6 the gradient went from top to bottom, now it is repeating it self in the middle. From the changes I see, I can't find an easy method to restore the old behaviour?

` <ItemsControl Width="400" Height="400" Items="{Binding PieWedges}">
            <ItemsControl.ItemsPanel>
                <ItemsPanelTemplate>
                    <Canvas></Canvas>
                </ItemsPanelTemplate>
            </ItemsControl.ItemsPanel>
            <ItemsControl.ItemTemplate>
                <DataTemplate>
                    <pie:PiePiece
                        Rotation="{Binding Rotation}"
                        WedgeAngle="{Binding Angle}"
                        Radius="{Binding OuterRadius}"
                        InnerRadius="{Binding InnerRadius}"
                        CenterX="200"
                        CenterY="200"
                        Fill="{Binding Fill}">
                    </pie:PiePiece>
                </DataTemplate>
            </ItemsControl.ItemTemplate>
        </ItemsControl>`

**Comment by grokys** [comment]
Oh dear :( I really thought this wouldn't affect anyone because the behavior introduced here is consistent with WPF... Looks like we either need to revert this change or add a setting to control it.

**Comment by wieslawsoltes** [comment]
I am for how WPF API does gradient brushes coordinate system. It's compatible and easy to convert from Svg to WPF.

**Comment by grokys** [comment]
Yeah I think I agree with @kekekeks - we should revert this change. I'll open a PR to do that.

**Pull request merged**
