### PR TITLE
Don't show text selector when no text is ready

### LINKED ISSUE #15694: Visibility of Text selection handles on empty TextBoxes on Android
### Describe the bug

Text selection handles appears as soon as the user clicks on the TextBox even when the TextBox is empty

image

### To Reproduce

This happens for any Basic TextBox when you run your Avalonia (11.1.0-beta2) app on Android

### Expected behavior

Text selection handles shouldn't appear when the user clicks on an empty TextBox

### Avalonia version

11.1.0-beta2

### OS

Android

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by emmauss**
## What does the pull request do?
When there's no text in a textbox, tapping it will not show the selection handles. 

## What is the current behavior?
Text selectors always show even when there's no text to select.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/avalonia-docs with user documentation

## Fixed issues
Fixes https://github.com/AvaloniaUI/Avalonia/issues/15694

### CODE REVIEW

**Review by maxkatz6 — APPROVED** [review]

**Review by maxkatz6 — APPROVED** [review]

**Comment by robloo** [comment]
On Android with Samsung S23 (not using Avalonia) here is the functionality. 

 1. First tap into empty textbox the cursor appears.
 2. Second tap into an empty textbox the cursor AND selection handle appears and the Paste, etc. Context menu opens.

I think you are oversimplifying this a bit and the selection handle is useful user feedback in some cases. At least it makes clear where the cursor is.

**Comment by emmauss** [comment]
> On Android with Samsung S23 (not using Avalonia) here is the functionality.
> 
>     1. First tap into empty textbox the cursor appears.
> 
>     2. Second tap into an empty textbox the cursor AND selection handle appears and the Paste, etc. Context menu opens.
> 
> 
> I think you are oversimplifying this a bit and the selection handle is useful user feedback in some cases. At least it makes clear where the cursor is.

I'm only able to show the handles on an empty textbox when you long press. This both shows the context menu and the handle. Tapping doesn't.  Imho, there isn't a purpose of the handle when the textbox is empty, as no selection can occur, and context menu will still show with long press

**Comment by robloo** [comment]
In Samsung OneUI this is what I see:

Single tap:



Tap once, wait and tap again:

**Comment by maxkatz6** [comment]
> First tap into empty textbox the cursor appears.
Second tap into an empty textbox the cursor AND selection handle appears and the Paste, etc. Context menu opens.

On iOS:
1. First tap shows the cursor
2. Second tap shows the context menu, but not the selection handle
3. Selection handle only appears if field is not empty, and user double tapped on the text (long press only moves the cursor).

**Comment by emmauss** [comment]
Flutter seems to use the android behavior(long press to show handle and menu) when using the material theme, and no showing when using cupertino(ios)

**Comment by robloo** [comment]
Flutter matching the host OS behavior seems correct to me. That could definitely be debated though.

**Comment by robloo** [comment]
So... the discussion was invalidated and we just merged as is?

**Comment by maxkatz6** [comment]
@robloo on both iOS and Android selection **handle** doesn't appear when input is focused. Only on second tap with a difference whether field is empty or not (Android will show the handle when empty, iOS will show the handle when there is some text).
This PR makes first common part better by not showing it immediately. 
I wouldn't keep this PR open until it gets platform specific implementations to complete second part, as it's not planned now. 

We need an issue to track that though.

**Pull request merged**
