### PR TITLE
Rework how TextBlock skips redundant measure and arrange calls

### PR DESCRIPTION
**Pull request by Gillibald**
## What does the pull request do?

This PR attempts to improve the logic that skips the creation of new TextLayouts when Measure or Arrange is called.

Previously we only tested for smaller widths. This PR tests for changes to the constraining size in general.

## Checklist

- [x] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/avalonia-docs with user documentation

### CODE REVIEW

**Review by MrJul — APPROVED** [review]
LGTM!

**Review by MrJul — APPROVED** [review]

**Comment by adirh3** [comment]
@Gillibald FYI since this PR I am getting crashes on `InvalidOperationException` with message `Invalid size returned for Measure.` in `Layoutable` line `387`.
I can't properly reproduce it, it happens randomly when I show my window when a `TextBlock` with `opacity=0.5` cause a re-render of it's parent `DockPanel` which contains another `TextBlock` with `FontSize="{DynamicBinding IconSize}"` and during `Measure` have `FontSize` is set to `NaN` which cause it to crash.

**Comment by Gillibald** [comment]
We need to cover this in a unit tests that sets the FontSize to NaN

**Comment by adirh3** [comment]
> We need to cover this in a unit tests that sets the FontSize to NaN

So you know how to repro this? If not I can try make something or capture process dump if it helps

**Comment by adirh3** [comment]
@Gillibald if it helps, it seems like the control is not even attached to visual tree.
But I don't understand why it's being measure, I caught it during debug -
image
It crashes internally in `Measure` when the `DesiredSize` is invalid, due to it not being attached -> bindings are not working.

**Pull request merged**
