### PR TITLE
Fix offset window position

### PR DESCRIPTION
**Pull request by ngarside**
## What does the pull request do?

Moves the window position 7 pixels to the left on Windows 10 & 11 (only with fully decorated windows).

## What is the current behavior?

Windows 10 & 11 add a 7 pixel invisible border on the left/right/bottom of windows for resizing. This means that windows are always offset by 7 pixels to the right (i.e. setting `Window.Position` to `(0,0)` actually places it at `(7,0)`.

Untitled
(position set to `(0,0)`)

## What is the updated/expected behavior with this PR?

Windows are always placed in the correct position.

From what I can tell the 7 pixel value is hardcoded into the Windows theme and there isn't a way to read it, but it also never changes, so hardcoding it seems like the best/only solution.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018248-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by maxkatz6** [comment]
It seems to be possible to get this offset https://github.com/digitalcreations/MaxTo/issues/50#issuecomment-221178411

**Comment by ngarside** [comment]
Huh, somehow I missed that - have updated to calculate the border size rather than hardcode it.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018315-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by danwalmsley** [comment]
Lets not merge this until I have investigated this.

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0021407-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
