### PR TITLE
Add Avalonia.Fonts.Inter to Avalonia.Desktop.slnf

### PR DESCRIPTION
**Pull request by affederaffe**
## What does the pull request do?
Add the project Avalonia.Fonts.Inter introduced in #10293 to Avalonia.Desktop.slnf in order to be able to build desktop projects at all.

## What is the current behavior?
With only Avalonia.Desktop.slnf loaded, the project is not buildable.

## What is the updated/expected behavior with this PR?
Be able to build the project.

## How was the solution implemented (if it's not obvious)?
Add the relevant project to Avalonia.Desktop.slnf.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Breaking changes
None

## Obsoletions / Deprecations
None

### CODE REVIEW

**Comment by Gillibald** [comment]
What exactly depends on it?

**Comment by affederaffe** [comment]
https://github.com/AvaloniaUI/Avalonia/blob/621f3ed7670b4f6444ccf4c9f2771dca1ff6ac1a/samples/ControlCatalog/ControlCatalog.csproj#L32

**Review by maxkatz6 — DISMISSED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0030697-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by affederaffe** [comment]
Actually, shouldn't Avalonia.Themes.Fluent/Simple have a reference to Avalonia.Fonts.Inter instead of the ControlCatalog since they use it via "avares://"? With a fresh clone, running for example the GpuInterop example results in `Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Avalonia.Fonts.Inter, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.`

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0030705-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by maxkatz6** [comment]
> Actually, shouldn't Avalonia.Themes.Fluent/Simple have a reference to Avalonia.Fonts.Inter instead

No, it shouldn't. Inter font is an optional dependency. Fluent/Simple font family has fallback defined, which should be used if font wasn't found. But it fails in another place now, which needs to be fixed. @Gillibald was looking into it before iirc.

**Review by maxkatz6 — APPROVED** [review]

**Comment by Gillibald** [comment]
> > Actually, shouldn't Avalonia.Themes.Fluent/Simple have a reference to Avalonia.Fonts.Inter instead
> 
> No, it shouldn't. Inter font is an optional dependency. Fluent/Simple font family has fallback defined, which should be used if font wasn't found. But it fails in another place now, which needs to be fixed. @Gillibald was looking into it before iirc.

Y I need to rework some part of the asset loader to be able to try to load assets without throwing. In general theme packages should not reference the font package directly. Themes should build just fine without referencing the font package.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0030753-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Pull request merged**
