### PR TITLE
TreeView: improve navigation with Left and Right keys

### PR DESCRIPTION
**Pull request by DmitryZhelnin**
## What does the pull request do?

This PR improves UX when using keyboard for `TreeView` navigation.
This is default behavior of Windows Explorer, IDE Solution Explorer, WPF's TreeView, etc.
 
## What is the current behavior?

Pressing `Left` key on `TreeViewItem` that has no children or is not expanded does not move keyboard focus to the parent item.
Pressing `Right` key on `TreeViewItem` that has children and is expanded does not move keyboard focus to the first child item.

## What is the updated/expected behavior with this PR?

Pressing `Left` key on `TreeViewItem` that has no children or is not expanded moves keyboard focus to the parent item.
Pressing `Right` key on `TreeViewItem` that has children and is expanded moves keyboard focus to the first child item.

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0023553-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0023583-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0023630-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0023674-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
