### PR TITLE
Fix publish value

### LINKED ISSUE #14753: BindingExpression has not been started
## Describe the bug
Haven't found the exact place but binding errors do not report properly in some cases and crash the application.
```
System.InvalidOperationException: BindingExpression has not been started.
   at Avalonia.Data.Core.UntypedBindingExpressionBase.GetValue()
   at Avalonia.Data.Core.UntypedBindingExpressionBase.PublishValue(Object value, BindingError error)
   at Avalonia.Data.Core.BindingExpression.ConvertAndPublishValue(Object value, BindingError error)
   at Avalonia.Data.Core.BindingExpression.OnNodeError(Int32 nodeIndex, String error)
   at Avalonia.Data.Core.ExpressionNodes.ExpressionNode.SetError(String message)
   at Avalonia.Data.Core.ExpressionNodes.LogicalAncestorElementNode.TrackedControlChanged(ILogical control)
   at Avalonia.Reactive.AnonymousObserver`1.OnNext(T value)
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value)
   at Avalonia.LogicalTree.ControlLocator.ControlTracker.Detached(Object sender, LogicalTreeAttachmentEventArgs e)
   at Avalonia.StyledElement.OnDetachedFromLogicalTreeCore(LogicalTreeAttachmentEventArgs e)
   at Avalonia.StyledElement.OnDetachedFromLogicalTreeCore(LogicalTreeAttachmentEventArgs e)
   at Avalonia.StyledElement.OnDetachedFromLogicalTreeCore(LogicalTreeAttachmentEventArgs e)
   at Avalonia.StyledElement.OnDetachedFromLogicalTreeCore(LogicalTreeAttachmentEventArgs e)
   at Avalonia.StyledElement.OnDetachedFromLogicalTreeCore(LogicalTreeAttachmentEventArgs e)
   at Avalonia.StyledElement.OnDetachedFromLogicalTreeCore(LogicalTreeAttachmentEventArgs e)
   at Avalonia.StyledElement.OnDetachedFromLogicalTreeCore(LogicalTreeAttachmentEventArgs e)
   at Avalonia.StyledElement.OnDetachedFromLogicalTreeCore(LogicalTreeAttachmentEventArgs e)
   at Avalonia.StyledElement.OnDetachedFromLogicalTreeCore(LogicalTreeAttachmentEventArgs e)
   at Avalonia.StyledElement.Avalonia.LogicalTree.ILogical.NotifyDetachedFromLogicalTree(LogicalTreeAttachmentEventArgs e)
   at Avalonia.Controls.TopLevel.HandleClosed()
   at Avalonia.Controls.WindowBase.HandleClosed()
   at Avalonia.Controls.Window.HandleClosed()
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.WindowImpl.WndProcMessageHandler(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
```

## To Reproduce
Have a binding error. 
I guess it has something to do with the lifetime of the control. If the property has not yet been initialized and it errors then it fails.
I could repro it either by opening the app or closing it down.
The case when opening has been fixed by using ReflectionBinding. But this was probably just hiding the issue.

## Expected behavior
Don't crash, report the error.

## Environment 

- OS: Windows
- Avalonia-Version: 11.1.999-cibuild0045352-beta - latest master version as of today

### PR DESCRIPTION
**Pull request by ltetak**
## What does the pull request do?
I don't understand this code at all but it seems PublishValue can be called in some cases (binding error published with UnsetValue) even if the BindingExpression is not started. We should probably proactively start it.
Should fix https://github.com/AvaloniaUI/Avalonia/issues/14753

## What is the current behavior?
Crash

## What is the updated/expected behavior with this PR?
No crash + binding to UnsetValue + binding error

## How was the solution implemented (if it's not obvious)?
Probably incorrectly fixed but describes the problem.
I based this on another PR - please check just the second commit. Sorry for that (I need a CI build)

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/avalonia-docs with user documentation

## Breaking changes
none

## Obsoletions / Deprecations
none

## Fixed issues
https://github.com/AvaloniaUI/Avalonia/issues/14753

### CODE REVIEW

**Comment by ltetak** [comment]
This still does not work reliably. It sometimes fails when closing the window. 
The Error being set is "Ancestor not found." So I guess any reference to the parent control will crash on window close due to this.

**Comment by workgroupengineering** [comment]
@ltetak  maybe you forgot to change the branch, Commit cedbdeaeea3faf2005c6a6f03c2d8040d9eb7c56 is PR #14782

**Comment by grokys** [comment]
I think the correct fix is to make calling `PublishValue` on a non-running binding expression a no-op. Please see https://github.com/AvaloniaUI/Avalonia/pull/15170 for what I think is a reasonable fix.

**Comment by maxkatz6** [comment]
@grokys @ltetak I guess, this PR can be closed?

**Pull request closed without merging**
