### PR TITLE
Dialogs rework

### PR DESCRIPTION
**Pull request by kekekeks**
Implementation of what was discussed in https://github.com/AvaloniaUI/Avalonia/issues/2052

Dialogs are now parent-modal on all platforms and properly set window parent. Other app windows aren't affected. 

This also introduces "moves with the parent" effect native to OSX.

### CODE REVIEW

**Comment by Gillibald** [comment]
Isn't Application.Current.MainWindow the common parent of a dialog and therefore could be the default?

**Comment by kekekeks** [comment]
Consider the following scenario:

- User is running on Linux with restrictive WM that refuses activation requests from background windows and just adds a special animation for window icon in the task bar.
- Application has two windows, main window is currently in background, user is interacting with a secondary window
- User click a button, application shows a dialog with MainWindow as a parent
- User doesn't see the dialog

**Comment by kekekeks** [comment]
Also, child windows on OSX are moved with the parent. That will introduce a weird interaction.

**Comment by kekekeks** [comment]
BTW, I generally against `Application.MainWindow` and `Application.Windows`. Those are global variables and should be considered a bad design.

**Review by danwalmsley — APPROVED** [review]
LGTM

**Pull request merged**
