### PR TITLE
X11: map super to win key

### PR DESCRIPTION
**Pull request by yatli**
see: https://askubuntu.com/questions/19558/what-are-the-meta-super-and-hyper-keys

relevant issue: https://github.com/yatli/fvim/issues/57

### CODE REVIEW

**Comment by kekekeks** [comment]
The key mappings are a bit weird. On my laptop the Win key is reported as KEY_LEFTMETA by evdev, but as Super_L by X11. Not sure how exactly we should name this key.

**Comment by yatli** [comment]
@kekekeks if you use a MacBook, there’s perhaps one layer of remapping somewhere, swapping alt(meta) and command(super)

**Comment by kekekeks** [comment]
On my machine Alt is reported as `KEY_LEFTALT`/`Alt_L`. It seems that `Meta` key is no longer in use on modern hardware.

Qt has even more weird [modifier mappings](https://doc.qt.io/qt-5/qt.html#KeyboardModifier-enum): 
>On macOS, the ControlModifier value corresponds to the Command keys on the keyboard, and the MetaModifier value corresponds to the Control keys. The KeypadModifier value will also be set when an arrow key is pressed as the arrow keys are considered part of the keypad.
>
>On Windows Keyboards, Qt::MetaModifier and Qt::Key_Meta are mapped to the Windows key.

**Comment by kekekeks** [comment]
GTK maps `Command` to Meta_L
https://github.com/GNOME/gtk/blob/7869ffbb49cf99fcf7c4a7f1b4925262991d1e5d/gdk/quartz/gdkkeys-quartz.c#L122

**Comment by yatli** [comment]
so it looks like the UI frameworks create enum entries for "Meta", but it's actually different from `Meta_L` defined in the X11 table.

**Comment by kekekeks** [comment]
From what I'm seeing, it's framework-specific and is a big mess in general.

**Comment by yatli** [comment]
I think it's wise that Avalonia simply use "LWin", "RWin" and avoid all that metaness.

**Comment by yatli** [comment]
...but anyway, X11 always report win keys as "Super" -- I'm pretty sure for that.

**Pull request merged**
