### PR TITLE
fixes: TrayIcon should be re-added when the Explorer is restarted

### PR DESCRIPTION
**Pull request by rmbadmin**
## What does the pull request do?
TrayIcon should be re-added when the Windows Explorer is restarted

## What is the current behavior?
After explorer crashes or restarts , the TrayIcon  will disappear

## What is the updated/expected behavior with this PR?
Run the Avalonia samples project, restart the explorer process and make sure the TrayIcon is still there

## How was the solution implemented (if it's not obvious)?
Rely Win32 [RegisterWindowMessage](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-registerwindowmessagea) 
Listen for re-added TrayIcon when TaskbarCreated

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=6982) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=6982) before we can accept your contribution.<br/><br/>:x: rmbadmin [sign now](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=6982)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/AvaloniaUI/Avalonia?pullRequest=6982) it.</sub>

**Comment by grokys** [comment]
Ping @danwalmsley

**Review by jmacato — DISMISSED** [review]
please clear up the formatting changes and merge conflict

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019158-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0020024-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0020137-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
