### PR TITLE
Adding setter to Application.DataTemplates

### PR DESCRIPTION
**Pull request by amkherad**
Allowing IoC containers to inject value into property.

### CODE REVIEW

**Comment by grokys** [comment]
If we're going to do this here, we should also do it on `Control`. In addition, being able to set it only once feels like a hack.

Before we move forward on this, could you explain why you need an IoC container to inject values into `Application.DataTemplates`? I've never come across such a thing being done? As far as I'm aware this wouldn't be supported in WPF/UWP either, right?

**Comment by Gillibald** [comment]
In WPF you can always add a merged dictionary to the application resources. All my applications register templates that way and it is working fine. Why isn't Application.DataTemplates internal? What is the usecase of that property? How are resources (Data Template's) resolved?

**Comment by grokys** [comment]
> Why isn't Application.DataTemplates internal? What is the usecase of that property?

Sorry, not sure I understand. How would you add data templates if it was made internal?

>  What is the usecase of that property?

It's used for adding application-wide data templates. 

> How are resources (Data Template's) resolved?

They are searched in the `DataTemplates` property of each control and then in `Application.DataTemplates`.

Are you asking why `DataTemplate`s aren't looked up in `Resources` like in WPF? That's because `Resources` is an unordered bag of key/values. WPF doesn't allow applying `DataTemplate`s to interfaces, but I wanted to allow that (it's something I miss in WPF) but to do that you need ordering, because otherwise the interface that is matched will depend on the non-deterministic order that data templates are retrieved from the resources.

**Comment by grokys** [comment]
The problem with making things like `DataTemplates` settable is that the `DataTemplates` class is an `AvaloniaList<>` which implements `INotifyCollectionChanged`. Which means that if someone subscribes to collection changed notifications on it, and then it's changed they will stop receiving changed notifications.

Now that may not be a big problem in practise, I'm not sure - but it _feels_ likely that it will bite someone at some point, and _feels_ like bad practise. So I'd like to understand why making `DataTemplates` settable is required, and whether we could come up with another solution that doesn't have the same potential problem

**Comment by Gillibald** [comment]
I think there should be some way to add and remove a collection of templates in a elegant way like you can do with MergedResourceDictionary.

You can alway have your own collection of templates and add remove them from DataTemplates but that would produce notification event if you don't do it properly. 

We don't need a setter for that scenario.

**Comment by danwalmsley** [comment]
@amkherad please could you explain what you are trying to achieve, are you trying to add templates from a dynamically loaded assembly (plugin) or something like that? If we know what you want to do from a higher level there might already be a better way to do it.

**Comment by Gillibald** [comment]
What is the benefit of replacing DataTemplates with your own instance instead of just adding values to the existing one?

**Comment by grokys** [comment]
I'm going to close this as there's been no further discussion and I'm not convinced by the approach here. Thanks for the PR anyway, and feel free to reply if you think we should continue along this path.

**Pull request closed without merging**
