### PR TITLE
Fixed double value validation in RangeBase

### PR DESCRIPTION
**Pull request by HermanKirshin**
## What does the pull request do?
Slider has problems in specific cases. 

## What is the current behavior?
This check always returns true. Value validation in RangeBase.Value setter currently does not work and setter logic can be triggered with NaN value

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0024821-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]

**Comment by maxkatz6** [comment]
@HermanKirshin hi!  Seems you disallowed write access to the branch in your repository for avalonia maintainers (there is an option when PR is created). So I can't update this branch in order to merge. 
Can you either allow write access or update your branch manually (merge master into it)?

**Comment by HermanKirshin** [comment]
@maxkatz6  I had updated the branch

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0024831-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
