### PR TITLE
Improved text wrapping performance

### PR DESCRIPTION
**Pull request by MrJul**
## What does the pull request do?

This PR optimizes text layout when wrapping is enabled.

There are two main changes:

 - CPU: avoid calling `FetchTextRuns` in `TextFormatterImpl.FormatLine` only to continue wrapping previously shaped runs. The results were already completely discarded in this case: let's completely avoid processing instead. This saves a **lot** of CPU time. The method code has been reorganized to make that path clearer.

- Memory: made `LineBreak.RemainingRuns` an implementation detail of `TextFormatterImpl` by removing them from `TextLineBreak`. A new internal `WrappingTextLineBreak` class is introduced instead. The remaining runs are cleared once they're processed instead of staying in memory for the whole `TextLine` lifetime and their containing list can be reused.

## Perf changes

Benchmarks with changes:

|                Method |  Wrap |  Trim |     Before |      After | Change |
|---------------------- |------ |------ |-----------:|-----------:|-------:|
|       BuildTextLayout |  True | False | 1,414.2 us |   534.7 us |   -62% |
| BuildEmojisTextLayout |  True | False | 7,039.2 us | 1,545.2 us |   -78% |
|       BuildTextLayout |  True |  True | 1,552.2 us |   580.3 us |   -63% |
| BuildEmojisTextLayout |  True |  True | 7,318.1 us | 1,576.7 us |   -78% |

### CODE REVIEW

**Comment by Gillibald** [comment]
The next step will be to reuse the ShapedRuns via some external cache. So we will be able to keep shaped data during multiple measure / arrange calls if the text source doesn't change but the constraint.

Signature of FormatLine will look like so: 
`TextLine FormatLine(ITextSource textSource, int firstTextSourceIndex, double paragraphWidth, TextParagraphProperties paragraphProperties, TextLineBreak? previousLineBreak = null, ShapedRunCache? shapedRunCache)` 

Shaped runs can be added to that cache and could be reused.

**Comment by MrJul** [comment]
That would be pretty nice! (The `TextLayout` itself could keep a cache of its previous runs.)

It would definitely improve raw performance while re-layouting. In addition to that, `ShapedRun` and `GlyphRun` are pretty large objects and can contribute to significant garbage collections when discarded.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0029317-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Review by Gillibald — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0029329-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Pull request merged**
