### PR TITLE
Introduce Typeface.Stretch and rework Typeface fallback selection

### PR DESCRIPTION
**Pull request by Gillibald**
## What does the pull request do?

This adjusts our Typeface fallback algorithm to match this behavior: https://drafts.csswg.org/css-fonts-4/#font-matching-algorithm

## What is the updated/expected behavior with this PR?
Screenshot 2021-10-27 072352

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

### CODE REVIEW

**Comment by grokys** [comment]
Just tried this out and added:

```
<TextBlock FontStretch="UltraCondensed">
    Hello World!
</TextBlock>
```

To the `MainWindow.xaml` in Sandbox, but I don't see any difference. What am I missing?

**Comment by Gillibald** [comment]
This is expected because not all font stretches are supported. There is not a single font family that I know that supports all stretch values.

On Google fonts you can filter by font width to find a font that matches a specific stretch value.

https://fonts.google.com/?width=1

 I think this is kind of outdated tech. Today there are variable fonts that support a greater variety of customization.

**Review by grokys — APPROVED** [review]
I can't say I know enough about fonts to judge its correctness then, but you do, so let's get this merged if you can fix the conflict @Gillibald

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018908-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018908-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
