### PR TITLE
Fix CalendarDatePicker two way binding syntax.

### LINKED ISSUE #13000: CalendarDatePicker popout displays incorrect date highlight if SelectedDate set through another means.
**Describe the bug**
Once you've used the popout to select a date, it will continue to highlight that date even if you've changed SelectedDate through some other means (such as code-behind event handlers).

**To Reproduce**

1. Open the popout and select a date
2. Change the SelectedDate property through code (in my case, from a button click event handler)
3. Open the popout again
4. You will see that the popout highlights the last date selected through the popout, not the SelectedDate property

**Expected behavior**
The popout should always highlight whichever date is assigned to the SelectedDate property when it is opened.

**Screenshot**
Avalonia CalendarDatePicker Incorrect Date Highlight

### PR DESCRIPTION
**Pull request by rabbitism**
## What does the pull request do?
Fix #13000

<del>Question: Can I assume that `{TemplateBinding XX Mode=TwoWay}` won't work at all? If so we need to check if we have similar issue in entire fluent/simple theme. </del>

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/avalonia-docs with user documentation

## Breaking changes

No.

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0040247-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by rabbitism** [comment]
This should be considered as a temporary fix, and the root cause is Calendar.SelectedDate value precedence. Please close this if someone finds a way to fix it permanently.

**Comment by maxkatz6** [comment]
@rabbitism I assume the original issue was also fixed by https://github.com/AvaloniaUI/Avalonia/pull/13087, right? So this PR can be closed.

**Comment by rabbitism** [comment]
> @rabbitism I assume the original issue was also fixed by https://github.com/AvaloniaUI/Avalonia/pull/13087, right? So this PR can be closed.

No, separate issue. 
That was discovered when i try to understand what templatebinding is doing. But not related to this one.

**Review by maxkatz6 — APPROVED** [review]

**Pull request merged**
