### PR TITLE
Android - Fix more IME bugs

### PR DESCRIPTION
**Pull request by emmauss**
## What does the pull request do?
Fixes bugs relating to the preedit text. TextPresenter now tracks the composing region. Changing the cursor now commits the current composing text, and clearing a currently composing word deletes the original word.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

### CODE REVIEW

**Comment by Gillibald** [comment]
Does iOS need that special composition region handling? If no other platform needs that API we need a way to solve that in the platform implementation instead of introducing new API's

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0026377-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by emmauss** [comment]
> Does iOS need that special composition region handling? If no other platform needs that API we need a way to solve that in the platform implementation instead of introducing new API's

iOS also sends the text range when setting the marked texts. That range is currently unused in the iOS text input responder.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0026615-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by Gillibald** [comment]
The preedit range is always at the current caret position. Changing selection during composition should not be allowed for now.

So if we enter composition we disable pointer or keyboard navigation until the composition is committed or canceled.

When we commit text we need to do the following:
- reset preedit
- move the cursor to the replacement region start
- delete replaced region
- insert committed text
- move the cursor to the end of the committed text

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0026628-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by seikosantana** [comment]
Wny reason why this ends up closed? I really wish i could use Avalonia for something im about to start, but this IME part is going to be scary if it crashes just for this issue

**Comment by Gillibald** [comment]
I am doing a cleanup of the current IME implementation on all platforms next week. So this will be fixed an a different way.

**Comment by seikosantana** [comment]
I'm very glad to know that.

I just gave avalonia a try yesterday and so far I'm liking it a lot, so I am thinking to use avalonia for a new project i'm about to start writing, but Android app is the focus. Seeing this IME problem I was a bit afraid about using it for Android app development but if the fix can arrive next week i'm glad to try out stuff again 😄

**Pull request closed without merging**
