### PR TITLE
Pass parent's service provider to the StyleInclude, so parents stack is complete

### PR DESCRIPTION
**Pull request by maxkatz6**
## What does the pull request do?

Currently for each StyleInclude/ResourceInclude we need to create a new root service provider, which returns an empty stack of parents. It breaks some markup extensions in a very corner case, see https://github.com/AvaloniaUI/Avalonia/pull/8680.

With this PR:
- We pass IServiceProvider to the runtime loader
- We generate XAML methods that accept IServiceProvider as well
- Works with XAML-only and XAML-with-class files
- No existing code should be affected

## Checklist

- [x] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Fixed issues

Fixes https://github.com/AvaloniaUI/Avalonia/pull/8680

### CODE REVIEW

**Comment by maxkatz6** [comment]
This PR is ready to review, but marking it as WIP only because [target PR](https://github.com/AvaloniaUI/Avalonia/pull/9537) wasn't yet merged

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0026763-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-nightly/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0026786-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-nightly/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0026882-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-nightly/nuget/v3/index.json) [PRBUILDID]

**Review by grokys — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0027002-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-nightly/nuget/v3/index.json) [PRBUILDID]

**Pull request merged**
