### PR TITLE
[TextBox] Add page keyboard navigation

### LINKED ISSUE #4202: TextBox and scrolling via PgUp & PgDn
Hi guys,

it seems that TextBox does not handle PgUp & PgDn keyboard strokes 
https://github.com/AvaloniaUI/Avalonia/blob/cda455edfdc6ec684d0f7f1419e77ab225d24e94/src/Avalonia.Controls/TextBox.cs#L514 

Am I correct?
Cheers

### PR DESCRIPTION
**Pull request by nicola36631**
## What does the pull request do?
Implements handling of PageLeft (SHIFT+PgUp), PageRight (SHIFT+PgDn), PageUp (PgUp), PageDown (PgDn) for the TextBox class
TextBoxPageHandling

## What is the current behavior?
The current TextBox does not handle PgUp and PgDn keys, doing nothing when pressed.

## What is the updated/expected behavior with this PR?
TextBox will now scroll the ScrollViewer accordingly:
- PageLeft (SHIFT+PgUp) will scroll the TextBox child ScrollViewer one page to the left WITHOUT changing the caret position
- PageRight (SHIFT+PgDn) will scroll the TextBox child ScrollViewer one page to the right WITHOUT changing the caret position
- PageUp (PgUp) will scroll the TextBox child ScrollViewer one page to the top WITHOUT changing the caret position
- PageDown (PgDn) will scroll the TextBox child ScrollViewer one page to the bottom WITHOUT changing the caret position

## How was the solution implemented (if it's not obvious)?
Added PageLeft, PageRight, PageUp, PageDown KeyGestures in PlatformHotkeyConfiguration, added handling in TextBox in OnKeyDown, added method FetchChildScrollViewer to fetch the visual child ScrollViewer and call its al;ready ready Page... method.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Breaking changes
None

## Obsoletions / Deprecations
None

## Fixed issues
Fixes #4202

### CODE REVIEW

**Comment by nicola36631** [comment]
@dotnet-policy-service agree

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0032712-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by Gillibald** [comment]
Please introduce a `PART_ScrollViewer` and get a reference to the ScrollViewer in the `OnApplyTemplate` override. By introducing these page gestures the ScrollViewer because mandatory.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0032716-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by robloo** [comment]
> the ScrollViewer because mandatory.

In most controls missing template parts should fail gracefully if possible. In this case it would probably be nice for backwards compatibility as well.

I would just still get the reference in OnApplyTemplate, but then before using it always do a null check (which is how the code is currently written anyway). So the `PART_ScrollViewer` isn't mandatory and if its missing this page up/down functionality is simply disabled.

Also don't forget the TemplatePart attribute on the TextBox control after this.

**Comment by nicola36631** [comment]
@Gillibald why do you say that the ScrollViewer has become mandatory?
If there isn't one (or max search depth is reached) null is returned and the MovePage... methods simply return gracefully.

**Comment by robloo** [comment]
@nicola36631 Can you implement the requested changes adding the template part and getting it within OnApplyTemplate? That should simplify this and close the additional linked issue as well (don't forget to add the fixes note for that too).

I think it should be about ready after that.

**Comment by Gillibald** [comment]
Since there was no response from @nicola36631 for a long time I will take over the PR and make the adjustments myself

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0036020-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Pull request merged**
