### PR TITLE
Feature/url handling

### PR DESCRIPTION
**Pull request by danwalmsley**
## What does the pull request do?

image

Allows your application to handle custom urls on OSX (and other platforms)

## What is the current behavior?

Only win32 and linux can currently implement this as OSX uses a specific api.

## What is the updated/expected behavior with this PR?

Added an event to Application that is raised when urls are opened on OSX.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

### CODE REVIEW

**Comment by maxkatz6** [comment]
Couple of moments from me.
1. App can be opened with protocol/arguments. And it can be activated again in runtime. Does Win32 support activation in runtime?
2. In UWP we have way more complex system of activation kinds/protocols. Win32 has simper model (file, protocol, command args...?), but it's still might not fit into "array of Uri's string".
3. Does it includes notification activation, if native notifications will be implemented some day?
4. Should it be build-in Avalonia (it extends responsibility of UI framework) or shipped as separated cross-platform library/app-host-framework?

I am not saying that we need to support everything from the beginning, but it could be flexible enough to add some new activation kind later.

Related specs from Project Reunion (COM-based library that wraps and uses both win32 and winrt api depending on availability, we can use it as a reference for our implementations as well):
https://github.com/microsoft/ProjectReunion/blob/c88d449a3a8149959831e7e121d4f9f10dab2287/specs/AppLifecycle/Activation/AppLifecycle%20Activation.md
https://github.com/microsoft/ProjectReunion/issues/111

**Comment by robloo** [comment]
This probably shouldn't be using a string and should be generalized to accept a URI as well.

https://docs.microsoft.com/en-us/dotnet/api/system.uri?view=net-5.0

**Comment by kekekeks** [comment]
>Does Win32 support activation in runtime?

No, it doesn't. We need to support single-instance application mode and pass args alongside with activation command.

> Win32 has simper model (file, protocol, command args...?)

It's application's responsibility to parse command line arguments if it wants to handle something more complex than the list of files. That's why we aren't using `Environment.GetCommandLineArgs()` and use arguments passed to `StartWithClassicDesktopLifetime()`

>Does it includes notification activation, if native notifications will be implemented some day?

How exactly are notifications related to file and uri associations?

>Should it be build-in Avalonia (it extends responsibility of UI framework) or shipped as separated cross-platform library/app-host-framework?

Qt raises [QFileOpenEvent](https://doc.qt.io/qt-5/qfileopenevent.html) on `QApplication` when it gets file open request from OSX. So, yes, it is definitely  the responsibility of the UI toolkit.

>This probably shouldn't be using a string and should be generalized to accept a URI as well.

Qt uses plain string and most likely does that for a reason. Command line might contain something that's not a valid URI, it's application's responsibility to handle that, not ours.

**Comment by maxkatz6** [comment]
> How exactly are notifications related to file and uri associations?

Notification's action-button callback. In WinRT/UWP app model it usually was described as URI arguments handled by application in runtime and/or triggered new application instance and handled during initial activation. There is no fundamental difference between [notification-uri-arguments](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/send-local-toast#activation-in-depth), [protocol-link](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/handle-uri-activation#step-3-handle-the-activated-event), [command-line](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.activation.commandlineactivatedeventargs?view=winrt-19041#examples) or [file-open](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/handle-file-activation#step-3-handle-the-activated-event) activation there, and I don't see it in general (apart from different args types). Everything is handled by OnActivated with specified Kind value and casting arguments to related args type.
Again, I am not asking to handle all possible activation kinds now, and I am not planning to ask them in the future, but do we really want to limit API with only couple of the most popular variants, if we want UI framework to handle them at all?

> Command line might contain something that's not a valid URI, it's application's responsibility to handle that, not ours.

I suppose in that case it could has different type from file/protocol activation, not mixed with UrlOpenedEventArgs. AFAIK it's already handled differently with this PR.

> It's application's responsibility

Yes, it's important to define line between application and UI framework responsibilities in activation kinds handling.

**Review by kekekeks — APPROVED** [review]

**Comment by kekekeks** [comment]
We'll get back to unifying activation when we start working on notification API. The current way of handling urls can be gradually deprecated if needed.

**Pull request merged**
