### PR TITLE
Exposing `Window.ChildWindows` collection

### LINKED ISSUE #7620: OwnedWindows Property
**Is your feature request related to a problem? Please describe.**
There's not a way to directly access all child windows from the parent.
Currently, we have to access all windows and check their parent.

**Describe the solution you'd like**
Similar to this: https://docs.microsoft.com/en-us/dotnet/api/system.windows.window.ownedwindows?view=windowsdesktop-6.0

### PR DESCRIPTION
**Pull request by pr8x**
Exposing`Window.ChildWindows` collection

Fixes https://github.com/AvaloniaUI/Avalonia/issues/7620

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018766-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018779-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by MarchingCube** [comment]
@AvaloniaUI/core I guess we might want to keep WPF compat and call this `OwnedWindows`?

**Comment by danwalmsley** [comment]
> @AvaloniaUI/core I guess we might want to keep WPF compat and call this `OwnedWindows`?

Yup.

@pr8x please rename? if not I can do it in a couple of days.

**Comment by danwalmsley** [comment]
> > @AvaloniaUI/core I guess we might want to keep WPF compat and call this `OwnedWindows`?
> 
> Yup.
> 
> @pr8x please rename? if not I can do it in a couple of days.

done.

**Review by MarchingCube — APPROVED** [review]
LGTM.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018876-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
