### PR TITLE
Fixed issue where RowDetailsTemplate was getting the wrong DataContext

### LINKED ISSUE #12106: [DataGrid]: using RowDetailsTemplate with empty list sets wrong DataContext
**Describe the bug**

Hello,
When using a RowDetailsTemplate of a DataGrid with an empty ItemsSource the RowDetailsTemplate will have the parent DataContext set, which causes a crash.

**To Reproduce**

- Create an empty list of items
- Assign to a DataGrid
- Launch, nothing happens.
- Add a RowDetailsTemplate
- Launch => crash

(example project included)

**Expected behavior**

Nothing should happen, if there is no item, there is no reason the RowDetailsTemplate get's called.

**Example Project**

[DataGridBug.zip](https://github.com/AvaloniaUI/Avalonia/files/11990721/DataGridBug.zip)

In the example project, if you launch it will not crash because there is one item generated in the ItemListViewModel constructor.
If you comment this line it will crash with a 
`Unable to cast object of type 'DataGridBug.ViewModels.ItemListViewModel' to type 'DataGridBug.ViewModels.ItemViewModel'.`

**Informations**
- Avalonia Version 11.0.0

### PR DESCRIPTION
**Pull request by GundlackFlorian**
Hello,

in this [issue](https://github.com/AvaloniaUI/Avalonia.Controls.DataGrid/issues/66) i noticed that the RowDetailsTemplate was getting the wrong DataContext when the first measurement pass was done which could cause a InvalidCastException or a StackOverflow (if a ContentControl is used).

## What is the current behavior?

https://github.com/AvaloniaUI/Avalonia/blob/194044692eb3967b8c6bd0ed140a954f53b48e0e/src/Avalonia.Controls.DataGrid/DataGridRows.cs#L2967-L2977

Right now the `detailsContent.DataContext` is only changed if the dataItem is not null.
So when no list or an empty one is provided `detailsContent.DataContext` is not changed and it's still on the value provided by  `_rowsPresenter.Children.Add(detailsContent);` (which is the DataContext of the DataGrid).

## What is the updated/expected behavior with this PR?

I removed the null check of the dataItem so:
- If the dataItem is set, `detailsContent.DataContext` will the item.
- If there no dataItem, the `detailsContent.DataContext` is set to null.

After this change the issues mentioned above are not happening anymore.
I tested setting the ItemsSource:
- Empty list -> works
- List with items -> works
- null -> works

Also no problem with RowDetailsVisibilityMode=Collapsed/Visible/VisibleWhenSelected

More details in the issue.

## Fixed issues
[Fixes AvaloniaUI/Avalonia.Controls.DataGrid#66](https://github.com/AvaloniaUI/Avalonia.Controls.DataGrid/issues/66)

### CODE REVIEW

**Comment by Gundz** [comment]
@dotnet-policy-service agree

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0037675-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by Gundz** [comment]
> You can test this PR using the following package version. `11.0.999-cibuild0037675-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

After testing with the build (i'm using the test project of the issue), the StackOverflow is fixed, but not the InvalidCastException.
I moved the `detailsContent.DataContext = dataItem` before the `_rowsPresenter.Children.Add(detailsContent)`.

**Comment by Gundz** [comment]
11.0.999-cibuild0037679-beta works !

**Review by grokys — APPROVED** [review]

**Pull request merged**
