### PR TITLE
[WIP] Add Text shadow

### LINKED ISSUE #6208: Feature request: text-shadow property
**Is your feature request related to a problem? Please describe.**

Right now it's not possible to implement text with a shadow, unless you define second text block with some offset.

**Describe the solution you'd like**
[TextShadows](https://www.w3schools.com/cssref/css3_pr_text-shadow.asp) similarly how we have BoxShadows

**Describe alternatives you've considered**
Drop shadow for any type of geometry - https://github.com/AvaloniaUI/Avalonia/issues/6207

**Additional context**
It seems even in Skia we have to render text twice manually, but at least we can do it on lower level. [#1](https://groups.google.com/g/skia-discuss/c/iPuPYVUjcLE) [#2](https://stackoverflow.com/questions/48838584/drop-shadow-or-edge-on-text-using-skiasharp)

UPD:
For now it's not that hard to implement simple shadow support with a custom text block control
https://gist.github.com/maxkatz6/24be64ceb9e0b395caa11a69c725658a

### PR DESCRIPTION
**Pull request by emmauss**
## What does the pull request do?
Add text shadow support to TextBlock. This is defined with the  TextShadowBrush, TextShadowXOffset, TextShadowYOffset properties. The API isn't final.
@Gillibald 

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Fixed issues
Fixes #6208

### CODE REVIEW

**Comment by Gillibald** [comment]
You should not add effect-specific properties to TextBlock or TextRunProperties. The only acceptable way of adding effects to text rendering is via https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.textformatting.textrunproperties.texteffects?view=windowsdesktop-6.0

A TextEffect can be applied to any character inside a TextRun. Ideally, these effects are implemented via https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/graphics/skiasharp/effects/image-filters, etc. So in the end we just apply an image filter during the draw step.

**Comment by maxkatz6** [comment]
@Gillibald it seems TextEffects is not used for text shadow in WPF, but Control.Effects is https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/how-to-create-text-with-a-shadow?view=netframeworkdesktop-4.8

Also what do you think about css-like api, since we already started using boxshadows api? 
https://github.com/AvaloniaUI/Avalonia/issues/6208

**Comment by Gillibald** [comment]
> @Gillibald it seems TextEffects is not used for text shadow in WPF, but Control.Effects is https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/how-to-create-text-with-a-shadow?view=netframeworkdesktop-4.8
> 
> Also what do you think about css-like api, since we already started using boxshadows api? #6208

`text-shadow` is a collection of shadows so `TextEffects` would be the better fit here
`text-shadow: 1px 1px 2px red, 0 0 1em blue, 0 0 0.2em blue;`

WPS's `Control.Effect` is a bitmap effect and is applied to the produced drawing of that control. This works via visual to geometry conversion. We could do the same.

**Comment by robloo** [comment]
Don't forget WPF's Bitmap Effects were later considered a bad idea and deprecated. https://docs.microsoft.com/en-us/dotnet/desktop/wpf/graphics-multimedia/bitmap-effects-overview?view=netframeworkdesktop-4.8

**Pull request closed without merging**
