### PR TITLE
Disabled button can be pressed issue/bug

### LINKED ISSUE #6957: Disabled button can be pressed
**Describe the bug**
Button stays focused when IsEnabled set to false and can process keyboard ENTER event.

**To Reproduce**
Run this window and follow the screen instructions:
```
 public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
#if DEBUG
            this.AttachDevTools();
#endif
        }

        private void InitializeComponent()
        {
            AvaloniaXamlLoader.Load(this);

            var button = new Button
            {
                Content = "Tabulate to this button"
            };

            Content = button;
            button.GotFocus += (_, _) =>
            {
                button.IsEnabled = false;
                button.Content =
                    $"Now this button is disabled ({nameof(IsEnabled)}:{button.IsEnabled},{nameof(IsEffectivelyEnabled)}:{button.IsEffectivelyEnabled}), but you can still press Enter";
                button.Click += (_, _) =>
                {
                    button.Content = "It just has been clicked.";
                };
            };
        }
    }
```

**Expected behavior**
1) Probably focus must be moved away from the control once is has been disabled
2) Probably a control must not process input events once is has been disabled

**Screenshots**
image

**Desktop (please complete the following information):**

- OS: Linux
- Version 0.10.10

### PR DESCRIPTION
**Pull request by Abdesol**
## What does the pull request do?
Add IsEffectivelyEnabled condition to OnClick(from Button)

## What is the updated/expected behavior with this PR?
If a controller is disabled(IsEnabled set to false), The Click event won't fire(work) unless the button is enabled.

## Fixed issues
Fixes https://github.com/AvaloniaUI/Avalonia/issues/6957

### CODE REVIEW

**Comment by Abdesol** [comment]
I added the test in the sandbox. If I did the test in a wrong place, let me know.

**Comment by maxkatz6** [comment]
Thanks.
For tests you need to create a new test method in tests project. You can add it in this file https://github.com/AvaloniaUI/Avalonia/blob/master/tests/Avalonia.Controls.UnitTests/ButtonTests.cs
I think you can copy and edit this specific method https://github.com/AvaloniaUI/Avalonia/blob/master/tests/Avalonia.Controls.UnitTests/ButtonTests.cs#L273-L284 it already does what you need to test (raises click on some event). You just need to disable button in your test method and check that event was not raised.

p.s. it seems like these tests "Button_Invokes_CanExecute_When_CommandParameter_Changed" and "Raises_Click_When_AccessKey_Raised" are mixed, probably somebody renamed incorrectly by mistake.

**Comment by maxkatz6** [comment]
Also you can just push commits to the same branch, you don't need to recreate PR

**Comment by Abdesol** [comment]
oh my bad.
I made a mistake in the test the assert should have been 0 ; ( 
Let me fix that

**Review by maxkatz6 — APPROVED** [review]
Looks good to me

**Comment by maxkatz6** [comment]
Thanks!

**Pull request merged**
