### PR TITLE
Correct ReactiveUI.Events Package Id

### PR DESCRIPTION
**Pull request by worldbeater**
#### What does the pull request do?

This PR corrects the `<PackageId />` attribute for `Avalonia.ReactiveUI.Events` package added in https://github.com/AvaloniaUI/Avalonia/pull/4535. 

Also, after a conversation with @grokys the `Avalonia.ReactiveUI.Events.UnitTests` project was removed in order to improve developer experience (unit tests no longer require the `Events_Avalonia.cs` file which is generated at nukebuild time only). Thinking that we shouldn't test autogenerated code.

#### What is the current behavior?

Currently, there are two packages named `Avalonia.ReactiveUI` and this results in one of them not getting published.

#### What is the updated/expected behavior with this PR?

Now, the `Avalonia.ReactiveUI.Events` package has a unique id, so it is generated and should be published now.

### CODE REVIEW

**Comment by kekekeks** [comment]
>Thinking that we shouldn't test autogenerated code.

Are we still checking it for API compat? It should be fine then.

**Comment by worldbeater** [comment]
> Are we still checking it for API compat? It should be fine then.

No we don't. Tried adding `<Import Project="..\..\build\ApiDiff.props" />` but it gives me:

```
error NU1101: Unable to find package Avalonia.ReactiveUI.Events. 
No packages exist with this id in source(s): api.nuget.org, dotnet-eng
```

Probably this requires input from someone with admin access I guess, to publish an initial package version to compare?

**Comment by kekekeks** [comment]
@danwalmsley

**Comment by grokys** [comment]
I think that @worldbeater is right that we should only enable ApiDiff once the package is published.

**Review by grokys — APPROVED** [review]

**Comment by workgroupengineering** [comment]
error MSB3202: the project "C:\GitHub\Avalonia\tests\Avalonia.ReactiveUI.Events.UnitTests\Avalonia.ReactiveUI.Events.UnitTests.csproj" non è stato trovato. [C:\GitHub\Avalonia\Avalonia.sln]

**Comment by worldbeater** [comment]
Yeah forgot to remove the project from the `.sln` file. Probably would be awesome to have a CI check for that.

**Pull request merged**
