### PR TITLE
Validate DataTemplates on empty DataType

### LINKED ISSUE #724: Throw an Exception if DataTemplate with null DataType is added to DataTemplates collection
Id done this by mistake and it was difficult to track down.

Perhaps an error message hinting to use ContentTemplate, ItemTemplate instead would be nice.

### PR DESCRIPTION
**Pull request by maxkatz6**
## What does the pull request do?

If DataTemplate inside of DataTemplates doesn't have any DataType on it, this template will be inherited and used on absolutely every ContentPresenter down the tree causing unexpected behaviors.
This PR makes developer's mistake harder.

Personally, I think it would be better to have XAML compile time error, and I can do this instead. But in this case, we would lose validation for non-xaml applications. Unless this validation will be duplicated in two places.

## Checklist

- [x] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Breaking changes

If any code previously incorrectly used DataTemplates, it would now throw an exception.

## Fixed issues
Fixes https://github.com/AvaloniaUI/Avalonia/issues/724

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0020750-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by danwalmsley** [comment]
nooooooo! this is one of the most useful features IMO!

**Comment by danwalmsley** [comment]
@maxkatz6 are you sure there are not valid use cases for this?

**Comment by maxkatz6** [comment]
@danwalmsley it will work with no problems, if there is no nested content presenters with empty data template. I.e. data template with textblock will work, but data template with buttons will fail in stackoverflow.

I don't see any use cases, where DataTemplates without a type is a good idea and not a mistake.

**Review by grokys — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0021174-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
