### PR TITLE
added failing unit test for ItemsPresenter

### PR DESCRIPTION
**Pull request by donandren**
Ocasionaly some listboxes are not displaying the items after clear and add new items.
Added a unit test to represent that situation.

### CODE REVIEW

**Comment by donandren** [comment]
Commenting that line:
`_availableSpace = finalSize;`
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/VirtualizingStackPanel.cs#L77
is solving the problem for me

**Comment by grokys** [comment]
Actually you may be right that that is the fix. I'm worried it might break something else, but the fact that it doesn't break any unit tests makes me think that that line is a left-over from a previous version of the logic.

Have you seen any other breakage if you remove that line?

**Comment by donandren** [comment]
nope in the real app behaviour everything is working pretty fine, no issues with that.
Another solution to that problem can be to reset _availableSpace when items are changed.

**Comment by grokys** [comment]
Ok, lets try removing that statement and see what breaks! ;)

**Pull request merged**
