### PR TITLE
Schedule opening popup if cannot be opened right now

### LINKED ISSUE #4501: Popup with IsOpen set to True in xaml causes exception at runtime
When setting `IsOpen="True"` for a `Popup`, it throws because the visual tree is still initializing I think. Not sure if it's supposed to work.

## Repro

```xaml
<Popup IsOpen="True">
    <TextBlock Text="Hello World!" />
</Popup>
```

If placed as a direct child of `Window`, it doesn't show anything. If placed deeper in the tree, e.g.:

```xaml
<Window ...>
    <StackPanel>
        <Popup IsOpen="True">
            <TextBlock Text="Hello World!" />
        </Popup>
    </StackPanel>
</Window>
```

it throws:

```
System.InvalidOperationException: Attempted to open a popup not attached to a TopLevel
```

If set manually in the `Window` constructor, after `InitializeComponent` (`AvaloniaXamlLoader.Load(this)`) it works as expected.

### PR DESCRIPTION
**Pull request by ShadowDancer**
## What does the pull request do?
Allows setting `IsOpen` on popup, even when it is not attached to visual tree

## What is the current behavior?
Currently `Open()` throws exception if popup does not have `VisualRoot`

## What is the updated/expected behavior with this PR?
Setting `IsOpen` or calling `Open()` schedules opening popup after it is attached to window

## Checklist

- [x] Added unit tests (if possible)?

## Fixed issues
Fixes #4501

This can be tested here:
https://github.com/ShadowDancer/Avalonia/tree/fix/opening_notattached_popup_tests
After launching control catalog for net core popup will be displayed with text "AAAAAAAAA...".

### CODE REVIEW

**Comment by ShadowDancer** [comment]
I have tried to add tests for checking if popup opens when scheduled.

test like this:
```

        [Fact]
        public void Popup_Open_Without_Target_Should_Attach_Itself_Later()
        {
            using (CreateServices())
            {
                int openedEvent = 0;
                var target = new Popup();
                target.Opened += (s, a) => openedEvent++;
                target.IsOpen = true;

                var w = new Window { Content = content };
                w.ApplyTemplate();

                Assert.Equal(1, openedEvent);
            }
        }
```

however for some reason `ApplyTemplate` does not raise `OnAttachedToVisualTree` on my popup. In real app this is called. I cannot figure out why it's does not work.

**Comment by worldbeater** [comment]
@ShadowDancer try playing with the `TestRoot` class. ReactiveUI activation fetcher uses the `AttachedToVisualTree` event, so somewhat like the following code should totally work in your test case (when element is assigned to `TestRoot.Child`, the `AttachedToVisualTree` is published): https://github.com/AvaloniaUI/Avalonia/blob/0ecbe9186ac02e7c33201d4fbe9cccac18c8b23c/tests/Avalonia.ReactiveUI.UnitTests/AvaloniaActivationForViewFetcherTest.cs#L158-L163

**Comment by ShadowDancer** [comment]
@worldbeater thanks for help, this works for me!

**Review by grokys — APPROVED** [review]
Sorry, for the delay, LGTM!

**Pull request merged**
