### PR TITLE
Update SharpDX to version 3.1.0

### PR DESCRIPTION
**Pull request by wieslawsoltes**

### CODE REVIEW

**Comment by grokys** [comment]
Just out of interest, is there anything that will be useful in this release or are you updating just because?

**Comment by wieslawsoltes** [comment]
Looks like lots of small bug fixes and improvements https://github.com/sharpdx/SharpDX/releases/tag/v3.1.0 so I though it was worth updating.

**Comment by amerkoleci** [comment]
I've made some fixes on SharpDX side, so worth update tho.

**Comment by grokys** [comment]
Merged, thanks!

**Pull request merged**
