### PR TITLE
Updates to Viewbox

### LINKED ISSUE #7734: Viewbox doesn't align its content correctly
**Describe the bug**

Viewbox content is misaligned when compared to WPF (except is using `Stretch=None`):
image

Each example above is a 30x30 Border, hosting a Viewbox, hosting a TextBlock with my symbol font (but is repeatable with any content besides TextBlock). The background of the TextBlock is red, to show the alignment

It's not as bad if you make the Viewbox a little bigger (e.g., here 75x75), but there is still some mis-alignment:
image

**Desktop (please complete the following information):**

- OS: Windows
- Version 0.10.12

### PR DESCRIPTION
**Pull request by amwx**
## What does the pull request do?
Couple fixes to `Viewbox`:
- Made `UseLayoutRounding` default to false to fix alignment of the hosted visual (fixes #7734). Alignment now pretty much matches WPF
- I noticed there was a TODO in the source for having Viewbox use an internal control to host the child so the scale transform doesn't affect a user set transform, so I added that in.
`Viewbox` now inherits from `Control` rather than `Decorator`, and hosts an internal visual that the `Child` property is inserted into - following how WPF does it. This is a binary breaking change, but I don't think its a usage breaking change

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Obsoletions / Deprecations
Viewbox doesn't host child directly anymore. It will break some selectors.

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018983-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by jmacato — APPROVED** [review]
ViewBox tests passed, thanks for taking out another TODO item :) LGTM 👍

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019145-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019145-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by Kermalis** [comment]
Is this a fix for #2631 or #7750 ?

**Comment by MarchingCube** [comment]
@AvaloniaUI/core This was a usage breaking change since users relying on `Viewbox` hosting a child directly (for styling purposes or custom controls) got broken. After a session with dev tools I was able to figure why controls in my app broke after an update but we might want to add this to breaking changes list (or figure if we can do this with regular transforms).

**Comment by grokys** [comment]
I think probably the `_containerVisual` shouldn't be added to the logical tree at least.

**Comment by amwx** [comment]
> I think probably the `_containerVisual` shouldn't be added to the logical tree at least.

Probably, but the only problem is `Child` should be added to the logical tree, but you can't add it at the Viewbox level since `Decorator` (`_containerVisual`) does that when setting the `Child` property and you get the "Already has a parent" exception. I guess one solution would be to add a custom control instead of just `Decorator` that is the direct descendant of `Viewbox` and make that only add the child to the visual tree so `Viewbox` can be the logical parent.

**Comment by grokys** [comment]
Yeah the fact that `Decorator` is being added as a logical child has broken some styles, such as:

https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Themes.Fluent/Controls/ScrollViewer.xaml#L156

**Comment by grokys** [comment]
Opened an issue https://github.com/AvaloniaUI/Avalonia/issues/8092

**Pull request merged**
