### PR TITLE
Add ColorPicker Fluent ControlThemes

### PR DESCRIPTION
**Pull request by robloo**
## What does the pull request do?

Converts the ColorPicker's Fluent Styles to use ControlThemes. This includes the `ColorPicker`/`ColorView` as well as the primitives `ColorSpectrum`, `ColorSlider` and `ColorPreviewer`.

The default/simple styles are unmodified.

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0022423-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]

**Comment by maxkatz6** [comment]
LGTM

**Comment by maxkatz6** [comment]
@robloo if you don't mind, I will update default/simple theme as well.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0022527-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by robloo** [comment]
@maxkatz6 I don't want you to waste your time on simple stuff. I know these controls well and can update the default theme no problem. I just noticed no default themes were being updated in any other controls so thought they were intentionally being skipped. I guess not? Is there is a plan to update all default themes?

The only point to discuss is whether it's worth it to duplicate all the TextBox, TabControl, etc. control templates in the default theme. I left a comment I'm sure you saw, but unless these are each copied over ColorPicker doesn't work in the default/simple theme. It seems like wasted work to get such a high-level control working on default theme too (default has no future).

**Comment by robloo** [comment]
@grokys I didn't hit any showstopper but there is one place so far where I disabled functionality because of it. I will rewrite this depending on the final solution but copying the entire control template is not feasible here and needs at least named access to template parts.

https://github.com/AvaloniaUI/Avalonia/blob/24e49d1a9cc8562787241301cff3d1f5f4c7234f/src/Avalonia.Controls.ColorPicker/Themes/Fluent/ColorPicker.xaml#L86

In the future I will probably need a new TabControl ControlTemplate for other reasons (It will be done in ColorView.xaml). Then I would still need access to its header part from the ColorPicker. So far this is the only case in ColorPicker where nested templates are very useful (and is the same example I listed in the discussion).

Please let me know if I need to clarify anything.

And thanks for confirming default theme for other controls will be updated to use ControlTheme as well.

**Comment by grokys** [comment]
Ok, in this case, the `TabBackgroundBorder`  seems to have a `CornerRadius` bound to `{TemplateBinding CornerRadius}`, i.e. it's bound to `ColorView.CornerRadius`:

https://github.com/robloo/Avalonia/blob/64c4599709d35c47406396d798b024ecf553cefb/src/Avalonia.Controls.ColorPicker/Themes/Fluent/ColorView.xaml#L100

So couldn't you simply set `CornerRadius="{DynamicResource TopOverlayCornerRadius}"` here?

https://github.com/AvaloniaUI/Avalonia/blob/24e49d1a9cc8562787241301cff3d1f5f4c7234f/src/Avalonia.Controls.ColorPicker/Themes/Fluent/ColorPicker.xaml#L49

Or am I looking at the wrong thing?

**Comment by robloo** [comment]
@grokys Here is an illustration to clarify:

image

The fundamental issue is both `ColorView` and `ColorPicker` need to set DIFFERENENT corner radius to the background border within the `ColorView`. Since `ColorPicker` hosts the `ColorView` it is a nested template part.

I suppose it may be possible to re-define the resource TopOverlayCornerRadius as you said. It would have to be customized for the `ColorPicker` ControlTheme ONLY though -- so I guess not sure where to put that resource.

**Comment by grokys** [comment]
Got you - regarding you edit, no I wasn't really saying that, I just didn't understand what was going on ;) Changing resources here is definitely one way to do this, but let me think about it a little and see how I think it would be done in an ideal world.

**Comment by grokys** [comment]
Arrgh, I could have sworn I replied to this the other evening, but I think I dreamt it as I was falling asleep! Sorry for the delay.

In this case wouldn't a simple class work? i.e. in `ColorView`:

```
  <Style Selector="^.topoverlay /template/ Border#TabBackgroundBorder">
    <Setter Property="CornerRadius" Value="{DynamicResource TopOverlayCornerRadius}" />
  </Style>
```

And then you set that class in `ColorPicker`.

**Comment by robloo** [comment]
@grokys Yes, I tested it and it works. However, I wouldn't say it is "architecturally correct", actually, the resources idea seems to better separate the two controls. 

Using a class solution like yours above, the `ColorView` needs to be aware of the `ColorPicker` and make accommodations for it. However, the `ColorPicker` is a higher-level control and `ColorView` shouldn't have an inter-dependency with it. `ColorView` should be general-purpose and self-contained.

**Pull request merged**
