### PR TITLE
Add disable styles for TextBox / ListBox / ComboBox / Slider

### LINKED ISSUE #3504: Some controls have no disabled style
The following controls have no disabled style making them looking exactly like when they are enabled. Avalonia Nuget Packages: **0.9.2**

## Screenshot:
image

## Repro:
```
<Window
    x:Class="AvaloniaApplication1.Views.MainWindow"
    xmlns="https://github.com/avaloniaui"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:vm="clr-namespace:AvaloniaApplication1.ViewModels;assembly=AvaloniaApplication1"
    Title="AvaloniaApplication1"
    Width="450"
    Height="450"
    Icon="/Assets/avalonia-logo.ico"
    mc:Ignorable="d">

    <Design.DataContext>
        <vm:MainWindowViewModel />
    </Design.DataContext>

    <Grid ShowGridLines="True">
        <Grid.ColumnDefinitions>
            <ColumnDefinition />
            <ColumnDefinition />
        </Grid.ColumnDefinitions>
        <StackPanel HorizontalAlignment="Center">
          <TextBlock FontSize="18" Margin="20" FontWeight="Bold"  Text="Enabled" />
            <StackPanel Orientation="Horizontal">
                <TextBlock VerticalAlignment="Center" Text="Textbox" />
                <TextBox Margin="10,0,0,0" Text="aaaaaaa" />
            </StackPanel>
            <StackPanel Orientation="Horizontal">
                <TextBlock VerticalAlignment="Center" Text="ComboBox" />
                <ComboBox Margin="10,0,0,0" SelectedIndex="0">
                    <ComboBoxItem Content="Bla" />
                </ComboBox>
            </StackPanel>
            <StackPanel Orientation="Horizontal">
                <TextBlock VerticalAlignment="Center" Text="ListBox" />
                <ListBox Margin="10,0,0,0" SelectedIndex="0">
                    <ListBoxItem Content="Bla" />
                    <ListBoxItem Content="Bla 2" />
                    <ListBoxItem Content="Bla 3" />
                </ListBox>
            </StackPanel>
            <StackPanel Orientation="Horizontal">
                <TextBlock VerticalAlignment="Center" Text="Slider" />
                <Slider Width="50" Margin="10,0,0,0" />
            </StackPanel>
            <StackPanel Orientation="Horizontal">
                <TextBlock VerticalAlignment="Center" Text="AutoCompleteBox" />
                <AutoCompleteBox
                    Width="50"
                    Margin="10,0,0,0"
                    Text="asdasd" />
            </StackPanel>
        </StackPanel>
        <StackPanel
            Grid.Column="1"
            HorizontalAlignment="Center"
            IsEnabled="False">
            <TextBlock FontSize="18" Margin="20" FontWeight="Bold" Text="Disabled" />
            <StackPanel Orientation="Horizontal">
                <TextBlock VerticalAlignment="Center" Text="Textbox" />
                <TextBox Margin="10,0,0,0" Text="aaaaaaa" />
            </StackPanel>
            <StackPanel Orientation="Horizontal">
                <TextBlock VerticalAlignment="Center" Text="ComboBox" />
                <ComboBox Margin="10,0,0,0" SelectedIndex="0">
                    <ComboBoxItem Content="Bla" />
                </ComboBox>
            </StackPanel>
            <StackPanel Orientation="Horizontal">
                <TextBlock VerticalAlignment="Center" Text="ListBox" />
                <ListBox Margin="10,0,0,0" SelectedIndex="0">
                    <ListBoxItem Content="Bla" />
                    <ListBoxItem Content="Bla 2" />
                    <ListBoxItem Content="Bla 3" />
                </ListBox>
            </StackPanel>
            <StackPanel Orientation="Horizontal">
                <TextBlock VerticalAlignment="Center" Text="Slider" />
                <Slider Width="50" Margin="10,0,0,0" />
            </StackPanel>
            <StackPanel Orientation="Horizontal">
                <TextBlock VerticalAlignment="Center" Text="AutoCompleteBox" />
                <AutoCompleteBox
                    Width="50"
                    Margin="10,0,0,0"
                    Text="asdasd" />
            </StackPanel>
        </StackPanel>

    </Grid>

</Window>


```

### PR DESCRIPTION
**Pull request by Symbai**
## What does the pull request do?
Added visual disable style to certain controls. See screenshots below.

## What is the current behavior?
Before

## What is the updated/expected behavior with this PR?
After

## Fixed issues
Fixes #3504

### CODE REVIEW

**Comment by Gillibald** [comment]
All effected controls should stop reacting to mouse events and keyboard navigation.

**Comment by grokys** [comment]
@Gillibald controls should already stop reacting to mouse/keyboard when disabled. Have you seen otherwise?

**Review by grokys — APPROVED** [review]
Thanks @Symbai - looks good to me, tested in ControlCatalog and these controls now display grayed-out.

**Comment by Gillibald** [comment]
The screenshot for disabled state showed a selection highlight so I assume selection still works.

**Comment by kekekeks** [comment]
Disabled elements keep their selection, it just can't be changed.

**Comment by Gillibald** [comment]
If that is the desired behavior then it is fine. In my opinion it should not have a selection highlight.

**Pull request merged**
