### PR TITLE
Added TopLevel.Opened event and use it for RxUI Activation.

### PR DESCRIPTION
**Pull request by grokys**
## What does the pull request do?

ReactiveUI's `.WhenActivated` feature does not work well with `Window` because the `Initialized` event will have already been fired before `InitializeComponent` exits. This PR adds a `TopLevel.Opened` event (to compliment the existing `TopLevel.Closed` event) and uses this event for RxUI activation.

## What is the current behavior?

RxUI's `.WhenActivated` call needs to come before `InitializeComponent` when using the feature with a window, otherwise activation will never trigger. This is less than ideal because any controls needed by the activation code will not have been created at this point.

## What is the updated/expected behavior with this PR?

`Opened` is now called when the window/popup is opened either via a call to `Show` or a call to `ShowDialog` and RxUI activation uses this event instead of `Initialized`.

## Checklist

- [x] Added unit tests (if possible)?

cc: @worldbeater

### CODE REVIEW

**Comment by Gillibald** [comment]
Is this different to https://docs.microsoft.com/de-de/dotnet/api/system.windows.window.activated?view=netframework-4.7.2?

**Comment by grokys** [comment]
Yes, this is only raised when the window is shown. `Activated` is raised when:

- The window is first opened.
- A user switches to a window by selecting it with the mouse, pressing ALT+TAB, or from Task Manager.
- A user clicks the window's taskbar button.

**Comment by worldbeater** [comment]
Might be worth adding unit tests that use `AvaloniaXamlLoader.Load(this)` to https://github.com/AvaloniaUI/Avalonia/blob/master/tests/Avalonia.ReactiveUI.UnitTests/AvaloniaActivationForViewFetcherTest.cs just to make sure we can place `WhenActivated` below a call to Avalonia XAML Loader in both `ReactiveUserControl` and `ReactiveWindow` :1st_place_medal:

**Review by worldbeater — APPROVED** [review]

**Comment by grokys** [comment]
Good point! I'd missed that there were tests for this already because that assembly isn't actually included in our solution! I'll add it in and add those tests.

**Comment by grokys** [comment]
@worldbeater added XAML loading to the tests. Could you take a look to see if the changes make sense, and I'll merge.

**Review by worldbeater — APPROVED** [review]
LGTM!

**Pull request merged**
