### PR TITLE
Clipboard image

### PR DESCRIPTION
**Pull request by viordash**
## What does the pull request do?

- Fix an incorrect CF_DIB value (Avalonia.Win32\Interop\UnmanagedMethods.cs).
- Adds definitions for clipboard image formats in Win32 (https://learn.microsoft.com/en-us/windows/win32/dataxchg/standard-clipboard-formats).
- The ControlCatalog.ClipboardPage example adds commands for working with images on the clipboard.

_In this PR there is no conversion of the received data to a common type, e.g. Avalonia.Media.Imaging.Bitmap. 
The main idea is to be able to get/set an image by documented format names, and then process the data in client code depending on the format._

## What is the current behavior?

For Win32, there is no way to add a DataObject with any of the documented image formats to the clipboard  (https://learn.microsoft.com/en-us/dotnet/api/system.windows.dataformats). 

Getting an image is possible, but need to know the correspondence of Unknown_Format_X to the real format. 
The Unknown_Format_X image can be stored using a small workaround by calling the GetFormatsAsync method before storing.

## What is the updated/expected behavior with this PR?

Ability to specify clipboard formats for images that match the 
https://learn.microsoft.com/en-us/dotnet/api/system.windows.dataformats?view=windowsdesktop-7.0

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0037897-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0037979-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]
Win32 part looks good.
Samples part is going to be removed soon as we going to have build in bitmap support with virtual avalonia data format for bitmaps.

**Comment by viordash** [comment]
Hi, @maxkatz6,
I would like to know how to handle with the error checks "AvaloniaUI.Avalonia — #20230804.4 failed". 
I assume that because of my code could not cause it

**Comment by kekekeks** [comment]
@viordash sorry for being slow with reviewing/merging your PRs. We are planning to do some refactoring of the way clipboard works soon, so PRs will be merged as a part of that effort.

**Pull request merged**
