### PR TITLE
Add new ColorView & ColorPicker Controls

### LINKED ISSUE #4179: Adding ColorPicker and Related Primitive Controls
# Adding ColorPicker/Button and ColorCanvas Controls

I don't think Avalonia has a ColorPicker control. Is there a plan to add this to the project? If so, I've been implementing my own (as many others have) and would like to propose the below idea. This is currently for UWP but porting should be possible. Right now I think it provides a unique concept to discuss and see if it fits with this project.

**ColorCanvas**

See WinUI

**ColorPicker Example**

Newest example:

image

Older example from the Windows Community Toolkit

example1

| Spectrum    | Palette | Channels |
| ------------- | ------------- | ------------- |
| Spectrum | Palette | Channels1 |
| | | Channels2 |

### PR DESCRIPTION
**Pull request by robloo**
## Checklist

- [ ] Added unit tests (if possible)?
- [x] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Fixed issues

Closes https://github.com/AvaloniaUI/Avalonia/issues/4179

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0020538-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by timunie** [comment]
Is it a good choice to have an enum for the tabs? I think one may want to extend the control later on with a "custom" view. Can this still be done?

**Comment by MikeCodesDotNET** [comment]
Are partial classes used for any other Avalonia controls? 

I'm not a fan of partial classes and given the simplicity of a colour picker, I don't see why it needs to be split up.

**Comment by robloo** [comment]
> Is it a good choice to have an enum for the tabs? I think one may want to extend the control later on with a "custom" view. Can this still be done?

That's unimplimented so far. The issue is you also want to be able to set the selected tab and it would be great to do that without an index. I'm open to other ideas to support devs setting the tab (this is new functionality).

**Comment by robloo** [comment]
> Are partial classes used for any other Avalonia controls?
>
>I'm not a fan of partial classes and given the simplicity of a colour picker, I don't see why it needs to be split up.

I wouldn't call the color picker simple, this is still a work in process. After a lot of design work, I think this implementation is going to have minimal code behind though.

Partial classes are used other places (a lot by me I'll admit) and this is the modern convention for controls I would say. I havnt heard of people not liking partial classes themselves, they are still used in WPF for generated code and things as you know. I guess some like monolithic files but that creates maintainability concerns in my opinion (more theoretical as code behind in this case should be minimal). Generally properties create a lot of boilerplate that hurts readability. You don't want 300 lines like this with control logic. Properties largely never change too.

In the WPF days I realize this is not how things were done. This comes from the WinUI library as well (to be fair their properties are auto generated from IDL so they have to be partial classes).

Let's wait until the control implementation is done (I'm on the road now and just wanted to commit what I have). Perhaps this will be an easier conversation once we actually have the control logic. Generally I think we have a difference of opinion though.

**Comment by MikeCodesDotNET** [comment]
I hope I didn't offend you when I said that the colour picker is simple; I implemented one (based on the WinUI code) in a day or two, so I understand it doesn't require large amounts of code. It certainly doesn't demand enough code that classes need splitting across multiple files. 

I can't comprehend the reasoning behind using partial classes for anything other than auto-generated code. Employing partial classes in situations where a file has [just 1 line of code](https://github.com/AvaloniaUI/Avalonia/blob/ef568fd63ab4eba9908456732a33f97c37497a14/src/Avalonia.Controls.ColorPicker/ColorView/ColorView.cs) is an excellent example of why I think this pattern is horrible. 

> this is the modern convention for controls I would say
 
I would disagree, but I'd suggest that our thoughts on this are ultimately irrelevant; we should instead endeavour to ensure our code observes the project's existing coding style and patterns. Using partial classes would not be consistent with the current control implementations.

Nonetheless, I'm happy to hold off discussing this further until the PR is ready for review and we can 'wax lyrical' about our opinions on the finer details.

**Comment by robloo** [comment]
> I implemented one (based on the WinUI code) in a day or two, so I understand it doesn't require large amounts of code. 

I have spent a lot of time going through WinUI color picker code over the past few years. This is surprising to me. It can take 2 days just to port from C++ to C#. Let alone redesign it correctly (the WinUI one is more like a classic Win32 control that can't be retemplated in several areas) and port to Avalonia. So I have to think you are seriously over-exaggerating what you did or don't fully understand what this control will be able to do compared to WinUI. Obviously, this is a little frustrating to discuss considering the work I've put in to date and I have to think Dunning-Kruger might have a few comments. A great amount of work is usually required to produce the simplest design. This is true in all of engineering.

Anyway, obviously the ColorView is going to have more than 1 line of code. This is a work-in-process draft PR... If you notice the WinUI code behind its also over 1200 lines. I won't need all that though and in fact will use a totally different implementation for the base (an internal control similar to the one i contributed to WCT). Honestly, I feel i shouldn't have made the PR, its too early. It would have been better to avoid this sort of conversation. The conversation about partial class files is valid though.

> would disagree, but I'd suggest that our thoughts on this are ultimately irrelevant; we should instead endeavour to ensure our code observes the project's existing coding style and patterns

Well, largely of course you are correct and no one is going to argue with that. However, we have to be open to change and improvement. So you can never say that as an absolute. I feel you are jumping on the one example here that is most in favor to your viewpoint and not seeing all the other places and controls where splitting out the properties cleans a lot up.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0020580-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by robloo** [comment]
Accidentally did a rebase without switching to master branch first. Going to close this PR and open a new one with a fixed commit history.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0020722-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request closed without merging**
