### PR TITLE
fix: Sourcelink Avalonia.Build.Tasks

### LINKED ISSUE #10188: Avalonia Nuget Package don't include debug info Avalonia.Build.Tasks
**Describe the bug**
When attempting a debug XamlC error, Visual Studio does not display the source code.
If open Avalonia Package with Nuget Explorer, you can see thath Avalonia.Build.Tasks PDB Info is missing .
immagine

**To Reproduce**

1. Create new project `dotnet new avalonia.app -o MyApp`
2. Add to `MyApp.csproj`
      ```xml
         <PropertyGroup>
            <AvaloniaXamlIlDebuggerLaunch>true</AvaloniaXamlIlDebuggerLaunch>
         </PropertyGroup>
      ```
3. Build 
5. See error

**Expected behavior**
Visualizze linked source code of Avalonia.Build-Task

**Screenshots**

**Desktop (please complete the following information):**

- OS:  Windows 10 Pro x64  22H2
- Version 11.0.0-preview4 and last nightly build

**Additional context**
it probably depends on an il-repack problem.

### PR DESCRIPTION
**Pull request by workgroupengineering**
## What does the pull request do?

Copy Sourcelink info from original Avalonia.Build.Tasks to patched.

## What is the current behavior?

[BuildTasksPatcher](https://github.com/AvaloniaUI/Avalonia/blob/84e482a43b6eb1838379c5e71a3799bb49f2b37c/nukebuild]/BuildTasksPatcher.cs)  stripp out SourceLink debug info and the IDE don't able to matching source code.

## What is the updated/expected behavior with this PR?

Matching source code through sourcelink when enabled the [debugging the XAML compiler](https://docs.avaloniaui.net/guides/developer-guides/debugging-xamlil). 

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Fixed issues

Fixes #10188

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0029549-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0029651-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0029661-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0029668-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0029853-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0029859-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by maxkatz6** [comment]
@workgroupengineering have you tested debug with these PR builds? Does it work?

**Comment by maxkatz6** [comment]
Looks like Avalonia.Build.Tasks has an embedded debug information after this PR.

CC @kekekeks

**Comment by workgroupengineering** [comment]
> @workgroupengineering have you tested debug with these PR builds? Does it work?

Yes, it works as as apected.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0030118-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0030489-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0030531-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Pull request merged**
