### PR TITLE
Auto-Loading Styles Module

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Add module to auto-load styles from xaml embedded resources that are specified with an attribute.

### CODE REVIEW

**Comment by grokys** [comment]
Looks good, and we need something like this! However, I can't see how this new code is invoked, and there are no unit tests to test it... Would it be possible to add unit tests somehow? I realise that isn't so simple as it relies on dynamically loading an assembly...

**Comment by grokys** [comment]
Hey @jkoritzinsky what is the status of this? Will it be moving forward or should I close it?

**Comment by kekekeks** [comment]
The main problem with whatever-auto-loading is the fact that we don't know the list of assemblies beforehand. And some platforms (iOS and webassembly) don't even have dynamic assembly loading infrastructure.

**Comment by jkoritzinsky** [comment]
Yeah our module system only works on non-AOT platforms. We need to think about what direction we want to take with the module system.

**Comment by kekekeks** [comment]
I was planning to have a post-build task for generating series of
```
yield return typeof(SomeType).Assembly;
```
and emitting a call to that code from the entry point.

**Pull request closed without merging**
