### PR TITLE
Fix `FillModes` regression

### PR DESCRIPTION
**Pull request by jmacato**
Fixes the bug regression on #2020 due to changes introduced in #2163.

### CODE REVIEW

**Comment by ahopper** [comment]
This fixes my issue which was a simpler version of #2020 where the animation would stop before the end.

**Comment by kekekeks** [comment]
Please, add a unit test to prevent this regression again.

**Comment by ahopper** [comment]
this might help create a unit test
```
<StackPanel>
    <StackPanel.Styles>
      <Style Selector="Panel#grow">
        <Setter Property="IsVisible" Value="false"/>
      </Style>
        <Style Selector="Panel#grow[IsVisible=true]">
        <Style.Animations>
          <Animation Duration="0:0:0.05"
                     FillMode="Forward"
                     Easing="SineEaseInOut">
            <KeyFrame Cue="0%">
              <Setter Property="Width" Value="0"/>
            </KeyFrame>
            <KeyFrame Cue="100%">
              <Setter Property="Width" Value="300"/>
            </KeyFrame>
          </Animation>
        </Style.Animations>
      </Style>
    </StackPanel.Styles>
    <ToggleButton Height="30" Width="300" VerticalAlignment="Top" Name="buttonSettings" IsChecked="{Binding #grow.IsVisible, Mode=TwoWay}" ClickMode="Press"  >
      <TextBlock>Click Me</TextBlock>
    </ToggleButton>
    <Panel Background="Green" Name="grow" Height="50" ></Panel>
    <TextBlock HorizontalAlignment="Center" Text="{Binding #grow.Bounds.Width}"/>
  </StackPanel>
```
The reported final width varies and is generally smaller than 300, if the animation time is longer it will reach 300. The effect is more visible in my real app where much more is going on

**Review by grokys — APPROVED** [review]
Thanks @jmacato !

**Pull request merged**
