### PR TITLE
Optimize CurrentThreadIsLoopThread on android backend

### PR DESCRIPTION
**Pull request by maxkatz6**
Thanks @byme8 for finding this problem with android backend!

## What is the current behavior?

There are multiple JVM calls just to check if we are on the current thread.

## What is the updated/expected behavior with this PR?

Single JVM call once and reusing CLR thread after that.

### CODE REVIEW

**Comment by maxkatz6** [comment]
https://user-images.githubusercontent.com/3163374/183271649-5c9d32d8-85f1-4ed3-8d99-b1b5835ff49f.mp4

**Comment by maxkatz6** [comment]
Apk with normal AOT for arm64 only, 20mb:
https://1drv.ms/u/s!AqsF0_O_NBsGk40JUIAHKAxHdW18VA?e=35JSPq

Or built it yourself from ControlCatalog.Android project.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0022958-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by robloo** [comment]
Well this is a very nice surprise. I wasn't expecting an optimization like this was possible or that it was such a simple fix. Was thinking the issues were more findamenral. I'll keep my mouth shut about what optimization is possible from here. Its certainly looking much more promising.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0022964-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by Gillibald — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0022980-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
