### PR TITLE
Fall back from CenterOwner to CenterScreen when owner window is minimized.

### LINKED ISSUE #7582: Child window is not centered when the parent window is minimized
**Describe the bug**
When we show a child window and the parent is minimized, and then we restore the parent window from the minimized state, the child window does not show.

**To Reproduce**
1. Show a window
2. Minimize the window
3. Show a child window with `WindowStartupLocation.CenterOwner`
4. The child window is displayed in the center of the parent window (I can say this because I debugged the Top and Left position values)
5. Restore the parent window from minimized state
6. The child window gets stuck in the original position, and because of that is not visible (In the use case I saw it was something similar to top:-31234 and left:-31234)

To reproduce check this sample app: https://github.com/OS-rafaelduarte/Avalonia_Boilerplate/tree/MinimizedDialogIssue

**Expected behavior**
The child window should be centered when the parent window is restored

**Desktop:**
- OS: Windows (It's fine on macOS)
- Version [Latest]

### PR DESCRIPTION
**Pull request by grokys**
## What does the pull request do?

When showing a child window with `WindowStartupLocation = CenterOwner` to a minimized owner window, we were displaying the child in an invalid position. Use the WPF behavior of falling back to `CenterScreen` in this situation.

## Fixed issues

Fixes #7582

### CODE REVIEW

**Comment by pr8x** [comment]
Also, when the owner window is (fully or partially) out of screen the children window will not be shown. Might make sense to clamp to screen boundaries?

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018978-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018978-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by danwalmsley — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018991-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
