### PR TITLE
Make the built-in VS XAML language service work with Avalonia

### PR DESCRIPTION
**Pull request by aelij**
The built-in XAML language service expects the `XmlnsDefinitionAttribute` in the `System.Windows.Markup` namespace. If we only move Avalonia's attribute there, we would get a lot of the XAML functionality working without the VS extension. I think it can go a long way to reduce friction in adopting Avalonia.

To make everything work, I also added the `ContentProperty`, so the designer would be aware of child elements.

There's just one ugly workaround - the `ItemsControl.Items` property is `IEnumerable`, so the designer won't allow adding children to it. I had to create an `IList ItemsList` property that shadows it to use as the content property.

WDYT?

Completion & namespaces:
image

Markup extensions:
image

Some validation:
image

### CODE REVIEW

**Review by grokys — COMMENTED** [review]
This is great, but I think @kekekeks needs to weigh in here as I'm not so up on the workings of the VS designer.

**Comment by kekekeks** [comment]
At first, I've also tried the approach of making VS to support our XAML, but ended up with my own implementation.

1) It will cause compilation errors in applications where Avalonia is *embedded* into WPF application.
2) We already have basic autocomplete for properties. Our extension currently only lacks binding completion. Which we'll have to implement ourselves anyway, since we have custom extensions and VS won't be able to detect `DataContext` type for for styles and templates. Support from the native XAML language service will never be perfect.
3) It will also limit us in stuff that we want to do in the future (e. g. we won't be able to add/change something, because it breaks support from VS).

In my opinion, this change won't introduce enough value to outweigh those points.

**Comment by kekekeks** [comment]
We might get away with compilation errors by using [type forwarding](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/type-forwarding-in-the-common-language-runtime), but I still don't think that it's worth the trouble.

**Comment by aelij** [comment]
I don't think it would introduce that trouble.

1. It's easy to work around these using `extern alias` (I've done this in the `Avalonia.Win32.Interop` assembly). I don't think type forwarding would help since the namespace is what matters to the language service.
   * Additionally, I believe this kind of situation should be very rare - you'd have to actually apply those attributes in one of the assemblies that reference both Avalonia and WPF.
   * Another point - I wouldn't expect many people to actually need the WPF interop, but I may be wrong. Was it born out of user requirements of was it just easy to implement?

2. Not perfect may be good enough for a lot of people. Like many others, I choose which extensions I install into VS very carefully, since they can dramatically affect my daily productivity. And if I could get by with basic completion without adding another designer I'd do it.
   * `DataContext` may work by adding the `d:DataContext` design-time attribute.

3. Can you give an example? I don't see how this would be limiting. These two attributes are basically the only thing needed for the language service to work properly.

Lastly - **Microsoft is standardizing XAML**. I think we should get on board instead of forking, especially for the most basic stuff. Those attributes are in `System.Xaml` (which might also go netstandard in the future).

**Comment by grokys** [comment]
Pseronally, I'm on the fence about this. I agree it would be really nice to have but do worry about copying a class from the BCL with an identical namespace!

**Comment by aelij** [comment]
Closing this for now. I will find another way to hack the XAML language service without modifying Avalonia.

**Comment by DamianSuess** [comment]
I know this item is closed, however, I'm upgrading [Prism.Avalonia](https://github.com/AvaloniaCommunity/Prism.Avalonia) to Prism v8.1 and the `ModuleCatalog` requires the `[ContentProperty("Items")]` attribute.

What (if any) is the current workaround for including `using System.Windows.Markup;`?

**Comment by maxkatz6** [comment]
@DamianSuess Avalonia has content attribute, which is assignable on the specific property.

**Comment by DamianSuess** [comment]
@maxkatz6 thank you, I appreciate the feedback & will look onto it more so. 
In the meantime of using `[content]`, will we ever see a more XAML compliant `contentproperty` feature? This way we can stay aligned with WPF WinUI/UWP, & Xamarin/MAUI syntax.

**Comment by jmacato** [comment]
is there any functional differences between `Content` and `ContentProperty`? If there's none then i'm not sure there's any merit in matching their naming.

**Pull request closed without merging**
