### PR TITLE
Refactor style apply

### LINKED ISSUE #8549: Window gets :is(Control) style applied twice
**Describe the bug**

Windows get the `:is(Control)` style applied twice, as can be seen in DevTools:

image

**To Reproduce**

1. Run an Avalonia application
2. Open DevTools
3. Notice that the style is applied twice

**Desktop (please complete the following information):**

- OS: All
- Version: master and stable

### PR DESCRIPTION
**Pull request by grokys**
## What does the pull request do?

Refactors how we attach styles:

- Removes the `IStyler` service and the `Styler` implementation
  - Having this as a pluggable service was only really done for unit testing purposes, but it meant that we had to do a service lookup each time a control wanted to style itself
- Moves the logic for applying styles and control themes from `Styler` into `StyledElement`
- Removes the style `TryAttach` method from the public API
  - I want to allow the possibility of refactoring this code later without breaking a public API

Also adds a fix for #8549:

- Don't apply styling in `TopLevel` constructor. This isn't a good idea for a number of reasons, one of which is demonstrated by #8549
- Instead apply styling when showing a window, or if it's needed call `StyledElement.ApplyStyling` manually, e.g. in unit tests.

## Performance Regression

This PR removes style caching for now. This will need to be added back in future, but:

- The old method of caching styles inside individual `Style`/`Styles` objects wasn't very efficient. We'll need to implement something better, that also helps speed up applying control themes
- Now we have control themes we have a _lot_ less styles than when style caching was added so probably less important

I modified a benchmark in this PR to test this; it adds a lot of styles for various controls in a nested tree and instantiates and styles a single `TextBox`:

Before:

|              Method |     Mean |    Error |   StdDev |  Gen 0 | Allocated |
|-------------------- |---------:|---------:|---------:|-------:|----------:|
| Apply_Detach_Styles | 68.18 us | 1.275 us | 1.065 us | 3.7842 |     15 KB |

After:

|              Method |     Mean |   Error |  StdDev |  Gen 0 | Allocated |
|-------------------- |---------:|--------:|--------:|-------:|----------:|
| Apply_Detach_Styles | 109.4 us | 0.89 us | 0.84 us | 4.2725 |     17 KB |

So we have a pretty serious performance regression in the worst case, though this only affects applications with a _lot_ of styles.  For typical applications which use mostly control themes it shouldn't be noticeable.

I don't want to address this in this PR as it's a separate feature, but will open a PR to add back style caching using a new method in the near future, which should improve things beyond what we had before.

Depends on #8600 
Fixes #8549

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0026033-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0026420-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0026423-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0026429-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]

**Pull request merged**
