### PR TITLE
Fix Animator for progress values less than zero

### LINKED ISSUE #15704: Translate animation flickers control visibility when using certain easings as of v11.0.6
### Describe the bug

We originally built a feature into our user prompt dialog overlay where if the user clicked into an area outside of the dialog, we would visually "shake" the dialog with a quick animation to indicate the operation wasn't allowed.  This was implemented back when we referenced Avalonia v11.0.5 and worked great.

We were about to implement a similar feature in another control in our latest codebase that now targets v11.0.7+ and found that the animation is causing the control to flicker visibility.  After digging in, we found that `BackEaseIn`, `BackEaseInOut`, `ElasticEaseIn`, and `ElasticEaseInOut` all cause the issue starting in Avalonia v11.0.6 and it is easily reproduced.

### To Reproduce

Add the following XAML to a project and check the `CheckBox` to trigger the animation.  You will see the button flicker visibility at times the easing (if it is `BackEaseIn`, `BackEaseInOut`, `ElasticEaseIn`, or `ElasticEaseInOut`) drops below the bottom line in the charts here: 

https://docs.avaloniaui.net/docs/reference/animation-settings

This all worked fine in v11.0.5, but some change in v11.0.6 broke it.  The bug is present from v11.0.6 through the current master.

This animation shows the issue in action:
AnimationIssue

Whereas here in v11.0.5 is how it should look:
AnimationWorking

```
<StackPanel>
	<Panel Width="300" Height="200" HorizontalAlignment="Left" Background="LightGray">
		<Button x:Name="shakeButton" IsEnabled="False" Content="Shakes When Enabled" HorizontalAlignment="Center" VerticalAlignment="Center">
			<Button.Theme>
				<ControlTheme TargetType="Button">
					<Setter Property="Template">
						<ControlTemplate>
							<Border BorderBrush="Black" BorderThickness="1" Background="White" Padding="20">
								<ContentPresenter Content="{TemplateBinding Content}" />
							</Border>
						</ControlTemplate>
					</Setter>

					<Style Selector="^:disabled">
						<Setter Property="TextElement.Foreground" Value="LightGray" />
					</Style>

					<Style Selector="^:not(:disabled)">
						<Setter Property="TextElement.Foreground" Value="Blue" />
						<Style.Animations>
							<Animation FillMode="Both" Duration="0:0:1">
								<Animation.Easing>
								<!--
									The following easing have flicker issues, which is every
									easing that drops below the bottom line in the charts here: https://docs.avaloniaui.net/docs/reference/animation-settings
											
									<BackEaseIn/>
									<BackEaseInOut/>
									<ElasticEaseIn />
									<ElasticEaseInOut />
								-->
									<ElasticEaseInOut/>
								</Animation.Easing>
								<KeyFrame Cue="0%">
									<Setter Property="TranslateTransform.Y" Value="0" />
								</KeyFrame>
								<KeyFrame Cue="50%">
									<Setter Property="TranslateTransform.Y" Value="-10" />
								</KeyFrame>
								<KeyFrame Cue="100%">
									<Setter Property="TranslateTransform.Y" Value="0" />
								</KeyFrame>
							</Animation>
						</Style.Animations>
					</Style>

				</ControlTheme>
			</Button.Theme>
		</Button>
	</Panel>
	<TextBlock TextWrapping="Wrap">Check the box to enable the button and trigger an aimation.  BackEaseIn, BackEaseInOut, ElasticEaseIn, and ElasticEaseInOut all cause issues.</TextBlock>
	<CheckBox IsChecked="{Binding #shakeButton.IsEnabled}" Content="Is enabled" />
</StackPanel>
```

### Expected behavior

The animation should move the button correctly even when the easing temporarily puts the animated control out of range of the normal values, and no visibility flickering should occur.  This worked in v11.0.5.

### Avalonia version

v11.0.6 and later

### OS

Windows

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MrJul**
## What does the pull request do?
This PR fixes the handling of animations having progress values < 0, which was broken after #13775.
This happens with some easings such as `ElasticEaseIn` or `BackEaseIn`.

Unit tests have been added.

## What is the current behavior?
The animation progress is becoming `NaN`.

## What is the updated/expected behavior with this PR?
Animations with such easings work.

## How was the solution implemented (if it's not obvious)?
If present, the existing key frames for 0% and 100% are correctly reused even if the progress is <0% or >100%.
Previously, a second neutral/fill frame was incorrectly added at 0%, effectively making `afterTime - beforeTime` always 0, resulting in a division by zero.

## Fixed issues
 - Fixes #15704

### CODE REVIEW

**Comment by MrJul** [comment]
Added more tests and fixes: a single key frame with a 100% cue was failing with the out-of-range easings.
This PR is now ready for review.

**Review by jmacato — COMMENTED** [review]
looking good so far! although since we're touching the keyframe fetching code anyway, should we try to handle the integer -> double runtime animation error in this PR as well?

Ex:

```
            var animation = new Avalonia.Animation.Animation
            {
                Duration = TimeSpan.FromSeconds(1.0),
                Children =
                {
                    new KeyFrame
                    {
                        Cue = new Cue(0.0),
                        Setters = { new Setter(TranslateTransform.YProperty, 10u) } // explicitly uint'd, but happens to int vals as well. 
                        // the TargetProp is a double type prop and the target val is uint and that has been broken since time immemorial.
                    },
                    new KeyFrame
                    {
                        Cue = new Cue(1.0),
                        Setters = { new Setter(TranslateTransform.YProperty, 20u) } // same goes here
                    }
                },
                IterationCount = new IterationCount(5),
                PlaybackDirection = PlaybackDirection.Alternate,
                Easing = easing
            };
```

**Comment by MrJul** [comment]
> although since we're touching the keyframe fetching code anyway, should we try to handle the integer -> double runtime animation error in this PR as well?

I'd prefer if we make a separate PR for that, as this seems a bit out of scope of this PR :)

IMO, we shouldn't even change the behavior here, as trying to convert the value on each animation tick might cause performance issues: we should instead throw when building the animator (this matches style setters that throw when creating the `ISetterInstance`).

Also, it only matters for C#, since the XAML compiler already type the value correctly.

I'm happy to discuss that further!

**Comment by jmacato** [comment]
> Also, it only matters for C#, since the XAML compiler already type the value correctly.

Hmm, I honestly still recall this happening on XAML too before, we might need to both corroborate and test that scenario

**Comment by MrJul** [comment]
> Hmm, I honestly still recall this happening on XAML too before, we might need to both corroborate and test that scenario

Unless I've misunderstood the scenario you're talking about, if the XAML compiler didn't special case setters, we would have strings everywhere in styles and animations, and setters wouldn't work at all. I've just double checked for sanity though!

The code is here: https://github.com/AvaloniaUI/Avalonia/blob/5e323b8fb1e2ca36550ca6fe678e487ff936d8bf/src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlSetterTransformer.cs#L79-L83

Also, using bindings in setters already convert the value correctly (also rechecked).

Off the top of my head, the place I frequently encounter which requires the correct (non-string) type in XAML is `Binding.ConverterParameter`.

> I thought boxing numeric types wouldnt have too much severe impact on perf? Also since this is going to be a one time cost (only on building the animator) the cost should be minimal right?

Indeed, perf would be perfectly fine if we do it only on building the animator.

Another argument for doing nothing is that dynamic converters aren't trimming friendly (they were initially removed from the binding system refactor for this reason). In my opinion, we should do all conversions at XAML compile time if possible - a lot is already done - and throw for incorrect value types passed at runtime.

Regarding C# usages, we could add some helper method to create a setter from a typed property if needed, reducing errors.
e.g. `Setter Create<TValue>(AvaloniaProperty<TValue> property, TValue value) => new Setter(property, value)`.

**Comment by jmacato** [comment]
> In my opinion, we should do all conversions at XAML compile time if possible - a lot is already done - and throw for incorrect value types passed at runtime.

Agreed, Im personally not that well versed in the XAML compiler side but that's a good way to do it.

> Regarding C# usages, we could add some helper method to create a setter from a typed property if needed, reducing errors.
e.g. Setter Create<TValue>(AvaloniaProperty<TValue> property, TValue value) => new Setter(property, value).

Yeah, this may need an API review with @grokys at least, since this is touching the Bindings infra already.

**Review by jmacato — APPROVED** [review]

**Pull request merged**
