### PR TITLE
Replace LineBreakEnumerator implementation

### PR DESCRIPTION
**Pull request by Gillibald**
## Checklist

- [x] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

### CODE REVIEW

**Comment by JimBobSquarePants** [comment]
@Gillibald I've hacked the following code to a local Avalonia build taking the test from RichTextKit and running it against your implementation.

I don't know whether the test is bad or what but I am seeing mismatches against the expected result. 

https://gist.github.com/JimBobSquarePants/afa0d1dab5dc334b0b009ef8211fab3bb

Test code expects the Unicode v 13.0 `LineBreakTest.txt` under `tests\TestFiles\UnicodeTestData\`

**Comment by Gillibald** [comment]
Just ran it against our Unicode data and everything passes

**Comment by Gillibald** [comment]
Okay. It seems my BreakPairTable is wrong. Don't know why I didn't see that. I am on it and let you know how I did it when I am finished.

**Comment by JimBobSquarePants** [comment]
@Gillibald Thanks. Sorry to have been the bearer of bad news!

**Comment by Gillibald** [comment]
That's good news. We would have never known until those rare conditions occur in the real world 😃

**Comment by Gillibald** [comment]
Everything should pass now. I had to look at the failing tests and make sure the needed pairs are present in the table. In the end, I added entries for those break condition to the table and generated a new map from it.

**Comment by JimBobSquarePants** [comment]
@Gillibald I'm afraid I'm still seeing failing output when I added the updated PairBreak entries to my local copy and ran the tests I linked before. 

https://gist.github.com/JimBobSquarePants/b7e7b118046392434d3bc343d5ad013b

**Comment by Gillibald** [comment]
I am testing against https://www.unicode.org/Public/13.0.0/ucd/auxiliary/LineBreakTest.txt
Data is parsed here: https://github.com/AvaloniaUI/Avalonia/blob/master/tests/Avalonia.Visuals.UnitTests/Media/TextFormatting/UnicodeDataGenerator.cs
And all tests cases are executed here: https://github.com/AvaloniaUI/Avalonia/blob/master/tests/Avalonia.Visuals.UnitTests/Media/TextFormatting/UnicodeDataGeneratorTests.cs#L21

Not sure what might be wrong

**Comment by JimBobSquarePants** [comment]
I'm testing against the same file but using a copy of the the tests taken directly from RichTextKit. 

https://github.com/toptensoftware/RichTextKit/blob/a2733e43ba8484032adfb1defbdde41c09986e7f/Topten.RichTextKit.Test/LineBreakTest.cs#L91

The logic in the test seems sound to me (_I could be wrong_) so I'm not sure what the issue is.

**Comment by Gillibald** [comment]
I guess I have to rewrite my tests then

**Comment by Gillibald** [comment]
Turns out I have only tested against the first break opportunity but not against the following. 131 tests still failing. I am on it 😃

**Comment by JimBobSquarePants** [comment]
@Gillibald I have a version here that passes all the tests but it needs a cleanup as I believe I can tidy up the rules. 

https://github.com/SixLabors/Fonts/blob/b31ab6b28f33034825f9b684a864c7751e3e4203/src/SixLabors.Fonts/Unicode/LineBreakAlgorithm.cs

**Comment by Gillibald** [comment]
Wow. You were faster. Will have a look at it.

**Comment by Gillibald** [comment]
Getting the contextual breaks right is probably the hardest part. Your way of using flags for that is probably the best that can be done.

**Comment by JimBobSquarePants** [comment]
It was a case of attrition to be honest. I struggle to follow the spec language so just identified patterns in the failing tests that RichTextKit was skipping and kept adding workarounds. 

>Your way of using flags for that is probably the best that can be done.

Yeah. I think the theory is sound it just needs a some cleanup. It can likely be simplified. 

Just to note my pair table differs from yours in two places. CL-IN, CP-IN where I use the direct break from the [example table](https://www.unicode.org/reports/tr14/tr14-37.html#Table2).

**Comment by Gillibald** [comment]
Y like to start from scratch when I am not confident with the adapted solution. When I took that implementation I had not much time to do it. In addition to that, I updated everything to Unicode 13 but I got the tests wrong. So I never realized something was wrong.

**Comment by Gillibald** [comment]
I have adapted your implementation and it seems everything works fine. Just one failing test but that might be caused by a mistake during the porting process.

Also, this test made me realize our Unicode trie has the wrong default for LineBreakClass. It defaulted to OpenPunctuation 😃

**Review by grokys — APPROVED** [review]

**Comment by JimBobSquarePants** [comment]
Glad you all got this sorted.

**Comment by Gillibald** [comment]
Thanks for your help

**Pull request merged**
