### PR TITLE
fixes to text when wrapping with lineBreaks in content

### PR DESCRIPTION
**Pull request by GaNacereddine**
## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=8559) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=8559) before we can accept your contribution.<br/><br/>:x: GaNacereddine [sign now](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=8559)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/AvaloniaUI/Avalonia?pullRequest=8559) it.</sub>

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0022273-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by Gillibald** [comment]
What exactly are you trying to achieve here? What is not working? Any example?

**Comment by GaNacereddine** [comment]
@Gillibald go to the TextBlockPage.xaml in samples

and add <LineBreak/> s to the RichTextBlock then run, you will notice that only the first line before the LineBreak is rendered.

the code we push in this PR fixes that issue.

and the issue is coming when you wrap the text only

**Comment by Gillibald** [comment]
You are just hiding the underlying issue. Should be fixes by https://github.com/AvaloniaUI/Avalonia/pull/8471

**Comment by GaNacereddine** [comment]
@Gillibald I do not have the same knowledge about the code base as you do, so I will take your word for it. 
we were in a hurry to solve the issue. 

can you please indicate in #8471 when this issue is resolved?

thanks

**Comment by Gillibald** [comment]
The PR can be merged at any time

**Pull request closed without merging**
