### PR TITLE
performance optimization of

### PR DESCRIPTION
**Pull request by donandren**
- AvaloniaObject.GetValue
- AvaloniaPropertyRegistry.IsRegistered
- AvaloniaProperty.GetMetadata

### CODE REVIEW

**Comment by grokys** [comment]
Wouldn't it make more sense in the case of property registrations to just register the property for the registered type and all base classes at the time of registration?

**Comment by donandren** [comment]
@grokys actually it's the opposite when you register a property it's for the base class (Control for example) and when the property is set it's usually from Control descendants (ToggleButton for example), and in advance actually in the time of the registration it's unknown which descendant class will set it (CheckBox or ToggleButton or Control)

**Comment by grokys** [comment]
Ah yeah, you have a point!

I will take a look at this PR very soon but first I *really* want to get the rest of the virtualization changes finished - it's sooo close. Then I'll take a look at bugs an optimization.

**Comment by grokys** [comment]
This has been merged into master! Thanks @donandren !

**Pull request closed without merging**
