### PR TITLE
Fix alt down shortcuts and allow alt down handling for end users

### LINKED ISSUE #5976: ⌘+⌥+<any key> input is not handled on macOS (Cmd+Option) (Meta+Alt)
**Describe the bug**
On macOS cmd+option+<any letter> input events are not working for the first char press. only for a second press, if you are not lifted up cmd+option. Other native apps handling shortcuts without any issues - so this is not an OS configuration fail. 

**To Reproduce**
I've got a repro attached to the InputManager.PreProcess event so this is not a code/markup fail by me.
```
    public partial class MainWindow : Window
    {
        public static MainWindow Self;
        public MainWindow()
        {
            AvaloniaXamlLoader.Load(this);
            Self = this;
            AvaloniaLocator.Current.GetService<IInputManager>().PreProcess.Subscribe(new InputObserverRaw());
        }
        private class InputObserverRaw : IObserver<RawInputEventArgs>
        {
            public void OnCompleted() => Self.Title += "Completed";

            public void OnError(Exception error) => Self.Title += error.ToString();

            public void OnNext(RawInputEventArgs value)
            {
                if (value is RawKeyEventArgs args)
                {
                    Self.Title = args.Type + ": " + args.Modifiers + " => " + args.Key;
                }
            }
        }
        private int _count;
        protected override void OnKeyDown(KeyEventArgs e)
        {
            if (e.Key == Key.K && e.KeyModifiers == (KeyModifiers.Alt | KeyModifiers.Meta))
            {
                _count++;
                Title = "PRESSED! Meta+Alt+K " + _count;
                e.Handled = true;
            }
            base.OnKeyDown(e);
        }
    }
```
1. Copy content above
2. Create new project from Avalonia template
3. Paste content to the MainWindow.axaml
4. Launch App
5. Hold cmd -> option -> Press K one time - no working, press again - working (window title showing the result)
6. release all keys and try again step 5.
7. Hold option -> cmd -> Press K - this order works!

**Expected behavior**
Hold cmd -> option -> input handling works on MacOS on first press

**Desktop (please complete the following information):**

- OS: MacOS Big Sur
- Version 11.3 Beta (Also our QA getting same issues on previous non-beta versions)

### PR DESCRIPTION
**Pull request by mklts**
## What does the pull request do?
Changes behavior of `AccessKeyHandler`.

## What is the current behavior?
`AccessKeyHandler` eats all key downs. This causes 2 issues
1) end user cannot handle alt key down if he wants to
2) shortcuts with alt do not work for the first press. see #5976 

## What is the updated/expected behavior with this PR?
`AccessKeyHandler` will eat alt key down only if main menu is open.

## Breaking changes
This can be a breaking change. Maybe someone already have some workarounds to handle alt downs. Now everything will work straight and this can cause bugs in end software.

## Fixed issues
Fixes #5976

### CODE REVIEW

**Comment by maxkatz6** [comment]
I think you should cleanup master branch in your fork, maybe recreate it.

image

**Comment by maxkatz6** [comment]
> This can be a breaking change. Maybe someone already have some workarounds to handle alt downs. Now everything will work straight and this can cause bugs in end software.

It makes sense, but we won't be able to backport any fixes in this case :)

**Comment by Mikolaytis** [comment]
> I think you should cleanup master branch in your fork, maybe recreate it.

Ok. When all my PR’s will be merged!

**Review by grokys — APPROVED** [review]
I wrote that "We always handle the Alt key" code originally, and I have no idea why. +1 on removing it.

This isn't strictly speaking a breaking change, as it doesn't change the API; though any change whatsoever can break user code I'd expect this to be low risk (though I've been wrong in the past).

**Pull request merged**
