### PR TITLE
Fluent data validation errors inline

### PR DESCRIPTION
**Pull request by danwalmsley**
## What does the pull request do?

image

image

## What is the current behavior?

we have some tooltip.. and its way more intuitive for it to work like this.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

### CODE REVIEW

**Comment by worldbeater** [comment]
Material Android controls e.g. `TextInputLayout` still show the notification icon in this case e.g. https://github.com/reactiveui/reactiveui.validation#example-with-android-extensions
Probably worth leaving that `(!)` icon?

**Comment by danwalmsley** [comment]
> Material Android controls e.g. `TextInputLayout` still show the notification icon in this case e.g. https://github.com/reactiveui/reactiveui.validation#example-with-android-extensions
> Probably worth leaving that `(!)` icon? We could also make all this stuff configurable via boolean flags like this is done on Android.
> 
> 

That is going to be extremely difficult!

**Comment by worldbeater** [comment]
Yeah worth making those options sometime in the future and definitely out of scope of this pr ;)

**Comment by maxkatz6** [comment]
Slider.Foreground should also be red on error.
image

**Comment by Nickelony** [comment]
I'd honestly love to have an option to choose between the old approach (ToolTip) and the new one, since the new approach ruins the layout of some of my windows, because it makes them taller when an error occurs. :/

Also is there any way to set a fixed font size for the new approach?

**Pull request merged**
