### PR TITLE
Cleanup layout visualizer and improve UX.

### PR DESCRIPTION
**Pull request by MarchingCube**
## What does the pull request do?

Small UX improvements for dev tools. Uses new `Viewbox` functionality to avoid layout visualizer getting clipped plus a highlight for active layout section. 

Also made sizing constraints a bit more obvious and fixed layout problems caused by lack of control size display rounding.

devtools-ux

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

### CODE REVIEW

**Comment by MarchingCube** [comment]
Also updated docs here: https://app.gitbook.com/@avalonia-ui/s/avalonia-docs/docs/getting-started/developer-tools

**Comment by Takoooooo** [comment]
> Also updated docs here: https://docs.avaloniaui.net/docs/getting-started/developer-tools

Hello, Dariusz! Just curious. Would it be possible to show the selector for the selected element in DevTools? I assume it may be super helpful

**Comment by MarchingCube** [comment]
@Takoooooo Potentially yes - although it is tricky since there are usually multiple ways of creating a selector for the control. One could create a very long direct selector that includes every ancestor in the tree, or create a class only selector. On top of that there are templated controls that introduce own scopes and one has to figure - which selector should show (one inside the template, or from the root).

**Review by maxkatz6 — APPROVED** [review]
LGTM

**Pull request merged**
