### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by mattleibow**
## What does the pull request do?
Adds a link to the discord server for all things .NET: https://aka.ms/dotnet-discord

### CODE REVIEW

**Review by worldbeater — APPROVED** [review]

**Comment by kekekeks** [comment]
aka.ms link can't be copy-pasted to desktop discord client properly

**Comment by jmacato** [comment]
@kekekeks i think the redirect should be enough for telegram to be invoked?

**Comment by danwalmsley** [comment]
> @kekekeks i think the redirect should be enough for telegram to be invoked? at least if they clicked the link instead of copy-pasting it

Telegram works with discord?

**Comment by danwalmsley** [comment]
Shall we remove the gitter link then?

**Comment by FoggyFinder** [comment]
I don't think removing gitter from the readMe is a good idea.

I tried to follow the link to the Discord but confirmation by phone was requested after I entered the nickname. I can't believe it's required for using Discord. I've used it couple of years ago and there was nothing like that.

I suppose I'm not the only one who doesn't want to share such information to every single app/messanger etc.

Gitter is accesable to everyone at least.

**Comment by danwalmsley** [comment]
> I don't think removing gitter from the readMe is a good idea.
> 
> I tried to follow the link to the Discord but confirmation by phone was requested after I entered the nickname. I can't believe it's required for using Discord. I've used it couple of years ago and there was nothing like that.
> 
> I suppose I'm not the only one who doesn't want to share such information to every single app/messanger etc.
> 
> Gitter is accesable to everyone at least.

Only email confirmation is required.

**Comment by danwalmsley** [comment]
@mattleibow might it be possible to allow login to discord with github account?

**Comment by FoggyFinder** [comment]
> Only email confirmation is required.

dunno then. That's what I get:

_message

I'll try to create a new account and login with it

**Comment by jmacato** [comment]
> > @kekekeks i think the redirect should be enough for telegram to be invoked? at least if they clicked the link instead of copy-pasting it
> 
> Telegram works with discord?

lol sorry... dum-dum mode yesterday :facepalm: i meant discord

**Comment by mattleibow** [comment]
Asking the mods to see what discord allows to log in with: https://discordapp.com/channels/732297728826277939/732297728826277942/737097467211939921

**Review by danwalmsley — APPROVED** [review]

**Pull request merged**
