### PR TITLE
Generate fake ref assemblies with patched *Impl and [NotClientImplementable] interfaces

### PR DESCRIPTION
**Pull request by kekekeks**
image

- Methods in interfaces with `Impl` suffix or `[PrivateApi]` attribute are made internal 
- Methods (in types) marked by `[Unstable]` are marked as `[Obsolete]`
- Interfaces marked as `[NotClientImplementable]` get injected with an `internal void NotClientImplementable()` method

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0033478-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0033482-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0033495-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]
LGTM.

It is important to mention, that these changes are applied on the ref assembly, which is now included in the nuget package as well (not before).
Which means, public API surface is more limited, but it is still possible to write a custom Avalonia platform backend by referencing non-ref assemblies directly via some msbuild magic. Since full assemblies are still included in the nuget.

**Comment by grokys** [comment]
We need to add documentation about the most common APIs that have been hidden. https://github.com/AvaloniaUI/Avalonia/pull/11091 adds two alternatives for common APIs.

**Comment by maxkatz6** [comment]
@MrJul unfortunately, analyzer solution won't work with F#. Unless somebody knows what to do with it.

> If MS - king of backward compatibility - can

MS uses a very similar solution with ref assemblies in the whole BCL and WPF - they keep public members for access between internal assemblies, and provide ref assemblies with public API.
Interesting, that EF went a different way.

**Comment by MrJul** [comment]
I obviously can't speak for the EF team, but I think they realized that some advanced use cases require internal/unstable API usages. One such case is implementing a new database provider, which can be compared with adding a new platform in Avalonia. I was honestly surprised the first time I came across these types in a MS product, but in a good way!

Besides the analyzer, each "pubternal" member has a XML doc warning. They even use it for really public types but with some unstable members, like constructors which might get new members later, see https://github.com/dotnet/efcore/blob/1da03436c9cb86711f06e3d07a9d5b7d728eb5ac/src/EFCore/Diagnostics/MaterializationInterceptionData.cs#L20 (Again a parallel can be draw with types such as Avalonia's `PointerEventArgs` and its obsolete ctor.)

Even without an analyzer, that documentation alone makes it hard to use such a pubternal member without realizing it (especially those in the `Internal` namespace), which might help for the F# analyzer-less situation.

I believe it's a good compromise: advanced users are warned that they shouldn't complain when things break, but know they can still use the members. On the contrary, having to explicitly change what assemblies get referenced in the nuget packages really feels like a hack: it no longer conveys the message "you're free to extend our library, but be careful and don't come complaining", it's now more like "nope, absolutely don't do this, get away now, or go maintain your own fork (which won't be compatible with the rest of the ecosystem)" which, in my opinion, only hurts the product.

**Comment by grokys** [comment]
@MrJul thanks for your feedback, we're in part using the preview releases to judge how to handle this - we'll try to come up with an acceptable solution for scenarios like yours.

**Comment by kekekeks** [comment]
The main problem is that Avalonia essentially provides a platform for other components, so any API breaks won't only result in compilation errors in the end user app, those would result in **runtime** MissingMethodExceptions. 

To deal with that, we have to limit the API surface available for 3rd party libraries, so moving types to `Internal` namespace isn't an option: it can and will be ignored by library authors and end users would blame us for breaking the API we haven't promised to keep stable.

**Comment by MrJul** [comment]
> The main problem is that Avalonia essentially provides a platform for other components, so any API breaks won't only result in compilation errors in the end user app, those would result in **runtime** MissingMethodExceptions.

I understand that: the same thing happens in the EF case above if some third party provider depends on EF's pubternal methods, then EF gets updated in some end user app but the third party provider isn't. Ideally all library authors should specify a maximum supported version, but that's not the norm currently with most NuGet packages.

> it can and will be ignored by library authors

If some library authors willingly chose to bypass the analyzer/documentation warnings, you can (must?) redirect the end user blaming you to them. That's my case here: if what I'm prototyping works and I want to publish a package, I'll be happy to get the blame caused by future unstable API changes (I'd have put a maximum version dependency to avoid the problem in the first place, but the end user can still override that).

If Avalonia breaking changes are correctly versioned, for example "real" public breaking changes in major versions only (following semver), and "public but internal" breaking changes in minor versions, it shouldn't be too hard to educate the library authors and users. (I'm aware that some will complain no matter what you do.)

Note that all these problems can still happen even with the changes in this PR if the implementation assemblies are directly referenced as mentioned above. If the plan was to not allow any third party platform (which would be a shame, the current infrastructure is pretty well thought and easy to extend: let's port Avalonia everywhere!), I don't think that comment would have been written.

Thanks to the team for acknowledging to my feedback, I hope some middle ground can be found!

**Pull request merged**
