### PR TITLE
[Text] Bidi pooling

### PR DESCRIPTION
**Pull request by mklts**
## What does the pull request do?
Added a pooling for bidi algorithms to reduce allocation of text build.

## What is the current behavior?

|                Method |       Mean |     Error |    StdDev |    Gen 0 |    Gen 1 |    Gen 2 | Allocated |
|---------------------- |-----------:|----------:|----------:|---------:|---------:|---------:|----------:|
|       BuildTextLayout |   610.8 us |   3.27 us |   2.90 us |  37.1094 |  18.5547 |        - |    232 KB |
| BuildEmojisTextLayout | 1,464.1 us |   7.08 us |   5.91 us | 113.2813 |  46.8750 |  15.6250 |    622 KB |
|   BuildManySmallTexts | 5,924.8 us | 116.91 us | 120.06 us | 820.3125 | 304.6875 | 140.6250 |  4,989 KB |

## What is the updated/expected behavior with this PR?

|                Method |       Mean |    Error |   StdDev |    Gen 0 |    Gen 1 |    Gen 2 | Allocated |
|---------------------- |-----------:|---------:|---------:|---------:|---------:|---------:|----------:|
|       BuildTextLayout |   604.2 us |  1.51 us |  1.42 us |  23.4375 |  11.7188 |        - |    146 KB |
| BuildEmojisTextLayout | 1,385.8 us |  3.06 us |  2.87 us |  62.5000 |  31.2500 |        - |    392 KB |
|   BuildManySmallTexts | 5,866.4 us | 18.72 us | 15.63 us | 757.8125 | 289.0625 | 132.8125 |  4,609 KB |

Also I've added `BuildManySmallTexts` benchmark.

### CODE REVIEW

**Comment by Mikolaytis** [comment]
Also I've added pooling to ShapedBuffer. But in it it not so trivial, I'll make another PR with this.

|                Method |       Mean |    Error |   StdDev |    Gen 0 |    Gen 1 |    Gen 2 | Allocated |
|---------------------- |-----------:|---------:|---------:|---------:|---------:|---------:|----------:|
|       BuildTextLayout |   605.3 us |  1.23 us |  1.09 us |   5.8594 |   1.9531 |        - |     38 KB |
| BuildEmojisTextLayout | 1,436.2 us |  2.12 us |  1.88 us |   5.8594 |        - |        - |     47 KB |
|   BuildManySmallTexts | 6,073.9 us | 26.58 us | 22.19 us | 734.3750 | 281.2500 | 125.0000 |  4,469 KB |

**Comment by Mikolaytis** [comment]
Added usage of PooledList. CPU is a bit slower, but memory is better, especially last bench.
|                Method |       Mean |     Error |    StdDev |    Gen 0 |    Gen 1 |   Gen 2 | Allocated |
|---------------------- |-----------:|----------:|----------:|---------:|---------:|--------:|----------:|
|       BuildTextLayout |   681.1 us |  13.53 us |  27.01 us |  22.4609 |   6.8359 |       - |    138 KB |
| BuildEmojisTextLayout | 1,605.8 us |  31.89 us |  65.14 us |  60.5469 |  29.2969 |       - |    383 KB |
|   BuildManySmallTexts | 6,990.1 us | 134.46 us | 179.50 us | 601.5625 | 273.4375 | 85.9375 |  3,663 KB |

**Comment by Mikolaytis** [comment]
CPU increase was just by using Pooled Collections. Memory improve was just from making bidi classes - structs.
I'm reverting usage of PooledCollections and result is:
|                Method |       Mean |    Error |   StdDev |    Gen 0 |    Gen 1 |   Gen 2 | Allocated |
|---------------------- |-----------:|---------:|---------:|---------:|---------:|--------:|----------:|
|       BuildTextLayout |   638.8 us |  0.71 us |  0.59 us |  22.4609 |  10.7422 |       - |    138 KB |
| BuildEmojisTextLayout | 1,444.7 us |  3.51 us |  3.29 us |  60.5469 |  29.2969 |       - |    383 KB |
|   BuildManySmallTexts | 5,614.0 us | 61.26 us | 57.30 us | 578.1250 | 273.4375 | 70.3125 |  3,537 KB |

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0028505-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by Mikolaytis** [comment]
Screenshot 2023-01-11 at 03 47 36
CoaleaseLevels making some allocations. After optimize:
|                Method |       Mean |    Error |   StdDev |     Median |    Gen 0 |    Gen 1 | Allocated |
|---------------------- |-----------:|---------:|---------:|-----------:|---------:|---------:|----------:|
|       BuildTextLayout |   679.5 us | 17.21 us | 49.94 us |   659.6 us |  21.4844 |   6.8359 |    136 KB |
| BuildEmojisTextLayout | 1,459.3 us |  1.60 us |  1.42 us | 1,459.0 us |  60.5469 |  29.2969 |    381 KB |
|   BuildManySmallTexts | 5,578.0 us | 45.29 us | 42.37 us | 5,589.6 us | 531.2500 | 265.6250 |  3,264 KB |

**Comment by Mikolaytis** [comment]
Optimized some non-required collections allocations in BidiAlgoritm

|                Method |       Mean |    Error |    StdDev |    Gen 0 |    Gen 1 | Allocated |
|---------------------- |-----------:|---------:|----------:|---------:|---------:|----------:|
|       BuildTextLayout |   664.2 us | 11.57 us |  12.86 us |  21.4844 |   6.8359 |    133 KB |
| BuildEmojisTextLayout | 1,510.8 us | 29.01 us |  32.24 us |  60.5469 |  29.2969 |    377 KB |
|   BuildManySmallTexts | 5,207.9 us | 82.07 us | 109.56 us | 453.1250 | 226.5625 |  2,796 KB |

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0028509-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Review by Gillibald — APPROVED** [review]

**Pull request merged**
