### PR TITLE
Lazy load resources

### PR DESCRIPTION
**Pull request by grokys**
## What does the pull request do?

Makes resources in `ResourceDictionaries` defined in XAML be deferred/lazy loaded. This is going to be important after #8421 because our themes will be moved into resource dictionaries.

A quick and dirty measurement of this PR on top of the fluent theme defined with `ControlTheme` suggests that it could help speed up initial load by 40%, though this measurement was very unscientific.

This PR isn't as efficient as it could be because it reuses the xaml compiler's infrastructure for templates to implement deferred resources, which is not necessary for simple objects as it causes a copy of the XAML context. For many simple types that is not necessary and a static method would suffice.

Depends on #8421

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0021486-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by DrWenz** [comment]
We run a few performance tests on a low end device (Toradex Verdin iMX8M Mini DualLite 1GB, 2x 1.2Ghz A53, 1GB LPDDR4(32bit)).

At one point we measured the time `AvaloniaXamlLoader.Load(this);` on `App.axaml.cs::Initialise` needs to execute.
For measurement we use `System.Diagnostics.Stopwatch`.

With Avalonia 0.10.16 we measured **~1450-1600ms**.
With optimisations from branch `feature/lazy-load-resources` we are down to **~430-490ms**, which is really insane !  

**_!! This approach save us more than 1 second on startup !!_**

**Comment by maxkatz6** [comment]
> This PR isn't as efficient as it could be because it reuses the xaml compiler's infrastructure for templates to implement deferred resources, which is not necessary for simple objects as it causes a copy of the XAML context. For many simple types that is not necessary and a static method would suffice.

We also don't need to make lazy some (or all) structs like Color, Thickness, double... 

SolidColorBrush should be lazy now. But in the future, we should replace it with ImmutableSolidColorBrush if it doesn't have any bindings in the resource definition.
While ImmutableSolidColorBrush can be lazy only if it has StaticResource as it might depend on another lazy resource. Otherwise, code like `<SolidColorBrush Color="Red" />` can be immutable and not lazy without any overhead.
Similarly, to other types that has immutable alternatives, see https://github.com/AvaloniaUI/Avalonia/issues/6387.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0022784-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0022787-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by grokys** [comment]
Cherry-picked @maxkatz6's commits which disable lazy load for value type resources.

**Comment by grokys** [comment]
I think this PR is ready for review now.

@DrWenz we changed this slightly to make it not lazy-load value types. If you have chance, I'd be interested to see how this latest change affects your startup times (for better or worse).

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0022858-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by DrWenz** [comment]
> We run a few performance tests on a low end device (Toradex Verdin iMX8M Mini DualLite 1GB, 2x 1.2Ghz A53, 1GB LPDDR4(32bit)).
> 
> At one point we measured the time `AvaloniaXamlLoader.Load(this);` on `App.axaml.cs::Initialise` needs to execute. For measurement we use `System.Diagnostics.Stopwatch`.
> 
> With Avalonia 0.10.16 we measured **~1450-1600ms**. With optimisations from branch `feature/lazy-load-resources` we are down to **~430-490ms**, which is really insane !
> 
> **_!! This approach save us more than 1 second on startup !!_**

@grokys currently measure **~498-560ms** for `AvaloniaXamlLoader.Load(this);` on `App.axaml.cs::Initialise`.

**Review by maxkatz6 — APPROVED** [review]
I am going to merge it now. Further improvements can be done separately.

**Comment by grokys** [comment]
> currently measure ~498-560ms for AvaloniaXamlLoader.Load(this); on App.axaml.cs::Initialise.

Hmm ok, so looks like the change to not defer value types might have actually slowed us down a little (though not much). I think we'll need some proper benchmarks to test this and make more improvements.

**Comment by DrWenz** [comment]
> > currently measure ~498-560ms for AvaloniaXamlLoader.Load(this); on App.axaml.cs::Initialise.
> 
> 
> 
> Hmm ok, so looks like the change to not defer value types might have actually slowed us down a little (though not much). I think we'll need some proper benchmarks to test this and make more improvements.
> 
> 

@grokys let me know if i should run further tests

**Comment by workgroupengineering** [comment]
@DrWenz can you try [this](https://github.com/workgroupengineering/Avalonia/tree/features/ApplyStyling_Perf)? I have aligned the old closed PR (#5919) to the last master and know if it is still valid. On my machine, starting ControlCatalog.NetCore goes from 6063ms (master) to 4593ms (branch).

**Comment by DrWenz** [comment]
> @DrWenz can you try [this](https://github.com/workgroupengineering/Avalonia/tree/features/ApplyStyling_Perf)? I have aligned the old closed PR (#5919) to the last master and know if it is still valid. On my machine, starting ControlCatalog.NetCore goes from 6063ms (master) to 4593ms (branch).

@workgroupengineering on my testapp i measure ~498-560ms for AvaloniaXamlLoader.Load(this); on App.axaml.cs::Initialise.
Created new branch from master and applied changes from #5919

**Pull request merged**
