### PR TITLE
Fix KDE accent color hot switching

### PR DESCRIPTION
**Pull request by affederaffe**
## What does the pull request do?
Fix accent color switch while the application is running

## What is the current behavior?
Any later accent color changes aren't respected

## What is the updated/expected behavior with this PR?
Updating the accent color in system settings also updates the accent color in Avalonia

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Breaking changes
None

## Obsoletions / Deprecations
None

### CODE REVIEW

**Comment by maxkatz6** [comment]
Can it also fix this issue https://github.com/AvaloniaUI/Avalonia/issues/11147 ?

**Comment by affederaffe** [comment]
Not at the moment, but I could easily turn off the log message, if that's desired

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0034478-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by maxkatz6** [comment]
Probably, yes, as it outputs an error on any non-KDE distro.

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0034480-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Pull request merged**
