### PR TITLE
Fix transitions memory leak

### LINKED ISSUE #10151: Setting Transitions in ControlTheme causes a memory leak
**Describe the bug**
If Transitions are set in ControlTheme and applied to Control, when the Control is removed from the logical tree, the GC will not collect the Control, which causes a memory leak. The ControlTheme of many default controls (such as Button, ToggleSwitch) has set Transitions, as long as these controls are used, memory leaks may occur.

**To Reproduce**

1. Create new AvaloniaApplication with Avalonia Package(11.0.999-cibuild0026512-beta or later).
2. Add the following code to the end of the MainWindow method of MainWindow.xaml.cs:

            var panel = new StackPanel();
            Content = panel;
            Observable.Timer(TimeSpan.FromSeconds(3), TimeSpan.FromSeconds(1), AvaloniaScheduler.Instance).Subscribe(l =>
            {
                panel.Children.Clear();
                foreach (var i in Enumerable.Repeat(0, 100))
                {
                    panel.Children.Add(new ToggleSwitch() { Content = "Test" });
                }
            });

    This will remove previously added controls and add 100 new ToggleSwitches to the main window every second.
3. Build and run the program.
4. Observe memory consumption.

**Expected behavior**
Memory usage grows for a short period and tends to balance.

**Screenshots**
image

**Desktop (please complete the following information):**

- OS: [Version Windows 11 Pro Version 22H2]
- Version [11.0.999-cibuild0026512-beta or later]

**Additional context**
After debugging, I have located the problem point.
When a Transitions value is applied to Animatable, it will Add Handler For NewValue and Remove Handler  for OldValue in Transitions.Transitions,This usually doesn't cause any problems.
But when the property is applied by ControlTheme and the control is removed from the logical tree, OnPropertyChanged for the property is not raised, which causes the reference of the control to be kept in OldValue.
https://github.com/AvaloniaUI/Avalonia/blob/5896e3328676ec0aaf36b35f09356051f88c24c6/src/Avalonia.Base/Animation/Animatable.cs#L112
https://github.com/AvaloniaUI/Avalonia/blob/5896e3328676ec0aaf36b35f09356051f88c24c6/src/Avalonia.Base/Animation/Animatable.cs#L125
This problem did not exist before version 11.0.999-cibuild0026512-beta.This bug may be introduced by (https://github.com/AvaloniaUI/Avalonia/commit/693065fa1e2f1f5fbbb3327d79a4a9596d236416)

### PR DESCRIPTION
**Pull request by DmitryZhelnin**
## What does the pull request do?

Manages subscriptions to changes of `Transitions` collection of `Animatable` control.

## What is the current behavior?

Subscriptions managed only when `Transitions` property is changed.

## What is the updated/expected behavior with this PR?

Subscriptions additionally managed when control is attached to or detached from visual tree.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Fixed issues
Fixes #10151

### CODE REVIEW

**Comment by workgroupengineering** [comment]
Small suggestion add delegate caching eg:

```csharp
 public class Animatable : AvaloniaObject
 {
       readonly System.Collections.Specialized.NotifyCollectionChangedEventHandler _collectionChanged;

       public Animatable()
       {
          _collectionChanged =TransitionsCollectionChanged;
       }

         /// <summary>
        /// Enables transitions for the control.
        /// </summary>
        /// <remarks>
        /// This method should not be called from user code, it will be called automatically by the framework
        /// when a control is added to the visual tree.
        /// </remarks>
        protected void EnableTransitions()
        {
            if (!_transitionsEnabled)
            {
                _transitionsEnabled = true;

                if (Transitions is object)
                {
                    if (!_isSubscribedToTransitionsCollection)
                    {
                        _isSubscribedToTransitionsCollection = true;
                        Transitions.CollectionChanged += _collectionChanged;
                    }
                    AddTransitions(Transitions);
                }
            }
        }
}
```

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0029454-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by maxkatz6** [comment]
@workgroupengineering can be improved separately.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0029483-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]

**Pull request merged**
