### PR TITLE
added clear function to combobox

### LINKED ISSUE #11151: ComboBox opportunity to clear selected item
TextBox provides the user with the opportunity to clear all the text at once by pressing the button.
It would be nice if ComboBox had the same opportunity to clear selected item.

### PR DESCRIPTION
**Pull request by lhsrebel72**
Fixes #11151

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0037784-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]
Thanks!
Please sign the CLA if everything is fine, so it can be merged.

**Comment by lhsrebel72** [comment]
> @dotnet-policy-service agree

**Comment by lhsrebel72** [comment]
> Thanks! Please sign the CLA if everything is fine, so it can be merged.

got it!

**Comment by lhsrebel72** [comment]
@dotnet-policy-service agree

**Pull request merged**
