### PR TITLE
fix #4996

### LINKED ISSUE #4996: preview 6, macOS, first ctrl-key event swallowed
See: https://github.com/yatli/fvim/issues/167

### PR DESCRIPTION
**Pull request by yatli**

### CODE REVIEW

**Comment by yatli** [comment]
@danwalmsley FYI https://github.com/AvaloniaUI/Avalonia/issues/4996#issuecomment-743793794

**Comment by yatli** [comment]
ringring?

**Comment by grokys** [comment]
@danwalmsley ping

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019146-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019146-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by jmacato** [comment]
Closing this due to inactivity. Please reopen again if needed.

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0021230-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
