### PR TITLE
Make sure we don't crash when RTL text is wrapped

### PR DESCRIPTION
**Pull request by Gillibald**
## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

### CODE REVIEW

**Comment by Gillibald** [comment]
#4828

**Comment by adirh3** [comment]
Checked with cibuild0011280, fixed #4828

**Review by maxkatz6 — APPROVED** [review]
LGTM

**Comment by Gillibald** [comment]
#4848

**Pull request merged**
