### PR TITLE
failing unit test for issue #633 and #849

### PR DESCRIPTION
**Pull request by donandren**
added failing unit test for issue #633 - listbox with virtualization simple does not add proper horizontal scroll

added same unit test for listbox with virtualization none - it's ok

### CODE REVIEW

**Comment by donandren** [comment]
Looks like issue #633 is not completelly fixed, PR is rebased against latest master and the unit test 
(ListBox_Virt_Simple_Should_Add_Horizontal_Scroll_When_Needed) is still failing.

Problem looks like is only partially fixed - now there is a horizontal scrollbar, but the content in the listbox item has been cut.

Steps for reproduction:
- Start Virtualization application
- content of the  listbox items is cut if it exceed the listbox width
- expected behavior can be seen if the listbox virtualization is turned off ( select None instead Simple )

**Comment by donandren** [comment]
@grokys any chance to look at this?

**Comment by grokys** [comment]
Hi @donandren - I've been a bit busy recently and my time on Avalonia has been spent trying to get a new renderer working, so fixing bug has taken a second place for the moment, sorry. I will try to fix it soon.

**Comment by donandren** [comment]
the same test and repro steps apply to #849

**Comment by donandren** [comment]
#859 is fixed, implementation is made bit different fromwhat the unit test is checking, now it's not relevant

**Pull request closed without merging**
