### PR TITLE
Fix #13249 Mouse cursor on TextBox scrollbars shows as caret

### LINKED ISSUE #13249: Mouse cursor on TextBox scrollbars shows as caret
## Describe the bug
When a textbox is showing its scrollbars, when you hover the mouse over the scrollbars or move them, the mouse cursor is shown as a caret.

## To Reproduce

- run avalonia window containing a multiline TextBox, with enough text to have visible scrollbars
- hover the mouse cursor over the scrollbars, its displayed as a caret

## Expected behavior
Over the scrollbar the mouse should probably show as a normal pointer.

## Screenshots

https://github.com/AvaloniaUI/Avalonia/assets/10578746/daee445a-3c1f-4c88-a023-0e127cbc3c8d

## Environment

- OS: Windows 11
- Avalonia-Version: 11.0.4 and 11.0.5-rc1

## Additional context
demo solution:
[AvaTextBoxScrollBars.zip](https://github.com/AvaloniaUI/Avalonia/files/12899847/AvaTextBoxScrollBars.zip)

### PR DESCRIPTION
**Pull request by RobertMut**
## What does the pull request do?
Fixes bug mentioned in #13249 "Mouse cursor on TextBox scrollbars shows as caret"

## What is the current behavior?
When you move cursor over scrollbars it appears as normal pointer rather than caret

## What is the updated/expected behavior with this PR?
Mouse pointer over scrollbar should appear as arrow.

## How was the solution implemented (if it's not obvious)?
Added arrow cursor setter to ScrollViewer.xaml

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/avalonia-docs with user documentation

## Fixed issues
Fixes #13249

### CODE REVIEW

**Comment by RobertMut** [comment]
@dotnet-policy-service agree

**Comment by MrJul** [comment]
Thank you for your first contribution!

The selector isn't conditional at all here, so you can set `Cursor="Arrow"` directly on the needed controls inside the template instead.

That said, rather than specializing the `ScrollViewer` which can be used anywhere, why don't we fix the `TextBox` style itself to set the `IBeam` cursor on the inner panel directly, instead of the whole `ScrollViewer`? It's more of a general question, not directly addressed to you :)

**Comment by RobertMut** [comment]
> Thank you for your first contribution!
> 
> The selector isn't conditional at all here, so you can set `Cursor="Arrow"` directly on the needed controls inside the template instead.
> 
> That said, rather than specializing the `ScrollViewer` which can be used anywhere, why don't we fix the `TextBox` style itself to set the `IBeam` cursor on the inner panel directly, instead of the whole `ScrollViewer`? It's more of a general question, not directly addressed to you :)

@MrJul Thanks for feedback. 
I've introduced changes you mentioned. 
Waiting for the review to make sure we're on the same page :)

**Comment by MrJul** [comment]
Thanks @RobertMut 

As mentioned above, I believe we can have a *local* solution by fixing the `TextBox`'s style instead.

Why? The idea here is to avoid changing the `ScrollViewer` globally, which isn't really specific to the `TextBox` and can be used anywhere. I know we're only talking about a `Cursor` here (which isn't really often overridden), but it's more of a general issue, making local, targeted, changes instead of global ones.

Are you interested in trying to fix the `TextBox` style instead?

It would involve setting the `IBeam` cursor on the necessary panel(s) instead of the `TextBox`'s root, including the `ScrollViewer`. A transparent background might be required.

**Comment by RobertMut** [comment]
> Thanks @RobertMut
> 
> As mentioned above, I believe we can have a _local_ solution by fixing the `TextBox`'s style instead.
> 
> Why? The idea here is to avoid changing the `ScrollViewer` globally, which isn't really specific to the `TextBox` and can be used anywhere. I know we're only talking about a `Cursor` here (which isn't really often overridden), but it's more of a general issue, making local, targeted, changes instead of global ones.
> 
> Are you interested in trying to fix the `TextBox` style instead?
> 
> It would involve setting the `IBeam` cursor on the necessary panel(s) instead of the `TextBox`'s root, including the `ScrollViewer`. A transparent background might be required.

Thanks for comment!
Finally got time to sit down. Now i changed `TextBox`, but in slightly different way. Modifying `Panel` got odd-looking result (i guess there is other part messing with it, but i didn't figured it out at this point), so did changes to `ScrollViewer` inside `TextBox` as you suggested. 
The left ones are with `IBeam` on `Panel`, right - current changes.

**Comment by MrJul** [comment]
Looking good!

After testing, the floating watermark (`PART_FloatingWatermark`) now has the default cursor instead of `IBeam` previously. Since it's "click-through" I believe it should be `IBeam` too.

**Review by MrJul — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
