### PR TITLE
Improve Geometry Parse/ToString

### PR DESCRIPTION
**Pull request by donandren**
## What does the pull request do?

<s>- `Geometry.Parse` creates PathGeometry to be consistent with WPF and much better while diagnosing issues with path mini markup language</s>
- `PathGeometry.ToString()` return meaningful string representing the geometry

## What is the current behavior?

- no ToString overrides don't exist

## Checklist

- [x] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

### CODE REVIEW

**Comment by Gillibald** [comment]
This will only produce equal strings for paths that don't contain relative coordinates or implicit commands. But I guess that is fine.

**Comment by ahopper** [comment]
Not sure if this really matters but it does make GeometryDrawing more heavy weight.

**Comment by Gillibald** [comment]
I think this is nice for debugging but we do not have to change Geometry.Parse to make this possible. There is a reason IGeometryContext was introduced.

**Comment by donandren** [comment]
> 
> 
> This will only produce equal strings for paths that don't contain relative coordinates or implicit commands. But I guess that is fine.

not exactly, relative coordinates and implicit will be formatted and converted to absolute, but that's expected

**Comment by grokys** [comment]
> Geometry.Parse creates PathGeometry to be consistent with WPF and much better while diagnosing issues with path mini markup language

`Geometry.Parse` in WPF creates a `StreamGeometry` too:

```
var g = Geometry.Parse("M0,0 L10,10");
System.Diagnostics.Debug.WriteLine(g.GetType().Name);
> StreamGeometry
```

**Review by grokys — APPROVED** [review]

**Pull request merged**
