### PR TITLE
fix: fix ListBoxItem generation.

### PR DESCRIPTION
**Pull request by rabbitism**
## What does the pull request do?

Make sure ListBoxItem is the container for ListBox Items.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

### CODE REVIEW

**Comment by robloo** [comment]
Just upgraded to preview5 -- and among many errors -- it looks like this PR will fix one of them. Is this similar to the issue you are fixing here?

image

```
at Avalonia.StyledElement.OnAttachedToLogicalTreeCore(LogicalTreeAttachmentEventArgs e)\r\n
at Avalonia.StyledElement.OnAttachedToLogicalTreeCore(LogicalTreeAttachmentEventArgs e)\r\n 
at Avalonia.StyledElement.Avalonia.Controls.ISetLogicalParent.SetParent(ILogical parent)\r\n
at Avalonia.StyledElement.SetLogicalParent(IList children)\r\n
at Avalonia.Visual.LogicalChildrenCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)\r\n
at Avalonia.Collections.AvaloniaList`1.NotifyAdd(IList t, Int32 index)\r\n
at Avalonia.Controls.Panel.ChildrenChanged(Object sender, NotifyCollectionChangedEventArgs e)\r\n
at Avalonia.Collections.AvaloniaList`1.NotifyAdd(T item, Int32 index)\r\n 
```

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0029697-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by rabbitism** [comment]
@robloo might be related to #10246, but not this one.

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0029729-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Pull request merged**
