### PR TITLE
Consolidated NuGet package versions and fixed package downgrades

### PR DESCRIPTION
**Pull request by wieslawsoltes**

### CODE REVIEW

**Comment by kekekeks** [comment]
We probably need to move common package references to a `.props` file like I did [for unit tests](https://github.com/AvaloniaUI/Avalonia/blob/master/tests/coretests.props#L25). It will remove "versions out of sync" issue completely.

**Comment by wieslawsoltes** [comment]
After migrating to `netstandard` this shouldn't be that big issue anymore. I think now when we reference `netstandard` some of packages will not be necessary anymore. Anyway good idea to consolidate all common package references in one place. Not sure how NuGet updates will work in this case.

**Comment by kekekeks** [comment]
Well, nuget restore works fine for unit tests and manually editing `csproj`/`props` files is much better with VS2017 which doesn't require you to reload the whole solution anymore.

**Comment by wieslawsoltes** [comment]
Yeah that sounds good. 

Can we merge this PR before moving common package references to a .props file?

**Pull request merged**
