### PR TITLE
Fix native dialogs throwing InvalidCastException

### PR DESCRIPTION
**Pull request by Deadpikle**
## What does the pull request do?

Managed file dialogs are currently throwing an `InvalidCastException` due to this XAML:

`<Setter Property="Margin">4</Setter>`

It complains that it cannot convert a string to a `Thickness`. (It seems like that should work, but let's just roll with the error for now I guess...)

You can fix this by doing:

`<Setter Property="Margin" Value="4"/>`

## What is the current behavior?

Managed file dialogs don't work at all and crash the program. You can repro this in the sample.

## What is the updated/expected behavior with this PR?

Managed file dialogs no longer crash!

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

## Breaking changes

None

### CODE REVIEW

**Comment by danwalmsley** [comment]
@kekekeks @grokys this seems to be treating the symptom rather than fixing the cause?

**Review by grokys — APPROVED** [review]
Yeah, we can merge this to get the dialogs fixed, but we need to investigate the root cause.

**Comment by Deadpikle** [comment]
Would you like me to file a corresponding issue for the underlying bug?

**Comment by grokys** [comment]
> Would you like me to file a corresponding issue for the underlying bug?

Please!

**Pull request merged**
