### PR TITLE
Port of WPF WrapPanel

### PR DESCRIPTION
**Pull request by wieslawsoltes**
## What does the pull request do?

Ports the WrapPanel control from dotnet/wpf repository.

## What is the current behavior?

WrapPanel is broken when wrapping multiple-lines in TabControl. 

UPDATE: After the port from WPF the Avalonia TabControl multi-line issue still exists. This seems to be another not related issue I think.

## What is the updated/expected behavior with this PR?

WrapPanel's behavior should now be inline with WPF's (did not port  ItemWidth/ItemHeight).

## Checklist

- [x] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

### CODE REVIEW

**Comment by wieslawsoltes** [comment]
@AvaloniaUI/core  We should probably port most of WPF `DoubleUtil` to Avalonia `MathUtilities` before porting stuff from WPF. The https://github.com/AvaloniaUI/Avalonia/pull/2563 also needs WPF `DoubleUtil`.

**Comment by wieslawsoltes** [comment]
Tested WPF version with Avalonia unit tests, and WPF passes all tests, so the issue/difference is in Avalonia way of doing layout https://github.com/wieslawsoltes/WpfGridTest/blob/77d4c02c1c2dcba59c72d901a6d12c9b63c737fe/WpfWrapPanelTest.cs#L38-L123

**Comment by wieslawsoltes** [comment]
For future reference this are WPF tests, all pass when running under netcoreapp3.0:
```C#
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using Xunit;
using Xunit.Abstractions;

namespace WpfWrapPanelTest
{
    public static class FrameworkElementExtensions
    {
        public static Rect BoundsRelativeTo(this FrameworkElement element, Visual relativeTo)
        {
            return element.TransformToVisual(relativeTo).TransformBounds(new Rect(element.RenderSize));
        }

        public static Rect BoundsRelativeTo(this UIElement element, Visual relativeTo)
        {
            return BoundsRelativeTo((FrameworkElement)element, relativeTo);
        }
    }

    public class WpfWrapPanelTest
    {
        private readonly ITestOutputHelper output;

        public WpfWrapPanelTest(ITestOutputHelper output)
        {
            this.output = output;
        }

        [WpfFact]
        public void Lays_Out_Horizontally_On_Separate_Lines()
        {
            var target = new WrapPanel()
            {
                Width = 100,
                Children =
                {
                    new Border { Height = 50, Width = 100 },
                    new Border { Height = 50, Width = 100 },
                }
            };

            target.Measure(new Size(double.PositiveInfinity, double.PositiveInfinity));
            target.Arrange(new Rect(target.DesiredSize));

            Assert.Equal(new Size(100, 100), new Size(target.ActualWidth, target.ActualHeight));
            Assert.Equal(new Rect(0, 0, 100, 50), target.Children[0].BoundsRelativeTo(target));
            Assert.Equal(new Rect(0, 50, 100, 50), target.Children[1].BoundsRelativeTo(target));
        }

        [WpfFact]
        public void Lays_Out_Horizontally_On_A_Single_Line()
        {
            var target = new WrapPanel()
            {
                Width = 200,
                Children =
                {
                    new Border { Height = 50, Width = 100 },
                    new Border { Height = 50, Width = 100 },
                }
            };

            target.Measure(new Size(double.PositiveInfinity, double.PositiveInfinity));
            target.Arrange(new Rect(target.DesiredSize));

            Assert.Equal(new Size(200, 50), new Size(target.ActualWidth, target.ActualHeight));
            Assert.Equal(new Rect(0, 0, 100, 50), target.Children[0].BoundsRelativeTo(target));
            Assert.Equal(new Rect(100, 0, 100, 50), target.Children[1].BoundsRelativeTo(target));
        }

        [WpfFact]
        public void Lays_Out_Vertically_Children_On_A_Single_Line()
        {
            var target = new WrapPanel()
            {
                Orientation = Orientation.Vertical,
                Height = 120,
                Children =
                {
                    new Border { Height = 50, Width = 100 },
                    new Border { Height = 50, Width = 100 },
                }
            };

            target.Measure(new Size(double.PositiveInfinity, double.PositiveInfinity));
            target.Arrange(new Rect(target.DesiredSize));

            Assert.Equal(new Size(100, 120), new Size(target.ActualWidth, target.ActualHeight));
            Assert.Equal(new Rect(0, 0, 100, 50), target.Children[0].BoundsRelativeTo(target));
            Assert.Equal(new Rect(0, 50, 100, 50), target.Children[1].BoundsRelativeTo(target));
        }

        [WpfFact]
        public void Lays_Out_Vertically_On_Separate_Lines()
        {
            var target = new WrapPanel()
            {
                Orientation = Orientation.Vertical,
                Height = 60,
                Children =
                {
                    new Border { Height = 50, Width = 100 },
                    new Border { Height = 50, Width = 100 },
                }
            };

            target.Measure(new Size(double.PositiveInfinity, double.PositiveInfinity));
            target.Arrange(new Rect(target.DesiredSize));

            Assert.Equal(new Size(200, 60), new Size(target.ActualWidth, target.ActualHeight));
            Assert.Equal(new Rect(0, 0, 100, 50), target.Children[0].BoundsRelativeTo(target));
            Assert.Equal(new Rect(100, 0, 100, 50), target.Children[1].BoundsRelativeTo(target));
        }
    }
}
```

```XML
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.abstractions" Version="2.0.3" />
    <PackageReference Include="xunit.assert" Version="2.4.1" />
    <PackageReference Include="xunit.core" Version="2.4.1" />
    <PackageReference Include="xunit.extensibility.core" Version="2.4.1" />
    <PackageReference Include="xunit.extensibility.execution" Version="2.4.1" />
    <PackageReference Include="xunit.runner.console" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.1" />
    <DotNetCliToolReference Include="dotnet-xunit" Version="2.3.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.9.0" />
    <PackageReference Include="Xunit.StaFact" Version="1.0.3-beta" />
  </ItemGroup>

</Project>
```

**Comment by wieslawsoltes** [comment]
This is ready for review.

**Review by grokys — APPROVED** [review]
LGTM, thanks @wieslawsoltes!

**Pull request merged**
