### PR TITLE
Add binding to Window.Position

### LINKED ISSUE #3494: Unable to bind to Window.Position
It is not currently possible to bind to the Position element of Window. The compiler returns the following error:

  MainWindow.xaml(7, 9): [XAMLIL] Unable to find suitable setter or adder for property Position of type Avalonia.Controls:Avalonia.Controls.Window for argument Avalonia.Markup:Avalonia.Data.Binding, available setter parameter lists are:
Avalonia.PixelPoint (line 7 position 9) Line 7, position 9.

It looks like the Position is treated differently to Width and Height. Is it possible to allow binding to this property?

### PR DESCRIPTION
**Pull request by Deadpikle**
## What does the pull request do?

Adds mechanisms so that users can bind to `Avalonia.Controls.Window.Position`.

## What is the current behavior?

Right now, you can't bind to `Window.Position`.

## What is the updated/expected behavior with this PR?

You can now bind to `Window.Position` with a `PixelPoint` property in your ViewModel, e.g. `<Window Position="{Binding SomeVariable}"> ... </Window>`.

## How was the solution implemented (if it's not obvious)?

I'll admit, this fix is kind of kooky, and there might be a better way.

First, I added a `StyledProperty` to `Window` for `Position`. (Should this be a `DirectProperty` instead...?) I monitor the event `Window.PositionChanged` so that I can update the dependency property value as needed. I also monitored the property change (`PositionProperty.Changed.AddClassHandler`) so that I could tell the Window to update via `Window.PlatformImpl`. 

Here's the strange part: on windows, we can't blindly update the dependency property in the `Window.PositionChanged` event handler, because when the dependency property changes (`SetValue(PositionProperty...)`), it causes `PositionProperty.Changed` to be called, which then triggers a move of the actual window. This is all well and good until on Windows this causes:

`PositionChanged?.Invoke(new PixelPoint((short)(ToInt32(lParam) & 0xffff), (short)(ToInt32(lParam) >> 16)));`

to be called, which then causes `Window.PositionChanged` to be called (with slightly different numbers, potentially!), which of course then causes a dependency property update, and things keep moving on forever. 

To stop that from happening, I added a bool to make sure that the window is _not_ moved additional times when I'm calling `SetValue(PositionProperty...)` from `Window.PositionChanged`.

...A better way to handle this would be to somehow call `SetValue` without actually triggering another `PositionProperty.Changed` event. I'm guessing there are better ways, but this way by opening this PR at least some discussion is started.

## Checklist

- [ ] Added unit tests (if possible)?
- [x] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

## Breaking changes

None

## Fixed issues

Fixes #3494.

### CODE REVIEW

**Comment by kekekeks** [comment]
I'm not sure if we can allow to bind to this property (or even should have a setter at all). On some systems positioning is 
1) async
2) can be cancelled

i. e. the workflow looks like:
1) app requests a position change
2) time passes
3) display server triggers a position change event

So `Window.Position` property will *continue to report the old value* for a while. This can't be changed and is by design since display server or window manager might refuse to change the position or reposition the window to completely different spot than requested.

On upcoming Wayland platform it's even worse Position will be a no-op and will always report (0, 0).

**Comment by Deadpikle** [comment]
Oh. Yeah, that would be a Big Problem. I didn't realize! This code definitely doesn't cover those use cases.

Willing to close this PR/change code as needed, but it definitely sounds like the current method of doing things is a no-go.

**Comment by grokys** [comment]
Given what @kekekeks describes, I think there are 3 solutions here:

- Make `Position` writable but don't expose the written value until the OS has updated the position
  - This might cause problems with two-way bindings?
- Make `Position` writable and expose the written value before the OS has updated the position
  - I think this is what we currently do - it's not ideal because we could be reporting an incorrect value
- Make `Position` readonly and add an `async Task SetPosition(PixelPoint p)` method, possibly with a `CanSetPosition` property (naming TBD)
  - This is probably the correct solution?

Either way, it looks like binding `Window.Position` isn't going to fly in the long-term so we should probably close this PR?

**Comment by kekekeks** [comment]
>async Task SetPosition(PixelPoint p)

There is no way to know if a particular resize was triggered by a particular resize request.

**Comment by Deadpikle** [comment]
`binding Window.Position isn't going to fly in the long-term so we should probably close this PR` -> 👍 

Thanks for considering! :)

**Pull request closed without merging**
