### PR TITLE
Update System.Reactive to 4.4.1 to avoid infinite recursive generics in CoreRT

### LINKED ISSUE #3366: Avalonia 0.9.0 With Corert Takes so long To Compile
hello guys this is not really an issue but i wanted to post it in here to hear your thoughts.
I'm using Corert with 'Avalonia latest Released Build' and all were good till u guys Released the 0.9.0 V Now my app Takes so much Time To Compile 'I had to Give Up after more than 2 Hours' and this was an issue with every Nightly Build and Now I'm Facing it with he latest Released 0.9.0 the 0.8.3 and before was all good, so why and what's changed in this new Released is there anyway to Update 0.8.3 to the latest version with the same Results like Earlier Releases?

### PR DESCRIPTION
**Pull request by hez2010**
## What does the pull request do?
Update System.Reactive to 4.4.1 to avoid infinite recursive generics in CoreRT.

## What is the current behavior?
Compilation never finished while building with CoreRT

## What is the updated/expected behavior with this PR?
Build with CoreRT successfully.

## How was the solution implemented (if it's not obvious)?
This issue was casued by System.Reactive and fixes to System.Reactive has been applied (https://github.com/dotnet/reactive/pull/1116, https://github.com/dotnet/reactive/pull/1121 and https://github.com/dotnet/reactive/pull/1177), so updating System.Reactive can fix this issue.

## Checklist

- [x] Added unit tests (if possible)?
- [x] Added XML documentation to any related classes?
- [x] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

## Breaking changes
No

## Fixed issues
Fixes #3366

### CODE REVIEW

**Comment by hez2010** [comment]
Confirmed resolved with 0.9.999-cibuild0006487-beta.

**Review by grokys — APPROVED** [review]
LGTM, thanks @hez2010 !

**Comment by hez2010** [comment]
I think this fix should be backport to v0.9 release, otherwise users who are using v0.9.x will never got successful AOT compilation.

**Comment by kekekeks** [comment]
>will never get successful AOT compilation.

You can just reference ReactiveUI directly from your project.

**Comment by danwalmsley** [comment]
@kekekeks any reason not to backport this?

**Comment by kekekeks** [comment]
Enforcing dependency version that's not strictly required might expose issues in end-user apps for absolutely no reason. 

AOT was previously broken by us bumping System.Reactive to a newer version for the sake of bumping System.Reactive to a newer version.

Also, bumping dependencies is breaking SemVer.

**Pull request merged**
