### PR TITLE
Fix mouse wheel events being eaten on ComboBox on browser

### PR DESCRIPTION
**Pull request by aldelaro5**
## What does the pull request do?
This fixes an issue I noticed where if you have enough items in a ComboBox on browser to have a scrollbar, scrolling is ignored. It forces the user to drag the scrollbar.

## What is the current behavior?
Due to https://github.com/AvaloniaUI/Avalonia/issues/2285, every time a mouse wheel event occurs, the event is eaten if the TopLevel is the same then the ComboBox. This works fine on Desktop platforms because the PopUp is a PopUpRoot which has its own TopLevel so the 2 TopLevels should never be the same otherwise the aforementioned issue occurs.

This however doesn't work with browser because there's only one TopLevel being the WebEmbeddableControlRoot and the PopUp is actually an OverlayPopupHost which doesn't have its own TopLevel. What this meant is that this check actually eats every mouse wheel events.

## What is the updated/expected behavior with this PR?
After a lot of testing, I found that the original issue is actually not reproducible on browser, only on desktops. It seems the popup itself prevents the outer views to get scrolled. I am not sure why exactly, but considering I can't reproduce the issue that justified this code, it's probably okay. FYI, this is the original PR: https://github.com/AvaloniaUI/Avalonia/pull/2287

EDIT: it was decided to remove the whole handler entirely.

## How was the solution implemented (if it's not obvious)?
Simply add an additional condition to have this input eating behavior to not do it if the popup is an OverlayPopupHost.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Breaking changes
None.

## Obsoletions / Deprecations
None.

## Fixed issues
No issue was filed for this, I investigated this myself and found I could file the PR directly. If this is a problem, I could file an issue.

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0033671-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by maxkatz6** [comment]
Not sure if relying on OverlayPopupHost is the best solution.
In the future we might switch to "native" popups on browser backend by creating a new canvas for each popup. This way there avalonia overlay layer won't be used.

**Comment by aldelaro5** [comment]
> Not sure if relying on OverlayPopupHost is the best solution. In the future we might switch to "native" popups on browser backend by creating a new canvas for each popup. This way there avalonia overlay layer won't be used.

Would checking if it is a PopupRoot be a better solution then? This way, only PopUpRoot will have this event handler which implicitly would not include the overlay one.

**Comment by aldelaro5** [comment]
Can I get an update if this is what I should try to do?

**Comment by grokys** [comment]
@maxkatz6 ping.

**Comment by maxkatz6** [comment]
Since this fix doesn't require any breaking changes and can be pushed later, I keep postponing the review of this PR. Sorry about that.
As I stated above, relying on OverlayPopup in the controls code isn't the best solution. Probably redoing part of #2287 is better.

For now what I found, the same issue is reproducible on desktop as well, if you enable overlay popups in BuildAvaloniaApp builder:
```
.With(new Win32PlatformOptions()
{
    OverlayPopups = true
})
```

**Comment by maxkatz6** [comment]
Actually, I don't think I can reproduce that issue from #2287 now. If I add combobox to each listbox item, scrolling is properly handled on combobox instead of listbox, even without that hack with top level handling.
Possibly light dismiss layer does the job now?

image

**Comment by maxkatz6** [comment]
@aldelaro5 after discussion with @grokys it seems to be safe to remove that old hack with toplevel wheel handling.

**Comment by aldelaro5** [comment]
> @aldelaro5 after discussion with @grokys it seems to be safe to remove that old hack with toplevel wheel handling.

To clarify, is that what my pr was doing or it's a completely different solution?

**Comment by maxkatz6** [comment]
@aldelaro5 OverlayHost check is a hack on top of an old hack. A safer solution seems to just remove an old hack as it's not needed anymore. I.e. removing the whole `AddDisposableHandler(PointerWheelChangedEvent)` block.

**Comment by aldelaro5** [comment]
@maxkatz6 There, I removed it and made sure it was still fixing the issue.

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0035491-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by aldelaro5** [comment]
Hum, what happened? it passed the CI for auto merge, but failed the CI for the actual merge?

**Comment by maxkatz6** [comment]
@aldelaro5 must be a fluke, typical with ours CI

**Pull request merged**
