### PR TITLE
fix polygon/polyline load fail points within the template

### PR DESCRIPTION
**Pull request by a526684540**
## What does the pull request do?
use polygon in button's template,polygon invisible
i want fix polygon/polyline Unable to load points within the template.

## What is the current behavior?
errorimage

## What is the updated/expected behavior with this PR?
Dingtalk_20230824153410
polygon/polyline can load points within the template.

## How was the solution implemented (if it's not obvious)?
Within the polygon constructor, “Points=new Points()”，BindingPriority is LocalValue；
When in the Template，loading points from xaml，BindingPriority is Template，so loading faild，the property points always the "new Points()";

### CODE REVIEW

**Comment by a526684540** [comment]
@dotnet-policy-service agree

**Comment by maxkatz6** [comment]
It's not a correct fix.
With this PR PointsProperty will have single instance of the Points array as a default value. Meaning, the same array is going to be shared.

Probably, the better fix is to call `SetValue(ProintsProperty, new Points(), BindingPriority.Template);` from the ctor instead of `Points = new Points`.

**Comment by a526684540** [comment]
I agree, your idea is better.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0038746-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]

**Pull request merged**
