### PR TITLE
Fix for issue #13493

### LINKED ISSUE #13493: TransitioningContentControl issue
## Describe the bug

TCC will throw an exception when switch back to the old content:
Even I ensured control's Visual Parent is cleared:

image

I tried to write a repro but I failed to do so.

## Expected behavior

Content should switch between old and new content.

## Environment 

- OS: Windows 11 22H2
- Avalonia-Version: 11.0.5

### PR DESCRIPTION
**Pull request by laolarou726**
## What does the pull request do?

This PR fixed an issue mentioned in [#13493](https://github.com/AvaloniaUI/Avalonia/issues/13493)
For function `UpdateContent(bool withTransition)`, this PR ensures that the Updated content is not in the last presented `ContentPresenter`, otherwise it will raise the exception mentioned in [#13493](https://github.com/AvaloniaUI/Avalonia/issues/13493)

## What is the current behavior?

Currently, in some cases, the new content is the content that TCC just presented. An exception will be raised.

## What is the updated/expected behavior with this PR?

Now there will be no such issue.

## Checklist

- [x] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/avalonia-docs with user documentation

## Fixed issues

- Fixes #13493

### CODE REVIEW

**Comment by maxkatz6** [comment]
Can you add a test for this scenario? In TransitioningContentControlTests file.
This PR also broken some other tests there.

**Comment by laolarou726** [comment]
> Can you add a test for this scenario? In TransitioningContentControlTests file. This PR also broken some other tests there.

I just fixed and now all the tests are passed. Also, I added one more test to verify the check is working. Could you please review it again? Thx!

**Comment by laolarou726** [comment]
Can any one help me to confirm that this PR is able to merge into the master? Thx.

**Review by grokys — CHANGES_REQUESTED** [review]
Hi @laolarou726 - thanks for the PR! However looking at the test, it seems to pass even without the modified code in `TransitioningContentControl`. In addition when I run your repro (https://github.com/laolarou726/TCCExceptionTest) I don't see any exception there either.

The fix looks reasonable but I'd like to be able to confirm the problem first and I'm not sure why I'm unable to. Does the unit test fail for you if you remove the changes to `TransitioningContentControl`?

**Comment by laolarou726** [comment]
> Hi @laolarou726 - thanks for the PR! However looking at the test, it seems to pass even without the modified code in `TransitioningContentControl`. In addition when I run your repro (https://github.com/laolarou726/TCCExceptionTest) I don't see any exception there either.
> 
> 
> 
> The fix looks reasonable but I'd like to be able to confirm the problem first and I'm not sure why I'm unable to. Does the unit test fail for you if you remove the changes to `TransitioningContentControl`?

Ohh sorry for the confusion, in the repo I replace the transitioningcontentcontrol to the fixed implementation "TCC". If you change all the TCC back to the TransitioningContentControl, the exception will occur. I'll just update the repo now.

**Comment by laolarou726** [comment]
@grokys I just updated the repro, and now the exception will shown. Please click the "Start" and wait for a few seconds. Then the exception will be thrown. [https://github.com/laolarou726/TCCExceptionTest](https://github.com/laolarou726/TCCExceptionTest).

For the test, do you think it's ok to just remove it?

**Comment by laolarou726** [comment]
> Hi @laolarou726 - thanks for the PR! However looking at the test, it seems to pass even without the modified code in `TransitioningContentControl`. In addition when I run your repro (https://github.com/laolarou726/TCCExceptionTest) I don't see any exception there either.
> 
> 
> 
> The fix looks reasonable but I'd like to be able to confirm the problem first and I'm not sure why I'm unable to. Does the unit test fail for you if you remove the changes to `TransitioningContentControl`?

Could you please check the repo again? Thx!

**Comment by laolarou726** [comment]
@grokys  Could you please review the repro again? Thanks!

**Review by maxkatz6 — APPROVED** [review]

**Pull request merged**
