### PR TITLE
Notifications: Correctly set parent

### PR DESCRIPTION
**Pull request by thopiekar**
As of Avalonia 11 the notifications are broken and are shown always in the upper left corner. I'm not an expert, but as the parent of the control is not correctly set, we can imagine that the library assumes that the coordinate (0, 0) is going to be used and thus it appears always at a static location. After fixing the assignment of the parent, the notification bubbles are shown at the right corner again.

Signed-off-by: Thomas Karl Pietrowski <thopiekar@gmail.com>
Signed-off-by: Thomas Karl Pietrowski <t.pietrowski@item24.com>
Signed-off-by: Malte Lauterjung <malte.lauterjung@trinidat.de>

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=9592) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=9592) before we can accept your contribution.<br/><br/>:x: thopiekar [sign now](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=9592)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/AvaloniaUI/Avalonia?pullRequest=9592) it.</sub>

**Comment by thopiekar** [comment]
Validated on my side with the ControlCatalog.NetCore sample as well as on the actual application being developed.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0026901-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-nightly/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0026909-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-nightly/nuget/v3/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]
LGTM, thanks!

**Comment by thopiekar** [comment]
Can't remember where I missed the checkbox but looks like did this somewhere. Just updated the branch - let's see how it goes.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0027041-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-nightly/nuget/v3/index.json) [PRBUILDID]

**Pull request merged**
