### PR TITLE
feat: formatting code and (a)xaml on build

### LINKED ISSUE #4072: Add Xaml Styles to project
It seems like https://github.com/Xavalon/XamlStyler extension works well with Avalonia.
So I would suggest to add settings.xamlstyler file with code style for xaml files in Avalonia solution.

Unfortunately it isn't integrated with .editorconfig, so we need another one file in repository for that...

### PR DESCRIPTION
**Pull request by workgroupengineering**
## What does the pull request do?

Format code and (a)xaml files modified at build time.

## What is the current behavior?

none

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/avalonia-docs with user documentation

## Fixed issues

Fixes #4072

### CODE REVIEW

**Comment by maxkatz6** [comment]
I don't think we can have an auto-formatting in the repository. But we definitely should have a XamlStyler set up, and incrementally update current XAML files to match it.

**Comment by workgroupengineering** [comment]
> I don't think we can have an auto-formatting in the repository. But we definitely should have a XamlStyler set up, and incrementally update current XAML files to match it.

Hi, this code does not formatting whole repository, ma only modified not staged files (.cs,.xaml,axaml).

see

https://github.com/workgroupengineering/Avalonia/blob/ec52006fd121bc01cef7a1091b7da9e637094fe6/build/dotnet-format.targets#L9-L14

https://github.com/workgroupengineering/Avalonia/blob/ec52006fd121bc01cef7a1091b7da9e637094fe6/build/XamlStyler.Console.targets#L9-L14

**Comment by robloo** [comment]
@maxkatz6 @grokys 

> I don't think we can have an auto-formatting in the repository. But we definitely should have a XamlStyler set up, and incrementally update current XAML files to match it.

I've been reviewing this tool and I think we should reconsider. It works VERY well and as stated by @workgroupengineering can be configured to format only new files in a GitHub action. I have a JSON settings file now that works well with Avalonia and could provide input here.

Other large projects have switched to automatic code formatting. So I'm not sure why there is an aversion to automatic code formatting -- it actually seems like a requirement at this point since there are so many people working on Avalonia. XAML is a good first step before touching C# as well.

We should also probably do a full formatting pass and then add it to the Git blame ignore file so it doesn't mess up history. If I recall that was the only real concern with large code formatting but Git already supports this use case well.

**Comment by maxkatz6** [comment]
We can start with pushing xaml styler config in a separated PR. And formatting project by project.

But I am not sure about automated formatting. Previously this discussion went nowhere, and I am uninterested to push this discussion again.

**Comment by robloo** [comment]
> But I am not sure about automated formatting. Previously this discussion went nowhere, and I am uninterested to push this discussion again

That discussion, if it's the one I was a part of, was focused on C# which is a bigger task. The reason it was shut down if I recall is because it destroys the git blame history.

There is new information now: namely the .git-blame-ignore-revs file supported by GitHub which allows blame to still work after a major formatting change. It can also be passed in the command line. I am also talking about Xaml only which is significantly lighter than C#. All this is to say we are in a different place now and a new discussion seems warranted.

We should however format everything at once -- not project by project. That keeps the commits to a minimum and a single hash can be added to a git blame ignore file which is better for performance.

**Pull request closed without merging**
