### PR TITLE
fix the separator can not show

### LINKED ISSUE #9643: NativeMenuItemSeparator does not work in exported managed menu on Windows
When using <NativeMenuItemSeparator /> and then <NativeMenuBar /> to place it in Windows, the horizontal line is not shown. Instead a greyed out menu item named "Avalonia.Controls.NativeMenuItemSeparator" is shown.

**To Reproduce**

1. Clone Avalonia repo from github on a Windows machine.
2. Checkout branch 'origin/releases/11.0.0.-preview4'
3. Build in Visual Studio 2022 17.4.1
4. Run 'ControlCatalog.NetCore'
5. Select the 'Menu' page sample
6. Expand the top leftmost item 'File'.

**Expected behavior**
I expected a horizontal line for the separator.

**Screenshots**
image

**Desktop (please complete the following information):**

- OS: Windows 11
- Version 11.0.0-preview4

### PR DESCRIPTION
**Pull request by startewho**
## What does the pull request do?

Try to fixes #9643 

image

replace the base class to NativeMenuItem and setting the Header to "-"

Btw，it is a long time from i first time i use the wpf framework.,and Avalonia is really better  in some places.greate work

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=9655) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=9655) before we can accept your contribution.<br/><br/>:x: startewho [sign now](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=9655)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/AvaloniaUI/Avalonia?pullRequest=9655) it.</sub>

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0027317-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-nightly/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0027316-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-nightly/nuget/v3/index.json) [PRBUILDID]

**Comment by grokys** [comment]
@danwalmsley I think this is your area.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0027582-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0027651-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Pull request merged**
