### PR TITLE
Avalonia.Headless.XUnit extensions and attempt to make Avalonia.Headless easier to use

### PR DESCRIPTION
**Pull request by maxkatz6**
## What does the pull request do?

1. Adds integration with XUnit. At this point provides an assembly-level attribute to configure avalonia test framework. In the future it would be nice to have per-method attribute without changing global test framework, but there is a question, how to pass an application/appbuilder type/instance.
2. Current test framework creates an application/appbuilder using new reflection method AppBuilder.Configure(Type) shared between unit tests and previewer.
3. Add missing nullable/trimming/documentation to the headless project.
4. Removes usage of IHeadlessWindow (which required users to use window.PlatformImpl), and replaces with public extensions.
5. Moves headless related projects to its own subfolder.
6. Now we have tests to make sure that headless platform works (+fixes couple of bugs).
7. Moves NoopStorageProvider to the Avalonia.Base, so there is always an StorageProvider instance instead of throwing an exception.

## What is the current behavior?

Developers need to copy-paste scary [xunit integration](https://github.com/kekekeks/Avalonia-unit-testing-with-headless-platform/blob/master/HeadlessTests/AvaloniaTestFramework.cs) between their projects.

## What is the updated/expected behavior with this PR?

It's easy to setup xunit-avalonia test project:
```csharp
[assembly: AvaloniaTestFramework(typeof(TestApplication))]

namespace Avalonia.Headless.UnitTests;

public class TestApplication : Application
{
    public TestApplication()
    {
        Styles.Add(new SimpleTheme());
    }

    public static AppBuilder BuildAvaloniaApp() => AppBuilder.Configure<TestApplication>()
        .UseSkia() /* Use skia instead of headless rendering, so we can render into window the bitmap */
        .UseHeadless(new AvaloniaHeadlessPlatformOptions
        {
            UseHeadlessDrawing = false
        });
}
```

## Checklist

- [x] Added unit tests (if possible)?
- [x] Added XML documentation to any related classes?
- [x] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Breaking changes

IHeadlessWindow is internal now, new extension methods added instead.

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0030670-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0031401-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0033655-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Review by grokys — APPROVED** [review]
LGTM, a big improvement in usability.

**Comment by amwx** [comment]
@maxkatz6 Is Avalonia.Headless.XUnit a separate package? I'm not seeing it in any of the nuget feeds and its not part of Avalonia.Headless.

**Comment by maxkatz6** [comment]
@amwx seems like my mistake, forgot to the packable list. And probably for better, as right now I am implementing support for NUnit, and it will require breaking changes in XUnit support (to keep it somewhat uniform).

Probably of approach in this PR, as it forces whole project to use UI synchronization context. And it also not possible in NUnit at all. So, we need per method attributes, similarly how https://github.com/AArnott/Xunit.StaFact/ does it.

**Pull request merged**
