### PR TITLE
Fix the scrollbar attaching to wrong scrollviewer, like scrollviewer …

### LINKED ISSUE #12482: DataGrid inside a ScrollViewer can not scroll normally.
**Describe the bug**
I have a DataGrid within a ScrollViewer. The ScrollViewer will be also scrolled when I try to scroll the DataGrid. I have tried the ScrollViewer.IsScrollChainingEnabled and set the event args's Handled as true, but no effect.

```xaml
    <ScrollViewer>
        <Border Height="1000"
                Margin="40"
                BorderBrush="Red"
                BorderThickness="1">
            <DataGrid Height="500" ScrollViewer.IsScrollChainingEnabled="False"
                      VerticalAlignment="Top"
                      ItemsSource="{dataGrid:Enum Key}">
                <DataGrid.Columns>
                    <DataGridTextColumn Binding="{Binding Path=.}" Header="Key" />
                </DataGrid.Columns>
            </DataGrid>
        </Border>
    </ScrollViewer>
```

**To Reproduce**

1. Put the mouse onto the DataGrid.
2. Scroll.
3. Then the DataGrid is scrolled and the ScrollViewer is also scrolled.

**Expected behavior**
The outer ScrollViwer should not be scrolled if the DataGrid can handle that event.

**Screenshots**
-

**Desktop (please complete the following information):**

- OS: win11
- Version 11.0.0-11.0.2.

**Additional context**

A sample for that here. [Avalonia.DataGrid.zip](https://github.com/AvaloniaUI/Avalonia/files/12290936/Avalonia.DataGrid.zip)

### PR DESCRIPTION
**Pull request by liwuqingxin**
…outer a datagrid.

## What does the pull request do?

Fix the bug that the scrollbar could attach to a wrong scrollviewer, like a scrollviewer outer a datagrid. #12482 

## What is the current behavior?

The scrollbar in control template of datagrid will find a nearest ancestor scrollviewer and attach to it. And there is no scrollviewer in control template of datagrid, the scrollbar in it's template will attach to the scrollviewer outer the datagrid, if it exsits. 

**Then, if we scroll the datagrid, the outer scrollviewer will be scrolled too.**

## What is the updated/expected behavior with this PR?

The scrollbar will not find the ancestor scrollviewer to attach to now. Instead it will try to attach to it's templatedparent if it is a scrollviewer.

I don't find any case that the scrollbar should bind to a scrollviewer that is not the scrollbar's tempatedparent. So if the case exists, stop this PR please.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Breaking changes

None.

## Fixed issues

Fixes #12482

### CODE REVIEW

**Comment by liwuqingxin** [comment]
@dotnet-policy-service agree

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0038980-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]
Can't imagine any scenario, when ScrollViewer is not a TemplatedParent for ScrollBar.
So, LGTM.

**Comment by liwuqingxin** [comment]
@maxkatz6 I don't know why the AvaloniaUI.IntegrationTests(Mac) failed with the error like:
> OpenQA.Selenium.WebDriverException : An unknown server-side error occurred while processing the command. Original error: 'POST /element' cannot be proxied to Mac2 Driver server because its process is not running (probably crashed). Check the Appium log for more details

Could you please tell me what should I do? 😅

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0038996-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Pull request merged**
