### PR TITLE
Added ability to use non well known property types in style selector

### PR DESCRIPTION
**Pull request by YohDeadfall**
This change allows to use a value of any type in a style selector expression if it's convertible to the target type. The target type is inferred from the actual value if the property type is `object`. Otherwise, the property type is used.

The feature fixes an issue when the expected property value is set in XAML and which is a string, so comparison with an actual value gives `false` and leads to writing a workaround in code.

The behavior is the same as in WPF inside bindings except that it doesn't catch errors.

### CODE REVIEW

**Comment by kekekeks** [comment]
I think we should parse enums and other values at compile type rather then attempting a runtime conversion. The property type is already known to compiler, so it can just reuse the existing parsing infrastructure.

**Comment by YohDeadfall** [comment]
Would it cover the case when some value is binded to the `Tag` property (or any other accepting `object`) and the property is used in a style selector?

**Comment by kekekeks** [comment]
It will not, but run-time parsing is a really bad idea performance-wise. 
We should probably extend the syntax to allow specifying the type in selector itself, e. g. `Button[Tag=(local:SomeEnum)Foo]`.

@grokys

**Comment by YohDeadfall** [comment]
A converted value may be cached which solves the perf problem and will cause an overhead only first time. Is it better?

**Comment by kekekeks** [comment]
Cache can solve the problem but e. g. `Tag` values can have have hundreds of different types across the app. The selector matcher will have to keep a dictionary for all of them. Trying to convert to all of those also involves a performance penalty: converter might do some expensive operations (e. g. if some Tag was holding an image, converter will attempt to load one using the string specified in selector) or throw format exceptions.

Also, keeping the value as a string will move errors from compile-time to the run-time, so invalid value will be simply ignored and selector not applied.

**Comment by YohDeadfall** [comment]
I meant a field stored in the same instance as the original value.

> Trying to convert to all of those also involves a performance penalty: converter might do some expensive operations (e. g. if some Tag was holding an image, converter will attempt to load one using the string specified in selector) or throw format exceptions.

In such cases I would say it's user's responsibility how to use the tool: to benefit from it using the feature reasonably or shoot their head with legs at once which can be easily done even without that change.

> Also, keeping the value as a string will move errors from compile-time to the run-time, so invalid value will be simply ignored and selector not applied.

Am all for compile time type checking and conversion if possible, but let's be honest. Not everything can be done by the compiler and for that cases there's an option to disable strongly typed binding generation. Therefore, the change can be used as a fallback.

**Comment by kekekeks** [comment]
>for that cases there's an option to disable strongly typed binding generation

Selectors are always parsed by compiler. What exactly is wrong with specifying the type explicitly? It's not needed for properties when type is already known.

**Comment by YohDeadfall** [comment]
If it's always the case, I see no reason to keep this PR. Just need the confirmation from @grokys since @MarchingCube had different opinion when we discussed this privately.

**Comment by MarchingCube** [comment]
Perhaps I misunderstood the problem, I think it would make sense to come up with a parsing type hint so we could handle this at compile time.

**Comment by grokys** [comment]
Would it not be a good idea to get this feature in with runtime parsing and then improve it to parse at compile time in a later PR?

**Comment by YohDeadfall** [comment]
If you think so, I will reopen the PR and finish it. Are you okay with changes?

**Comment by grokys** [comment]
I think so, yeah. Might be nice to have a few more unit tests for more types?

**Comment by kekekeks** [comment]
>Would it not be a good idea to get this feature in with runtime parsing and then improve it to parse at compile time in a later PR?

As long as the type is explicitly specified or derived from the property type. No ad-hoc conversion attempts.

**Comment by YohDeadfall** [comment]
@grokys, I added more tests. Could you take another look?

**Comment by YohDeadfall** [comment]
@kekekeks, the thing you proposed might be useful in case of command parameters to write values. Right now, it takes a few lines to specify a value if there's no standard one (i.e. stored in a static field or property).

**Comment by YohDeadfall** [comment]
@grokys, is there something else to address?

**Review by grokys — APPROVED** [review]

**Pull request merged**
