### PR TITLE
Fix SelectedItemsChanged event arguments in SelectingItemsControl

### PR DESCRIPTION
**Pull request by WojciechKrysiak**
- What does the pull request do?
Corrects the event arguments for replacing a selected item in SelectingItemsControl.
- What is the current behavior?
The arguments for the SelectedItemsChanged event are inverted.
- What is the updated/expected behavior with this PR?
Sets the arguments as expected.

Checklist:

- [x] Added unit tests

### CODE REVIEW

**Comment by jmacato** [comment]
Idk if this should be added to the breaking changes.

**Comment by WojciechKrysiak** [comment]
I haven't found any issues referencing this bug, so it's unlikely anyone quietly assumed this will remain broken forever. I'd say it's more likely no one used this feature until now.

**Comment by danwalmsley** [comment]
Wow thats a good spot! @jmacato should we get this into 0.7?

**Comment by jmacato** [comment]
@danwalmsley I do think this is a critical bug fix that needs to be included with the release
@WojciechKrysiak hmm better be safe and let's add it there

**Comment by WojciechKrysiak** [comment]
@jmacato done: https://github.com/AvaloniaUI/Avalonia/wiki/Breaking-Changes

**Review by jmacato — APPROVED** [review]
@WojciechKrysiak Thanks!

**Pull request merged**
