### PR TITLE
Allow ContextMenus to be shared

### LINKED ISSUE #497: Exception is thrown when ContextMenu was set in Style and is displayed for different item
**Reproducing the issue:**
1. Right click on `TreeViewItem1`
2. Right click on `TreeViewItem2` -> exception is thrown

**Code to reproduce the issue:**

``` XAML
<TreeView>
    <TreeView.Styles>
        <Style Selector="TreeViewItem">
            <Setter Property="ContextMenu">
                <Setter.Value>
                    <ContextMenu>
                        <MenuItem Header="MenuItem1"/>
                    </ContextMenu>
                </Setter.Value>
            </Setter>
        </Style>
    </TreeView.Styles>
    <TreeViewItem Header="TreeViewItem1"/>
    <TreeViewItem Header="TreeViewItem2"/>
</TreeView>
```

**Exception thrown:**

```
Exception thrown: 'System.InvalidOperationException' in Perspex.Controls.dll
Exception thrown: 'System.Reflection.TargetInvocationException' in mscorlib.dll
Core2D.Perspex.vshost.exe Error: 0 : Obiekt docelowy wywołania zgłosił wyjątek.
   w System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   w System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   w System.Delegate.DynamicInvokeImpl(Object[] args)
   w Perspex.Interactivity.Interactive.RaiseEventImpl(RoutedEventArgs e)
   w Perspex.Interactivity.Interactive.BubbleEvent(RoutedEventArgs e)
   w Perspex.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   w Perspex.Input.MouseDevice.MouseUp(IMouseDevice device, IInputRoot root, Point p, MouseButton button, InputModifiers inputModifiers)
   w Perspex.Input.MouseDevice.ProcessRawEvent(RawMouseEventArgs e)
   w System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   w System.Reactive.Linq.ObservableImpl.Where`1._.OnNext(TSource value)
   w System.Reactive.Linq.ObservableImpl.OfType`2._.OnNext(TSource value)
   w System.Reactive.Observer`1.OnNext(T value)
   w Perspex.Input.InputManager.ProcessInput(RawInputEventArgs e)
   w Perspex.Controls.TopLevel.HandleInput(RawInputEventArgs e)
   w Perspex.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   w Perspex.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   w Perspex.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   w Perspex.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   w Perspex.Application.Run(ICloseable closable)
   w Core2D.Perspex.App.Start() w C:\DOWNLOADS\GitHub-Core2D\Core2D\src\Core2D.Perspex\App.xaml.cs:wiersz 146
Core2D.Perspex.vshost.exe Error: 0 : The Control already has a parent.
   w Perspex.Controls.Control.Perspex.Controls.ISetLogicalParent.SetParent(ILogical parent)
   w Perspex.Controls.ContextMenu.Show(Control control)
   w Perspex.Controls.ContextMenu.ControlPointerReleased(Object sender, PointerReleasedEventArgs e)
```

### PR DESCRIPTION
**Pull request by grokys**
## What does the pull request do?

Fixes an issue that had its 4th birthday yesterday! Finally #497 is fixed :)

Allows `ContextMenu`s to be defined in `Resources` or a in `Setter` and shared between multiple controls.

## Checklist

- [x] Added unit tests (if possible)?

## Fixed issues

Fixes #497

### CODE REVIEW

**Comment by danwalmsley** [comment]
@grokys interesting points to note:

currently if you try to run the code from the original issue, the xaml compiler will complain (at runtime)

```
Unhandled exception. System.InvalidOperationException: Cannot use a control as a Setter value. Wrap the control in a <Template>.
```

If you wrap it in a Template, then it works. However obviously each item gets its own instance.

**Review by danwalmsley — APPROVED** [review]
Can merge following discussion of my observations.

**Comment by grokys** [comment]
@danwalmsley that's strange, this code is intended to allow `ContextMenu` is a style:

https://github.com/AvaloniaUI/Avalonia/pull/3751/files#diff-902c2eefb49d6cc928fce42801728dcfR174

And there's even a test to make sure it works:

https://github.com/AvaloniaUI/Avalonia/pull/3751/files#diff-d70fbee3dfcf082663beff7f0ca62430R225

**Comment by danwalmsley** [comment]
> @danwalmsley that's strange, this code is intended to allow `ContextMenu` in a style:
> 
> https://github.com/AvaloniaUI/Avalonia/pull/3751/files#diff-902c2eefb49d6cc928fce42801728dcfR174
> 
> And there's even a test to make sure it works:
> 
> https://github.com/AvaloniaUI/Avalonia/pull/3751/files#diff-d70fbee3dfcf082663beff7f0ca62430R225

Ok so it seems you get the issue if its in resource. If your putting it in styles, then you wont come across the bug on master, because you will be asked to wrap in a datatemplate.

**Pull request merged**
