### PR TITLE
WIP: Added Opening/Closed for NativeMenu on OSX.

### PR DESCRIPTION
**Pull request by grokys**
## What does the pull request do?

*Note: this is my first time working on OSX. I have no idea what I'm doing.*

image

Adds the `Opening` and `Closed` events for OSX to `NativeMenu` which relate to `menuWillOpen` and `menuDidClose`. Note that `NativeMenu` already exposed `NeedsUpdate` as `Opening`; this event has been moved to a separate `NeedsUpdate` event.

## Breaking changes

After this change native menus can no longer be modified in the `Opening` event. Code for that needs to be moved to `NeedsUpdate`. I think it was my misunderstanding of how OSX menus worked that caused us to map `NeedsUpdate` to `Opening` in the first place, sorry.

### CODE REVIEW

**Comment by robloo** [comment]
Being able to update menu items in an `Opening` event seems like it would be expected. Certainly that's what I would expect coming from a Windows background. `Opening` events generally allow any last minute updates including loading content or cancelling the open. Having a specialized 'NeedsUpdate' method for that seems strange. 

Since this is all for NativeMenu I should probably just keep my mouth closed though. As long as this isn't in some multi-platform abstraction there is no concern.

**Comment by kekekeks** [comment]
> As long as this isn't in some multi-platform abstraction there is no concern.

It is

**Comment by robloo** [comment]
> > As long as this isn't in some multi-platform abstraction there is no concern.
> 
> It is

Ah, ok. I misunderstood and though `NativeMenu` was just a managed wrapper directly over the OSX application menu. Might need to update docs [here](https://avaloniaui.net/docs/controls/nativemenu). I see now it's an abstraction that can also be used on Linux for example.

My point stands then that I would normally expect to be able to modify menus within the `Opening` event so the original functionally may have made more sense.

**Comment by grokys** [comment]
> My point stands then that I would normally expect to be able to modify menus within the Opening event so the original functionally may have made more sense.

That's as maybe, but OSX doesn't allow you to do so, so we're a bit limited in what we can do here.

Originally OSX's `NeedsUpdate` was mapped to `Opening` because `NeedsUpdate` is the only place on OSX where you can modify menus. As you say, this makes sense in a wider Avalonia context and what what caused me to ask @danwalmsley (who originally implemented this feature) to map `NeedsUpdate` to `Opening`.

The problem is that `NeedsUpdate` _isn't_ only called when the menu is opening: it's also called when a user presses a hotkey. What triggered the need for this PR is that one of our customers needs to know _when the menu is actually opening_.

So seems to me we're constrained to model the underlying OSX machinery here.

**Comment by robloo** [comment]
> The problem is that NeedsUpdate isn't only called when the menu is opening: it's also called when a user presses a hotkey. What triggered the need for this PR is that one of our customers needs to know when the menu is actually opening.
>
> So seems to me we're constrained to model the underlying OSX machinery here.

I see. Usually to get around such issues a state-management wrapper is required over the underlying events as well. Instead of just "converting" the native events to a direct equivalent in Avalonia some logic is applied and state is tracked. The events are never raised directly.

This would easily solve the problem of filtering hotkey presses after the menu in open; however, I haven't thought of a way to filter out unwanted NeedsUpdate events before the menu actually opens. Would take a bit of trial and error to see if this is even possible. Anyway, I'm not saying anything needs to change one way or another.

**Review by danwalmsley — APPROVED** [review]

**Comment by danwalmsley** [comment]
@grokys LGTM, yes, NeedsUpdate is where you can update the menu items.. Opening and Closed you shouldnt do that.

**Pull request merged**
