### PR TITLE
Use newer image in README.md

### PR DESCRIPTION
**Pull request by worldbeater**
### What does the pull request do?

Updates Avalonia image in `README.md` with a modification of our [OpenGraph]() image, shown in https://github.com/AvaloniaUI/Avalonia/issues/2914

### Update

Now this PR uses the following image, as requested.

### CODE REVIEW

**Review by grokys — APPROVED** [review]
Nice! :D

**Comment by KvanTTT** [comment]
The second picture a bit overloaded in my opinion.

**Comment by worldbeater** [comment]
@KvanTTT here is another option.



Which one would you prefer?

**Comment by Gillibald** [comment]
I prefer the second one

**Pull request merged**
