### PR TITLE
[Draft] Implemented IReadableBitmapImpl for Avalonia.Skia.SurfaceRenderTarget

### PR DESCRIPTION
**Pull request by llfab**
## What does the pull request do?
Adds IReadableBitmapImpl to Avalonia.Skia.SurfaceRenderTarget such that you can call RenderTargetBitmpa.CopyPixels() when using Skia

## What is the current behavior?
RenderTargetBitmpa.CopyPixels() currently asserts because Avalonia.Skia.SurfaceRenderTarget does not implement IReadableBitmapImpl

## What is the updated/expected behavior with this PR?
as above

## Checklist

- [ ] Added unit tests (if possible)?
- [x] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Breaking changes
Does not break current API

## Fixed issues
none

## Relates to
https://github.com/AvaloniaUI/Avalonia/discussions/10283

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0029803-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Review by kekekeks — APPROVED** [review]

**Comment by kekekeks** [comment]
sorry, was a brain fart, reverted

**Comment by kekekeks** [comment]
It won't work without a PixelFormat since CopyPixels will check if it's not null

**Comment by llfab** [comment]
That's correct. I did miss that too thinking if RenderTargetBitmap.Format == SurfaceRenderTarget.Format (both null) might do it. Any idea about that?

**Comment by llfab** [comment]
Wanted to do that as a Draft only for now anyways to be able to consume it by NuGet...

**Pull request merged**
