### PR TITLE
Allow DevTools to use dark mode

### PR DESCRIPTION
**Pull request by amwx**
## What does the pull request do?
Adds a property (`UseDarkMode`) to `DevToolsOptions` to allow DevTools to launch using Dark mode.

usage:
```C#
this.AttachDevTools(new DevToolsOptions
{
    UseDarkMode = true
});
```

result:
EDIT: Fixed layout visualizer to always use black foreground for better readibility
image

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019467-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019497-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by MarchingCube — APPROVED** [review]
Thanks, this will save many people from being blinded by light theme dev tools :)

**Comment by jmacato** [comment]
dark mode ftw

**Pull request merged**
