### PR TITLE
Fix #7567 - TreeView crashes the app when trying to display the same viewmodel twice

### LINKED ISSUE #7567: TreeView crashes the app when trying to display the same ViewModel twice
**Describe the bug**
When trying to draw one viewmodel in treeview twice, it crashes with an exception.

**To Reproduce**

1. Create a TreeView
2. Create a ViewModel
3. Create a collection property in the viewmodel with a list of elements
4. Add one item twice to the collection
5. Attach the collection from the ViewModel to the TreeView
6. Launch the application
7. When trying to draw a TreeView, the entire application
crashes with an exception

**Expected behavior**
TreeView displays 2 identical elements

**Desktop:**

- OS: Windows 11
- Version 0.10.12

### PR DESCRIPTION
**Pull request by Kibnet**
## What does the pull request do?
Changes the internal implementation of the TreeContainerIndex class so that it can store and process viewmodels more than once.

## What is the current behavior?
Now, when trying to add a ViewModel to TreeContainerIndex through the Add method, it crashes with an exception on line 48, since the key is already present in the dictionary.

## What is the updated/expected behavior with this PR?
The exception will stop being thrown out. TreeView will be able to draw and work with ViewModels added several times.

## How was the solution implemented (if it's not obvious)?
Another dictionary has been added that controls all copies of a single ViewModel

## Fixed issues
Fixes #7567

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=7568) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=7568) before we can accept your contribution.<br/><br/>:x: Kibnet [sign now](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=7568)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/AvaloniaUI/Avalonia?pullRequest=7568) it.</sub>

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018546-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018549-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018549-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018655-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018782-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018843-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by robloo** [comment]
The assumption that there is only one instance of something in the UI is a very deep principle in XAML-frameworks. You wouldn't expect to add the same button twice would you? Similarly, I don't think its fair to expect the same view model to be added twice? I've never seen this and I'm not sure what WPF would do.

I also think it's dangerous to assume all ViewModels will implement HashCode correctly. That is rarely done in my experience and only types that you know have a good hashcode implementation are used in cases like this.

**Comment by Kibnet** [comment]
> The assumption that there is only one instance of something in the UI is a very deep principle in XAML-frameworks. You wouldn't expect to add the same button twice would you? Similarly, I don't think its fair to expect the same view model to be added twice? I've never seen this and I'm not sure what WPF would do.
> 
> I also think it's dangerous to assume all ViewModels will implement HashCode correctly. That is rarely done in my experience and only types that you know have a good hashcode implementation are used in cases like this.

Oddly enough, but sometimes you need to display the same element twice, for example, when it is a nested element of two different nodes. I had such a task and I was surprised that it was impossible. And all because of an unobvious assumption that someone suggested. As a result, my edits allowed me to implement what I need.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019471-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by n-ski** [comment]
> I've never seen this and I'm not sure what WPF would do. 

WPF handles adding/removing a duplicate item to/from the hierarchy just fine, and although this case is indeed niche I assumed this would work the same in Avalonia, and it has caused me a bit of trouble when porting a WPF application to Avalonia.

**Comment by robloo** [comment]
> WPF handles adding/removing a duplicate item to/from the hierarchy just fine

If WPF handles this situation I certainly agree Avalonia should. We should check the implementation and see if there is anything that can be learned. Perhaps this is also how things are implemented in WPF though and this PR is just fine.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019515-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0020022-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
