### PR TITLE
Single win32 assembly

### PR DESCRIPTION
**Pull request by grokys**
Merge `Avalonia.Win32` assemblies. Previously we had two Avalonia.Win32 assemblies, one targeting `net461` and one targetting `netstandard2.0`. This merges both assemblies into a single `Avalonia.Win32` assembly targeting `netstandard2.0`.

- It uses `System.Drawing.Common` to implement the `System.Drawing` types
- It p/invokes to Win32 instead of using `System.Windows.Forms`
- It moves `WinFormsAvaloniaControlHost` to `Avalonia.Win32.Interop`

We should also in theory be able to merge `Avalonia.DotNetCoreRuntime` and `Avalonia.DotNetFrameworkRuntime` now, but when doing so D2D crashes when there's a bitmap in the application (which I assume is #1320).

The build scripts etc still need to be updated but I wanted to get some early input from @kekekeks and @jkoritzinsky to see if this is a valid approach.

### CODE REVIEW

**Comment by kekekeks** [comment]
You probably need to remove https://github.com/AvaloniaUI/Avalonia/blob/master/src/Windows/Avalonia.Win32.NetStandard/IconImpl.cs as well.

**Comment by kekekeks** [comment]
Regarding platform support libraries, I'd like to have them separated, since there might be platform differences that could cause issues in the future or ones that we aren't aware of yet. Merging them to one project and using `TargetFrameworks` property for producing two different binaries should be fine though.

**Comment by grokys** [comment]
> You probably need to remove https://github.com/AvaloniaUI/Avalonia/blob/master/src/Windows/Avalonia.Win32.NetStandard/IconImpl.cs as well.

Oh actually I can remove the whole `Avalonia.Win32.NetStandard` directory. Forgot to do that.

> Regarding platform support libraries, I'd like to have them separated, since there might be platform differences that could cause issues in the future or ones that we aren't aware of yet. Merging them to one project and using TargetFrameworks property for producing two different binaries should be fine though.

Ok, I think this'll be a separate PR anyway, as want to get this right first!

**Comment by jkoritzinsky** [comment]
@grokys You mention that when merging the runtime support libraries, that D2D crashes. Can you put together a repro of that and send it over? It'd be nice to have a repro that's smaller than AvalonStudio.

**Comment by grokys** [comment]
> @grokys You mention that when merging the runtime support libraries, that D2D crashes. Can you put together a repro of that and send it over? It'd be nice to have a repro that's smaller than AvalonStudio.

Hmm, that doesn't seem to be happening any more. If I manage to repro it again, I'll commit.

**Comment by grokys** [comment]
@kekekeks @jkoritzinsky i think this is ready for a proper review now.

**Review by kekekeks — COMMENTED** [review]
We can probably merge the contents of `WinFormsWin32Platform.cs` to `Win32Platform.cs`.

Other than that looks good

**Comment by grokys** [comment]
@kekekeks done!

**Review by kekekeks — APPROVED** [review]

**Pull request merged**
