### PR TITLE
fixes(OSX): convertBaseToScreen:' is deprecated: first deprecated in macOS 10.7

### PR DESCRIPTION
**Pull request by workgroupengineering**
## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

### CODE REVIEW

**Comment by workgroupengineering** [comment]
Can anyone test the artifacts of this PR?
I don't have a mac.

**Comment by grokys** [comment]
@danwalmsley what do you think?

I'm pretty wary of touching the OSX backend because just looking at it causes it to break. I'm not sure changes like this can be done lightly.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018396-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by jmacato** [comment]
Closing due to inactivity, please ping me if this is going to be worked on again.

**Comment by workgroupengineering** [comment]
@jmacato  I don't have an Apple device. if you have a chance to try it and give me the feedback, i will work on it

**Comment by jmacato** [comment]
@workgroupengineering okay i'll try to test it on my mac :)

**Comment by workgroupengineering** [comment]
> @workgroupengineering okay i'll try to test it on my mac :)

Thanks, I wait your feedback.

**Comment by workgroupengineering** [comment]
Hi @jmacato,
Have you taken the time to try PR?

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019456-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by workgroupengineering** [comment]
> You can test this PR using the following package version. `0.10.999-cibuild0019456-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

I tried this build on a friend's Mac Mini and it works as expected.

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019490-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
