### PR TITLE
Inertial scrolling fix

### PR DESCRIPTION
**Pull request by kekekeks**

### CODE REVIEW

**Comment by MarchingCube** [comment]
@danwalmsley Can you verify this? We have so many PRs hanging and this is literally a one liner.

**Comment by danwalmsley** [comment]
@MarchingCube @kekekeks why does this not target master?

**Comment by MarchingCube** [comment]
Good question, I didn't even realize that this targets 0.9.

**Comment by jmacato** [comment]
The change is already in master (https://github.com/AvaloniaUI/Avalonia/pull/3594/files)

**Pull request merged**
