### PR TITLE
Minimization bugfix on Windows

### PR DESCRIPTION
**Pull request by fr-Pursuit**
## What does the pull request do?
This PR fixes a bug regarding window minimization on Windows: the window currently stays activated when minimized programatically, where it should be deactivated.

## What is the current behavior?
When minimizing a Window on Windows using either a custom made button or the self-rendered window decorator, the window stays activated.

## What is the updated/expected behavior with this PR?
When minimizing a Window on Windows using either a custom made button or the self-rendered window decorator, the window is deactivated. Then, the OS will automatically activate the window below.

## How was the solution implemented (if it's not obvious)?
The issue was fixed by:
- Changing the value of the `activated` parameter given to the `ShowWindow` method when the Window is minimized
- Using the `Minimize` Win32 command regardless of the `activated` parameter (when using the `ShowMinNoActive` command, the Window still stays active; the only thing different is that the OS doesn't try to make *the window below* active)

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=7537) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=7537) before we can accept your contribution.<br/><br/>:x: fr-Pursuit [sign now](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=7537)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/AvaloniaUI/Avalonia?pullRequest=7537) it.</sub>

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018506-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by danwalmsley** [comment]
For information and in the interest of recording decision making:

Checked WPF sourcecode:
https://github.com/dotnet/wpf/blob/b63c69eaf5b58e758765a37bb18064bbc94832ad/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Window.cs#L5107-L5117

This suggest that this PR does introduce the correct behavior, that in the case of Minimize, ShowActivated flag is ignored.

**Review by danwalmsley — APPROVED** [review]

**Review by danwalmsley — APPROVED** [review]

**Comment by danwalmsley** [comment]
@fr-Pursuit thanks for the PR, Welcome to Avalonia community :)

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018518-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
