### PR TITLE
Proper support for double equality checks

### PR DESCRIPTION
**Pull request by ForNeVeR**
This PR supersedes #316 and adds some useful machinery to implement double equality checks in future.

### CODE REVIEW

**Comment by grokys** [comment]
Hi @ForNeVeR sorry for not getting to this earlier - it slipped my attention.

Could you explain the exact problem this solves? i.e. does a crash occur somewhere before this PR is applied? Is there incorrect behavior? A unit test demonstrating the error would be useful.

**Comment by ForNeVeR** [comment]
@grokys actually you _got_ here earlier, we discussed this problem in Gitter chat and I promised to create some samples (in form of the unit tests if applicable) to show the problems I'm solving here.

So sorry for me not doing it in a timely manner; I hope I'll get to that task at the weekend.

**Comment by grokys** [comment]
Any progress?

**Comment by ForNeVeR** [comment]
Finally I've found some time to add test for the `ProgressBar` control.

This `MathUtilities` stuff is complex a bit, so if you think that's an overengineering for such a simple task, then feel free to close this PR. I don't think that's a very important issue.

**Comment by grokys** [comment]
Thanks @ForNeVeR - so the problem is just that the `ProgressBar` might be a fraction of a pixel away from the end due to FP rounding errors? I'm not sure that's a huge problem is reality ;)

**Comment by ForNeVeR** [comment]
Honestly, I am not sure either. But that's not "a fraction of a pixel" - in case of this unit test it's a difference between 0% and 100%.

Look, it's intended that when `Maximum` = `Minimum` = `0`, then the progress bar should show be filled by 100%. Instead it could do anything due to floating point errors. In my case, I wanted to show the case when `Minumum` = 0, `Maximum` = 0 and `Value` = 0. It should be 100% then, but because `Maximum` is a bit off, it's showing `Value / (Maximum - Minimum)` = `Value / (2e-17 - 0)` = 0%.

**Comment by grokys** [comment]
Hmm, but should `Maximum = Minimum = 0` show 100%? Personally I'd expect it to show 0%, but I'd be willing to be persuaded if other frameworks show 100% in this case.

**Comment by ForNeVeR** [comment]
I don't know what it actually should show, but it does 100% currently as written in https://github.com/Perspex/Perspex/blob/a6b74db847506fd4f4d04aebe43d968b111a4acc/src/Perspex.Controls/ProgressBar.cs#L39

If it shouldn't behave this way, then we just need to remove this line and the whole story about floating point comparison in this code won't be relevant, because that comparison won't exist.

**Comment by grokys** [comment]
Ahhh, ok!  I wasn't even aware of that line! (I didn't write `ProgressBar`).

Ok, first lets see what other frameworks do for min = max = 0.

**Comment by grokys** [comment]
I do however agree that an equality comparison with epsilon is useful in general.

**Comment by grokys** [comment]
Closing this because we've gone through a rename and it will no longer apply. I may well end up taking the epsilon equality check method from it at some point though!

**Pull request closed without merging**
