### PR TITLE
Add Contract.RequireNotNull

### PR DESCRIPTION
**Pull request by danwalmsley**
Suggest to review Contract.cs first, everything else is just moving to new api.

Your first question will likely be, why not leave api as is, and use the doesnt return when false annotation. I tried this and it didnt work for me.

## What does the pull request do?
Before we enable nullable reference types on our projects, iv added this method which will be compatible with the NRT analysis.

## What is the current behavior?
Contract.Require(x!=null) confuses the analysis.

## What is the updated/expected behavior with this PR?
Because Contract.RequireNotNull has an annotation that roslyn recognises, we get rid of alot of warnings can can concentrate on addressing actual NRT issues.

### CODE REVIEW

**Comment by danwalmsley** [comment]
https://github.com/dotnet/csharplang/issues/2820

**Comment by grokys** [comment]
@MarchingCube I know we spoke about this in gitter, and we talked about using this pattern for null checks:

```
void M(ReferenceType foo)
{
    foo = foo ?? throw new ArgumentNullException(nameof(foo));
}
```

This has the advantage that the parameter name appears in the exception. We could of course add a parameter name to `Contract.RequireNotNull`.

I've looked through various MS dotnet projects and they all seem to use a mix of the `??` pattern above and explicit `if (foo == null)` checks.

Any preferences?

**Comment by kekekeks** [comment]
`throw` expression has only became available in C# 7. It's a recent addition to the language, so explicit null checks are probably just some old code written before C# 7.

**Comment by MarchingCube** [comment]
@grokys I think a mix of `throw` expressions and `if (x is null)` should be fine. `if (x == null)`  was causing slowdowns since it has to call virtual equals quite often and is simply too slow for high frequency code. Other option would be to extend our nullable reference type annotations and simply don't null check in internal code.

**Pull request closed without merging**
