### PR TITLE
Introduced RawPointerPoint for usage with IntermediatePoints

### PR DESCRIPTION
**Pull request by kekekeks**
Future-proofs https://github.com/AvaloniaUI/Avalonia/pull/7413 for pen input. Only backport together.

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018570-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by Takoooooo** [comment]
I am curious what is the purpose of having a separate struct for a single property? Why can't we just use Point everywhere?

**Comment by kekekeks** [comment]
That's what I've initially thought, but for pen input there would be pressure, radius, tilt and distance. For each individual point. We need to make the change now so we could extend that structure later without breaking compatibility.

**Comment by maxkatz6** [comment]
@kekekeks after checking iOS documentation, I wonder if it should be done in other way, so Avalonia won't request any additional points from the system unless application called GetIntermediatePoints. 
In Windows we need to call [GetPointer***InfoHistory](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getpointerpeninfohistory) and on iOS we need to call [coalescedTouches(touch)](https://developer.apple.com/documentation/uikit/uievent/1613808-coalescedtouches).
And at least for iOS documentation does not recommend calling this method because of overhead unless application really needs it. Not to mention, xamarin .NET wrapper over this API will probably allocate array to keep these touches (Windows documentation explicitly mentions special buffer of points, so it should be fine).

**Comment by kekekeks** [comment]
I guess we could change it to use `Func<IReadOnlyList<RawPointerPoint>>`.

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018610-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
