### PR TITLE
Fix TextLayout rendering with transform applied.

### PR DESCRIPTION
**Pull request by grokys**
## What does the pull request do?

Changes the type of transform used when rendering a `TextLayout` to a post-transform to a pre-transform. Using a post-transform caused the text to be rendered in the wrong place when an existing transform is applied to the `DrawingContext`. 

Render tests that failed before and passed after included.

Because Avalonia uses row-major matrixes the standard order of multiplications is pre-multiplication. Was there any particular reason you used post multiplication @Gillibald? Maybe the API doesn't make it clear...

## Checklist

- [x] Added unit tests (if possible)?

### CODE REVIEW

**Review by Gillibald — APPROVED** [review]
There was no particular reason to use `PushPostTransform`. Just some error on my side when I refactored that code.

LGTM

**Comment by Gillibald** [comment]
So only Mac is failing. I wonder what might go wrong.

**Comment by Gillibald** [comment]
I can't help here because I don't own a Mac. Can someone build this locally and provide the rendered images that corespond to the failing tests?

**Comment by maxkatz6** [comment]
@Gillibald 
I run it on mac, actual text is rendered bold.
Screen Shot 2021-07-27 at 3 50 20 PM

Content of the "TextLayout" test files folder
[Archive.zip](https://github.com/AvaloniaUI/Avalonia/files/6888326/Archive.zip)

**Comment by Gillibald** [comment]
No idea why strokes are thicker on OSX. We can clearly see that the correct font is loaded. So this might be related to how Skia rasterizes those glyphs on OSX. Maybe we could try a more recent version of SkiaSharp that somehow aligns the produced rendering.

**Comment by maxkatz6** [comment]
@Gillibald @grokys should we skip this test on macOS? It's not a bug introduced with this PR anyway.

**Comment by Gillibald** [comment]
Y we can just ignore it we will not be able to achieve exact results.

**Comment by grokys** [comment]
Won't backport this because the relevant line isn't present in 0.10.x.

**Pull request merged**
