### PR TITLE
move to a consistent langversion of 11

### PR DESCRIPTION
**Pull request by SimonCropp**
`<LangVersion>` was a combo of `preview`, `latest`, and `10`. given `11` is the current stable, move to that

### CODE REVIEW

**Comment by SimonCropp** [comment]
anything more needed on this one?

**Review by maxkatz6 — APPROVED** [review]

**Comment by maxkatz6** [comment]
@robloo it can be latest. Though we already had problems with breaking changes in the language itself because of targeting the latest one ("scoped" keyword related).

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0028296-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0028358-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Pull request merged**
