### PR TITLE
fix #4786 invalidatevisual when foreground changes in TextPresenter

### LINKED ISSUE #4786: TextBox doesn react on Foreground changes
When `TextBox` Foreground is changed it doesn't make effect until it's clicked or resized ... etc.

### PR DESCRIPTION
**Pull request by donandren**
## What is the current behavior?

TextBox doesn't react to Foreground changes until it's invalidated for some other reason

## What is the updated/expected behavior with this PR?

fix the problem and immediately TextBox is redrawn after Foreground is  changed
## Breaking changes

nope

### CODE REVIEW

**Review by Gillibald — APPROVED** [review]
LGTM

**Comment by MarchingCube** [comment]
What about `SelectionForegroundBrushProperty `, it seems we won't render again if this changes as well.

**Comment by Gillibald** [comment]
+ `CaretBrush`

**Review by MarchingCube — APPROVED** [review]
LGTM.

**Pull request merged**
