### PR TITLE
Fix datagrid ascending multi-column sort

### LINKED ISSUE #2801: DataGrid multiple column sorting not working
You can see this using the 0.8.0 Avalonia Control Gallery.
Sort by region and then population only ever sorts by population decreasing.
image

This second image should display population ascending (note the column sort arrow):
image

### PR DESCRIPTION
**Pull request by rfvgyhn**
## What does the pull request do?
Fixes datagrid mutlisort only sorting in descending order

## What is the current behavior?
Sorting a datagrid by more than one column results in the additional columns only sorting in a descending direction

## What is the updated/expected behavior with this PR?
Sorting a datagrid by more than one column results in the additional columns sorting in both directions

## Checklist

- [x] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

## Breaking changes
None

## Fixed issues
Fixes #2801

### CODE REVIEW

**Review by grokys — CHANGES_REQUESTED** [review]
Thanks for the fix @Rfvgyhn and above all thanks for kicking off getting some unit tests together. However I think you may have kicked the hornet's nest here ;)

Firstly, you need to add the new test assembly to our nuke script in order to get the tests to run in CI: https://github.com/AvaloniaUI/Avalonia/blob/5b1bd80f4b585c7e397f91439c4d3a3747403c19/nukebuild/Build.cs#L186-L203

However running the unit tests in VS I see some strange failures running on .NET framework (Core is OK).

in the VS test runner:

```
[xUnit.net 00:00:00.1358339] Avalonia.Controls.DataGrid.UnitTests: Catastrophic error during deserialization: System.ArgumentException: Could not load type 
Parameter name: serializedValue
   at Xunit.Sdk.SerializationHelper.Deserialize[T](String serializedValue) in C:\Dev\xunit\xunit\src\common\SerializationHelper.cs:line 35
   at Xunit.Sdk.TestFrameworkExecutor`1.Deserialize(String value) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\TestFrameworkExecutor.cs:line 66
   at Xunit.DefaultTestCaseBulkDeserializer.<BulkDeserialize>b__2_0(String serialization) in C:\Dev\xunit\xunit\src\xunit.runner.utility\Descriptor\DefaultTestCaseBulkDeserializer.cs:line 22
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Xunit.DefaultTestCaseBulkDeserializer.BulkDeserialize(List`1 serializations) in C:\Dev\xunit\xunit\src\xunit.runner.utility\Descriptor\DefaultTestCaseBulkDeserializer.cs:line 22
   at Xunit.Xunit2.BulkDeserialize(List`1 serializations) in C:\Dev\xunit\xunit\src\xunit.runner.utility\Frameworks\v2\Xunit2.cs:line 73
   at Xunit.Runner.VisualStudio.VsTestRunner.RunTestsInAssembly(IRunContext runContext, IFrameworkHandle frameworkHandle, LoggerHelper logger, TestPlatformContext testPlatformContext, IMessageSinkWithTypes reporterMessageHandler, AssemblyRunInfo runInfo) in C:\Dev\xunit\xunit\src\xunit.runner.visualstudio\VsTestRunner.cs:line 518
```

Under ncrunch:

```
System.InvalidCastException: Unable to cast object of type 'System.Linq.OrderedEnumerable`2[Avalonia.Controls.DataGrid.UnitTests.Collections.DataGridSortDescriptionTests+Item,System.String]' to type 'System.Linq.IOrderedEnumerable`1[System.Object]'.
   at Avalonia.Controls.DataGrid.UnitTests.Collections.DataGridSortDescriptionTests.ThenBy_Orders_Correctly_When_Descending() in D:\projects\AvaloniaUI\Avalonia\tests\Avalonia.Controls.DataGrid.UnitTests\Collections\DataGridSortDescriptionTests.cs:line 77
```

I'm really not sure what's happening here :/

**Comment by grokys** [comment]
Ah, I've worked out the problem: `IOrderedEnumerable<T>` isn't covariant in .NET Framework (but this was fixed for .NET core):

https://stackoverflow.com/a/47728953/6448

**Comment by Rfvgyhn** [comment]
Good catch. I've made some changes that should now allow the tests to work with the full framework.

I was also messing with some integrated git stuff in Rider and messed up the commit history. Let me know if a new branch/PR would be preferable.

**Review by grokys — APPROVED** [review]
Thanks @Rfvgyhn !

**Pull request merged**
