### PR TITLE
Fix Relative Source with {x:Type} bindings

### LINKED ISSUE #10486: CompiledBinding fails with RelativeSource
Might as well file the bug officially.

Using Avalonia `11.0.999-cibuild0030749-beta`.

With this in csproj

    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>

Let's create a compiled binding

    <Button Content="Action!" VerticalAlignment="Bottom" Width="120"
        Command="{Binding ViewModel.Action, RelativeSource={RelativeSource AncestorType={x:Type views:MainView}}}" />

It gives a compile error

>  MainView.axaml(25, 17): [AVLN:0004] AncestorType must be set for RelativeSourceMode.FindAncestor when searching the visual tree. Line 25, position 17.

Here's a repo project
[Avalonia11-RelativeSource.zip](https://github.com/AvaloniaUI/Avalonia/files/10833171/Avalonia11-RelativeSource.zip)

The work-around is to replace the binding with this, and it works

    "{Binding $parent[views:MainView].ViewModel.Action}"

### PR DESCRIPTION
**Pull request by maxkatz6**
## What is the current behavior?

This works:
```
<Button Content="Action!" VerticalAlignment="Bottom" Width="120"
    Command="{Binding ViewModel.Action, RelativeSource={RelativeSource AncestorType=views:MainView}}" />
```

## What is the updated/expected behavior with this PR?

This also works now:
```
<Button Content="Action!" VerticalAlignment="Bottom" Width="120"
    Command="{Binding ViewModel.Action, RelativeSource={RelativeSource AncestorType={x:Type views:MainView}}}" />
```

## Fixed issues

Fixes #10486

### CODE REVIEW

**Review by kekekeks — APPROVED** [review]

**Comment by danipen** [comment]
What is the diff between "this works" and "this also now works"?

**Comment by maxkatz6** [comment]
> What is the diff between "this works" and "this also now works"?

`{x:Type}` markup extension wasn't working in this context.

**Comment by danipen** [comment]
Ok now I see thanks 🙏

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0030842-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Pull request merged**
