### PR TITLE
X11 mate clipboard

### PR DESCRIPTION
**Pull request by viordash**
## What does the pull request do?

Fixes custom format data saving if CLIPBOARD_MANAGER is available.
Adds a wait for the data to be saved to CLIPBOARD_MANAGER to complete.

## What is the current behavior?

_Linux Mint 21.1 Mate 64.
Linux Ubuntu 18.04_
Unstable use of custom data formats, such as the file copy format, even if the save (SetDataObjectAsync) succeeds and the subsequent read (GetDataAsync) returns the values written, the ability to paste the file is still not available on X11.
Code example:
```
      var dataObject = new DataObject();

      const string data = "copy\nfile:///tmp/X11Clipboard.cs";
      dataObject.Set("x-special/mate-copied-files", data);

      await clipboard.ClearAsync();
      await clipboard.SetDataObjectAsync(dataObject);

      var paste = await clipboard.GetDataAsync("x-special/mate-copied-files");
      if (paste is byte[] xbytes)
      {
          Debug.WriteLine("x-special :" + System.Text.Encoding.UTF8.GetString(xbytes));
      }
```
The current implementation of X11Clipboard.SetDataObjectAsync with the existing CLIPBOARD_MANAGER only stores text atoms, `StoreAtomsInClipboardManager(_textAtoms)`. The required formats will be processed later, in OnEvent.
Also, saving with StoreAtomsInClipboardManager.CLIPBOARD_MANAGER does not wait for completion, which would sometimes confuse the X11 event stream because a new format/data request might arrive before the data was stored.

## What is the updated/expected behavior with this PR?

Stable saving of data in various formats.
Added a TaskCompletionSource to asynchronously wait for the completion of the store in the StoreAtomsInClipboardManager.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0037324-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0037334-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Review by jmacato — CHANGES_REQUESTED** [review]
Would it be possible to add unit tests for this?

**Comment by viordash** [comment]
> Would it be possible to add unit tests for this?

I'm ready to add the necessary unit tests for the x11 clipboard. But I couldn't find a test project with x11 support. Please indicate in which project I can add these tests

**Comment by maxkatz6** [comment]
Yeah, we don't have platform-specific tests for Linux @jmacato 
At some point it would make sense to add integration tests for linux.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0037376-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0037706-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Review by kekekeks — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0037720-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0037757-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Pull request merged**
