### PR TITLE
Introduce optional PushOpacity bounds

### LINKED ISSUE #11343: Opacity on element with CustomDrawOperation affect Clip or ClipToBounds
**Describe the bug**
I have a custom control that use CustomDrawOperation to blur an image.
ClipToBounds is false on element and its ancestors... 
The custom draw operation draw outside of the element bounds (what I want to do).
But when I set opacity to something different from 1, my element get clipped to its bounds (what I never asked for)

**Expected behavior**
Opacity on element with CustomDrawOperation should NOT clip to bounds, just change the opacity... 

**Screenshots**
Blur with Opacity=1
image

Same Blur with Opacity < 1 (the element is clipped, I don't want that).
image

**Desktop (please complete the following information):**

- OS: Windows 10
- Version 11 preview 8

**Additional context**

### PR DESCRIPTION
**Pull request by Gillibald**
## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Fixed issues

Fixes #11343

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0034799-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by dbriard** [comment]
Hi, I get back to the sample I provided in original issue https://github.com/AvaloniaUI/Avalonia/issues/11343#issuecomment-1546612520 and just noticed that Opacity is doing nothing when UseOpacitySaveLayer is false. 

I don't know if this is the desired behavior?

So if UseOpacitySaveLayer is true, the custom draw operation was clipped, I suppose that this is what has been fixed here?
But if UseOpacitySaveLayer is false, is it normal that Opacity on a Control that is drawing with CustomDrawOp do nothing?
I tried PushOpacity too and it also does nothing:
```
var state = context.PushOpacity(0.2, Bounds);
                context.Custom(new CustomDrawOp(Bounds, source, sourceRect, destRect, interpolationMode, Blur));
                state.Dispose();
```

Do I have to do opacity myself in CustomDrawOp? or is it a bug?

**Comment by Gillibald** [comment]
Without UseOpacitySaveLayer all brushes being used need to apply the current alpha. With UseOpacitySaveLayer a real layer is created that uses pushed opacity when the layer is blended into the current scene.

**Comment by dbriard** [comment]
> Without UseOpacitySaveLayer all brushes being used need to apply the current alpha. With UseOpacitySaveLayer a real layer is created that uses pushed opacity when the layer is blended into the current scene.

Thank you, is there a way to get "the current alpha"? or do I have to multiply element alpha with all its ancestor manually?

**Pull request closed without merging**
