### PR TITLE
SetForegroundBrush in skia uses the smallest Length first. fixes #658

### LINKED ISSUE #658: Fix Skia SetForegroundBrush implementation
Current implementation does not take into account that multiple brushes can be applied to the same text.

i.e.

"This is a test string"
Then setforeground brush can be applied, black over whole string.

Then setforeground brush can be applied red to "test" part of the string.

Current implementation would just produce black text.

### PR DESCRIPTION
**Pull request by donandren**

### CODE REVIEW

**Comment by danwalmsley** [comment]
just testing and reviewing now

**Comment by danwalmsley** [comment]
image
@donandren its not enought to apply just a single brush
all the brushes need to be applied in the order they were added

**Comment by danwalmsley** [comment]
This is with this PR, your implementation chooses a single brush for the entire line, it should apply all of them to get the text to render correctly.

**Comment by donandren** [comment]
@danwalmsley are you sure that's the skia.desktop from the PR build and what's the difference with the master?
now it should look different

**Comment by donandren** [comment]
@danwalmsley i've made some quick work so when we have multiple matches the order to be taken into account, this should probably work

**Comment by danwalmsley** [comment]
@donandren will give it a quick try

**Comment by danwalmsley** [comment]
if you cant get Avalon studio to build and open files you can go back to this commit, 

https://github.com/VitalElement/AvalonStudio/commit/1382a2500ff9a0538a5cc34888a0fdba64dbc9aa

**Comment by danwalmsley** [comment]
@donandren woohoo thanks this works now

image

**Comment by danwalmsley** [comment]
@donandren Is this mergable?

**Comment by donandren** [comment]
@danwalmsley it should be

**Pull request merged**
