### PR TITLE
Fix - TextPresenter ignores FontStretch property

### PR DESCRIPTION
**Pull request by VladimirDrobyshev**
## What does the pull request do?

The PRs fixes that TextPresenter ignores non default value of the FontStretch property

## What is the current behavior?

The FontStretch property of TextPresenter does not affects text drawing

## What is the updated/expected behavior with this PR?

The FontStretch property of TextPresenter affects text drawing

## Checklist

- [x] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/avalonia-docs with user documentation

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0039658-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by VladimirDrobyshev** [comment]
@microsoft-github-policy-service agree

**Comment by VladimirDrobyshev** [comment]
> @dotnet-policy-service agree

@dotnet-policy-service agree

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0039670-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Review by Gillibald — APPROVED** [review]

**Pull request merged**
