### PR TITLE
build on visual studio for mac fixed #1956

### LINKED ISSUE #1956: Visual Studio for mac fail to build ControlCatalog.NetCore
Visual Studio for mac fails to build ControlCatalog.NetCore Out of the box.

Look like Extension methods with ref parameter are not supported.

Errors:
 

-   Utilities/IdentifierParser.cs(11,63,11,66): error CS8339: The parameter modifier 'ref' cannot be used after the modifier 'this'

- Markup/Parsers/ArgumentListParser.cs(12,57,12,60): error CS8339: The parameter modifier 'ref' cannot be used after the modifier 'this'

### PR DESCRIPTION
**Pull request by donandren**
- What does the pull request do?
fixes Visual studio for mac build of ControlCatalog.NetCore project
- What is the current behavior?
Build errors
- What is the updated/expected behavior with this PR?
Fix build errors
- How was the solution implemented (if it's not obvious)?
refactored  usage of extension methods with ref parameter to use old fashion static method way

Fixes #1956

### CODE REVIEW

**Comment by danwalmsley** [comment]
It builds for me, did you update your installation?

**Comment by donandren** [comment]
Visual Studio for mac is the latest version. 
Note: Cake shell script builds fine the solution, but not the visual studio for mac

**Comment by danwalmsley** [comment]
I can confirm BETA channel version 7.7 (VS for Mac) that this is fixed.

So im guessing in the next VS for Mac release this will no longer be an issue.

**Comment by kekekeks** [comment]
This basically downgrades the used language version which is not a "build fix"

**Comment by grokys** [comment]
Yeah, if this is going to be fixed in the next VS for Mac, I'm tempted to give it a 👎 .

**Pull request closed without merging**
