### PR TITLE
use Silk.NET.Maths lib when target upper than .net 6.0

### PR DESCRIPTION
**Pull request by startewho**
## What does the pull request do?

When the Silk.Net.Math can use the simd tech,and i want to see by using the lib, can we make the performance a bit better?

i don't know how to test the performace at all .any one can give some help.

make the pr as draft ,so i can check the ci result

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/avalonia-docs with user documentation

### CODE REVIEW

**Comment by timunie** [comment]
> i don't know how to test the performace at all .any one can give some help.

maybe look into src/samples/Avalonia.Benchmarks

**Comment by maxkatz6** [comment]
We typically don't want adding any unnecessary dependencies to the core projects, as it will affect all users. Increasing app size, jit time, complexity with porting and licensing (though, not all of that applies to Silk.NET). 
If there is substantial performance benefit of their Vector2D implementation, we might better port their implementation to this repository instead of adding dependency.

**Comment by startewho** [comment]
> We typically don't want adding any unnecessary dependencies to the core projects, as it will affect all users. Increasing app size, jit time, complexity with porting and licensing (though, not all of that applies to Silk.NET). If there is substantial performance benefit of their Vector2D implementation, we might better port their implementation to this repository instead of adding dependency.

thanks, i  think i need some benchmark proof to show the performance  changes

**Comment by kekekeks** [comment]
Sorry, but we won't be adding a 800kb mandatory 3rd party dependency.

Consider using vector types from System.Numerics that are available in .NET 8.0.

**Comment by kekekeks** [comment]
Also, I don't really see how exactly using [this](https://github.com/dotnet/Silk.NET/blob/81cfc1008b1df8901a4d8c4e365cabda6797eaf2/src/Maths/Silk.NET.Maths/Scalar.BaseOps.cs#L1924-L2083) is faster than doing a simple `a*b`.

**Pull request closed without merging**
