### PR TITLE
Fix gesture recognizers

### PR DESCRIPTION
**Pull request by kekekeks**
1) Fixed inertial scroll
2) Notify all recognizers about PointerCaptureLost event

### CODE REVIEW

**Comment by grokys** [comment]
What broke this?

**Comment by kekekeks** [comment]
Since https://github.com/AvaloniaUI/Avalonia/pull/3161/files PointerCaptureLost is always triggered, even after PointerReleased event. ScrollGestureRecognizer wasn't expecting that.

Second one was broken by design in the initial implementation: gesture recognizers weren't notified pointer being captured elsewhere which would lead to resource leaks, see https://github.com/AvaloniaUI/Avalonia/issues/3133

**Comment by kekekeks** [comment]
Separate PR with just ScrollGestureRecognizer is targeting 0.9 branch - https://github.com/AvaloniaUI/Avalonia/pull/3595

The change in gesture recognizer API is technically breaking one, so it for `master` only.

**Comment by kekekeks** [comment]
Actually, it was broken even before 0.9.0 preview.

**Pull request merged**
