### PR TITLE
Add missing content alignment in fluent textbox theme

### LINKED ISSUE #4389: TextBox in fluent theme missing HorizontalContentAlignment and VerticalContentAlignment support
Default theme:
https://github.com/AvaloniaUI/Avalonia/blob/1f259cacd7a6659ced203f5f6cbd10060bc79700/src/Avalonia.Themes.Default/TextBox.xaml#L16-L17

Version: 0.10.0-preview2

### PR DESCRIPTION
**Pull request by jmacato**
Fixes #4389

### CODE REVIEW

**Comment by MarchingCube** [comment]
Not sure how how that works in UWP, but I think watermark also needs to follow this alignment.

**Comment by jmacato** [comment]
@MarchingCube not sure either, @maxkatz6 any ideas?

**Comment by maxkatz6** [comment]
@jmacato there is no content alignment support in the UWP TextBox. You can check it [in winui repo](https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/CommonStyles/TextBox_themeresources.xaml)
These props exists in Control base class tho.

Usually TextAlignment/HorizontalTextAlignment are used instead.

**Comment by danwalmsley** [comment]
@jmacato we should do what we did in our old theme then, and apply it to the watermark too. as watermark is supposed to be position exactly the same as the text.

**Comment by jmacato** [comment]
YOLO merging this since the changes are trivial...

**Pull request merged**
