### PR TITLE
Remove legacy designer

### PR DESCRIPTION
**Pull request by jkoritzinsky**
When we released Avalonia 0.6.0 we switched to our new remote designer architecture. We also updated our Visual Studio plugin to use the new remote designer via Avalonia.Ide. So, we have nothing using the old designer. Since it's been 3 months and we didn't make any back-compat guarantees, I'd say that everyone is using the up-to-date extension.

As far as I know, we have no plans to revive the old designer because of its limitations and brittleness. So, I propose we remove the old designer libraries.

### CODE REVIEW

**Comment by kekekeks** [comment]
I'd rather not remove the tests but alter them to use the new designer. Or at least keep the old ones for now since Win32 window embedding is still used by visual studio and the old test checks if that embedding is working

**Comment by kekekeks** [comment]
Other than that LGTM

**Comment by jkoritzinsky** [comment]
@kekekeks Can you take another quick look just to make sure that the test I added is testing what you want?

**Comment by kekekeks** [comment]
Thanks for the missing test for the new designer. It would be nice to check xplat mode as well (just remove `--method win32` and check if result message contains bitmap data).

**Review by kekekeks — APPROVED** [review]

**Pull request merged**
