### PR TITLE
Fixed #600: Incorrect TextBox selection coloring for non-left aligned…

### LINKED ISSUE #600: Incorrect TextBox selection coloring for non-left aligned text
Text disappears for a moment when I'am trying to select text inside TextBox from right to left:
[video](https://files.gitter.im/AvaloniaUI/Avalonia/WbpT/Invalid_TextBox_selection_for_not_left_aligned_text.mp4)

### PR DESCRIPTION
**Pull request by mikel785**

### CODE REVIEW

**Comment by grokys** [comment]
Thanks @mikel785!  Would you be able to add a render test that fails when the line you added is commented out and passes when it's there? If not, I can add one myself.

**Comment by mikel785** [comment]
Hello! I am not sure about how to implement an automated unit test. But can add animated gif  screenshots btw.

**Comment by grokys** [comment]
You can find the render tests [here](https://github.com/AvaloniaUI/Avalonia/tree/master/tests/Avalonia.RenderTests) but don't worry, i can add one ;)

**Comment by mikel785** [comment]
Ok =) Anyway here it is for direct2d:
Without fix:
orig
Fixed:
fixed

**Comment by grokys** [comment]
Thanks @mikel785, merged!

**Pull request merged**
