### PR TITLE
Don't add duplicate logical children to `ItemsControl` 

### LINKED ISSUE #10246: ListBox Items duplicate in logical tree.
I noticed that after migrating to preview5, ListBox no longer wraps items in container. Is this an expected behavior? 
Also every child element is attached to logical tree twice. 

image

### PR DESCRIPTION
**Pull request by grokys**
## What does the pull request do?

As described in #10246, `ItemsControl` was adding control items to the logical tree twice. This happens because control items need to be part of the logical tree before any layout pass occurs, but once the first layout pass occurs, the panel adds the containers to the logical tree, causing duplicates.

Fixed this by checking that the `LogicalChildren` doesn't already contain the control before adding it.

## Fixed issues

Fixes #10246

### CODE REVIEW

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0030000-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by fredg1** [comment]
That check fails when the addition is made asynchronously...

**Comment by maxkatz6** [comment]
@fredg1 it doesn't. UI controls are not thread safe by design. You need to synchronize your operations on UI thread using Dispatcher or proper synchronization context.

**Comment by fredg1** [comment]
Oh... (._. )

Well, thanks for the quick answer...

**Pull request merged**
