### PR TITLE
Fixes large text layout

### PR DESCRIPTION
**Pull request by Gillibald**
## What does the pull request do?
It changes the TextFormatterImpl to retain already shaped runs to improve the general performance of large text layouts.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

## Fixed issues
#4434

### CODE REVIEW

**Comment by Gillibald** [comment]
There is still room for improvement. Without this change, it took minutes to create the large text layout now its a matter of milliseconds

**Comment by jmacato** [comment]
@Gillibald is this ready? so excited :D

**Comment by Gillibald** [comment]
@Deadpikle Could you verify that build `9736` works for you?

**Comment by Deadpikle** [comment]
@Gillibald @jmacato Changes work great!

Before (9703):
avalonia-before

After (9736):

avalonia-after

**Review by jmacato — APPROVED** [review]
LGTM! @danwalmsley @grokys please include this in 0.10

**Pull request merged**
