### PR TITLE
Added Window.OnClosed and sealed HandleClosed.

### LINKED ISSUE #2965: Add Window.OnClosed
And seal `HandleClosed`

### PR DESCRIPTION
**Pull request by grokys**
## What does the pull request do?

`Window` had `OnClosing` and `OnOpened` virtual methods but no `OnClosed`. This PR adds that.

It also includes a change that I'd like feedback on: it seals `Window.HandleClosed` and `HandleResized`, because a user inheriting from `Window` shouldn't be messing with those (and `Window` is commonly used as a base class). This does leave open the question of whether we should seal those methods in `PopupRoot` too, and whether we should also seal `HandlePaint` and `HandleScalingChanged`? The `Handle*` methods are kind of internal APIs for communication with the platform impl.

## Fixed issues

Fixes #2965

### CODE REVIEW

**Comment by kekekeks** [comment]
I'd seal the entire `PopupRoot` class

**Review by kekekeks — APPROVED** [review]

**Comment by HendrikMennen** [comment]
Sealing popuproot will break AvaloniaEdit. https://github.com/AvaloniaUI/AvaloniaEdit/blob/master/src/AvaloniaEdit/CodeCompletion/CompletionWindowBase.cs

What should be used instead?

**Comment by danwalmsley** [comment]
Popup!

**Comment by HendrikMennen** [comment]
I am no expert but I thought there would be a reason for using Popuproot instead of Popup. I will try use that

**Comment by HendrikMennen** [comment]
@danwalmsley I tried using Popup instead and it seems to work. Opened pull request

**Comment by kekekeks** [comment]
@HendrikMennen 
The way you are using internal positioning API [here](https://github.com/AvaloniaUI/AvaloniaEdit/commit/75849d2bf61511b3ab98b41806b390df40f3d123#diff-f7b1ac033849967b12a03b1bcd87211aR375) won't work properly with screen edges.

I think we need a way to supply an extra parameter for a placement rectangle inside the placement target that would get applied here: https://github.com/AvaloniaUI/Avalonia/blob/1a6e21518c601b9634064574554594425e307934/src/Avalonia.Controls/Primitives/PopupPositioning/IPopupPositioner.cs#L324

That way it would be possible to provide all required information for the positioner.

**Pull request merged**
