### PR TITLE
Implementation of Label control (again)

### PR DESCRIPTION
**Pull request by HackerDelphi**
1. implemented Label control (again)
2. changed implementation of ControlPresenter to be same as WPF one. Added additional prebuild DataTemplate (for ContentPresenter)
3. added default style for Label control (both Default and Fluent themes)
4. Added sample to TextBox page (not sure needed other sample)
5. Added styles for Label in ControlCatalog/App.xaml

## What does the pull request do?
Implements Label control.
_this is a second iteration now based on right base branch_

## What is the current behavior?
Have Label control which allows targeting of Input elements by hotkeys

## What is the updated/expected behavior with this PR?
Label control

## How was the solution implemented (if it's not obvious)?
No WPF Label control analog was there before it

## Checklist

- [ ] Added unit tests (if possible)?
- [x ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

## Breaking changes
nope

## Fixed issues
nope

### CODE REVIEW

**Comment by robloo** [comment]
I have to ask this again :) Why add this control? It is a legacy name from the Windows Forms days and before. Now TextBlock is the control to use.

If there is no new functionality it seems like this is unjustified code duplication that will inevitably create a maintenance burden.

**Comment by robloo** [comment]
If this is really necessary for the scenario of porting WPF code it should derive from TextBlock and basically be no new functionality just a new name.

However even in WPF, label was there for compatibility with WinForms. It's bad to preserve compatiblity like this across two generations, deprecated ideas need to fall away.

**Comment by HackerDelphi** [comment]
> I have to ask this again :) Why add this control? It is a legacy name from the Windows Forms days and before. Now TextBlock is the control to use.
Nope. TextBlock have no "Target" property and cannot has hotkey.

> If there is no new functionality it seems like this is unjustified code duplication that will inevitably create a maintenance burden. Not to mention confusion between the controls for developers.
Because it has "Target" propery and allows to have "AccessChar" so, if text on Label is P__aste you will have ability to press "Alt + a" and control set as Target will be focused.

**Comment by robloo** [comment]
Interesting, I haven't used that special 'underscore in strings' since Windows Forms :) I also haven't needed it.

Two things:
 1. Shouldn't this still derive from a TextBlock? It would just then have special handling based on the Text string and add more properties for `Target` and `AccessChar`.
 2. Direct character key press handling like this has largely been removed in all XAML tech. Instead, concepts like KeyboardAccelerators are used which are much more powerful -- and more international input method friendly I would imagine.

I am concerned we are taking a step back going with this type of control. If someone wants to use it I can see how it would simplify a few things in LOB apps, it would help porting over old, existing code too. Still feels out of place in XAML though.

**Comment by maxkatz6** [comment]
Actually, it's interesting idea to resurrect Label.  It was used as element's header, that can be positioned as developer wants (above, below, from the left or right...). In UWP There is no Label control, but there are Header and Description properties in the TextBox, ToggleSwitch, DataPicker and others. And after we ported some of these controls from UWP to Avalonia 0.10, we also ported its Header properties, that are always hardcoded to be above of the control (develop can restyle it though).

And question is, do we need these properties, when we can have old Label? Of course it's a bit more verbose than <TextBox Header="Email" />, but it is always more flexible.

Although I also would prefer better keyboard accelerators support instead of AccessChar-like properties.

**Comment by HackerDelphi** [comment]
> Although I also would prefer better keyboard accelerators support instead of AccessChar-like properties.

Most reason to implement this contror is XAML level WPF compatability.
Company i working for have many WPF applications. 
Most of them will be awful in Web (like some of our leads want) and compatability of XAML will be very big reason to migrate to Avalonia instead of Angular (BRRRR).

**Comment by robloo** [comment]
> there are Header and Description properties in the TextBox, ToggleSwitch, DataPicker and others.

Good point, I always thought it wasn't desirable from a framework viewpoint to add these properties to individual controls. You're right it artificially constrains location of the header as well. Instead, the `HeaderedContentControl` (in the community toolkit) container was a cleaner design IMO. However, for some good reasons WinUI is trying to flatten the visual tree. Same reasons they added border props to Grid, etc.

Adding a [`HeaderedContentControl`](https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/headeredcontentcontrol) to Avlaonia that integrated the `Label` functionality with possible KeyboardAccelerators might be a good architecture to solve all needs here.

**Comment by HackerDelphi** [comment]
> Interesting, I haven't used that special 'underscore in strings' since Windows Forms :) I also haven't needed it.
> 
> Two things:
> 
> 1. Shouldn't this still derive from a TextBlock? It would just then have special handling based on the Text string and add more properties for `Target` and `AccessChar`.
No. Label can have complex context (and this may be changed by Templates, surprise!). Historically Label is content control, but with Target property.
> 2. Direct character key press handling like this has largely been removed in all XAML tech. Instead, concepts like KeyboardAccelerators are used which are much more powerful -- and more international input method friendly I would imagine.
Label doesn't use any direct input handling logic - it uses ContentPresenter with AccessText as Template instead.
> I am concerned we are taking a step back going with this type of control. If someone wants to use it I can see how it would simplify a few things in LOB apps, it would help porting over old, existing code too. Still feels out of place in XAML though.
This is not step back this is step forward in support of WPF XAML compatability.

**Comment by danwalmsley** [comment]
@grokys @MarchingCube @kekekeks im convinced :)

**Comment by HackerDelphi** [comment]
> > there are Header and Description properties in the TextBox, ToggleSwitch, DataPicker and others.
This is overimplementing IMHO. better to have these properties to be attached or user HeaderedContentControl descedants if needed. 
For reasons of Grid layout with Labels at left and InputElements at right the best solution with customization possibility is Label with Target set in left column and InputElement in right column. This solution allows to add f.e. additional Grid column between labels and Inputs and place GridSplitter there. 
> Adding a [`HeaderedContentControl`](https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/headeredcontentcontrol) to Avlaonia that integrated the `Label` functionality with possible KeyboardAccelerators might be a good architecture to solve all needs here.
HeaedredContentControl is part of WPF [`HeaderedContentControl`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.headeredcontentcontrol?view=netframework-4.6)

BTW GroupBox template in WPF (surprise!)  contains ContentPresenter with RecognizeAccessText property set (like in Label sic!) for Header display. 
In Avalonia there is no needed property "ContentSource" in ContentPresenter (and its implementation is not clear in WPF. I spent some time for inverstigations but was unable find where is it used) for same template, but Label actually is wrapper for ContentPresenter with needed properties set, so it can be used for future GroupBox Header template implementation.

**Comment by robloo** [comment]
> This is not step back this is step forward in support of WPF XAML compatability.

Well my point was in WPF it was only added for compatibility with WinForms. We shouldn't carry compatibility mechanisms across two generations. Old things need to be deprecated.

However, I definitely see the opportunity to solve a few things with a Label-type control. However, I wouldnt call it a label:

 1. Be a container like HeaderedContentControl to wrap an existing control with some header text.
 2. Allow the header to be placed top, bottom, left, right
 3. Using this control would allow removing header properties from Textbook, etc. Carried over from WinUI.
 4. The HeaderedContentControl could have a Keyboard Accelerator property that would focus the child control.
 5. I would get rid of the older string with underscores text. It needs to be replaced with something modern.

**Review by jmacato — APPROVED** [review]
Eh it wouldnt hurt to improve WPF compat more so I'm approving this :) Thanks for the effort @HackerDelphi ! :D

**Comment by robloo** [comment]
Improving WPF compatibility is a good thing and I can't argue with that logic :) There are definitely other areas that introduce much, much more of a compatibility problem though so I know compatibility is not a driver of decision making. Innovation and change for the better are important too.

It would still be good to investigate a more general, modern control to handle headers of content.

**Comment by HackerDelphi** [comment]
> > This is not step back this is step forward in support of WPF XAML compatability.
> 
> Well my point was in WPF it was only added for compatibility with WinForms. We shouldn't carry compatibility mechanisms across two generations. 
This is wrong. Label is mechanism allowing have activation control different than InputElement itself. Label still exist in most UI frameworks (even in HTML).
> Old things need to be deprecated.
Label is not old thing. Label is one of main controls in existing WPF applications. And it is still needed for developers. 
Not everyone loooks for "modern" <===> "not modern" differences. Many users are needed to still have Labels for keyboard only input and developers are needed to have VERY simple way to migrate existing Applications without unneeded changes (like make Header to input instead of Label and set Keyboard Accelerator instead of still use of Label.Content with underscore included.

U can see how labels are resized at left pane on this screenshot

And here size changed back. Underscores became when Alt was pressed. Pressing of Alt+F, Alt+L and Alt+B are setting focus to apropriative control.
(demo page is added to branch)
> 1. Be a container like HeaderedContentControl to wrap an existing control with some header text.
> 2. Allow the header to be placed top, bottom, left, right
> 3. Using this control would allow removing header properties from Textbook, etc. Carried over from WinUI.
> 4. The HeaderedContentControl could have a Keyboard Accelerator property that would focus the child control.
> 5. I would get rid of the older string with underscores text. It needs to be replaced with something modern.

This is not good idea IMHO. Label is label and HeaderedContentControl is HeaderedContentControl (f.e. TabItem, Expander, GroupBox). TextBlock is TextBlock (it is lightweight beacasue supports only text rendering).

**Comment by robloo** [comment]
@HackerDelphi Fair enough

**Comment by maxkatz6** [comment]
@HackerDelphi 
Thanks!

**Pull request merged**
