### PR TITLE
fix: Preview not showed when using using statment #12974

### LINKED ISSUE #12974: Preview not showed when using `using` statment
**Describe the bug**

When you reference a class in xaml with the `internal` access modifier and use the `using` statement in xmlns, the previewer shows nothing and the Avalonia Diagnostic output window reports an error like this:

```bash
System.Xaml.XamlException: 'Unable to resolve type MainViewModel from namespace using:Sandbox.ViewModels Line 34, position 6.' Line number '34' and line position '6'.
```

**To Reproduce**

1. Go to SandBox Project
2. Add class with `internal` access modifier  eg: `internal class MainViewModel`
3. Open `MainWindow.axaml`
4. Add  xmlns thah refer at namespace of added class eg `xmlns:l="using:SandBox.ViewModels"`
5. Add reference in xaml eg:
    ```xaml
       <Window.DataContext>
         <l:MainViewModel/>
       </Window.DataContext>
    ```
7. See error

**Expected behavior**
the previewer shows 

**Screenshots**

immagine

**Workaround**

replace `using` with clr-namespace or make public the class.

**Desktop (please complete the following information):**

- OS: any
- Version cde91774ac9db803041642212eeb2626919c449d

**Additional context**

### PR DESCRIPTION
**Pull request by workgroupengineering**
## What does the pull request do?

Update `XamlC`

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/avalonia-docs with user documentation

## Fixed issues

Fixes #12974

### CODE REVIEW

**Review by maxkatz6 — APPROVED** [review]

**Comment by maxkatz6** [comment]
XamlX backports are very problematic, which is why we normally don't do them.

**Comment by workgroupengineering** [comment]
Thank for reply. I understand.

**Comment by maxkatz6** [comment]
Backported https://github.com/AvaloniaUI/Avalonia/commit/3ef837580eff567eed0988f0d19387ba262f67f2

**Comment by workgroupengineering** [comment]
Thank

**Pull request merged**
