### PR TITLE
WIP: Virtualization improvements

### LINKED ISSUE #10367: ListBox with variable height items using Expander and virtualization shows items on top of each other
**Describe the bug**
A ListBox with variable height ItemTemplate by using an Expander shows items on top of each other while scrolling them into view.
(also some scroll 'skipping' while scrolling them out of view? see video)

(ps. after multiple scroll passes, there seem to appear 'ghost' items in view)

this is using `11.0.999-cibuild0030035-beta`.

**To Reproduce**
[ListBox_VariableHeightItems.zip](https://github.com/AvaloniaUI/Avalonia/files/10757213/ListBox_VariableHeightItems.zip)

ListBox looks like:
```xaml
    <ListBox Items="{Binding Items}">
        <ListBox.ItemTemplate>
            <DataTemplate DataType="vm:Item">
                <Expander HorizontalAlignment="Stretch" IsExpanded="{Binding IsExpanded, Mode=TwoWay}">
                    <Expander.Header>
                        <TextBlock Text="{Binding Index}" />
                    </Expander.Header>
                    <Panel Height="250" Background="Black" />
                    <!--  instead of panel I'd like to do an inner ListBox for a simple master-detail pattern  -->
                </Expander>
            </DataTemplate>
        </ListBox.ItemTemplate>
    </ListBox>
```

**Expected behavior**
Items adjacent to each other.

**Screenshots**

https://user-images.githubusercontent.com/27849065/219400418-5ba2c2ed-a295-42dc-8923-55304016cd8a.mp4

### PR DESCRIPTION
**Pull request by grokys**
## What does the pull request do?

Working on improving virtualization with variable-sized items:

- Housekeeping: [move the realized element list out of `VirtualizingStackPanel`](https://github.com/AvaloniaUI/Avalonia/pull/10869/commits/a08f4ac97726d51b3ba638f003b49c56099581ee) as it was getting big
- [Estimate positions based on realized elements.](https://github.com/AvaloniaUI/Avalonia/pull/10869/commits/a4a68006579991debab4ac9cdb01fe969b0bc8a3): when estimating the first and last item, we can make use of the currently realized elements to estimate them more accurately. Helps prevent jumpy scrolling
- Similarly [calculate desired size from last realized element.](https://github.com/AvaloniaUI/Avalonia/pull/10869/commits/f5aabcf6955d5cc97695227549716eb4dd8a84ba)
- [Register anchor candidate in `VirtualizingStackPanel`](https://github.com/AvaloniaUI/Avalonia/pull/10869/commits/e9a851d6d2f6906f908a995f236ee4393a0ddfb1): We need to register controls as anchor candidates in the panel instead of in `ItemsControl` because the candidate needs to be registered after arrange. See commit message for more details
- [Make thumb drag delta relative to parent](https://github.com/AvaloniaUI/Avalonia/pull/10869/commits/f2110a05c6074de13ada57591163c7cedc1a4213) instead of thumb itself: prevents the viewport jumping around when scrolling a virtualized list with differing sizes. Instead the thumb jumps around which is much better
- [Started writing VirtualizationDemo.](https://github.com/AvaloniaUI/Avalonia/pull/10869/commits/0dd87bd2d738c1b1539ee3daf4d56de119fc81bd) to give some more realistic examples of lists to test virtualization on. Started with a chatgpt-generated chat.

## Fixed issues

Fixes #10367

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0032680-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0032684-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0032690-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by grokys** [comment]
Closing this in favor of a slightly different approach.

**Pull request closed without merging**
