### PR TITLE
fix: Avalonia on Windows - Intermittent "Arithmetic operation resulted in an overflow".

### PR DESCRIPTION
**Pull request by Lakritzator**
## What does the pull request do?
It fixes intermittent Avalonia crashes on windows, as it was taking a Int32 from a larger IntPtr, which causes System.OverflowException

## What is the current behavior?
While running a Windows application using Avalonia one can (depends on something) get the following error:

```
System.OverflowException
  HResult=0x80131516
  Message=Arithmetic operation resulted in an overflow.
  Source=mscorlib
  StackTrace:
   at System.IntPtr.op_Explicit(Int64 value)
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs:line 648
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.WndProc.cs:line 30
```
The callstack shows the WinProc, handling of the windows messages, and the IntPtr.

Specifically it's about WindowsMessage.WM_INPUTLANGCHANGE here.
The lparam (long param) is taken, which is an IntPtr, the details for what it exactly has can be found [here](https://learn.microsoft.com/en-us/windows/win32/winmsg/wm-inputlangchange), there it specifies: "The low word contains a [Language Identifier](https://learn.microsoft.com/en-us/windows/win32/intl/language-identifiers) for the input language. The high word contains a device handle."

Avalonia wants the low word, so the method UnmanagedMethod.LGID(IntPtr) is called and in there the IntPtr.ToInt32() method.
Unfortunately sometimes the device handle value causes issues as the total "value" is bigger than fits in an int (Int32) so an exception is thrown. It doesn't happen often, so intermittent exceptions.

## What is the updated/expected behavior with this PR?
No cashes in this part.

## How was the solution implemented (if it's not obvious)?
Instead of getting an Int32 (int) causing OverflowException, now a long is retrieved and from this the lower 16 bits are taken.

## Checklist

- [ ] Added unit tests (if possible)?
A unit test for Avalonia doesn't make much sense, but one can make one around the IntPtr to prove the issue, see down below.
- [ ] Added XML documentation to any related classes?
Not needed, will not add value.
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation
Not needed, will not add value.

The error example, this causes an exception:

```
        uint deviceHandle = 0xf765;
        uint languageIdInput = 0xabcd;

        uint longParam = deviceHandle << 16 | languageIdInput;

        var lParam = new IntPtr(longParam);
        long intValue = lParam.ToInt32();

        var languageIdOutput = (uint)(intValue & 0xffff);
        Assert.Equal(languageIdInput, languageIdOutput);
```

The solution example, no exception:

```
        uint deviceHandle = 0xf765;
        uint languageIdInput = 0xabcd;

        uint longParam = deviceHandle << 16 | languageIdInput;

        var lParam = new IntPtr(longParam);
        long longValue = lParam.ToInt64();

        var languageIdOutput = (uint)(longValue & 0xffff);
        Assert.Equal(languageIdInput, languageIdOutput);
```

## Breaking changes
Nothing

## Obsoletions / Deprecations
Nothing

## Fixed issues
I didn't find any reported issues that look like the issue I had.

P.S.
Some additional hints, I found some other places where a IntPtr is squeezed into a uint, and the same exception might be occur.

One example is the TrayIconImpl.WndProc where the lParam.ToInt32 is called, I couldn't simply deduct if this would be an issue as it's a custom message. Another example is in UnmanagedMethods.GetWindowLongPtr, where the return value should be an IntPtr (See [p-invoke example](https://www.pinvoke.net/default.aspx/user32/GetWindowLongPtr.html)). Also look at the [SetWindowLongPtr documentation](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowlongptra) and the implementation. As this might only cause issues in use-cases where Avalonia isn't involved, and some code refactoring will be needed, I didn't look into details (yet).

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0024847-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by Lakritzator** [comment]
I tested the feed, and there is still something odd, so do not merge.
I got another exception, which doesn't make much sense, I need to check this out. 

```
System.OverflowException
  HResult=0x80131516
  Message=Arithmetic operation resulted in an overflow.
  Source=mscorlib
  StackTrace:
   at System.IntPtr.op_Explicit(Int64 value)
```

**Review by kekekeks — APPROVED** [review]

**Comment by Lakritzator** [comment]
It seems the value was much bigger, and it doesn't even fit in a Int64. This called for different measures.
More or less this describes the issue:

```
 long longValue = 0x7fff_ffff_ffff_1234;
 var HKL= new IntPtr(longValue);
 // Doing something with HKL here, like ToInt64, or even casting it to a ulong, will fail.
```

So to fix this, we need to have the conversion in our code (not in that of IntPtr) and disable checking:

```
 long longValue = 0x7fff_ffff_ffff_1234;
 var HKL= new IntPtr(longValue);
 // Doing something with HKL here, like ToInt64, or even casting it to a ulong, will fail.
 unchecked {
     return (uint)((ulong)HKL & 0xffff);
 }
```

It's even important to do it in two steps... this will now fix the issue, I'm awaiting the updated build so I can test this.

**Comment by Lakritzator** [comment]
I'd love to test this, but it seems that the change for #9241 doesn't work for me, I even tried adding  <PackageReference Include="MicroCom.Runtime" Version="0.10.5" />

I keep getting:

```
System.IO.FileLoadException
  HResult=0x80131044
  Message=Could not load file or assembly 'MicroCom.Runtime, Version=0.10.5.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
  Source=Avalonia.Win32
  StackTrace:
   at .cctor()
```

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0025165-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by maxkatz6** [comment]
@Lakritzator might be some nuget/cache issue. I build it from the command line with no issue.

**Comment by Lakritzator** [comment]
@maxkatz6 The error comes in the project where I use Avalonia, and only during runtime. I'm not even sure why a nuget cache has to do with it.

I actually get the following exception when I run my app standalone (outside of Visual Studio):

Unhandled Exception: System.TypeInitializationException: The type initializer for '<Module>' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'MicroCom.Runtime, Version=0.10.5.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
   at .cctor()
   --- End of inner exception stack trace ---
   at Avalonia.AppBuilderDesktopExtensions.LoadWin32[TAppBuilder](TAppBuilder builder)
   at Avalonia.AppBuilderDesktopExtensions.UsePlatformDetect[TAppBuilder](TAppBuilder builder) in /_/src/Avalonia.Desktop/AppBuilderDesktopExtensions.cs:line 22

**Comment by maxkatz6** [comment]
@Lakritzator it seems your project requires strong named dependencies, and MicroCOM.Runtime is not, CC @kekekeks 
Let's merge this PR so you can check on your project from nuget build.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0025224-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by Lakritzator** [comment]
@maxkatz6 That is the weird thing about the exception, my project itself does NOT require strong named dependencies.
image

But as you already merged, where is the version which should solve this?

I tried 11.0.999-cibuild0025224-beta and the latest at this time 11.0.999-cibuild0025230-beta, both give me:
System.IO.FileLoadException
  HResult=0x80131044
  Message=Could not load file or assembly 'MicroCom.Runtime, Version=0.10.5.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
  Source=Avalonia.Win32
  StackTrace:
   at .cctor()

I'm very confused about the error...

Here is my startup class:

```
class Program
{
    // Initialization code. Don't use any Avalonia, third-party APIs or any
    // SynchronizationContext-reliant code before AppMain is called: things aren't initialized
    // yet and stuff might break.
    public static void Main(string[] args)
    {
        BuildAvaloniaApp().StartWithClassicDesktopLifetime(args);
    }

    // Avalonia configuration, don't remove; also used by visual designer.
    public static AppBuilder BuildAvaloniaApp()
        => AppBuilder.Configure<App>()
            .UseReactiveUI()
            .UsePlatformDetect()
#if DEBUG
            .LogToTrace(LogEventLevel.Debug);
#else
            .LogToTrace();
#endif
}
```

**Comment by maxkatz6** [comment]
@Lakritzator this issue was fixed with that PR https://github.com/AvaloniaUI/Avalonia/pull/9324

**Pull request merged**
