### PR TITLE
Made TabControl observe changes which affect SelectedContent/Template, plus various analyzer warning fixes

### PR DESCRIPTION
**Pull request by TomEdwardsEnscape**
While fixing analyzer warnings, I noticed that `TabControl` and `TabItems` only synchronise content and content templates when the selected item changes. I switched them to bindings/observables, so that changes are applied immediately, e.g. in response to a style trigger.

I also noticed that `TabControl.ContentTemplate` was either not used at all (for a user-provided `TabItem`) or always used (for a generated `TabItem`). WPF evaluates both every time, [and `TabItem.ContentTemplate` wins if not null](https://referencesource.microsoft.com/#PresentationFramework/src/Framework/System/Windows/Controls/TabControl.cs,582). This PR introduces the same precedence rules.

The PR also contains the set of fixes for / suppressions of analyzer warnings that I originally set out to make, plus an update to `Avalonia.Desktop.slnf` which corrects the paths to some projects.

## TabControl specifics

`TabItem.TabStripPlacement` is now a `DirectProperty`. I applied the same pattern that I used in `ScrollBar` to subscribe to `TabControl.TabStripPlacement` and forward the value. The value also is now nullable, so won't incorrectly return `Dock.Left` when there isn't a `TabControl` around.

`TabControl.SelectedContent` and `TabControl.SelectedContentTemplate` are now direct and read-only. These previously had analyzer suppression attributes saying that they were "supposed to be a styled readonly property", but this doesn't make sense, as they are set with local priority by `TabControl` and thus can never be styled.

Additionally, both of those properties are now set by observable subscribers. This means that changes to `TabControl.ContentTemplate`, `TabItem.ContentTemplate`, and `TabItem.Content` are now reflected immediately, instead of when the selected tab next changes.

### TabControl.UpdateHeader

I didn't change this method despite the warnings it is emitting. It's a weird feature and I don't know what to do with it. Is it really desirable to *sometimes* automatically set the header when the content changes?

I think we should delete this code, and let users create their own attached behaviour if they actually want the functionality.

## Breaking changes

* Some properties have switched from styled to direct.
* `TabControl.ContentTemplate` is now used if `TabItem.ContentTemplate` is null. This matches WPF.

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0034716-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by Gillibald** [comment]
https://github.com/AvaloniaUI/Avalonia/blob/91ff652c12afbf99ebff782f6600acb373f5ad7f/src/Avalonia.Controls/TabItem.cs#L85 this method doesn't look symmetrical. In case Header is null there is a check for IHeader for non null Header there isn't.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0034914-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by grokys** [comment]
@Gillibald ping.

**Review by Gillibald — APPROVED** [review]

**Pull request merged**
