### PR TITLE
refactor DiscardDayTime method

### PR DESCRIPTION
**Pull request by davidgordon12**
## What does the pull request do?

Refactors the DiscardDayTime method to be one line instead of 4

## What is the updated/expected behavior with this PR?

Same behavior is expected.

## Checklist

- [x] Added unit tests (if possible)?
- [x] Added XML documentation to any related classes?
- [x] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019888-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by MarchingCube** [comment]
It seems that `CalendarDatePicker` has a copy of this function (with old implementation). Can you unify this as well?

**Comment by robloo** [comment]
@MarchingCube 

> It seems that CalendarDatePicker has a copy of this function (with old implementation). Can you unify this as well (probably just use this public function and remove private one)?

That is being removed in PR #7958 . It is an unused method. So I dont think it needs to be updated here.

**Review by MarchingCube — APPROVED** [review]
LGTM.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019920-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
