### PR TITLE
Features Dispatcher.Post<T>(Action<T>, T arg, DispatcherPriority priority = DispatcherPriority.Normal)

### LINKED ISSUE #6510: [Core] Add overload to Dispatcher.Post thath accept Action<T>
**Is your feature request related to a problem? Please describe.**
Avoid generate clousure in case like this:

https://github.com/AvaloniaUI/Avalonia/blob/68370e37a5d5340613369e49f8aa9f9e5b7f31d1/src/Avalonia.Controls.DataGrid/DataGrid.cs#L4495-L4498

If this feature will be accepted we can simplify previous code like this:

```csharp
   Dispatcher.UIThread.Post(PreparingCellForEditPrivate, (Control)element);
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by workgroupengineering**
## Checklist

- [ ] Added unit tests (if possible)?
- [x] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Fixed issues

Fixes #6510

### CODE REVIEW

**Comment by kekekeks** [comment]
1) what is "tipizzed"
2) @grokys are we ok with a breaking change in IDispatcher? That type is not likely to be implemented by the user code.

**Comment by grokys** [comment]
> are we ok with a breaking change in IDispatcher? That type is not likely to be implemented by the user code.

Yeah I don't think that would be a problem.

However, I'm not sure about this:

- Are the amount of closures being created causing a problem in your application? I'd be interested to see some profiler output which flags this as a problem.
- Is a single parameter so special? What if I want to pass two parameters?

Has anyone else has run into this problem?

**Comment by maxkatz6** [comment]
> Is a single parameter so special? What if I want to pass two parameters?

Tuple or record would be an answer.
Some .NET APIs has single "object" parameter.

**Comment by grokys** [comment]
> This is a trivial example that shows the problem:

Well yeah, I mean obviously you can demonstrate that it generating a delegate costs an allocation, but I'm surprised if that'd be a bottleneck in an application...

But I'll bow out of this, if other think it's worth the complexity then go for it.

**Comment by workgroupengineering** [comment]
The problem is significant with 24/24 active applications running on small devices like the Raspberry.

**Comment by workgroupengineering** [comment]
One part of the main library that would benefit from this feature is this.

https://github.com/AvaloniaUI/Avalonia/blob/3e3396d132385fd1304fc2ddef873911acd273ca/src/Avalonia.Visuals/Rendering/RenderLoop.cs#L112-L136

**Comment by kekekeks** [comment]
Yes, that one needs to run with Render priority.

**Comment by maxkatz6** [comment]
@grokys with this API we also can improve most useful method of AvaloniaSynchronizationContext - Post
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs#L33
which is usually used by various .NET apis, when it needs sync context

**Review by maxkatz6 — APPROVED** [review]

**Comment by workgroupengineering** [comment]
Seen this:

https://github.com/AvaloniaUI/Avalonia/blob/4f3a1e5d2fcd5a0b202dc85dbc21edc3079f7316/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs#L42

perhaps the argument should also be added to InvokeAsync

**Comment by maxkatz6** [comment]
@workgroupengineering build is failing

**Pull request merged**
