### PR TITLE
fixes: Dialog cancel consistency on windows

### LINKED ISSUE #6033: Dialog cancel consistency
**Describe the bug**
The file dialogs (`OpenFileDialog`, `SaveFileDialog`, and `OpenFileDialog`) do not have consistent return values when pressing cancel. On windows, I get `OpenFileDialog` returning empty array, `SaveFileDialog` returning null, and `OpenFolderDialog` returning an empty string. On linux, all of these return null when pressing cancel.

**To Reproduce**
Open different dialogs on different platforms, press cancel on them, and look at the return values.

```cs
private async void Test()
{
    OpenFileDialog ofd = new OpenFileDialog();
    string[] ofdRes = await ofd.ShowAsync(this);

    SaveFileDialog sfd = new SaveFileDialog();
    string sfdRes = await sfd.ShowAsync(this);

    OpenFolderDialog old = new OpenFolderDialog();
    string oldRes = await old.ShowAsync(this);

    response = $"openfile: {SetName(ofdRes)}, savefile: {SetName(sfdRes)}, openfolder: {SetName(oldRes)}";
}

private string SetName(string text)
{
    if (text == null)
        return "[null]";
    else if (text == "")
        return "[empty]";
    else
        return $"\"{text}\"";
}

private string SetName(string[] textArr)
{
    if (textArr == null)
        return "[null]";
    else if (textArr.Length == 0)
        return "[empty array]";
    else
        return $"\"{string.Join(", ", textArr)}\"";
}
```

**Expected behavior**
Should be consistent across all platforms. I'm not entirely sure what the cancel values for these dialogs are supposed to be. Maybe all null like on linux?

**Screenshots**

Windows
windows
Linux
linux

**Desktop (please complete the following information):**

- OS: Windows, Linux (PopOS w/ XFCE)
- Version 0.10.6

**Additional context**

### PR DESCRIPTION
**Pull request by workgroupengineering**
## What does the pull request do?

Windows *FileDialog cancel as same  behavior of liunx.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Fixed issues

Fixes #6033

### CODE REVIEW

**Comment by workgroupengineering** [comment]
@grokys can you review?

**Review by grokys — APPROVED** [review]
Sorry for the lateness.

I've not been involved at all in this code, but this behavior makes sense I think. One change that we should probably do is to add nullable annotations to https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/SystemDialog.cs and also XML doc comments which describe this behavior. I can add that quickly to this branch.

**Comment by grokys** [comment]
@workgroupengineering pushed a change to this branch which adds `#nullable` annotations to the file system dialogs and also XML doc comments. Could you take a look and check it's all correct?

**Comment by workgroupengineering** [comment]
LGTM

**Pull request merged**
