### PR TITLE
Fix binding errors when switching ContentControl content

### LINKED ISSUE #1099: Changing ContentControl Content produces binding errors
Repro:

https://github.com/wieslawsoltes/Draw2D/blob/453320c81b602a954aed65efb01eff77132689e8/src/Core2D.Avalonia/Views/MainView.xaml#L123-L165

Version: 0.5.1-build3602-alpha

Debug output:

```
DEFAULT_APPNAME Error: 0 : Binding: Error in binding to "Core2D.Avalonia.Views.Style.DrawStyleView"."DataContext": "Could not find CLR property 'SelectionStyle' on 'Core2D.Editor.Tools.GuideToolSettings'"
DEFAULT_APPNAME Error: 0 : Binding: Error in binding to "Avalonia.Controls.CheckBox"."IsChecked": "Could not find CLR property 'ClearSelectionOnClean' on 'Core2D.Editor.Tools.GuideToolSettings'"
DEFAULT_APPNAME Error: 0 : Binding: Error in binding to "Avalonia.Controls.Slider"."Value": "Could not find CLR property 'HitTestRadius' on 'Core2D.Editor.Tools.GuideToolSettings'"
DEFAULT_APPNAME Error: 0 : Binding: Error in binding to "Avalonia.Controls.TextBox"."Text": "Could not find CLR property 'HitTestRadius' on 'Core2D.Editor.Tools.GuideToolSettings'"
DEFAULT_APPNAME Error: 0 : Binding: Error in binding to "Avalonia.Controls.CheckBox"."IsChecked": "Could not find CLR property 'ConnectPoints' on 'Core2D.Editor.Tools.GuideToolSettings'"
DEFAULT_APPNAME Error: 0 : Binding: Error in binding to "Avalonia.Controls.Slider"."Value": "Could not find CLR property 'ConnectTestRadius' on 'Core2D.Editor.Tools.GuideToolSettings'"
DEFAULT_APPNAME Error: 0 : Binding: Error in binding to "Avalonia.Controls.TextBox"."Text": "Could not find CLR property 'ConnectTestRadius' on 'Core2D.Editor.Tools.GuideToolSettings'"
DEFAULT_APPNAME Error: 0 : Binding: Error in binding to "Avalonia.Controls.CheckBox"."IsChecked": "Could not find CLR property 'DisconnectPoints' on 'Core2D.Editor.Tools.GuideToolSettings'"
DEFAULT_APPNAME Error: 0 : Binding: Error in binding to "Avalonia.Controls.Slider"."Value": "Could not find CLR property 'DisconnectTestRadius' on 'Core2D.Editor.Tools.GuideToolSettings'"
DEFAULT_APPNAME Error: 0 : Binding: Error in binding to "Avalonia.Controls.TextBox"."Text": "Could not find CLR property 'DisconnectTestRadius' on 'Core2D.Editor.Tools.GuideToolSettings'"

DEFAULT_APPNAME Error: 0 : Binding: Error in binding to "Avalonia.Controls.CheckBox"."IsChecked": "Could not find CLR property 'SplitIntersections' on 'Core2D.Editor.Tools.PolyLineToolSettings'"

DEFAULT_APPNAME Error: 0 : Binding: Error in binding to "Avalonia.Controls.CheckBox"."IsChecked": "Could not find CLR property 'ConnectPoints' on 'Core2D.Editor.Tools.ScribbleToolSettings'"
DEFAULT_APPNAME Error: 0 : Binding: Error in binding to "Avalonia.Controls.Slider"."Value": "Could not find CLR property 'HitTestRadius' on 'Core2D.Editor.Tools.ScribbleToolSettings'"
DEFAULT_APPNAME Error: 0 : Binding: Error in binding to "Avalonia.Controls.TextBox"."Text": "Could not find CLR property 'HitTestRadius' on 'Core2D.Editor.Tools.ScribbleToolSettings'"
DEFAULT_APPNAME Error: 0 : Binding: Error in binding to "Avalonia.Controls.DropDown"."Items": "Could not find CLR property 'Tools' on 'Core2D.Editor.Tools.ScribbleToolSettings'"
DEFAULT_APPNAME Error: 0 : Binding: Error in binding to "Avalonia.Controls.DropDown"."SelectedItem": "Could not find CLR property 'CurrentTool' on 'Core2D.Editor.Tools.ScribbleToolSettings'"

DEFAULT_APPNAME Error: 0 : Binding: Error in binding to "Avalonia.Controls.CheckBox"."IsChecked": "Could not find CLR property 'Simplify' on 'Core2D.Editor.Tools.RectangleToolSettings'"
DEFAULT_APPNAME Error: 0 : Binding: Error in binding to "Avalonia.Controls.Slider"."Value": "Could not find CLR property 'Epsilon' on 'Core2D.Editor.Tools.RectangleToolSettings'"
DEFAULT_APPNAME Error: 0 : Binding: Error in binding to "Avalonia.Controls.TextBox"."Text": "Could not find CLR property 'Epsilon' on 'Core2D.Editor.Tools.RectangleToolSettings'"
DEFAULT_APPNAME Error: 0 : Binding: Error in binding to "Avalonia.Controls.CheckBox"."IsChecked": "Could not find CLR property 'IsFilled' on 'Core2D.Editor.Tools.RectangleToolSettings'"
DEFAULT_APPNAME Error: 0 : Binding: Error in binding to "Avalonia.Controls.CheckBox"."IsChecked": "Could not find CLR property 'IsClosed' on 'Core2D.Editor.Tools.RectangleToolSettings'"

DEFAULT_APPNAME Error: 0 : Binding: Error in binding to "Avalonia.Controls.CheckBox"."IsChecked": "Could not find CLR property 'ConnectPoints' on 'Core2D.Editor.Tools.ScribbleToolSettings'"
DEFAULT_APPNAME Error: 0 : Binding: Error in binding to "Avalonia.Controls.Slider"."Value": "Could not find CLR property 'HitTestRadius' on 'Core2D.Editor.Tools.ScribbleToolSettings'"
DEFAULT_APPNAME Error: 0 : Binding: Error in binding to "Avalonia.Controls.TextBox"."Text": "Could not find CLR property 'HitTestRadius' on 'Core2D.Editor.Tools.ScribbleToolSettings'"

DEFAULT_APPNAME Error: 0 : Binding: Error in binding to "Avalonia.Controls.CheckBox"."IsChecked": "Could not find CLR property 'Simplify' on 'Core2D.Editor.Tools.PathToolSettings'"
DEFAULT_APPNAME Error: 0 : Binding: Error in binding to "Avalonia.Controls.Slider"."Value": "Could not find CLR property 'Epsilon' on 'Core2D.Editor.Tools.PathToolSettings'"
DEFAULT_APPNAME Error: 0 : Binding: Error in binding to "Avalonia.Controls.TextBox"."Text": "Could not find CLR property 'Epsilon' on 'Core2D.Editor.Tools.PathToolSettings'"

DEFAULT_APPNAME Error: 0 : Binding: Error in binding to "Avalonia.Controls.CheckBox"."IsChecked": "Could not find CLR property 'IsFilled' on 'Core2D.Editor.Tools.QuadraticBezierToolSettings'"
DEFAULT_APPNAME Error: 0 : Binding: Error in binding to "Avalonia.Controls.CheckBox"."IsChecked": "Could not find CLR property 'IsClosed' on 'Core2D.Editor.Tools.QuadraticBezierToolSettings'"
DEFAULT_APPNAME Error: 0 : Binding: Error in binding to "Avalonia.Controls.DropDown"."Items": "Could not find CLR property 'Tools' on 'Core2D.Editor.Tools.QuadraticBezierToolSettings'"
DEFAULT_APPNAME Error: 0 : Binding: Error in binding to "Avalonia.Controls.DropDown"."SelectedItem": "Could not find CLR property 'CurrentTool' on 'Core2D.Editor.Tools.QuadraticBezierToolSettings'"

DEFAULT_APPNAME Error: 0 : Binding: Error in binding to "Avalonia.Controls.CheckBox"."IsChecked": "Could not find CLR property 'SplitIntersections' on 'Core2D.Editor.Tools.PointToolSettings'"

DEFAULT_APPNAME Error: 0 : Binding: Error in binding to "Avalonia.Controls.CheckBox"."IsChecked": "Could not find CLR property 'ConnectPoints' on 'Core2D.Editor.Tools.GuideToolSettings'"
DEFAULT_APPNAME Error: 0 : Binding: Error in binding to "Avalonia.Controls.Slider"."Value": "Could not find CLR property 'HitTestRadius' on 'Core2D.Editor.Tools.GuideToolSettings'"
DEFAULT_APPNAME Error: 0 : Binding: Error in binding to "Avalonia.Controls.TextBox"."Text": "Could not find CLR property 'HitTestRadius' on 'Core2D.Editor.Tools.GuideToolSettings'"
```

### PR DESCRIPTION
**Pull request by grokys**
## What does the pull request do?

When changing the `Content` in a `ContentControl`, often a different type of control will be created. In these cases, the new `Content` was briefly applied to the old control's `DataContext` causing the binding errors seen in #1099.

There were two separate causes of this:

1. In the case of inherited properties changing, `PropertyChanged` was raised on the child before the parent. This is because the inherited value change was being notified by listening to the parent `PropertyChanged` event, and this event handler was added before any other handlers (in the `AvaloniaObject.InheritanceParent` setter).
2. In `ContentPresenter.UpdateChild`, the new `DataContext` was being set _before_ the old child was removed from the logical tree, causing the new incorrect data context to be briefly inherited by the old child control.

## What is the current behavior?

The current behavior is that seen in #1099.

## What is the updated/expected behavior with this PR?

#1099 no longer occurs. See the tests added in 302bf55 for unit tests.

I've also updated the content controls to use the recommended pattern for registering content presenters, i.e. implementing `IContentPresenterHost.RegisterContentPresenter` and forwarding that to a virtual method.

## How was the solution implemented (if it's not obvious)?

For the points above:

1. Added an `IAvaloniaObject.InheritablePropertyChanged` event which will be called only after all other property changed events have been raised and only for inheritable properties. Subscribe to this in `AvaloniaObject.InheritanceParent`  instead of `PropertyChanged`
2. Adds an extra `ChildChanging` event to `IContentPresenter` which is called before the `DataContext` is updated. This event is listened for in `ContentControlMixin` to remove the old control from the logical tree

## Checklist

- [x] Added unit tests (if possible)?

## Fixed issues

Fixes #1099

### CODE REVIEW

**Comment by grokys** [comment]
Current status: @ahopper is still experiencing some problems [as reported on gitter](https://gitter.im/AvaloniaUI/Avalonia?at=5c49d7669bfa375aab52762d): waiting for a repro.

**Comment by ahopper** [comment]
This appears to fix the original issue binding to the wrong template but there are still binding errors on changing content. This repro
[ContentControlBindingRepro.zip](https://github.com/AvaloniaUI/Avalonia/files/2798849/ContentControlBindingRepro.zip)

produces
```
Binding: Error in binding to "Avalonia.ValueStore"."Content": "Null value in expression ''."
Binding: Error in binding to "Avalonia.Controls.Button"."Command": "Null value in expression ''."

Binding: Error in binding to "Avalonia.Controls.TextBlock"."Text": "Null value in expression ''."
Binding: Error in binding to "Avalonia.Controls.TextBlock"."Text": "Null value in expression ''."
```
The first two are on initial load and the second two on changing content

**Comment by grokys** [comment]
@ahopper the problem shown up by your repro should now be addressed.

**Comment by ahopper** [comment]
This now fixes everything in my repro. It does not fix binding errors in https://github.com/AvaloniaUI/Avalonia/issues/2258 but that may be something different

**Pull request merged**
