### PR TITLE
fixed: scroll to last in listbox not working sometimes

### LINKED ISSUE #2106: ListBox Virtualization sometimes prevents last item selection
To repro run the VirtualizationDemo, select an item in the list then use the down arrow to move to the last item, sometimes the last item is never shown.  If the last item is made visible by scrolling to it, sometimes clicking on it causes it to be scrolled out of view.

### PR DESCRIPTION
**Pull request by donandren**
- What does the pull request do?
unittest and fix for issue #2106  scroll to last in listbox not working sometimes
- What is the current behavior?
- What is the updated/expected behavior with this PR?
- How was the solution implemented (if it's not obvious)?

Checklist:

- [x] Added unit tests (if possible)?

Fixes #2106

### CODE REVIEW

**Comment by donandren** [comment]
@ahopper if you can document/repro  such issues i will be more than happy to try fix them. Although items with different height in virtualized list  is probably not very well supported and i have never tested similar scenarios

**Review by grokys — APPROVED** [review]
Thanks @donandren this is great! Such a simple fix, but really appreciate the unit tests ;)

**Comment by grokys** [comment]
Oh, is this still WIP?

**Comment by donandren** [comment]
@grokys i want to test this little bit more before merge, it may need some small adjustments not sure

**Comment by donandren** [comment]
ready for merge

**Pull request merged**
