### PR TITLE
WIP: Added additional Geometry impls.

### LINKED ISSUE #1352: Geometry rendering performance
I think I've brought this up before, but using stream geometry for simple shapes (rects, ellipses, lines) is quite slow, since instead of using known optimized methods of drawing, the graphics library has to do a tessellation for our custom streaming geometry, which is a *very* expensive CPU-bound process. I have a case when calling DrawLine in cycle instead of using a prepared geometry with Direct2D makes a ~400 times difference in terms of performance.

I'm a bit concerned that we are relying on geometry implementations being the actual `Path`-like objects provided by the rendering system. That makes it harder to optimize in the future, since we'll have to implement all of that `IGeometryImpl` logic for each simple shape and do it at least twice (for skia and direct2d).

### PR DESCRIPTION
**Pull request by grokys**
Using a `StreamGeometry` for everything is ineffecient, so added `EllipseGeometry`, `LineGeometry` and `RectangleGeometry` impls. 

Added implementations of these interfaces for Direct2D. @kekekeks I've not implemented these in the Skia backend because I didn't know how you wanted to do them. Do you want to add them?

Fixes #1352

### CODE REVIEW

**Comment by kekekeks** [comment]
`SKPath` has `isRect` and `isOval` methods, so I guess Skia detects common geometry types automatically, so for now we can fall back to building regular `SKPath` objects. It needs further investigation though.

**Comment by nc4rrillo** [comment]
@grokys In the interest of getting this merged, let's build SKPath objects like @kekekeks suggested. I can do the work.

**Comment by Gillibald** [comment]
Do you want me to finish this?

https://docs.microsoft.com/en-us/dotnet/api/skiasharp.skcanvas.drawline?view=skiasharp-1.60.3
https://docs.microsoft.com/en-us/dotnet/api/skiasharp.skcanvas.drawrect?view=skiasharp-1.60.3
https://docs.microsoft.com/en-us/dotnet/api/skiasharp.skcanvas.drawoval?view=skiasharp-1.60.3

**Comment by jkoritzinsky** [comment]
@Gillibald sure!

**Comment by Gillibald** [comment]
Just had a look at this and I dont get why this still uses a DrawGeometry call instead of just calling DrawLine, DrawRectangle, DrawEllipse on the render target. Shouldn't we just add These to the DrawingContext(IDrawingContextImpl) and use the optimized render paths that ways? Skia would work the same.

**Comment by grokys** [comment]
@Gillibald because shapes will (not sure if it's implemented yet?) allow you do do things like this: http://www.blackwasp.co.uk/WPFCombinedGeometry.aspx

**Comment by Gillibald** [comment]
You can always bring a conversion in place (Shape-> Geometry). Maybe the performance isn't relevant for shapes.

**Comment by MarchingCube** [comment]
@grokys I took a look at this PR, and adding support for missing geometry types on Skia is quite easy. Also Skia has dedicated methods for adding shapes to `SkPath` that are actually optimized if you just use single type (like lines, rectangles), so it makes sense to have a line geometry. Still I could barely see any improvement in this scenario as we are heavily bottlenecked by other rendering parts.

After doing initial profiling run on some stress test scenario (like 200-300 rectangles redrawn per-frame) I found that actually the `SkPaint` creation and diposal takes far longer that actually drawing the geometry. After playing around a bit with Skia and allowing for simple pooling of `SkPaint` I managed to improve rendering speed from 30 fps to 45 fps. To do any sort of pooling in official version I need a Skia version with (https://skia.org/user/api/SkPaint_Reference#SkPaint_reset) exposed. Not sure how long it would take to get a package up with this (as this is few lines of code) @mattleibow.

**Comment by grokys** [comment]
Superseded by #2375.

**Pull request closed without merging**
