### PR TITLE
Skia: Fixed line width

### LINKED ISSUE #1448: TextBox: non default aligned text selection issue
When `TextBox.TextAlignment` is set to `Center` or `Right` and I try to apply text selection the rendering becomes very strange.
textbox

### PR DESCRIPTION
**Pull request by Karnah**
- What does the pull request do?
You can see this bug when select text in multiline TextBox with CenterAllignment or RightAllignment. Selection rectangle does not overlap text. This is because the line width is calculated on the wrong substring

- What is the current behavior?
2018-05-11-c7gnw7

- What is the updated/expected behavior with this PR?
2018-05-11-3nk2yx

I created branch from #1579 because you can see problem without selection bug

Fixes #1448 

Checklist:

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

### CODE REVIEW

**Comment by grokys** [comment]
@Karnah just updated the title as this is skia-specific. I've not been involved in the skia backend, so will wait for a review from someone who has.

**Comment by Karnah** [comment]
@grokys, sure, thanks!

**Comment by nc4rrillo** [comment]
This LGTM. @grokys, can this be merged?

**Comment by danwalmsley** [comment]
@nc4rrillo I though this should be merged after the changes @marchingcube has done?

**Review by jkoritzinsky — APPROVED** [review]

**Pull request merged**
