### PR TITLE
Fix DataGridTemplateColumn Recycled Issue

### LINKED ISSUE #5453: DataGridTemplateColumn doesn't respect FuncDataTemplate SupportsRecycling parameter
**Describe the bug**
DataGrid tries to recycle data templates even if this operation was marked as unsupported.

**To Reproduce**
Create DataGridTemplateColumn template from code behind with hardcode dependency on date context value instead of bindings.

**Expected behavior**
DataTemplate is not recycled, if it was marked as SupportsRecycling = false.

**Desktop (please complete the following information):**

- OS: All
- Version 0.10.0 (must be 0.9 and earlier too).

### LINKED ISSUE #5637: DataGridTemplateColumn Recycled Issue
**Describe the bug**
When use DataGridTemplateColumn and assing dynamic CellTemplate, if row is Recycled do not, select correct template

**To Reproduce**

1. Download attache project and run
2. Scroll down to end
3. Scroll up to start
4. You can see that some control is not correct

**Expected behavior**
Select correct template.

**Screenshots**
Before Scroll down and up

Aefore Scroll down and up

Gif

DataGridTemplateColumn Issue

**Desktop (please complete the following information):**

- Version: 0.10.0 and 52fa38adce86089968c64df6be111a64c90025da

**Additional context**
[Avalonia.DataGrid.Model.zip](https://github.com/AvaloniaUI/Avalonia/files/6101887/Avalonia.DataGrid.Model.zip)

### PR DESCRIPTION
**Pull request by workgroupengineering**
DataGridTemplateColumn incorrect select template whwn DataGridRow Recycled

## What is the current behavior?

see issue #5637

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

## Fixed issues
Fixes #5637
Fixes #5453

### CODE REVIEW

**Comment by workgroupengineering** [comment]
Hi @maxkatz6,
I don't know if it is the right solution for the problem not knowing the DataGrid well. Can you suggest me how to do a test in order to avoid regressions in the future?

**Comment by maxkatz6** [comment]
@workgroupengineering I don't think I can name myself as a data grid internals specialist...
Although your changes looks good to me, I would check WPF implementation, if it updates DataGridTemplateColumn control element on datacontext changed, when it uses CellTemplateSelector. Its implementation differs in many places, but probably it could help somehow.
It seems like Silverlight/WCT don't support template selectors at all.

**Comment by maxkatz6** [comment]
My main concert with this PR implementation this PopulateCellContent will be invoked for each row always on scrolling/rows-recycling, even if data template shouldn't be recalculated.
On other hand this part of DataGrid is badly integrated with Avalonia anyway, see https://github.com/AvaloniaUI/Avalonia/issues/5453.

**Comment by workgroupengineering** [comment]
Hi @maxkatz6,
When you have some free time. Can you test if this PR works in your use case?

**Review by maxkatz6 — APPROVED** [review]

**Pull request merged**
