### PR TITLE
Fixes Issue #6263

### LINKED ISSUE #6263: ListBox.AutoScrollToSelectedItem does not scroll to the selected item when the selected item is updated just after new rows were added
Hello.
I'm trying to make ListBox scroll to a newly added item.

Consider the following code:

```C#
private void AddRowsImpl()
{
    for (var i = 0; i < 10; ++i)
    {
        var row = new RowViewModel { ...};
        
        Rows.Add(row);
    }

    SelectedRow = Rows[^1];
}
```

As we can see we first add items and then make the last one selected. Although the correct item is selected, the ListBox scrolls to the very beginning.

ListBox is created like this:

```XAML
<ListBox Grid.Row="1"
                 AutoScrollToSelectedItem="True"
                 SelectedItem="{Binding SelectedRow, Mode=TwoWay}"
                 VirtualizationMode="None"
                 Items="{Binding Rows}">
```

If we select an item without adding new rows, the ListBox scrolls correctly. The reason might be is that the ListBox does not have ListBoxItem's for the new rows yet.

I managed to dig deeper until found this method:

```C#
internal class ItemVirtualizerNone : ItemVirtualizer
    public override void ScrollIntoView(int index)
    {
        if (index != -1)
        {
            var container = Owner.ItemContainerGenerator.ContainerFromIndex(index);
            container?.BringIntoView();
        }
    }
}
```

with a debugger I managed to see that index is not -1 and `container` is not null, and `BringIntoView()` is actually called, but seems to have no effect.

I have attached a sample project that represents the problem. You need to click the "Add Rows" button. It is expected the ListBox to scroll to the last item.

[mve.zip](https://github.com/AvaloniaUI/Avalonia/files/6826516/mve.zip)

### LINKED ISSUE #11626: Wrong content of ListBox after ItemSource change
**Describe the bug**
In a ListBox with the default settings for ItemsPanel modifications of the binded ItemsSource may lead to the some elements are not re-creaded and are shown in the list several times. 
Note: seems the presence of non-null SelectedItem is mandatory to reproduce the problem

**To Reproduce**

1. Build and run the attached project. 
[AvaloniaApplication1.zip](https://github.com/AvaloniaUI/Avalonia/files/11634133/AvaloniaApplication1.zip)

2. Click the "Step 1" button.
3. Click the "Step 2" button.
4. Carefully compare the lists on the screen.
5. Note: some elements are different!
6. Resize the window as small as possible and resise it back (to force VirtualizingStackPanel recreate items)
7. Note: the contents of the lists are identical

**Expected behavior**
The contents of the lists should not depend on used ItemPanel.

**Screenshots**
image

**Desktop (please complete the following information):**

- OS: Windows
- Version 11.0.0-rc1.1

**Additional context**

### PR DESCRIPTION
**Pull request by workgroupengineering**
## What is the current behavior?

Before

## What is the updated/expected behavior with this PR?

After

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Fixed issues

Fixes #6263
Fixes #11626,

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0034924-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0035053-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0035206-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by grokys** [comment]
Just encountered a similar problem in #11626, which I think this PR should also fix, but I'm kinda not sure about always scheduling the scroll on the dispatcher, though it might not be a problem in practice. Need a little time to think about potential fixes.

**Review by grokys — APPROVED** [review]
I've been thinking about this and I think it's an acceptable solution. The main problem introduced by scrolling using the dispatcher is that unit tests get a little more unwieldy but that shouldn't be a reason to not include it.

**Pull request merged**
