### PR TITLE
[WIP] Update DataGridColumn.cs

### PR DESCRIPTION
**Pull request by usUyGBx**
## What does the pull request do?
This PR converts Header property of DataGridColumn from plain to StyledPrperty.

## What is the current behavior?
Header property does not support Binding and can cause Avalonia to crash.
(In case value is not string and user perform column reorder)

## What is the updated/expected behavior with this PR?
Header property does support Binding and still can cause Avalonia to crash.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

### CODE REVIEW

**Comment by JamRemco** [comment]
Related ? > [https://github.com/AvaloniaUI/Avalonia/issues/3831#issue-606957250](url)

**Comment by grokys** [comment]
@sdoroff are you around? How does this look to you?

**Comment by sdoroff** [comment]
@grokys Since `DataGridColumns` are not in either the logical or visual tree does additional plumbing need to be added to ensure that the `DataContext` is inherited from the owning `DataGrid`? Without that, making the `Header` bindable isn't particularly useful.

**Comment by grokys** [comment]
That's very true. @usUyGBx - how does this work given that `DataGridColumn`s aren't part of the logical tree? Did you confirm it works?

**Comment by usUyGBx** [comment]
Sorry, I diid not check DataContext switching. The binding works only on initialization. I will think how to improve it.

**Comment by grokys** [comment]
Closing this as it's seen no movement for a while. Please reopen if you update it.

**Pull request closed without merging**
