### PR TITLE
Rename to PointerEntered and PointerExited

### LINKED ISSUE #8058: Standardize Pointer Event Names with WinUI
### Discussed in https://github.com/AvaloniaUI/Avalonia/discussions/7907

Avalonia has the following primary pointer events:

PointerEnter 
PointerLeave 
PointerMoved
PointerPressed 
PointerReleased

UWP/WinUI, which was the basis for this implementation, has:

PointerEntered
PointerExited
PointerMoved
PointerPressed
PointerReleased
PointerCanceled
PointerCaptureLost

The first observation is a good simplification. UWP has PointerCanceled, PointerCaptureLost and PointerExited which are all used in slightly different situations. UWP apps must actually handle all of these events as PointerExited may never fire after PointerEntered. My assumption is Avalonia cleaned all of this up and fires PointerEnter and PointerLeave consistently doing away with the other two.

However, then we get into naming:

UWP PointerEntered vs Avalonia PointerEnter. Almost all events are past-tense and almost ALWAYS end in 'ed'. This was changed in Avalonia so it no longer matches the other event names or standard convention. In my opinion PointerEnter is misnamed and should be PointerEntered like in UWP.

Then we have PointerLeave. This was probably renamed because it no longer works exactly like UWP -- as mentioned it handles all cases where pointer exits the control for whatever reason. however, again it doesn't end in 'ed' and isn't well paired with the term 'enter'. In English the terms are matched "Enter"/"Exit" (most common) and "Arrive"/"Leave" (slightly less common) as antonyms. So in my opinion this never should have been changed and should have retained the UWP naming PointerExited.

---

As agreed in the discussion, two events should be renamed as follows:

 1. PointerEnter -> PointerEntered
 1. PointerLeave -> PointerExited

I will submit a PR for this.

### PR DESCRIPTION
**Pull request by robloo**
**Warning: This is a big breaking change for almost all apps and libraries.**

## What does the pull request do?

Per discussion in https://github.com/AvaloniaUI/Avalonia/discussions/7907 and issue https://github.com/AvaloniaUI/Avalonia/issues/8058, this standardizes event naming with ~WPF~/UWP/WinUI as follows:

 1. PointerEnter -> PointerEntered
 2. PointerLeave -> PointerExited

Several secondary members and unit tests were also renamed to match.

## What is the current behavior?

Two pointer events use the non-standardized PointerEnter and PointerLeave terminology.

## What is the updated/expected behavior with this PR?

The two pointer events use standardized PointerEntered and PointerExited terminology aligning with other XAML frameworks.

## How was the solution implemented (if it's not obvious)?

Find and replace.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Breaking changes

Yes, this is a bad one for breaking changes.

## Obsoletions / Deprecations

None

## Fixed issues

Closes https://github.com/AvaloniaUI/Avalonia/issues/8058

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0021393-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by maxkatz6** [comment]
> this standardizes event naming with WPF/UWP/WinUI as follows

WPF used *MouseEnter*. But since we went UWP/WinUI route, I also would prefer PoitnerEntered.

**Comment by robloo** [comment]
>> this standardizes event naming with WPF/UWP/WinUI as follows
>
>WPF used MouseEnter. But since we went UWP/WinUI route, I also would prefer PoitnerEntered.

Thanks, that actually would have been a good conversation point in the issue or discussion. It explains where the original naming in Avalonia comes from. I guess it's been too long since I used this in WPF and assumed it was the same as UWP.

Nevertheless, agree that the new "Pointer" term is from UWP/WinUI along with the overall design and event args, multi-touch, etc. So as it is now it is kind-of a mix of WPF + UWP. As you said, it makes sense then just to standardize around the modern terminology and UWP/WinUI design used elsewhere.

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0021402-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
