### PR TITLE
Changed IScreenImpl.AllScreens return type so that it's not array

### PR DESCRIPTION
**Pull request by jp2masa**
## Changes
- Changed `IScreenImpl.AllScreens` return type so that it's not array. (It's now ~`IEnumerable<Screen>`~`IReadOnlyList<Screen>`).

This is a binary breaking change, but I believe it's important. ~Also, I replaced array with `IEnumerable<Screen>` because there's already a `ScreenCount` property, and I think there's no specific order for the screens.~

### CODE REVIEW

**Comment by Gillibald** [comment]
Why not just use IReadOnlyList<Screen>  remove ScreenCount and use AllScreens. Count instead?

**Comment by jp2masa** [comment]
As this is a platform implementation, it may be faster to get just the screen count (see for example Win32 implementation).

**Comment by Gillibald** [comment]
On windows _allScreens is used to store all screens. Nothing that prevents you from changing IEnumerable<Screen> to IReadOnlyList<Screen>

**Comment by MarchingCube** [comment]
I might ask a bit different question - what is wrong with having screens as an array? Most of the platform implementations cache results as an array, no implementation `yield` screens so lazy evaluation is not possible. I am not sure about user API implications, but from the end user perspective this now forces an extra allocation every time when enumerating (`GetEnumerator` call).

**Comment by grokys** [comment]
I think the problem is that an array can be modified, i.e. `AllScreens[0] = null` which shouldn't be allowed. `IReadOnlyList<>` is the right choice in this case IMO.

**Review by grokys — APPROVED** [review]

**Comment by grokys** [comment]
Thanks @jp2masa, could you allow pushes to your branch so that I can merge the changes from `master` into it?

**Pull request merged**
