### PR TITLE
Add None to StandardCursorTypes #2378

### PR DESCRIPTION
**Pull request by MarkusKgit**
## What does the pull request do?
Adds a None field to StandardCursorType for setting an invisible cursor (see #2378) and adds the corresponding implementations for Win32, X11 and GTK

## What is the current behavior?
StandardCursorType does not have a None field

## What is the updated/expected behavior with this PR?
Cursor can be set to StandardCursorType.None which makes the Cursor invisible

## How was the solution implemented (if it's not obvious)?

**Win32:**

From https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-setcursor:

> Type: HCURSOR: A handle to the cursor. The cursor must have been created by the CreateCursor function or loaded by the LoadCursor or LoadImage function. If this parameter is NULL, the cursor is removed from the screen.

**X11:**
X11 does not have a default None-Type-Cursor. Instead the cursor can be set to an invisible Bitmap.
Implementation was taken from https://github.com/aktau/hhpc/blob/master/hhpc.c#L105

**GTK3:**

From https://code.woboq.org/gtk/gtk/gdk/gdkcursor.h.html#GDK_BLANK_CURSOR:

> GDK_BLANK_CURSOR = -2,

## Checklist

- [ ] Added unit tests (if possible)?

Manually tested on Windows 10 and Ubuntu 18.04 (X11)

- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

## Breaking changes
None

## Fixed issues
Implements #2378

### CODE REVIEW

**Comment by kekekeks** [comment]
PR lacks OSX implementation. Implementations for other platforms look OK.

**Comment by MarkusKgit** [comment]
Would be nice if someone could look at the OSX part, I have zero experience there and no Mac for testing

**Comment by kekekeks** [comment]
@danwalmsley

**Comment by danwalmsley** [comment]
If you can hold on a few days I can push that here!

**Comment by danwalmsley** [comment]
@MarkusKgit @kekekeks @grokys osx implementation added.

**Comment by MarkusKgit** [comment]
Awesome, thank you @danwalmsey. 
There is just minor typo on the property (IsHiden) but that's just nitpicking :)

**Comment by danwalmsley** [comment]
> Awesome, thank you @danwalmsley.
> There is just minor typo on the property (IsHiden) but that's just nitpicking :)

Its been a long day, thanks though :D

**Pull request merged**
