### PR TITLE
Opacity masks

### LINKED ISSUE #485: Implement Opacity Mask

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Fixes #485.  Skia doesn't have support for a basic opacity mask so it's implementation does nothing.

### CODE REVIEW

**Comment by grokys** [comment]
Wow that was surprisingly simple! We should probably have render tests for it though?

Other than that LGTM, will let @danwalmsley test and give the thumbs-up to merge.

**Comment by grokys** [comment]
Looks like Dan is busy, so I'm trying this out, but I can't get an opacity mask to appear in the ControlCatalog using either D2D or Cairo. I've added the following to the first `Rectangle` in `CanvasPage`

        <Rectangle.OpacityMask>
          <LinearGradientBrush StartPoint="0%,0%" EndPoint="100%,100%">
            <LinearGradientBrush.GradientStops>
              <GradientStop Offset="0" Color="Black"/>
              <GradientStop Offset="1" Color="Transparent"/>
            </LinearGradientBrush.GradientStops>
          </LinearGradientBrush>
        </Rectangle.OpacityMask>

Not sure if it's something I'm doing wrong, but if I change this from an opacity mask to a fill it seems to work...

**Comment by jkoritzinsky** [comment]
You need to put a fill in the rectangle because the default fill is null. Put a fill with full opacity (ex red) and also the opacity mask.

**Comment by grokys** [comment]
Yeah, the fill is still set to blue, sorry for the confusion. I just wanted to say that if I change the fill from blue to the linear gradient brush in the example then I se the linear gradient. However if I use that linear gradient brush as an opacity mask, I just get solid blue. Did you try it?

**Comment by kekekeks** [comment]
>Skia doesn't have support for a basic opacity mask so it's implementation does nothing.

I think that it's implemented by mask filters

https://chromium-skia-gm.commondatastorage.googleapis.com/doxygen/doxygen/html/classSkMaskFilter.html

**Comment by jkoritzinsky** [comment]
@kekekeks I already looked at mask filters. None of the supplied ones are a basic opacity mask that I can give an `SkPaint`. They all seem to be related to image manipulation (i.e. blur, emboss, gamma transformation, etc). If you see the one we would use let me know.

**Comment by jkoritzinsky** [comment]
@grokys I fixed the bug you mentioned. Try it out again when you get a chance.

**Comment by grokys** [comment]
Thanks for this @jkoritzinsky - got it merged eventually! :)

**Pull request merged**
