### PR TITLE
Fixes/osx nswindow refactor fix issues

### PR DESCRIPTION
**Pull request by danwalmsley**
Fix some regressions OSX:

 Windows open centrally by default,
 WindowState, Position are obeyed.
 
Fixes some bugs with "static casting" to protocols, causing crashes.
Fixes, popups, context menus and flyouts when in FullScreen mode.
Popups, contextmenus and flyouts are NSPanels.

 FrameSize property will be null (as in invalid) before window is shown.

### CODE REVIEW

**Comment by danwalmsley** [comment]
reminder: can flyout now work when parent in fullscreen mode?

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0020453-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by danwalmsley** [comment]
> reminder: can flyout now work when parent in fullscreen mode?

yes it works.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0020469-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by grokys — APPROVED** [review]

**Pull request merged**
