### PR TITLE
Improve NumericUpDown and AutoCompleteBox focusability 

### LINKED ISSUE #5016: NumericUpDown has no :focus
Hello, there!

It seems impossible to style the `NumericUpDown` control differently when it is focused by the user, i.e.

```xml
<Style Selector="NumericUpDown:focus">
   <!-- NumericUpDown is not amused. -->
   <Setter Property="Background" Value="Red"/>
</Style>
```

whereas

```xml
<Style Selector="TextBox:focus">
   <!-- TextBox becomes red on focus like a charm. -->
   <Setter Property="Background" Value="Red"/>
</Style>
```

Is there any workaround?

### LINKED ISSUE #8069: Can't focus NumericUpDown
**Describe the bug**
`NumericUpDown` elements can not receive focus, but some of its internal children can and should.
Currently when calling `NumericUpDown.Focus()`, nothing happens with regard to visual and keyboard focus.
This seems like a mistake, as one would expect the `TextBox` inside the `NumericUpDown` template to become the focused object, with the caret being put inside of it, possibly selecting the numerical content of the box as well.

**To Reproduce**
- Create a `NumericUpDown` element, either through code behind or XAML
- Grab the element in the code behind, for example on the `LayoutChanged` element of the parent container
- Call `.Focus()` on the element and watch as nothing happens.

**Expected behavior**
The focus and all keyboard input being put onto the `TextBox` inside of the `NumericUpDown` (like how calling `.Focus()` on a `TextBox` works), or the `NumericUpDown` element otherwise becoming focused and taking in user input.

**Desktop (please complete the following information):**

- OS: Windows 10

**Additional context**
I've tried selecting its children elements directly, but I can't seem to access these from the code end of things.

### LINKED ISSUE #11152: NumericUpDown correct tab processing
I'm using the NumericUpDown control in the stable version.
I disabled 'ShowButtonSpinner'. When I use 'Tab' for choosing the control and changing the value, as a user, I need to do it twice.
First, select control; second, move for editing. It's not very comfortable.
I think it would be nice if the control with the disabled ShowButtonSpinner would focus the first time.

First tab:
image

Second tab:
image

### LINKED ISSUE #12921: `AutoCompleteBox` keeps focus (once) when using shift+tab
**Describe the bug**
Using shift+tab when `AutoCompleteBox` has focus, it focuses something else that looks like the `AutoCompleteBox`.

**To Reproduce**
| Action | Image |
|--------|--------|
| Click on an `AutoCompleteBox` | image |
| Hit tab once | image |
| Hit shift+tab once | image |
| Hit shift+tab once again | image |

**Expected behavior**
Previous element is focused. In the given example above, the topright `AutoCompleteBox` should get focus, and no thicker wide border should occur.

**Desktop (please complete the following information):**
- OS: WIndows
- Version 11.0.4

**Additional context**
Found via #12848

### LINKED ISSUE #13339: Clicking Label control does not set focus to target NumericUpDown control
## Describe the bug

The `NumericUpDown` control's text box does not receive input focus when the Label control that targets it is clicked.
 
## To Reproduce

Define a view with this content:

```xaml
<StackPanel>
  <TextBox />

  <Label Content="Click me" Target="{Binding #BirthdayHeightBox}" />
  <NumericUpDown Name="BirthdayHeightBox" />
</StackPanel.
```

Launch the view and set focus to the TextBox control.
Then click on the Label.

No change in focus.

## Expected behavior

The NumericUpDown control should receive focus.

## Environment 

- OS: Windows 11
- Avalonia-Version: 11.0.5

### PR DESCRIPTION
**Pull request by mgnslndh**
## What does the pull request do?
Makes the NumericUpDown control focusable. Focus is delegated its child TextBox.

## What is the current behavior?
NumericUpDown is not focusable.

## What is the updated/expected behavior with this PR?
Makes it possible to focus the NumericUpDown control and when that happens focus is delegated to the containing TextBox control.

## How was the solution implemented (if it's not obvious)?
- Override Focusable property default value to true
- Focus the TextBox when NumericTextBox gets focus.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/avalonia-docs with user documentation

I tried adding unit tests for this behavior but failed. It boils down to the visual tree not being setup correctly during test so the calls to TextBox.Focus() will fail under test, but works in a normal app scenario.

If it is possible to make a working test then please advise me how to proceed. The RealFocus test service is not enough for this test case.

## Breaking changes
Don't think so.

## Fixed issues
Fixes #8069
Fixes #13339
Fixes #11152
Fixes #5016
Fixes #12921

### CODE REVIEW

**Comment by maxkatz6** [comment]
Does it work with Shift+Tab or any other way of back-focus to previous focusable element?

**Comment by mgnslndh** [comment]
@maxkatz6 
> Does it work with Shift+Tab or any other way of back-focus to previous focusable element?

No, the PR does not address that scenario. I'll look into it.

**Comment by IanRawley** [comment]
I've used the ideas in this as a base to manage something for a basic control I'm working on, and the back navigation aspect can be handled to an extent with 
```
if (e.Source == this && e.KeyModifiers.HasFlag(KeyModifiers.Shift))
{
    KeyboardNavigationHandler.GetNext(this, NavigationDirection.Previous)?.Focus(NavigationMethod.Tab);
}
``` 
in the OnGotFocus override.

**Comment by IanRawley** [comment]
I've refactored my version to account for a few oversights, and sometimes overthinking things, and come to this version.
```
protected override void OnGotFocus(GotFocusEventArgs e)
{
    base.OnGotFocus(e);
    if (e.Source == this)
    {
        if (e.KeyModifiers.HasFlag(KeyModifiers.Shift))
            KeyboardNavigationHandler.GetNext(this, NavigationDirection.Previous)?.Focus(NavigationMethod.Tab, e.KeyModifiers);
        else
            TextBox?.Focus(NavigationMethod.Tab);

        e.Handled = true;
    }
}
```

I'm not sure what you'd need to change to account for the ButtonSpinner that wraps the TextBox in the Simple Theme.  I suspect nothing actually, but haven't looked into it.

**Pull request merged**
