### PR TITLE
Add labels to issue templates

### PR DESCRIPTION
**Pull request by grokys**
Add labels to issue templates.

### CODE REVIEW

**Comment by pr8x** [comment]
Could consider having a question template as well.

**Comment by workgroupengineering** [comment]
You could consider adding a issue template for each platform (Linux, Windows, macOs, Android, iOS)  with platform-specific questions.

**Comment by grokys** [comment]
@pr8x I've just opened the discussions board so questions should go there now I think. I thought I saw a way to guide users to the discussions board from the issue template selection screen, but I can't find it now.

@workgroupengineering yeah that might be a good idea, what platform-specific questions do you have in mind?

**Comment by workgroupengineering** [comment]
It could be so:

## Common
- Avalonia Version or SHA: 10.0.rc


## Developed machine
- OS:
- Architetture:
- dotnet rutnime
- dotnet sdks
- IDE Name e Version
- Platform specific sdk:
  - Windows SDK:
  - macOS SDK:
  - iOS SDK:
  - Android SDK:

## Tareget machine:

### Common
- dotnet rutnime:

### Windows
- Windows Version:
- Video Card:
- Video Card driver version: 
- DirectX version:
- OpenGL version:

### Linux 
- Distribution: (Ubuntu 16.10 lts)
- Architetture: x64,x86, arm64, ecc..
- Video Card:
- Video Card driver version: 
- X Server Version: 
- xrandr
   - version (xrandr --version):
   - providers (xrandr --listproviders):
   - monitors (xrandr --listmonitors):
 
### Ras PI
- Hardware version:
- Distribution:
- Memory:

### macOS
- Machine (iMac, MacMini, MacBook ecc..):
- OS Version:
- ...

### iOS
- Device (iPhone 8, ecc....)
- OS Version:

### Adroid:
- Device (Sony Z1 2gb Ram, ecccc):
- Kernal Version:
- Android Distro and Version:
- Open GL Version:
- ....


You could make a template that contains everything and others for the specific platform.

Or a single template and a github action that parse the issue and tags it with the compiled platforms.

In my opinion the second possibility is better but more complicated to implement.

**Pull request merged**
