### PR TITLE
feat: formatting code before commit

### PR DESCRIPTION
**Pull request by workgroupengineering**
## What does the pull request do?

formatting code before commit

## What is the current behavior?

none

## How was the solution implemented (if it's not obvious)?

This PR adds a pre-commit git hook that checks the formatting of the code through [dotnet-format](https://github.com/dotnet/format), it doesn't add any noise because it runs locally before the commit is stored.

At this time they do not support the format of xaml, axaml, csproj and props. I am working at public PR on [dotnet-format](https://github.com/dotnet/format).

For security reasons it is not possible to save the script in the .git / hooks folder of the git repository. To make everything work, after cloning the repository you need to execute the following instruction on the command line:

```bash
git config --local core.hooksPath .githooks
```

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [x] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0017730-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by kekekeks** [comment]
See https://github.com/AvaloniaUI/Avalonia/discussions/6261

>For security reasons it is not possible to save the script in the .git / hooks folder of the git repository. 

Which is why we were thinking about running formatter straight from MSBuild in pre-CoreCompile hook.

**Comment by workgroupengineering** [comment]
> See #6261
> 
> > For security reasons it is not possible to save the script in the .git / hooks folder of the git repository.
> 
> Which is why we were thinking about running formatter straight from MSBuild in pre-CoreCompile hook.

I had already read the discussion before proposing this PR.
I have evaluated https://github.com/kzu/AutoCodeFix, but it has the same problem as an MSBuild task:
- the build is not necessarily done before the PR is sent, resulting in uncontrolled commits being sent
- adds noise to commit history with specific commits to correct formatting errors.
- to reduce the noise in the commits history, it is necessary to do the sqash

This PR is a compromise:

- Doesn't add noise because before each commit
- Unchecked commits cannot be sent
- As for security, if you don't run the git config --local core.hooksPath .githooks command, nothing is done automatically

**Comment by jmacato** [comment]
Closing this due to inactivity. Please ping me if you want to work on this again.

**Comment by workgroupengineering** [comment]
@jmacato  I don't have an Apple device. if you have a chance to try it and give me the feedback, i will work on it

**Comment by workgroupengineering** [comment]
This PR is complete.

**Comment by jmacato** [comment]
@AvaloniaUI/core any decisions over this one? i think this can help with formatting issues as well?

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019232-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019982-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0026191-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0029115-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Pull request closed without merging**
