### PR TITLE
Implemented UniformGrid

### PR DESCRIPTION
**Pull request by jp2masa**
## Changes
- Implemented `UniformGrid`.

I think it would be interesting to provide an option for square items, do you think it's worth adding it?

## Checklist

- [X] Added unit tests (if possible)?
- [X] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

### CODE REVIEW

**Review by jkoritzinsky — APPROVED** [review]
LGTM!

**Comment by jmacato** [comment]
@jp2masa can you resync this to master?

**Comment by nc4rrillo** [comment]
LGTM :rocket:

**Comment by jmacato** [comment]
@nc4rrillo @jp2masa say, should we include a ViewBox too? iirc @wieslawsoltes have something in PanAndZoom repo for that?

**Comment by wieslawsoltes** [comment]
I have some simple VB control https://github.com/wieslawsoltes/PanAndZoom/tree/master/src/Avalonia.Controls.ViewBox

**Pull request merged**
