### PR TITLE
WIP: Use LineGeometry to DrawLines on DeferredRenderer

### PR DESCRIPTION
**Pull request by danwalmsley**
## What does the pull request do?
Fixes dirty rects calculations for lines with thickness and that are diagonals.

## What is the current behavior?

image

## What is the updated/expected behavior with this PR?

image

## How was the solution implemented (if it's not obvious)?

Uses LineGeometry so Skia will calculated the bounds not avalonia.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

### CODE REVIEW

**Comment by kekekeks** [comment]
Geometries are generally slower than plain `DrawLine` calls. We should fix our bounds calculation instead.

**Comment by danwalmsley** [comment]
notice that there is some margin in the dirty rect indicating an issue with deferred renderer.

**Comment by danwalmsley** [comment]
> Geometries are generally slower than plain `DrawLine` calls. We should fix our bounds calculation instead.

how do you know that the calculation will 100% match skias, especially with us using double and skia floats?

**Comment by danwalmsley** [comment]
superceeded by #3909

**Pull request closed without merging**
