### PR TITLE
Or Selector benchmark and removal of repeated virtual calls

### PR DESCRIPTION
**Pull request by MarchingCube**
I had similar changes like in https://github.com/AvaloniaUI/Avalonia/pull/10478 but I didn't have time to wrap it up before leaving for holidays. I've started from writing a benchmark case so we can avoid this issue in the future. More selectors could be covered later too.

## What does the pull request do?

Removes repeated virtual calls to `Count`.

## What is the current behavior?

There are many repeated virtual calls to `Count` that can be easily avoided.
Also it might be the case that a few changes to `StyledElement` might have the same problem, in one case in `ApplyStyles` it might be an actual pessimization to use a for loop since `Styles` have a struct enumerator that does not allocate anything.

## What is the updated/expected behavior with this PR?

Minor perf increase, I didn't bother to measure. But I have benchmarks for or selector with optimization to iteration (as introduced in https://github.com/AvaloniaUI/Avalonia/pull/10478):

Before
|                Method |     Mean |    Error |   StdDev |   Gen0 | Allocated |
|---------------------- |---------:|---------:|---------:|-------:|----------:|
|  OrSelector_One_Match | 50.95 ns | 0.223 ns | 0.198 ns | 0.0076 |      32 B |
| OrSelector_Five_Match | 52.05 ns | 0.265 ns | 0.248 ns | 0.0076 |      32 B |

After
|                Method |     Mean |    Error |   StdDev |   Gen0 | Allocated |
|---------------------- |---------:|---------:|---------:|-------:|----------:|
|  OrSelector_One_Match | 39.70 ns | 0.315 ns | 0.263 ns |      - |         - |
| OrSelector_Five_Match | 39.79 ns | 0.329 ns | 0.275 ns |      - |         - |

So we are saving 32B per match while also getting ~20% perf speedup. So yeah an analyzer would help a lot since this little issue causes trouble all over the place.

Also added extra run configs for benchmark project so we can easily control it without manually changing arguments.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0031510-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by MrJul** [comment]
Thanks for providing a benchmark! (I'm the author of #10478)
The virtual call reductions are nice, I'll keep that in mind for future changes :)


> Also it might be the case that a few changes to `StyledElement` might have the same problem, in one case in `ApplyStyles` it might be an actual pessimization to use a for loop since `Styles` have a struct enumerator that does not allocate anything.

I went with `for` for consistency here: indeed the `Styles` enumerator won't be boxed. That said, `Styles.Count` isn't virtual either and cheap enough to be inlined so there's no heavy cost to pay here. (See [this example](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8lAbhvqfIDoBhCADYCYYDAEsIAO1zcA8sABWIjAFkIAExgD21DgGYmpBrwYBvGg0tMDxFAwAyY3Bn4BXSRgAUj5wB5mdAB8DAJOGACUZhZWMQBm0AyeAG7YUAxiDAC8DHSs6Qy+IWF8EO4YeQDUFWLh0TH1XACcnqHOANpiALrhOjEAvnUMg8Q2dj4upR72EGDYAt5h/uRBRc6R5tQNlilpkGVZqxglZb1b8WnJqfnZufmFex6V1bWbWzHMza0YHd2nlgOvSzDUYOMIAMWgMGwYAAFgs/AFgl91oM4pDoTDEjt0hgYPh0pJDi83u9yJ8wj1BgCATQgA=) where you can see that `Count` has been inlined to a `[rsi+0x10]` access.)

The other cases could definitely cache the virtual call count.

**Comment by MarchingCube** [comment]
> Thanks for providing a benchmark! (I'm the author of #10478) The virtual call reductions are nice, I'll keep that in mind for future changes :)
> 
> > Also it might be the case that a few changes to `StyledElement` might have the same problem, in one case in `ApplyStyles` it might be an actual pessimization to use a for loop since `Styles` have a struct enumerator that does not allocate anything.
> 
> I went with `for` for consistency here: indeed the `Styles` enumerator won't be boxed. That said, `Styles.Count` isn't virtual either and cheap enough to be inlined so there's no heavy cost to pay here. (See [this example](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8lAbhvqfIDoBhCADYCYYDAEsIAO1zcA8sABWIjAFkIAExgD21DgGYmpBrwYBvGg0tMDxFAwAyY3Bn4BXSRgAUj5wB5mdAB8DAJOGACUZhZWMQBm0AyeAG7YUAxiDAC8DHSs6Qy+IWF8EO4YeQDUFWLh0TH1XACcnqHOANpiALrhOjEAvnUMg8Q2dj4upR72EGDYAt5h/uRBRc6R5tQNlilpkGVZqxglZb1b8WnJqfnZufmFex6V1bWbWzHMza0YHd2nlgOvSzDUYOMIAMWgMGwYAAFgs/AFgl91oM4pDoTDEjt0hgYPh0pJDi83u9yJ8wj1BgCATQgA=) where you can see that `Count` has been inlined to a `[rsi+0x10]` access.)
> 
> The other cases could definitely cache the virtual call count.

You are right in the case of `Styles` it can be actually inlined since it does not go through an interface. For `IReadOnlyList` it sadly will call `Count` for each condition check.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0031586-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]

**Pull request merged**
