### PR TITLE
Trying to make integration tests more stable on macOS.

### PR DESCRIPTION
**Pull request by grokys**
## What does the pull request do?

We have very unstable integration tests on macOS. I was trying and failing to find a solution in this PR, but Appium on macOS just crashes randomly it seems.

This PR is worth merging however because it improves a couple of things:

- Skips the most flaky test: `Does_Not_Switch_Space_From_FullScreen_To_Main_Desktop_When_FullScreen_Window_Clicked` - this is the one that was causing the most failures
- Gives display names to the mac CI tasks
- Displays detailed logs when running tests so we can see the passed tests, not only the skipped and failed ones - this can be useful if the test before the failing test left the system in an invalid state; previously, we didn't know what ran before
- Uploads the appium logs as an artifact on fail so we can try to diagnose the problem

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0030949-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0030963-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0030970-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0031101-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Review by danwalmsley — APPROVED** [review]

**Pull request merged**
