### PR TITLE
Scene hittest now uses exclusive `Rect.Contains`. Fixes https://githu…

### LINKED ISSUE #3079: PointerPressed captures pointers 1 pixel outside of the control
I have a control that's size is 128 wide and 16 tall. When I subscribe to the PointerPressed event, I am getting events from both x=128 and y=16 (which are outside of the control). Any X and Y coords larger do not fire the event. The event also will not fire if there is a different control directly next to this control. For example, if I have another control to the right of this control, then events with x=128 will not be sent to this control.

### PR DESCRIPTION
**Pull request by jinek**
## What does the pull request do?
Partially fixes https://github.com/AvaloniaUI/Avalonia/issues/3079

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0022497-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by jinek** [comment]
> You can test this PR using the following package version. `0.10.999-cibuild0022497-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

Can not test this build as public API there changed a lot

```
1>/home/jinek/Repo/Consolonia/src/Consolonia.Core/Drawing/ConsoloniaRenderInterface.cs(7,24): error CS0234: The type or namespace name 'Media' does not exist in the namespace 'Avalonia.Visuals' (are you missing an assembly reference?)
     1>/home/jinek/Repo/Consolonia/src/Consolonia.Core/Drawing/ConsoloniaRenderInterface.cs(28,27): error CS0246: The type or namespace name 'FormattedTextStyleSpan' could not be found (are you missing a using directive or an assembly reference?)
     1>/home/jinek/Repo/Consolonia/src/Consolonia.Core/Drawing/ConsoloniaRenderInterface.cs(21,16): error CS0246: The type or namespace name 'IFormattedTextImpl' could not be found (are you missing a using directive or an assembly reference?)
     1>/home/jinek/Repo/Consolonia/src/Consolonia.Core/Drawing/ConsoloniaRenderInterface.cs(96,13): error CS0246: The type or namespace name 'BitmapInterpolationMode' could not be found (are you missing a using directive or an assembly reference?)
     1>/home/jinek/Repo/Consolonia/src/Consolonia.Core/Drawing/ConsoloniaRenderInterface.cs(102,13): error CS0246: The type or namespace name 'BitmapInterpolationMode' could not be found (are you missing a using directive or an assembly reference?)
     1>/home/jinek/Repo/Consolonia/src/Consolonia.Core/Drawing/ConsoloniaRenderInterface.cs(118,13): error CS0246: The type or namespace name 'BitmapInterpolationMode' could not be found (are you missing a using directive or an assembly reference?)
```

**Comment by maxkatz6** [comment]
@jinek thanks!
Can you write a unit test, so it won't be forgotten later? See DeferredRendererTests_HitTesting.cs file

Note, this PR changes old renderer's code, which is soon to be deprecated. New renderer hit testing code is here: https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Base/Rendering/Composition/CompositionTarget.cs#L97
Which probably also should be checked/tested. CompositorHitTestingTests.cs file.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0022615-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by jinek** [comment]
@maxkatz6 I've added few more exclusive checks

**Comment by grokys** [comment]
Looks good but there are a few other `DrawOperation`s to change;

https://github.com/AvaloniaUI/Avalonia/blob/1c1499c39961786f5b5046fc2fbd4c641f570566/src/Avalonia.Base/Rendering/SceneGraph/ImageNode.cs#L112
https://github.com/AvaloniaUI/Avalonia/blob/1c1499c39961786f5b5046fc2fbd4c641f570566/src/Avalonia.Base/Rendering/SceneGraph/GlyphRunNode.cs#L76

I didn't check all of them so there may be more.

I don't think we need unit tests for each one of these.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0022652-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]

**Pull request merged**
