### PR TITLE
InlineUIContainer

### PR DESCRIPTION
**Pull request by Gillibald**
## What does the pull request do?

Port of: https://docs.microsoft.com/en-us/dotnet/api/system.windows.documents.inlineuicontainer?view=windowsdesktop-6.0
InlinesWrapping

## Checklist

- [x] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019747-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by robloo** [comment]
Awesome!

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019838-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0020044-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0020083-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0020141-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]

**Comment by GaNacereddine** [comment]
@Gillibald Thanks for the great work,

can you share how you did the space between the button and text?

it would be great if you could share the xaml for the example above

**Comment by maxkatz6** [comment]
I believe it's example from the attached wpf link
https://docs.microsoft.com/en-us/dotnet/api/system.windows.documents.inlineuicontainer?view=windowsdesktop-6.0

**Comment by Gillibald** [comment]
You need to post the actual Xaml you have tried so I can reproduce the underlying issue

**Pull request merged**
