### PR TITLE
feat(LibInputBackend): Intercept Keyboard events

### PR DESCRIPTION
**Pull request by workgroupengineering**
## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0022216-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by workgroupengineering** [comment]
@kekekeks  while working in this PR, I found a problem. Avalonia [Key](https://github.com/AvaloniaUI/Avalonia/blob/27445b1cd8555da31ce09c7d573f42f8405f94d8/src/Avalonia.Base/Input/Key.cs) enum has not keys from F25 to F35. How How can I map them??

**Comment by kekekeks** [comment]
We can add F25-F35 if needed. I'm not sure if there are keyboards with such keys though.

**Comment by workgroupengineering** [comment]
@kekekeks  Can you suggest a Linux dist where I can test Framebuffer in Hyper-V? I try with ubuntu but i have some problems.

**Comment by kekekeks** [comment]
I was only testing with bare-metal (various Intel and ARM devices) and with qemu. 

According to [this Phoronix article](https://www.phoronix.com/news/Linux-5.14-Hyper-V-Display) the proper support for DRM/KMS in Hyper-V should be available starting with Linux 5.14.

Also, try running kmscube, if it runs the problem might be an Avalonia bug.

If you have problems with pointer input, make sure that Hyper-V provides an absolute pointing device (tablet/touchscreen) and that said device is properly recognized by `libinput list-devices` and produces absolute positioned events for `libinput debug-events`

**Comment by workgroupengineering** [comment]
hi kekekeks, 
thanks for the tips, i found the solution using vfb.

I have design doubts that I would like to discuss.
the features I would like to implement:
- Select Keybord Layout
- Allow Custom Keybord Layout
- Management of multiple keyboards, mouses and touch screens
- Inject a custom handler for libinput events 
- Support to Seat

The questions are:

- for configuration:
   - [ ] Add parameter to  StartLinux*
   - [ ] Extend AppBuilder
- for management of multiple keyboards, mouses and touch screens. Avalonia currently creates a MouseDevice and Touch Device instance for all connected devices. https://github.com/AvaloniaUI/Avalonia/blob/e57e0b76fceb118ed15260844b4eae025662f6a6/src/Linux/Avalonia.LinuxFramebuffer/Input/LibInput/LibInputBackend.cs#L15-L16 is it better to add a Source property or create an instance for each device? Adding the source property could lead to consistency issues, creating multiple instances could be a waste of memory.

**Comment by workgroupengineering** [comment]
@kekekeks 

What is the correlation between RawKeyEventArgs and EventArgs RawTextInputEventArgs?

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0029320-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0037518-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0039353-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0039814-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by jmacato** [comment]
What's the status here @workgroupengineering @maxkatz6 ?

**Comment by workgroupengineering** [comment]
missing review

**Comment by workgroupengineering** [comment]
I close, it will never be accepted because they will include this feature only in Avalonia Accelerate https://github.com/AvaloniaUI/Avalonia/discussions/16997

**Comment by grokys** [comment]
Not sure what this PR has to do with the features we announced for Avalonia Accelerate? Though it's hard to tell because there's no description. Anyway I'm 100% sure that Avalonia Accelerate has nothing to do with this not getting merged.

**Comment by kekekeks** [comment]
Avalonia Accelerate will have an _on-screen_ keyboard (similar to what you have on your phone), there are currently no plans to lock something like _hardware_ keyboard support.

**Pull request closed without merging**
