### PR TITLE
Limit IFocusManager API, extend IInputElement API, remove focus static members from public API

### PR DESCRIPTION
**Pull request by maxkatz6**
## What does the pull request do?

- Clean-ups inconsistence between focus and keyboard focus APIs.
- Replaces public static API with TopLevel API
- Removes unstable IFocusScope API after discussion

Keeping in mind that we have a very long list of refactorings related to the focus system in Avalonia, we really need to limit it now with something that won't be broken mid 11.x.

```diff
// Limited APIs:
public interface IFocusManager
{
-    Avalonia.Input.IInputElement? Current { get; }
-    Avalonia.Input.IFocusScope? Scope { get; }
-    void Focus(Avalonia.Input.IInputElement? control, Avalonia.Input.NavigationMethod method = Avalonia.Input.NavigationMethod.Unspecified, Avalonia.Input.KeyModifiers keyModifiers = Avalonia.Input.KeyModifiers.None);
-    void RemoveFocusScope(Avalonia.Input.IFocusScope scope);
-    void SetFocusScope(Avalonia.Input.IFocusScope scope);
+    Avalonia.Input.IInputElement? GetFocusedElement();
+    [Avalonia.Metadata.UnstableAttribute("This API might be removed in 11.x minor updates. Please consider focusing another element instead of removing focus at all for better UX.")]
+    void ClearFocus();
}

- public interface IKeyboardDevice : Avalonia.Input.IInputDevice, System.ComponentModel.INotifyPropertyChanged
+ public interface IKeyboardDevice : Avalonia.Input.IInputDevice
{
-    Avalonia.Input.IInputElement? FocusedElement { get; }
-    void SetFocusedElement(Avalonia.Input.IInputElement? element, Avalonia.Input.NavigationMethod method, Avalonia.Input.KeyModifiers modifiers);
}

// Hidden APIs:
- [Avalonia.Metadata.PrivateApi]
- public class FocusManager : Avalonia.Input.IFocusManager
- { }
 
- [Avalonia.Metadata.PrivateApi]
- public class KeyboardDevice : Avalonia.Input.IKeyboardDevice
- { }
- [Avalonia.Metadata.PrivateApi]
- public class MouseDevice : Avalonia.Input.IMouseDevice
- { }
- [Avalonia.Metadata.PrivateApi]
- public class PenDevice : Avalonia.Input.IPointerDevice
- { }
- [Avalonia.Metadata.PrivateApi]
- public class TouchDevice : Avalonia.Input.IPointerDevice
- { }

// Not implementable by user code anymore. But intended to be returned in 11.x.
+ [Avalonia.Metadata.NotClientImplementableAttribute]
public interface IFocusScope
{
}

// Extended APIs:
public class InputElement
{
...
-   void Focus();
+  bool Focus(NavigationMethod method = Unspecified, KeyModifiers keyModifiers = None);
...
}

public class TopLevel
{
...
+   IFocusManager FocusManager { get; }
...
}
```

## Breaking changes

Yes.
- Static FocusManager.Instance replaced with TopLevel.FocusManager.
- FocusManager.Focus is replaced with InputElement.Focus
- Instead of FocusManager.Focus(null) there is FocusManager.ClearFocus() now
- InputScope functionality is hidden from the API. It might or might not be restored in the future.
- IKeyboardDevice doesn't have methods duplicating FocusManager anymore
- KeyboardDevice and FocusManager implementations are internal now
- Less related, but MouseDevice, TouchDevice and PenDevice are internal now as well (they didn't had any public APIs anyway).

## Fixed issues

Fixes partially #11381
Prepares for #7607

### CODE REVIEW

**Comment by maxkatz6** [comment]
cc @amwx

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0034881-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by grokys** [comment]
I think the only thing missing from the API is a way to track focus changes globally: previously one could do that by subscribing to `IKeyboardDevice.PropertyChanged` (which wasn't an ideal API). I think I've only needed this for diagnostic purposes though (at least I can't remember any other uses right now), so not sure how important it is.

**Review by grokys — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0035030-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by MrJul** [comment]
Small feedback on `ClearFocus` being potentially removed later: if Avalonia is embedded inside any other UI system, you _need_ to be able to clear the focus as you don't want an Avalonia control to stay visually focused when the focus has moved to a non-Avalonia UI element. Probably a niche interop scenario again, I know, but still a real one :)

The whole API will probably change with #7607 anyway? If I'm interpreting "preparing" correctly, that PR is on the table again, which is great, as focus needs a good overhaul!

**Comment by kekekeks** [comment]
>you need to be able to clear the focus as you don't want an Avalonia control to stay visually focused
That should be handled by `ITopLevelImpl.Deactivated` event handler

**Comment by MrJul** [comment]
> That should be handled by `ITopLevelImpl.Deactivated` event handler

Indeed! Thanks for the pointer, it turns out that indeed that extra `ClearFocus` call wasn't needed with `ITopLevelImpl.LostFocus`. Please disregard my previous comment.

**Comment by kekekeks** [comment]
>Can we no longer simulate keyboard key input (not just text) across the entire application?

Simulating input events in 11.0 works _exactly_ as it does in WPF and UWP - by raising a routed event:
```
focusedElement.RaiseEvent(new KeyEventArgs
{
    RoutedEvent = InputElement.KeyDownEvent,
    Key = ...,
    KeyModifiers = ..,
    Source = element,
};
```

This was the intended way of sending events since 0.1.0.

For tracking focused element updates you can use `InputElement.GotFocusEvent` and `InputElement.LostFocusEvent` that can be subscribed to globally via `Raised` property.

**Comment by kekekeks** [comment]
The key bindings are a valid concern though, we'll investigate how to make those to be triggerable by user code.

**Comment by qfmee** [comment]
> > Can we no longer simulate keyboard key input (not just text) across the entire application?
> 
> Simulating input events in 11.0 works _exactly_ as it does in WPF and UWP - by raising a routed event:
> 
> ```
> focusedElement.RaiseEvent(new KeyEventArgs
> {
>     RoutedEvent = InputElement.KeyDownEvent,
>     Key = ...,
>     KeyModifiers = ..,
>     Source = element,
> };
> ```
> 
> This was the intended way of sending events since 0.1.0.
> 
> For tracking focused element updates you can use `InputElement.GotFocusEvent` and `InputElement.LostFocusEvent` that can be subscribed to globally via `Raised` property or by using IFocusManager

I am still unable to obtain input. Is there a more detailed sample code?

**Comment by storzem** [comment]
> Simulating input events in 11.0 works _exactly_ as it does in WPF and UWP - by raising a routed event:

I'm in the same boat as @qfmee, and I can't seem to simulate any input via the method you described.

I've put all of the following logic inside the Keyboard control itself for now while I'm testing:

`   

   //In Keyboard control's constructor
   InputElement.GotFocusEvent.Raised.Subscribe(ElementHasFocus);
   InputElement.LostFocusEvent.Raised.Subscribe(ElementLostFocus);
        
   
    
    private void ElementHasFocus((object, RoutedEventArgs) obj)
    {
        if (obj.Item1 is TextBox ie) //hardcoded type selection for testing.
            _currentElement = ie;
    }
    
    private void ElementLostFocus((object, RoutedEventArgs) obj)
    {
        if (obj.Item1 == _currentElement)
            _currentElement = null;
    }


//In an event handler for key presses on our keyboard...

      _currentElement?.RaiseEvent(new KeyEventArgs
            {
                RoutedEvent = InputElement.KeyDownEvent,
                Key = Key.A,
                KeyModifiers = KeyModifiers.Shift,
                Source = this,
            });
       _currentElement?.RaiseEvent(new KeyEventArgs
            {
                RoutedEvent = InputElement.KeyUpEvent,
                Key = Key.A,
                KeyModifiers = KeyModifiers.Shift,
                Source = this,
            });
           
`

"this" is my keyboard control. I've tried with and without the KeyUpEvent, with and without the Modifier Key, Setting source to MainWindow and _currentElement. 

_currentElement is not null, and is set to the TextBox I have focused as expected.

Am I missing something here?

**Comment by storzem** [comment]
After further testing, I've found the following works for the text input:
```
    _currentElement?.RaiseEvent(new TextInputEventArgs
            {
                RoutedEvent = InputElement.TextInputEvent,
                Text = key.DisplayValue,
                Source = _currentElement,
            });
          
```

I'm still struggling to send key event's though.

**Comment by timunie** [comment]
@storzem should work similar, I guess? Can you show which code does not work for you?

**Comment by timunie** [comment]
EDIT: Best would be to open a new Q&A discussion and ideally have a minimal sample showing what you have so far.

**Comment by kekekeks** [comment]
The Source should be set to the _focused element_ not to your keyboard control

**Comment by qfmee** [comment]
Like this: 

_currentElement?.RaiseEvent(new KeyEventArgs
                {
                    RoutedEvent = InputElement.KeyDownEvent,
                    Key = Key.Left,
                    KeyModifiers = KeyModifiers.None,
                    Source = _currentElement,
                });, 

the Control key can take effect, but the text can't, such as Key.A,Key.B...........

**Comment by storzem** [comment]
> the Control key can take effect, but the text can't, such as Key.A,Key.B...........

Yeah, I found for alphanumerics (and possibly more), you need to use:

 _currentElement?.RaiseEvent(new TextInputEventArgs
            {
                RoutedEvent = InputElement.TextInputEvent,
                Text = key.DisplayValue,
                Source = _currentElement,
            });

**Comment by qfmee** [comment]
Thanks. This method allows for text input, but non English text, such as Chinese, cannot be input！

**Comment by qfmee** [comment]
> > EDIT: Best would be to open a new Q&A discussion and ideally have a minimal sample showing what you have so far.
> 
> Apologies for the late reply, work has been super busy!
> 
> Based on what @qfmee said last, it seems like it might just be a case of alphanumeric keys being ignored on the KeyDownEvent. I'm assuming this is to avoid duplicate input, as TextInputEvent handles text.... I'll get some testing done and put a Q&A + example project together either tonight or this weekend.

Thanks. This method allows for text input, but non English text, such as Chinese, cannot be input！

**Pull request merged**
