### PR TITLE
Radio button and checkbox vertically center the content.

### PR DESCRIPTION
**Pull request by danwalmsley**
## What does the pull request do?

Fixes the content alignment of Radio buttons and Checkboxes

## What is the current behavior?

incorrect positioning.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

### CODE REVIEW

**Comment by grokys** [comment]
I wonder why this is necessary - the `Top` alignment comes from the UWP styles and they don't appear to have the same alignment issue?

**Comment by FoggyFinder** [comment]
> Fixed issues

Partially: #4328

**Comment by maxkatz6** [comment]
@grokys 
It seems UWP margins were added to work with Segoe UI font. If I set same font for Avalonia, it looks fine even with default Top alignment.
For Avalonia with default Roboto font both Top and Center alignments doesn't look good enough as for me.
But if we remove top margin at all, Center alignment will looks good with both these fonts (as @jp2masa suggested).

UWP with Segoe UI
image
Avalonia with Segoe UI
image
Avalonia with Roboto
image

VerticalAlignment: Stretch - Top (default) - Center (this PR) - Bottom

**Comment by maxkatz6** [comment]
I found issue on WinUI repository, why they used Top value at first place 
https://github.com/microsoft/microsoft-ui-xaml/issues/1520

Radio/CheckBox and should be centered only by first line.
image

**Comment by grokys** [comment]
Thanks @maxkatz6 - that's interesting. Do you agree that this PR is the best solution for now then?

**Comment by maxkatz6** [comment]
@grokys well, if we will use Center alignment for now, then we should also remove top margins as well.

https://github.com/AvaloniaUI/Avalonia/blob/588d4377eb85bca48b647b5f826e47f739079c29/src/Avalonia.Themes.Fluent/CheckBox.xaml#L11
https://github.com/AvaloniaUI/Avalonia/blob/588d4377eb85bca48b647b5f826e47f739079c29/src/Avalonia.Themes.Fluent/RadioButton.xaml#L16

**Comment by Sorien** [comment]
as I remember roboto had exactly the same problem in browsers, s/t like https://github.com/google/fonts/issues/24, but when I trying it in jsfiddele it seems to be solved

**Pull request merged**
