### PR TITLE
Fix RelativePanel crash inside StackPanel

### LINKED ISSUE #8624: Application immediately crashes with exception "Invalid size returned for Measure." when putting a RelativePanel in a StackPanel
**Describe the bug**
I made a minimal repo for [reproducing the error](https://github.com/GNUGradyn/AvaloniaDemo). Here is the exception
```
System.InvalidOperationException: Invalid size returned for Measure.
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 373
   at Avalonia.Controls.StackPanel.MeasureOverride(Size availableSize) in /_/src/Avalonia.Controls/StackPanel.cs:line 207
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 559
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 364
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding) in /_/src/Avalonia.Layout/LayoutHelper.cs:line 46
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding, Thickness borderThickness) in /_/src/Avalonia.Layout/LayoutHelper.cs:line 39
   at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size availableSize) in /_/src/Avalonia.Controls/Presenters/ContentPresenter.cs:line 366
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 559
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 364
   at Avalonia.Layout.LayoutHelper.MeasureChild(ILayoutable control, Size availableSize, Thickness padding) in /_/src/Avalonia.Layout/LayoutHelper.cs:line 46
   at Avalonia.Controls.Decorator.MeasureOverride(Size availableSize) in /_/src/Avalonia.Controls/Decorator.cs:line 54
   at Avalonia.Controls.Primitives.VisualLayerManager.MeasureOverride(Size availableSize) in /_/src/Avalonia.Controls/Primitives/VisualLayerManager.cs:line 133
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 559
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 364
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 625
   at Avalonia.Layout.Layoutable.MeasureCore(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 559
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 364
   at Avalonia.Layout.Layoutable.MeasureOverride(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 625
   at Avalonia.Controls.Window.MeasureOverride(Size availableSize) in /_/src/Avalonia.Controls/Window.cs:line 928
   at Avalonia.Controls.WindowBase.MeasureCore(Size availableSize) in /_/src/Avalonia.Controls/WindowBase.cs:line 243
   at Avalonia.Layout.Layoutable.Measure(Size availableSize) in /_/src/Avalonia.Layout/Layoutable.cs:line 364
   at Avalonia.Layout.LayoutManager.Measure(ILayoutable control) in /_/src/Avalonia.Layout/LayoutManager.cs:line 287
   at Avalonia.Layout.LayoutManager.ExecuteInitialLayoutPass() in /_/src/Avalonia.Layout/LayoutManager.cs:line 174
   at Avalonia.Controls.Window.ShowCore(Window parent) in /_/src/Avalonia.Controls/Window.cs:line 693
   at Avalonia.Controls.Window.Show() in /_/src/Avalonia.Controls/Window.cs:line 631
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.ShowMainWindow() in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 129
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 118
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at AvaloniaDemo.Program.Main(String[] args) in D:\code\AvaloniaDemo\AvaloniaDemo\Program.cs:line 12
   ```

**To Reproduce**

Put a Relative panel in a stack panel

**Expected behavior**
You get a relative panel in a stack panel

**Screenshots**
image

**Desktop (please complete the following information):**

- OS Windows 10
- Version 0.10.14 (NuGet 0.10.17)

### PR DESCRIPTION
**Pull request by byme8**
## What does the pull request do?
Fix for https://github.com/AvaloniaUI/Avalonia/issues/8624

## What is the current behavior?
When you put RelativePanel inside the StackPanel, the RelativePanel will try to take all available space. In the case of the vertical StackPanel, it would try to take infinite height and fail because of it. 

## What is the updated/expected behavior with this PR?
The Grid, WrapPanel, and DockPanel completely ignore the infinite size, They will limit their height based on the child component's height. The same behavior is applied to the RelativePanel.

## Fixed issues
Fixes #8624

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=8727) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=8727) before we can accept your contribution.<br/><br/>:x: byme8 [sign now](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=8727)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/AvaloniaUI/Avalonia?pullRequest=8727) it.</sub>

**Comment by byme8** [comment]
When I was working on the issue, I found peculiar logic. In the RelativePanel.MeasureOverride. it measures and resets measurements multiple times. Does someone have idea why it happens?
``` cs
// RelativePanel.cs
protected override Size MeasureOverride(Size availableSize)
{
    _childGraph.Clear();
    foreach (Layoutable child in Children)
    {
        if (child == null)
        {
            continue;
        }

        var node = _childGraph.AddNode(child);

        node.AlignLeftWithNode = _childGraph.AddLink(node, GetDependencyElement(AlignLeftWithProperty, child));
        node.AlignTopWithNode = _childGraph.AddLink(node, GetDependencyElement(AlignTopWithProperty, child));
        node.AlignRightWithNode = _childGraph.AddLink(node, GetDependencyElement(AlignRightWithProperty, child));
        node.AlignBottomWithNode = _childGraph.AddLink(node, GetDependencyElement(AlignBottomWithProperty, child));

        node.LeftOfNode = _childGraph.AddLink(node, GetDependencyElement(LeftOfProperty, child));
        node.AboveNode = _childGraph.AddLink(node, GetDependencyElement(AboveProperty, child));
        node.RightOfNode = _childGraph.AddLink(node, GetDependencyElement(RightOfProperty, child));
        node.BelowNode = _childGraph.AddLink(node, GetDependencyElement(BelowProperty, child));

        node.AlignHorizontalCenterWith = _childGraph.AddLink(node, GetDependencyElement(AlignHorizontalCenterWithProperty, child));
        node.AlignVerticalCenterWith = _childGraph.AddLink(node, GetDependencyElement(AlignVerticalCenterWithProperty, child));
    }

    _childGraph.Measure(availableSize); // <== measure first time

    _childGraph.Reset(false);  // <== reset
    var calcWidth = Width.IsNaN() && (HorizontalAlignment != HorizontalAlignment.Stretch);
    var calcHeight = Height.IsNaN() && (VerticalAlignment != VerticalAlignment.Stretch);

    var boundingSize = _childGraph.GetBoundingSize(calcWidth, calcHeight);
    _childGraph.Reset();  // <== measure second time
    _childGraph.Measure(boundingSize);  // <== reset
    
    return boundingSize;
}
```

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0023117-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by danwalmsley** [comment]
> When I was working on the issue, I found peculiar logic. In the RelativePanel.MeasureOverride. it measures and resets measurements multiple times. Does someone have idea why it happens?
> 
> ```cs
> // RelativePanel.cs
> protected override Size MeasureOverride(Size availableSize)
> {
>     _childGraph.Clear();
>     foreach (Layoutable child in Children)
>     {
>         if (child == null)
>         {
>             continue;
>         }
> 
>         var node = _childGraph.AddNode(child);
> 
>         node.AlignLeftWithNode = _childGraph.AddLink(node, GetDependencyElement(AlignLeftWithProperty, child));
>         node.AlignTopWithNode = _childGraph.AddLink(node, GetDependencyElement(AlignTopWithProperty, child));
>         node.AlignRightWithNode = _childGraph.AddLink(node, GetDependencyElement(AlignRightWithProperty, child));
>         node.AlignBottomWithNode = _childGraph.AddLink(node, GetDependencyElement(AlignBottomWithProperty, child));
> 
>         node.LeftOfNode = _childGraph.AddLink(node, GetDependencyElement(LeftOfProperty, child));
>         node.AboveNode = _childGraph.AddLink(node, GetDependencyElement(AboveProperty, child));
>         node.RightOfNode = _childGraph.AddLink(node, GetDependencyElement(RightOfProperty, child));
>         node.BelowNode = _childGraph.AddLink(node, GetDependencyElement(BelowProperty, child));
> 
>         node.AlignHorizontalCenterWith = _childGraph.AddLink(node, GetDependencyElement(AlignHorizontalCenterWithProperty, child));
>         node.AlignVerticalCenterWith = _childGraph.AddLink(node, GetDependencyElement(AlignVerticalCenterWithProperty, child));
>     }
> 
>     _childGraph.Measure(availableSize); // <== measure first time
> 
>     _childGraph.Reset(false);  // <== reset
>     var calcWidth = Width.IsNaN() && (HorizontalAlignment != HorizontalAlignment.Stretch);
>     var calcHeight = Height.IsNaN() && (VerticalAlignment != VerticalAlignment.Stretch);
> 
>     var boundingSize = _childGraph.GetBoundingSize(calcWidth, calcHeight);
>     _childGraph.Reset();  // <== reset
>     _childGraph.Measure(boundingSize);  // <== measure second time
>     
>     return boundingSize;
> }
> ```

Ported from: https://github.com/HandyOrg/HandyControl/blob/master/src/Shared/HandyControl_Shared/Controls/Panel/RelativePanel.cs#L220-L228

The reset call has an argument and has different behavior.

**Comment by danwalmsley** [comment]
@byme8 any chance to add a unit test here? 

https://github.com/AvaloniaUI/Avalonia/blob/master/tests/Avalonia.Controls.UnitTests/RelativePanelTests.cs

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0023221-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by byme8** [comment]
> @byme8 any chance to add a unit test here?
> 
> https://github.com/AvaloniaUI/Avalonia/blob/master/tests/Avalonia.Controls.UnitTests/RelativePanelTests.cs

I will add tests

**Comment by byme8** [comment]
@danwalmsley I added tests for a stretched relative panel.

**Review by maxkatz6 — APPROVED** [review]

**Review by danwalmsley — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0023266-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
