### PR TITLE
Set pull and pich gestures to handled when handled by handler

### LINKED ISSUE #10016: Pull gesture sample does not work for top and bottom rectangles
***ControlCatalog Gesture page***

When I touch the left and right rectangles and drag my finger in the opposite direction the green dot is pulled correctly. When do the same for the top and bottom rectangles it seems like the ScrollViewer takes precedence and moves the viewport instead of the green dots being pulled.

**Expected behavior**

I would expect that a control (rectangles and dots) that has touch/gesture behavior would have precedence over a scroll viewer that contains them. Pulling the rectangles should not affect the ScrollViewer.

**Screenshots**

PullGesture

**Desktop (please complete the following information):**

- OS: Windows 10 
- Build/Version: 19044.2486 / 21H2

**Additional context**

I'm using a Dell S2240T touch screen.

### PR DESCRIPTION
**Pull request by emmauss**
## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Fixed issues
Fixes #10016

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0028846-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by wieslawsoltes** [comment]
I still can not get this working:
```xaml
  <RefreshContainer Name="Refresh"
                    HorizontalAlignment="Stretch"
                    VerticalAlignment="Stretch"
                    PullDirection="TopToBottom"
                    RefreshRequested="Refresh_OnRefreshRequested">
    <Border Background="Red" />
  </RefreshContainer>
```
I used also ListBox but did not work too.

**Comment by emmauss** [comment]
> I still can not get this working:
> 
> ```
>   <RefreshContainer Name="Refresh"
>                     HorizontalAlignment="Stretch"
>                     VerticalAlignment="Stretch"
>                     PullDirection="TopToBottom"
>                     RefreshRequested="Refresh_OnRefreshRequested">
>     <Border Background="Red" />
>   </RefreshContainer>
> ```
> 
> I used also ListBox but did not work too.

The content of a refresh container must be a scrollviewer, or a control that has a scrollviewer

**Comment by wieslawsoltes** [comment]
> > I still can not get this working:
> > ```
> >   <RefreshContainer Name="Refresh"
> >                     HorizontalAlignment="Stretch"
> >                     VerticalAlignment="Stretch"
> >                     PullDirection="TopToBottom"
> >                     RefreshRequested="Refresh_OnRefreshRequested">
> >     <Border Background="Red" />
> >   </RefreshContainer>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I used also ListBox but did not work too.
> 
> The content of a refresh container must be a scrollviewer, or a control that has a scrollviewer

I could not get it working with ListBox

**Comment by emmauss** [comment]
> > > I still can not get this working:
> > > ```
> > >   <RefreshContainer Name="Refresh"
> > >                     HorizontalAlignment="Stretch"
> > >                     VerticalAlignment="Stretch"
> > >                     PullDirection="TopToBottom"
> > >                     RefreshRequested="Refresh_OnRefreshRequested">
> > >     <Border Background="Red" />
> > >   </RefreshContainer>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I used also ListBox but did not work too.
> > 
> > 
> > The content of a refresh container must be a scrollviewer, or a control that has a scrollviewer
> 
> I could not get it working with ListBox

If you are using mouse, it won't trigger pulls. Pulling only works with touch and pen.

**Comment by wieslawsoltes** [comment]
> > > > I still can not get this working:
> > > > ```
> > > >   <RefreshContainer Name="Refresh"
> > > >                     HorizontalAlignment="Stretch"
> > > >                     VerticalAlignment="Stretch"
> > > >                     PullDirection="TopToBottom"
> > > >                     RefreshRequested="Refresh_OnRefreshRequested">
> > > >     <Border Background="Red" />
> > > >   </RefreshContainer>
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > I used also ListBox but did not work too.
> > > 
> > > 
> > > The content of a refresh container must be a scrollviewer, or a control that has a scrollviewer
> > 
> > 
> > I could not get it working with ListBox
> 
> If you are using mouse, it won't trigger pulls. Pulling only works with touch and pen.

I have used touch input.

**Comment by emmauss** [comment]
> 

Does this work for you? 
```xaml
  <RefreshContainer Name="Refresh"
                    HorizontalAlignment="Stretch"
                    VerticalAlignment="Stretch"
                    PullDirection="TopToBottom">
    <ListBox HorizontalAlignment="Stretch" VerticalAlignment="Stretch" MinHeight="400"/>
  </RefreshContainer>
```

**Comment by wieslawsoltes** [comment]
> > 
> 
> Does this work for you?
> 
> ```
>   <RefreshContainer Name="Refresh"
>                     HorizontalAlignment="Stretch"
>                     VerticalAlignment="Stretch"
>                     PullDirection="TopToBottom">
>     <ListBox HorizontalAlignment="Stretch" VerticalAlignment="Stretch" MinHeight="400"/>
>   </RefreshContainer>
> ```

Doesn't work for me. No idea what might be wrong.

**Comment by wieslawsoltes** [comment]
> > 
> 
> Does this work for you?
> 
> ```
>   <RefreshContainer Name="Refresh"
>                     HorizontalAlignment="Stretch"
>                     VerticalAlignment="Stretch"
>                     PullDirection="TopToBottom">
>     <ListBox HorizontalAlignment="Stretch" VerticalAlignment="Stretch" MinHeight="400"/>
>   </RefreshContainer>
> ```

I am pretty sure touch and other gestures work on that machine.

**Comment by wieslawsoltes** [comment]
@emmauss 

https://user-images.githubusercontent.com/2297442/213802771-b8c0eca0-2a65-49d9-a5d1-8b4fc57e17d4.mp4

**Comment by wieslawsoltes** [comment]
@emmauss I have made some test on that machine and seems the pull recogniser on it only detects top to bottom one even if other pull gesture directions have been done:
```
  <UserControl.GestureRecognizers>
    <PullGestureRecognizer PullDirection="TopToBottom"/>
    <PullGestureRecognizer PullDirection="BottomToTop"/>
    <PullGestureRecognizer PullDirection="RightToLeft"/>
    <PullGestureRecognizer PullDirection="LeftToRight"/>
  </UserControl.GestureRecognizers>
```
```
        AddHandler(Gestures.PullGestureEvent, OnPullGesture);
        AddHandler(Gestures.PullGestureEndedEvent, PullGestureEnded);
```
```
    private void OnPullGesture(object? sender, PullGestureEventArgs e)
    {
        Console.WriteLine($"PullGesture {e.Id} {e.PullDirection} {e.Delta}");
    }

    private void PullGestureEnded(object? sender, PullGestureEndedEventArgs e)
    {
        Console.WriteLine($"PullGestureEnded {e.Id} {e.PullDirection}");
    }
```

```
PullGesture 1 TopToBottom 0, 0
PullGesture 1 TopToBottom 0, 0
PullGesture 1 TopToBottom 0, 0
PullGesture 1 TopToBottom 0, 0
PullGesture 1 TopToBottom 0, 0
PullGesture 1 TopToBottom 0, 0
PullGesture 1 TopToBottom 0, 0
PullGesture 1 TopToBottom 0, 0
PullGesture 1 TopToBottom 0, 0
PullGesture 1 TopToBottom 0, 0
PullGesture 1 TopToBottom 0, 0
PullGesture 1 TopToBottom 0, 0
PullGesture 1 TopToBottom 0, 0
PullGesture 1 TopToBottom 0, 0
PullGesture 1 TopToBottom 0, 0
PullGesture 1 TopToBottom 0, 0
PullGesture 1 TopToBottom 0, 0.7999999999999972
PullGesture 1 TopToBottom 0, 0.7999999999999972
PullGesture 1 TopToBottom 0, 1.6000000000000014
PullGesture 1 TopToBottom 0, 1.6000000000000014
PullGesture 1 TopToBottom 0, 1.6000000000000014
PullGesture 1 TopToBottom 0, 1.6000000000000014
PullGesture 1 TopToBottom 0, 2.3999999999999986
PullGesture 1 TopToBottom 0, 1.6000000000000014
PullGesture 1 TopToBottom 0, 1.6000000000000014
PullGesture 1 TopToBottom 0, 1.6000000000000014
PullGesture 1 TopToBottom 0, 0.7999999999999972
PullGesture 1 TopToBottom 0, 0
PullGestureEnded 1 TopToBottom
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0.8000000000000043
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0
PullGesture 2 TopToBottom 0, 0.8000000000000043
PullGesture 2 TopToBottom 0, 1.6000000000000014
PullGesture 2 TopToBottom 0, 1.6000000000000014
PullGesture 2 TopToBottom 0, 1.6000000000000014
PullGesture 2 TopToBottom 0, 1.6000000000000014
PullGesture 2 TopToBottom 0, 1.6000000000000014
PullGesture 2 TopToBottom 0, 1.6000000000000014
PullGesture 2 TopToBottom 0, 1.6000000000000014
PullGesture 2 TopToBottom 0, 2.3999999999999986
PullGesture 2 TopToBottom 0, 2.3999999999999986
PullGestureEnded 2 TopToBottom
PullGesture 3 TopToBottom 0, 0.7999999999999972
PullGesture 3 TopToBottom 0, 0.7999999999999972
PullGesture 3 TopToBottom 0, 1.6000000000000014
PullGesture 3 TopToBottom 0, 0.7999999999999972
PullGesture 3 TopToBottom 0, 0.7999999999999972
PullGesture 3 TopToBottom 0, 0
PullGesture 3 TopToBottom 0, 0
PullGesture 3 TopToBottom 0, 0
PullGesture 3 TopToBottom 0, 0
PullGesture 3 TopToBottom 0, 0
PullGesture 3 TopToBottom 0, 0
PullGesture 3 TopToBottom 0, 0
PullGesture 3 TopToBottom 0, 0
PullGesture 3 TopToBottom 0, 0
PullGesture 3 TopToBottom 0, 0
PullGesture 3 TopToBottom 0, 0
PullGesture 3 TopToBottom 0, 0
PullGesture 3 TopToBottom 0, 0
PullGesture 3 TopToBottom 0, 0
PullGesture 3 TopToBottom 0, 0
PullGesture 3 TopToBottom 0, 0
PullGesture 3 TopToBottom 0, 0
PullGesture 3 TopToBottom 0, 0
PullGestureEnded 3 TopToBottom
PullGesture 4 TopToBottom 0, 0
PullGesture 4 TopToBottom 0, 15.200000000000003
PullGesture 4 TopToBottom 0, 16.799999999999997
PullGesture 4 TopToBottom 0, 20.799999999999997
PullGesture 4 TopToBottom 0, 28.799999999999997
PullGesture 4 TopToBottom 0, 32
PullGesture 4 TopToBottom 0, 38.400000000000006
PullGesture 4 TopToBottom 0, 40.8
PullGesture 4 TopToBottom 0, 46.400000000000006
PullGesture 4 TopToBottom 0, 62.400000000000006
PullGesture 4 TopToBottom 0, 65.6
PullGesture 4 TopToBottom 0, 69.6
PullGesture 4 TopToBottom 0, 72.8
PullGesture 4 TopToBottom 0, 76
PullGesture 4 TopToBottom 0, 79.2
PullGesture 4 TopToBottom 0, 82.4
PullGesture 4 TopToBottom 0, 99.19999999999999
PullGesture 4 TopToBottom 0, 99.19999999999999
PullGesture 4 TopToBottom 0, 99.19999999999999
PullGesture 4 TopToBottom 0, 102.4
PullGesture 4 TopToBottom 0, 109.6
PullGesture 4 TopToBottom 0, 136
PullGesture 4 TopToBottom 0, 148
PullGesture 4 TopToBottom 0, 176.8
PullGesture 4 TopToBottom 0, 199.2
PullGesture 4 TopToBottom 0, 220.8
PullGesture 4 TopToBottom 0, 220.8
PullGesture 4 TopToBottom 0, 220.8
PullGesture 4 TopToBottom 0, 224.8
PullGesture 4 TopToBottom 0, 235.2
PullGesture 4 TopToBottom 0, 269.6
PullGesture 4 TopToBottom 0, 289.6
PullGesture 4 TopToBottom 0, 309.6
PullGesture 4 TopToBottom 0, 328.8
PullGesture 4 TopToBottom 0, 348.8
PullGesture 4 TopToBottom 0, 368.8
PullGesture 4 TopToBottom 0, 400
PullGesture 4 TopToBottom 0, 440.8
PullGesture 4 TopToBottom 0, 456
PullGesture 4 TopToBottom 0, 472
PullGesture 4 TopToBottom 0, 480.79999999999995
PullGesture 4 TopToBottom 0, 482.4
PullGesture 4 TopToBottom 0, 487.20000000000005
PullGesture 4 TopToBottom 0, 503.20000000000005
PullGesture 4 TopToBottom 0, 514.4
PullGesture 4 TopToBottom 0, 516
PullGesture 4 TopToBottom 0, 518.4
PullGesture 4 TopToBottom 0, 520.8
PullGesture 4 TopToBottom 0, 522.4
PullGesture 4 TopToBottom 0, 523.2
PullGesture 4 TopToBottom 0, 527.2
PullGesture 4 TopToBottom 0, 535.2
PullGesture 4 TopToBottom 0, 540
PullGesture 4 TopToBottom 0, 542.4
PullGesture 4 TopToBottom 0, 544.8
PullGesture 4 TopToBottom 0, 547.2
PullGesture 4 TopToBottom 0, 554.4
PullGesture 4 TopToBottom 0, 566.4
PullGesture 4 TopToBottom 0, 572.8
PullGestureEnded 4 TopToBottom
```

**Comment by emmauss** [comment]
With this
```xaml
<UserControl x:Class="MobileSandbox.MainView"
             xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mobileSandbox="using:MobileSandbox"
             Background="Transparent"
             x:DataType="mobileSandbox:MainView">
  <UserControl.GestureRecognizers>
    <PullGestureRecognizer PullDirection="TopToBottom"/>
    <PullGestureRecognizer PullDirection="BottomToTop"/>
    <PullGestureRecognizer PullDirection="RightToLeft"/>
    <PullGestureRecognizer PullDirection="LeftToRight"/>
  </UserControl.GestureRecognizers>
</UserControl>
```
And the handlers you set, all the recognizers work with this branch.

**Comment by wieslawsoltes** [comment]
> With this
> 
> ```
> <UserControl x:Class="MobileSandbox.MainView"
>              xmlns="https://github.com/avaloniaui"
>              xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
>              xmlns:mobileSandbox="using:MobileSandbox"
>              Background="Transparent"
>              x:DataType="mobileSandbox:MainView">
>   <UserControl.GestureRecognizers>
>     <PullGestureRecognizer PullDirection="TopToBottom"/>
>     <PullGestureRecognizer PullDirection="BottomToTop"/>
>     <PullGestureRecognizer PullDirection="RightToLeft"/>
>     <PullGestureRecognizer PullDirection="LeftToRight"/>
>   </UserControl.GestureRecognizers>
> </UserControl>
> ```
> 
> And the handlers you set, all the recognizers work with this branch. Log: https://pastebin.com/FQ5xiRk7

I am using this branch, maybe this is specific to my macine setup.

**Comment by wieslawsoltes** [comment]
> With this
> 
> ```
> <UserControl x:Class="MobileSandbox.MainView"
>              xmlns="https://github.com/avaloniaui"
>              xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
>              xmlns:mobileSandbox="using:MobileSandbox"
>              Background="Transparent"
>              x:DataType="mobileSandbox:MainView">
>   <UserControl.GestureRecognizers>
>     <PullGestureRecognizer PullDirection="TopToBottom"/>
>     <PullGestureRecognizer PullDirection="BottomToTop"/>
>     <PullGestureRecognizer PullDirection="RightToLeft"/>
>     <PullGestureRecognizer PullDirection="LeftToRight"/>
>   </UserControl.GestureRecognizers>
> </UserControl>
> ```
> 
> And the handlers you set, all the recognizers work with this branch. Log: [pastebin.com/FQ5xiRk7](https://pastebin.com/FQ5xiRk7)

Ah sorry for confusion I have copied gestures page code from master and not from this PR so it obviously did not work, not the demo works.

**Comment by wieslawsoltes** [comment]
@emmauss Shouldn't we mark event as handled here ?

https://github.com/AvaloniaUI/Avalonia/blob/18a08938dcdb25c975bc54d6856b7b6a7a762ec7/src/Avalonia.Controls/PullToRefresh/RefreshInfoProvider.cs#L89-L106

same as in demo:

https://github.com/AvaloniaUI/Avalonia/pull/10027/files#diff-8c522dbed43e2b932a3ad7fe60757044d65879bdfacbd9b2f80623c59301dfedR191

**Comment by wieslawsoltes** [comment]
@emmauss So with empty list pull gesture works with this PR, but not with items (see my above comment with not setting e.Handled).

**Comment by wieslawsoltes** [comment]
@emmauss Another annoying thing is that we limit the area where pull gesture is detected, I think entire bounds should be taken into account:
https://github.com/AvaloniaUI/Avalonia/blob/1cc29c7e8d24c0d326c741f0488c92b95ac6b718/src/Avalonia.Base/Input/GestureRecognizers/PullGestureRecognizer.cs#L112

**Review by wieslawsoltes — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0029011-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0029016-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Pull request merged**
