### PR TITLE
feat(Build): Add 3 retry when the LeakTests fails

### PR DESCRIPTION
**Pull request by workgroupengineering**
## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

### CODE REVIEW

**Comment by rstm-sf** [comment]
It would be nice to add that this is a hack for sometimes failing tests

**Comment by jmacato** [comment]
I do wonder if there's a less hacky way of doing leak tests

**Comment by workgroupengineering** [comment]
From the test I did on the PR # 6549, the test fails because it cannot open the communication between the testadapter and dotMemory. I speculate it's due to pipeline overload.

**Review by grokys — APPROVED** [review]
LGTM, lets see if this makes it more stable.

**Pull request merged**
