### PR TITLE
Fix for render cycle crash when RenderTransform contains invalid values.

### LINKED ISSUE #3653: Animations can cause entire window to become black/transparent
## Development Environment

* Avalonia 0.9.3
* Not using ReactiveUI
* Windows 10 OR macOS 14 (presumably Linux, too, but untested)

## Bug Description

Under certain animation conditions, the entire window will become black or transparent _except_ for where the animation is taking place.

Windows:

black

macOS:

Screen Shot 2020-03-10 at 11 06 59 AM

## How to Replicate

Clone https://github.com/Deadpikle/AvaloniaProgressRing/tree/bug/black-screen and start the sample project. The only difference between this branch and `master` is that the animation `PlaybackDirection` was set to `Normal`. I was able to make it happen in other circumstances too, but didn't write down what those were. (sorry!)

Edit: Have updated the sample for a smaller test case -- only one of the circles will animate now.

Thanks!

### PR DESCRIPTION
**Pull request by jmacato**
## What does the pull request do?

This "fixes" the issue when the rendering subsystem gets a matrix from RenderTransform that contains `double.NaN` or infinities and crashes the whole scene.
 
## How was the solution implemented (if it's not obvious)?

It checks `RenderTransform`'s matrix determinant and when it's either a `NaN` or infinite then it logs the anomaly and returns.

## Fixed issues
Also fixes #3653 but #3836 addresses the root cause.
Also could fix https://github.com/zkSNACKs/WalletWasabi/issues/3500 but it needs to be tested.

### CODE REVIEW

**Comment by grokys** [comment]
A unit test would be useful here to prevent the problem from re-occuring.

**Comment by MarchingCube** [comment]
I also wonder what is the perf impact here for initial render of a complex graph. Since now we have to calculate determinant for every node plus it attempts to retrieve logger as well.

**Comment by Gillibald** [comment]
NaN and Infinity both are invalid values and should never be part of a transform matrix. Validating this in a hot path isn't an good idea. Just produce sain values.

**Comment by jmacato** [comment]
> I also wonder what is the perf impact here for initial render of a complex graph. Since now we have to calculate determinant for every node plus it attempts to retrieve logger as well.

Yeah, not sure where else in the render chain would it be better to have matrix checks....

**Comment by Gillibald** [comment]
You just don't have them at least not in release mode

**Comment by MarchingCube** [comment]
TBH no renderer has such checks in release builds since as @Gillibald said - user should provide valid and sane data. Doing such things in the renderer to fix apps that are broken is not the best approach, especially if that regresses 99% of well behaved apps.

**Comment by danwalmsley** [comment]
> TBH no renderer has such checks in release builds since as @Gillibald said - user should provide valid and sane data. Doing such things in the renderer to fix apps that are broken is not the best approach, especially if that regresses 99% of well behaved apps.

definately, I wonder if the error can be caught when the user tries to set an invalid value and an exception thrown 

or 

when a user tries to set nan or infinity, its logged and ignored?

**Comment by grokys** [comment]
I agree - I think we need to prevent this state getting to the renderer. Should I close this?

**Comment by jmacato** [comment]
> I agree - I think we need to prevent this state getting to the renderer. Should I close this?

I wonder where can we check those invalid values?

**Pull request closed without merging**
