### PR TITLE
Set window margin to 0 WinUiComp is used - issue #8316

### LINKED ISSUE #8316: Resizing a Window that has ExtendClientAreaToDecorationsHint="True" shows white strips on Windows
**Describe the bug**
As soon as ExtendClientAreaToDecorationsHint="True" is set on a window, a white strip appears when resizing. This is disturbing for black-theme applications.

Happens on Windows 11 (and probably others). I suspect Windows chrome at work here.

**To Reproduce**

1. Create an empty window
2. Add Background="Black" to the window
3. Add ExtendClientAreaToDecorationsHint="True" to the window
4. Debug, Resize the window and see the white strip (see screenshot for a gif demo)

**Expected behavior**
The resize should not flicker white, but be of the same color as the Window background.

**Screenshots**
resize flicker

**Desktop (please complete the following information):**

- OS: Windows 11
- Version 0.10.5

**Additional context**

### PR DESCRIPTION
**Pull request by Tetedeiench**
## What does the pull request do?
This sets the default window margin on Windows using WinUIComp to 0 to avoid artefacts when resizing the window with ExtendClientAreaToDecorationsHint="true" .

This avoids graphic artefacts, especially visible when using dark themes, as resizing will draw a white background.

Using a margin of 0 will make the background transparent, and thus remove the visual artefact.

See issue #8316 .

## What is the current behavior?
The window margin is always set to 1

## What is the updated/expected behavior with this PR?
If window margin will be set to 0 if WinUIComp is used

## Checklist

- [ ] Added unit tests (if possible)? Not possible
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Breaking changes
None

## Obsoletions / Deprecations
None

## Fixed issues
Fixed #8316

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=8393) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=8393) before we can accept your contribution.<br/><br/>:x: Tetedeiench [sign now](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=8393)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/AvaloniaUI/Avalonia?pullRequest=8393) it.</sub>

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0021384-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]
Tested on window resizing with and without extended client area. Seems to work just fine.
In case of any problem, will revert or revisit.

**Comment by maxkatz6** [comment]
@Tetedeiench could you sign the CLA?

**Comment by Tetedeiench** [comment]
@maxkatz6 done !

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0021391-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by HendrikMennen** [comment]
This PR seems to to remove the Windows 11 rounded corners entirely, which is not good in my opinion.

**Pull request merged**
