### PR TITLE
WIP: DataGrid control

### PR DESCRIPTION
**Pull request by sdoroff**
This is a port of the DataGrid from the Silverlight Toolkit
It's still in the early stages of development, many features are not yet implemented, and the code is not in a particularly pretty state, with many commented out methods that will be cleaned up later. I'm making the pull request now in hopes of using it to stage API discussions that I need some input on.

### CODE REVIEW

**Comment by danwalmsley** [comment]
@sdoroff very nice! I will have a play around in the next few days, see how it handles data binding, etc.

Does it support data virtualization?

**Comment by sdoroff** [comment]
@danwalmsley - Cells are generated as needed, so virtualization should be possible.

**Comment by sdoroff** [comment]
Where should this code live? 
I'm leaning towards a separate project within the Avalonia repository.
If this is made a separate, optional, assembly/nuget package, how does that affect themeing? Is there a mechanism for the automatic discovery of style assemblies or would it have to be added as a `StyleInclude`?

**Review by sdoroff — COMMENTED** [review]
Is there a downside to adding this method? Will it work as intended?

**Comment by sdoroff** [comment]
To make certain functionality work nicely, I need access to the properties on `Avalonia.Markup.Xaml.Data.Binding`. Mainly to inspect the binding path. There are a couple of options:

1. If we move this into a new project we can just reference `Avalonia.Markup.Xaml`
2. We can create a `BindingBase` class in `Avalonia.Base` that defines the properties

Is there a strong preference between the two? Also, to make auto-generated columns work, I'll need a way to create `Avalonia.Markup.Xaml.Data.Binding` from within the control.

**Comment by sdoroff** [comment]
Related to moving the control to a separate project, would there be a downside to allowing `Avalonia.Markup.Xaml.PortableXaml.AvaloniaDefaultTypeConverters` to check for the `System.ComponentModel.TypeConverterAttribute` allowing for new `TypeConverter`s to be registered?

**Review by sdoroff — COMMENTED** [review]
`CollectionView` seems like a necessary evil to make certain functionality possible (sorting and grouping). I have some ideas about how to make the API nicer to work with from code. But I'm certainly open to ideas about the how the data interfaces could work.

**Comment by grokys** [comment]
@sdoroff @kekekeks @jkoritzinsky @danwalmsley @wieslawsoltes 

What you you say we create a `AvaloniaUI/Avalonia.Control.DataGrid` repository and make @sdoroff the maintainer of it?

**Comment by jkoritzinsky** [comment]
Sure! I think we can do that for a control like DataGrid.

**Comment by grokys** [comment]
> Related to moving the control to a separate project, would there be a downside to allowing Avalonia.Markup.Xaml.PortableXaml.AvaloniaDefaultTypeConverters to check for the System.ComponentModel.TypeConverterAttribute allowing for new TypeConverters to be registered?

Actually, that reminds me: we need to fix `TypeConverter`s to use `TypeConverterAttribute` in core Avalonia - the reason it was done way the way was done is that `TypeConverter` wasn't present in the PCL profile we were using. Now we're on netstandard it shouldn't be a problem.

**Comment by grokys** [comment]
@sdoroff does this sound good to you? Would you like me to set up a `AvaloniaUI/DataGrid` repository for you?

> Related to moving the control to a separate project, would there be a downside to allowing Avalonia.Markup.Xaml.PortableXaml.AvaloniaDefaultTypeConverters to check for the System.ComponentModel.TypeConverterAttribute allowing for new TypeConverters to be registered?

On checking this, it does appear that `TypeConverterAttribute` should be supported already.

**Comment by grokys** [comment]
@sdoroff created here: https://github.com/AvaloniaUI/DataGrid. I've sent you an invite to be a maintainer of that repository.

**Comment by sdoroff** [comment]
A quick update: I've made a good amount of progress and, with some luck, should have a fully functional alpha ready by the end of the month. I'll push the code to the new repository then.

**Comment by sdoroff** [comment]
I had some questions regarding styles. The Silverlight implementation makes heavy use of Style typed properties that get set passed on to various sub-components (rows, cells, headers, etc) when the visual tree is generated. Many of the applications of this can be replicated with the Avalonia style selectors, with two important exceptions:

1) CellStyle - which is set on the DataGridColumn
Columns aren't actually part of the visual tree, they just explain how cells should be generated for each row, so selectors will not work. Column CellStyles are used for basic formatting (font, alignment, etc) and conditional formatting (eg negative values should have red backgrounds) through bindings in the style. Does anyone have any thoughts on how best to implement this in Avalonia? I'm leaning towards having a CellClasses property on the DataGridColumn that is copied over to the Cells Classes when it is created.

2) RowGroupHeaderStyles
When a DataGrid is displaying a grouped data source, the style of the group headers is determined through this collection of styles on the DataGrid. The depth (level of the subgroup) of determines the index within the collection to use. I have no idea how something like this should work in Avalonia. Does anyone have any clever ideas of how to replicate this functionality?

**Comment by jmacato** [comment]
Related Issue #1030

**Comment by jkoritzinsky** [comment]
Now that the WIP DataGrid code has been pushed to the AvaloniaUI/DataGrid repository, I'm going to close this PR.

**Pull request closed without merging**
