### PR TITLE
[perf] Improve performance of AvaloniaObject SetAndRaise method. 

### PR DESCRIPTION
**Pull request by MarchingCube**
## What does the pull request do?

Starts performance exploration for `AvaloniaObject.SetAndRaise`. I wish for this to start discussion about potential design changes, etc.

## What is the current behavior?

As many people noticed this method is quite heavy on the performance and can appear as hot spot in some benchmarks as well. I decided to run some simple benchmark to see what is the performance.
You can see it in the code but in a nutshell - create new `AvaloniaObject` and set it's property 100 times.

|               Method |      Mean |     Error |    StdDev | Ratio |   Gen 0 | Gen 1 | Gen 2 | Allocated |
|--------------------- |----------:|----------:|----------:|------:|--------:|------:|------:|----------:|
|  SetAndRaiseOriginal | 27.562 us | 0.3252 us | 0.3042 us |  1.00 | 70.0073 |     - |     - |  53.77 KB |
| SetAndRaiseOptimized |  5.662 us | 0.0308 us | 0.0288 us |  0.21 | 13.8168 |     - |     - |  10.62 KB |
|    SetAndRaiseSimple |  3.965 us | 0.0188 us | 0.0176 us |  0.14 | 13.4430 |     - |     - |  10.33 KB |

So not only this method takes quite some time (and `SetAndRaise` is called quite a lot in framework), but it allocates over 50KB to set 100 integers.

## What is the updated/expected behavior with this PR?

Run `DirectPropertyBenchmark` from `Avalonia.Benchmarks` project.

## How was the solution implemented (if it's not obvious)?

Reworked the deferred setter:
- moved the property value optimized list to a standalone class so I can use it for setters as well
- store properly typed deferred setters to avoid boxing allocations (before we had one `object` based setter, that internally had dictionary of setter statuses. I changed that to have one deferred setter per property, which basically flips the structure.)
- get rid of `SetAndRaise` variant that uses callbacks.
- did manual "inlining" pass to embed all the functions into main `SetAndNotify`, remove `SettingStatus` as it can be now embedded directly in a setter.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

## Fixed issues

cc: @grokys @jkoritzinsky

### CODE REVIEW

**Comment by jkoritzinsky** [comment]
The updates look good to me! I'd say if we need to have two versions because of usage differences (with one being a fast path) then that's ok. When I wrote this, I was just glad I was able to construct a state machine that did the right thing. I didn't really focus on performance at the time. Once this is marked "Ready for review" then I'll take another pass.

**Comment by MarchingCube** [comment]
@jkoritzinsky I did a bit more aggressive changes now, this increased perf again, and for simple case of 1 direct property it is 4 times faster than current implementation. It also allocates 5 times less and triggers less GC. I think general memory footprint should stay almost the same, not sure if that matters that much for this, as it allows to save quite some memory bandwidth during runtime.

**Comment by MarchingCube** [comment]
I will rework this to remove `SetAndRaise` that take a callback.

**Comment by MarchingCube** [comment]
@jkoritzinsky Please take a look when you have a moment. Since @grokys removed a need for `SetAndRaise` taking a callback I was able to streamline that code even further. Now performance of our direct property fast path is quite close to just setting that value directly and raising manually (simple case in benchmarks).

I still kept old implementation for comparison and benchmark reasons, but if we are happy with this implementation I will remove old one.

**Review by jkoritzinsky — APPROVED** [review]
LGTM! Let's remove the old implementation and then merge!

**Comment by MarchingCube** [comment]
Oh, it still seems we use callback overload in `PriorityValue.UpdateValue`. Will take a look what I can do there.

**Comment by MarchingCube** [comment]
In the end I had to bring back support for callbacks in `DeferredSetter`, but I decided to give it completely separate path, as I don't want to regress direct properties perf.

Still, I guess I also reduced memory footprint and perf of non-direct properties by caching callbacks and reducing callback nesting.

I didn't benchmark non-direct properties, as I don't have a setup for it.

**Comment by MarchingCube** [comment]
@grokys @jkoritzinsky Removed old implementation and fixed usage in `PriorityValue` - all tests are green now as well.

**Review by jkoritzinsky — APPROVED** [review]

**Pull request merged**
