### PR TITLE
WIP: Add color font support for Direct2D1 backend

### PR DESCRIPTION
**Pull request by Gillibald**
- What does the pull request do?
It enables support for color fonts with Direct2D1 backend.
- What is the current behavior?
The current implementation uses TextRenderer to render texts and color fonts aren't enabled because of that.
- What is the updated/expected behavior with this PR?
When it is possible to render a colored glyph (embedded Bitmap) the render backend uses that glyph. This also works if you use a char that is not supported by your font family. The render backend automaticly tries to find a glyph that is available in other font familes. Emojis everywhere jay :)
- How was the solution implemented (if it's not obvious)?
AvaloniaTextRenderer was removed and instead a DrawText runs on the render target with enabled color font feature.

### CODE REVIEW

**Comment by nc4rrillo** [comment]
I think this breaks formatted text spans. In the existing code, the Brush wrapper is set and in the `AvaloniaTextRenderer` the `clientDrawingEffect` is used.

You can check by highlighting text in a textbox and seeing if the foreground changes to white.

**Comment by nc4rrillo** [comment]
I think you're going to need to use `TranslateColorGlyphRun` and call the corresponding `DrawColorBitmapGlyphRun` and `DrawSvgGlyphRun`

If `DWRITE_E_NOCOLOR` is returned you can fallback to `DrawGlyphRun`

**Comment by Gillibald** [comment]
The current implementation doesnt call DrawGlyphRun so just Code from the base implementation is used. That makes the class redundant. Or am i missing something? You can check that yourself in the current master.

**Comment by nc4rrillo** [comment]
If you look at `FormattedTextImpl` on [line 47](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Windows/Avalonia.Direct2D1/Media/FormattedTextImpl.cs#L47) it calls `ApplySpan`.
`ApplySpan` calls `SetDrawingEffect` with a `BrushWrapper` (which inherits from `ComObject` on the Text Layout object on [line 103](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Windows/Avalonia.Direct2D1/Media/FormattedTextImpl.cs#L103)

In `AvaloniaTextRenderer` on [line 53](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Windows/Avalonia.Direct2D1/Media/AvaloniaTextRenderer.cs#L53) `CreateBrush` is called if `wrapper` is not null as a result of a cast to `BrushWrapper`

Just calling `DrawText` on the render target regresses on this point. The `DrawGlyphRun` functionality in `AvaloniaTextRenderer` calls `DrawGlyphRun` on the render target.

**Comment by Gillibald** [comment]
SharpDX doesn't support this scenario. ColorGlyphRunEnumerator isn't fully implemented and needs some fixing. Don't know what we can do about that.
https://github.com/sharpdx/SharpDX/issues/1012

**Comment by jmacato** [comment]
>When it is possible to render a colored glyph (embedded Bitmap) the render backend uses that glyph. This also works if you use a char that is not supported by your font family. The render backend automaticly tries to find a glyph that is available in other font familes. Emojis everywhere jay :)

Can the same thing be done with Skia on other platforms @Gillibald  ?

**Comment by Gillibald** [comment]
This implementation doesnt work because SharpDx is missing some marshaling code

**Comment by jkoritzinsky** [comment]
@Gillibald can you open an issue on SharpDX for the missing APIs? I'll take a stab at fixing the mappings for the next SharpDX version if I know what APIs I need to fix.

**Comment by Gillibald** [comment]
I will open an issue that describes what is missing.

**Comment by Gillibald** [comment]
There is already an Issue for the non functional API under https://github.com/sharpdx/SharpDX/issues/1012

**Comment by jkoritzinsky** [comment]
Ok. I'll take a look at sending in a PR to fix that.

**Comment by jkoritzinsky** [comment]
@Gillibald I've opened SharpDX/SharpDX#1038. Any other SharpDX bugs that need to be fixed for this PR?

**Comment by Gillibald** [comment]
Only https://github.com/sharpdx/SharpDX/issues/1034 is left

**Comment by jkoritzinsky** [comment]
@Gillibald SharpDX 4.2.0 is now released with the fixes we've talked about. Hopefully this PR won't end up blocked on any other dependencies of ours.

**Comment by Gillibald** [comment]
Looks like there is still something wrong with the marshaling code `var colorGlyphRun = colorGlyphRunEnumerator.CurrentRun;` just crashes

**Comment by Gillibald** [comment]
Exception thrown "Object reference not set to an instance of an object."
 ```
bei SharpDX.DirectWrite.ColorGlyphRunEnumerator.get_CurrentRun()
   bei Avalonia.Direct2D1.Media.AvaloniaTextRenderer.DrawGlyphRun(Object clientDrawingContext, Single baselineOriginX, Single baselineOriginY, MeasuringMode measuringMode, GlyphRun glyphRun, GlyphRunDescription glyphRunDescription, ComObject clientDrawingEffect)
```

**Comment by jkoritzinsky** [comment]
Can you turn off Just My Code and tell me what line in the property it's crashing on?

**Comment by Gillibald** [comment]
Will turn that off and have a look where it breaks. Thanks for giving me that hint

**Comment by Gillibald** [comment]
Running it without "Just My Code" doesn't give me more information. No idea how to debug this further.

**Comment by Gillibald** [comment]
I will close this for now. We will get color font support when we introduce our own text layout.

**Pull request closed without merging**
