### PR TITLE
Add new DropDownButton Control

### LINKED ISSUE #4960: Add DropDownButton porting over from WinUI
Would be great to add a DropDownButton to Avalonia porting over from WinUI. I'll do this myself if I get a thumbs-up from the core team.

 * https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.controls.dropdownbutton?view=winui-2.4

Comparison of button controls:

https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/buttons

### LINKED ISSUE #7839: TextBlock Not Vertical Centered By Default in ContentPresenter
**Describe the bug**

Text added to certain controls is not vertically centered by default. This is different from other XAML frameworks.

This bug applies specifically to controls that have a drop-down chevron such as `ComboBox` (which is correct), `SplitButton`, `ToggleSplitButton` and `DropDownButton`. With these controls, content should always be aligned with the chevron by default. Whether or not it should apply to `Button` is open for debate.

**To Reproduce**

The following XAML:

```xaml
        <Button IsEnabled="False" Height="80">Disabled</Button>
        <DropDownButton IsEnabled="False" Height="80">Disabled</DropDownButton>
```

Will produce:

image

Note that the following XAML will produce the correct, expected button with vertically centered text.

```xaml
<Button IsEnabled="False" Height="80">
  <TextBlock Text="Disabled" VerticalAlignment="Center" />
</Button>
```

**Expected behavior**

The default styles (templates) for related controls should set the `VerticalContentAlignment` of the `ContentPresenter` to Center. This is what is done for `ComboBox`.

**Screenshots**

Issue:

image

No Issue: (XAML Studio) Same behavior as UWP.

image

**Desktop (please complete the following information):**

- OS: Windows 10
- Version: (For Button Only) Master @ 65817edc980aad7c0f861382de1541b92a73fb36

**Additional context**

### PR DESCRIPTION
**Pull request by robloo**
## What does the pull request do?

Adds a new `DropDownButton` control following the ideas in UWP/WinUI. This closes #4960 and addresses #7839 for controls other than `Button` (controls with drop-down chevrons).

 - [DropDownButton Class in UWP/WinUI](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.dropdownbutton?view=winui-3.0)
 - [Buttons Docs from WinUI](https://docs.microsoft.com/en-us/windows/apps/design/controls/buttons#create-a-drop-down-button)
 - https://github.com/microsoft/microsoft-ui-xaml/tree/main/dev/DropDownButton

## What is the current behavior?

There is no `DropDownButton`

## What is the updated/expected behavior with this PR?

There is now a `DropDownButton` control. 
 - This control is most useful as a building block in other custom controls.
 - It standardizes the design and implementation for everyone. This helps developers and users.
 - It helps speed-up porting to Avalonia from existing UWP/WinUI code bases

image

## How was the solution implemented (if it's not obvious)?

 1. A new `DropDownButton` control is added deriving from `Button`
 2. `Button` was extended to better support flyout states and usability with derived controls
      - Added the ":flyout-open" Psuedoclass following SplitButton. This allows easier styling for apps using the DropDownButton.
      - Added overridable methods for OnFlyoutOpened and OnFlyoutClosed available to derived controls. This was done in the WinUI version of the control and makes sense as DropDownButton is used more as a primitive.
 3. Added `DropDownButton` to the ControlCatalog Buttons Page

## Additional Considerations

 - I debated whether or not to make the `DropDownButton` a primitive in Controls.Primitives. However, in the end I followed WinUI.
 - This is a foundational control for the ColorPicker.

## Checklist

- [ ] Added unit tests (if possible)?
- [x] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Breaking changes

None

## Obsoletions / Deprecations

None

## Fixed issues

 - Closes #4960 
 - Partially closes #7839

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019379-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019380-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by robloo** [comment]
Any ideas why the ContentPresenter isn't vertically centering text? I'm about ready to file another issue for this?



image

```xaml
        <DropDownButton IsEnabled="False" Height="80">Disabled</DropDownButton>
        <DropDownButton />
        <DropDownButton CornerRadius="8"
                        BorderBrush="Black"
                        BorderThickness="2"
                        Height="80">
          <Border Background="Teal"
                  Height="4"
                  Width="4" />
        </DropDownButton>
```

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019381-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019382-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019383-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by timunie** [comment]
Hi @robloo 

>  Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

I can pickup this in the same way I do for SplitButton and ToggleSplitButton. Tbh I think every new control should be documented. I'll open an issue in the docs. 

Happy coding
Tim

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019506-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019671-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
