### PR TITLE
Add DataGrid fluent Control Theme

### PR DESCRIPTION
**Pull request by maxkatz6**
See #7120 

Merge after [feature/7120-fluent-control-themes](https://github.com/AvaloniaUI/Avalonia/tree/feature/7120-fluent-control-themes)

### CODE REVIEW

**Comment by robloo** [comment]
Since DataGrid is already done, I'll look at this as an example and try to get ColorPicker updated tomorrow.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0022406-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by grokys — APPROVED** [review]
LGTM and fixes the problem with grouping chevrons I was seeing in master.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0022590-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
