### PR TITLE
Fix: Enable seamless forward and backward transition in VirtualizingCarouselPanel

### LINKED ISSUE #14115: Change calculation of "forward" flag in VirtualizingCarouselPanel
## Current Behaviour
The VirtualizingCarouselPanel currently does not behave like a real carousel when using a PageTransition. In the current implementation the transition is reversed when switching from the last item to the first one and when switching from the first one to the last. I would not expect this kind of behaviour. The transitions should only change when the switching direction is changed.

https://github.com/AvaloniaUI/Avalonia/assets/152692858/21f61e32-edf4-47be-b111-8c00a728275e

## Expected Behaviour
The transitions should behave like in a circular list (as a carousel is round). When the current item is the last item in the list and the next item ist the first item in the list the pagetransition should go forward (and not backward). The same should happen when the current item is the first one and the next item is the last one. In this case the transition should go backward (and not forward).
The user should be able to cycle through the list forward and backward seamlessly.

https://github.com/AvaloniaUI/Avalonia/assets/152692858/11945e16-abd3-471a-bce8-971b6a43b345

## Solution
To achieve this, the `VirtualizingCarouselPanel.ArrangeOverride` method should be as this:

```csharp
protected override Size ArrangeOverride(Size finalSize)
{
    var result = base.ArrangeOverride(finalSize);

    if (_transition is null &&
        _transitionFrom is not null &&
        _realized is { } to &&
        GetTransition() is { } transition)
    {
        _transition = new CancellationTokenSource();

        var forward = (_realizedIndex > _transitionFromIndex) || (_transitionFromIndex == Items.Count - 1 && _realizedIndex == 0);
        forward = forward && !(_transitionFromIndex == 0 && _realizedIndex == Items.Count - 1);
        
        transition.Start(_transitionFrom, to, forward, _transition.Token)
            .ContinueWith(TransitionFinished, TaskScheduler.FromCurrentSynchronizationContext());
    }

    return result;
}
```

### PR DESCRIPTION
**Pull request by LuckyGeorge1975**
## What does the pull request do?
The calculation of the 'forward' flag has been changed. The change only applies when using more than 2 items in the carousel. If using only 2 items the flag is calculated as before.

## What is the current behavior?
Currently the flag changes from forward to backward when transitioning from the last element to the first element in the item list and the flag changes from backward to forward when transitioning from the first item to the last item. The transition is not like a carousel but more like a linear stack.

## What is the updated/expected behavior with this PR?
The transition direction does not change when transitioning from the first or last item when using more than 2 items. The transition is now seamless.

## How was the solution implemented (if it's not obvious)?
When using more than 2 items it is checked if the `_transitionFromIndex` is the last one and the `_realizedIndex` is the first or if the `_transitionFromIndex` is the first and the `_realizedIndex` is the last.

## Checklist
- [x] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/avalonia-docs with user documentation

## Fixed issues
Fixes #14115

### CODE REVIEW

**Comment by LuckyGeorge1975** [comment]
@dotnet-policy-service agree

**Comment by LuckyGeorge1975** [comment]
There is currently no way to calculate the correct transition direction when using only 2 items. So the fix only applies when using more than 2 items in a carousel.

**Description**
When using only two items the panel does not know if the transition should be forward or backward when transitioning from index 1 to index 0.

**Comment by jp2masa** [comment]
Maybe the carousel should be reworked to work with deltas? I think that's the only way to get a circular behavior.

**Comment by LuckyGeorge1975** [comment]
@jp2masa 

Thought about it. But how would you calculate the delta direction if the user changes `SelectedItem` or `SelectedIndex` via DataBinding or programmatically? I'm currently thinking about a change to calculate the "shortest" distance between `_transitionFromIndex` and `_realizedIndex`. Imagine a carousel with 10 items and you want to transition from 2 to 9 - in that case the transition should go backward and not forward.

But this will not solve the issue when using only 2 items as you have no idea what the user really wants. The only way to make this work correctly is to make `SelectedItem` and `SelectedIndex` readonly and only allow transitions with the `Carousel.Next()` and `Carousel.Previous()` methods. But that change would cripple the control.

**Comment by jp2masa** [comment]
> The only way to make this work correctly is to make SelectedItem and SelectedIndex readonly and only allow transitions with the Carousel.Next() and Carousel.Previous() methods. But that change would cripple the control.

In my opinion, the carousel, being a circular control, should have readonly selection properties and some kind of `Move(int delta)` public method.

Anyway, I don't make decisions here, so someone from the core team will have to confirm what approach is preferred for the future.

**Review by maxkatz6 — APPROVED** [review]

**Pull request merged**
