### PR TITLE
Fix #8240: Automation cause memory leak

### LINKED ISSUE #8240: Memory leak in master branch (automation related?)
**Describe the bug**
The latest master branch (tested 0.10.999-cibuild0020870-beta https://github.com/AvaloniaUI/Avalonia/commit/cea6bc27a06f25b4f2d3a73d3411e904b1767e74) has a memory leak, probably related to Automation code.

Note: this is a regression from the current stable 0.10.x version (which doesn't have automation related modules).

**To Reproduce**
The repro is very simple - just add a button, press it and the button will not be freed anymore. 

1. Clone the repo: https://github.com/BAndysc/AvaloniaMenuLeak
2. Checkout branch `leak2`
3. Run the app
4. The top text shows managed used memory, in the beginning it is less than 3 MBs
5. Press the button Add control
6. This will spawn a control, that has a reference to 1GB byte array, so obviously the ram usage will rise up to 1 GB
7. Press Remove Control
8. GC will free the control and datacontext almost instantly, and it will go down to 3 MBs, so far so good.
9. Press Add control again
10. This time click the button 'Click me'
11. Press Remove control
12. Notice this time the memory usage doesn't drop. The control is not freed!

**Screenshots**
dotMemory screenshot:
image

**Desktop:**

- OS: Mac
- Version: 0.10.999-cibuild0020870-beta (it works fine on 0.10.14)

### PR DESCRIPTION
**Pull request by flexxxxer**
## What does the pull request do?
(Probably) Fixes #8240

## What is the current behavior?
Memory leak happens.

## What is the updated/expected behavior with this PR?
No memory leak.

## How was the solution implemented (if it's not obvious)?
TODO.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/avalonia-docs with user documentation

## Breaking changes
TODO.

## Obsoletions / Deprecations
TODO.

## Fixed issues
Fixes #8240

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0040557-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0040561-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0040602-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0040609-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0040613-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0040671-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0040798-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0040826-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by flexxxxer** [comment]
idk how to fix it

**Comment by flexxxxer** [comment]
hm maybe know

**Comment by timunie** [comment]
@flexxxxer we appreciate your tries a lot. But if you're stuck, feel free to leave it for someone else. I fully understand it.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0040836-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by maxkatz6** [comment]
@flexxxxer I am going to close this PR for now. Let me know if I should reopen it.

**Pull request closed without merging**
