### PR TITLE
[WIP] Implemented basic image filters for some drawing operations

### PR DESCRIPTION
**Pull request by kekekeks**
image-filter

```xml
          <Style Selector="Image">
              <Style.Animations>
                  <Animation Duration="0:0:2"
                             IterationCount="Infinite"
                             FillMode="None"
                             PlaybackDirection="AlternateReverse"
                             Easing="SineEaseInOut">
                      <KeyFrame Cue="0%">
                          <Setter Property="DropShadowImageFilter.Offset" Value="0,0"/>
                          <Setter Property="DropShadowImageFilter.Blur" Value="5,5"/>
                          <Setter Property="DropShadowImageFilter.Color" Value="Green"/>
                      </KeyFrame>
                      <KeyFrame Cue="100%">
                          <Setter Property="DropShadowImageFilter.Offset" Value="40,60"/>
                          <Setter Property="DropShadowImageFilter.Blur" Value="20,30"/>
                          <Setter Property="DropShadowImageFilter.Color" Value="Blue"/>
                      </KeyFrame>
                  </Animation>
              </Style.Animations>
          </Style>
```

See extra info in #2605

The basic idea is to have a way to apply a filter to a particular drawing operation instead of a while subtree (`box-shadow` CSS property does exactly that). We can extend the API to apply the filter to the entire subtree via drawing it in RTB first, but that won't play nicely with our current layering implementation.
So once we get our layers sorted out, we could have something like
```xml
<Control ImageFilter.AffectsSubtree="True">
     <Control.ImageFilter>
           <DropShadowImageFilter Offset="5,10" Color="Green"/>
     </Control.ImageFilter>
</Control>
```

I'm also considering to rename `ImageFilter` to `FillImageFilter`/`BackgroundImageFilter` since it's only supported for background fills.

We might implement `LayerImageFilter` later.

Note: This PR lacks Direct2D implementation.

### CODE REVIEW

**Comment by Sorien** [comment]
I can't test it right now but is it respecting ClipToBounds="True"? because as I remember these images were clipped when I tried to implement these effect.

**Comment by kekekeks** [comment]
Yes, it currently gets clipped to control bounds. If you want only content to be clipped, you need

```xml
<Border>
   <Border.ImageFilter>
      <DropShadowImageFilter Color="Red" Offset="10,10"/>
   </Border.ImageFilter>
   <Border ClipToBounds="True">
       <YourContent/>
   </Border>
</Border>

**Comment by kekekeks** [comment]
Unfortunately, the effect is only applied to Fill, not to Stroke. So stroked borders with transparent background don't drop any shadows.

**Comment by kekekeks** [comment]
Mkay, shadows for strokes can be implemented separately by drawing said stroke two times and applying SkMaskFilter when drawing the "shadow" part.

**Comment by kekekeks** [comment]
I think we need two separate properties: `FillEffect` and `StrokeEffect`. That way we can have shadows for text too.

**Comment by ameliadiedrich** [comment]
Any news regarding this feature ?

**Comment by danwalmsley** [comment]
closing due to inactivity.

**Comment by yankun** [comment]
Has this work been deprecated? Currently I'm in the absolute need for Paths to have a simple shadow.

**Comment by RayKoopa** [comment]
Also looking for this, my search for WPF`s
```xml
<Image ...>
    <Image.Effect>
        <BlurEffect Radius="20"/>
    </Image.Effect>
</Image>
```
led me here eventually, which doesn't seem possible in Avalonia at the moment, right?

**Comment by RayKoopa** [comment]
Thanks for letting me know! I'll probably not use it yet though as it has more code than any other part of this small app :D

**Pull request closed without merging**
