### PR TITLE
fix pointerover on mouse leaving window

### LINKED ISSUE #2946: :pointerover not disappearing when cursor leaves the window entirely
The title says it all.

Here's the simple test: https://pastebin.com/kLL0KHGa
To reproduce, hover the mouse over the menu, then move it to the left until it leaves the window. The menu won't disappear, although it is supposed to.

### PR DESCRIPTION
**Pull request by ahopper**
## What does the pull request do?

Fixes #2946

## What is the current behavior?

On windows on leaving the window with the mouse or clicking on the non client area `MouseDevice` is left believing the mouse is at position 0,0 so any styles that apply pointerover and occupy the top left of the window will remain triggered.

## How was the solution implemented (if it's not obvious)?

For WM_MOUSELEAVE -1,-1 is returned instead of 0,0 this windows message does not include mouse position.
For WM_NCLBUTTONDOWN etc the mouse position is now returned.
I tested the linux behaviour and it returns a position outside the client area for these actions

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

## Fixed issues

Fixes #2946

### CODE REVIEW

**Comment by kekekeks** [comment]
```xml
<Window ClipToBounds="False">
   <Canvas ClipToBounds="False">
       <Rectangle Canvas.Left="-10" Canvas.Top="-10" Width="100" Height="100" Fill="Red"/>
   </Canvas>
</Window>
```

Will the rectangle still have the :pointerover?

**Comment by ahopper** [comment]
Interesting point, on linux you just get 1 last mouse position once the mouse leaves which depends on how fast the mouse was moving when it left. So the situation is even more vague here.

**Comment by ahopper** [comment]
Just tried and pointerover is not set in this case (on windows anyway)

**Comment by ahopper** [comment]
Maybe as we don't get meaningful and consistent mouse position as the mouse exits across all platforms we should force it to be the same on all platforms, say (-1,-1).

**Comment by grokys** [comment]
How should we move forward on this PR? @kekekeks ?

**Comment by kekekeks** [comment]
I'd make the "current" position nullable

**Comment by ahopper** [comment]
if we go the nullable route what should happen with the obsolete IPointerDevice.GetPosition

**Comment by ahopper** [comment]
and https://github.com/AvaloniaUI/Avalonia/blob/53fa618eb112cc0fbe4283aa0b58f741a9ff1cd7/src/Avalonia.Controls/Primitives/PopupPositioning/IPopupPositioner.cs#L301-L302

**Comment by ahopper** [comment]
I'm not really sure where to go with this, most of the knock on effects of making the Position nullable affect things that are already marked obsolete. It does not seem like a good use of time to modify obsolete things and I don't have a clear enough view of the big picture to replace them with whatever the non obsolete replacements should be.  This pr, as is, fixes the immediate problem, perhaps the nullable position should be part of another pr to remove all the internally used obsolete pointer stuff?

**Comment by grokys** [comment]
Ok, that sounds like a plan to me, I'm 👍 if @kekekeks agrees.

**Comment by kekekeks** [comment]
Popups bound to the mouse pointer shouldn't be shown when said pointer is outside of the window.
So it would be a valid behavior to close the popup completely.

**Comment by kekekeks** [comment]
GetPosition could return `(-1, -1) for now

**Comment by ahopper** [comment]
I had a very quick go at implementing nullable Position, the biggest issue is that it breaks a number of tests to do with context menus and popups because the  test mouse does not work at a low enough level to set Position in MouseDevice (they were working by luck before). Happy to take it further but time is very short right now.

**Comment by ahopper** [comment]
I did look at alternatives for passing the mouse position to IPopupPositioner and wonder if it would be better to make whatever opens the popup to pass the position, for context menu this is easy (unless there is some keyboard way to open that I'm unaware of), for tooltips we would have to store mouse position ready for the timer event.

**Comment by grokys** [comment]
@ahopper what's the status on this? Is "GetPosition could return (-1, -1) for now" a no-go?

**Comment by ahopper** [comment]
@grokys sorry I just haven't had time to go further with this, I think making GetPosition return (-1,-1) with a nullable position creates further work without really fixing the issue.  I still think the pr as is solves the immediate issue (as the current behaviour is just wrong).

**Comment by kekekeks** [comment]
`(-1, -1)` *is* a hack, but it fixes the issue for *most* of the apps. I think we can merge it as is and  later incorporate an actual MouseDevice in the test mouse helper, so mouse position can be nullable.

Merging as is also allows us to merge this PR into 0.9 release branch, since that won't cause any breaking changes.

**Review by grokys — APPROVED** [review]
Ok then LGTM (Lets Get This Merged)!

**Pull request merged**
