### PR TITLE
API listing tracker

### PR DESCRIPTION
**Pull request by maxkatz6**
We use this PR to track any API changes between releases.

### CODE REVIEW

**Comment by tannergooding** [comment]
It's worth noting we're trying to remove GenAPI and rely on the built in Roslyn support where possible.

I really wouldn't recommend other projects taking a dependency on it and instead use the official built in support: <https://learn.microsoft.com/en-us/dotnet/standard/assembly/reference-assemblies#generating-reference-assemblies>

**Comment by tannergooding** [comment]
https://github.com/dotnet/arcade/issues/12009 covers the investigation and some of the plans around moving to a Roslyn based approach.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0028920-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by maxkatz6** [comment]
@tannergooding thanks for the recommendation!

As for now, we don't plan to use this tool to generate public ref assemblies.
This PR is primarily needed to get our public API surface which can be reviewed in this PR. We need to hide as much as possible members before the next major release. But also, we were thinking to use it as a convenient way to review breaking changes between minor releases. For the 0.10.x releases we used ApiCompat, but it's not so [convenient](https://github.com/ForNeVeR/wpf-math/issues/333#issuecomment-1399618737).

Roslyn based generator indeed sounds like something we should use in the future. But right now, the task seems to be limited to .NET 8 alpha only, also it's missing targets in the nuget package.
Instead, I tried new Microsoft.DotNet.GetAPI.Tool and it generated valid API for one of the assemblies which I pushed here (huge diff between MCCI and Roslyn based generators - https://github.com/AvaloniaUI/Avalonia/commit/4eb50be0d5e008d49e8380a72d97b46e50620f79). 
It seems there are expected differences how it understands some newer features (like readonly structs). But also interpreters enums as a class with const fields (BitmapBlendingMode as an example in the diff).

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0028930-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by ViktorHofer** [comment]
As one of the owners of `Microsoft.DotNet.GenAPI`, I just want to warn you on its usage. It's a non publicly shipping tool that will be discontinued and at some point deleted from arcade. As @tannergooding already mentioned, we are actively working on a Roslyn based GenAPI tooling to emit the public API contract for a given assembly. We haven't yet decided if we will productize it though. Also, that tooling isn't yet ready to be consumed as it's still missing some important features like synthesized fields, full qualified type names + bodies in a single line, nullability, etc.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0029970-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0034115-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0034474-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Pull request closed without merging**
