### PR TITLE
[Needs API review] Feature/icons

### PR DESCRIPTION
**Pull request by maxkatz6**
## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

## Fixed issues
See: https://github.com/AvaloniaUI/Avalonia/issues/4087

### CODE REVIEW

**Comment by robloo** [comment]
Should this be added to https://github.com/AvaloniaUI/Avalonia/discussions/5893 to help prioritize? This one (especially FontIcon) is pretty important in my opinion.

**Comment by maxkatz6** [comment]
@robloo personally I would like to have these icons build in the Avalonia core. With the very one reason - to keep relevant controls' API stricter.
BUT it should have been done from the beginning or at least way earlier.
Right now we have NativeMenuItem.Icon that is a Bitmap. We have Window.Icon that is also a Bitmap. In both cases we can only have raster images, and rendering controls into a bitmap is not so simple in this case, see https://github.com/AvaloniaUI/Avalonia/issues/4087#issuecomment-640199458. Also, it will introduce breaking changes.
We also have MenuItem.Icon that is an object. Moreover, currently MenuItem has pretty limited API to deal with toggle/radio menu items, so users actively use this Icon property just to add toggle/radio control in there. And while it's planned to introduce ToggleMenuItem/RadioMenuItem, changing Icon type to be more specific will be a breaking change, once again.

On other hand, we already have FontIcon control that is questionable for me, and to port more UWP controls we most likely will need these Icons anyway.

So, to justify these breaking changes we need pretty good reasons, and Avalonia core team does not really see any other advantages, but compatibility with UWP.

**Comment by robloo** [comment]
Well, that's what i was afraid of. The Icon story is pretty poor in Avalonia and it should really be generalized more as in UWP. There is no 1.0 release yet so in my opinion better late than never. All these controls should be taking an IconSource and not bitmaps. Avalonia should at least have an Icon interface that is more specific than a bitmap.

To export to a native menu there should be a mechanism to render the entire font icon to a bitmap (like in UWP where you can render a control to a bitmap) this is needed for drag/drop graphics anyway.

**Comment by beto-rodriguez** [comment]
@robloo I think icons can be easily implemented in Avalonia using SVG paths, and you could actually animate them (with some work). Practically all modern icons libraries expose their icons in SVG format, since Avalonia can run on SkiaSkarp, it is easy to render SVG icons.

**Comment by robloo** [comment]
@beto-rodriguez Thats an interesting idea. However, I would say there should actually be an SvgIcon to go along with the rest.

And the reason fonts were used instead of other vector graphics at the time was simply performance. You can't beat the performance of rendering a glyph from a font as its already so heavily optimized all the way through systems.

Now supporting Svg animations is nice too but the XAML UI frameworks seem to be moving to Lottie animations instead. These would go towards an animated icon. Everyone standardizing on lottie would help sharing design resources.

I'll think about all this more. I'm not saying UWP was perfect: IconSource vs IconElement, etc. Wasnt the best. However, having all the icon types readily available saved a lot of time rather than creating your own bitmaps.

For Avalonia, I firmly think it needs to be aware of 'icons' separately from 'bitmaps' in some way. Icons are a subset of bitmaps but for very specific usages: like menus and interface elements. This would make the API a lot cleaner and easier to use.

**Comment by maxkatz6** [comment]
@beto-rodriguez yep, unlikely UWP implementation, with this PR it is possible to create custom third-party IconElement with overriding IconElementTemplate. It might include various font implementations (Fluent icons, Segoe icons, FontAwesome icons etc.) and SVG as well. Let's say, https://github.com/wieslawsoltes/Svg.Skia/ repo can provide SvgIcon and SvgIconSource in Avalonia nuget package, and implementation will be simple.

**Comment by Gillibald** [comment]
Writing FontIcons to a Bitmap is a no brainer. We can switch to using a GlyphRun directly instead of a TextBlock. By using a GlyphRun it will be possible to export everything to a path.

**Comment by robloo** [comment]
I'm not sure where this PR is at -- hopefully it can still get past the core team and accepted into mainline.

> It might include various font implementations (Fluent icons, Segoe icons, FontAwesome icons etc.)

@maxkatz6 As you are aware, I have most of the tooling necessary now to generate various symbol fonts including those you mentioned. If ever you want to add them in some fashion -- even as another 3rd party Nuget -- just let me know. We should be able to automatically generate most of the code defining symbol icons and the font .ttf files as well. https://github.com/robloo/SymbolIconManager

**Comment by maxkatz6** [comment]
> I'm not sure where this PR is at -- hopefully it can still get past the core team and accepted into mainline.

I think we should at least remove ItemElementSource support from this PR and just propose to use ```<Template>``` where developer need to reuse same icon in multiple places. If it's possible. @wieslawsoltes you have worked with templates a lot recently, is it possible to declare something like below? Or do we need to do some changes in ControlPresenter?
```
    <Window.Resources>
        <Template x:Key="ImageTemplate">
            <Image/>
        </Template>
    </Window.Resources>
    <StackPanel>
        <Button Content="{StaticResource ImageTemplate}" />
        <Button Content="{StaticResource ImageTemplate}" />
    </StackPanel>
```

**Comment by robloo** [comment]
That's also really easy I think, don't re-render on each property change. Set a flag, batch property changes together and then render to a bitmap internally only every N milliseconds (likely a very high number to filter out animations entirely, 50ms or so). Put in the docs that animation of icons and their properties 
 used with NativeMenus isn't supported. If a dev tries this it will be a very poor animation and shouldn't affect performance. They'll read the docs or ask here why it isnt working and we can answer. Animations are not bitmaps. NativeMenu requires bitmaps.

I'm also assuming image animation would be done in a future AnimatedIcon which obviously wouldn't implement IBitmap and therefore couldn't be passed to the NativeMenu APIs.

**Comment by maxkatz6** [comment]
Closing it for now. Will come back after tasks with higher priority that I am planning to work during February

**Pull request closed without merging**
