### PR TITLE
Avoid per-frame allocations for renderer lock.

### PR DESCRIPTION
**Pull request by MarchingCube**
## What does the pull request do?

Part of my effort on reducing allocations in Avalonia.

## What is the current behavior?

Every time we obtain a lock we allocate a delegate and `AnonymousDisposable`.

image

## What is the updated/expected behavior with this PR?

Less dynamic allocations when obtaining renderer lock.

## How was the solution implemented (if it's not obvious)?

Implement new disposable that allows us to avoid allocating extra actions. We still have to create new instance every time to avoid potential API safety issues (people retaining disposable, etc.)

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

## Fixed issues

@kekekeks - what do you think? `AvaloniaNativeDeferredRendererLock` has similar pattern. In worst case scenario (double dispose protection is desired we could still cache the delgate, effectively halving allocation amount).

### CODE REVIEW

**Comment by kekekeks** [comment]
I'm not sure that removing this allocation justifies also removing API safety. On the other hand it's effectively an internal API, so we should be fine.

**Comment by MarchingCube** [comment]
@kekekeks As I said if you have doubts I could cache the delegate only and still allocate new disposable. This will remove some of the allocations.

**Comment by mstr2** [comment]
You could set an internal flag on the `LockDisposable` to indicate that is has been acquired, and clear the flag when it is disposed. If it is acquired while the flag is still present, you would throw an exception. This way, you would still get API safety.

**Comment by MarchingCube** [comment]
For now I decided to settle on creating new disposable each time, but without extra delegate. This way we have less heavy allocations and it will be clearer in profiler that we are dealing with lock allocations and not some random disposable.

**Review by kekekeks — APPROVED** [review]

**Comment by yingDev** [comment]
is it possible to optimize this ? 
https://github.com/AvaloniaUI/Avalonia/blob/e67bb01c5f000c9e1fd0726baf83f326a64fa7dc/src/Avalonia.Base/Reactive/LightweightObservableBase.cs#L133-L135

**Comment by Gillibald** [comment]
I guess ArrayPool could be used here

**Pull request merged**
