### PR TITLE
Android - Text Input fixes

### LINKED ISSUE #12067: [11.0.0] TextBox input broken on Android since RC2
**Describe the bug**

Input using device keyboard on a few tested devices (Samsung S21 android 13, Zebra TC21 android 11, Datalogic Skorpio x5 android 10, all using their default keyboards) is broken with digit input (maybe other inputs as well).

For example on the Zebra TC21 this is the result, when typing "1 2 3 4 5":

In the default TextBox character '5' is doubled.
In the password TextBox '3', '4' and '5' are doubled.
Results differ per type of device (the Samsung S21 in password textbox shows "234" as result).

image
(label shows content of password textbox)

**To Reproduce**

```xaml
    <StackPanel Margin="20" Spacing="20">
        <TextBox
            x:Name="text"
            HorizontalAlignment="Stretch"
            VerticalAlignment="Center" />
        <TextBox
            x:Name="pass"
            HorizontalAlignment="Stretch"
            VerticalAlignment="Center"
            PasswordChar="*" />

        <TextBlock HorizontalAlignment="Stretch" Text="{Binding #pass.Text}" />
    </StackPanel>
```

- OS: Android
- Version 10, 11 and 13 tested
- - Avalonia 11.0.0 RC2.2 and 11.0.0 -- problem does not exist on RC1 and before (it was a problem back in a preview in november last year)

### PR DESCRIPTION
**Pull request by emmauss**
## What does the pull request do?
This fixes various issues relating to text composing and typing on android.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Fixed issues
Fixes #12067

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0037991-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by robloo** [comment]
Two brand new control primitives and some fundamental differences in concept. This is an important PR to understand.

 1. PR description is very useful. Not only what changed by WHY and how it works.
 2. Nothing is documented. At least the new controls need to be fully XML documented (not just placeholder text).

Please document your code...

**Comment by emmauss** [comment]
> Two brand new control primitives and some fundamental differences in concept. This is an important PR to understand.
> 
>     1. PR description is very useful. Not only what changed by WHY and how it works.
> 
>     2. Nothing is documented. At least the new controls need to be fully XML documented (not just placeholder text).
> 
> 
> Please document your code...

Sorry, the commit history had some commits that were not supposed to be included in this branch. They were removed and those included the changes that are not related to android text fixes.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0037997-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by robloo** [comment]
Ah, ok, thanks for the clarification. That makes more sense.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0038012-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Review by danwalmsley — APPROVED** [review]

**Pull request merged**
