### PR TITLE
[WIP]: Add RenderOptions.Default

### PR DESCRIPTION
**Pull request by timunie**
## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0039238-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by timunie** [comment]
with the new, AttachedProperty-proposal I'm getting this in InteilisSense: 
image

Most likely because the analyzer doesn't know there is a Get and Set method available.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0039367-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by timunie** [comment]
closing in favor of https://github.com/AvaloniaUI/Avalonia/pull/13552

**Pull request closed without merging**
