### PR TITLE
fix: ItemTemplate is not applied on Menu/MenuItem

### LINKED ISSUE #9696: ItemTemplate is not applied on Menu/MenuItem
**Describe the bug**
ItemTemplate defined for Menu/MenuItem is not applied to their submenus. 

**To Reproduce**
image
Items is bound to a list of string in VM. In this case I would expect both menu item shows 123, but it still shows the original bound value.

**Expected behavior**
ItemTemplate should be applied to submenus as HeaderTemplate. 

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 11
- Version: 11.0-preview4

**Additional context**
Copy from discussion #9684

### PR DESCRIPTION
**Pull request by workgroupengineering**
## What is the current behavior?

ItemTemplate defined for Menu/MenuItem is not applied to their submenus.

## How was the solution implemented (if it's not obvious)?

Like discussion #10018 to apply ItemTemplate you have to write code like this:

```xaml
    <Menu Items="{Binding Columns}">
      <Menu.ItemContainerTheme>
        <ControlTheme TargetType="MenuItem" x:DataType="l:Column" BasedOn="{StaticResource {x:Type MenuItem}}">
          <Setter Property="Header" Value="{Binding}"/>
          <Setter Property="Background" Value="Red"/>
        </ControlTheme>
      </Menu.ItemContainerTheme>
      <Menu.ItemTemplate>
        <DataTemplate x:DataType="l:Column">
          <CheckBox IsChecked="{Binding IsVisible}"
                    Content="{Binding Header}"/>
        </DataTemplate>
      </Menu.ItemTemplate>
    </Menu>
```

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [x] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Fixed issues

Fixes #9696

### CODE REVIEW

**Comment by workgroupengineering** [comment]
@rabbitism Can you test in your scenario?

**Review by maxkatz6 — APPROVED** [review]

**Comment by rabbitism** [comment]
> @rabbitism Can you test in your scenario?

Thanks! I checked the theme quite a few times, can't believe I missed this part.

**Comment by rabbitism** [comment]
Actually this PR didn't fix my issue.
ItemTemplate should be applied to children, instead of the Header itself. 
When I set ItemTemplate to this parent, I would expect all it's submenus to show 123, instead of itself. 
image

**Comment by workgroupengineering** [comment]
> Actually this PR didn't fix my issue. ItemTemplate should be applied to children, instead of the Header itself. When I set ItemTemplate to this parent, I would expect all it's submenus to show 123, instead of itself. image

Instead of screenshot, can you share code here or make public repository?

**Comment by rabbitism** [comment]
@workgroupengineering I just copied over your change locally and tested in control catalog.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0028877-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Pull request merged**
