### PR TITLE
Add VirtualizingWrapPanel

### PR DESCRIPTION
**Pull request by emmauss**
## What does the pull request do?
Adds VirtualizingWrapPanel control. This behaves similar to WrapPanel, but content is virtualized.

## Checklist

- [x] Added unit tests (if possible)?
- [x] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

### CODE REVIEW

**Comment by maxkatz6** [comment]
@emmauss does it support items of different sizes, like in normal wrap panel? I wonder if it might be easier to start with VirtualizingUniformGrid, which always have cells of the same size. API-wise can be inspired either by UniformGridLayout (items repeater) or UniformGrid panel.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0034310-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by SmRiley** [comment]
In WPF, VirtualizingWrapPanel can be implemented by third parties. I don't quite understand. Shouldn't the priorities of wrappanel and stackpanel be parallel? Why do both WPF and Avalonia choose stackpanel first? Or is it that wrappanel can pass stackpanel? Manual implementation?

**Comment by emmauss** [comment]
> In WPF, VirtualizingWrapPanel has implemented by third parties. I don't quite understand. Shouldn't the priorities of wrappanel and stackpanel be parallel? Why do both WPF and Avalonia choose stackpanel first? Or is it that wrappanel can pass stackpanel Manual implementation?

Because StackPanel is a basic container that can be used to create both simple and complex layouts. WrapPanel is a specialized stackpanel. You would use StackPanel to create menus, grid-like layouts,, virtual keyboard layouts, lists, etc. WrapPanels aren't suitable for these.

**Comment by cezarypiatek** [comment]
Would it be possible to merge that control under a different name that indicates it’s meant for square/even elements? I believe there are still many use cases where it would be useful in that form. I tried copying the code from this PR to reuse it directly, but it’s not possible since some abstract methods from VirtualizingPanel are internal.

**Comment by Symbai** [comment]
@cezarypiatek https://github.com/kyuranger/Avalonia.SVirtualizingWrapPanel but it seems to be bugged when using it with a scrollviewer. I would love to test this PR to see if it works better. Why cannot we have this merged before any VirtualizingUniformGrid is being considered. I mean this PR is like 2 years old and no activity for VirtualizingUniformGrid yet. We could have a virtualized wrap panel at least for 2 years now, instead we have nothing.

**Pull request closed without merging**
