### PR TITLE
Implemented a stub toplevel impl as a replacement for disposed ones

### PR DESCRIPTION
**Pull request by kekekeks**
Got a bit tired of random `ObjectDisposedException`s on GTK backend

### CODE REVIEW

**Comment by grokys** [comment]
Wouldn't it make more sense to just set `PlatformImpl = null` and pull null checks around all accesses?

**Comment by kekekeks** [comment]
It would make more sense to not use implementation after disposal. With "null checks everywhere" we  will be essentially trading occasional `ObjectDisposedException`s for occasional `NullReferenceException`

**Comment by grokys** [comment]
Right, that's what I mean - `PlatformImpl == null` would mean "is disposed". Or am I missing something?

**Comment by kekekeks** [comment]
Yep, we'd still have pieces of code that try to use it one way or another. To ensure that stuff doesn't ever crash, we need some stub that will return safe data.

**Comment by grokys** [comment]
> Yep, we'd still have pieces of code that try to use it one way or another.

You mean clients expecting `Window.PlatformImpl` to be non-null? I don't think dereferencing null pointers in C# is a problem exclusive to here, in fact I think it's a bigger potential problem in lots of other places but we don't want to go creating stubs for every nullable type. Personally I think documenting `PlatformImpl` to say "can be null if underlying platform implementation has been closed" would suffice...

**Comment by kekekeks** [comment]
We could also introduce (or reference existing) `Option` type. 

https://www.nuget.org/packages/Option
https://www.nuget.org/packages/Optional/

**Comment by grokys** [comment]
Yeah, though unless we include it everywhere, it's going to be even more confusing than before... To be honest I think we need language support for non-nullable reference types, I've tried various thing in the past and they always seem to have holes. So given that, I'd still personally prefer just to null out the platform impl on close and document that fact...

**Comment by kekekeks** [comment]
Superceded by #995

**Pull request closed without merging**
