### PR TITLE
Fix Window autosize modes to respect MaxWidth and MaxHeight

### LINKED ISSUE #2471: SizeToContent not sizing correctly
I have made a message box for one of my programs but it is not sizing as it should

image

I have got ``SizeToContent="WidthAndHeight"`` in the xaml file

Happens on Windows and Linux (Can't test macOS because I don't have a mac/macOS VM)

repo with code: https://github.com/AzyIsCool/HATE

### LINKED ISSUE #5466: Cant get the AutoSizes right with a scrollviewer in a reagion
I'm trying to limiting Windows **MaxHeight** to the screen size as i use **CanResize=false** Windows. I need to have an ScrollViewer to ensure all content can be scroll on small resolutions, but i want only the content inside the ScrollWindow, everything else like description, some tools and bottom actions to be always visible. This partial works as soon window never reach MaxHeight or i will have the bottom actions overlaped, if i force a 340px Height they show but when scroll is not need the 340px is way to large and show a big pad.

No scroll need (Shows correctly)
image

When scroll is need it overlap bottom actions and the scroll content are missing for about the same height as the bottom actions
image

If i force 340px on DevTools it shows ok:
image

But if i do the same on a not required scroll window, it will do a huge padding, because the real height is about 80px...
image

I belive if i put the ScrollViewer on root and everyting inside it, it would work ok, but i like to have this regions always to show.
I have tried many things and code behind but all my attemps fails. It seens the last **"Auto"** is not respected somehow

```XML
<controls:WindowEx xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:controls="clr-namespace:UVtools.WPF.Controls"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="UVtools.WPF.Windows.ToolWindow"
        CanResize="False"
        MaxHeight="1000"
        SizeToContent="WidthAndHeight"
        WindowStartupLocation="CenterOwner"
        Title="Tool"
        Icon="/Assets/Icons/UVtools.ico">

    <Grid RowDefinitions="Auto,Auto,Auto,Auto,*,Auto">
    
    <!-- Description -->
    <Border Grid.Row="0"
      Background="WhiteSmoke"
      Padding="10"
      IsVisible="{Binding Description, Converter={x:Static StringConverters.IsNotNullOrEmpty}}">
        <TextBox Classes="TransparentReadOnly"
          HorizontalAlignment="Left"
          MaxWidth="{Binding DescriptionMaxWidth}"
          FontSize="16"
          Watermark="Description:"
          UseFloatingWatermark="True"
          Padding="5"
          Text="{Binding Description}"/>
    </Border>

    <!-- Layer Range -->
    <Border Grid.Row="1"
      Background="WhiteSmoke"
      Classes="GroupBox"
      Margin="5"
      IsVisible="{Binding LayerRangeVisible}">

      <StackPanel Orientation="Vertical">
        <Grid 
          ColumnDefinitions="Auto,*" Background="LightBlue">
          <TextBlock
            Padding="10" FontWeight="Bold"
            VerticalAlignment="Center"
            Text="Layer range selector"/>
          <CheckBox
            Grid.Column="1"
            Padding="10"
            FontWeight="Bold"
            VerticalAlignment="Center"
            HorizontalAlignment="Right"
            IsChecked="{Binding LayerRangeSync}"
            ToolTip.Tip="Synchronize and lock the layer range for single layer navigation"
            Content="Synchronize"/>
        </Grid>
        
        <Grid
          RowDefinitions="Auto,5,Auto"
          ColumnDefinitions="Auto,150,Auto,150,Auto"
          Margin="15">
          <TextBlock
            Grid.Row="0"
            Grid.Column="0"
            VerticalAlignment="Center"
            Text="From:"
            Margin="0,0,10,0"
            />

          <NumericUpDown
            Grid.Row="0"
            Grid.Column="1"
            VerticalAlignment="Center"
            Minimum="0"
            Maximum="{Binding MaximumLayerIndex}"
            Value="{Binding LayerIndexStart}"
            />

          <TextBlock
            Grid.Row="0"
            Grid.Column="2"
            VerticalAlignment="Center"
            Text="To:"
            IsEnabled="{Binding !LayerRangeSync}"
            Margin="20,0,10,0"
            />

          <NumericUpDown
            Grid.Row="0"
            Grid.Column="3"
            VerticalAlignment="Center"
            Maximum="{Binding MaximumLayerIndex}"
            IsEnabled="{Binding !LayerRangeSync}"
            Value="{Binding LayerIndexEnd}"
            />

          <Button Name="LayerSelectPresetButton"
            Grid.Row="0"
            Grid.Column="4"
            Margin="10,0,0,0"
            VerticalAlignment="Stretch"
            VerticalContentAlignment="Center"
            Padding="10,0,10,0"
            Content="Select ⮟"
            Command="{Binding OpenContextMenu}"
            CommandParameter="LayerSelectPreset"
            >
            <Button.ContextMenu>
              <ContextMenu Name="LayerSelectPresetContextMenu" PlacementMode="Bottom">
                <MenuItem
                  Header="_All layers"
                  HotKey="Ctrl + Shift + A" InputGesture="Ctrl + Shift + A"
                  Command="{Binding SelectAllLayers}"
                  />

                <MenuItem
                  Header="_Current layer"
                  HotKey="Ctrl + Shift + C" InputGesture="Ctrl + Shift + C"
                  Command="{Binding SelectCurrentLayer}"
                  />

                <Separator />

                <MenuItem
                  Header="_Bottom layers"
                  HotKey="Ctrl + Shift + B" InputGesture="Ctrl + Shift + B"
                  Command="{Binding SelectBottomLayers}"
                  />

                <MenuItem
                  Header="_Normal layers"
                  HotKey="Ctrl + Shift + N" InputGesture="Ctrl + Shift + N"
                  Command="{Binding SelectNormalLayers}"
                  />

                <Separator />

                <MenuItem
                  Header="_First layer"
                  HotKey="Ctrl + Shift + F" InputGesture="Ctrl + Shift + F"
                  Command="{Binding SelectFirstLayer}"
                  />

                <MenuItem
                  Header="_Last layer"
                  HotKey="Ctrl + Shift + L" InputGesture="Ctrl + Shift + L"
                  Command="{Binding SelectLastLayer}"
                  />

              </ContextMenu>
            </Button.ContextMenu>
          </Button>

          <TextBlock
            Grid.Row="2" Grid.Column="1"
            HorizontalAlignment="Center"
            Text="{Binding LayerStartMM, StringFormat=(\{0:F2\}mm)}" />

          <TextBlock
            Grid.Row="2" Grid.Column="3"
            HorizontalAlignment="Center"
            Text="{Binding LayerEndMM, StringFormat=(\{0:F2\}mm)}" />

          <TextBlock
            Grid.Row="2" Grid.Column="4"
            Margin="10,0,0,0"
            HorizontalAlignment="Center"
            Text="{Binding LayerRangeCountStr}" />

        </Grid>
      </StackPanel>

    </Border>

    <!-- ROI -->
    <Border
        Grid.Row="2" Classes="GroupBox"
      Background="WhiteSmoke"
      Margin="5"
      IsVisible="{Binding IsROIVisible}">

      <StackPanel Orientation="Vertical">
        <TextBlock
          Classes="GroupBoxHeader"
          Text="ROI - Region of interest"/>

        <TextBlock Margin="15"
                   Text="{Binding ROI, StringFormat=Region: \{0\}}" />

        <StackPanel Spacing="20" Margin="15,0,15,15" Orientation="Horizontal">
          <CheckBox 
            Content="Clear ROI after perform the operation"
            IsChecked="{Binding ClearROIAfterOperation}"
            />
          <Button 
            Padding="5" 
            Content="Clear ROI"
            Command="{Binding ClearROI}"/>
        </StackPanel>
        
      </StackPanel>

    </Border>
    
    <!-- Profiles -->
    <Border
        Grid.Row="3" Classes="GroupBox"
      Background="WhiteSmoke"
      Margin="5"
      IsVisible="{Binding IsProfilesVisible}"
      >

      <StackPanel Orientation="Vertical">
        <Grid
          ColumnDefinitions="Auto,*" Background="LightBlue">
          <TextBlock
            Padding="10" FontWeight="Bold"
            VerticalAlignment="Center"
            Text="{Binding Profiles.Count, StringFormat=Profiles: \{0\}}" />

          <StackPanel Orientation="Horizontal"
                      Grid.Column="1"
                      HorizontalAlignment="Right"
                      Spacing="2">
            <Button
              VerticalAlignment="Center"
              ToolTip.Tip="Clear all profiles"
              IsEnabled="{Binding Profiles.Count}"
              Command="{Binding ClearProfiles}"
              >
                <Image Width="16" Height="16" Source="/Assets/Icons/delete-16x16.png" />
            </Button>

          </StackPanel>

        </Grid>

        <Grid
          RowDefinitions="Auto,Auto"
          ColumnDefinitions="*,5,Auto,5,Auto,5,Auto"
          Margin="15"
          >

          <ComboBox 
                  Margin="0,0,0,10"
                  IsEnabled="{Binding Profiles.Count}"
                  IsVisible="{Binding Profiles.Count}"
                  SelectedItem="{Binding SelectedProfileItem}"
                  HorizontalAlignment="Stretch"
                  Items="{Binding Profiles}" />

          <Button
              Grid.Row="0"
              Grid.Column="2"
              Margin="0,0,0,10"
              VerticalAlignment="Stretch"
              ToolTip.Tip="Deselect the current profile"
              IsEnabled="{Binding SelectedProfileItem, Converter={x:Static ObjectConverters.IsNotNull}}"
              IsVisible="{Binding Profiles.Count}"
              Command="{Binding DeselectProfile}">
              <Image Source="/Assets/Icons/checkbox-unmarked-16x16.png" />
            </Button>

          <Button
              Grid.Row="0"
              Grid.Column="4"
              Margin="0,0,0,10"
              VerticalAlignment="Stretch"
              FontWeight="Bold"
              ToolTip.Tip="Set the selected profile as default to load in with this dialog.
&#x0a;Shift + click to clear the default profile."
              IsEnabled="{Binding SelectedProfileItem, Converter={x:Static ObjectConverters.IsNotNull}}"
              IsVisible="{Binding Profiles.Count}"
              Command="{Binding SetDefaultProfile}"
              Content="D"/>

          <Button
            Grid.Row="0"
            Grid.Column="6"
            Margin="0,0,0,10"
              VerticalAlignment="Stretch"
              ToolTip.Tip="Remove the selected profile"
              IsEnabled="{Binding SelectedProfileItem, Converter={x:Static ObjectConverters.IsNotNull}}"
              IsVisible="{Binding Profiles.Count}"
              Command="{Binding RemoveSelectedProfile}"
              >
            <Image Source="/Assets/Icons/trash-16x16.png" />
          </Button>

          <TextBox
            Grid.Row="1"
            Grid.Column="0"
            IsEnabled="{Binding ButtonOkEnabled}"
            Text="{Binding ProfileText}"
            Watermark="Profile name or leave empty for auto name"/>

          <Button
            Grid.Row="1"
            Grid.Column="2"
              VerticalAlignment="Stretch"
              ToolTip.Tip="Add a new profile with the current set values"
              IsEnabled="{Binding ButtonOkEnabled}"
              Command="{Binding AddProfile}"
              >
            <Image Source="/Assets/Icons/plus-16x16.png" />
          </Button>
          
        </Grid>
        
      </StackPanel>

    </Border>

    <!-- Content -->
    <Border Grid.Row="4"
      Classes="GroupBox"
      IsVisible="{Binding IsContentVisible}"
      Background="WhiteSmoke"
      Margin="5">

        <Grid RowDefinitions="Auto,*">
            <TextBlock Classes="GroupBoxHeader"
                       Text="{Binding Title}"/>

            <ScrollViewer Grid.Row="1"
                Content="{Binding ContentControl}"/>
        </Grid>
    </Border>

    <!-- Actions -->
    <Border Grid.Row="5" Classes="FooterActions">
      <Grid RowDefinitions="Auto"
          ColumnDefinitions="*">
        <StackPanel Spacing="10" Orientation="Horizontal">
          <Button
              Padding="10"
              IsDefault="True"
              IsVisible="{Binding IsButton1Visible}"
              Command="{Binding OnButton1Click}">
            <StackPanel
              Orientation="Horizontal"
              Spacing="10">
              <Image Source="/Assets/Icons/undo-alt-16x16.png"/>
              <TextBlock Text="{Binding Button1Text}"/>
            </StackPanel>
          </Button>

          <CheckBox 
            IsChecked="{Binding IsCheckBox1Checked}"
            IsVisible="{Binding IsCheckBox1Visible}"
            Content="{Binding CheckBox1Text}"/>
        </StackPanel>

        <StackPanel 
          Spacing="10" 
          HorizontalAlignment="Right" 
          Orientation="Horizontal">
          <Button
            Padding="10"
            IsDefault="True"
            IsVisible="{Binding ButtonOkVisible}"
            IsEnabled="{Binding ButtonOkEnabled}"
            Command="{Binding Process}">
            <StackPanel
              Orientation="Horizontal"
              Spacing="10">
              <Image Source="/Assets/Icons/accept-16x16.png"/>
              <TextBlock Text="{Binding ButtonOkText}"/>
            </StackPanel>
          </Button>

          <Button 
            Padding="10"
            IsCancel="True"
            Command="{Binding Close}"
            HotKey="Escape">
            <StackPanel 
              Orientation="Horizontal"
              Spacing="10">
              <Image Source="/Assets/Icons/exit-16x16.png"/>
              <TextBlock Text="Cancel"/>
            </StackPanel>
          </Button>
        </StackPanel>
        
      </Grid>
    </Border>

  </Grid>
</controls:WindowEx>

```

### LINKED ISSUE #5973: ScrollViewer scrollbar width don't change
**Describe the bug**
Scrollbar of ScrollViewer don't change it's width and goes out of window.

**To Reproduce**
1. Create window with SizeToContent="true" and set MaxWidth
2. Add something bigger then window inside ScrollViewer
3. Run and see bug

**Expected behavior**
ScrollViewer's scrollbar should fit window

**Screenshots**
изображение
изображение

**Desktop:**

- OS: Windows
- Version 0.10.5

### LINKED ISSUE #6441: Auto SizeToContent + MaxHeight + ScrollViewer dont adapt well and cut contents
**Describe the bug**
I'm always fighting the Auto SizeToContent system, and need to apply dirty hacks for the content to really adjust and be visible.
I do tool windows with `SizeToContent="WidthAndHeight"` and then i limit the `MaxHeight` to be the screen resolution less a margin, so the windows can constrain to the screen and never go out. So far so good, then i just put a ScrollViewer for content and expect it to work, the problem is it will never work as expected after Height hit MaxHeight and scroll is required.

Note the cut content and scroll viewport not properly calculated:
image

I think i'm not doing something that outrageous/complex on this window, but everytime i use SizeToContent and try to play with Auto and Fills things never go right when MaxWidth/Height is set. I think this need a serious review as this bug is here from long term...
However if you able to resize the window, even 1px less will auto fix the viewport and get the all content to show within the scrollviewer. But it should work without allow CanResin and user have to colapse and expand the window to content to adapt.

Not only this but there are other elements that break things, for example TabControl, when switch tabs on a system  that is not Windows, the window will not auto resize. #4896

Also there are more problems, if you have a **control.IsVisible = false** when window spawn, setting it to **true** after will not make scroll to adapt. But this may be related with my main problem.

**To Reproduce**
```XML
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="AvaloniaAutoHeightBug.Test1Window"
        Title="Test1Window"
        CanResize="False"
        Width="400"
        SizeToContent="Height"
        MaxHeight="800"
        >

    <Grid RowDefinitions="Auto,*,Auto">
        <Border Grid.Row="0" Background="Gray" Height="50">
            <TextBlock Text="Header" FontWeight="Bold" 
                       VerticalAlignment="Center"
                       HorizontalAlignment="Center"/>
        </Border>

        <Border Grid.Row="1" Background="LightGray">
            <ScrollViewer>
                <Grid RowDefinitions="Auto,100,Auto,100,Auto,100,Auto,100,Auto,100,Auto,100,Auto,100,Auto,100,Auto,100,Auto,100,Auto,100,Auto,100,Auto,100,Auto">
                  <TextBlock Grid.Row="0" Text="Spacing 1"/>
                  <TextBlock Grid.Row="2" Text="Spacing 2"/>
                  <TextBlock Grid.Row="4" Text="Spacing 3"/>
                  <TextBlock Grid.Row="6" Text="Spacing 4"/>
                  <TextBlock Grid.Row="8" Text="Spacing 5"/>
                  <TextBlock Grid.Row="10" Text="Spacing 6"/>
                  <TextBlock Grid.Row="12" Text="Spacing 7"/>
                  <TextBlock Grid.Row="14" Text="Spacing 8"/>
                  <TextBlock Grid.Row="16" Text="Spacing 9"/>
                  <TextBlock Grid.Row="18" Text="Spacing 10"/>
                  <TextBlock Grid.Row="20" Text="Spacing 11"/>
                  <TextBlock Grid.Row="22" Text="Spacing 12"/>
                  <TextBlock Grid.Row="24" Text="Spacing 13"/>
                  <TextBlock Grid.Row="26" Text="Spacing 14"/>
              </Grid>
            </ScrollViewer>
        </Border>

        <Border Grid.Row="2" Background="Gray" Height="50">
            <TextBlock Text="Footer" FontWeight="Bold"
                       VerticalAlignment="Center"
                       HorizontalAlignment="Center"/>
        </Border>
    </Grid>

  </Window>
```

**Expected behavior**
image

**Desktop (please complete the following information):**

- OS: This happen on every OSes i tried
- Version 0.10.7

### LINKED ISSUE #6740: Windows with SizeToContent and MaxWidth constraint don't properly call MeasureOverride on their children
**Describe the bug**
Following TextBlock doesn't properly report its `DesiredSize` **UNTIL** a user resized the window manually. 
```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        x:Class="AvaloniaTextWrapAutoSize.MainWindow"
        SizeToContent="WidthAndHeight"
        MaxWidth="500">
    <TextBlock TextWrapping="WrapWithOverflow">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean leo urna, facilisis sit amet odio vitae, vehicula congue est. Donec sit amet feugiat arcu, id rhoncus erat. Duis in imperdiet enim, eu hendrerit lorem. Praesent placerat a libero et ullamcorper. Mauris et libero id felis pulvinar vehicula. Morbi eleifend sit amet dui eget posuere. In ac sem eros. Suspendisse laoreet id nulla nec fringilla. Sed dignissim sem turpis, non molestie sem pretium vitae. Praesent eu congue mauris. Curabitur facilisis orci interdum lacus aliquet lobortis nec in magna. Vivamus ipsum neque, malesuada ut erat a, faucibus egestas libero. Sed placerat eu eros sit amet accumsan. Integer nec luctus ex, nec posuere ipsum. Nam magna ligula, fermentum ut ipsum at, tempor tempus massa. Donec feugiat libero at diam tristique, ac aliquam dui finibus.
    </TextBlock>
</Window>
```
In the example above (until a first manual resize), TextBlock reports DesiredSize ignoring window MaxWidth constraint, then Window sets its size according to this invalid DesiredSize.

After debugging it looks like Window is calling `MeasureOverride` with incorrect parameters (should be constrained to MaxWidth, but it is not) on its children.

**To Reproduce**

1. Create an Avalonia Window
2. Copy the code above
3. Run

**Expected behavior**
TextBlock should receive correct constraint to `MeasureOverride`.

**Desktop (please complete the following information):**

-  macOS Big Sur, Apple M1, .NET 6.0
- Avalonia 0.10.8

### PR DESCRIPTION
**Pull request by sn4k3**
## What does the pull request do?

Fixes windows not respecting `MaxWidth` and `MaxHeight` when `SizeToContent` is set to any Auto size system, causing overflow and out-of-view content.
This problem was live since ever and very annoying to deal on apps
Also read: https://github.com/AvaloniaUI/Avalonia/discussions/8082

## What is the current behavior?

Currently with `SizeToContent=AnyAuto` and `MaxWidth` and/or `MaxHeight` set, when size overflow the `Maximum` the content will overflow and be out of the view. In other words, `MaxWidth` nor `MaxHeight` is respected in auto size mode.

## What is the updated/expected behavior with this PR?

Prevents content to overflow from `MaxWidth` and `MaxHeight` when using auto sizing

1. Open **Catalog sample** -> `MainWindow.xaml`
2. Remove `Width` and `Height` properties
3. Add: `MaxWidth="1000" MaxHeight="600" SizeToContent="WidthAndHeight"`
4. Run without this fix and observe the wrong behaviour on **Grid** and **Calendar**
5. Apply the fix, rerun the sample and observe the correct behaviour 

### Before fix:
image

### After fix:
ControlCatalog Desktop_2022-05-06_16-15-02

## How was the solution implemented (if it's not obvious)?

Put  `MaxWidth` and `MaxHeight` in equation when calculating windows Measurement

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Fixed issues
Fixes #5466 
Fixes #6441 
Fixes #2471
Fixes #5973
Fixes #6740

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=8093) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=8093) before we can accept your contribution.<br/><br/>:x: sn4k3 [sign now](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=8093)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/AvaloniaUI/Avalonia?pullRequest=8093) it.</sub>

**Comment by maxkatz6** [comment]
Looks good to me. Thanks you for spending time on it!

Target branch should be "master".

**Comment by sn4k3** [comment]
> Target branch should be "master".

As master shown a lot of commits behind i tought that was the one. Sorry for the trouble.

**Comment by grokys** [comment]
Look good, though as @maxkatz6 says it needs to target master.

I'll also add a couple of unit tests if that's OK with you?

**Comment by grokys** [comment]
Hmm actually it won't target master cleanly. Do you think you could rebase onto master? I don't think GH lets us rebase branches from forks.

If you don't know how to do that, I can do it on another branch and open a new PR - let me know.

**Comment by sn4k3** [comment]
> I'll also add a couple of unit tests if that's OK with you?

Sure


> Hmm actually it won't target master cleanly. Do you think you could rebase onto master? I don't think GH lets us rebase branches from forks.
> 
> If you don't know how to do that, I can do it on another branch and open a new PR - let me know.

I tried to rebase but it won't let-me due some .sh files which much commit and i can't discard :( 
After commit them i rebase but there are a lot of conflicts and confusion.
I'm droping this PR and will create a new one from master

**Comment by sn4k3** [comment]
Created new PR #8095

**Pull request closed without merging**
