### PR TITLE
fix(DevTools): Invalid Enum Editor

### PR DESCRIPTION
**Pull request by workgroupengineering**
## What is the current behavior?

Show `NumericUpDown` instend of `ComboBox` with list of enum values.

## What is the updated/expected behavior with this PR?

Show `ComboBox` with list of enum values.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0036909-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by maxkatz6** [comment]
I thought it's already working like this? Also, what if it's a flags enum?

**Comment by timunie** [comment]
I'd like to see some kind of MulitSelectionComboBox here. Should be not too difficult to add. "Just" a button with current value as string and a Flyout containing a ListBox. However, will need some time for sure.

**Comment by workgroupengineering** [comment]
> I thought it's already working like this? 

it's a bug introduced by my previous PR.

> Also, what if it's a flags enum?

is considered as a normal enum, in the next PR I will handle this case too.

**Review by maxkatz6 — APPROVED** [review]

**Pull request merged**
