### PR TITLE
Updated portable.xaml submodule to latest develop.

### PR DESCRIPTION
**Pull request by grokys**
As requested by @cm4ker

### CODE REVIEW

**Comment by cm4ker** [comment]
Looks like appveyor has filed tests. Does anyone know what is crush this test Avalonia.DesignerSupport.Tests.DesignerSupportTests.Designer_In_Win32_Mode_Should_Provide_Valid_Hwnd?

**Comment by cm4ker** [comment]
Ok I'm try to go into and figure out what's the problem

**Comment by cm4ker** [comment]
After this pull request https://github.com/cwensley/Portable.Xaml/pull/104 (commit f8bf7a7) the AvaloniaUI have errors. I think it connected with adding ```source.OnBeforeProperties(state.Value)``` calls...

**Comment by cm4ker** [comment]
I think I found the root of problem. https://github.com/cwensley/Portable.Xaml/pull/111

**Comment by cm4ker** [comment]
@grokys can we update it to latest develop?

**Review by jmacato — APPROVED** [review]
Should hopefully fix https://github.com/AvaloniaUI/DataGrid/issues/6 and #1646

**Pull request merged**
