### PR TITLE
Fix rendering artifacts

### LINKED ISSUE #1098: Text not always included in dirty rectangles and produces rendering artifacts
When drawing text with `DrawText` the text is not  always included in dirty rectangles, this results in rendering artifacts.

Demonstration:

https://files.gitter.im/AvaloniaUI/Avalonia/YSbE/2017-08-10_20-23-38.mp4
https://files.gitter.im/AvaloniaUI/Avalonia/Qmwz/2017-08-10_20-33-26.mp4

Repro code: 

https://github.com/wieslawsoltes/Draw2D/blob/453320c81b602a954aed65efb01eff77132689e8/src/Core2D.Avalonia/Renderers/AvaloniaShapeRenderer.cs#L449

Version: 0.5.1-build3602-alpha

### LINKED ISSUE #1178: Rendering artifacts with DeferredRenderer
See ProgressBar page

rendebug

### PR DESCRIPTION
**Pull request by grokys**
Drawing e.g. a line on a pixel boundary causes the line to be drawn half on one side and half on the other side of the pixel. This means that when moving the primitive being drawn, the bounding box to clear must be extended by 0.5 pixels.

Fixes #1178

@wieslawsoltes does this also fix #1098 ?

### CODE REVIEW

**Comment by kekekeks** [comment]
Does it take into account matrix transformations, DPI and stroke width?

**Comment by grokys** [comment]
I tested it with stroke width, but good point on the other two - I will investigate...

**Comment by grokys** [comment]
@kekekeks you were right, this didn't work with scale transforms. Should now be fixed.

**Comment by grokys** [comment]
I should probably add some unit tests though.

**Comment by grokys** [comment]
Unit tests added and some faulty logic fixed.

**Review by kekekeks — APPROVED** [review]
LGTM

**Pull request merged**
