### PR TITLE
[CRITICAL] [Input] [MacOS] fix timestamp overflow on objC side

### PR DESCRIPTION
**Pull request by mklts**
NOTE: this bug affects all Avalonia versions and all apps built on them right now
I’ve got negative feedback from our users and started digging deep and that's what I've come up with:

## What does the pull request do?
Fixes a huge issue on macos. If you will click on macos now in one point clickcount will never reset. So user can cause double click just with click after any time in same spot. This is huge issue.
It was not experianced before maybe because time was not capped by int32. But now all our lunacy users experiance this issue and this is a huge bug.

## What is the current behavior?
Click on macos anywhere in same spot two times with 5 sec offset. DoubleTapped will be invoked.

## What is the updated/expected behavior with this PR?
Should work as before

## How was the solution implemented (if it's not obvious)?
on objC side was uint32 overflow. timestamp was always uint.maxvalue. it brokes this logic 
https://github.com/AvaloniaUI/Avalonia/blob/245290097658a5d21d6983dd20bf30f36ebd64d2/src/Avalonia.Base/Input/MouseDevice.cs#L133-L136
second if check is always false because uint.maxvalue-uint.maxvalue=0

Should be backported to 0.19 asap

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0033651-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by kekekeks** [comment]
You need to fix RawMouseEvent too:
https://github.com/AvaloniaUI/Avalonia/blob/245290097658a5d21d6983dd20bf30f36ebd64d2/src/Avalonia.Native/avn.idl#L585-L589

**Comment by Mikolaytis** [comment]
I cannot resolve an issue using ulong in idl format. Tried a lot of cases - none worked. Need support from @kekekeks :)

**Comment by hez2010** [comment]
In idl you need to use ulong64.

**Review by kekekeks — APPROVED** [review]

**Comment by kekekeks** [comment]
You need to update C# code as well

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0033914-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0034110-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Pull request merged**
