### PR TITLE
Hardcode DatePicker month/day to prevent unrepresentable dates

### LINKED ISSUE #4793: Crashes with DatePicker due to Unpresentable Dates
The `DatePicker` crashes if you click on it (i.e. bring up the pop-up) when the Day of the selected date is outside the range of any Month. Tested with the current development branch and the 0.1.0-preview5 release on Windows 10

The exception is on `"System.ArgumentOutOfRangeException: 'Year, Month, and Day parameters describe an un-representable DateTime.'"` in DateTimePickerPanel.cs on Line 491.

https://github.com/AvaloniaUI/Avalonia/blob/3d33abafeb698b9e7fcc423d9ec67ed694d67dd7/src/Avalonia.Controls/DateTimePickers/DateTimePickerPanel.cs#L491

Basically, when it is rendering the Months, it renders a whole date with a format that only reports the month, so when it tries to renter e.g. `February 31` it fails.

The exception goes away if you change the day on that line to be 1 rather than the chosen day. Need to change line 409 (year rendering) to deal with leap years (e.g. selecting February 29 has the same problem, because it doesn't exist in some years). The time formatting has hardcoded values for minute/second; I don't know why the dates do not, but I'm not a date/time expert.

I'm not sure what the best solution is, but at the moment the control is not really usable. If hardcoding those sounds sensible - or someone has a better suggestion - I'll be happy to put a PR together.

Full stacktrace from the .NET Core Control Catalog:

```
   at System.DateTime.DateToTicks(Int32 year, Int32 month, Int32 day)
   at System.DateTime..ctor(Int32 year, Int32 month, Int32 day)
   at Avalonia.Controls.Primitives.DateTimePickerPanel.FormatContent(Int32 value, DateTimePickerPanelType panelType) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Controls\DateTimePickers\DateTimePickerPanel.cs:line 491
   at Avalonia.Controls.Primitives.DateTimePickerPanel.UpdateItems() in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Controls\DateTimePickers\DateTimePickerPanel.cs:line 475
   at Avalonia.Controls.Primitives.DateTimePickerPanel.set_MaximumValue(Int32 value) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Controls\DateTimePickers\DateTimePickerPanel.cs:line 149
   at Avalonia.Controls.DatePickerPresenter.InitPicker() in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Controls\DateTimePickers\DatePickerPresenter.cs:line 335
   at Avalonia.Controls.DatePickerPresenter.set_Date(DateTimeOffset value) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Controls\DateTimePickers\DatePickerPresenter.cs:line 133
   at Avalonia.Controls.DatePicker.OnFlyoutButtonClicked(Object sender, RoutedEventArgs e) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Controls\DateTimePickers\DatePicker.cs:line 399
   at Avalonia.Interactivity.Interactive.<AddHandler>g__InvokeAdapter|4_0[TEventArgs](Delegate baseHandler, Object sender, RoutedEventArgs args) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Interactivity\Interactive.cs:line 63
   at Avalonia.Interactivity.Interactive.<>c__4`1.<AddHandler>b__4_1(Delegate baseHandler, Object sender, RoutedEventArgs args) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Interactivity\Interactive.cs:line 66
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Interactivity\EventRoute.cs:line 167
   at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Interactivity\EventRoute.cs:line 101
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Interactivity\Interactive.cs:line 120
   at Avalonia.Controls.Button.OnClick() in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Controls\Button.cs:line 267
   at Avalonia.Controls.Button.OnPointerReleased(PointerReleasedEventArgs e) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Controls\Button.cs:line 306
   at Avalonia.Input.InputElement.<>c.<.cctor>b__26_9(InputElement x, PointerReleasedEventArgs e) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Input\InputElement.cs:line 181
   at Avalonia.Interactivity.RoutedEvent`1.<>c__DisplayClass2_0`1.<AddClassHandler>g__Adapter|0(Object sender, RoutedEventArgs e) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Interactivity\RoutedEvent.cs:line 143
   at Avalonia.Interactivity.RoutedEvent.<>c__DisplayClass23_0.<AddClassHandler>b__0(ValueTuple`2 args) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Interactivity\RoutedEvent.cs:line 92
   at System.Reactive.AnonymousObserver`1.OnNextCore(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousObserver.cs:line 67
   at System.Reactive.ObserverBase`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/ObserverBase.cs:line 36
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 148
   at Avalonia.Interactivity.RoutedEvent.InvokeRaised(Object sender, RoutedEventArgs e) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Interactivity\RoutedEvent.cs:line 99
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Interactivity\EventRoute.cs:line 148
   at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Interactivity\EventRoute.cs:line 101
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Interactivity\Interactive.cs:line 120
   at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice device, UInt64 timestamp, IInputRoot root, Point p, PointerPointProperties props, KeyModifiers inputModifiers) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Input\MouseDevice.cs:line 289
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Input\MouseDevice.cs:line 162
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawInputEventArgs e) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Input\MouseDevice.cs:line 84
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Input\InputManager.cs:line 35
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Controls\TopLevel.cs:line 473
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in C:\Users\Murdo\source\repos\Avalonia\src\Windows\Avalonia.Win32\WindowImpl.AppWndProc.cs:line 459
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in C:\Users\Murdo\source\repos\Avalonia\src\Windows\Avalonia.Win32\WindowImpl.WndProc.cs:line 30
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in C:\Users\Murdo\source\repos\Avalonia\src\Windows\Avalonia.Win32\Win32Platform.cs:line 129
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Base\Threading\Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Controls\ApplicationLifetimes\ClassicDesktopStyleApplicationLifetime.cs:line 105
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in C:\Users\Murdo\source\repos\Avalonia\src\Avalonia.Controls\ApplicationLifetimes\ClassicDesktopStyleApplicationLifetime.cs:line 128
   at ControlCatalog.NetCore.Program.Main(String[] args) in C:\Users\Murdo\source\repos\Avalonia\samples\ControlCatalog.NetCore\Program.cs:line 102
```

### PR DESCRIPTION
**Pull request by VisualMelon**
## What does the pull request do?
Prevents crashes with the `DatePicker` control when the selected date contains large 'day' values which do not exist in some months.

## What is the current behaviour?
Selecting, for example, the 30th of September, and then invoking the DatePicker (i.e. by clicking on it to bring up the popup) causes a crash as described in #4793.

## What is the updated/expected behaviour with this PR?
The `DatePicker` no longer crashes.

## How was the solution implemented (if it's not obvious)?
Day and month values were hard-coded in the formatting, so that large day values cannot cause problems; hard-coding the month isn't necessary to address the observed issues, but makes the code more consistent such that only the parts of the date on which the value of interest may depend are specified.

## Checklist

- [ ] Unit tests: writing a test for this turned into a total nightmare... short of attaching the full template for `DatePickerPresenter`, it's a bit difficult to test this. Any suggestions welcome.
- [x] No additional classes or members to document
- [x] No documentation changes necessary

## Breaking changes
None of which I'm aware

## Fixed issues
Fixes #4793

### CODE REVIEW

**Comment by KieranDevvs** [comment]
Is it not worth adding some logic into the cases to check if the day of the month is valid for the selected month. i.e 
(Maybe extract this out into its own method)
```
case DateTimePickerPanelType.Month:
    var monthMaxValue = Date.DaysInMonth(FormatDate.Year, value);
    if(FormatDate.Day > monthMaxValue ) {
        FormatDate.Day = monthMaxValue;
    }
    return new DateTime(FormatDate.Year, value, FormatDate.Day).ToString(ItemFormat);
```
That way, when you change the month, you retain the user input as close as possible.

**Comment by VisualMelon** [comment]
@KieranDevvs that could be done, but it should be done in a different place outside of the formatting code. I assume the current behaviour is whatever UWP does.

**Comment by KieranDevvs** [comment]
> @KieranDevvs that could be done, but it should be done in a different place outside of the formatting code. I assume the current behaviour is whatever UWP does.
> 
> Edit: oh, I see what you mean: preserve the date as closely as possible when formatting. Yeah, that could be done, but unless there is a reason for expecting the month to be formatted depending on the day, I don't think it's worth the additional complexity.

Well when using a DateTime picker, if I select 31st (end of the month) of December, then change the month to February, I would expect my input to be the end of the month in February. 

Here's a more detailed explanation as to why this might get annoying:
In your expected use case, if you change the month, you have to change the date except on the occasion that you want the 1st of that month.

In my use case, if you change the month, in most scenarios (from 1st to 28th) your input will remain, (no more user actions necessary). In the edge case that the date selected by the user is greater than the maximum date in the selected month, we just select the maximum date in that month (as it is likely that the user wants the end of the month regardless of the specific date). And if that case fails, then, and only then is the user required to update the date that they wish to select.

Indeed it is extra complexity (not much) but it adds a better user experience.
This is just my opinion, maybe its worth getting some more input from the community before finalising the matter?

**Comment by VisualMelon** [comment]
@KieranDevvs all the user-interaction is done in a different place: it does behave as you describe: if you selected January 31, and then select April, it then changes to April 30. Specifically, it is not the case that you have to change the day whenever you change the month: it is preserved if it is in range, and clamped otherwise.

This PR is just a small change in the formatting code, so that when October 30 is selected, the thing doesn't crash when you open it and it renderers all the labels.

**Comment by amwx** [comment]
> Well when using a DateTime picker, if I select 31st (end of the month) of December, then change the month to February, I would expect my input to be the end of the month in February.

> In my use case, if you change the month, in most scenarios (from 1st to 28th) your input will remain, (no more user actions necessary). In the edge case that the date selected by the user is greater than the maximum date in the selected month, we just select the maximum date in that month (as it is likely that the user wants the end of the month regardless of the specific date). And if that case fails, then, and only then is the user required to update the date that they wish to select.

This is already the behavior of the control. The logic for that is handled elsewhere, this just formats the items that go in each date/time unit picker. 

> Is it not worth adding some logic into the cases to check if the day of the month is valid for the selected month. i.e
(Maybe extract this out into its own method)

This is actually already done when generating the items for display. The issue here was when I originally wrote the control, I used the `FormatDate` property in all the cases to format the items, which is what was leading to unrepresentable dates. The changes here from what I can tell line up with UWP and using the first of the month or year should never result in a unrepresentable date now.

**Comment by grokys** [comment]
@amwx what's the state of this PR? Should it be merged?

**Comment by amwx** [comment]
I don't think anything else need to be done so I'd say it can be merged

**Pull request merged**
