### PR TITLE
Update .NET Core SDK to version 3.0.x

### PR DESCRIPTION
**Pull request by jp2masa**
## Changes
- Update .NET Core SDK to version 3.0.x.

This is needed to use C# 8.0.

### CODE REVIEW

**Comment by kekekeks** [comment]
It's fine to update SDK, but we might need to wait for non-MS IDEs to add support for C# 8.0 before using it.

**Comment by Abdulbaqi-Alshareef** [comment]
> It's fine to update SDK, but we might need to wait for non-MS IDEs to add support for C# 8.0 before using it.

I did quick search and I found that Jetbrains rider now support it and omnisharp (which add cross platfrom support for .net to code editors) now support C# 8.0 which available for Vscode, Sublime text , Atom , Vim, Brackets, Emacs.

**Comment by kekekeks** [comment]
If no one objects, I'll merge it next week after updating the SDK on my machine.

**Comment by jp2masa** [comment]
The build is failing because CI has MSBuild 16.2 and we need 16.3. Maybe we could use .NET Core MSBuild on Windows?

It also seemed to work when I set it to install .NET Core 2.1 SDK instead of Runtime, but that sounds hacky. Anyway, it may be a possible option?

**Comment by MichalPetryka** [comment]
Visual Studio 2017 doesn't support C# 8.0 nor .Net Core 3.0, some people are still using it

**Comment by kekekeks** [comment]
@MichalPetryka VS2017 will still be supported for apps using Avalonia as a library.

**Comment by jmacato** [comment]
Any updates?

**Comment by jp2masa** [comment]
It looks like `ubuntu-latest` doesn't have the .NET Core 3.0 SDK yet. We can either wait or add the installation to the script.

**Comment by jmacato** [comment]
hmm they are always late to the game anyway, ignore it. let's just inform users to upgrade via dotnet ppa because that's how the official downloads do it.

**Comment by grokys** [comment]
What's the status on this now?

**Comment by jp2masa** [comment]
I think it's ready. CI build on #3033 fails only because of macOS (i.e. this PR should fix that).

**Review by grokys — APPROVED** [review]

**Pull request merged**
