### PR TITLE
fix using touch for date/time pickers.

### PR DESCRIPTION
**Pull request by danwalmsley**
## What does the pull request do?

Fixes scrollgestures on date/time pickers

## What is the current behavior?

handles events, and uses a transparent background so others are not picked up.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Fixed issues

@amwx

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019363-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019369-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by amwx** [comment]
`Tapped` event probably makes more sense anyway so that change seems fine to me. 

Though, we can get an invalid scrolling state with touch scrolling gesture where scroll can end up between items.
image

 WinUI's ScrollViewer has snap points that I think automatically handle this - so I think the `Offset` just needs to be coerced in the property setter, probably something like `if (dy % ItemHeight != 0) then snap to nearest` but I don't have a full understanding of how the manipulation gestures work and if that would mess something else up
https://github.com/AvaloniaUI/Avalonia/blob/d9f833930fe298487d5baa5c550ccdd2323d3d1f/src/Avalonia.Controls/DateTimePickers/DateTimePickerPanel.cs#L216-L218

**Comment by jmacato** [comment]
@amwx yeah snapping to the nearest multiple of the item's height would be ideal

**Review by maxkatz6 — APPROVED** [review]

**Comment by maxkatz6** [comment]
Let's merge it as a small fix of single problem. Scroll snapping issue can be followed separately.
@amwx can you create a small issue from your comment? Thanks.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019385-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by amwx** [comment]
> Let's merge it as a small fix of single problem. Scroll snapping issue can be followed separately. @amwx can you create a small issue from your comment? Thanks.

Done (#7840). I'll try to do the fix too, as it should be pretty trivial to do

**Pull request merged**
