### PR TITLE
fix(Geometries): Relative line drawing

### LINKED ISSUE #13235: Text alignment mismatch when using icon fonts
## Describe the bug

Text alignment mismatch when using icon fonts such as SegoeFluentIcons.

## To Reproduce

Check out `icon-font-err` branch for both repo:

[Avalonia Test](https://github.com/laolarou726/TypesettingErrorDemo)
[WPF Test](https://github.com/laolarou726/TypesettingErrorDemoWPF)

## Screenshots

In Avalonia:
image

In WPF:
image

## Environment

- OS: Windows 11 22H2
- Avalonia-Version: 11.1.999-cibuild0040792-beta

### PR DESCRIPTION
**Pull request by workgroupengineering**
## What does the pull request do?

 fix parsing relative line drawing

## What is the current behavior?

When using this `F1 M50,50z l -5,-5` the line is not drawn as expected

```xaml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x='http://schemas.microsoft.com/winfx/2006/xaml'
        x:Class="Sandbox.MainWindow">
  <Window.Resources>
    <Geometry x:Key="redoGeometry1">F1 M50,50z l -5,-5</Geometry>
    <DrawingGroup x:Key="redoDrawingGroup" >
      <DrawingGroup Opacity="1" Transform="1,0,0,1,0,-246.2">
        <GeometryDrawing Geometry="{StaticResource redoGeometry1}">
          <GeometryDrawing.Pen>
            <Pen Brush="#FF000000" Thickness="2" LineCap="Round" LineJoin="Round" />
          </GeometryDrawing.Pen>
        </GeometryDrawing>
      </DrawingGroup>
    </DrawingGroup>
    <DrawingImage x:Key="redoDrawingImage" Drawing="{StaticResource redoDrawingGroup}" />
  </Window.Resources>
  <Grid Height="200" Width="200">
    <Image Source="{StaticResource redoDrawingImage}"/>
  </Grid>
</Window>

```

### Expected(WPF)

DrawingGeometry_RelativeLine expected

### Avalonia(Skia)

DrawingGeometry_RelativeLine Skia out

### Avalonia(D3D)

DrawingGeometry_RelativeLine DirectX out

## What is the updated/expected behavior with this PR?

Avalonia D3D and Skia as same behavior of WPF

## Checklist

- [x] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/avalonia-docs with user documentation

## Fixed issues

Fixes #13235

### CODE REVIEW

**Comment by workgroupengineering** [comment]
The other commands for drawing lines also suffer from the same problem

## Horizontal Line `h`

Command: **`F1 M50,50z h 10`**

### Expected(WPF)

Relative_Line_h expected

### Avalonia(D3D)


Relative_Line_h D3D out


### Avalonia(Skia)

Relative_Line_h skia out


## Vertical Line `v`

Command: **`F1 M50,50z v 10`**

### Expected(WPF)

Relative_Line_v expected


### Avalonia(D3D)

Relative_Line_v D3D out


### Avalonia(Skia)


Relative_Line_v skia out

**Comment by Gillibald** [comment]
M50,50z l -5,-5

-Move to 50,50
-Close current segment by drawing a line straight to to starting point 0,0
Draw a line relative to current point 0,0 to -5,-5

So the result should be a line from -5,-5 to 50,50

All this should be covered in a unit test.

I personally don't trust the WPF implementation and instead the SVG spec should be followed.

**Review by kekekeks — APPROVED** [review]

**Review by Gillibald — COMMENTED** [review]
This test is failing:

```
 [Fact]
 public void Should_Parse_Path_With_Segments()
 {
     var pathGeometry = new PathGeometry();
     using (var context = new PathGeometryContext(pathGeometry))
     using (var parser = new PathMarkupParser(context))
     {
         parser.Parse("M50,50z l -5,-5");

         Assert.Equal(2, pathGeometry.Figures.Count);

         var firstFigure = pathGeometry.Figures[0];

         Assert.Equal(new Point(50, 50), firstFigure.StartPoint);

         var secondFigure = pathGeometry.Figures[1];

         Assert.Equal(new Point(0,0), secondFigure.StartPoint);
     }
 }
```

**M50,50z**

When the first figure is closed it should draw a line from 50,50 to 0,0 because we explicitly close the figure

**l -5,-5**

A LineTo should start at 0,0 and end at -5,-5

In the end, there should be one line starting at -5,-5 and ending at 50,50

The current PathMarkupParser implementation is not properly dealing with segments that only contain a `MoveTo` and are explicitly closed. This should always produce a `LineTo`

**Comment by Gillibald** [comment]
> Do we have a geometry sink that doesn't produce an actual platform impl? If so, it should be used in tests instead of render tests

There are existing tests here: https://github.com/AvaloniaUI/Avalonia/blob/master/tests/Avalonia.Base.UnitTests/Media/PathMarkupParserTests.cs

They are producing PathFigures but you can also mock `IGeometryContext`

**Comment by workgroupengineering** [comment]
> **M50,50z**
> 
> When the first figure is closed it should draw a line from 50,50 to 0,0 because we explicitly close the figure

The [WPF Spec](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/graphics-multimedia/path-markup-syntax?view=netframeworkdesktop-4.8#move-command) **`M50,50z`** produce empty figure. I would like to do a separate PR that addresses issue #4913


> I personally don't trust the WPF implementation and instead the SVG spec should be followed. 

I think if team decide to do this it should be implemented in v12. It's a big change that would lead to big problems even in font management. It should be possible to set for single font to use WPF compatibility.

Tell me what direction the team wants to take. 
And whether to resolve the issue of empty figures here or separately.

**Comment by Gillibald** [comment]
https://svg-path-visualizer.netlify.app/#M50%2C50z%20l%20-5%2C-5

**Comment by workgroupengineering** [comment]
> https://svg-path-visualizer.netlify.app/#M50%2C50z%20l%20-5%2C-5
> 
> This shows the correct result

So do I have to follow the SVG Specification?

**Comment by Gillibald** [comment]
Please remove added render tests and rewrite them so that the tests only use the PathMarkupParser. The rendered result might depend on the backend but we want to ensure the parser properly parses some sequences that are currently not working as expected.

**Review by Gillibald — APPROVED** [review]

**Pull request merged**
