### PR TITLE
Move BaseDark and BaseLight colours into their own file

### PR DESCRIPTION
**Pull request by TheVeryStarlk**
## What does the pull request do?
The title says it all.

## What is the current behavior?
Change few colours instead of changes many resources.

## What is the updated/expected behavior with this PR?
Performance improvement.

## How was the solution implemented (if it's not obvious)?
Move BaseDark and BaseLight colours into their own file

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Breaking changes
Not sure if there is.

## Obsoletions / Deprecations
None.

## Fixed issues
None* (Might fix some issues that are related to performance, if there's any)

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=7169) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=7169) before we can accept your contribution.<br/><br/>:x: StarlkYT [sign now](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=7169)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/AvaloniaUI/Avalonia?pullRequest=7169) it.</sub>

**Comment by amwx** [comment]
Swapping just the colors isn't going to work (or at least it didn't when I tried to do this) since the Brushes are created with StaticResources to the colors (ex `<SolidColorBrush x:Key="SystemControlBackgroundAltMediumHighBrush" Color="{StaticResource SystemAltMediumHighColor}" />`. I can't remember if the `<StaticResource ... />` items have to be swapped too (I think they do) or if it's just the colors and brushes, it's been a while since I tried this.

Either you have to swap the brushes too (which is what I do, and it's still basically instantaneous), or you'd have to change everything to DynamicResources which adds the overhead of dynamic resources

**Comment by StarlkYT** [comment]
> Swapping just the colors isn't going to work (or at least it didn't when I tried to do this) since the Brushes are created with StaticResources to the colors (ex `<SolidColorBrush x:Key="SystemControlBackgroundAltMediumHighBrush" Color="{StaticResource SystemAltMediumHighColor}" />`. I can't remember if the `<StaticResource ... />` items have to be swapped too (I think they do) or if it's just the colors and brushes, it's been a while since I tried this.
> 
> Either you have to swap the brushes too (which is what I do, and it's still basically instantaneous), or you'd have to change everything to DynamicResources which adds the overhead of dynamic resources

The idea is to swap the brushes only leaving the DynamicResources

**Comment by amwx** [comment]
> > Swapping just the colors isn't going to work (or at least it didn't when I tried to do this) since the Brushes are created with StaticResources to the colors (ex `<SolidColorBrush x:Key="SystemControlBackgroundAltMediumHighBrush" Color="{StaticResource SystemAltMediumHighColor}" />`. I can't remember if the `<StaticResource ... />` items have to be swapped too (I think they do) or if it's just the colors and brushes, it's been a while since I tried this.
> > Either you have to swap the brushes too (which is what I do, and it's still basically instantaneous), or you'd have to change everything to DynamicResources which adds the overhead of dynamic resources
> 
> The idea is to swap the brushes only leaving the DynamicResources

What I'm saying is if you move the colors to another file and only swap that one file to change themes, it's not going to work for most of the brushes, since they reference the color via static resource.

Example:
`<Color x:Key="MyColor">Red</Color>`
and in another file
`<SolidColorBrush x:Key="MyBrush" Color="{StaticResource MyColor}" />`
and even further
`<StaticResource x:Key="AliasedResource" ResourceKey="MyBrush" />`

if you swapped `MyColor` to say blue, you're not going to see that change in anything that references `MyBrush` or `AliasedResource`, because the brush color was defined with StaticResource, which is only evaluated once when it loads.

**Comment by robloo** [comment]
Is this still needed? Wasn't it done in another PR?

**Comment by maxkatz6** [comment]
Not exactly the same was done, but now Fluent theme switching is fast. Further improvements can be done though. Most likely with ThemeResource.
Also, CLA wasn't signed in this PR.

**Comment by robloo** [comment]
Well, thanks a lot for the contribution @StarlkYT! It was a great idea, other PRs took it a slightly different direction though.

**Pull request closed without merging**
