### PR TITLE
Fixes related to `ManagedFileChooser` handling of "complex" volume names

### PR DESCRIPTION
**Pull request by speles**
## What does the pull request do?

This PR fixes a few small issues that prevent "complex" volume labels and mountpoints (i.e. having non-ASCII or special characters) to work correctly in the `ManagedFileChooser` dialog.

## What is the current behavior?

1. The program crashes when dialog is opened if there are volumes with non-ASCII characters in the volume label.
2. If the volume mount point path has a whitespace (or a few other special symbols) in the name, the volume wouldn't be shown in the dialog at all.
3. Even after fixing (1) and (2), the volume label would be shown in the dialog incorrectly (with some characters unescaped).

## What is the updated/expected behavior with this PR?

Dialog can be opened and function correctly even if there are some volumes with non-ASCII or special characters in the mountpoint path or in the label.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=8134) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=8134) before we can accept your contribution.<br/><br/>:x: speles [sign now](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=8134)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/AvaloniaUI/Avalonia?pullRequest=8134) it.</sub>

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0020394-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by jmacato — APPROVED** [review]
Honestly I regret doing these in LINQ but these changes looks a-ok!

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0020425-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
