### PR TITLE
Sign assemblies

### PR DESCRIPTION
**Pull request by danwalmsley**
## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

### CODE REVIEW

**Comment by fforjan** [comment]
By curiosity, what is the value for you to enable this ?

 we are not doing this strong named signing in some of our projects as we do not see real values in that. Only dotnet code can verify such signature.
Strong name signing also break the name of the assemblies soif any code consume the name (InternalVisibleTo or load assembly if i remember correctly) this is a breaking change.

We prefer digital signing which is more visible to the user and is more secure to modification

**Comment by kekekeks** [comment]
Strong naming is required for several scenarios like Visual Studio extensions.

**Comment by danwalmsley** [comment]
internalsvisibleto is only valid when used inside Avalonia repo to give access to unit tests, and its bad practise... for people consuming avalonia... they already do not have the option to use this.

0.10.0 is breaking change anyway. This is the major one we want to get in,so we can maintain stable api going forward.

**Comment by rstm-sf** [comment]
In general, in this regard, the [strongnamer](https://github.com/dsplaisted/strongnamer) library is interesting

**Pull request merged**
