### PR TITLE
Fluent textbox update

### PR DESCRIPTION
**Pull request by jmacato**
## What does the pull request do?
Updates the look of TextBox to the newest standards.

image
image

@AvaloniaUI/core

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0033545-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by robloo** [comment]
1. Not a fan of the gray instead of white or slightly offwhite background. This doesn't match Fluent and makes it seem disabled in the current design language.
2. I dont think you should be changing the SystemAlt... resources at all. These are shared and used in apps. Just change the Text specific resources.
3. It doesn't look like you based the changes off Fluent v2 upstream which is not ideal IMO.

**Comment by robloo** [comment]
It was pointed out this is essentially following the Android Material design standard as well. If so, that's a big shift away from other XAML frameworks and I don't think it makes sense for a product of this lineage. Definitely advocate for a much wider discussion before you start doing this.

**Comment by MikeCodesDotNET** [comment]
@robloo, to give some context. 

@jmacato is doing this on my request, and it’s a work in progress—we desire to make a few minor tweaks to just three controls. We primarily want to tweak the borders and bring them closer to the latest Fluent style.

I’m unsure where it was pointed out about Material design, as that’s incorrect. We’re staying true to fluent. 

I agree that this PR isn’t the finished article, but the tweaks were looking to make will be minor.

**Comment by robloo** [comment]
@MikeCodesDotNET Thanks for the comments.

> we desire to make a few minor tweaks to just three controls. We primarily want to tweak the borders and bring them closer to the latest Fluent style.

Being more specific on my 4 original points above (Which I still think are valid in this version of the PR) if the tweaks are essentially just to bring the borders up to the Fluent v2 styles that should still affect all text-input controls to keep a consistent design language. That includes a handful of controls but probably not too many. 

How it's going to look mixing Fluent v1 and Fluent v2 in the final theme is up for debate. It might look fine. Then again a part of me is thinking we shouldn't be changing what already passed Microsoft's design team in a mix/match way. I also would rebase the controls directly on upstream Fluent v2 pulling in all the latest resources (and not change the Fluent v1 shared system ones). If we are going to do this, it might as well be done right and future-proofed.

> We primarily want to tweak the borders and bring them closer to the latest Fluent style.

Then the current background brushes are probably incorrect. Here is Fluent v2 from WinUI (Design intent)

issue235

And here is a side-by-side of the PR screenshot next to Material Design. It isn't a mistake to say this looks more like Material than Fluent. A lot of that is the gray instead of white background choice which may be a mistake.

| PR | Material Design |
|-|-|
| image | image |

https://m2.material.io/components/text-fields

**Comment by jmacato** [comment]
closing for lack of consensus, will revisit this again soon

**Pull request closed without merging**
