### PR TITLE
Check if event was handled before in OnTextInput

### PR DESCRIPTION
**Pull request by temporaryuser0**

### CODE REVIEW

**Comment by grokys** [comment]
@temporaryuser0 can you explain why this change is necessary?

**Comment by temporaryuser0** [comment]
@danwalmsley well, they shouldn't be, but looks like they are getting called always, because no checking is done first, I guess.

**Comment by grokys** [comment]
Set handled to true where? If you've got an inner control (in the template) then setting handled to true there will mean the event doesn't bubble up to the text box.

**Comment by grokys** [comment]
Could you give us a unit test demonstrating the problem, or at least an example?

**Comment by temporaryuser0** [comment]
Sure, if i remember correctly you didnt implement PasswordBox, so now if you wanted to make your "own" with TextBox, you can't because if you set Handled to true it stills appends text to it. Other than that i it doesn't really break the code, and allows for more modifications, so it should be left there (even in original WPF implementation the first thing they do is check if e.Handled is false before doing anything).

**Review by grokys — APPROVED** [review]

**Comment by grokys** [comment]
I still don't understand why this is needed, and "it doesn't really break the code" is a really bad reason for merging something, but in this case it's true, so merged.

**Comment by danwalmsley** [comment]
I'd have thought password box could just override template so the actual text isn't bound

**Comment by grokys** [comment]
Or if it inherits from `TextBox` just override `OnTextInput` and not call the base method.

**Pull request merged**
