### PR TITLE
Fixing AutoCompleteBox on Android

### LINKED ISSUE #12437: AutoCompleteBox on Android not functional
**Describe the bug**
On Android you cannot select an autocomplete suggestion from the popup of the AutoComplete control.

**To Reproduce**

1. Go to 'AutoCompleteBox' in ControlCatalog.Android
2. Click on top left autocompletebox
3. Type 'a', 'l'
4. In popup you get 'Alabama' en 'Alaska'
5. Click on 'Alabama'
6. Popup closes, but state of autocompletebox is not changed to alabama.

**Expected behavior**
Like on desktop, I expect 'Alabama' in the box.

**Screenshots**

https://github.com/AvaloniaUI/Avalonia/assets/27849065/62d69fcd-667b-4c6e-82e5-7bfa54dc5e05

**Notable**
In the 11.0.1 version (.2 not tested) the reproduce steps would produce a NRE, but not since https://github.com/AvaloniaUI/Avalonia/commit/ec21caf7fe0419b2284e34d63cd13da6de9460dc

- OS: Android (tested android 10 and 13)
- Version: latest commit at writing

### PR DESCRIPTION
**Pull request by msneijders**
## What does the pull request do?
This fixes AutoCompleteBox for Android.

## What is the current behavior?
After typing using the softkeboard and getting the autosuggest popup, and tapping an item from the popup, the selected value is not set to the textbox of the AutoCompleteBox.
(see #12437 for elaborate description).

## What is the updated/expected behavior with this PR?
Tapping on an item from the autosuggest list, closes the popup and selects it to the textbox.

## How was the solution implemented (if it's not obvious)?
There are 3 problems from preventing working on Android:
1. After tapping an item from the popup while softkeyboard is still opened, the AutoCompleteBox.OnLostFocus gets a `null` from the FocusManager.GetFocusedElement() -- HasFocus is than 'False' and closes the popup, and that makes selecting an item in the SelectingItemsControl not to work because on Android thats done in PointerReleased. FocusedElement is `null`  because the `AndroidInputMethod` resets the FocusedElement after it detects the softkeyboard closing -- this is solved by no longer resetting the FocusedElement, but instead reopening the softkeyboard now works by listening to PointerPressed event of the focused element.
2. `AutoCompleteBox.HasFocus()` did not work on Android (even after fixing the FocusedElement null value) when the focused element was inside its DropDownPopup. Fixed by copying some code from `ComboBox`.
3. `SelectingItemsControlSelectionAdapter` listens to PointerReleased from the SelectingItemsControl inside the popup, for doing the `OnCommit()`. This is not triggered on Android because `ListBoxItem` sets it to Handled=True when selecting on PointerReleased. This is fixed by adding a handler with handledEventsToo.

## Breaking changes
None

## Fixed issues
Fixes #12437

### CODE REVIEW

**Comment by msneijders** [comment]
@dotnet-policy-service agree company="Florisoft"

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0038334-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by emmauss** [comment]
The more optimal solution would be to maintain focus on the text box, even with the suggestion popup open. This will give similar experience to native android edittext widget. I'm currently investigating the feasibility of this.

**Comment by jmacato** [comment]
Closing this PR temporarily due to inactivity. Please ping me if this needs to be reopened.

**Pull request closed without merging**
