### PR TITLE
Fix Deferred Renderer memory leak

### PR DESCRIPTION
**Pull request by danwalmsley**
Just for a start discussion.

### CODE REVIEW

**Comment by danwalmsley** [comment]
cc @MarchingCube you may have some input on this...

**Comment by grokys** [comment]
@jkoritzinsky you added the dispose functionality to `VisualNode`, so I'd appreciate your input. In particular in 92d171f1 you wrote:

> VisualNodes are now owned by Scene objects, not by their parents. Add a Disposed member to make it easier to diagnose ownership bugs.

However the `Disposed` member is never set, and disposing a visual node doesn't dispose its children. Should it? Was this functionality not finished (hence `Disposed` never being set)?

**Comment by MarchingCube** [comment]
I checked this PR and there is still an memory leak (smaller, but still some nodes are being leaked as I can still see some of my controls staying alive despite not being in visual tree anymore).

**Comment by MarchingCube** [comment]
I am wondering if we shouldn't also clear the index here (https://github.com/AvaloniaUI/Avalonia/blob/2b6a65a199874f740fc26f2f212ea8eeab859aca/src/Avalonia.Visuals/Rendering/SceneGraph/Scene.cs#L104).

**Comment by danwalmsley** [comment]
> I am wondering if we shouldn't also clear the index here 
>   
>     
>       Avalonia/src/Avalonia.Visuals/Rendering/SceneGraph/Scene.cs
>     
>     
>         Lines 99 to 105
>       in
>       2b6a65a
>     
>     
>     
>     
> 
>         
>           
>            public void Dispose() 
>         
> 
>         
>           
>            { 
>         
> 
>         
>           
>                foreach (var node in _index.Values) 
>         
> 
>         
>           
>                { 
>         
> 
>         
>           
>                    node.Dispose(); 
>         
> 
>         
>           
>                } 
>         
> 
>         
>           
>            } 
>         
>     
>   
> 
> .

Iv added clearing that to this PR to see if it helps, however if the scene is no longer referenced by anything shouldn't that make the index and all the child visuals collectable?

**Comment by MarchingCube** [comment]
It should, but I've seen controls being still referenced somehow. Might just be a chance that I saw this in memory profiler. After some digging I wonder if there is some inconsistency caused by 
https://github.com/AvaloniaUI/Avalonia/blob/2b6a65a199874f740fc26f2f212ea8eeab859aca/src/Avalonia.Visuals/Rendering/SceneGraph/SceneBuilder.cs#L277-L299

Since this is also supposed to remove children nodes, and `Scene.Remove`  also disposes the node. I wonder if something is not working correctly here.

**Comment by MarchingCube** [comment]
@danwalmsley Based on even more memory profiling I think that another problem might be actually in 
https://github.com/AvaloniaUI/Avalonia/blob/051ad5c468e69dc16f53000310db772cee9693cc/src/Avalonia.Visuals/Rendering/SceneGraph/VisualNode.cs#L325-L340

In my case I have a `TextBlock` that has cloned `_drawOperationsRefCounter`, this one is still referencing old `VisualNode`, and through `Parent` relationship I end up keeping most of the old scene alive.

For testing I was also setting `Parent` to null in `Dispose` and this actually got rid of my memory leaks.

This really needs some feedback from @jkoritzinsky or @grokys .

**Comment by grokys** [comment]
Superseded by #2321

**Pull request closed without merging**
