### PR TITLE
Relax Typface resolution

### PR DESCRIPTION
**Pull request by Gillibald**
## What is the updated/expected behavior with this PR?

This will load both typefaces even when one is called `Roboto Condensed` instead of `Roboto`
```
<TextBlock Text="Hello ello 0123" FontFamily="avares://MyAssembly/Assets/RobotoCondensed-Regular.ttf#Roboto"/>
<TextBlock Text="Hello ello 0123" FontFamily="avares://MyAssembly/Assets/Roboto-Regular.ttf#Roboto"/>
```

## Checklist

- [x] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019493-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by jmacato — APPROVED** [review]
LGTM

**Comment by jmacato** [comment]
@Gillibald is this backportable?

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019843-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
