### PR TITLE
Don't use LocalValue priority for values in ControlTemplate

### LINKED ISSUE #2789: Set Template-provided properties with a separate BindingPriority
Right now template-provided properties are being set with `LocalValue` priority which makes them to take precedence over any style setters. That's really inconvenient since it makes some control aspects impossible to style without changing the entire ControlTemplate.

We should have a separate `TemplateProperty` binding priority which can be overridden by `StyleTrigger` binding priority.

### PR DESCRIPTION
**Pull request by grokys**
## What does the pull request do?

We have an [ongoing](https://github.com/AvaloniaUI/Avalonia/issues/2788) [source](https://github.com/AvaloniaUI/Avalonia/discussions/7530) [of](https://github.com/AvaloniaUI/Avalonia/issues/4804) [confusion](https://github.com/AvaloniaUI/Avalonia/discussions/7571) in Avalonia in that values set in a control template are set using `LocalValue` priority meaning that they can't be overridden by style setters (to be fair, WPF/UWP have this too but it's less noticeable due to their styling system).

This PR changes the XAML compiler to set literal values, `StaticResource`s and `DynamicResource`s with `TemplatedParent` priority, meaning that the values can be overridden in styles which have a trigger selector.

## Questions

- This change is specific to the XAML compiler. We can add a way to explicitly use `TemplatedParent` priority to indexer bindings (we already have `[~Foo.Bar]` syntax) but how would e.g. `Avalonia.Markup.Declarative` do this?
- What about `{Binding}`s - should they change their priority in `ControlTemplate`s? What if they have an explicit `Priority` already set?
- Is `TemplatedParent` priority going to be OK here? I think it is, but I may have missed something. Do we need a separate priority?
- Should we rename `TemplatedParent` priority to simply `Template`?

## Breaking changes

Styles which had non-working overrides of control template values will now come alive and potentially mess things up (you can see such a problem in the `HamburgerMenu` control in ControlCatalog here).

## Fixed issues

Fixes #2789

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018901-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by pr8x** [comment]
> we already have [~Foo.Bar] syntax

What does it do?

**Comment by amwx** [comment]
What's the status on this PR? 

Couple comments to the questions:
> ## Questions
>     * What about `{Binding}`s - should they change their priority in `ControlTemplate`s? What if they have an explicit `Priority` already set?

I would expect anything within a ControlTemplate to have a `Template` related priority that can then be overridden in a separate style selector. See the WinUI `SplitView` template file for an example of Bindings working:
https://github.com/microsoft/microsoft-ui-xaml/blob/main/dev/SplitView/SplitView_themeresources.xaml

Can you set an explicit priority in Xaml, or is this another Markup.Declarative issue? If so, no offense to them, but getting around these issues in C# is a lot easier than Xaml and I would say make everything template priority.

>     * Should we rename `TemplatedParent` priority to simply `Template`?

This would probably make sense to do IMO

**Comment by grokys** [comment]
> What's the status on this PR?

We've found that overring controls themes with this change, but without something like https://github.com/AvaloniaUI/Avalonia/issues/2769 / https://github.com/AvaloniaUI/Avalonia/discussions/7378 is just too difficult so I'm afraid that this change has had to be shelved before we can implement something like that first.

**Comment by amwx** [comment]
> > What's the status on this PR?
> 
> We've found that overring controls themes with this change, but without something like #2769 / #7378 is just too difficult so I'm afraid that this change has had to be shelved before we can implement something like that first.

Understandable, but not great. I hope this and the styling system upgrades are still in the queue for 11.0. Probably reciting the obvious here, but the longer these upgrades wait, the harder it becomes to make the change.

**Comment by grokys** [comment]
Updated this branch with changes from #8263 as this PR is not much use without that one. Temporarily updated the target to the branch for #8263 as well as to not include the changes from that PR in the diff.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0022332-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by grokys** [comment]
Now that #8479 has been merged, this PR can be merged too.

We will probably want to think about changing the `TemplatedParent` priority to rename it and lower its priority, but lets get this merged as-is and think about that in a subsequent PR.

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0022371-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
