### PR TITLE
Fix: RangeBase should not write coerced values back when DataContext is changing

### LINKED ISSUE #11870: Slider clamps bound value to default min max value when removed from visual tree
**Describe the bug**
A slider or any RangeBase control with Value, Minimum and Maximum bound writes a value back to the binding clamped to the default (0 ,100) rather than the bound min max.

**To Reproduce**
Run the repro and click flip  twice, The slider will change value when it should not

[RangeBaseRepro.zip](https://github.com/AvaloniaUI/Avalonia/files/11847437/RangeBaseRepro.zip)

**Expected behavior**
The view model should maintain the requested value.

**Desktop (please complete the following information):**

- OS: Windows 10
- Version 11.0.999-cibuild0036924-beta

### PR DESCRIPTION
**Pull request by timunie**
## What does the pull request do?
solves an issue where the bound value was changed when data context was changed or cleared

## What is the current behavior?
coerced value was written back to the datacontext which is a recent regression 

## What is the updated/expected behavior with this PR?
regression doesn't happen anymore

## How was the solution implemented (if it's not obvious)?
added a bool flag skipping the coerce if the datacontext is beeing changed

## Checklist

- [x] Added unit tests (if possible)?
- [x] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Fixed issues
Fixes #11870 

fyi @ahopper : I tested this branch with your sample and it was solved for me. I'd be happy if you can  verify this PR. 

@grokys Hope you don't mind I took a look into it. If the fix is wrong, feel free to cherry-pick the Unit-Test.

### CODE REVIEW

**Comment by robloo** [comment]
My instinct is this is a general issue and should probably be addressed at a lower level.

 1. Avalonia has DataContext switching differences from WPF (there are issues for it some place)
 2. Coercion still might not work correctly in all edge cases (again, some issues for coercion might still be open)

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0037044-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by ahopper** [comment]
This control has always had the issue that the order you set the properties in XAML matters, if the value comes first it will be clamped to the defaults before the desired min and max are set.  There seem to be issues with coercion at both ends of the lifetime.

**Comment by ahopper** [comment]
An alternative solution might just be to make the default Minimum and Maximum values min and max double values.

**Comment by timunie** [comment]
> An alternative solution might just be to make the default Minimum and Maximum values min and max double values.

probably an idea for now. But the underlaying issue should be solved anyway.

**Comment by ahopper** [comment]
@timunie I'm currently using a hybrid of this pr and big default min max values in my app with no issues, the big limits are belt and braces and probably not needed.

**Comment by timunie** [comment]
We need to wait for @maxkatz6 to check and merge this PR. Currently his workload is different 😉

**Review by maxkatz6 — APPROVED** [review]
[ISupportInitialize](https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.isupportinitialize?view=net-8.0) could help with XAML order, but not with DataContext reloading. Will keep this as a hack for now...

**Pull request merged**
