### PR TITLE
Improve Button and ToggleButton styling

### LINKED ISSUE #1102: Button:pressed seems to replace template if it was overridden
repro code

```
 <UserControl.Styles>
    <Style Selector="Button.RoundedButton">
      <Setter Property="Template">
        <ControlTemplate>
          <Border Background="Red" CornerRadius="8">
            <ContentPresenter Content="{TemplateBinding Content}"/>
          </Border>
        </ControlTemplate>
      </Setter>
    </Style>
    <Style Selector="Button.RoundedButton:pointerover">
      <Setter Property="Template">
        <ControlTemplate>
          <Border Background="Green" CornerRadius="4">
            <ContentPresenter Content="{TemplateBinding Content}"/>
          </Border>
        </ControlTemplate>
      </Setter>
    </Style>
  </UserControl.Styles>


<Button Content="Test" Classes="RoundedButton" />
```

If the button is pressed it gets no default colour and not red as it should be. Added the pointerover template to prove that selector was working...

[Secondary Bug]
interestingly after first template is applied, I cant change the second one to:
```    
<Style Selector="Button.RoundedButton:pointerover /template/ Border">
      <Setter Property="Background" Value="Green" />
    </Style>
```

### PR DESCRIPTION
**Pull request by Abdulbaqi-Alshareef**
## What does the pull request do?
This PR makes it easier to change the Button and ToggleButton's Background and BorderBrush on pressed, pointerover and checked etc.

## What is the current behavior?
Currently one has to target the ContentPresenter within the template to change these properties

## What is the updated/expected behavior with this PR?
Target this:
`Button:pressed`
instead of:
`Button:pressed /template/ ContentPresenter`

## Breaking changes
No breaking changes, targeting ContentPressenter or Button itself both still work
##Fixed issues
Closes #1102 

Note: its the same PR #2642 but because it has some problems with commits I closed it and opened this.

### CODE REVIEW

**Comment by worldbeater** [comment]
This seems to break existing implementations that rely on default button styles for `:pointerover` and `:pressed` button states. Isn't critical, but to fix that I had to define `:pointerover` and `:pressed` states explicitly, as such:

image
 
Otherwise the button won't change it's background when the pointer is over it or when it's pressed. Probably worth adjusting the default styles for the `Button` control.

**Comment by kekekeks** [comment]
Apparently this breaks visual states for `<Button Background="Blue"/>`: the button will be blue regardless of pressed/ponterover states

**Comment by kekekeks** [comment]
@grokys

**Comment by grokys** [comment]
Yes, I believe this PR is wrong. The style selectors select into the template deliberately to avoid exactly this problem. We should revert this PR, sorry @Abdulbaqi-Alshareef.

**Comment by grokys** [comment]
Opened a PR to revert it: https://github.com/AvaloniaUI/Avalonia/pull/2783

**Comment by Abdulbaqi-Alshareef** [comment]
@grokys  I think it should work, because properties of the content presenter within the template bound to parent template properties, also it works with the Buuton without classes
```
<Style Selector="Button">
      <Setter Property="Background" Value="Red"/>
</Style>
```
so style above works as expected but if you add class "Rounded"
```
<Style Selector="Button.Rounded">
      <Setter Property="Background" Value="Red"/>
</Style>
```
Then Its like overriding backround for all states of the default theme for Buttons that have Rounded class.
So do you think the problem with targeting control instead of contentpresenter within the template,
I think its something in the styling system.

**Comment by kekekeks** [comment]
@Abdulbaqi-Alshareef `<Button Background="Red"/>` overrides every single style by being a LocalValue

**Comment by grokys** [comment]
@Abdulbaqi-Alshareef as @kekekeks says, this is caused by the fact that setting a property outside a style results in a higher priority for the value. This is the [same as in WPF](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/dependency-property-value-precedence#dependency-property-setting-precedence-list) and is needed because a theme may set e.g. a default color for a control which needs to be overridable by a user setting e.g. `<Button Background="Red"/>`.

So when the style targets the button itself, it has a lower priority than the value set in XAML where the control is instantiated meaning that hovering over the control no longer causes a change in color.

**Comment by Abdulbaqi-Alshareef** [comment]
@kekekeks  @grokys  ah yes it's clear now, but targetting contentpresnter in default theme means you need to target it every time to override its style and that's a difficult part for newcomers to Avalonia , may this need some enhancements?

**Comment by Gillibald** [comment]
With Wpf I can still change the controls background on some condition without targeting the content presenter directly. So this is still some issue with the styling system. Setter values within a style that target only a type should have lower priority than a style targeting a class etc

**Comment by Gillibald** [comment]
Borders have the same problem now so we have to revert my default style changes as well

**Comment by Gillibald** [comment]
> Style triggers. The triggers within styles from page or application (these styles might be either explicit or implicit styles, but not from the default styles, which have lower precedence).

**Comment by grokys** [comment]
> With Wpf I can still change the controls background on some condition without targeting the content presenter directly. 

How do you do that in WPF? I'm looking at the [default button style for WPF](https://docs.microsoft.com/en-us/dotnet/framework/wpf/controls/button-styles-and-templates) and the visual states target the individual component controls in the template:

```
<VisualState x:Name="MouseOver">
	<Storyboard>
	  <ColorAnimationUsingKeyFrames Storyboard.TargetProperty="(Panel.Background).
		  (GradientBrush.GradientStops)[1].(GradientStop.Color)"
									Storyboard.TargetName="Border">
		<EasingColorKeyFrame KeyTime="0"
							 Value="{StaticResource ControlMouseOverColor}" />
	  </ColorAnimationUsingKeyFrames>
	</Storyboard>
</VisualState>
```

Note `Storyboard.TargetName="Border"` - this visual state is targeting the `Border` in the control template.

**Comment by Gillibald** [comment]
Y looks like I was wrong about the the ability to override the default behavior with the help of a trigger.

**Comment by Gillibald** [comment]
TabItem has the same problem with its default style so we have to revert my changes there too. Currently the TabItem itself is targeted and instead the ContentPresenter should be targeted for PointerOver etc

**Comment by Gillibald** [comment]
When I set the default Background by a Setter will it work with a selector like `TabItem:pointerover` to change the Background?

**Comment by rollersteaam** [comment]
Still seems to be an issue, I started using Avalonia a few days ago and was trying to make a button which changes its image based on its state. (That was its own problem, but irrelevant to the current issue.) Needing to do "Button:pressed /template/ ContentPresenter" isn't in the documentation for the :pressed pseudoclass either, I could only find the solution by searching for this issue.

**Pull request merged**
