### PR TITLE
Wrap Clipboard.GetTextAsync in a try-catch to mimic WPF default behavior (Avalonia 0.10)

### LINKED ISSUE #13716: Crash when pasting into the TextBox fails
## Describe the bug
It looks like the clipboard methods on Windows can fail and the TextBox doesn't handle the exception in any way thus the application crashes. 

```
System.TimeoutException: Timeout opening clipboard.
   at Avalonia.Win32.ClipboardImpl.OpenClipboard() in //src/Windows/Avalonia.Win32/ClipboardImpl.cs:line 30
   at Avalonia.Win32.ClipboardImpl.GetTextAsync() in //src/Windows/Avalonia.Win32/ClipboardImpl.cs:line 52
   at Avalonia.Controls.TextBox.Paste() in /_/src/Avalonia.Controls/TextBox.cs:line 723
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__1280(Object state)
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in //src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in //src/Windows/Avalonia.Win32/Win32Platform.cs:line 283
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in //src/Windows/Avalonia.Win32/Win32Platform.cs:line 217
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in //src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in //src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at WoWDatabaseEditorCore.Avalonia.Program.Main(String[] args)
   ```

## To Reproduce
No idea how to reproduce. An user reported the issue.

## Expected behavior
I think it is okay if the textbox try catches the clipboard method and ignores when it fails?

## Environment 

- OS: Windows
- Avalonia-Version: 0.10.22 (but after a brief look at the TextBox and Clipboard implementations in 11.0.x it looks like nothing has really changed to prevent this exception?)

### PR DESCRIPTION
**Pull request by BAndysc**
(this is a fix for 0.10 branch, even if 0.10.23 was never going to be released, I would really want to use a nightly build until my app is upgraded to Avalonia 11)

## What does the pull request do?
In this PR clipboard GetText calls are wrapped in a try-catch and in case of a TimeoutException, the exception is silently ignored. This mimics WPF default behaviour - https://github.com/dotnet/wpf/blob/main/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Documents/TextEditorCopyPaste.cs#L389

## What is the current behavior?
If GetText() throws a TimeoutException, the whole app crashes. The exception can be thrown due to [clipboard locking issues in TS sessions](https://github.com/dotnet/wpf/blob/main/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/clipboard.cs#L597)

## What is the updated/expected behavior with this PR?
The app won't crash when clipboard method fails.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/avalonia-docs with user documentation

## Breaking changes
Technically it changes the behaviour, but I don't think anybody depends on their app crashes?

## Obsoletions / Deprecations
n/a

## Fixed issues
Fixes #13716

### CODE REVIEW

**Comment by BAndysc** [comment]
Dear Avalonia Team, is there any way to trigger a CI build for this PR targeting Avalonia 0.10 branch? Upgrading to Avalonia 11 takes some time and my user constantly report this crash and there is no way to workaround it on my side.

**Review by maxkatz6 — APPROVED** [review]

**Comment by maxkatz6** [comment]
Corrected target branch. It should be "stable/0.10.x".
Thank you!

**Comment by maxkatz6** [comment]
Accidentally committed with version change commit (the only difference between stable branch and 0.10.22).
Reverted that directly.

**Comment by BAndysc** [comment]
Ah, that explains a lot! Thanks and sorry for the confusion :)

**Pull request merged**
