### PR TITLE
PathMarkupParser rewrite

### LINKED ISSUE #1606: PathMarkupParser doesn't support comma separator for implicit commands
This works:
```xml
<Path Data="M0,0 L 10,10 20,20" />
```
This doesn't work:
```xml
<Path Data="M0,0 L 10,10,20,20" />
```

According to the [SVG specification](https://www.w3.org/TR/SVG11/paths.html#PathDataGeneralInformation):

> - Superfluous white space and separators such as **commas** can be eliminated (e.g., "M 100 100 L 200 200" contains unnecessary spaces and could be expressed more compactly as "M100 100L200 200").
> - The command letter can be eliminated on subsequent commands if the same command is used multiple times in a row (e.g., you can drop the second "L" in "M 100 200 L 200 100 L -100 -200" and use "M 100 200 L 200 100 -100 -200" instead).

### LINKED ISSUE #1640: PathMarkupParser doesn't support implicit lineto commands following a moveto command
This works:

```xml
<Path Data="M0,0L10,10" />
```

This doesn't work:

```xml
<Path Data="M0,0 10,10" />
```

According to the [SVG specification](https://www.w3.org/TR/SVG/paths.html#PathDataMovetoCommands):
> - If a moveto is followed by multiple pairs of coordinates, the subsequent pairs are treated as implicit lineto commands

### LINKED ISSUE #1659: PathMarkupParser doesn't support whitespace after FillRule command
This works:

`<Path Data="F1M0,0" />`

This doesn't work:

`<Path Data="F 1M0,0" />` -> `InvalidDataException("Invalid fill rule")`

### PR DESCRIPTION
**Pull request by Gillibald**
- What does the pull request do?
This PR changes the way how path markup is parsed in avalonia to make parsing more testable.
- What is the current behavior?
The current implementation just writes commands to a StreamGeometry.
- What is the updated/expected behavior with this PR?
The updated version produces PathGeometry instead of calling methods on the StreamGeometry directly. That way we can write better unit tests for the SVG spec.
- How was the solution implemented (if it's not obvious)?
The new parser uses a regex to split the path data into command tokens that hold all arguments specified in the data string between command identifiers. That way we can identify implicit commands and process them later.

Checklist:

- [x] Added unit tests (if possible)?
- [x] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

Fixes #1606
Fixes #1640
Fixes #1659

### CODE REVIEW

**Comment by grokys** [comment]
Thanks for this @Gillibald - looks much better than before, the only thing I'm worried about is that it looks to be creating a _lot_ of objects during parsing, I'm a bit worried about the memory traffic it will introduce. It might be worth creating some benchmarks with Benchmark.Net to see what's happening there. Don't know what you think @jkoritzinsky?

**Comment by jkoritzinsky** [comment]
I'm always up for more memory benchmarks! It's always better to have quantitative data when possible.

**Comment by Gillibald** [comment]
Will do some profiling. Converting to a PathGeometry introduces a bigger memory footprint but will habe a look where is room for improvements.

**Comment by grokys** [comment]
Yeah, I'm sure `PathGeometry` does use more memory, and I'm fine with that. What I'm worried about here is more memory _traffic_.

**Comment by Gillibald** [comment]
Looks like I am not the right person to write some benchmarks fot the new component. I probably need some help or atleast some advice.

**Comment by jkoritzinsky** [comment]
You'll probably want to use `dotMemoryUnit` for measuring memory traffic. So these tests would probably go in our `LeakTests` project.

**Comment by jkoritzinsky** [comment]
@Gillibald Here's the documentation for testing memory traffic: https://www.jetbrains.com/help/dotmemory-unit/Checking_Memory_Traffic.html

**Comment by Gillibald** [comment]
Will have a look. Thanks for your help.

**Comment by grokys** [comment]
@Gillibald I hope you don't mind but I just pushed a benchmark for `PathMarkupParser`. The results are:

```
           Method |     Mean |    Error |   StdDev |   Gen 0 |  Gen 1 | Allocated |
----------------- |---------:|---------:|---------:|--------:|-------:|----------:|
 Parse_Large_Path | 474.2 us | 10.94 us | 31.05 us | 27.3438 | 6.8359 | 168.17 KB |
```

It's hard to tell how much of that is from the parser and how much is from the `PathGeometry` but it doesn't look too bad on first glance.

**Comment by grokys** [comment]
Given that, should we merge this? Or did you want to take a look at the benchmark first?

**Comment by grokys** [comment]
One way to test how much memory is used by the parser might be:

1. Add an `IGeometryContext` interface with the same API as `IStreamGeometryContext`
2. Add a `PathGeometryContext` that implements it, and writes to a `PathGeometry`
3. Make the `PathGeometryParser` accept an `IGeometryContext` and use that to create the `PathGeometry`

This might be nice as it would also allow creation of `StreamGeometry`s via `PathGeometryParser`. This could be a separate PR though,

**Comment by Gillibald** [comment]
This is my current benchmark result:
``` ini

BenchmarkDotNet=v0.10.8, OS=Windows 10.0.17134
Processor=Intel Core i7-4500U CPU 1.80GHz (Haswell), ProcessorCount=4
Frequency=2338342 Hz, Resolution=427.6534 ns, Timer=TSC
dotnet cli version=2.1.300
  [Host]     : .NET Core 4.6.26328.01, 64bit RyuJIT
  DefaultJob : .NET Core 4.6.26328.01, 64bit RyuJIT


```
 |           Method |     Mean |    Error |   StdDev |   Gen 0 |  Gen 1 | Allocated |
 |----------------- |---------:|---------:|---------:|--------:|-------:|----------:|
 | Parse_Large_Path | 171.5 us | 3.389 us | 5.936 us | 18.3105 | 2.4414 |  37.66 KB |

**Comment by Gillibald** [comment]
.Net Core 2.1 will probably improve a lot

**Comment by jkoritzinsky** [comment]
I can go through and Span-ify in a new PR. The Span-ification of the PathMarkupParser will be blocked on the same bug that #1668 is blocked on.

**Review by grokys — APPROVED** [review]

**Comment by grokys** [comment]
Merged! Thanks @Gillibald !

**Comment by jkoritzinsky** [comment]
I started prototyping a Span-ified version. I've included the benchmark results below. The perf change is insane!


```
           Method |     Mean |    Error |   StdDev |  Gen 0 |  Gen 1 | Allocated |
----------------- |---------:|---------:|---------:|-------:|-------:|----------:|
 Parse_Large_Path | 40.55 us | 1.147 us | 3.309 us | 4.6997 | 1.0986 |   9.63 KB |
```

**Comment by Gillibald** [comment]
Looks promising👍The benefit is quit obvious.

**Comment by jkoritzinsky** [comment]
Result from my newest prototype:

``` ini

BenchmarkDotNet=v0.10.14, OS=Windows 10.0.17134
Intel Core i5-6300U CPU 2.40GHz (Skylake), 1 CPU, 4 logical and 2 physical cores
.NET Core SDK=2.1.300
  [Host]     : .NET Core 2.0.7 (CoreCLR 4.6.26328.01, CoreFX 4.6.26403.03), 64bit RyuJIT
  DefaultJob : .NET Core 2.0.7 (CoreCLR 4.6.26328.01, CoreFX 4.6.26403.03), 64bit RyuJIT


```
|           Method |     Mean |     Error |    StdDev |  Gen 0 |  Gen 1 | Allocated |
|----------------- |---------:|----------:|----------:|-------:|-------:|----------:|
| Parse_Large_Path | 29.60 us | 0.5703 us | 0.5602 us | 0.8850 | 0.2136 |   4.76 KB |

I'll put out a PR with the Span-ified version in a bit.

**Pull request merged**
