### PR TITLE
fix: Exception when calling Classes.Remove

### LINKED ISSUE #8480: Exception when calling Classes.Remove
**Describe the bug**

When calling Classes.Remove we get exception `Collection was modified; enumeration operation may not execute.`

I think it was introduced here https://github.com/AvaloniaUI/Avalonia/commit/e63aa46458022a4a8974afe1eb1792ec7d1968c3 after we updated to 0.10.16 release.

```
Collection was modified; enumeration operation may not execute.

   at Avalonia.Controls.Classes.NotifyChanged() in /_/src/Avalonia.Styling/Controls/Classes.cs:line 320
   at Avalonia.Controls.Classes.Remove(String name) in /_/src/Avalonia.Styling/Controls/Classes.cs:line 188
   at WalletWasabi.Fluent.Behaviors.HistoryItemTypeClassBehavior.RemoveClasses() in WalletWasabi.Fluent\Behaviors\HistoryItemTypeClassBehavior.cs:line 67
   at WalletWasabi.Fluent.Behaviors.HistoryItemTypeClassBehavior.<OnAttachedToVisualTree>b__3_1(Object x) in WalletWasabi.Fluent\Behaviors\HistoryItemTypeClassBehavior.cs:line 21
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 54
   at System.Reactive.Linq.ObservableImpl.Switch`1._.InnerObserver.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Switch.cs:line 104
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 145
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 766
   at Avalonia.AvaloniaObject.Avalonia.PropertyStore.IValueSink.ValueChanged[T](AvaloniaPropertyChangedEventArgs`1 change) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 544
   at Avalonia.ValueStore.NotifyValueChanged[T](AvaloniaProperty`1 property, Optional`1 oldValue, BindingValue`1 newValue, BindingPriority priority) in /_/src/Avalonia.Base/ValueStore.cs:line 366
   at Avalonia.ValueStore.SetExisting[T](Object slot, StyledPropertyBase`1 property, T value, BindingPriority priority) in /_/src/Avalonia.Base/ValueStore.cs:line 266
   at Avalonia.ValueStore.SetValue[T](StyledPropertyBase`1 property, T value, BindingPriority priority) in /_/src/Avalonia.Base/ValueStore.cs:line 100
   at Avalonia.StyledElement.set_DataContext(Object value) in /_/src/Avalonia.Styling/StyledElement.cs:line 187
   at Avalonia.Controls.Primitives.TreeDataGridRow.Unrealize() in /_/src/Avalonia.Controls.TreeDataGrid/Primitives/TreeDataGridRow.cs:line 91
   at Avalonia.Controls.Primitives.TreeDataGridRowsPresenter.UnrealizeElement(IControl element) in /_/src/Avalonia.Controls.TreeDataGrid/Primitives/TreeDataGridRowsPresenter.cs:line 87
   at Avalonia.Controls.Primitives.TreeDataGridPresenterBase`1.RecycleElement(IControl element) in /_/src/Avalonia.Controls.TreeDataGrid/Primitives/TreeDataGridPresenterBase.cs:line 509
   at Avalonia.Controls.Primitives.RealizedElementList.ItemsRemoved(Int32 modelIndex, Int32 count, Action`2 updateElementIndex, Action`1 recycleElement) in /_/src/Avalonia.Controls.TreeDataGrid/Primitives/RealizedElementList.cs:line 190
   at Avalonia.Controls.Primitives.TreeDataGridPresenterBase`1.OnItemsCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e) in /_/src/Avalonia.Controls.TreeDataGrid/Primitives/TreeDataGridPresenterBase.cs:line 594
   at Avalonia.Controls.Models.TreeDataGrid.HierarchicalRows`1.OnCollectionChanged(IndexPath& parentIndex, NotifyCollectionChangedEventArgs e) in /_/src/Avalonia.Controls.TreeDataGrid/Models/TreeDataGrid/HierarchicalRows.cs:line 327
   at Avalonia.Controls.Models.TreeDataGrid.HierarchicalRows`1.Avalonia.Controls.Models.TreeDataGrid.IExpanderRowController<TModel>.OnChildCollectionChanged(IExpanderRow`1 row, NotifyCollectionChangedEventArgs e) in /_/src/Avalonia.Controls.TreeDataGrid/Models/TreeDataGrid/HierarchicalRows.cs:line 190
   at Avalonia.Controls.Models.TreeDataGrid.HierarchicalRow`1.Collapse() in /_/src/Avalonia.Controls.TreeDataGrid/Models/TreeDataGrid/HierarchicalRow.cs:line 152
   at Avalonia.Controls.Models.TreeDataGrid.HierarchicalRow`1.set_IsExpanded(Boolean value) in /_/src/Avalonia.Controls.TreeDataGrid/Models/TreeDataGrid/HierarchicalRow.cs:line 81
   at Avalonia.Controls.Models.TreeDataGrid.ExpanderCell`1.set_IsExpanded(Boolean value) in /_/src/Avalonia.Controls.TreeDataGrid/Models/TreeDataGrid/ExpanderCell.cs:line 37
   at Avalonia.Controls.Primitives.TreeDataGridExpanderCell.set_IsExpanded(Boolean value) in /_/src/Avalonia.Controls.TreeDataGrid/Primitives/TreeDataGridExpanderCell.cs:line 43
   at Avalonia.Controls.Primitives.TreeDataGridExpanderCell.<>c.<.cctor>b__26_2(TreeDataGridExpanderCell o, Boolean v) in /_/src/Avalonia.Controls.TreeDataGrid/Primitives/TreeDataGridExpanderCell.cs:line 18
   at Avalonia.DirectProperty`2.InvokeSetter(IAvaloniaObject instance, BindingValue`1 value) in /_/src/Avalonia.Base/DirectProperty.cs:line 164
   at Avalonia.AvaloniaObject.SetDirectValueUnchecked[T](DirectPropertyBase`1 property, T value) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 805
   at Avalonia.AvaloniaObject.SetValue[T](DirectPropertyBase`1 property, T value) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 385
   at Avalonia.DirectPropertyBase`1.RouteSetValue(IAvaloniaObject o, Object value, BindingPriority priority) in /_/src/Avalonia.Base/DirectPropertyBase.cs:line 156
   at Avalonia.Data.TemplateBinding.System.IObserver<System.Object>.OnNext(Object value) in /_/src/Markup/Avalonia.Markup/Data/TemplateBinding.cs:line 111
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value) in /_/src/Avalonia.Base/Reactive/LightweightObservableBase.cs:line 118
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 761
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaProperty`1 property, Optional`1 oldValue, BindingValue`1 newValue, BindingPriority priority) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 672
   at Avalonia.AvaloniaObject.SetAndRaise[T](AvaloniaProperty`1 property, T& field, T value) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 702
   at Avalonia.Controls.Primitives.ToggleButton.set_IsChecked(Nullable`1 value) in /_/src/Avalonia.Controls/Primitives/ToggleButton.cs:line 96
   at Avalonia.Controls.Primitives.ToggleButton.Toggle() in /_/src/Avalonia.Controls/Primitives/ToggleButton.cs:line 131
   at Avalonia.Controls.Primitives.ToggleButton.OnClick() in /_/src/Avalonia.Controls/Primitives/ToggleButton.cs:line 112
   at Avalonia.Controls.Button.OnPointerReleased(PointerReleasedEventArgs e) in /_/src/Avalonia.Controls/Button.cs:line 364
   at Avalonia.Input.InputElement.<>c.<.cctor>b__32_9(InputElement x, PointerReleasedEventArgs e) in /_/src/Avalonia.Input/InputElement.cs:line 223
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 145
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 148
   at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 79
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/Interactive.cs:line 123
   at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice device, UInt64 timestamp, IInputRoot root, Point p, PointerPointProperties props, KeyModifiers inputModifiers) in /_/src/Avalonia.Input/MouseDevice.cs:line 313
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e) in /_/src/Avalonia.Input/MouseDevice.cs:line 144
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e) in /_/src/Avalonia.Input/InputManager.cs:line 37
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs:line 518
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.WndProc.cs:line 33
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at WalletWasabi.Fluent.Desktop.Program.Main(String[] args) in WalletWasabi.Fluent.Desktop\Program.cs:line 110
```

**To Reproduce**

**Expected behavior**

No exception.

**Screenshots**

**Desktop (please complete the following information):**

- Version 0.10.16

**Additional context**

### PR DESCRIPTION
**Pull request by workgroupengineering**
## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Fixed issues

Fixes #8480

### CODE REVIEW

**Comment by workgroupengineering** [comment]
# Benchmarks 23 - Style_ClassSelector

## Before

```ini
BenchmarkDotNet=v0.13.1, OS=Windows 10.0.19044.1806 (21H2)
Intel Core i5-10400 CPU 2.90GHz, 1 CPU, 12 logical and 6 physical cores
.NET SDK=6.0.400-preview.22301.10
  [Host]     : .NET 6.0.5 (6.0.522.21309), X64 RyuJIT
  DefaultJob : .NET 6.0.5 (6.0.522.21309), X64 RyuJIT
```

|       Method |       Mean |    Error |   StdDev |  Gen 0 |  Gen 1 | Allocated |
|------------- |-----------:|---------:|---------:|-------:|-------:|----------:|
|        Apply |   625.7 ns |  7.09 ns |  6.64 ns | 0.0806 | 0.0049 |     507 B |
| Apply_Toggle | 1,210.5 ns | 15.12 ns | 14.14 ns | 0.1050 | 0.0049 |     671 B |
| Apply_Detach | 1,047.0 ns | 10.08 ns |  8.93 ns | 0.0928 | 0.0037 |     588 B |

```ini
// * Hints *
Outliers
  Style_ClassSelector.Apply_Detach: Default -> 1 outlier  was  removed (1.08 us)

// * Legends *
  Mean      : Arithmetic mean of all measurements
  Error     : Half of 99.9% confidence interval
  StdDev    : Standard deviation of all measurements
  Gen 0     : GC Generation 0 collects per 1000 operations
  Gen 1     : GC Generation 1 collects per 1000 operations
  Allocated : Allocated memory per single operation (managed only, inclusive, 1KB = 1024B)
  1 ns      : 1 Nanosecond (0.000000001 sec)
```

## After
```ini
BenchmarkDotNet=v0.13.1, OS=Windows 10.0.19044.1806 (21H2)
Intel Core i5-10400 CPU 2.90GHz, 1 CPU, 12 logical and 6 physical cores
.NET SDK=6.0.400-preview.22301.10
  [Host]     : .NET 6.0.5 (6.0.522.21309), X64 RyuJIT
  DefaultJob : .NET 6.0.5 (6.0.522.21309), X64 RyuJIT
```

|       Method |       Mean |    Error |   StdDev |  Gen 0 |  Gen 1 | Allocated |
|------------- |-----------:|---------:|---------:|-------:|-------:|----------:|
|        Apply |   652.2 ns |  1.83 ns |  1.63 ns | 0.0806 | 0.0049 |     509 B |
| Apply_Toggle | 1,227.9 ns |  3.89 ns |  3.03 ns | 0.1050 | 0.0049 |     673 B |
| Apply_Detach | 1,060.6 ns | 17.57 ns | 16.44 ns | 0.0940 | 0.0037 |     590 B |

```ini
// * Hints *
Outliers
  Style_ClassSelector.Apply: Default        -> 1 outlier  was  removed (658.89 ns)
  Style_ClassSelector.Apply_Toggle: Default -> 3 outliers were removed (1.25 us..1.26 us)

// * Legends *
  Mean      : Arithmetic mean of all measurements
  Error     : Half of 99.9% confidence interval
  StdDev    : Standard deviation of all measurements
  Gen 0     : GC Generation 0 collects per 1000 operations
  Gen 1     : GC Generation 1 collects per 1000 operations
  Allocated : Allocated memory per single operation (managed only, inclusive, 1KB = 1024B)
  1 ns      : 1 Nanosecond (0.000000001 sec)
```

**Comment by workgroupengineering** [comment]
@wieslawsoltes Can you tets?

**Comment by wieslawsoltes** [comment]
> @wieslawsoltes Can you tets?

It's hard to repro and my case is on stable branch.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0021843-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by grokys** [comment]
Hi @workgroupengineering, sorry but I'm already working on this. We need a generic solution to this problem as it crops up in a few places, with unit tests etc. Also the `ReaderWriterLockSlim` stuff is unnecessary because the listeners should only be added/removed on the UI thread - the problem is that of re-entrancy not thread safety.

**Comment by MarchingCube** [comment]
For me this is an instant repro in master, I will take a look.

**Comment by danwalmsley** [comment]
https://github.com/AvaloniaUI/Avalonia/pull/8492

**Comment by grokys** [comment]
> this issue can simple fix with this code:

yeah but that always creates a copy, even though most of the times it will not be needed. We already do this in a few places, but we need a better solution.

> ReaderWriterLockSlim is for ensure that the _listeners does not change during the copy.

`ReaderWriterLockSlim` is for managing thread safety, but this problem isn't occurring because multiple threads are accessing the collection - it's always the UI thread. The problem occurs when a classes changed listener modifies the collection that is currently being enumerated on the same thread, i.e. it's a reentrancy problem not a threading problem.

**Pull request closed without merging**
