### PR TITLE
Fix COM issue in Cursor

### LINKED ISSUE #7547: Cursor causes COM failure with NativeAOT
**Describe the bug**
Generally Avalonia is almost compatible with NativeAOT, except cursor in ControlCatalog causes COM failure with NativeAOT:

```
Unhandled Exception: System.InvalidOperationException: COM Interop requires ComWrapper instance registered for marshalling.
   at System.Runtime.InteropServices.ComWrappers.ComInterfaceForObject(Object) + 0x56
   at System.Runtime.InteropServices.ComWrappers.ComInterfaceForObject(Object, Guid) + 0xe
   at ControlCatalog.NetCore!<BaseAddress>+0x225a32f
   at System.Drawing.Bitmap..ctor(Stream, Boolean) + 0xad
   at Avalonia.Win32.CursorFactory.LoadSystemDrawingBitmap(IBitmapImpl) + 0x59
   at Avalonia.Win32.CursorFactory.CreateCursor(IBitmapImpl, PixelPoint) + 0x43
   at ControlCatalog.ViewModels.CursorPageViewModel..ctor() + 0x198
   at ControlCatalog.Pages.CursorPage..ctor() + 0x3a
   at ControlCatalog.MainView.!XamlIlPopulate(IServiceProvider, MainView) + 0x18e3
   at ControlCatalog.MainView..ctor() + 0x52
   at ControlCatalog.MainWindow.!XamlIlPopulate(IServiceProvider, MainWindow) + 0x20b2
   at ControlCatalog.MainWindow..ctor() + 0x27
   at ControlCatalog.App.OnFrameworkInitializationCompleted() + 0x3c
   at ControlCatalog.NetCore.Program.Main(String[]) + 0x3b7
   at ControlCatalog.NetCore!<BaseAddress>+0x2287d1f
```

**To Reproduce**

1. Clone Avalonia repo
2. Merge branch microcom-dragndrop(#7506) into main to make sure Drag'n'Drop won't break the app.
3. Build ControlCatalog.NetCore with NativeAOT.
    To build it with NativeAOT, you need to:
    1. Add below content to ControlCatalog.NetCore.csproj:
        ```xml
        <ItemGroup>
          <PackageReference Include="Microsoft.DotNet.ILCompiler" Version="7.0.0-*" />
          <RdXmlFile Include="rd.xml" />
        </ItemGroup>
        ```
    2. Place a nuget.config ControlCatalog.NetCore under directory:
        ```xml
        <?xml version="1.0" encoding="utf-8"?>
        <configuration>
          <packageSources>
            <!--To inherit the global NuGet package sources remove the <clear/> line below -->
            <clear />
            <add key="dotnet7" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json" />
            <add key="nuget" value="https://api.nuget.org/v3/index.json" />
          </packageSources>
        </configuration>
        ```
    3. Place a rd.xml under ControlCatalog.NetCore directory:
        ```xml
        <Directives>
          <Application>
	    <Assembly Name="ControlCatalog" Dynamic="Required All"></Assembly>
	    <Assembly Name="Avalonia.Themes.Default" Dynamic="Required All"></Assembly>
	    <Assembly Name="Avalonia.Themes.Fluent" Dynamic="Required All"></Assembly>
          </Application>
        </Directives>
        ```
4. `dotnet publish -c Release -r win-x64`
5. Launch published ControlCatalog.NetCore

**Expected behavior**
No exception was thrown.

**Additional context**
Note that if you comment out the Cursor page, ControlCatalog will successfully launch and most functions work without any issue.

### PR DESCRIPTION
**Pull request by hez2010**
## What does the pull request do?
S.D.Common has moved to `ComWrappers` since 6.0 and fixed issues with NativeAOT (see https://github.com/dotnet/runtime/pull/54636 and https://github.com/dotnet/runtime/pull/54884), so I bumped its version to 6.0.0. 

## Fixed issues
Fixes #7547

### CODE REVIEW

**Comment by kekekeks** [comment]
@maxkatz6

**Review by maxkatz6 — DISMISSED** [review]

**Comment by kekekeks** [comment]
Note that it might be not compatible with netstandard2.0 or netcoreapp2.1

**Comment by maxkatz6** [comment]
@kekekeks I understand that netstandard still won't be compatible with nativeaot, but why shouldn't it be without? Especially when nuget package still has these targets. 

We can double check just to be safe.

**Comment by maxkatz6** [comment]
Otherwise we can conditionally target newer version for avalonia net6 target.

**Comment by kekekeks** [comment]
The package provides reference assemblies for netstandard2.0 but doesn't actually support everything netstandard2.0 does

`buildTransitive/netcoreapp2.0/System.Drawing.Common.targets`:
```xml
<Project InitialTargets="NETStandardCompatError_System_Drawing_Common_netcoreapp3_1">
  <Target Name="NETStandardCompatError_System_Drawing_Common_netcoreapp3_1"
          Condition="'$(SuppressTfmSupportBuildWarnings)' == ''">
    <Error Text="System.Drawing.Common doesn't support $(TargetFramework). Consider updating your TargetFramework to netcoreapp3.1 or later." />
  </Target>
</Project>
```

**Comment by kekekeks** [comment]
I think we need to conditionally upgrade it for `net6` and keep the old version for `netstandard2.0`

**Comment by hez2010** [comment]
@kekekeks @maxkatz6 I've made S.D.Common conditional targeted.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018528-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by kekekeks — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018529-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
