### PR TITLE
Bump sdk version to 5.0.102

### LINKED ISSUE #5401: Add supports .NET 5 SDK
**Is your feature request related to a problem? Please describe.**
Add supports .NET 5 SDK

**Describe the solution you'd like**
One issue is that ILRepack.NETStandard needs to be updated to support .NET 5 https://github.com/AvaloniaUI/Avalonia/pull/5396#issuecomment-770428635 and https://github.com/jbevain/cecil/issues/669

### PR DESCRIPTION
**Pull request by rstm-sf**
## What does the pull request do?
Bump version sdk to 5.0.102

## What is the current behavior?
Limit to .NET Core 3.1 and C#8

## What is the updated/expected behavior with this PR?
Limit to .NET 5.0 and C#9

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

## Fixed issues

Fixes #5401 

## Dependencies

Depends on https://github.com/peters/il-repack/pull/2
Depends on https://github.com/AvaloniaUI/Avalonia/pull/5423

Depends on update https://www.nuget.org/packages/ILRepack.NETStandard/ ?

### CODE REVIEW

**Comment by rstm-sf** [comment]
Hello, @worldbeater! Сouldn't see what is happening on Linux with a Pharmacist at net5?

**Comment by jp2masa** [comment]
The problem is this:

```
/home/vsts/work/1/s/nukebuild/_build.csproj : error NU1107: Version conflict detected for Microsoft.CodeAnalysis.Common. Install/reference Microsoft.CodeAnalysis.Common 3.8.0 directly to project _build to resolve this issue. 
/home/vsts/work/1/s/nukebuild/_build.csproj : error NU1107:  _build -> Pharmacist.Core 2.0.6 -> Microsoft.CodeAnalysis.CSharp 3.8.0 -> Microsoft.CodeAnalysis.Common (= 3.8.0) 
/home/vsts/work/1/s/nukebuild/_build.csproj : error NU1107:  _build -> MicroComGenerator -> Microsoft.CodeAnalysis.CSharp.Workspaces 3.7.0 -> Microsoft.CodeAnalysis.Common (= 3.7.0).
```

So you have to either directly reference `3.8.0` on `_build` or upgrade it on `MicroComGenerator`:

https://github.com/AvaloniaUI/Avalonia/blob/1a39210febf92e9e87b3ebacca9b56d99e660913/src/tools/MicroComGenerator/MicroComGenerator.csproj#L8.

**Comment by rstm-sf** [comment]
Thanks!

I am looking wrong again. But I was more confused by this

```
/home/vsts/work/1/s/nukebuild/_build.csproj : warning NU1603: Pharmacist.Core 2.0.6 depends on ICSharpCode.Decompiler (>= 2.0.6) but ICSharpCode.Decompiler 2.0.6 was not found. An approximate best match of ICSharpCode.Decompiler 2.3.0 was resolved.
/home/vsts/work/1/s/nukebuild/_build.csproj : warning NU1701: Package 'ICSharpCode.Decompiler 2.3.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.
/home/vsts/work/1/s/nukebuild/_build.csproj : warning NU1701: Package 'ICSharpCode.NRefactory 5.5.1' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.
```
It has its own [ICSharpCode.Decompiler](https://github.com/reactiveui/Pharmacist/blob/357b54abbddd36b31ade933caa9e1bff486003ec/src/Pharmacist.Core/Pharmacist.Core.csproj#L22) which is not [covered](https://github.com/reactiveui/Pharmacist/blob/357b54abbddd36b31ade933caa9e1bff486003ec/src/ICSharpCode.Decompiler/ICSharpCode.Decompiler.csproj#L20)

**Comment by worldbeater** [comment]
@rstm-sf probably worth switching to an older Pharmacist version that doesn't break the build. Probably Pharmacist is going to be deprecated soon in favor of https://github.com/reactivemarbles/ObservableEventsSourceGenerator anyway as far as I know.

**Comment by rstm-sf** [comment]
@worldbeater, maybe then it is worth removing potentially deprecated technology from the repository before it is actively used?

**Comment by rstm-sf** [comment]
Adding Pharmacist.MsBuild did not help, although it seems like the necessary assembly is located there

```xml
<PackageReference Include="Pharmacist.MsBuild" Version="2.0.6" />
```

**Comment by worldbeater** [comment]
Modified the project file as such:
```xml
<PackageReference Include="Pharmacist.Core" Version="2.0.6" />
<PackageReference Include="ICSharpCode.Decompiler" Version="7.0.0.6291-preview2" />
```
And got the following exception:
```
[1/2] ArgumentNullException: Value cannot be null. (Parameter 'genericType')
   at ICSharpCode.Decompiler.TypeSystem.ParameterizedType..ctor(IType genericType, IEnumerable`1 typeArguments)
   at Pharmacist.Core.Generation.ReflectionExtensions.GetRealType(IType type, ICompilation compilation) in D:\a\Pharmacist\Pharmacist\src\Pharmacist.Core\Generation\ReflectionExtensions.cs:line 142
   at Pharmacist.Core.Generation.ReflectionExtensions.GetEventType(IEvent eventDetails) in D:\a\Pharmacist\Pharmacist\src\Pharmacist.Core\Generation\ReflectionExtensions.cs:line 108
   at Pharmacist.Core.Generation.Resolvers.EventNamespaceResolverBase.IsValidParameters(IEvent eventDetails) in D:\a\Pharmacist\Pharmacist\src\Pharmacist.Core\Generation\Resolvers\EventNamespaceResolverBase.cs:line 32
   at Pharmacist.Core.Generation.Resolvers.PublicEventNamespaceResolver.IsValidEvent(IEvent x) in D:\a\Pharmacist\Pharmacist\src\Pharmacist.Core\Generation\Resolvers\PublicEventNamespaceResolver.cs:line 132
   at Pharmacist.Core.Generation.Resolvers.PublicEventNamespaceResolver.<>c__DisplayClass1_0.<GetValidEventDetails>b__1(ITypeDefinition typeDefinition) in D:\a\Pharmacist\Pharmacist\src\Pharmacist.Core\Generation\Resolvers\PublicEventNamespaceResolver.cs:line 61
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
```
The Pharmacist error seems to be coming from here https://github.com/reactiveui/Pharmacist/blob/main/src/Pharmacist.Core/Generation/ReflectionExtensions.cs#L142 Probably that's caused by a type argument being `null`.

**Comment by rstm-sf** [comment]
Probably we should disable the NETSDK1138 warning. See also #5301

**Comment by rstm-sf** [comment]
https://github.com/peters/il-repack has been archived by the owner. It is now read-only.

**Pull request closed without merging**
