### PR TITLE
Make miscellaneous Avalonia.Base APIs internal

### PR DESCRIPTION
**Pull request by grokys**
## What does the pull request do?

Made a bunch of APIs in Avalonia.Base internal. Should be mostly uncontroversial - they're generally stuff that won't be useful outside of Avalonia, or are utils that aren't our responsibility.

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0035004-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0035020-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by amwx** [comment]
`KeyboardNavigationHandler` should stay public for now. I definitely use `.GetNext()` as there is no other alternative, at least until a more robust focus API can be implemented. Either that or make `TabNavigation` static class public, but I feel that's even less desirable on your end.

`UpdateIsEffectivelyEnabled()` is used to update the enabled states for controls that implement `ICommand`. How are custom controls that don't derive from an existing control, like `Button` but still implement `ICommand`, now supposed to handle that? Using `IsEnabled` directly has the issue it could be overridden since its public API, and WPF even has `IsEnabledCore` as a protected member.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0035064-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by grokys** [comment]
Thanks @amwx for the feedback - I'll make those APIs public again.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0035109-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0035117-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Pull request merged**
