### PR TITLE
Add ProgressBarAutomationPeer

### PR DESCRIPTION
**Pull request by Takoooooo**
## What does the pull request do?
Started to add automation peers for our controls,the main goal is to have all controls covered with the automation peers. ProgressBarAutomationPeer is a [port](https://github.com/dotnet/wpf/blob/main/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Automation/Peers/ProgressBarAutomationPeer.cs) of WPF version of it in general. I am planning to add integration tests for each control but i can't think of any useful integration tests for progress bars,if someone would have any good ideas i will implement the tests. Tested that ProgressBar plays well now with Windows and MacOS narrators.

## Fixed issues
Part of https://github.com/AvaloniaUI/Avalonia/issues/10143

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0029759-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0029765-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by robloo** [comment]
I thought we needed to add a header for code included from other projects?

**Comment by maxkatz6** [comment]
@robloo good question. I haven't paid attention as this code is as simple as it can be. And other automation classes (supposedly also from there) don't have any headers.

**Pull request merged**
