### PR TITLE
Retain selection when SelectionModel.Source changes if new Source contains selected item(s)

### PR DESCRIPTION
**Pull request by JaggerJo**
## What does the pull request do?

This PR slightly changes the behaviour of the `SelectionModel` to retain the selection even if a new source collection is
assigned - if the source collection still contains the selection. 

## What is the current behaviour?

The selection is lost when `Source` is set, even if the new enumerable contains the / an equivalent item. 

## What is the updated/expected behavior with this PR?

The selection is retained.

## Checklist

- [x] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0017717-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by JaggerJo** [comment]
LeakTests pass locally (on MacOS) 🤨

**Comment by grokys** [comment]
Sorry for the delay @JaggerJo - I'd not noticed this PR. Will take a look now and try to work out why tests are failing.

**Comment by JaggerJo** [comment]
> Sorry for the delay @JaggerJo - I'd not noticed this PR. Will take a look now and try to work out why tests are failing.

Thanks. Retaining the current selection if it's still contained in the new source collection would be really handy for F# / FuncUI. Right now it's a bit annoying to work around.

**Comment by grokys** [comment]
Ok, I can confirm that there is a leak after this change:

image

I'll try to work out how to fix it.

**Comment by JaggerJo** [comment]
> Ok, I can confirm that there is a leak after this change:
> 
> image
> 
> I'll try to work out how to fix it.

Thanks!

**Comment by grokys** [comment]
The problem looks to be a conflict between `InternalSelectionModel` and `SelectionModel`.

`InternalSelectionModel` is what is used internally by controls if they don't have a bound `SelectionModel`; it maintains a writable `SelectedItems` collection in case someone wants to use that instead of a `SelectionModel` and uses this to do what you're adding here (retain selection when Source changes).

So my questions are:

- Were you aware that when changing the `Items` on a control which doesn't have a bound `SelectionModel`, the selection should be preserved without this PR?
- If you weren't aware of this, is this not working in some cases?

**Comment by JaggerJo** [comment]
> The problem looks to be a conflict between `InternalSelectionModel` and `SelectionModel`.
> 
> `InternalSelectionModel` is what is used internally by controls if they don't have a bound `SelectionModel`; it maintains a writable `SelectedItems` collection in case someone wants to use that instead of binding `Selection` and uses this collection to do what you're adding here (retain selection when Source changes).
> 
> So my questions are:
> 
> * Were you aware that when changing the `Items` on a control which doesn't have a bound `SelectionModel`, the selection should be preserved without this PR?

It's been a while since I created the PR, so I don't know for sure. 

> * If you weren't aware of this, is this not working in some cases?

There are cases where it does not retain the selection. I can create a small repro.

**Comment by grokys** [comment]
Following up on my last comment: the reason the bare `SelectionModel` doesn't try to do this is:

- There's an overhead in copying the `SelectedItems` when the source changes. `SelectionModel` is designed to work efficiently with e.g. tens/hundreds of thousands/millions of items, and this overhead can be quite high
- So the idea was: if you have a case where you have very many items in a list and you need to avoid storing each selected item in a collection (which is the default behavior with `InternalSelectionModel`)  you'd bind to a `SelectionModel` which is under your control
- In this case, maintaining the selection between source changes is opt-in and you'd do it manually - there may be more efficient ways to do this if you know the domain of your data

**Comment by grokys** [comment]
> There are cases where it does not retain the selection. I can create a small repro.

Please!

**Comment by JaggerJo** [comment]
[Repro.zip](https://github.com/AvaloniaUI/Avalonia/files/8554912/Repro.zip)
CleanShot 2022-04-25 at 15 27 25

**Comment by grokys** [comment]
Ok, the problem seems to be in this method: https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Controls/Selection/InternalSelectionModel.cs#L298-L310

`source` is this case is an instance of `FSharpList<Person>` which doesn't implement `IList`, so it's failing to find the selected item to restore it. We can't use e.g. `IReadOnlyList<T>` because we don't know the type of `T`; we're working only with `object`s at this level.

I'm going to close this PR because I think it's unnecessary given my findings - if you could open an issue maybe we can work out how to handle this better (maybe we need to handle `IStructuralEquatable`?)

**Pull request closed without merging**
