### PR TITLE
fix: Missing quality parameter

### LINKED ISSUE #12493: `quality` parameter is ignored in `Bitmap.Save` with `.jpg`
**Describe the bug**
The parameter does not appear to have any effect and no warning is reported.

**To Reproduce**

1. Create a new `Bitmap` (I used `WriteableBitmap`) of ~1920x1080
2. Fill it with non-trivial data
3. Call `bitmap.Save("test.jpg", quality: 10)` (I also tried 1)

**Expected behavior**
You get a low quality version of the bitmap weighting under 100KB

**Actual behavior**
You get a high quality file over 1MB in size.
It appears the resulting file is actually a PNG instead of JPEG.

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: Windows
- Version 11.0.2

### PR DESCRIPTION
**Pull request by workgroupengineering**
## What is the current behavior?

- quality parameter is ignored in `Bitmap.Save`

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Fixed issues

Fixes #12493

### CODE REVIEW

**Comment by workgroupengineering** [comment]
This PR partial resolve Issue https://github.com/AvaloniaUI/Avalonia/issues/12493.

the remaining problem is with the save format.
Decode the type based on the file extension, add a parameter that identifies the format.

I can't decide which is the best choice. What do you think in the @avaloniaui-team ?

**Comment by kekekeks** [comment]
Neither is the best, it should be handled in the same way as in WPF - BitmapEncoder API, but async. The whole `Save` method was a stopgap measure that stayed as is for years.

**Comment by workgroupengineering** [comment]
> Neither is the best, it should be handled in the same way as in WPF - BitmapEncoder API, but async. The whole `Save` method was a stopgap measure that stayed as is for years.

They were ideas for not adding breaking change.

What do you think if I mark the save method as obsolete, and in a second PR implement BitmapEncoder.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0038636-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by jmacato** [comment]
Closing this PR temporarily due to inactivity. Please ping me if this needs to be reopened.

**Comment by Gillibald** [comment]
I think we can just merge it

**Review by Gillibald — APPROVED** [review]

**Pull request merged**
