### PR TITLE
Some menu fixes and integration tests.

### LINKED ISSUE #7906: MenuItem steals focus when it gets selected
When pointer enter on MenuItem, it gets selected and steals the focus from inputs  
(happens here: https://github.com/AvaloniaUI/Avalonia/blob/0c63e35f51941b34dd56b903e94592bb83d70ca2/src/Avalonia.Controls/MenuItem.cs#L648)

menu-steals-focus

### PR DESCRIPTION
**Pull request by grokys**
## What does the pull request do?

Fixes #7906. While investigating/fixing it I noticed a couple of other problems:

- Clicking on a top-level menu item and then pressing the down arrow didn't select the first child menu item
- If a top-level menu has a single item and the left/right arrow keys were pressed, the item closes and then re-opens causing a flicker

Added integration tests for all of these issues and fixed them.

- Don't focus top-level menu items when selected unless the menu itself is open in `MenuItem` (fixes #7906)
- In `DefaultMenuInteractionHandler`, select the first item when down is pressed if the submenu is open
- In `DefaultMenuInteractionHandler`, when moving left/right from a top-level menu item, check if the newly selected item is the same as the previously selected item before closing/opening

## Fixed issues

Fixes #7906

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019767-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019769-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by MarchingCube — APPROVED** [review]
Looks reasonable to me, tested this locally as well and it behaves better now :)

Not sure if we are tracking this somewhere but trying to use exported menu fallback on menu page is crashing instantly. But this is not related to your PR.

**Comment by grokys** [comment]
@MarchingCube that should have been fixed by https://github.com/AvaloniaUI/Avalonia/pull/7954 I think?

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019859-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by danwalmsley** [comment]
lots of conflicts on backport. if this is needed for stable please provide an implementation for stable.

**Pull request merged**
