### PR TITLE
Update SkiaSharp to 3.0.0-alpha.1.7

### PR DESCRIPTION
**Pull request by wieslawsoltes**
This is only for testing and to get NuGet's

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0038619-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by adirh3** [comment]
@wieslawsoltes Not sure if you're planning to keep this PR, but sharing some findings for the sake of documentation (based on 3.0.0-nightly.13) -
As you might know images look worse now, this seems to be fixed when using non-default sampling options when drawing to `SKCanvas` with `new SKSamplingOptions(SKFilterMode.Linear, SKMipmapMode.Linear)`.
Passing `SKSamplingOptions` seems to be supported only for `SKImage`, and not `SKBitmap` like Avalonia uses in `WriteableBitmapImpl`.

**Comment by wieslawsoltes** [comment]
> @wieslawsoltes Not sure if you're planning to keep this PR, but sharing some findings for the sake of documentation (based on 3.0.0-nightly.13) - As you might know images look worse now, this seems to be fixed when using non-default sampling options when drawing to `SKCanvas` with `new SKSamplingOptions(SKFilterMode.Linear, SKMipmapMode.Linear)`. Passing `SKSamplingOptions` seems to be supported only for `SKImage`, and not `SKBitmap` like Avalonia uses in `WriteableBitmapImpl`.

I will keep the PR open for time being, I did not put more work fixing some obsolete things, one of which is migrating to sampling options. Any help here is wanted :)

**Comment by adirh3** [comment]
> I will keep the PR open for time being, I did not put more work fixing some obsolete things, one of which is migrating to sampling options. Any help here is wanted :)

Sure thing :) pushed my changes here - https://github.com/AvaloniaUI/Avalonia/pull/12729
You can take these changes or we can keep my branch, but there are still few open questions -
- Why `WriteableBitmapImpl` using `SKBitmap` instead of `SKImage`?
- Why `ImmutableBitmap` keeping both `SKBitmap` and `SKImage`?

**Comment by jmacato** [comment]
Closing this PR temporarily due to inactivity. Please ping me if this needs to be reopened.

**Pull request closed without merging**
