### PR TITLE
Fix UseLayoutRounding calculations.

### LINKED ISSUE #3467: CheckBox looks weird on a HiDPI display
I have a 4k display on Windows, here're my display settings (notably, 150% scale):
image

If I start ControlCatalog.NetCore from dbc66b7787f1667d8f26da6c630cd83ffbb41f4c (today's master), check boxes from the CheckBox page looks visibly acentric:
image

The same page looks fine if I move if to another display (the one with low DPI/100% scale):
image

### PR DESCRIPTION
**Pull request by grokys**
## What does the pull request do?

Ported `RoundLayoutSize` and `RoundLayoutValue` from WPF and use these to calculated layout rounding.

This fixes the misalignment of indeterminate checkboxes reported in #3467.

In doing so, I had to remove `UseLayoutRounding` on `ScrollBar` - its default size of 18 with a thumb size of 8 can't be laid out to device pixels with a scaling of 1.5x. Previously, the thumb had more space on the right than the left, with this change it had more space on the left than the right. For some reason though it was more noticably offset with the space on the left. We may need to change the default sizes for `ScrollBar`.

## What is the current behavior?

image

## What is the updated/expected behavior with this PR?

image

## Checklist

- [x] Added unit tests (if possible)?
- [x] Added XML documentation to any related classes?

## Fixed issues

Fixes #3467.

### CODE REVIEW

**Comment by MarchingCube** [comment]
Ah, I was seeing this issue for a while I was working on a 4K monitor and I suspected haywire rounding :)

**Review by danwalmsley — APPROVED** [review]
LGTM as in, tried it on both Windows and Mac and both I could see an improvement.

**Comment by grokys** [comment]
@danwalmsley I actually committed an experiment in the previous version that didn't disable layout rounding for scrollbars, so they were misaligned. Just force pushed the correct version if you want to just check again.

**Comment by danwalmsley** [comment]
@grokys yes tested again, I cant notice any difference on scrollbars myself, but definately better on the other stuff.

**Pull request merged**
