### PR TITLE
Hit testing fix and support for horizontal wheel scroll

### PR DESCRIPTION
**Pull request by donandren**
-hit testing fix for items not in visible part handling mouse events
-support for horizontal wheel scroll

### CODE REVIEW

**Comment by grokys** [comment]
> hit testing fix for items not in visible part handling mouse events

Could you explain more about this? Is there an issue files, or a unit test failure that I can look at?

**Comment by donandren** [comment]
1. support of horizontal wheel :
At my laptop mouse pad I can make horizontal scroll on any application (explorer, chrome etc.).
In avalonia if we have a horizontal content with scroll viewer the same mouse pad action are not making the content to scroll left/right - this PR is making that possible.

2.Hit testing problem fixed
In vertical listbox with scroll without virtualization with 100 items, but the listbox is restricted by it's bounds, so it shows only 10 and you can scroll up and down, let's say that the visible items are from 10-20.
It was possible to click on item 0-10 that are not visible in the visible part of the listbox content.
So other  controls outside the listbox were unable to process the mouse events because of that.

There are no issues about those, but I've noticed it and tryied to fix them.

**Comment by grokys** [comment]
> 1. support of horizontal wheel

Yes, this should be supported.

> 2. Hit testing problem fixed

I still don't understand what the problem is here, sorry. Would it be possible to write a unit test that demonstrates it? Or even a video that shows what's happening.

Anyway, the two fixes should be placed in separate PRs as it's hard to review like this, and if one isn't quite right it will prevent the other from getting merged.

**Comment by donandren** [comment]
@grokys There was only few lines of code so i tough it could be  faster to be in single PR.
I'll make 2 PR's with both issues separated

**Pull request closed without merging**
