### PR TITLE
Animatable: fix transitions memory leak

### LINKED ISSUE #12860: Animatable: subscriptions to Transitions collection are leaked
**Describe the bug**
The subscription to collection changes made in `OnPropertyChangedCore` method doesn't take into account whether the control was attached to visual tree or not.

https://github.com/AvaloniaUI/Avalonia/blob/050ae370ad02f90b237ce27c869343e628030465/src/Avalonia.Base/Animation/Animatable.cs#L126-L126

For example, you have `TabControl` with two `TabItem`s and the second tab contains a `Button`. But you never activate the second tab and later detach the whole  `TabControl` from visual tree. In this scenario the subscription is made when the `Button` is created but since this `Button` was never attached to visual tree there is no unsubscription when parent control is detached. So the whole parent control can not be garbage collected.

**To Reproduce**
- MainWindow.axaml
```xaml
<Grid RowDefinitions="Auto *">
  <Button Grid.Row="0" Content="Update content" Click="Button_OnClick" />
  <ContentControl Grid.Row="1" Name="contentControl" />
</Grid>
```

- MainWindow.axaml.cs
```cs
private void Button_OnClick(object sender, RoutedEventArgs e)
{
    contentControl.Content = contentControl.Content is null ? new TabbedContent() : null;
}
```

- TabbedContent.axaml
```xaml
<TabControl>
  <TabItem Header="First Item">
    <TextBlock Text="First" />
  </TabItem>
  <TabItem Header="Second Item">
    <Button Content="Second" />
  </TabItem>
</TabControl>
```

1. Click `Update content` button multiple times
2. Force GC and take memory dump
3. See count of `TabbedContent` controls in the memory dump

**Expected behavior**
Detached instances are garbage collected.

**Screenshots**
изображение

**Desktop (please complete the following information):**

- OS: Windows 10
- Version 11.0.4

### PR DESCRIPTION
**Pull request by DmitryZhelnin**
## What does the pull request do?
Fixes memory leak in `Animatable`.

## What is the current behavior?
Sometimes subscriptions to `Transitions` collection changes are leaked.

## What is the updated/expected behavior with this PR?
Leaks are fixed.

## How was the solution implemented (if it's not obvious)?

Subscription is made only if control is already attached to visual tree.

## Fixed issues
Fixes #12860

### CODE REVIEW

**Review by damian-666 — COMMENTED** [review]
@kekekeks    can you help me on this if im speaking out of turn or making wrong assumptions, i just making  a very general suggestion and someone with a lot of history has to be a sort of code police and nnone wants to be that "fault finder".. but   its for everyones benefit.  

 TDLR  my suggestion are at the bottom :  its jsut i've owned wpf  code and its get to where sometime you want to rewrite it  so unmanagleble and delicate .. .im there now.with my own wpf IDE project.   and thats why im looking at avalonia   again.  

im new here  but was in industry 15 years in Silicon valley and game tooling and we had alot of UI.. and otehr compandies including my own., with wpf tooling..  owning code  just get more expensive as it grows ..  i am seeing signs of code churn and too mjch state management..  ive watched in for 10 years its getting very amazing but.. its got 3 ways to do ui and 7 platorms thats amazing but.. its scary.

one thing i llook for is symmetry.. and redunancy. 
noone wants to break anything so they tend to add fixes and state to represent the conditions under which the bug happens..  or leave existing state there when it should not be needed.   but that adds exponential complexity.    they dont wanna destroy anyones work .  

the "dependency property "was added to UIElement when its not real data.   so whenever possilbe shouid be used.    (Please verify i dont know react)


  also overdetermination.. means too many variables that can be a function or a query or a combination  of another essential one(s) state , meaning its redundant   .   the best fix removes code especially state that represents a visualization.. thie wpf paradigm means bind to  actual **( persistent)** data members via properties,   the lifetime of the data  either as  a setting or in a file.**     .  
  
   its means careful review and wide understanding, but not in every case.. anyone can  try to change a base class.    if that class has an antipattern related to the bug(s) they wann fix.   jsut test all the samples..   sometiems breaking fxing a thing , breaking 5 other things, is ok if you can fix all that by simplification  unless you are close to a release or on a master branch.   like this is..
   
   
_transitionsEnabled ?    its his real data?   is it needed?  it it a dependency property..  is there another way to query it..

_isSubscribedToTransitionsCollection    


  newTransitions.CollectionChanged += TransitionsCollectionChangedHandler;
                    _isSubscribedToTransitionsCollection = true;
                    
                    can you just do  newTransitions.CollectionChanged -= TransitionsCollectionChangedHandler;    somehwere.. its not going to do anything if not subcribed to is own handler.. then remove _isSubscribedToTransitionsCollection     my staff idd that to fix leaks an i never have a problem..   if you unlisten twice its not a big deal... its not null..   however. on a massive grid it could be slow... i am not sure..   i
                    
                     also i dont know OSS etiquette tell me when or where to be quiet .. im not invested in this yet.

**Comment by timunie** [comment]
@damian-666 we are totally aware of the need to refractor some areas. If you have followed the development of v11 vs 0.10.x, you probably have seen the many breaking changes we introduced. One of the motivation doing that was to get a more stable API while still allowing us to do needed refracturing later on. Still there are some area for improvement, so your contribution is welcome.

**Comment by damian-666** [comment]
Thanks, I looked  over the code in the base class and its seems like it's ok.     i'll be aware that you already bit the bullet  v10 to v11.     and il plan to build from the develop branch as things stabilize, and i probably will be on net8 or 9 by the time i really transtiion to this..    i watched on and off  it since 2017

  some old apis can be marked  [deprecated]  or hide it  to completion .. spit a warning it they still use it.. that can save alot of suffering on clients.. thta use closed parts and cant update binaries..
  
i see teh 
  OnPropertyChanged and I would be afraid to touch this, this type of nested listening in this mehtod,  gives me intractable trouble in my wpf code.        the order of method calls will be different in different platforms  so its just reality.  
  
  
    -maybe- _isSubscribedToTransitionsCollection can be removed but

the two ways according to SE   are  puting   -= then += to avoid double notification. or uisng  the adding of the extra state as it was done here  

https://stackoverflow.com/questions/3597950/how-can-i-check-if-an-event-has-been-subscribed-to-in-net

i like the business model, of this project, so  i wont get burned by closed sources again.. rahter pay for consulting..to gurus

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0039507-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0039616-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]

**Pull request merged**
