### PR TITLE
Fix window activation on Windows platform.

### LINKED ISSUE #2975: Window Activate not work on Win7
If window in any not focused state: minimized, other app in front, then i try to use code from WPF:
```
        var mainWindow = lifetime.MainWindow;
        if (mainWindow != null)
        {
          mainWindow.Show();
          mainWindow.Activate();
          if (mainWindow.WindowState == WindowState.Minimized)
            mainWindow.WindowState = WindowState.Normal;
        }
```
Work only for minimized state, bring to front not work.
Related #2398, but i check on windows7
Linux not checked.

### PR DESCRIPTION
**Pull request by cocacola89**
Use SetForegroundWindow() with fallback to SetActiveWindow() for window activation on Windows platform.

## What does the pull request do?
Fixes (hopefully) window activation on Windows platform.

## What is the current behavior?
Calling `Window.Activate()` causes activation only if other window of the same app is active.

## What is the updated/expected behavior with this PR?
Calling `Window.Activate()` causes activation if other window of the same app is active 
OR causes window's taskbar item flashing otherwise. 

## How was the solution implemented (if it's not obvious)?
Use `SetForegroundWindow()` function with fallback to previously used `SetActiveWindow()` function.

## Breaking changes
None

## Fixed issues
Fixes #2975

### CODE REVIEW

**Comment by danwalmsley** [comment]
Nice one! I will test this out, will be good to get this fix in the 0.9 release.

**Comment by danwalmsley** [comment]
@cocacola89 I just tested on windows 10, and i dont get the flashing in the task bar?

**Comment by cocacola89** [comment]
> @cocacola89 I just tested on windows 10, and i dont get the flashing in the task bar?

That's odd.

As I wrote in [#2975](https://github.com/AvaloniaUI/Avalonia/issues/2975) I could not test it properly, so that may be the case.

On the other hand, the fix is pretty straightforward, and the extension method I attached in  [#2975](https://github.com/AvaloniaUI/Avalonia/issues/2975) seems to work just fine.

I would add a little clarification on the expected behaviour:
 - if any non-modal window of the same app is already active `Window.Activate()` does not lead to flashing taskbar item - window should get activated right away;
- if there is no active window (e.g. all windows of all apps are minimized) and you set `Window.WindowState = WindowState.Normal` before `Window.Activate()` - this window should become active without flashing taskbar item;
- if there is some active window owned by another app (e.g. Explorer window), `Window.Activate()` should lead to taskbar flashing.

I'm also using Windows 10 and a workaround extension method I provided.

What is the test-case in which you don't get taskbar item flashing?
Does the extension method from [#2975](https://github.com/AvaloniaUI/Avalonia/issues/2975) perform any different?

**Comment by grokys** [comment]
@danwalmsley any more feedback on this?

**Comment by grokys** [comment]
@danwalmsley ping. Do we want to get this in 0.9?

**Comment by danwalmsley** [comment]
@grokys finally updated this... iv tried things like:

1) run the app with code so after 10 secs it will call Activate.
2) minimize the app as soon as it load.
3) goto another app like vs,and start typing code.
4) it doesnt do any flashing... 

seems flashing is covered by flashwindowex and isnt anything to do with Activate...
https://pietschsoft.com/post/2009/01/27/csharp-flash-window-in-taskbar-via-win32-flashwindowex

**Comment by nathanAjacobs** [comment]
Why was this never merged into the repo? Without it, a window that is behind another app when Activate() is called does not come to the foreground, it remains behind the other app. With this fix, the app correctly comes to the foreground when the app is behind other apps and Activate() is called.

**Comment by jmacato** [comment]
@nathanAjacobs i think this needed a viable repro so @danwalmsley could verify the bug report. If you happen to have a step by step or a repro project we can test then this could be reused/reopened

**Comment by nathanAjacobs** [comment]
@jmacato @danwalmsley Here is the link to the repro project: [https://github.com/nathanAjacobs/AvaloniaWindowBug](url)

How to reproduce:
1. Run the app from Visual Studio on Windows.
2. Select another application so the other app takes focus (the AvaloniaWindowBug app should now be behind another app).
3. Click the tray icon in the system tray.
4. The AvaloniaWindowBug app remains behind the other app :(

How to test fix:
1. In the App.axaml.cs class, change the useFix bool to true.
2. Run the app from Visual Studio on Windows.
3. Select another application so the other app takes focus (the AvaloniaWindowBug app should now be behind another app).
4. Click the tray icon in the system tray.
5. The AvaloniaWindowBug app correctly comes to the front :)

Bonus:
It seems that when the tray icon uses a context menu to restore the window, this fix is not needed. Probably because the app technically has focus when the context menu is shown. However this fix is still necessary. Because, if I want to restore the window just by clicking the tray icon with the left mouse button and add a context menu for other functionality when the icon is right clicked, it will not work without this fix.

1. In the App.axaml.cs class, change the useFix bool back to false.
2. In the App.axaml.cs class, change the useContextMenu bool to true.
2. Run the app from Visual Studio on Windows.
3. Select another application so the other app takes focus (the AvaloniaWindowBug app should now be behind another app).
4. Click the tray icon in the system tray.
5. Click "Open AvaloniaWindowBug"
5. The AvaloniaWindowBug app correctly comes to the front without using the fix.

**Comment by tvass83** [comment]
@danwalmsley, @grokys Can we expect a fix for this in the near future? It is still not working as expected in v0.10.10.

**Comment by danwalmsley** [comment]
@nathanAjacobs @tvass83 this was fixed and released in 0.10.8... the repro provided is targettting much older version 0.10.3.

@tvass83 its not clear to me what exactly is not working then?

**Comment by nathanAjacobs** [comment]
@danwalmsley I haven't tried in a recent version yet so I can't say for sure, but have you downloaded the project I linked?

Basically, the problem is that calling Activate() on a window when the avalonia application doesn't have focus does absolutely nothing. With this fix, the window activates even when the avalonia app loses focus.

**Comment by tvass83** [comment]
@danwalmsley Actually you seem to be right, my repro app was misleading me, it is indeed working properly starting from v0.10.8, sorry about the confusion.

@nathanAjacobs essentially your fix made it into 0.10.8:
https://github.com/AvaloniaUI/Avalonia/blob/0c81bb053f3d20e5f803b500c71d758494e54b87/src/Windows/Avalonia.Win32/WindowImpl.cs#L510

**Comment by nathanAjacobs** [comment]
Awesome, glad to see this was implemented!

**Pull request closed without merging**
