### PR TITLE
Updated adorners and hit testing to account for RenderTransforms

### LINKED ISSUE #433: Invalid control Bounds when RenderTransform is applied
I think this also affect the input when using pointer event and `GetPosition` relative to transformed control.

rendertransform

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Pulls the transformation matrix from the rendering layer and stores it for adorners and hit testing. Fixes #433.

### CODE REVIEW

**Comment by grokys** [comment]
This is great. I'm not incredibly happy about adding an attached property to every visual in the scene, but I can't really think of a better solution for now.

Also this still doesn't handle the case where a control is translated outside its parents bounds, as in this test: https://gist.github.com/grokys/0e05708186517f675a17d7b27e0eb89b (we should probably add that test as a skipped test to remind us)

However, this is still a lot better than we have now, and I'm not sure that the two issues with it will be solved easily. I don't know if you considered the parent bounds issue, so I'll let you think about that first, but we should definitely merge this.

**Comment by jkoritzinsky** [comment]
The alternative to the attached property is manually recalculating the transform matrix. I chose a little extra memory usage instead of the matrix recomputation.

For the out of parent bounds issue: Try setting ClipToBounds to false on the panel and try again.

**Comment by grokys** [comment]
The `Panel` is the top-level control, do you mean setting it on the parent `Border`? `Border` has `ClipToBounds = false` by default. I've tried both of those but it makes no difference.

I agree that it's better to use the attached property than recomputing.

The solution I imagined in the end (which I understand is how WPF does it) will be that rendering the scene will build geometry to render on the rendering thread, and that geometry can be used for hit testing. This is a good solution in the meantime however.

**Comment by jkoritzinsky** [comment]
@grokys Looking at the implementation I did again, this implementation is really just building a geometry of the bounds and using that (with the `TransformedBounds` intermediary structure).

**Pull request merged**
