### PR TITLE
Moved render tests for each platform to their own directory.

### PR DESCRIPTION
**Pull request by grokys**
The test .cs files stay in the `Avalonia.RenderTests` directory but the D2D and Skia render test .csprojs are moved to their own directory: include the test files by using a glob in the .csproj.

This avoids the hack we were having to do to get `BaseIntermediateOutputPath` to work - we no longer have this problem as now each .csproj has its own directory, it can use the default directory for intermediate files.

### CODE REVIEW

**Comment by grokys** [comment]
I did this because ncrunch was choking on the hack we were having to do previously which just got too annoying.

**Comment by grokys** [comment]
I've updated the cake script but the skia render tests are still failing because the test dll is being run from `` instead of `` and so the `TestFiles aren't . Any idea why this would be @jkoritzinsky @wieslawsoltes @kekekeks ?

**Comment by grokys** [comment]
The problem seems to be this: https://github.com/cake-build/cake/issues/900. However updating cake doesn't seem to fix it. Investigating more...

**Comment by grokys** [comment]
@jkoritzinsky fixed the build problems, how does this look to you now?

**Comment by jkoritzinsky** [comment]
LGTM!

**Review by jkoritzinsky — APPROVED** [review]

**Pull request merged**
