### PR TITLE
Updated packages used by tests

### PR DESCRIPTION
**Pull request by jp2masa**
## Changes

- Updated packages used by tests
- Fixed renderer test parameter type (it was nullable and inline data was int, and the conversion stopped working; the type was wrong anyway, because the pen couldn't be null)

### CODE REVIEW

**Comment by jp2masa** [comment]
The tests seem to be failing because the latest `xunit.runner.visualstudio` doesn't support `net461`, only `net462`. Would it be fine to update tests to `net462`?

**Comment by maxkatz6** [comment]
> Would it be fine to update tests to net462?

Yes.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0029618-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0029688-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Pull request merged**
