### PR TITLE
Android: Force punch a hole in the SurfaceView to workaround issue #9230

### LINKED ISSUE #9230: Rendering exception on Android
The interface is not refreshed, the default is dark gray, and the interface will be refreshed normally after clicking on the input box.

image
image
image

MyPhone: OnePlus 8Pro
Soc: Qualcomm 865
System: Color OS13.0 (based Android 13)

### PR DESCRIPTION
**Pull request by tristanlabelle**
## What does the pull request do?
It fixes #9230 , see current behavior below.

## What is the current behavior?
On some physical Android devices like my Pixel 4 running Android 13, apps render as plain gray after the initial Splash screen transition. After switching to a different app and switching back, the app renders properly. This does not repro in the emulator.

## What is the updated/expected behavior with this PR?
The app should render properly after the Splash screen on previously affected devices.

## How was the solution implemented (if it's not obvious)?
Force the SurfaceView to punch a hole in its canvas so the surface below can be seen by overriding `dispatchDraw`.

## How tested
Ran `MobileSandbox.Android` on:
- Physical Google Pixel 4 running Android 13
- Emulated Pixel 5 running Android 6
- Emulated Pixel 5 running Android 13

In all cases, the app rendered properly immediately after the Splash screen.

## Checklist
- [ ] ~Added unit tests (if possible)?~ Probably impossible?
- [ ] ~Added XML documentation to any related classes?~ Does not apply
- [ ] ~Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation~ Does not apply

## Breaking changes
None

## Obsoletions / Deprecations
None

## Fixed issues
Fixes #9230

### CODE REVIEW

**Comment by tristanlabelle** [comment]
@emmauss Here's a PR for the workaround I mentioned on Telegram.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0025811-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by kekekeks — APPROVED** [review]

**Comment by danwalmsley** [comment]
@tristanlabelle thank you so much for this! awesome!

**Comment by tristanlabelle** [comment]
@danwalmsley / @kekekeks My pleasure :). I imagine tests are not supposed to take 9h to run? And the build failed for unrelated reasons after merging back with master. How can we kick it back into track?

**Comment by maxkatz6** [comment]
@tristanlabelle CI was unstable with the release of .NET 7. Some of the preview workload builds didn't worked. We are upgrading it to the stable release now, should be better.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0025879-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0025889-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
