### PR TITLE
Feature/Fluent TabControl

### PR DESCRIPTION
**Pull request by maxkatz6**
## What does the pull request do?

image
image
image
image

### CODE REVIEW

**Comment by maxkatz6** [comment]
Since this style is based on UWP's Pivot, it brings some specific style details:
1. Bigger header's font
2. Content margin (you can see it here, pink padding on left and right: https://asp-net-example.blogspot.com/2016/11/uwp-simple-pivot-example.html)

Probably Margin should be removed, because it could be uncomfortable for developers to migrate to new style. @danwalmsley 

Also:
1. It seems TabControl can use TabStrip internally. And TabItem could inherit TabStripItem. Right now it duplicates 100% of style.
2. I will remove unused resources, rename rest of "Pivot*" to "TabControl*" and add new Avalonia specific later.

**Review by danwalmsley — APPROVED** [review]
Tested and L*awesome*TM

**Comment by robloo** [comment]
I'm a little confused by this control. As noted, it appears more like UWP's Pivot (and it using those style resources). Is this going to cause confusion down the road when a full TabView control is needed? There are a lot of features in a TabView not covered here.

 * https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/tab-view
 * https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/tabview

Should this control be renamed?

**Comment by maxkatz6** [comment]
@robloo 
TabControl in Avalonia and WPF is not same as TabView in WinUI.
TabView is way more complex control, and while it should be possible to improve existed TabControl (by rewriting it from the scratch), I believe there should be some light-weight tabbed control. And just imho, it isn't same control, even though with similar name.

This control was named as "TabControl" in WPF, and is familiar for developers.
In same time Pivot looks and works in similar way, but is limited with Top view and has better touch experience.
This style from PR is based on Pivot, but also it is the common style of tabbed controls in Fluent design (see also [NavigationView](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview) left and top modes).

But I agree. WinUI doesn't have such a problem - it have never had control named "TabControl" (there is Pivot and MasterDetailsView instead), so TabView is not conflicted with anything. Avalonia could have complex browser-like TabView in future.
So it is good point to decide now, if we should rename TabControl.

FYI @danwalmsley

**Comment by maxkatz6** [comment]
In WinUI there are NavigationView and TabView, but Pivot still could be used as light-weight control and is easier to restyle. Also it supports swipe navigation (NavView and TabView don't).
I am not still sure, if Avalonia needs to rename TabControl to Pivot. In this case it should also migrate other features.

Right now there is TabControl with Fluent-like selected indicator. Not Pivot, not TabView.

**Comment by Gillibald** [comment]
Implementing all TabView features on top of TabControl shouldn't be that hard. I don't think we should rename all controls to match WinUI's naming.

**Comment by robloo** [comment]
I guess my concern is there is a big conceptual difference between a Pivot and TabView in WinUI. There is a use case for both situations.

Pivot : Lightweight view that simply cycles through different views represented by a header
TabView : A full-featured tabbed interface. It's possible to close tabs, move tabs, tear tabs off into a new window, etc. This, like NavigationView, is one of the ways an app can layout the main user interface.

I think it's important to decide if TabControl will be one or the other. I certainly don't think it should be both -- I don't care so much about the name.

**Comment by robloo** [comment]
Separately, with the left/right styles above. What happens with right-to-left vs left-to-right languages? The indicator should actually switch sides.

**Comment by Gillibald** [comment]
Y it should but we currently don't have FlowDirection support

**Comment by danwalmsley** [comment]
We could rename it, but only at the point that someone implements a real `TabControl` as people are already using this.

**Pull request merged**
