### PR TITLE
Fix CefNet.Avalonia Compat

### PR DESCRIPTION
**Pull request by AigioL**
## What does the pull request do?
https://github.com/AvaloniaUI/Avalonia/commit/ca408e55b5091449158cfae7536960464389f6fd Breaking the compatibility
[CefNet.Avalonia](https://www.nuget.org/packages/CefNet.Avalonia) required cursor handle.
https://github.com/CefNet/CefNet/blob/master/CefNet.Avalonia/Internal/CursorInteropHelper.cs#L18

## What is the current behavior?
```
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'CefNet.Internal.CursorInteropHelper' threw an exception.
  Source=CefNet.Avalonia
  StackTrace:
   在 CefNet.Internal.CursorInteropHelper.Create(IntPtr cursorHandle)
   在 CefNet.Internal.AvaloniaWebViewGlue.OnCursorChange(CefBrowser browser, IntPtr cursorHandle, CefCursorType type, CefCursorInfo customCursorInfo)
   在 CefNet.Internal.CefDisplayHandlerGlue.OnCursorChange(CefBrowser browser, IntPtr cursor, CefCursorType type, CefCursorInfo customCursorInfo)
   在 CefNet.CefDisplayHandler.OnCursorChangeImpl(cef_display_handler_t* self, cef_browser_t* browser, IntPtr cursor, CefCursorType type, cef_cursor_info_t* custom_cursor_info)

内部异常 1:
MissingMethodException: Method not found: 'Avalonia.Platform.IPlatformHandle Avalonia.Input.Cursor.get_PlatformCursor()'.
```

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=5763) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=5763) before we can accept your contribution.<br/><br/>:x: AigioL [sign now](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=5763)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/AvaloniaUI/Avalonia?pullRequest=5763) it.</sub>

**Comment by grokys** [comment]
@kekekeks are we OK exposing `IntPtr` handles in `*Impl` interfaces or should `IPlatformHandle` be used?

**Comment by Gillibald** [comment]
Looks like only the Win32 platform uses a handle the rest rests the property to `IntPtr.Zero` so this change is wrong and redundant `Handle` properties should be removed.

On Win32 just cast to `IPlatformHandle`: https://github.com/AvaloniaUI/Avalonia/blob/master/src/Windows/Avalonia.Win32/CursorFactory.cs#L170

**Comment by AigioL** [comment]
> 看起来只有 Win32 平台使用句柄， 其余的设置属性， 所以这种变化是错误的， 多余的属性应该删除。`IntPtr.Zero``Handle`
> 
> 在Win32刚刚投到[：https://github.com/AvaloniaUI/Avalonia/blob/master/src/Windows/Avalonia.Win32/CursorFactory.cs#L170](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Windows/Avalonia.Win32/CursorFactory.cs#L170)`IPlatformHandle`

It also seems to have influenced macOS and Linux

https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.X11/X11CursorFactory.cs#L72
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.X11/X11CursorFactory.cs#L141
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.X11/X11CursorFactory.cs#L88
https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.X11/X11CursorFactory.cs#L77

Mobile platforms may not need
Maybe should let the desktop implementation classes inherit IPlatformHandle
Or set up two interfaces to distinguish between mobile platform (IMobileCursorImpl) and desktop platform (IDesktopCursorImpl)

**Comment by kekekeks** [comment]
All platform handles should be exposed as IPlatformHandle. In some cases platform handles might be non-representable as a plain IntPtr without additional info.

**Pull request closed without merging**
