### PR TITLE
Update Measure and Layout if a child of RelativePanel updates it's postion

### LINKED ISSUE #10360: RelativePanel does not update Layout in some situations: How do I a Control to e.g. RelativePanel.LeftOf=""  in ViewModel // How do I change alignement in code behind?
### Discussed in https://github.com/AvaloniaUI/Avalonia/discussions/10330

<div type='discussions-op-text'>

<sup>Originally posted by **NoizeDaemon** February 13, 2023</sup>
Hi! I've recently started using AvaloniaUI & I am also still pretty new to MVVM in general... I'm stuck on two things atm:

### 1) Is there a way to bind the Name of Controls/bind a reference to a control by Name?

I'm trying to change relative positions in a `RelativePanel` from my ViewModel (I know thats probably not the MVVM way, so there's question 2):

```
<RelativePanel Grid.Row="1">
	<Rectangle Name="R1" Width="30" Height="30" Fill="White"
		RelativePanel.AlignHorizontalCenterWithPanel="True" RelativePanel.AlignVerticalCenterWithPanel="True"/>
	<Rectangle Name="R2" Width="30" Height="30" Fill="Purple"
		RelativePanel.LeftOf="{Binding LeftOf}"/>
	<Rectangle Name="R3" Width="30" Height="30" Fill="Red"
		RelativePanel.RightOf="R1"/>
</RelativePanel>
```

Binding a string `"R1"` to `LeftOf` does not work (it binds the string, but looking at the debugger `RelativePanel.LeftOf` takes the actual control as value, not the name).

So is there a way I could reference a control by it's name from ViewModel (maybe by means of a ValueConverter?).

Alternatively, can you combine multiple Bindings?
There's binding to controls like `$parent[1]` - if I could do sth like `{Binding $parent[{Binding ChildIndex}]}`, that would solve my problem too 😅

Can the relative position even be changed at runtime?

### 2) What would be the correct MVVM way to do this?

Eventually I want to bind an `ItemsControl` (with a `RelativePanel` as `ItemsPanel`) to a list of classes containing amongst others the relative positions to other items.
So I'd start with R1 in the center of the panel, then add R2 to the right of R1, R3 on above R2, etc.

Any help, tips or good ressources to read would be highly appreciated!

### Update:

Trying to do this in code behind:

```
public partial class MainView : UserControl
    {
        private ItemsControl itemsControl;
        private List<Rectangle> visualNumberItems;

        public MainView()
        {
            InitializeComponent();
            visualNumberItems = new List<Rectangle>();
        }

        void NumberItemsChanged(object? sender, NotifyCollectionChangedEventArgs e)
        {
            visualNumberItems = itemsControl
                .GetLogicalDescendants()
                .OfType<ILogical>()
                .OfType<Rectangle>()
                .ToList();

            if (visualNumberItems.Count == 1)
            {
                RelativePanel.SetAlignVerticalCenterWithPanel(visualNumberItems[0], true);
                RelativePanel.SetAlignHorizontalCenterWithPanel(visualNumberItems[0], true);
            }
            else if (visualNumberItems.Count > 1)
            {
                RelativePanel.SetRightOf(visualNumberItems[visualNumberItems.Count - 1], visualNumberItems[visualNumberItems.Count - 2]);
            }
        }

        void NumberItemsControlLoaded(object? sender, RoutedEventArgs e)
        {
            itemsControl = (ItemsControl)sender;
            ((INotifyCollectionChanged)itemsControl.Items).CollectionChanged += NumberItemsChanged;
        }
    }
```

The values for the first Rectangle change, but do not visually update.
The values for the other Rectangles don't even change (see Debugger screenshots).
All the Rectangles are stuck in the upper left corner.

Here's my new XAML:

```
<ItemsControl Name="numberItemsControl" Grid.Row="1"  Items="{Binding NumberItems}" Loaded="NumberItemsControlLoaded">
		<ItemsControl.ItemsPanel>
			<ItemsPanelTemplate>
				<RelativePanel/>
			</ItemsPanelTemplate>
		</ItemsControl.ItemsPanel>
		<ItemsControl.ItemTemplate>
			<DataTemplate>
				<Rectangle Width="50" Height="50" x:Name="{Binding Name}" Fill="White"
							Tag="{Binding Tag}"/>
			</DataTemplate>
		</ItemsControl.ItemTemplate>
</ItemsControl>
```

If I could get that to work, I could potentially change their position based on the Tag I set in my ViewModel...

image

image

Also is there a way to get only the last added descendant/visual item? I only found options for the first or, like i did here, all of them...
</div>

### PR DESCRIPTION
**Pull request by timunie**
## What does the pull request do?

Change the way a RelativePanel reacts if a child changes it's position

## What is the current behavior?

Only the initial value is respected unless one forces the Panel to update

## What is the updated/expected behavior with this PR?

It's now possible to update the position of any child

## How was the solution implemented (if it's not obvious)?

Use `AffectsParentArrange` and `AffectsParentMeasure` for all position properties

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Fixed issues
Fixes #10360 

//cc @danwalmsley as you seem to be the one who implemented this control back then 
@NoizeDaemon can you test this PR in your sample App and give me a feedback, if your issue is solved?

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0030108-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by NoizeDaemon** [comment]
> 11.0.999-cibuild0030108-beta

This is my first time installing a prebuild.

I first set the packages source manually and then updated through the package manager. Then I had build errors.
Then I reverted the changes and used the console instead:  `Install-Package Avalonia -Version 11.0.999-cibuild0030108-beta`

Still getting build errors:

```
2>------ Build started: Project: MinimalSample.Desktop, Configuration: Debug Any CPU ------
2>Skipping analyzers to speed up the build. You can execute 'Build' or 'Rebuild' command to run analyzers.
2>D:\Coding\Small Projects\MinimalSample\MinimalSample.Desktop\Program.cs(19,18,19,35): error CS0311: The type 'Avalonia.AppBuilder' cannot be used as type parameter 'TAppBuilder' in the generic type or method 'AppBuilderDesktopExtensions.UsePlatformDetect<TAppBuilder>(TAppBuilder)'. There is no implicit reference conversion from 'Avalonia.AppBuilder' to 'Avalonia.Controls.AppBuilderBase<Avalonia.AppBuilder>'.
2>D:\Coding\Small Projects\MinimalSample\MinimalSample.Desktop\Program.cs(19,18,19,35): error CS7069: Reference to type 'AppBuilderBase<>' claims it is defined in 'Avalonia.Controls', but it could not be found
2>Done building project "MinimalSample.Desktop.csproj" -- FAILED.
```

Is there something else I need to do when installing prebuilds? (Sorry for the inconvenience!)

**Comment by timunie** [comment]
There may be breaking changes in addition. Let me try.

**Comment by timunie** [comment]
Sent you a PR to your sample with this PR as package version. Somehow proposal 3 doesn't work for me.

**Review by NoizeDaemon — APPROVED** [review]
The RelativePanel is now correctly updating when binding values change.
No more need to manually call InvalidateArrange()! 👍

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0030158-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0030188-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Pull request merged**
