### PR TITLE
Add ColorPicker Default ControlThemes

### PR DESCRIPTION
**Pull request by robloo**
# What does the pull request do?

Converts the ColorPicker's Default Styles to use ControlThemes. This includes the primitives ColorSpectrum, ColorSlider and ColorPreviewer.

Includes changes discussed starting here: https://github.com/AvaloniaUI/Avalonia/pull/8587#issuecomment-1198976395

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0022669-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by robloo** [comment]
This one is ready for review and merge

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0022698-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0022745-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
