### PR TITLE
Use standard Program.cs for samples.

### PR DESCRIPTION
**Pull request by grokys**
## What does the pull request do?

Use a standard Program.cs from our templates for samples.

Also merge ControlCatalog.NetCore into ControlCatalog.Desktop, dual targetting netfx and netcore in the same project.

### CODE REVIEW

**Comment by kekekeks** [comment]
I think single-targeted net core project was there because of full .net targeting issues on non-windows platforms. I'm not sure that they are completely solved.

**Comment by jkoritzinsky** [comment]
With the newly released framework targeting pack NuGet packages, we should be able to alleviate those issues most likely.

**Comment by kekekeks** [comment]
You have also removed /dev/fb0 platform support from the catalog.

**Comment by grokys** [comment]
Ah ok, I thought the problems that required two projects had been solved. Should I restore the dual control catalog projects?

> You have also removed /dev/fb0 platform support from the catalog.

Ah yes, that was only in netcore. I will add that back in.

**Comment by grokys** [comment]
@kekekeks i've reinstated ControlCatalog.NetCore.

**Comment by grokys** [comment]
Closing this as it's out-of-date. We probably want to revisit though.

**Pull request closed without merging**
