### PR TITLE
Fix inserting at index 0 with VirtualizingStackPanel.

### LINKED ISSUE #10769: ItemsControl items won't show
**Describe the bug**
In some cases, inserting/adding new items to an `ObservableCollection` that's bound to a `ListBox` or `ItemsControl` will cause these items to not show.
This seems to be the case consistently when inserting at the index 0.
This also seems to cause a "defective" state for the `VirtualizingStackPanel` causing items to overlap.

**To Reproduce**
In Control Catalog, `ListBoxPageViewModel` change the following - 

Line 23 - 
https://github.com/AvaloniaUI/Avalonia/blob/74d0241e7fefe38d1bfcdbac1a95c2dd50a30578/samples/ControlCatalog/ViewModels/ListBoxPageViewModel.cs#L23
```
Items = new ObservableCollection<ItemModel>(Enumerable.Range(1, 7).Select(i => GenerateItem()));
```
Change to less items to notice anything.

Line 37 - 
https://github.com/AvaloniaUI/Avalonia/blob/74d0241e7fefe38d1bfcdbac1a95c2dd50a30578/samples/ControlCatalog/ViewModels/ListBoxPageViewModel.cs#L37
```
AddItemCommand = MiniCommand.Create(() => Items.Insert(0,GenerateItem()));
````
Change the item to be inserted at index zero.

1. Run Control Catalog
2. Click on ListBox page
3. Click the add item button

**Expected behavior**
Items to be added reliably.

**Screenshots**
This is the overlapping -
image

**Additional context**
Commenting the `if` in line 1094 in `VirtualizingStackPanel` and letting the `else` section always execute, seems to solve the issue.
https://github.com/AvaloniaUI/Avalonia/blob/74d0241e7fefe38d1bfcdbac1a95c2dd50a30578/src/Avalonia.Controls/VirtualizingStackPanel.cs#L1094

@grokys I believe you're the most relevant guy for this (sorry for notification if not)

### PR DESCRIPTION
**Pull request by grokys**
## What does the pull request do?

The was a 🤦 in `VirtualizingStackPanel`. The comment immediately after the check says:

> The insertion point was before the first element, update the first index.

But the check is `<= 0` instead of `< 0`, causing #10769.

## Fixed issues

Fixes #10769

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0032252-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0032308-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0032318-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0032342-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0032368-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Pull request merged**
