### PR TITLE
Rework VNC sessions to support showing other windows and dialogs

### PR DESCRIPTION
**Pull request by almightyju**
## What does the pull request do?
I started wanting to find a way to support using `TopLevel.StorageProvider.OpenFilePickerAsync` which wouldn't work since naturally there is no `IStorageProvider` for VNC so I decided to use the `Avalonia.Dialogs.ManagedFileDialogExtensions` stuff.

This pull request overhalls how VNC sessions work so that other windows can be shown/used.

I'm not sure if this request is outside the scope since the Pausing contributions thing, if so feel free to ignore/close for now.

## What is the current behavior?
Currently showing another window does nothing as the HeadlessVncFramebufferSource is hard coded to the main window. 

## What is the updated/expected behavior with this PR?
Other windows can be shown and interacted with over VNC and when closing the child window/dialog it reverts to the previous window.

## How was the solution implemented (if it's not obvious)?
A `HeadlessVncConnectionManager` is responsible for handling VNC sessions and switching which Window the `HeadlessVncFramebufferSource` uses to get the current frame. The `HeadlessVncConnectionManager` also handles shutdown on the last VNC client disconnection

The `HeadlessVncFramebufferSource` will now fix the frame size to the size of the MainWindow ClientSize, this is because when switching windows it would trigger the frame buffer to be recreated at a different size as part of `Capture()`, during testing it would almost always cause the VNC client to no longer get new frames shown so now it's configurable via `bool resizeBufferIfContentSizeChanges`.

To support using the `ManagedSystemDialogs` an `IMountedVolumeInfoProvider` needs to be registered so an extra extension method has been added to each platform so the VNC stuff can use the managed dialogs.

Side note: during testing I found `WindowsMountedVolumeInfoListener` would cause the connection to hang and running the poll in a background thread fixed it so I've included that here too (can do a separate request if preferred)

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0035994-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by jmacato** [comment]
re-requesting @kekekeks 's review. But IMO concept wise it looks good.

**Comment by maxkatz6** [comment]
I strongly believe we should make ManagedFileDialog work without any windowing available. At least as a popup.

**Comment by maxkatz6** [comment]
Windowing support in VNC sessions is another topic though. I am not knowledgeable enough about VNC to speak about this part.

**Pull request closed without merging**
