### PR TITLE
Register attached property metadata on TOwner instead of THost.

### LINKED ISSUE #11212: AttachedProperty Coercion Callback is not invoked
**Describe the bug**
Coercion Callback is not invoked

**To Reproduce**

1. Add following code to `AvaloniaObjectTests_Coercion`

   ```csharp
        [Fact]
        public void Coerce_AttachedProperty()
        {
            var numberOfCall = 0;
            AttachedPropertyOwnerCoerce.CoerceDoubleCallback = (_) => numberOfCall++;
            var class1 = new Class1();

            class1.SetValue(AttachedPropertyOwnerCoerce.DoubleProperty, 101.1d);

            Assert.Equal(1, numberOfCall);
            Assert.Equal(100d, AttachedPropertyOwnerCoerce.GetDouble(class1));
        }

        private class AttachedPropertyOwnerCoerce
        {
            public static readonly AttachedProperty<double> DoubleProperty =
                AvaloniaProperty.RegisterAttached<AttachedPropertyOwnerCoerce, Class1, double>("Double",coerce: CoerceDouble);

            public static Action<AvaloniaObject> CoerceDoubleCallback;

            public static double GetDouble(Class1 control) => control.GetValue(DoubleProperty);
            public static void SetDouble(Class1 control, double value) => control.SetValue(DoubleProperty, value);

            private static double CoerceDouble(AvaloniaObject instance, double value)
            {
                CoerceDoubleCallback?.Invoke(instance);
                var o = (Class1)instance;
                return Math.Clamp(value, 50d, 100d);
            }
        }
   ```
3. Run `Coerce_AttachedProperty` test

**Expected behavior**
Coercion Callback is invoked

**Screenshots**
(none)

**Desktop (please complete the following information):**

- OS: any
- Version: **11.0.0-preview7**

**Additional context**
Validate Callback is invoked

### PR DESCRIPTION
**Pull request by grokys**
## What does the pull request do?

As described in #11212, attached property coercion was not being applied in some cases because the metadata was being registered to the `THost` control not the `TOwner` control.

Added a test and fixed that.

I think this is the correct fix for this issue (rather than #11330) but need to confirm I've understood the issue correctly.

## Fixed issues

Fixes #11212

### CODE REVIEW

**Review by maxkatz6 — APPROVED** [review]

**Comment by maxkatz6** [comment]
@grokys build is failing

**Comment by grokys** [comment]
> You have THost and TOwner the wrong way round in the PR description. I was doubting my sanity until I checked the code. 😅

Ooops! Fixed ;)

**Comment by grokys** [comment]
Ok, had to change this a little more (as demonstrated by the failing tests): changed to pass both owner and host type to the `AvaloniaProperty` ctor as the metadata needs to be registered on the host, but the `Owner` property still needs to be set to the owner, not the host.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0034766-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Pull request merged**
