### PR TITLE
[Text] Use CultureInfo.Name instead of ISOLanguageName for character matching

### LINKED ISSUE #12349: Wrong default font when show CJK characters
**Describe the bug**

Wrong default font when show CJK characters

for example my computer use Chinese but it show me Japanese font `Yu Gothic UI`

**To Reproduce**

`Microsoft YaHei` is a Chinese font in Windows

```xml
<!--wrong--><TextBlock Text="包直入今骨角房" FontSize="50" />
<!--right--><TextBlock Text="包直入今骨角房" FontSize="50" FontFamily="Microsoft YaHei"/>
```

图片

( Project: [AvaloniaApplication3.zip](https://github.com/AvaloniaUI/Avalonia/files/12180632/AvaloniaApplication3.zip) )

**Expected behavior**

It shoud use Chinese font

**Screenshots**

see above

**Desktop (please complete the following information):**

- OS: Windows 10
- Version 22H2 19045.3208
- Language `中文(简体，中国)` Chinese (Simplified, China)

and same on my friend's computer

- OS: Windows 11
- Version 22H2

**Additional context**

### PR DESCRIPTION
**Pull request by Gillibald**
## What does the pull request do?

It changes character matching to use a full bcp47 language identifier to be able to distinguish between different variants of a language family. The previous solution of specifying a two or three-letter tag wasn't enough to achieve this.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/avalonia-docs with user documentation

## Fixed issues

Fixes: #12349

### CODE REVIEW

**Comment by robloo** [comment]
I know you don't always add docs to your PR descriptions for small changes, but the reasons you are doing this would ideally be documented in code.

When trying to match it seems like ISO codes are better and Name is a good fallback. I wonder if some smarter heuristics using all 3 make sense. Anyway, the more that is documented about why you made this change, based on what findings, the better.

**Comment by Gillibald** [comment]
When I first introduced this part of the font manager I looked at the Skia source and it stated it is generally fine to use the ISO 639 language code so I used them but it looks like DirectWrite does not match font families properly in that case.

We can specify multiple languages so I can just add the new one as you pointed out. Thanks.

**Comment by YexuanXiao** [comment]
> When I first introduced this part of the font manager I looked at the Skia source and it stated it is generally fine to use the ISO 639 language code so I used them but it looks like DirectWrite does not match font families properly in that case.
> 
> We can specify multiple languages so I can just add the new one as you pointed out. Thanks.

Thanks for fixing it. The two-letter and three-letter code are insufficient for users who utilize Chinese, as the current Chinese characters in use have at least three variants (China, China Taiwan, and Japan). They share the same Unicode code points, often represent the same meanings, but have different appearances. ISO 639 cannot distinguish between them.

**Review by maxkatz6 — APPROVED** [review]

**Comment by robloo** [comment]
Really would have commented the main points here in source code. It's lost knowledge if you don't do that for stuff like this and someone in the years to come might change it accidentally.

**Pull request merged**
