### PR TITLE
Upgrade ReactiveUI and System.Reactive

### PR DESCRIPTION
**Pull request by worldbeater**
## What does the pull request do?

ReactiveUI 10 released with [a few breaking changes](https://github.com/reactiveui/ReactiveUI/releases/tag/10.0.1), so worth upgrading the packages.

## What is the current behavior?

`Avalonia.ReactiveUI` depends on an older version of `ReactiveUI`, and that causes issues when sharing code between a .NET Standard library that references latest `ReactiveUI` and with a library that references `Avalonia.ReactiveUI`.

## What is the updated/expected behavior with this PR?

This PR upgrades the following packages:
`System.Reactive`: `4.0.0` -> `4.1.6`
`ReactiveUI`: `9.0.1` -> `10.0.1`

## Checklist

- [x] Correct unit tests
- [x] Correct XML documentation for any related classes

### CODE REVIEW

**Comment by worldbeater** [comment]
Currently the tests are failing only on Windows with the following exception:
```
System.IO.FileLoadException : Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```
Wondering how this relates to ReactiveUI and System.Reactive upgrade, planning to investigate more.

**Comment by worldbeater** [comment]
Absolutely no idea about what happens with the leak tests on the [Windows CI](https://dev.azure.com/AvaloniaUI/AvaloniaUI/_build/results?buildId=3831), on my local Windows machine the tests from the `Avalonia.LeakTests` project pass successfully, and on the CI some of the tests throw the following exception:
```
System.IO.FileLoadException : Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

**Comment by MarchingCube** [comment]
Checked your PR, this happens to me locally as well when I run from nuke. I had to tweak few things to allow for running nuke leak tests locally as current build script crashes for me.

**Comment by jp2masa** [comment]
#2930
The `System.Memory` package needs to be upgraded as well.

**Comment by MarchingCube** [comment]
Also this PR is the same as https://github.com/AvaloniaUI/Avalonia/pull/2930. We should close one and unify the effort in one place. Especially since the other one seems to build now.

**Pull request closed without merging**
