### PR TITLE
Implement binding to methods for compiled bindings

### LINKED ISSUE #4237: CompiledBinding does not work with binding to methods
```
/home/ubuntu/projects/Core2D/src/Core2D.UI/Views/Data/DatabaseControl.xaml(31,42,31,42): Avalonia error XAMLIL: Unable to resolve property of name 'OnApplyRecord' on type 'XamlX.TypeSystem.CecilTypeSystem+CecilType'. (line 31 position 42) Line 31, position 42. [/home/ubuntu/projects/Core2D/src/Core2D.UI/Core2D.UI.csproj]
```

current workaround is to disable compiled bindings for that parts:
```XAML
                        <MenuItem Header="apply" CommandParameter="{Binding CurrentRecord}" IsVisible="{Binding !!CurrentRecord}">
                            <MenuItem.Command>
                                <Binding Path="$parent[Window].DataContext.OnApplyRecord" x:CompileBindings="False" x:DataType="Editor:IProjectEditor"/>
                            </MenuItem.Command>
                        </MenuItem>
```

### PR DESCRIPTION
**Pull request by jkoritzinsky**
## What does the pull request do?

This PR enables using compiled bindings to bind to methods. A compiled binding can now point to a method and the resulting value will either be a delegate or a command (depending on the target type).

## What is the current behavior?

Compiled bindings fail with a compilation error when a method is in the binding path.

## What is the updated/expected behavior with this PR?

Compiled bindings will work when pointed at methods and `ICommand` implementations will be generated when bound to a property of type `ICommand`.

## How was the solution implemented (if it's not obvious)?

 This implements the first integrated "target-typing" in our binding system for bindings as the "method->command" converter for reflection bindings is linker-unsafe and cannot be made linker-safe as-is.

## Checklist

- [X] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Breaking changes

The reflection-based method binding uses `Expression.GetDelegateType` to get the delegate type, which can result in different delegate types being used than the existing implementation for scenarios with 7 or more parameters.

## Fixed issues
Fixes #4237

### CODE REVIEW

**Comment by Takoooooo** [comment]
@jkoritzinsky Tests are failing,please check them

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0017631-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json)

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018393-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018790-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by danwalmsley — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018856-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
