### PR TITLE
Span-ify PathMarkupParser

### PR DESCRIPTION
**Pull request by jkoritzinsky**
- What does the pull request do?
Change `PathMarkupParser` to use `ReadOnlySpan<char>`s instead of regular expressions to parse paths.
- What is the current behavior?
Currently the parser uses regular expressions and data-structures on the heap to parse paths.
- What is the updated/expected behavior with this PR?
Better performance. 

Old perf (from #1661):

``` ini

BenchmarkDotNet=v0.10.8, OS=Windows 10.0.17134
Processor=Intel Core i7-4500U CPU 1.80GHz (Haswell), ProcessorCount=4
Frequency=2338342 Hz, Resolution=427.6534 ns, Timer=TSC
dotnet cli version=2.1.300
  [Host]     : .NET Core 4.6.26328.01, 64bit RyuJIT
  DefaultJob : .NET Core 4.6.26328.01, 64bit RyuJIT


```
 |           Method |     Mean |    Error |   StdDev |   Gen 0 |  Gen 1 | Allocated |
 |----------------- |---------:|---------:|---------:|--------:|-------:|----------:|
 | Parse_Large_Path | 171.5 us | 3.389 us | 5.936 us | 18.3105 | 2.4414 |  37.66 KB |

New perf:

``` ini

BenchmarkDotNet=v0.10.14, OS=Windows 10.0.17134
Intel Core i5-6300U CPU 2.40GHz (Skylake), 1 CPU, 4 logical and 2 physical cores
.NET Core SDK=2.1.300
  [Host]     : .NET Core 2.0.7 (CoreCLR 4.6.26328.01, CoreFX 4.6.26403.03), 64bit RyuJIT
  DefaultJob : .NET Core 2.0.7 (CoreCLR 4.6.26328.01, CoreFX 4.6.26403.03), 64bit RyuJIT


```
|           Method |     Mean |     Error |    StdDev |  Gen 0 |  Gen 1 | Allocated |
|----------------- |---------:|----------:|----------:|-------:|-------:|----------:|
| Parse_Large_Path | 29.60 us | 0.5703 us | 0.5602 us | 0.8850 | 0.2136 |   4.76 KB |

So, this PR uses approximately 13% of the managed memory that the current implementation uses in our benchmark.

### CODE REVIEW

**Comment by grokys** [comment]
Really nice @jkoritzinsky !

**Comment by KvanTTT** [comment]
Did you measure performance on different processors? I see `Intel Core i7-4500U CPU 1.80GHz (Haswell), ProcessorCount=4` in old perf and `Intel Core i5-6300U CPU 2.40GHz (Skylake), 1 CPU, 4 logical and 2 physical cores` in the new one.

**Comment by grokys** [comment]
@jkoritzinsky is this no longer blocked on dependency?

**Comment by jkoritzinsky** [comment]
I don't believe so. The android project build would be failing if it was blocked.

**Review by grokys — APPROVED** [review]

**Pull request merged**
