### PR TITLE
Fix CarouselPresenter's handling of inserted items

### LINKED ISSUE #2432: SelectingItemsControl does not track correctly changes to collection bound to Items
Carousel, TabStrip use SelectingItemsControl and when collection bound to Items changes the views are resolved incorrectly.

Repro (use InsertBeforeView/InsertAfterView buttons):
```XAML
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:local="clr-namespace:ControlCatalog.Pages;assembly=ControlCatalog"
             x:Class="ControlCatalog.Pages.ReproPage">
    <DockPanel>
        <TabStrip Items="{Binding Views}" SelectedItem="{Binding CurrentView, Mode=TwoWay}" Focusable="false" DockPanel.Dock="Bottom">
            <TabStrip.ItemsPanel>
                <ItemsPanelTemplate>
                    <WrapPanel/>
                </ItemsPanelTemplate>
            </TabStrip.ItemsPanel>
            <TabStrip.DataTemplates>
                <DataTemplate DataType="local:View">
                    <StackPanel Orientation="Horizontal" Spacing="2">
                        <TextBlock Text="{Binding Title}" Foreground="Red" Margin="2"/>
                    </StackPanel>
                </DataTemplate>
            </TabStrip.DataTemplates>
        </TabStrip>
        <StackPanel Orientation="Horizontal" Spacing="2" DockPanel.Dock="Top">
            <Button Content="RemoveCurrentView" Command="{Binding RemoveCurrentView}"/>
            <Button Content="AddView" Command="{Binding AddView}"/>
            <Button Content="InsertBeforeView" Command="{Binding InsertBeforeView}"/>
            <Button Content="InsertAfterView" Command="{Binding InsertAfterView}"/>
            <Button Content="RestoreViews" Command="{Binding RestoreViews}"/>
        </StackPanel>
        <Border>
            <Carousel Items="{Binding Views}" SelectedItem="{Binding CurrentView, Mode=TwoWay}" IsVirtualized="False">
                <Carousel.DataTemplates>
                    <DataTemplate DataType="local:View">
                        <Border>
                            <TextBlock Text="{Binding Title}"/>
                        </Border>
                    </DataTemplate>
                </Carousel.DataTemplates>
            </Carousel>
        </Border>
    </DockPanel>
</UserControl>
```
```C#
using System.Linq;
using Avalonia;
using Avalonia.Collections;
using Avalonia.Controls;
using Avalonia.Markup.Xaml;

namespace ControlCatalog.Pages
{
    public class View
    {
        public string Title { get; set; }
    }

    public class ReproPage : UserControl
    {
        public static readonly AvaloniaProperty ViewsProperty =
            AvaloniaProperty.Register<AutoCompleteBoxPage, AvaloniaList<View>>(nameof(Views));

        public static readonly AvaloniaProperty CurrentViewProperty =
            AvaloniaProperty.Register<AutoCompleteBoxPage, View>(nameof(CurrentView));

        public AvaloniaList<View> Views
        {
            get => (AvaloniaList<View>)GetValue(ViewsProperty);
            set => SetValue(ViewsProperty, value);
        }

        public View CurrentView
        {
            get => (View)GetValue(CurrentViewProperty);
            set => SetValue(CurrentViewProperty, value);
        }

        public AvaloniaList<View> CreateViews()
        {
            return new AvaloniaList<View>()
            {
                new View() { Title = "--0--" },
                new View() { Title = "--1--" },
                new View() { Title = "--2--" }
            };
        }
        int count = 3;
        public void RemoveCurrentView()
        {
            Views.Remove(CurrentView);
            CurrentView = Views.FirstOrDefault();
        }

        public void AddView()
        {
            Views.Add(new View() { Title = $"--{count++}--" });
            CurrentView = Views.LastOrDefault();
        }

        public void InsertBeforeView()
        {
            int index = Views.IndexOf(CurrentView);
            Views.Insert(index, new View() { Title = $"--{count++}--" });
            CurrentView = Views[index];
        }

        public void InsertAfterView()
        {
            int index = Views.IndexOf(CurrentView) + 1;
            Views.Insert(index, new View() { Title = $"--{count++}--" });
            CurrentView = Views[index];
        }

        public void RestoreViews()
        {
            Views = CreateViews();
            CurrentView = Views.FirstOrDefault();
        }

        public ReproPage()
        {
            this.InitializeComponent();

            RestoreViews();

            DataContext = this;
        }

        private void InitializeComponent()
        {
            AvaloniaXamlLoader.Load(this);
        }
    }
}
```

https://github.com/wieslawsoltes/Avalonia/tree/SelectingItemsControlIssue

### PR DESCRIPTION
**Pull request by grokys**
## What does the pull request do?

Fixes `CarouselPresenter`'s handling of changes to the underlying `Items` collection.

## What is the current behavior?

The behavior in #2432 was caused by `CarouselPresenter` not handling inserted items correctly (or at all).

## What is the updated/expected behavior with this PR?

Now handles changes to the underlying `Items` collection correctly, in both virtualized and non-virtualized modes.

## Checklist

- [x] Added unit tests (if possible)?

## Fixed issues

Fixes #2432

### CODE REVIEW

**Comment by grokys** [comment]
@wieslawsoltes @danwalmsley I think this PR should be ready now. From what I understand you need to test it with the dock library?

**Comment by wieslawsoltes** [comment]
The PR builds are failing on CI so I did not test because of missing PR nuggets.

**Comment by grokys** [comment]
@wieslawsoltes fixed the failing test that was failing CI.

**Comment by wieslawsoltes** [comment]
@grokys Ok will test.

**Review by wieslawsoltes — APPROVED** [review]

**Comment by wieslawsoltes** [comment]
@grokys @danwalmsley Tested this with the `Dock` project and could not repro the issue anymore.

**Pull request merged**
