### PR TITLE
Avoid initializing properties if there is no observer. Optimize access.

### LINKED ISSUE #2897: Optimization opportunity in AvaloniaProperty.NotifyInitialized
`AvaloniaProperty.NotifyInitialized` is called for every property(including attached properties) on every Avalonia object.  In control Catalog, once you visit every page, this is 1,230,000 calls.  The only thing I can find that uses this is PsuedoClasses, these receive events from 40,000 of them but only 190 actually change the value.
This is a very expensive way to set PseudoClass defaults.

Is the `IObservable<AvaloniaPropertyChangedEventArgs> Initialized` often/ever used by user code?

Or have I missed some vital use?

The numbers are large in part due to a Datagrid layout/virtualization issue

### PR DESCRIPTION
**Pull request by MarchingCube**
## What does the pull request do?

Quite simple optimization that avoids majority of memory allocations and perf hit caused by it when initializing `AvaloniaObject` instances.

## What is the current behavior?

We are trying to raise initialized events even when there is no listener causing pointless allocations.

## What is the updated/expected behavior with this PR?

Only allocate when there is a listener.

## How was the solution implemented (if it's not obvious)?

- Changed to use `HashSet` and a `List` instead of `Dictionary` for better memory footprint when creating new initialization data cache.
- use `IDirectPropertyAccessor` to avoid going through `AvaloniaObject.GetValue` that does extra checks and is not needed since all properties must be registered on the object (since we used `GetRegistered` before).
- Avoid doing any work and allocations when there is no `Initialized` subscribers.
- Cache `IsDirect` to avoid going through virtual function calls all the time.

Old:

|           Method |     Mean |     Error |    StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|----------------- |---------:|----------:|----------:|-------:|------:|------:|----------:|
| InitializeButton | 4.871 ns | 0.0974 ns | 0.1042 ns | 0.0062 |     - |     - |       5 B |

New:

|           Method |     Mean |     Error |    StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|----------------- |---------:|----------:|----------:|-------:|------:|------:|----------:|
| InitializeButton | 1.759 ns | 0.0178 ns | 0.0167 ns | 0.0016 |     - |     - |       1 B |

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

## Fixed issues

Fixes #2897

cc: @ahopper

### CODE REVIEW

**Comment by MarchingCube** [comment]
I will run my benchmarks soon and post the results.

**Comment by ahopper** [comment]
This looks like a great improvement. I still wonder if AvaloniaPropertyRegistry.NotifyInitialized can be avoided completely if all it really does is set PsuedoClass defaults but that would be a far more disruptive change.

**Comment by MarchingCube** [comment]
Added benchmarks, will take a look at failing tests.

**Comment by MarchingCube** [comment]
It seems that `SelectedItems` in `TreeView` lazy functionality was broken and worked only thanks to property registry calling getter early.

**Review by grokys — APPROVED** [review]
LGTM, thanks @MarchingCube !

**Pull request merged**
