### PR TITLE
Upgrade DataGrid

### LINKED ISSUE #7098: DataGrid text column properties should be set with default styles and not bindings
See: https://github.com/AvaloniaUI/Avalonia/blob/7842883961d094e08e9def7f30cf32fd573179c7/src/Avalonia.Controls.DataGrid/DataGridTextColumn.cs#L163-L167

Because of that it's hard to override Margin and VerticalAlignment

### PR DESCRIPTION
**Pull request by maxkatz6**
## What does the pull request do?
1. Implement support of NthChild in DataGrid (for rows, cells and column headers)
2. Do not hardcode Margin and VerticalAlignment on data grid text column
3. Add missing support of Border properties to the DataGrid templates

image

Also fixes #7098

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0017624-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json)

**Comment by timunie** [comment]
Hi @maxkatz6 

Great ideas 💡

> Do not hardcode Margin and VerticalAlignment on data grid text column

Just a thought: Is it possible to use add properties called `ElementClasses` and `EditingElementClasses` to the DataGridColums so that one can combine different classes and reuse existing ones? 

Happy coding
Tim

**Comment by maxkatz6** [comment]
> Just a thought: Is it possible to use add properties called ElementClasses and EditingElementClasses to the DataGridColums so that one can combine different classes and reuse existing ones?

There is already CellStyleClasses property. It makes sense to add another one for edit mode, although it's easy to differentiate with selector by control type (TextBlock vs TextBox). Not sure about template column though.

**Comment by timunie** [comment]
Cellstyle is just for the cell? Or? At least for me it didn't apply to the TextBlock

**Comment by maxkatz6** [comment]
```Selector="DataGridCell.my-class > TextBlock"```
Or 
```Selector="DataGridCell.my-class > TextBox"```

**Comment by timunie** [comment]
I can place a Style inside for the Cellstyle which applies, but I can't add a class by name to TextBlock or TextBox

**Comment by timunie** [comment]
> ```Selector="DataGridCell.my-class > TextBlock"```
> Or 
> ```Selector="DataGridCell.my-class > TextBox"```

Ahh yes that makes sense. What I had in mind was `Selector=TextBlock.myClass1` and `Selector=TextBlock.myClass2` and then use it like `ElementClasses=myClass1, myClass2` but that may be too much advanced for the DataGrid.

A happy new year later

Tim

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0017626-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json)

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019896-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by grokys — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019929-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
