### PR TITLE
Fix referencing resources in merged dictionaries

### LINKED ISSUE #3323: Issue with referencing from one resource to another in same ResourceDictionary
Avalonia 0.8.3.

I cannot make a reference from one resource to another via StaticResource even in the same ResourceDictionary. It fails with:

> Avalonia.Markup.Xaml.XamlLoadException: 'Error loading xaml at avares://repro/Visual.xaml: An error occured getting provided value'
> KeyNotFoundException: Static resource 'Red' not found.

In case of change StaticResource to DynamicResource, application starts without exceptions but 'dynamic' reference does not works.

Visual.xaml
```
<ResourceDictionary
    xmlns="https://github.com/avaloniaui"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    >


    <Color x:Key="Red">#FFE21A1A</Color>
    <SolidColorBrush x:Key="RedBrush" Color="{StaticResource ResourceKey=Red}"  />

</ResourceDictionary>
```

MainWindow.xaml
```
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:s="clr-namespace:System;assembly=mscorlib"
        xmlns:markup="clr-namespace:Portable.Xaml.Markup;assembly=Avalonia.Markup.Xaml"
        xmlns:viewModels="clr-namespace:repro.ViewModels"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="repro.Views.MainWindow"
        Icon="/Assets/avalonia-logo.ico"
        Width="800" Height="600"
        >

    <Design.DataContext>
        <viewModels:MainWindowViewModel/>
    </Design.DataContext>

    <Window.Resources>

      <ResourceDictionary>
        <ResourceDictionary.MergedDictionaries>
          <ResourceInclude Source='/Visual.xaml'/>
        </ResourceDictionary.MergedDictionaries>

      </ResourceDictionary>

    </Window.Resources>

      <Button
          Content="should have red background"
          Margin="40"
          Background="{DynamicResource ResourceKey=RedBrush}"
           />

</Window>
```

Please make note, if I remove RedBrush from Visual.xaml and modify Window.Resources node to

```
<Window.Resources>

      <ResourceDictionary>
        <ResourceDictionary.MergedDictionaries>
          <ResourceInclude Source='/Visual.xaml'/>
        </ResourceDictionary.MergedDictionaries>
        <SolidColorBrush x:Key="RedBrush" Color="{DynamicResource ResourceKey=Red}"  />
      </ResourceDictionary>

</Window.Resources>
```
everything will works fine.

[repro.zip](https://github.com/AvaloniaUI/Avalonia/files/3921745/repro.zip)

### PR DESCRIPTION
**Pull request by grokys**
## What does the pull request do?

As described in #3323, `StaticResource` in a merged dictionary did not find the resource correctly. Investigating this further I found that `DynamicResource` didn't work properly either, because merged dictionaries did not appear as `IResourceNode`s in the resource tree.

To fix this I needed to do a few things:

- Make `ResourceDictionary` implement `IResourceNode`
- Renamed `ISetStyleParent` to `ISetResourceParent` (as it no longer applies to just styles) and implement it on `ResourceDictionary`
- Correctly pass resource changed messages to merged dictionaries

## Checklist

- [x] Added unit tests (if possible)?

## Fixed issues

Fixes #3323

### CODE REVIEW

**Comment by jmacato** [comment]
@danwalmsley this would be useful on 0.9 since drawingpresenters from another ResourceDictionary that reference a DynamicResource brush in wasabi doesnt work.. this could potentially fix that.

**Comment by grokys** [comment]
Going to merge this as it's had no reviews after 2 weeks and probably the best test of it is for people to start using it!

**Comment by grokys** [comment]
Holding of merging as @jmacato wants to test first.

**Review by jmacato — APPROVED** [review]
Just noticed that i was testing for `Style` that references another resource from another `Style`.. definitely not within the scope of this PR i guess... LGTM :)

**Pull request merged**
