### PR TITLE
Removed legacy XAML loader

### PR DESCRIPTION
**Pull request by kekekeks**
This also creates our own `IProvideValueTarget`, `IUriContext` and `IXamlTypeResolver` in `Avalonia.Markup.Xaml` namespace.

### CODE REVIEW

**Review by jmacato — DISMISSED** [review]
Finally :) but we should wait till @jkoritzinsky gets around in reviewing this one

**Comment by donandren** [comment]
I think it's a good idea to have interface(s) `IMarkupExtension` and/or 'IMarkupExtension<T>' so when we try implement custom markup extensions we know what's the signature of the method we need to implement like `object ProvideValue(IServiceProvider serviceProvider)`
Duck typing the methods can lead a lot of people to confusion how to create custom markupextensions.

**Comment by kekekeks** [comment]
@donandren there are 6 accepted signatures (listed in the search order):
`T ProvideTypedValue()`
`T ProvideTypedValue(IServiceProvider)`
`T ProvideValue()`
`T ProvideValue(IServiceProvider)`
`object ProvideValue()`
`object ProvideValue(IServiceProvider)`

where T is *any* type that's not a `System.Object`.  That can't be represented by a limited concept of .NET interface. We'll need at least 4 interfaces `IMarkupExtension<T>, IMarkupExtensionThatNeedsAServiceProvider<T>, IMarkupExtension, IMarkupExtensionThatNeedsAServiceProvider` and I don't really like such design.

**Comment by kekekeks** [comment]
The overload without IServiceProvider is needed because tracking the info needed for IServiceProvider is quite expensive. I'd like to have more overloads with explicit interface imports in the future, like `T ProvideValue(IUriContext uriContext)` that only needs one service from `IServiceProvider`, so compiler will know exactly what info it needs to track.

**Comment by donandren** [comment]
Understand your concerns. But i would be happy if we have some interface so it's easy to write custom extension without looking at documentations. So xamlil engine works the same as it is - with duck typing resolution. But we have one markup interface for standard general purpose, something like:

``` C#
//TParam is service provider, but in the future can be a service coming from provider
public interface IMarkupExtension<T,TParam>
{
    T ProvideValue(TParam)
}
```

**Comment by kekekeks** [comment]
@donandren For now I've added `MarkupExtension` class back to avoid confusion. I think we need to discuss interfaces and other markup extension markers separately.

**Pull request merged**
