### PR TITLE
Added base dark theme

### PR DESCRIPTION
**Pull request by wieslawsoltes**
- What does the pull request do?
Adds new default themw dark accent.
- What is the current behavior?
Default theme only has light accent.
- What is the updated/expected behavior with this PR?
Adds dark theme accent to default theme.

To apply theme application wide:
```XAML
<Application xmlns="https://github.com/avaloniaui">
  <Application.Styles>
    <StyleInclude Source="resm:Avalonia.Themes.Default.DefaultTheme.xaml?assembly=Avalonia.Themes.Default"/>
    <StyleInclude Source="resm:Avalonia.Themes.Default.Accents.BaseDark.xaml?assembly=Avalonia.Themes.Default"/>
  </Application.Styles>
</Application>
```

To apply theme to part of application like `UserControl`:
```XAML
<UserControl xmlns="https://github.com/avaloniaui"
        Background="{DynamicResource ThemeBackgroundBrush}"
        TextBlock.Foreground="{DynamicResource ThemeForegroundBrush}"
        TextBlock.FontSize="{DynamicResource FontSizeNormal}">
  <UserControl.Styles>
    <StyleInclude Source="resm:Avalonia.Themes.Default.Accents.BaseDark.xaml?assembly=Avalonia.Themes.Default"/>
  </UserControl.Styles>
</UserControl>
```
or use style:
```XAML
<Application xmlns="https://github.com/avaloniaui">
  <Application.Styles>
    <StyleInclude Source="resm:Avalonia.Themes.Default.DefaultTheme.xaml?assembly=Avalonia.Themes.Default"/>
    <StyleInclude Source="resm:Avalonia.Themes.Default.Accents.BaseLight.xaml?assembly=Avalonia.Themes.Default"/>
    <Style Selector="UserControl.themed">
      <Setter Property="Background" Value="{DynamicResource ThemeBackgroundBrush}"/>
      <Setter Property="Foreground" Value="{DynamicResource ThemeForegroundBrush}"/>
      <Setter Property="FontSize" Value="{DynamicResource FontSizeNormal}"/>
    </Style>
  </Application.Styles>
</Application>
```
```XAML
<UserControl xmlns="https://github.com/avaloniaui" Classes="themed">
  <UserControl.Styles>
    <StyleInclude Source="resm:Avalonia.Themes.Default.Accents.BaseDark.xaml?assembly=Avalonia.Themes.Default"/>
  </UserControl.Styles>
</UserControl>
```
Demo:

### CODE REVIEW

**Comment by jmacato** [comment]
@wieslawsoltes i think the Headers on the content is missing the accent theme? I can't them on this dark mode

**Comment by wieslawsoltes** [comment]
> @wieslawsoltes i think the Headers on the content of ControlCatalog is missing the accent theme? I can't them on this dark mode

It is part of control catalog: https://github.com/AvaloniaUI/Avalonia/blob/a0a03753cb39264e6011ad3df8fee9faf7193bb2/samples/ControlCatalog/App.xaml#L6-L20

That probably needs to be changed to:
```XAML
<Style Selector="TextBlock.h1">
    <Setter Property="FontSize" Value="{DynamicResource FontSizeLarge}"/>
    <Setter Property="FontWeight" Value="Medium"/>
</Style>
<Style Selector="TextBlock.h2">
    <Setter Property="FontSize" Value="{DynamicResource FontSizeNormal}"/>
</Style>
<Style Selector="TextBlock.h3">
    <Setter Property="FontSize" Value="{DynamicResource FontSizeSmall}"/>
</Style>
```

**Comment by wieslawsoltes** [comment]
@jmacato Pushed header changes and enabled the full theme support for main view in control catalog, so dark theme looks good out of the box.

**Comment by grokys** [comment]
We already have this in the default `Window` style:

```
<Setter Property="Background" Value="{DynamicResource ThemeBackgroundBrush}"/>
<Setter Property="FontSize" Value="{DynamicResource FontSizeNormal}"/>
```

If you were to add `Foreground` to this, then a `Window` would just work out of the box right?

**Comment by wieslawsoltes** [comment]
> We already have this in the default `Window` style:
> 
> ```
> <Setter Property="Background" Value="{DynamicResource ThemeBackgroundBrush}"/>
> <Setter Property="FontSize" Value="{DynamicResource FontSizeNormal}"/>
> ```
> If you were to add `Foreground` to this, then a `Window` would just work out of the box right?

@grokys I did a lot of hacks before I got things working in the theme editor and before 0.7 release so need to test this and will let you know what works and what not :smile:

**Comment by wieslawsoltes** [comment]
> We already have this in the default `Window` style:
> 
> ```
> <Setter Property="Background" Value="{DynamicResource ThemeBackgroundBrush}"/>
> <Setter Property="FontSize" Value="{DynamicResource FontSizeNormal}"/>
> ```
> If you were to add `Foreground` to this, then a `Window` would just work out of the box right?

@grokys I have included changes in PR.

**Review by grokys — APPROVED** [review]
This is excellent! I've been wanting this for such a long time, thanks @wieslawsoltes!

**Pull request merged**
