### PR TITLE
Upgrade Cake and clean up build script

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Upgrade Cake to 0.28 and clean up targets/package references for tests to reduce build warnings. Get LeakTests running on CI again, this time much cleaner than before. Reduce build output a bit so Appveyor won't truncate it all.

### CODE REVIEW

**Comment by grokys** [comment]
This looks good to me but I'm not really that familiar with the cake scripts. Might be worth @wieslawsoltes taking a look here. If he doesn't have time though, I'm 👍 .

**Comment by grokys** [comment]
@jkoritzinsky any idea what's going on [here](https://ci.appveyor.com/project/AvaloniaUI/Avalonia/build/0.1.5434#L1527) and how to fix it?

**Comment by jkoritzinsky** [comment]
That's because we have an outdated version of JetBrains.Tools.CommandLine for the inspector. It doesn't understand the new project format fully.  I tried upgrading, but I was getting false positives for PossibleNullReferenceException errors.

**Comment by grokys** [comment]
Ahh yes I remember you saying now. Ok, LGTM!

**Review by grokys — APPROVED** [review]

**Pull request merged**
