### PR TITLE
Allow for setting WM shadow hint on a context menu.

### PR DESCRIPTION
**Pull request by MarchingCube**
## What does the pull request do?

Exposed more `Popup` API on `ContextMenu`.

## What is the current behavior?

It is quite hard to disable window manager shadows on context menu popups since one can't write an easy selector for it (`ContextMenu` is attached/detached to different parts of the logical tree).

## What is the updated/expected behavior with this PR?

You can override WM drop shadow hint.

## How was the solution implemented (if it's not obvious)?

Current problem is that disabling drop shadows on the context menu will not disable it for child menu items. I wonder if we should somehow propagate that? On the other hand writing a style for child popup is much easier since selector is just `ContextMenu MenuItem`.

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Avaloniaui.net with user documentation

### CODE REVIEW

**Comment by maxkatz6** [comment]
> Current problem is that disabling drop shadows on the context menu will not disable it for child menu items

Just for case, it is already disabled from the template: https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Themes.Fluent/MenuItem.xaml#L113 (for MenuItem > MenuItem)
And there: https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Themes.Fluent/MenuItem.xaml#L161 (for Menu > MenuItem)

**Comment by MarchingCube** [comment]
Seems that `MenuItem > MenuItem` is actually hardcoded to true. Not a problem in my app since we use custom template but `ContextMenu` itself is more annoying as it creates popups in code.

**Comment by maxkatz6** [comment]
Why we can't add Popup to the template? I don't see any drawbacks, and it will match behavior in other controls (MenuItem, AutoSuggestBox).

**Comment by MarchingCube** [comment]
That would definitely make things easier to style but I am not sure why it is created in code in the first place - maybe @grokys knows?

**Review by kekekeks — APPROVED** [review]

**Comment by grokys** [comment]
> That would definitely make things easier to style but I am not sure why it is created in code in the first place - maybe @grokys knows?

That would indeed be better but I'm not sure how it would work. To instantiate a template you need to instantiate it somewhere, but in this case where? The contents of the context menu template go _inside_ the popup, so you need a popup root to instantiate the template into if that makes sense.

**Comment by MarchingCube** [comment]
One option would be to provide something like `PopupTemplateProperty` so if somebody needs to they can override it and do whatever styling they need. What do you think?

**Comment by grokys** [comment]
> One option would be to provide something like PopupTemplateProperty so if somebody needs to they can override it and do whatever styling they need. What do you think?

Possibly? Another alternative would be to make the `Popup` properties attached properties. I think this is separate from this PR however so I think we should merge this.

**Pull request merged**
