### PR TITLE
Fix managed dialog enumeration and volume label on Windows.

### PR DESCRIPTION
**Pull request by jmacato**

### CODE REVIEW

**Review by danwalmsley — APPROVED** [review]
LGTM - added a commit to include drive letter in label.

**Comment by HendrikMennen** [comment]
I am not sure if this is caused by this, but I can't use the managed dialog anymore.
A few days ago it still worked. This is on debian 10

```
System.IO.FileNotFoundException: Could not find file '/proc/partitions'.
File name: '/proc/partitions'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
   at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
   at System.IO.File.ReadAllLines(String path)
   at Avalonia.FreeDesktop.LinuxMountedVolumeInfoListener.Poll(Int64 _) in D:\a\1\s\src\Avalonia.FreeDesktop\LinuxMountedVolumeInfoListener.cs:line 41
   at Avalonia.FreeDesktop.LinuxMountedVolumeInfoProvider.Listen(ObservableCollection`1 mountedDrives) in D:\a\1\s\src\Avalonia.FreeDesktop\LinuxMountedVolumeInfoProvider.cs:line 13
   at Avalonia.Dialogs.ManagedFileChooserViewModel..ctor(FileSystemDialog dialog) in D:\a\1\s\src\Avalonia.Dialogs\ManagedFileChooserViewModel.cs:line 108
   at Avalonia.Dialogs.ManagedFileDialogExtensions.ManagedSystemDialogImpl`1.Show(SystemDialog d, IWindowImpl parent) in D:\a\1\s\src\Avalonia.Dialogs\ManagedFileDialogExtensions.cs:line 18
   at Avalonia.Dialogs.ManagedFileDialogExtensions.ManagedSystemDialogImpl`1.ShowFileDialogAsync(FileDialog dialog, IWindowImpl parent) in D:\a\1\s\src\Avalonia.Dialogs\ManagedFileDialogExtensions.cs:line 44
   at VHDPlus.ViewModels.MainWindowViewModel.OpenFile(String type) in /mnt/c/Users/HendrikMennen/source/repos/VHDP/VHDPlus/ViewModels/MainWindowViewModel.cs:line 254
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in D:\a\1\s\src\Avalonia.Base\Threading\JobRunner.cs:line 40
   at Avalonia.X11.X11PlatformThreading.HandleX11(CancellationToken cancellationToken)
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken) in D:\a\1\s\src\Avalonia.X11\X11PlatformThreading.cs:line 200
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in D:\a\1\s\src\Avalonia.Base\Threading\Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in D:\a\1\s\src\Avalonia.Controls\ApplicationLifetimes\ClassicDesktopStyleApplicationLifetime.cs:line 107
   at VHDPlus.Program.Main(String[] args) in /mnt/c/Users/HendrikMennen/source/repos/VHDP/VHDPlus/Program.cs:line 54

**Comment by kekekeks** [comment]
Are you, by chance, trying to run it on WSL?

**Comment by HendrikMennen** [comment]
That's correct

**Comment by kekekeks** [comment]
@jmacato it seems that WSL doesn't expose /proc/partitions like an actual Linux does. I guess we need just skip partition scanning if there is no /proc/partitions.

**Comment by jmacato** [comment]
@kekekeks crap.. i thought that was a standard linux interface :/

**Comment by kekekeks** [comment]
WSL isn't exactly a "standard linux"

**Comment by jmacato** [comment]
Yeah, we'll just have to terminate partition scanning when that happens

**Comment by danwalmsley** [comment]
WSL v2 will prob solve this? since it will be an actual virtual machine, and not an emulated linux?

**Comment by jmacato** [comment]
@danwalmsley i believe it should, but for a precautionary measure, terminating the polling when `/proc/partitions` isn't found would be a good idea i think.

**Pull request merged**
