### PR TITLE
Make all Render overrides sealed

### LINKED ISSUE #10066: Make all `Render` method overrides sealed
At some point we might want to change the way built-in primitives are rasterized.

### PR DESCRIPTION
**Pull request by Takoooooo**
## What does the pull request do?
This is needed because at some point we might want to change the way built-in primitives are rasterized

## Fixed issues
Fixes #10066

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0029850-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Review by kekekeks — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0029858-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by gusmanb** [comment]
Same problem here, I have custom controls that inherit from Border and now they're dead...

**Comment by tkefauver** [comment]
@gusmanb Definitely agree :( 

It ended up being pretty easy for my Border control though. Its a really basic one like what you're mentioning and I got it working... just had to replace `Border.Child` usage with `UserControl.Content`.

**Comment by 29654761** [comment]
This is very bad idea.
Avalonia can almost do nothing.

**Comment by timunie** [comment]
@29654761 it's a bad idea to comment on merged PRs. Open a Discussion with your specific issue und use-case described. If possible, show sample code.

**Pull request merged**
