### PR TITLE
Vortice integration

### PR DESCRIPTION
**Pull request by amerkoleci**
## What does the pull request do?
Replaces SharpDX with Vortice.Windows

image

## What is the current behavior?
Updates SharpDX with Vortice.Windows for Direct2D1 backend

## What is the updated/expected behavior with this PR?
Completed the integration started from #5764 

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=6002) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=6002) before we can accept your contribution.<br/><br/>:x: amerkoleci [sign now](https://cla.dotnetfoundation.org/AvaloniaUI/Avalonia?pullRequest=6002)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/AvaloniaUI/Avalonia?pullRequest=6002) it.</sub>

**Comment by amerkoleci** [comment]
Not sure why CI build fails on windows, any thoughts?

**Comment by amerkoleci** [comment]
Ok, all chekcs have passed and I verified all render tests and unit tests works as expected.

**Comment by amerkoleci** [comment]
@grokys @danwalmsley can someone review the PR please?

**Comment by amerkoleci** [comment]
@andrew-boyarshin any thought why this randomically happens?

```
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at SharpGen.Runtime.ComObject.Release()
   at SharpGen.Runtime.ComObject.DisposeCore(IntPtr nativePointer, Boolean disposing)
   at SharpGen.Runtime.CppObject.Dispose(Boolean disposing)
   at SharpGen.Runtime.DisposeBase.CheckAndDispose(Boolean disposing)
   at SharpGen.Runtime.DisposeBase.Finalize()
```

**Comment by andrew-boyarshin** [comment]
I'm not sure, but it would take some time to debug this, and time is something I don't have at the moment. Using `SharpGen.Runtime` built in _Debug_ configuration and enabling all kinds of tracing (especially recently introduced `EnableObjectLifetimeTracing`) would definitely be helpful though. It would also help to figure out a stable reproducible case, tracing might help discover which `CppObject`s it relates to.

**Pull request closed without merging**
