### PR TITLE
Fixes text processing bugs

### LINKED ISSUE #5805: Rework the ITextShaper to support shaping multiple runs at once
Currently, the text shaper only shapes each run individually this causes shaping issues when text highlighting is applied.

Related WPF API: https://github.com/dotnet/wpf/blob/main/src/Microsoft.DotNet.Wpf/src/PresentationCore/MS/internal/TextFormatting/TextShapeableSymbols.cs#L60

### PR DESCRIPTION
**Pull request by Gillibald**
## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Fixed issues

Fixes: #5805

### CODE REVIEW

**Comment by hez2010** [comment]
Can confirm this PR fixes #7502 except the one "IME position update doesn't take scrolling into account".

**Comment by adirh3** [comment]
@Gillibald with this PR, it's much better, but empty TextBlocks still takes vertical space (unlike before)
image

**Comment by hez2010** [comment]
@adirh3 I think it is expected, in order to match WPF behavior.

WPF behavior:

スクリーンショット 2022-02-25 001946

**Comment by maxkatz6** [comment]
I'm actually surprised. I think empty text blocks worked like this for a long time now. I even used "IsVisibility" binding workarounds to avoid it in Avalonia 0.10.x.

**Comment by adirh3** [comment]
> @adirh3 I think it is an expected change, in order to match WPF behavior.
> 
> WPF behavior:
> 
> スクリーンショット 2022-02-25 001946

Makes sense, thanks.
@Gillibald probably worth mentioning it in the breaking changes section.

**Comment by hez2010** [comment]
Another found:
Pressing `right` after pressing `end` at line 1 will result in navigating to line 3.
The caret doesn't move back when pressing `left` after pressing `end`.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018939-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018939-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by MarchingCube** [comment]
It no longer crashed but I've tested your PR and found two issues (that probably were there before)
text-editing-issues

1. Selecting first letter is shifting the entire text layout a bit
2. Deleting selection puts caret after where it should be. Checked in other text editors too and caret does not behave like that elsewhere.

**Comment by adirh3** [comment]
Another little thing I noticed - 
1. Type something
2. Press Ctrl+Shift+Left arrow key
3. Text selected
4. Press Left arrow key again
5. Caret not moving to index 0

**Comment by Gillibald** [comment]
> Another little thing I noticed -
> 
> 1. Type something
> 2. Press Ctrl+Shift+Left arrow key
> 3. Text selected
> 4. Press Left arrow key again
> 5. Caret not moving to index 0

I did not move the CaretIndex to the end of selection and always kept it at the start. Looks like regular editors behave differently. Will change that.

**Comment by Gillibald** [comment]
Your issues should be fixed now

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018945-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018945-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by adirh3** [comment]
> Your issues should be fixed now

Fixed, but now moving with the caret jumps 2 characters at a time

**Comment by Gillibald** [comment]
CaretHorizontalMovement

Can you explain your issue further?

**Comment by adirh3** [comment]
> CaretHorizontalMovement
> 
> Can you explain your issue further?

Sorry my bad, haven't pulled all changes.
One other thing I noticed, is that when selecting text, pressing Right/Left would jump to end.
1. Type something
2. Press Ctrl+Shift+Left
3. Press Right
4. Expected - all text, except first character selected. Actual - selection removed

**Comment by adirh3** [comment]
Not 100% sure, but I think it was caused by either this or last PR.
TextBlock with `MaxLines=3` and `TextWrapping="Wrap"`, sometimes the text not wrapping, **depending on screen DPI**.
image
There are empty lines, with the last words not displayed, here the word "Music" is missing as you can see in the tooltip.
This text reproes consistently on 150% scale monitor (resolution is 4k,16:9), but work on other monitor with scale of 125%.

**Comment by Gillibald** [comment]
> Not 100

Y definitely a rounding issue

**Comment by Gillibald** [comment]
> Not 100% sure, but I think there is another issue caused by either this or last PR. TextBlock with `MaxLines=3` and `TextWrapping="Wrap"`, sometimes the text not wrapping, **depending on screen DPI**. image There are empty lines, with the last words not displayed, here the word "Music" is missing as you can see in the tooltip. This text reproes consistently on 150% scale monitor (resolution is 4k,16:9), but work on other monitor with scale of 125%.

I think I need your help here. Could you try to repro this in the SandBox and have a look at the actual TextBlock.TextLayout?
I can't repro it by changing desktop scaling.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018956-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018956-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by adirh3** [comment]
@Gillibald can confirm selection is fixed.

As for the TextBlock scale bug, I just can't repro it for some reason on my main computer, only on work one, even though both were connected to the same monitors.
I will keep trying to make a repro later today and update here.
Here is a video showing it - 
Uploading Avalonia Scale Bug.mp4…

Also, new bug I noticed -
1. Type in RTL language, here is a text - "שלום"
2. Press space
3. See caret is mispositioned, pressing right/left would move it to the middle of the word

**Comment by danielmayost** [comment]
@adirh3 I noticed some bugs of this kind some time ago, here:  https://github.com/AvaloniaUI/Avalonia/issues/7502#issuecomment-1026550213

**Comment by Gillibald** [comment]
I need to have a deeper look at that issue. In general it is better to set the FlowDirection to RightToLeft when editing RTL text.

**Comment by Gillibald** [comment]
@MarchingCube All your issues should be fixed now

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018986-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0018986-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by Gillibald** [comment]
Okay thanks for having a look

**Review by grokys — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019007-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0019007-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by adirh3** [comment]
@Gillibald Sorry but I can't create a repro, here are some debug info if it helps - 
image
image
image
image

Let me know if any other information may help.

**Comment by adirh3** [comment]
@Gillibald does the info above help? 
Should I create a separate issue? Since it's not really a text processing bug.

**Comment by adirh3** [comment]
> There were some issues with scaling that I could fix. Please try #7746

Thanks, seems like that PR fixed most of the issues with multiple lines. But single lines still have missing end-character -
image
(e missing at the end)
Will check if I can create a repro for this.

**Pull request merged**
