### PR TITLE
DevTools: Fix crash when property getter throws

### PR DESCRIPTION
**Pull request by pr8x**
## What does the pull request do?

Fix a bug in DevTools that would prevent the user from navigating to elements.

## What is the current behavior?

DevTools refuses to navigate to elements when one of their property getter throw.

## What is the updated/expected behavior with this PR?

The exception is handled now and will show in the value field.

image

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0020179-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by pr8x** [comment]
image

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0020205-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0020206-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
