### PR TITLE
Numeric up/down control added

### PR DESCRIPTION
**Pull request by DmitryZhelnin**
Ported numeric up/down control. Added sample to ControlCatalog.

default

### CODE REVIEW

**Comment by danwalmsley** [comment]
@DmitryZhelnin wow this looks really good :) 

I think I missed the conversation other day about generics, related to this. but would it not make more sense have only a single control.

The values are doubles, and you have an increment property. That way the user can deal with casting the value, to byte or something else?

**Comment by DmitryZhelnin** [comment]
@danwalmsley thanks for the reply! I think end-user should not be worried about casting values etc.
For example I have an `int` property in my viewmodel and I'll just take `IntegerUpDown` to manipulate this property out of the box, I dont wanna to change anything in my viewmodel.

**Comment by grokys** [comment]
I think I agree with @danwalmsley, if you're using binding to bind the values then the binding system should take care of converting `double` <-> `int` etc, so you shouldn't need to change anything. Or is this not working correctly?

**Comment by DmitryZhelnin** [comment]
@danwalmsley @grokys Guys, I think you were right. I'll rework the code and add new commits later.

**Comment by DmitryZhelnin** [comment]
Now it's only one `NumericUpDown` control with double values. 

> binding system should take care of converting double <-> int etc
This works as expected.

**Comment by DmitryZhelnin** [comment]
Somehow I missed the fact that `double?` type of the `Value` property doesn't work with binded properties except they are `double`. So I have to remove `Default` value feature.

**Comment by lindexi** [comment]
I think some controls should be move to other sln like [UWPCommunityToolkit](https://github.com/Microsoft/UWPCommunityToolkit)

**Review by grokys — APPROVED** [review]
This looks great! As @lindexi says "advanced" controls like this should probably live somewhere else in the long run but for now lets put them into Avalonia.Controls until we decide where they should go.

**Pull request merged**
