### PR TITLE
The Great Interface Removal Part I

### LINKED ISSUE #9495: Breaking Change: Remove Unneeded Interfaces
We currently have many interfaces in Avalonia which mirror concrete classes, for example (list is not exhaustive):

- `IAvaloniaObject` -> `AvaloniaObject`
- `IControl` -> `Control`
- `IInteractive` -> `Interactive`
- `ILayoutable` -> `Layoutable`
- `IPanel` -> `Panel`
- `IStyledElement` -> `StyledElement`
- `ITemplatedControl` -> `TemplatedControl`
- `IVisual` -> `Visual`

These interfaces were added at the beginning of the project at a time where the prevailing fashion in unit testing was "create an interface for each concrete class in order to make it easier to mock".

This turned out to be a mistake because:

- Using interfaces instead of concrete classes means that every method call is a virtual method call. This degrades performance in large applications and can be particularly noticeable when profiling on slower embedded and mobile hardware
- We still target `netstandard2.0` which includes platforms such as .NET framework where default interface implementations are not supported, meaning that we can't even add methods to these interfaces without breaking API compatibility
- Mocking is unnecessary in the unit tests anyway: it's much better to use concrete classes
- Implementing these interfaces in user code isn't supported by much of the code anyway

For 11.0 we should remove these interfaces to improve performance. This will be a large breaking change, but we feel it's necessary, and the fix should be reasonably straightforward - remove a bunch of `I` characters.

### PR DESCRIPTION
**Pull request by grokys**
## What does the pull request do?

As discussed in #9495, removes a bunch of unneeded interfaces; the concrete classes should be used from this point on:

- `IAvaloniaObject` -> `AvaloniaObject`
- `IControl` -> `Control`
- `IInteractive` -> `Interactive`
- `ILayoutable` -> `Layoutable`
- `IPanel` -> `Panel`
- `IStyledElement` -> `StyledElement`
- `ITemplatedControl` -> `TemplatedControl`
- `IVisual` -> `Visual`

In a few cases, the interfaces were used to hide less commonly needed functionality, e.g. `IVisual.VisualRoot`: the extension methods should be used, e.g. `control.GetVisualRoot()`.

Doesn't remove `IStyleable` yet, that will come in a later PR (perhaps some other interfaces can be removed too).

## Breaking changes

Yes :)

## Fixed issues

Fixes #9495

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0026598-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]
40% LGTM 60% YOLO

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0026649-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by maxkatz6** [comment]
@rabbitism it was discussed in the #9495

**Pull request merged**
