### PR TITLE
Fix FlowDirection within Viewbox

### LINKED ISSUE #8170: Incurrect behavior within ViewBox
~Affter #8122 the Inheritance hierarchy from `ViewBox` to his kids was broken, causing serious problems with `FlowDirection` behavior.~

**Edit:** sorry, this because my mistake. will fix it.

Example:
image

### PR DESCRIPTION
**Pull request by danielmayost**
## What does the pull request do?
Fixes #8170.

## What is the current behavior?
~`FlowDirection` system find visual ancestor of `Control` to set his `MirrorTransform`, affter #8122 the expected behavior was broken because `ViewboxContainer` considered part of the chain of components that determine `FlowDirection`, and it does not really inherit `FlowDirection` because it is not part of the logical tree.~

I found out I was wrong in my previous `FlowDirection` implementation, I mistakenly calculated `MirrorTransform` after `RenderTransform`, and this caused some issues as expected.

I fixed it, now `MirrorTransform` is calculated before `RenderTransform`.

## Fixed issues
Fixes #8170

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0020586-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by danielmayost** [comment]
Ready to review.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0020672-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0020673-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by Gillibald — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `0.10.999-cibuild0020737-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
