### PR TITLE
feat: Also allows using string instead of {x:Type} in ControlTemplate.TargetType

### LINKED ISSUE #11334: Standalone ControlTemplate with TargetType fails to resolve properties
I'm trying to make a `ControlTemplate` at the top of my `ResourceDictionary` that can be reused by two `ControlThemes` later in the same resource dictionary, preventing me from having to duplicate the template content.

If I have this:
```
<ControlTemplate x:Key="ToggleButtonControlTemplate" TargetType="ToggleButton">
  <ContentPresenter
    x:Name="PART_ContentPresenter"
    Background="{TemplateBinding Background}"
    ...
    />
</ControlTemplate>
```

And reference it in a `ControlTheme` later like this: 
```
<Setter Property="Template" Value="{StaticResource ToggleButtonControlTemplate}" />
```

I get this exception:  
> ToggleButton.axaml(36,6,36,6): Avalonia error AVLN:0004: Unable to resolve suitable regular or attached property Background on type Avalonia.Controls:Avalonia.Controls.Control Line 36, position 6.

That happens on the `Background` property setter.  But if I am saying `TargetType` on the `ControlTemplate`, it should be able to resolve the `Background` property properly.

## Easy Repro Steps

Place this simple snippet in any `ResourceDictionary` and you'll get the exception when compiling.

```
<ControlTemplate x:Key="ControlTemplateIssueRepro" TargetType="Button">
  <ContentPresenter Background="{TemplateBinding Background}" />
</ControlTemplate>
```

This needs to be fixed so that standalone `ControlTemplates` can be reused across multiple `ControlThemes` that don't inherit each other.

### PR DESCRIPTION
**Pull request by workgroupengineering**
## What does the pull request do?

Allows using string instead of {x:Type} in ControlTemplate.TargetType

## What is the current behavior?

Throw `Unable to resolve suitable regular or attached property`

## Checklist

- [x] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Fixed issues

Fixes #11334

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0035854-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-all/nuget/v3/index.json) [PRBUILDID]

**Comment by workgroupengineering** [comment]
@billhenn Can you try this PR if it solve your problem?

**Comment by grokys** [comment]
I've not had time to review this PR yet, but I suspect that we're hitting ordering issues with the transformers as iirc there should be a transformer which transforms `string` into `Type` for relevant properties, but could be that it's getting run too late.

**Comment by workgroupengineering** [comment]
> I've not had time to review this PR yet, but I suspect that we're hitting ordering issues with the transformers as iirc there should be a transformer which transforms `string` into `Type` for relevant properties, but could be that it's getting run too late.

If you suggest the area to see, I'll try to check.

**Comment by grokys** [comment]
@workgroupengineering sorry I'm not really familiar enough with the XAML compiler internals to be able to point you to it, this was just from a vague memory of hitting something similar a while ago. Will probably need input from someone who knows this part of the code a bit better.

**Comment by workgroupengineering** [comment]
> @workgroupengineering sorry I'm not really familiar enough with the XAML compiler internals to be able to point you to it, this was just from a vague memory of hitting something similar a while ago. Will probably need input from someone who knows this part of the code a bit better.

I investigated, `ControlTheme` following the same path.

https://github.com/AvaloniaUI/Avalonia/blob/4552278f4b4e34e168557139808eeabd071d5fe6/src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlControlThemeTransformer.cs#L28-L33

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0038662-beta`. (feed url: https://nuget-feed-all.avaloniaui.net/v3/index.json) [PRBUILDID]

**Comment by billhenn** [comment]
This PR has been floating out there for a while.  Just curious as to the status since it would be nice to have the bug fix in place for standalone ControlTemplate usage.

**Review by maxkatz6 — APPROVED** [review]
LGTM
Even though it's probably not the best solution, it does match other transformers and adds a test, so it can be refactored in the future.

**Pull request merged**
