### PR TITLE
Fixes Border and Shape border re-rendering when changing Brush value

### PR DESCRIPTION
**Pull request by SKProCH**
## What does the pull request do?
Fixes the https://github.com/AvaloniaUI/Avalonia/issues/12408

## What is the current behavior?
When I change color of SolidColorBrush, which bind with DynamicResource to Rectangle's Stroke/Border's BorderBrush, then Rectangle/Border doesn't re-render.

## What is the updated/expected behavior with this PR?
Changing value of Rectangle.Stroke and Border.BorderBrush starts re-rendering control properly.

## Checklist
- [x] Added XML documentation to any related classes?

## Fixed issues
https://github.com/AvaloniaUI/Avalonia/issues/12408

### CODE REVIEW

**Comment by SKProCH** [comment]
I first tried to do this through adding a new implementation of `IPen`, but multiple attempts to friend this with the compositor were unsuccessful. So for the moment the implementation has been replaced by `Pan`.

**Comment by saCadOww** [comment]
> > > Sacad**[]()~~~~**

**Comment by maxkatz6** [comment]
Checked the way how compositor handles immutable and mutable resources, and these changes overall make sense to me.
It is allowed to pass mutable resources (brushes, pen) to the UI-thread drawing context, which records drawing operations. And compositor will handle mutable resources in RenderDataDrawingContext in its own way. Converting them to immutable when it needs to.

The only possible problem is that we have mutable Pen created on each drawing, and compositor will actually subscribe on Pen's changes adding additional overhead. When we know for sure this Pen will never be changed (only internal brushes). But it would require more involved changes.

cc @kekekeks

**Comment by maxkatz6** [comment]
Possibly, we can avoid creation of mutable Pen, if Brush and other components of the Pen were immutable?

**Comment by SKProCH** [comment]
I originally thought of this too, and made an ImmutablePenWithDynamicBrush class. However, it didn't work because you have to create a server object for Brush. I spent a few hours experimenting with it, and still it sometimes didn't work correctly (for example with Border.BorderThickness 1 was not displayed, but with 2 - everything was fine). It may be worth implementing something similar.

Also, I'll take a look at the caching mechanism.

**Comment by Gillibald** [comment]
It should be possible to test Stroke and FillBrush for mutability and only then construct a mutable Pen. The Compiler should produce immutable brushes.

**Comment by SKProCH** [comment]
@maxkatz6 yep, your changes works fine. Thanks. 

I'll also, take a closer look, to see if I can improve something.

**Review by maxkatz6 — APPROVED** [review]

**Comment by SKProCH** [comment]
@maxkatz6 can you add to the queue again?

**Pull request merged**
