### PR TITLE
Add class CroppedBitmap

### PR DESCRIPTION
**Pull request by vmelnikov**
## What does the pull request do?
Added class CroppedBitmap which allows to render a part of Source in Image Control

## How was the solution implemented (if it's not obvious)?
I added some changes to ImagePage of ControlCatalog to demonstrate CroppedBitmap usage

CroppedBitmap

### CODE REVIEW

**Comment by MarchingCube** [comment]
I've glanced over WPF documentation to understand this class and I think this needs more work to be useful. 

In examples this class can be used directly from XAML like:

```xaml
<CroppedBitmap x:Key="croppedImage" 
      Source="{StaticResource masterImage}" SourceRect="30 20 105 50"/>
```

This is currently not possible in this implementation and it would limit usability.

Docs: https://docs.microsoft.com/en-us/dotnet/framework/wpf/controls/how-to-crop-an-image
WPF implementation: https://github.com/dotnet/wpf/blob/master/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Imaging/CroppedBitmap.cs

**Comment by vmelnikov** [comment]
I tried to realize this functionality and  I have one problem. If I want to use CroppedBitmap directly in XAML I need to inherit it from AvaloniaObject and add setters for Source and SourceRect properties. In this case this class will cease to be immutable. I haven't find any way to notificate the parent Image Control to render when changes occurs in it Source. Can anybody help me with it?

**Comment by kekekeks** [comment]
@vmelnikov You need to implement `IAffectsRender` on your `IImage` implementation.

**Comment by vmelnikov** [comment]
> @vmelnikov You need to implement `IAffectsRender` on your `IImage` implementation.

Thanks it works

**Review by grokys — APPROVED** [review]

**Comment by nir34** [comment]
Can save croppedBitmap as a jpg?

**Comment by timunie** [comment]
@nir34 please open a Q&A or ask on telegram https://t.me/Avalonia if you have a question. Closed issues are not a good place to ask. I think jpg is not supported atm, but png is which is even better in most cases. Try `MyBitmap.Save()`

**Pull request merged**
