### PR TITLE
Fixed animations causing unnecessary rendering

### PR DESCRIPTION
**Pull request by adirh3**
## What does the pull request do?
 Compositor key frame animations cause the renderer re-draw the entire visual tree when not needed.
This PR resets the state of these animations to make sure it will not happen.

## What is the current behavior?
If you hide (minimize) and then show a window, you will see excessive CPU/GPU usage even if there are no active animations.
You can repro this easily by minimizing and then maximizing the Control Catalog, you will see high GPU usage only after minimizing it once -
image

## What is the updated/expected behavior with this PR?
After hiding and showing an Avalonia window, it will render only when needed.

## How was the solution implemented (if it's not obvious)?
When a `KeyFrameAnimationInstance` activates it will be added to the compositor clock, triggering redrawing of the visual.
When the animation ends, it will deactivate and remove itself from the clock.
The issue is that when minimizing the window all animations will deactivate and then activate again with the `_finished = true` state when the window is showed again.
This PR resets the state on Deactiate to `_finished = false`. 

## Checklist

- [ ] Added unit tests (if possible)?
- [ ] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

### CODE REVIEW

**Comment by kekekeks** [comment]
I think we should add `if(_finished)` check to `Activate` instead, so finished animations won't be added to the clock.

**Comment by adirh3** [comment]
> I think we should add `if(_finished)` check to `Activate` instead, so finished animations won't be added to the clock.

Changed it, but I am not sure I understand the lifetime of an animation. It seems like animations are never cleared from `_animations` in the server, and `_finished` is never reset to `false`.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0027308-beta`. (feed url: https://pkgs.dev.azure.com/AvaloniaUI/AvaloniaUI/_packaging/avalonia-nightly/nuget/v3/index.json) [PRBUILDID]

**Comment by kekekeks** [comment]
Once animation _instance_ is attached to a property it stays there until said property is changed. It's not possible to restart an animation _instance_, you can only replace it with a new one. We can probably optimize it and replace the animation instance with its last returned value once it has finished.

**Review by maxkatz6 — APPROVED** [review]

**Pull request merged**
