### PR TITLE
WIP: Linux Skia Support

### PR DESCRIPTION
**Pull request by jameswalmsley**

### CODE REVIEW

**Comment by danwalmsley** [comment]
Please attach required libskia.so

**Comment by kekekeks** [comment]
There is no point of having a separate library. There are two approaches of rendering stuff on screen from Skia.Desktop on Linux:
1) use XLib directly, I could provide you with C# code that renders to XId from offscreen byte array (something like SetDIBitsToDevice)
2) Introduce a new `DrawFromBitmap(IntPtr ptr, int width, int height, int stride)` to `IWindowImpl` so rendering subsystem won't need to know about onscreen surface at all.

**Comment by danwalmsley** [comment]
@kekekeks ok sure, probably will be a good idea to add the DrawFromBitmap method, 

then we can get rid of all the #ifdefs 
?

If I give you access to the branch could you push the code c# code you have?

**Comment by kekekeks** [comment]
Unfortunately native library doesn't seem to work: `System.EntryPointNotFoundException: sk_managedstream_set_delegates`

**Comment by jameswalmsley** [comment]
@kekekeks Thanks for trying it, the pushed libraries here are now out of date compared to the skiasharp version.

**Comment by danwalmsley** [comment]
PR is now obsolete closing.

**Pull request closed without merging**
