### PR TITLE
Notify window on mouseEntered (mac only)

### PR DESCRIPTION
**Pull request by ltetak**
## What does the pull request do?
Fixes issue when Tooltip hides immediately on mac - see https://github.com/AvaloniaUI/Avalonia/pull/13565#issuecomment-2040006675

## What is the current behavior?
Tooltip flickers (hides) which should be solved by https://github.com/AvaloniaUI/Avalonia/pull/13565 but it does not fix this for mac

## What is the updated/expected behavior with this PR?
no flickering

cc: @grokys

### CODE REVIEW

**Comment by maxkatz6** [comment]
cc @grokys, not sure who else can review it.

**Comment by ltetak** [comment]
To reiterate this problem. AFAIK there is no Avalonia equivalent for MouseEnter. There is only LeaveWindow (https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Base/Input/Raw/RawPointerEventArgs.cs#L9) 
I guess this roots from the Windows API which does have WM_MOUSEMOVE + WM_MOUSELEAVE but does not have WM_MOUSEENTER (or equivalent) - do not mix this with WM_POINTERENTER and WM_POINTERLEAVE which handles non-mouse devices. In general, WM_MOUSEMOVE handles the "window enter" as well (the first time you receive this event you know you must be over the window. And you receive it immediately).
On Mac this is different. There is mouse handling for all three events (enter + move + leave). So they don't need to send the mouse-move event immediately after mouse-enter event. This creates a race condition in many cases (e.g. the ToolTip will hide since the mouse seems not to hover it yet).
That's why I think this solution maps well to the Windows behavior and should work fine in all cases. 
cc: @grokys @maxkatz6

**Comment by ltetak** [comment]
@Gillibald I think you are working with mac as well. Can you please take a look at this PR?

**Review by grokys — APPROVED** [review]
Not sure that I'm the right person to review this, as I've not really been involved in mouse event handling in the macOS backend, but from what I can see I don't think it should cause problems, so giving it a tentative +1. Thanks @ltetak !

**Pull request merged**
