### PR TITLE
Move inlines support to TextBlock and rename RichTextBlock

### LINKED ISSUE #9199: Focus have different behavior in RichTextBlock and TextBlock
**Describe the bug**
`RichTextBlock` gets the focus inside `StackPanel` when it is nested in a container with `Focusable="True"` property. In the same time `TextBlock` does not gets the focus in the same case.

**To Reproduce**

1. Add code in MainWindow.xaml
```xaml
<Window xmlns="https://github.com/avaloniaui"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
        x:Class="AvaloniaApplication1.MainWindow"
        Title="AvaloniaApplication1">
  <VirtualizingStackPanel>
    <Panel
      Width="100"
      Height="100"
      Background="Yellow"
      Focusable="True">
      <RichTextBlock>
        RichTextBlock 0
      </RichTextBlock>
    </Panel>
    
    <Panel
      Width="100"
      Height="100"
      Background="Red"
      Focusable="True">
      <RichTextBlock>
        RichTextBlock 1
      </RichTextBlock>
    </Panel>
    
    <Panel
      Width="100"
      Height="100"
      Background="Green"
      Focusable="True">
      <TextBlock Text="Text Block"></TextBlock>
    </Panel>
    
    
    <Panel
      Width="100"
      Height="100"
      Background="Blue">
      <RichTextBlock>
        RichTextBlock 3
      </RichTextBlock>
    </Panel>
    
    <TextBlock>
    </TextBlock>
  </VirtualizingStackPanel>
</Window>
```
2. Press `TAB` key multiple times

**Expected behavior**
After each button press the focus should be switched to next `Panel` block.

**Actual behavior**
The focus switched only after double press. (it seems that `RichTextBlock` getting focus on second key press)

**Desktop (please complete the following information):**

- OS: MacOS 12.5.1
- Version 11.0.0-preview2

### PR DESCRIPTION
**Pull request by Gillibald**
## Checklist

- [x] Added unit tests (if possible)?
- [x] Added XML documentation to any related classes?
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with user documentation

## Fixed issues

Fixes: #9199, #9208, #9249

### CODE REVIEW

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0025112-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0025120-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by robloo** [comment]
I'm surprised you're getting rid of `RichTextBlock` after the discussion about the need for this control and the symmetry in naming/usage with `RichTextBox`.

Then making a new control now for selectable text doesn't feel quite right API-wise. I don't think this control should exist. It would make more sense to have an IsSelectable or EnableSelection property on the now unified TextBlock.

**Comment by Gillibald** [comment]
We need to define a control template with a flyout for text selection, etc. This introduces an overhead we do not want for all TextBlocks. So we either encapsulate text selection support in some attachable behavior or have a dedicated control.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0025149-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by robloo** [comment]
> We need to define a control template with a flyout for text selection, etc. This introduces an overhead we do not want for all TextBlocks.

That was the same reasoning for separating TextBlock from RichTextBlock originally. Text is so widely used and the vast majority of it is simple strings so we shouldn't be using the heaving inlines and rich text text formatting engine unless it's absolutely necessary. However, you seem to have changed course here and decided performance won't be an issue "Inlines support itself just adds an empty list to each TextBlock."

> So we either encapsulate text selection support in some attachable behavior or have a dedicated control. 

I understand not wanting to add a lot to the control template for this. But shouldn't there be another control entirely for pop-up selection controls like copy/paste/select-all, etc.? This is needed in TextBox and other places as well. It likely shouldn't be on TextBlock to begin with.

**Comment by Gillibald** [comment]
> > We need to define a control template with a flyout for text selection, etc. This introduces an overhead we do not want for all TextBlocks.
> 
> That was the same reasoning for separating TextBlock from RichTextBlock originally. Text is so widely used and the vast majority of it is simple strings so we shouldn't be using the heavy inlines and rich text text formatting engine unless it's absolutely necessary. However, you seem to have changed course here and decided performance won't be an issue "Inlines support itself just adds an empty list to each TextBlock."
> 
> > So we either encapsulate text selection support in some attachable behavior or have a dedicated control.
> 
> I understand not wanting to add a lot to the control template for this. But shouldn't there be another control entirely for pop-up selection controls like copy/paste/select-all, etc.? This is needed in TextBox and other places as well. It likely shouldn't be on TextBlock to begin with.
> 
> So what I mean is there would be a `SelectionFlyout` control with it's own template. The `TextBlock` would only create an instance of this and show it if it was selectable. The `SelectionFlyout` would be it's own templated control and usable from `TextBox` and other places.

We could avoid using a control template(theme) by managing the cursor override and the flyout creation in the control itself and not via a style.

The main reason why I moved inlines support to TextBlock itself is for WPF compat. People expect inlines to work inside a TextBlock and usually don't find the dedicated RichTextBlock control.

**Comment by robloo** [comment]
> The main reason why I moved inlines support to TextBlock itself is for WPF compat. People expect inlines to work inside a TextBlock and usually don't find the dedicated RichTextBlock control.

That's what I said at first :) You said no. https://github.com/AvaloniaUI/Avalonia/issues/7982#issuecomment-1143856241

> We could avoid using a control template(theme) by managing the cursor override and the flyout creation in the control itself and not via a style.

Well I have in mind something half like this. The selection flyout (I assume with copy/paste/select-all, etc.) DOES need to have a template that can be re-styled. However, it shouldn't be part of the TextBlock or any other control. These controls will do as you said, manage the cursor overrides and create this flyout only when needed using the template defined elsewhere.

I would really make `SelectionFlyout` it's own flyout like `MenuFlyout` does right now. That would be the cleanest design for everything IMO.

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0025417-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0025492-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0025560-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Review by maxkatz6 — APPROVED** [review]

**Comment by avaloniaui-team** [comment]
You can test this PR using the following package version. `11.0.999-cibuild0025604-beta`. (feed url: https://nuget.avaloniaui.net/repository/avalonia-all/index.json) [PRBUILDID]

**Pull request merged**
