### PR TITLE
ILauncher launch events and intercept

### PR DESCRIPTION
**Pull request by profix898**
## What does the pull request do?
Introduces new events on ``ILauncher`` implementations that triggers when a Uri/file launch occurs. The event arguments provide information about the Uri/file and include a property to cancel the default invocation.

## What is the current behavior?
``ILauncher`` invokes the platform handling of Uri/file directly. No event is raised.

## What is the updated/expected behavior with this PR?
Desired Enhancements
Notification Event: We want to be notified by an event when a URI/file launch occurs.
Interception and Custom Handling: We aim to intercept the call and handle the URI/file launch in a customizable way.

## How was the solution implemented (if it's not obvious)?
The PR adds two events to ``ILauncher``: ``UriLaunching`` and ``FileLaunching``. It also adds an abstract base class implementing the event handling. Existing ``ILauncher`` implementations are updated to derive from that common base instead.
The PR also turns the ``PlatformInfoPage`` in the ``ControlCatalog`` into more general Platform page and exposes Uri launcher for testing (opens Avalonia website). Additional platform features (think MAUI essentials) might be added here in the future?!

## Fixed issues
See #15673

### CODE REVIEW

**Comment by cla-avalonia** [comment]
@profix898,

Please read the following Contributor License Agreement (CLA). If you agree with the CLA, please reply with the following:
```
@cla-avalonia agree
```

<details>
    <summary>Contributor License Agreement</summary>
    
### Contribution License Agreement

This Contribution License Agreement ( **“Agreement”** ) is agreed to by the party signing below ( **“You”** ),
and conveys certain license rights to the AvaloniaUI OÜ ( **“AvaloniaUI OÜ”** ) for Your contributions to
AvaloniaUI OÜ open source projects. This Agreement is effective as of the latest signature date below.

**1. Definitions.**

**“Code”** means the computer software code, whether in human-readable or machine-executable form,
that is delivered by You to AvaloniaUI OÜ under this Agreement.

**“Project”** means any of the projects owned or managed by AvaloniaUI OÜ and offered under a license
approved by the Open Source Initiative (www.opensource.org).

**“Submit”** is the act of uploading, submitting, transmitting, or distributing code or other content to any
Project, including but not limited to communication on electronic mailing lists, source code control
systems, and issue tracking systems that are managed by, or on behalf of, the Project for the purpose of
discussing and improving that Project, but excluding communication that is conspicuously marked or
otherwise designated in writing by You as “Not a Submission.”

**“Submission”** means the Code and any other copyrightable material Submitted by You, including any
associated comments and documentation.

**2. Your Submission.** You must agree to the terms of this Agreement before making a Submission to any
Project. This Agreement covers any and all Submissions that You, now or in the future (except as
described in Section 4 below), Submit to any Project.

**3. Originality of Work.**  You represent that each of Your Submissions is entirely Your 
original work. Should You wish to Submit materials that are not Your original work, 
You may Submit them separately to the Project if You (a) retain all copyright and 
license information that was in the materials as you received them, (b) in the 
description accompanying your Submission, include the phrase &quot;Submission 
containing materials of a third party:&quot; followed by the names of the third party and any 
licenses or other restrictions of which You are aware, and (c) follow any other 
instructions in the Project&#39;s written guidelines concerning Submissions.

**4. Your Employer.** References to “employer” in this Agreement include Your employer or anyone else
for whom You are acting in making Your Submission, e.g. as a contractor, vendor, or agent. If Your
Submission is made in the course of Your work for an employer or Your employer has intellectual
property rights in Your Submission by contract or applicable law, You must secure permission from Your
employer to make the Submission before signing this Agreement. In that case, the term “You” in this
Agreement will refer to You and the employer collectively. If You change employers in the future and
desire to Submit additional Submissions for the new employer, then You agree to sign a new Agreement
and secure permission from the new employer before Submitting those Submissions.

**5. Licenses.**

**a. Copyright License.** You grant AvaloniaUI OÜ, and those who receive the Submission directly
or indirectly from AvaloniaUI OÜ, a perpetual, worldwide, non-exclusive, royalty-free, irrevocable
license in the Submission to reproduce, prepare derivative works of, publicly display, publicly perform,
and distribute the Submission and such derivative works, and to sublicense any or all of the foregoing
rights to third parties.

**b. Patent License.** You grant AvaloniaUI OÜ, and those who receive the Submission directly or
indirectly from AvaloniaUI OÜ, a perpetual, worldwide, non-exclusive, royalty-free, irrevocable license
under Your patent claims that are necessarily infringed by the Submission or the combination of the
Submission with the Project to which it was Submitted to make, have made, use, offer to sell, sell and
import or otherwise dispose of the Submission alone or with the Project.

**c. Other Rights Reserved.** Each party reserves all rights not expressly granted in this Agreement.
No additional licenses or rights whatsoever (including, without limitation, any implied licenses) are
granted by implication, exhaustion, estoppel or otherwise.

**6. Representations and Warranties.** You represent that You are legally entitled to grant the above
licenses. You represent that each of Your Submissions is entirely Your original work (except as You may
have disclosed under Section 3 ). You represent that You have secured permission from Your employer to
make the Submission in cases where Your Submission is made in the course of Your work for Your
employer or Your employer has intellectual property rights in Your Submission by contract or applicable
law. If You are signing this Agreement on behalf of Your employer, You represent and warrant that You
have the necessary authority to bind the listed employer to the obligations contained in this Agreement.
You are not expected to provide support for Your Submission, unless You choose to do so. UNLESS
REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING, AND EXCEPT FOR THE WARRANTIES
EXPRESSLY STATED IN SECTIONS 3, 4, AND 6 , THE SUBMISSION PROVIDED UNDER THIS AGREEMENT IS
PROVIDED WITHOUT WARRANTY OF ANY KIND, INCLUDING, BUT NOT LIMITED TO, ANY WARRANTY OF
NONINFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.

**7. Notice to AvaloniaUI OÜ.** You agree to notify AvaloniaUI OÜ in writing of any facts or
circumstances of which You later become aware that would make Your representations in this
Agreement inaccurate in any respect.

**8. Information about Submissions.** You agree that contributions to Projects and information about
contributions may be maintained indefinitely and disclosed publicly, including Your name and other
information that You submit with Your Submission.

**9. Governing Law/Jurisdiction.** This Agreement is governed by the laws of the Republic of Estonia, and
the parties consent to exclusive jurisdiction and venue in the courts sitting in Talinn,
Estonia. The parties waive all defenses of lack of personal jurisdiction and forum non-conveniens.

**10. Entire Agreement/Assignment.** This Agreement is the entire agreement between the parties, and
supersedes any and all prior agreements, understandings or communications, written or oral, between
the parties relating to the subject matter hereof. This Agreement may be assigned by AvaloniaUI OÜ.


*AvaloniaUI OÜ dedicates this Contribution License Agreement to the public domain according to the Creative Commons CC0 1.*

</details>

**Comment by profix898** [comment]
@cla-avalonia agree

**Comment by robloo** [comment]
In my opinion this isn't the correct approach. ILauncher is clean and simple as is and works for most apps. If you need to customize a service, then you need to provide your own ILauncher implementation. That's the whole beauty of using services.

Inside your implementation you can do what you want first, raise events, then invoke the system ILauncher.

That said, I'm not sure we have a way of registering service overrides. We probably should support that.

**Comment by maxkatz6** [comment]
I agree with @robloo.

Looking at your original issue:
> Previously I had a custom Hyperlink(button) and URI launcher implementation. Having the launcher in Avalonia directly means that there will be third-party controls using ILauncher. So it would be great to have some flexibility to intercept, rewrite or handle Uri/file launch calls.

Typically, such scenario could be solved by having a special routed event on a Hyperlink control. Like, `UriNavigating`. Control would raise this event, while control consumers can handle it. If it wasn't handled - control launch the uri by itself.

**Comment by profix898** [comment]
Thanks for your feedback. But if I'm not mistaken, you can't do any such thing. Since V11 the service locator (``AvaloniaLocator``) is internal. You can't register additional services nor can you override existing ones. For that reason, you also can't modify Avalonia "core" services (by means of providing alternate implementations).

More specifically for this case, the launcher implementations are hardwired for the platform-specific ITopLevelImpl, e.g. ``AndroidLauncher`` is directly "embedded" in ``Avalonia.Android.Platform.SkiaPlatform.TopLevelImpl``. It does not go through the service locator at all.

**Comment by maxkatz6** [comment]
> You can't register additional services nor can you override existing ones

That point was about a service in your application logic, not a replacement for Avalonia service.

**Comment by robloo** [comment]
So condensing a few ideas:

 1. It's best to have your own services defined in your application (use `Microsoft.Extensions.DependencyInjection`). These services would include an `ILauncher` implementation like this PR where you can intercept and do whatever you want. Inside that service you would call Avalonia's built-in service.
 2. `HyperlinkButton` can be customized by just handling the `Click` event and `IsVisited` properties yourself. This allows you to "intercept" the click and route it to your own launcher service first. Personally, I'm not against adding a cancellable `Navigating` event to `HyperlinkButton` in the future though.
 3. It would be great if we could override Avalonia's own services implementation at some point in the future. Not sure when/if that will be supported though.

**Comment by maxkatz6** [comment]
Closing this PR as per https://github.com/AvaloniaUI/Avalonia/issues/15673#issuecomment-2257127449
Let me know if you have any questions on redefining HyperlinkButton behavior.

**Comment by robloo** [comment]
Note that `IsVisited` can be manually set as well to indicate the URL has been navigated to visually.

I still think we should have a way of overriding core Avalonia services by an application. However, having an app-level service provider that does its own handling falling back to Avalonia's services has proven to be a solid approach so far.

**Pull request closed without merging**
